### ISSUE TITLE
Windows guest  OS does not execute or display any output

### ISSUE THREAD

**Issue by raniemi** [mitchellh/packer#1003]
(The original issue can be found on joefitzgerald/packer-windows#46)

It appears that `puppet-masterless` is failing silently or not being executing at all when trying to provision a new Windows guest OS using puppet. This issue was discovered while attempting to provision a Windows 2008 R2 SP1 x64 guest OS using the sample template found in the [packer-windows](https://github.com/ranl/packer-windows) project.  

A general test case would be to:
* have packer 0.5.2 and VMWare Fusion installed (have not tried with VirtualBox)
* reuse one of the Windows 2008 packer templates from [packer-windows](https://github.com/ranl/packer-windows)
* replace the `scripts/chef.bat` reference with `scripts/puppet.bat`
* add your own `puppet-masterless` provisioner 
* you should see that `execute_command` is echoed in stdout, but nothing else is displayed (even with debugging turned on and PACKER_LOG=1)

More details can be found at joefitzgerald/packer-windows#46.

**Comment by michaeltlombardi** [comment]
Can this issue be closed? The upstream issue has been.

**Comment by rickard-von-essen** [comment]
Closing since no reply
