### ISSUE TITLE
Puppet-masterless for Windows module-paths separator character

### ISSUE THREAD

**Issue by dylanmei** [mitchellh/packer#1007]
On a Windows guest the [PathListSeparator](http://golang.org/pkg/os/#pkg-constants) character is `;` but the puppet-masterless provisioner [is written to use](https://github.com/dylanmei/packer/blob/master/provisioner/puppet-masterless/provisioner.go#L261) `:`.

This is a problem when specifying more than one module-path. Puppet will not complain about the correctness of the `--modulepath` argument, but will be unable to locate any modules.

It seems the provisioner may need to know its running against Windows in order to fill the `execute_command` template correctly.

**Comment by michaeltlombardi** [comment]
The upstream for this is closed and there seems to be a fix from @pleschev in 2014 addressing the issue. Can this be updated or closed?

**Comment by rickard-von-essen** [comment]
Closing since this is most likely working since long.
