### ISSUE TITLE
Chef provisioner fails without root

### ISSUE THREAD

**Issue by benlangfeld** [mitchellh/packer#1054]
```
<snip>
    virtualbox-iso: Preparing...                ########################################### [100%]
    virtualbox-iso: 1:chef                   ########################################### [100%]
    virtualbox-iso: Thank you for installing Chef!
    virtualbox-iso: Creating directory: /tmp/packer-chef-client
    virtualbox-iso: Uploading validation key...
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error copying validation key: scp: /tmp/packer-chef-client/validation.pem: Permission denied

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error copying validation key: scp: /tmp/packer-chef-client/validation.pem: Permission denied

==> Builds finished but no artifacts were created.
make: *** [vm] Error 1
```

`ChefClient.createDir` uses sudo to create the `StagingDir`, creating it with owner/group `root:root`, but then `packer.Communicator` uses the user defined in the manifest to upload the validator key, which fails if that user is not `root`.

I think the `prevent_sudo` option should probably be applied in `createDir` to deal with this. Would this be an acceptable solution?

**Comment by memelet** [comment]
I too get permission errors like @jslusher. Why is it just he and I? @tehmaspc, why do you not get these errors?

**Comment by tehmaspc** [comment]
@memelet 

you have to do this first:
#: gem install magic


j/k - maybe default behavior has changed - what I would try is to launch the build in packer with debug on and tell it to do into interactive mode while dumping the temporary ec2 instance key. I used this to login to the ec2 instance that gets created to view the environment when I had issues in the past.

I haven't touched packer w/ chef for a while - if i get some time this wkend I could take a look - but try the steps above.

cc @jslusher 

cheers,

**Comment by memelet** [comment]
Thanks @jslusher 

While a bit smelly, this is working:

```
#!/bin/bash

#
# From https://github.com/mitchellh/packer/issues/1054
#

sudo mkdir -p /etc/chef
sudo chown -R ubuntu.ubuntu /etc/chef

mkdir /tmp/packer-chef-client
chmod 0755 /tmp/packer-chef-client

sudo mkdir -p /etc/chef/ohai/hints
sudo touch /etc/chef/ohai/hints/ec2.json

sudo mkdir -p /var/log/chef

sudo apt-get update && sudo aptitude -y safe-upgrade

exit 0
```

I spend way too much time debugging chef as it is to have any desire to narrow this down ;-)

**Comment by binlialfie** [comment]
still having the same error, even with @memelet script.  if I trying to to do apt-get upgrade -y, the packer stuck with interactive package selection purple screen.

any updates on this please?

**Comment by rbowlby** [comment]
Seems like most amazon-ebs images make use of a non-root user. Also seems like it's unlikely someone would ever use chef-client without a validator. So I think it's safe to assert that the chef-client provisioner fails in the most default of use cases. Case in point, this is my very first hour using packer and I'm already creating a shell provisioner to deal with this issue. :(

I believe having some logic that appropriately modifies dir perms ahead of scp if user is not root would suffice?
+1

**Comment by mujina** [comment]
Come up against these issues today related to permissions and found my way here. My personal scenario was spinning up EC2 instances running Amazon Linux with the default user "ec2-user". After reading the comments above and @memelet 's comments regarding debugging I opted to use a bind mounted which seems a fairly clean solution. 

    {
      "type": "shell",
      "inline": [
        "sudo mkdir /etc/chef",
        "mkdir /tmp/packer-chef-client",
        "chmod 0755 /tmp/packer-chef-client",
        "sudo mount -o bind /tmp/packer-chef-client /etc/chef"
      ]
    },

**Comment by ameir** [comment]
I submitted PR https://github.com/mitchellh/packer/pull/2027 which addresses this issue.  The client key will be created in the staging directory by default, unless otherwise specified.  To me, this is the cleanest solution, versus the workarounds described above.

**Comment by tehmaspc** [comment]
Well any 'fix' is better than any workaround; but there wasn't any recourse prior :)

**Comment by mitchellh** [comment]
Should be fixed by #2255.

**Comment by acqant** [comment]
So what do you do if you want to keep the machine registered with chef?  I used @mujina fix and /tmp/packer-chef-client and /etc/chef are gone.  Do I have to copy everything from /tmp/packer-chef-client to /etc/chef at the end of the chef provision?

Bash resource: setup permissions
chef resource: provision
Bash resource: move files to /etc/chef ??

**Comment by acqant** [comment]
@mitchellh 
Even with 0.8.2 and using staging dir I get the error about registering the node not being able to write to /etc/chef.

Is this fix supposed to handle /etc/chef too?
