### ISSUE TITLE
Allow ssh agent forwarding in packer builder

### ISSUE THREAD

**Issue by WyseNynja** [mitchellh/packer#1066]
My packer build user has an SSH key I want to use to clone some git repos.

For now, I am copying the id_rsa onto the box and using it, but I would much prefer to use ssh agent forwarding.

Is this possible?  I only see options for ssh_username, ssh_port, and ssh_timeout.

**Comment by kgilpin** [comment]
+1

**Comment by noodlehaus** [comment]
Have posted on the google group an issue that could be related to this, as currently, all my SSH traffic goes through a tunnel/proxycommand:

https://groups.google.com/forum/#!topic/packer-tool/kC0peY9Qamo

**Comment by bamdadd** [comment]
+1

**Comment by jszwedko** [comment]
:+1:

**Comment by arturhoo** [comment]
:+1:

**Comment by derek-adair** [comment]
+1

**Comment by bwlz** [comment]
:+1:

**Comment by invisibleroads** [comment]
:+1:

**Comment by invisibleroads** [comment]
One workaround is to use "git archive --output ../xyz.tar.gz master" and then use the [file provisioner](https://www.packer.io/docs/provisioners/file.html) to upload the repository archive to the server.

**Comment by mitchellh** [comment]
Done!

**Comment by invisibleroads** [comment]
Cool
