### ISSUE TITLE
Packer fails when missing node_name

### ISSUE THREAD

**Issue by bklang** [mitchellh/packer#1118]
This is following up on #1100.

The field `node_name` is described as "optional", though the build fails without it because knife is unable to remove the chef client from the chef server after a successful configuration run.  This results in the VM being destroyed.

I can think of a couple of ways to address this, but I'm not sure which you prefer:

* Set the default `node_name` to `localhost`, which appears to be what chef-client (or perhaps just the guest OS) defaults to

* Alternatively (and this is probably safer) make `node_name` a required attribute

**Comment by mitchellh** [comment]
I think this is a dup of #1295. This should get fixed with that.
