### ISSUE TITLE
Variable interpolation in `builders:output_directory`

### ISSUE THREAD

**Issue by beporter** [mitchellh/packer#1172]
If I wanted to consolidate builds into their own sub-directory, say, `output/` (relative to the `packer.json` file), I don't seem to be able to use a builder's `{{.Name}}` in the `output_directory` value.

For example, this snippet

```json
{
	"builders": [
		{
			"type": "vmware-iso",
			"name": "sample-vmx",
			"guest_os_type": "ubuntu-64",
			"output_directory": "output/{{.Name}}",
		}
	]
}
```

...causes packer to create a directory named `output/<no value>/` where I would expect `output/sample-vmx/`. I assume I am doing something wrong. The docs say ["some configurations have special local variables that are available only for that configuration"](http://www.packer.io/docs/templates/configuration-templates.html) and ["By default this is "output-BUILDNAME" where "BUILDNAME" is the name of the build."](http://www.packer.io/docs/builders/vmware-iso.html) but I can't find a reference guide anywhere that shows **which** settings allow interpolation, which don't, and what values are allowed when the setting allows it.

Is there **not** a way to override the _pattern_ for the output directory while maintaining the "BUILDNAME" style replacement? Shouldn't this be interpolate-able?

**Comment by mitchellh** [comment]
I believe this is fixed.
