### ISSUE TITLE
Set `virtualhw.version` to the version installed

### ISSUE THREAD

**Issue by rasa** [mitchellh/packer#1191]
Several have asked for Packer to automatically set the `virtualhw.version` setting in the .vmx file to the version of the VMWare Workstation/Fusion/Player used during the build.

In the rare instance that someone wants to build for an older version (they have VMWare WS 10 installed, but want to build for WS 9/Player 5), we could add a `version` option to the template. For example, adding
`"version": "9",`
would set
`virtualhw.version = "9"`
in the .vmx.

The default value for `version` could be `default`, which would be the version of the VMWare Workstation/Fusion/Player installed.

For reference, the values for `virtualhw.version` can be found [here](http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1003746)

**Comment by mitchellh** [comment]
I want to note that the "Version" setting can be used in templates to manually override this.

**Comment by dragon788** [comment]
@mitchellh Do you have an example of using 'Version'? I'm horrible at figuring this stuff out without it (even though the code is clean and incredibly well commented, it takes me a while to grok it).
