### ISSUE TITLE
Allow remote OVF downloads

### ISSUE THREAD

**Issue by toddsampson** [mitchellh/packer#1195]
Any plans to allow for remote ovf file downloads with an ovf_url, along with the corresponding vmdk, as you did with iso_url?

I want to send the team a packer config that uses a hosted ovf base box, makes some customizations using provisioning scripts, and then builds a Vagrant box.

**Comment by russroy** [comment]
+1

**Comment by richardzone** [comment]
+1

**Comment by derektamsen** [comment]
+1

**Comment by gamename** [comment]
+1

**Comment by cbednarski** [comment]
I think this should be fairly easy to do with [go-getter](https://github.com/hashicorp/go-getter), which can support getting all the bits out of a zip file.

**Comment by kotatsu360** [comment]
+1

**Comment by artburkart** [comment]
To @cbednarski's point, what would the implementation of this look like?

I could see `source_path` being overridden, so it can accept a url to an ova archive file, but an ovf seems less doable unless some opinionated convention is selected.

**Comment by cbednarski** [comment]
@artburkart I think for the ovf case we would say it must be in a tar or zip, and it will be extracted after we download it. You're right though that without an archive of some kind there is no way to know which files are supposed to be included.
