### ISSUE TITLE
Packer.exe doesn't go away after Ctrl+C

### ISSUE THREAD

**Issue by CMCDragonkai** [mitchellh/packer#1210]
On Windows, during a long packer execution, if you hit Ctrl+C the packer.exe doesn't go away. I have to manually task kill the packer.exe.

Is there a way to make sure all the packer processes die when I run Ctrl+C or does that only kill the current packer process?

**Comment by sethvargo** [comment]
Hi @CMCDragonkai 

I am sorry you are having issues with Packer. Which version of Packer are you using (`packer version`)?

**Comment by mitchellh** [comment]
Closing due to lack of response and due to the time period it might be fixed.
