### ISSUE TITLE
vmware-iso with remote esx5: file-based iso_url fails to upload

### ISSUE THREAD

**Issue by rbrewer123** [mitchellh/packer#1221]
Running packer 0.6.0 on 64-bit Linux.  When I initiate a vmware-iso build to a remote esx5 host (ESXi 5.1) I get a failure while uploading the ISO when I use a file:///foo/bar/baz.iso URL.  If I change it to an http URL (http://host/foo/bar/baz.iso) it works.  For the file-based failure, it appears to upload about 32 MB of the ISO and then error out.

**Comment by michaeltlombardi** [comment]
Should this issue have been closed by #1479?

**Comment by rickard-von-essen** [comment]
This is working since long.
