### ISSUE TITLE
Microsoft Azure builder

### ISSUE THREAD

**Issue by euskadi31** [mitchellh/packer#1223]
Can you add support for Microsoft Azure?

Thx

**Comment by errordeveloper** [comment]
:+1:

**Comment by sethvargo** [comment]
https://github.com/mitchellh/packer/pull/1689

**Comment by JamieCressey** [comment]
+1

**Comment by spuder** [comment]
Has microsoft already done this? https://github.com/Azure/packer-azure

**Comment by paulmey** [comment]
Support for the Azure Resource Management API's is now merged in the Packer main repo: https://www.packer.io/docs/builders/azure.html
The 'old' (service management) API's will still be supported through plugins in the above repository.

**Comment by rickard-von-essen** [comment]
This is included in packer since Packer `v0.1.0`.
