### ISSUE TITLE
floppy_files will crash packer if folder contains .DS_Store file

### ISSUE THREAD

**Issue by trodemaster** [mitchellh/packer#1240]
This seems simple to reproduce. 
1. Copy files including a mac .DS_Store file into a folder
2. Use that folder as part of a floppy_files when building a windows VM
3. Run packer and get this crash https://gist.github.com/trodemaster/92f44bbc67f8fe9a9004

This is on packer version 0.6.0 and host OS is 10.9.3. Let me know if more detail is needed I can capture a debug log.

**Comment by mitchellh** [comment]
Fixed upstream
