### ISSUE TITLE
vmware builder has hardcoded scsi/lsilogic controller

### ISSUE THREAD

**Issue by routelastresort** [mitchellh/packer#1242]
Currently, the VMware builder (```iso/step_create_vmx``` and ```vmx/step_clone_vmx```) only supports SCSI disks.  I just made custom -ide versions of the builders for myself, but this may impact other people as well.  (specifically, vApps with IDE disk with no serious I/O needs).  Yes, SCSI seems to be the de-facto standard (I've seen it hard-coded in many other cloud/virtualization tools), but it definitely may be impacting other users.

**Comment by mauilion** [comment]
This is still busted for vmware-iso. Can you reopen to address? Basically we need something like what was described in the description. A diskinterfacetype flag that vmware-iso / step_create_vmx will honor.

**Comment by mauilion** [comment]
For others searching for this. I found that you can provide your own vmx template and in that template configure the disk to use sata or whatever you want.

**Comment by mitchellh** [comment]
Going to say fixed due to @mauilion's comment. A good workaround. if someone submits a PR to add a choice for Packer to automatically set IDE vs SCSI, I'd accept that as well.

**Comment by splashx** [comment]
Definitely not fixed as vmware-iso has nothing to do with vmware-vmx in the user's perspective.

**Comment by mcandre** [comment]
+1, as MINIX lacks support for SCSI drives, so MINIX guests are therefore incompatible with VMware provider until packer JSON's can successfully specify IDE rather than SCSI.
