### ISSUE TITLE
Allow setting volume type for root volume during baking

### ISSUE THREAD

**Issue by renat-sabitov** [mitchellh/packer#1266]
Amazon came up with a new EBS volume type which potentially can speed up baking

http://aws.amazon.com/blogs/aws/new-ssd-backed-elastic-block-storage/

It'd be great to allow setting up ebs volume properties for the boot volume during bake. We can name it "run_block_device_mappings"

**Comment by mitchellh** [comment]
Should be fixed with `launch_block_device_mapping`

**Comment by ZillaG** [comment]
I get using an AWS Ubuntu base AMI

==> amazon-ebs: Error launching source instance: InvalidBlockDeviceMapping: Invalid device name /dev/sda
==> amazon-ebs: 	status code: 400, request id: c3967b11-f72a-49e2-9dce-e242caa1eb8d
