### ISSUE TITLE
Use godep (or similar)

### ISSUE THREAD

**Issue by cstrahan** [mitchellh/packer#1268]
I'd like to package `packer` for [NixOS](http://nixos.org/), but to do so I need to reference specific commits (Nix packages strictly enforce deterministic builds, so I can't just "go get" the deps). Would it be possible to add a Godep file for this project, much like what was done for Consul?

**Comment by thypon** [comment]
bump +1, i really appreciate this one to easy the packaging hassles.

**Comment by mitchellh** [comment]
We're waiting for GopherCon on word for Go's official solutioln (which Godep plans to implement). Until then, a "wontfix". Sorry.
