### ISSUE TITLE
"external command" generic post-processor ?

### ISSUE THREAD

**Issue by renaudguerin** [mitchellh/packer#1312]
Hi,

I'm using the amazon-ebs builder and I'd like to automatically deploy AMI artifacts from Packer to EC2.

To achieve that currently, I'd have to call Packer from a clumsy wrapper script that :
- needs to implement its own "-only" logic if it's going to have some flexibility, and pass this on to Packer.
- parses Packer's output and looks for artifacts, handles any failures, including partial failures in case there are several targets.
- feeds any successful artifacts into deployment scripts.

That's a fair amount of logic, parallelism and error-checking that's already implemented in Packer : it would be so much better to have this as a Packer post-processor instead.

There's already a dictionary of artifact output values (builder-id, id, string, files-count ...) in the machine readable output, all that would be required is the ability to construct an external command line from these and other variables.

Any chance this can be done ?
Thanks !

**Comment by mitchellh** [comment]
Dup of #644
