### ISSUE TITLE
SELinux issue with directory mounts in docker

### ISSUE THREAD

**Issue by rlpowell** [mitchellh/packer#1324]
See https://bugzilla.redhat.com/show_bug.cgi?id=1117721 ; the relevant bit:

directories that you are mounting into the container (i.e. /tmp/packer-docker485478580 ) need to have svirt_sandbox_file_t as their label

**Comment by mitchellh** [comment]
I haven't been able to get a good setup to test this. It would be a great help for you (or anyone else) to please submit a PR for this. I attempted it a few times but I'm not confident in my implementation. No one else has made an issue about this so I wonder if its not very widespread either, so closing this for now until a PR comes in.

**Comment by rohanpm** [comment]
Since you had some doubts about how common this may be, I'd like to point out that I also hit this issue on my first attempt at using packer.

The error message is unhelpful, it wouldn't surprise me if many users would be unable to diagnose this as an SELinux issue.

```
==> docker: Starting docker container...
    docker: Run command: docker run -v /tmp/packer-docker824144154:/packer-files -d -i -t docker-registry.example.com/redhat/rhel6 /bin/bash
    docker: Container ID: 652efea908c8799458f6b089e2f413cc2afe4c625423e7e05f6e1dc85d5bcd0a
==> docker: Uploading ansible/roles/setup/distro/repos/files/redhat-6/ => /tmp/et/repos/rhel6/
==> docker: Killing the container: 652efea908c8799458f6b089e2f413cc2afe4c625423e7e05f6e1dc85d5bcd0a
Build 'docker' errored: Upload failed with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> docker: Upload failed with non-zero exit status: 1

==> Builds finished but no artifacts were created.
```

(Somewhere under the hood, permission must have been denied to something, but the error message doesn't communicate it.)

**Comment by dmiles96** [comment]
I'm running into this issue, now, as well. Is there a fix for this coming?

**Comment by awalker125** [comment]
I hit this today. I've done a PR #4843 for this. I've just added :Z to the volume mount so the files can be copied from /packer-file into the location ansible uses. I'm not sure if it will be accepted but its working for me.
