### ISSUE TITLE
qcow2/vmdk qemu builders

### ISSUE THREAD

**Issue by routelastresort** [mitchellh/packer#1366]
Similar to `virtuabox-ovf` or `vmware-vmx`, (with boot command support) this would help automate configuration of vApps or appliances in their distributed form.  This seems like the best entry point for making something Xen/KVM/OpenStack/CloudStack/etc automation-friendly.  Once images are built properly, they could be further customized specific to environments or use cases, e.g. what the current OpenStack builder does today.  I'm working on a pull request for this now...

**Comment by priteau** [comment]
Was there more work done on this issue? I would like to use Packer to customize existing QEMU/KVM images, such as the Fedora or CentOS cloud images, instead of building them from scratch.

**Comment by cmluciano** [comment]
@priteau if you have these uploaded to your openstack instance, you can use the [openstack builder](https://www.packer.io/docs/builders/openstack.html) to modify existing machines.

**Comment by routelastresort** [comment]
I've had some more time to mess with this, and the qemu builder seems to work with .qcow2 as a source input (or anything else that qemu supports!).  Here's an example of what you need (don't use Ubuntu cloud images, as they need cloud-init-fed credentials -  I was just testing it out:

```json
  "builders": [
    {
      "type": "qemu",
      "disk_image": "true",
      "iso_checksum": "e49d43f60f32590c9dbd0dbb40b71707ec7ba2239531556bb4fe4097e6d1bac4",
      "iso_checksum_type": "sha256",
      "iso_url": "images/ubuntu-14.04-server-cloudimg-amd64-disk1.img",
      "ssh_username": "ubuntu"
    }
  ]
```

On a Mac, you can add the following just to test, assuming you have qemu installed through homebrew, etc.:
```
     "accelerator": "none",
      "headless": "true",
```

I'll test this more in detail, but it looks like the docs can just be updated to reflect the support for multiple source image types.  I was about to split out the builder into common, iso, and "disk" (anything supported by qemu) types.  Either way, this really shows the awesome flexibility of qemu support from command line arguments / qemuargs :+1: 

/cc @priteau

**Comment by jfbibeau** [comment]
@routelastresort Thanks for your post. Definitely can confirm the QEMU builder works with a QCOW2 when setting `disk_image` set to `true`. It can even do a disk resize on the fly, brilliant. I'll see if I can submit a PR to update the docs.
