### ISSUE TITLE
Support daily build iso images for iso_checksum

### ISSUE THREAD

**Issue by dschmitz** [mitchellh/packer#1368]
Hi,

it would be pretty cool if it is possible to specify a an URL for the iso_checksum. This way packer could handle iso images changing on daily basis. For the moment it is only possible to specify none which yields in downloading the image everytime for a day. Or by specifying a checksum which makes it necessary to retrieve the checksum everyday manually or by some external script.

Regards
David

**Comment by vtolstov** [comment]
may be i can write pull request for this, because i'm already have many images and i'm bored with manually getting sha sums.

**Comment by mohae** [comment]
If this is about distribution supplied images and checksums, it's a little more complicated than just specifying the checksum url for some distros. The image name can change, e.g. CentOS 7 and LTS versions of Ubuntu. For these, both the image url and the image name will change, which will also affect finding the correct checksum on the checksum page.

I am working on a tool to generate Packer images and have had to work through this for the distros I currently support. One of my original motivations was not having to keep the ISO info, including checksum, up to date and not having to look them up in the first place.

If this sort of functionality is something that is desirable for Packer, I'd be happy to contribute.

**Comment by dragon788** [comment]
This would be incredibly useful in cases of a software repository like Artifactory (or BinTray) where their software allows access to the md5 sums simply by appending the type of checksum required to the URL (if enabled). For example we access a "built" ISO at http://my.artifactory.mycompany.com/isos/ubuntu-daily-build-2015-06-23.iso and the md5 by simply appending .md5 to the URL.

**Comment by vtolstov** [comment]
I think about something like this: when in checksum filed user inputs http:// we download file and parse it (all sums files have sum "space" filename) after getting needed sum we simple check downloaded file.
@mitchellh what do you think?

**Comment by artburkart** [comment]
Could someone explain to me the difference between this issue and the the PRs that added `iso_checksum_url` support?

https://github.com/mitchellh/packer/pull/3162
https://github.com/mitchellh/packer/pull/2744

**Comment by vtolstov** [comment]
You can specify remote url and remote checksum file and don't need to specify checksum in packer template

**Comment by vtolstov** [comment]
@rickard-von-essen or @mwhooker can you close this, as it already implemented.

**Comment by rickard-von-essen** [comment]
Already implemented, see above. 👍
