### ISSUE TITLE
Invalid region or lookup failure error with Digital Ocean builder

### ISSUE THREAD

**Issue by philososaur** [mitchellh/packer#1416]
I am encountering an "Invalid region or lookup failure" with any combination of region slug or name, and also when trying to use the deprecated region_id setting.  

> digitalocean: Error creating droplet: Invalid region or lookup failure: 'nyc1': Unknown region 'nyc1'

**Comment by ryanuber** [comment]
@philososaur I think DO has discontinued launching droplets in nyc1 altogether at this point. I noticed a similar issue in December, and we switched the default region to "nyc3". Can you give this another go and see if you get the same error? I've been using packer with DO regularly and haven't seen this one come up again.

**Comment by vtolstov** [comment]
I think we need to modify DO builder to get all regions and if user not specify it, randomly get available region. SO we don't need to hard code region name.

**Comment by vtolstov** [comment]
Please, try this patch: https://github.com/mitchellh/packer/pull/1882

**Comment by mitchellh** [comment]
Fixed
