### ISSUE TITLE
{{cmd `x`}} function returns the output returned by executing x, for use in setting user variables

### ISSUE THREAD

**Issue by rhbecker** [mitchellh/packer#1435]
Drawing inspiration from how the following are supported ...

1. ##### env function

   ```go
   // {{env `EXAMPLE_ENVIRONMENT_VAR`}}
   func templateEnv(n string) string {
	   return os.Getenv(n)
   }
   ```
1. ##### pwd global function

   ```go
   // {{pwd}}
   func templatePwd() (string, error) {
   	   return os.Getwd()
   }
   ```

... I'd like to propose something like the following for your consideration ...

##### cmd function

   ```go
   import (
	"os/exec"
   )
   // {{cmd `basename $PWD`}}
   func templateCmd(n string) string {
	   return exec.Command(n).Output()
   }
   ```

... Idea being that a user variable could be set to whatever is output by any number of commands a template writer could dream up. See go docs for [func (*Cmd) Output](http://golang.org/pkg/os/exec/#Cmd.Output).

**Comment by mitchellh** [comment]
I agree with someone... here or some other issue, that I dislike the idea of Packer templates themselves potentially subprocessing to arbitrary commands, except under the explicit config of something like a local shell provisioner.

For this reason, I agree that the commands should be executed externally and passed in as variables...
