### ISSUE TITLE
Puppet manifest_file must point to a file

### ISSUE THREAD

**Issue by levilovelock** [mitchellh/packer#1446]
In the new version of puppet import statements are being deprecated. It is recommended instead that you point the puppet masterless to a directory rather than a file.

At the moment packer has a requirement that manifest_file must point to a file. Could we allow manifest_file to point to a directory and handle it from there?

https://docs.puppetlabs.com/puppet/latest/reference/lang_import.html

**Comment by sethvargo** [comment]
Fixed in https://github.com/mitchellh/packer/pull/1771
