### ISSUE TITLE
Provisioning multiply and differently per type of builder.

### ISSUE THREAD

**Issue by gtmtech** [mitchellh/packer#1449]
Suppose I want to create 2 types of VM as a result of a packer build - 

* box1 - configured with a vagrant user and all the vagrant goodness, to allow me to use it within a Vagrantfile
* box2 - configured without vagrant, because I dont want vagrant on all my other environments.

I might create a provisioning setup_vagrant.sh, and only apply it to the virtualbox-iso type. But then how can I also output a virtualbox-iso which doesn't have vagrant set up on it as well for other uses? It seems provisioners are tied to "types" of builder, whereas I think this would be better served by allowing named builders, which may have the same type, and tying provisioners to the names instead.

As it stands, I seem to need to require 2 different .json packer files (w/ lots more duplication) to achieve the above, unless there is something obvious I am missing.

Hope that makes sense

**Comment by sethvargo** [comment]
I'm going to close this due to no reply, but please let me know and we can re-open it.

**Comment by gtmtech** [comment]
Apologies @jasonberanek @sethvargo I used your solution in the end so thanks.
