### ISSUE TITLE
Vpshere post-processor fails with "Unknown artifact type, can't build box: mitchellh.vmware-esx"

### ISSUE THREAD

**Issue by bemeyert** [mitchellh/packer#1457]
Hi all,

I wanted to post this first to the ML. But my posts don't appear although I am subscribed.

I'm trying to use the Vsphere post-processor and always and up with a failure([see Gist](https://gist.github.com/bemeyert/9b9d37556efa870c228e) ). My guess is that the build artifact gets deleted, before it is even uploaded. And this although I defined "keep_input_artifact".

My post-processor configuration looks like this:

```json
  "post-processors": [
    {
      "type": "vsphere",
      "keep_input_artifact": true,
      "username": "{{ user `vsphere_user` }}",
      "password": "{{ user `vsphere_password` }}",
      "vm_name": "{{ user `box_name` }}",
      "host": "{{ user `vsphere_host` }}",
      "datacenter": "{{ user `vsphere_dc` }}",
      "cluster": "{{ user `esx_host` }}",
      "resource_pool": " "
    }
  ]
```

I verified the values by manually uploading an OVF-file with "ovftool".

Does anybody have an idea of what's going on?

Cheers, Shorty

**Comment by icnocop** [comment]
@rkarimuthu, no, it's not in the official 0.7.5 release.

See https://github.com/mitchellh/packer/pull/1921 for the latest thread regarding this issue.

@higebu produced an unofficial release as indicated here:
https://github.com/mitchellh/packer/pull/1577

Basically, it can be found here:
https://github.com/higebu/packer/releases/tag/v0.7.5.higebu

**Comment by higebu** [comment]
I reopened the p-r for this issue:
https://github.com/mitchellh/packer/pull/1921

And the latest version of binaries are here:
https://github.com/higebu/packer/releases/tag/v0.7.5.higebu5

**Comment by vladimirondrus** [comment]
Hi all,

We are using builder:
"type": "vmware-iso",
"remote_type": "esx5"

now we want to use vsphere post processor to create template in vcenter server.

Is this suported in latest packer 0.8.1 version?
or this is somehow working only in higebu branch?

Regards,
Vladimir Ondrus

**Comment by mihai-satmarean** [comment]
First: Thanks a lot for the great software - it change the face of sysadmin.
I was also under the impression that you can build using any builder and afterwards the ovftool will convert your machine and upload to vsphere.
I was trying to build with virtualbox-iso and post process with vsphere.
Is this supported? 
Sorry I could not found some hint like which post processors are compatible with which builders.

**Comment by kaltokri** [comment]
jasonberanek commented on 3 Sep 2014:
At minimum, we should add documentation to make clear the behavior is different if building from the esxi builder.

I didn't find any information about it in documentation and spend a whole day searching a solution.
Please add hint to documentation soon.

**Comment by Sher-Chowdhury** [comment]
My team and I also spen't a couple of days trying to get this to work before discovering this thread. 

I would be grateful if you could clarify in the documentation that you can't use the vSphere Post-Processor when building Building on a Remote vSphere Hypervisor.
