### ISSUE TITLE
Improve Error in "packer validate" When Required File is Missing

### ISSUE THREAD

**Issue by tomwheeler** [mitchellh/packer#1474]
Each member of our team uses Packer templates stored in git, but some of the paths they reference are defined in environment variables because they vary on each person's computer. Here is an excerpt of such a template:

```
{
  "variables": {
    "var_out_dir": "{{env `VAR_OUT_DIR`}}",
    "var_vmx_file": "{{env `VAR_VMX_FILE`}}",
  },
  "builders": [
	{
	  "type": "vmware-vmx",
	  "source_path": "{{user `var_vmx_file`}}",
	  "output_directory": "{{user `var_out_dir`}}"
```

When I use "packer validate" on that template, I get the following error:

```
Template validation failed. Errors are shown below.

Errors validating build 'Example'. 1 error(s) occurred:

* source_path is required
```

This is confusing because, as you see, the template does correctly define a variable called source_path. The syntax of this template is correct, and I am able to successfully build a working VM using it.

Upon further investigation, I found that "packer validate" seems to be doing a stat on the file at the referenced path, and since the environment variable was not defined at the time I ran "packer validate" (we set this in a shell script that runs "packer build"), this message is trying to indicate that the path is unspecified"

I think it would be more clear in this case if the error said something like "source_path refers to a non-existent file" (or perhaps even "source_path refers to a non-existent file; if this is defined by a variable, the variable might currently be unset")

**Comment by mitchellh** [comment]
Flxed
