### ISSUE TITLE
Debug should prompt between provisioner scripts

### ISSUE THREAD

**Issue by jantman** [mitchellh/packer#1475]
Using v0.6.0 at least, running with `debug` does not pause/prompt between each provisioner, but between all of them. This is really the only part of `-debug` that matters to me...

**Comment by dpetzel** [comment]
I ran into this as well using 0.8.6. I would also like to see it pause between each provisioner.

**Comment by solarce** [comment]
This would be super dope to have.

**Comment by rickard-von-essen** [comment]
This is a bit tricky to implement with the current design so don't hold your breath. But I agree it would be useful.

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
