### ISSUE TITLE
amazon-chroot copy_files and copy_files_cleanup

### ISSUE THREAD

**Issue by tjbaker** [mitchellh/packer#1490]
http://www.packer.io/docs/builders/amazon-chroot.html

The example in the docs for copy_files cites copying resolve.conf from the packer host to ensure you have dns resolution in the chroot volume.  When I look at the copy_files step it looks like it does an rm -f on the list of files in the cleanup. 

https://github.com/mitchellh/packer/blob/master/builder/amazon/chroot/step_copy_files.go#L75

```
// StepCopyFiles copies some files from the host into the chroot environment.
//
// Produces:
//   copy_files_cleanup CleanupFunc - A function to clean up the copied files
//   early.
```

My usecase requires copying over a more permissive /etc/sudoers from the packer host to set !requiretty  to allow "sudo" as the command_wrapper (just like the examples).  My last file provisioner resets the sudoer file back to the original state.  Everything appears to work as expected with the builder and provisioners, though the problem is evident when I launch an instance from the newly created AMI.  The copy_files_cleanup deletes /etc/sudoers since it was a copy_file and cloud-init on first boot appends to the file.  Since it was deleted in the cleanup step by packer you end up with just the 4 appended lines in the file.  If I create a new volume from the packer created snapshot and attach it to another instance, I can see that /etc/sudoers does not exist.

The example of resolve.conf works as cloud-init writes this file on first boot of the instance and you don't really notice that the file was deleted out of the source AMI chroot volume before being snapshot.  I think the documentation is lacking here; the fact that the example works as a side effect of the ec2 boot process lead me down a path of much troubleshooting.

How have others solved the tty problem or other instances where they needed to alter /etc/sudoers to allow chroot to work?

**Comment by sethvargo** [comment]
Hi @tjbaker 

Is there a specific thing in Packer we could do to make this easier? It looks like you got it all figured out.

**Comment by catsby** [comment]
> This can be closed

Closing this, thanks for the detailed explanation of your workaround. If you do think of something that you feel packer should be doing to make this easier, please let us know.
Thanks!
