### ISSUE TITLE
Unwrap Amazon API errors

### ISSUE THREAD

**Issue by evgeny-goldin** [mitchellh/packer#1495]
Running

    PACKER_LOG=INFO packer build ..

with **"amazon-chroot"** builder and certain "source_ami" on **Packer 0.7.1** I receive the following error message: 

    2014/09/13 17:31:26 packer-builder-amazon-chroot: 2014/09/13 17:31:26 Create args: &ec2.CreateVolume{AvailZone:"eu-west-1c", Size:8, SnapshotId:"snap-7d140b86", VolumeType:"gp2", IOPS:24, Encrypted:false}
    ==> amazon-chroot: Error creating root volume: The parameter iops is not supported for this volume type. (InvalidParameterCombination)

["create-volume"](http://docs.aws.amazon.com/cli/latest/reference/ec2/create-volume.html) CLI documentation states that "iops" is "Only valid for Provisioned IOPS (SSD) volumes" (`io1`) while packer attempted to use it with General Purpose (SSD) volume (`gp2`).

**Comment by mitchellh** [comment]
Agreed with @m1keil
