### ISSUE TITLE
amazon-ebs ephemeral block mappings are failing with InvalidBlockDeviceMapping

### ISSUE THREAD

**Issue by beetlebugorg** [mitchellh/packer#1500]
With 0.7.0+ I'm now getting this error, works fine in 0.6.1.

```
==> amazon-ebs: Error launching source instance: Either snapshot ID or volume size must be provided for: /dev/sdb, /dev/sdc, /dev/sdd, /dev/sde (InvalidBlockDeviceMapping)
```

I have the following configuration in my packer template.

```
      "launch_block_device_mappings": [
        {
          "device_name": "/dev/sda1",
          "volume_size": 15,
          "volume_type": "gp2",
          "delete_on_termination": true
        },
        {
          "device_name": "/dev/sdb",
          "virtual_name": "ephemeral0"
        },
        {
          "device_name": "/dev/sdc",
          "virtual_name": "ephemeral1"
        },
        {
          "device_name": "/dev/sdd",
          "virtual_name": "ephemeral2"
        },
        {
          "device_name": "/dev/sde",
          "virtual_name": "ephemeral3"
        }
      ],
```

If you move the ephemeral device config from `launch_block_device_mappings` to `ami_block_device_mappings` the image will build but then you get the same `InvalidBlockDeviceMapping` when launching the image. Interestingly in the AWS Web Console the image shows the Block Devices as if they were EBS:

```
/dev/sda1=snap-d0183243:15:true:gp2:45, /dev/sdb=::false:standard, /dev/sdc=::false:standard, /dev/sdd=::false:standard, /dev/sde=::false:standard
```

**Comment by richid** [comment]
I'm pretty sure this issue has resolved itself for me. I just build a bunch of AMIs with the ```amazon-chroot``` builder and they launched fine without modification. Using Packer ```0.7.5```.

Has this started working for anyone else?

**Comment by eciramella-r7** [comment]
For us too - but there were a bunch of changes that could have fixed this (I haven't looked too deeply).

**Comment by richid** [comment]
@eciramella-r7 I confirmed a bit ago that ```0.7.5``` wasn't working, so I wonder if something changed on the EC2 side of things.

**Comment by scalp42** [comment]
It hasn't resolved itself for us, still running into the same issue.

**Comment by nyetsche** [comment]
Still seeing this with m3 instances, has anyone found a workaround? I tried to go back to the 0.6.1 tag, but something is broken in the dependencies so I can't build from scratch.

**Comment by beetlebugorg** [comment]
It's been working again for me on 0.7.5. I'm using m3.medium to build images. The only thing I've changed in my packer template is the source ami. I wonder if that could be contributing to the issue?

**Comment by nyetsche** [comment]
It must be. The AMI `ami-146e2a7c` (Amazon AWS Linux) fails for me, but `ami-48400720`, Redhat RHEL 6.6 succeeds.

**Comment by nyetsche** [comment]
So after poking at this further I realized the key difference between those two AMIs is the root block device - `/dev/xvda` for `ami-146e2a7c` and `/dev/sda1` for `ami-48400720`. My packer was inherited from a different AMI and was setting the root block device to `/dev/sda1` for `ami-146e2a7c`.

So..I think this is solved in 0.7.5? Can anyone else confirm that this is a configuration error?

**Comment by jsternberg** [comment]
Not sure if it's related, but we're attempting to use `NoDevice` and I'm running into this error after `CreateImage` is called.

```
Build 'ubuntu' errored: Error creating AMI: Either snapshot ID or volume size must be provided for: /dev/sdb, /dev/sdc (InvalidBlockDeviceMapping)
```

This is the mapping for the builder:

```
"ami_block_device_mappings": [
  {
    "device_name": "/dev/sdb",
    "no_device": true
  },
  {
    "device_name": "/dev/sdc",
    "no_device": true
  }
]
```

This same configuration worked for a co-worker of mine, but it doesn't appear to work for me.

**Comment by catsby** [comment]
Hello All –

It seems Amazon may have changed something on the API side here, at least I think... 
Sending no value for `VolumeSize` in the current version of the API we're using is throwing this error. If AWS had supplied a default before, it seems it's not longer there :frowning: .

I've updated the documentation in https://github.com/mitchellh/packer/pull/2250 to mention that if you're not specifying a `snapshot_id`, you must include the `volume_size`. 

Unfortunately I think that's the best we can do here.

**Comment by BrunoBonacci** [comment]
Hi @catsby,

Not too sure that this is the only problem.

I'm trying to build an image with packer 0.8.1 out of `d2.2xlarge` to use the *6 ephemeral* disks with the following snippet.

```
...
        "ami_block_device_mappings": [
            {
                "device_name": "/dev/sdb",
                "virtual_name": "ephemeral0"
            },
            {
                "device_name": "/dev/sdc",
                "virtual_name": "ephemeral1"
            },
            {
                "device_name": "/dev/sdd",
                "virtual_name": "ephemeral2"
            },
            {
                "device_name": "/dev/sde",
                "virtual_name": "ephemeral3"
            },
            {
                "device_name": "/dev/sdf",
                "virtual_name": "ephemeral4"
            },
            {
                "device_name": "/dev/sdg",
                "virtual_name": "ephemeral5"
            }
        ],
...
```

But once the AMI is built it maps the device with the following devices:

```
/dev/sda1=snap-971d5eb8:8:true:gp2, 
/dev/sdb=::false:standard, 
/dev/sdc=::false:standard, 
/dev/sdd=::false:standard, 
/dev/sde=::false:standard, 
/dev/sdf=::false:standard, 
/dev/sdg=::false:standard
```

Which causes errors during the launch of the instance.
Now I don't think that #2250 has much to do with this as the ephemeral storage hasn't a `snapshot_id` associated and the `volume_size` it is imposed by the instance type.

As you can see the first entry refer to an EBS backed snapshot which seems to suggest that the problem you mentioned is not influencing this particular case which is *mostly* about mapping 6 ephemeral devices into an AMI.

Bruno
