### ISSUE TITLE
Shell provisioner leaves behind temporary script

### ISSUE THREAD

**Issue by petehayes** [mitchellh/packer#1536]
The shell provisioner creates a script /tmp/script.sh and then executes it.  It would be an improvement if the script was deleted after executing so that subsequent uses of the shell provisioner, possibly by another user, does not step on it.  I see this warning in the logs:

chmod: changing permissions of `/tmp/script.sh': Operation not permitted

This happens when I initially create an image using qemu and root login and then build on top of that image using a non root user.

**Comment by bbaassssiiee** [comment]
Audit issue: /tmp/script.sh is world-writable and world-executable

RHEL6-STIG V-38643 Medium  There must be no world-writable files on the system
