### ISSUE TITLE
append vmware.log of the vm being created to packer logs

### ISSUE THREAD

**Issue by Sheshagiri** [mitchellh/packer#1543]
As of now vmware.log of the vm that is being created is not appended to the packer logs. It would be good to append those logs to the packer logs. If a user has incorrect configuration in the template like for example if the guest_os_type is set incorrectly `vm power on would fail` with bad guest os name error, after this packer will unregister the vm and delete all the files(including logs). It would be good to see vmware.log in packer logs as well. This would be specific to vmware-iso builder i guess.

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
