### ISSUE TITLE
Async Copies

### ISSUE THREAD

**Issue by vogxn** [mitchellh/packer#1610]
This is wrt to the amazon builder. I'm looking for ideas on how to make the copy to regions an async operation. Right now copy happens in three steps:

```go
StepCopyAmiToRegion
StepModifyAmiAttributes
StepCreateTags
```

When copying to all AWS regions this operation takes up to 3hours. It would be nice to daemonize the copy operation and subsequent operations. But this requires a dependency as go-routines are not fit for this since they exit soon as packer finishes. Are there better ways this can be done from within packer?

**Comment by mitchellh** [comment]
This is possible, and almost easy, but hasn't really been heavily requested by anyone except yourself. If you want to add it, feel free to submit a PR, but I don't see a reason to do this in Packer itself right now since no other builder behaves this way.

**Comment by vogxn** [comment]
Have put in retries on copy failures, so we're good now. Thanks for coming back on this one
