### ISSUE TITLE
Vagrant post-processor copies file to /tmp

### ISSUE THREAD

**Issue by rasschaert** [mitchellh/packer#1618]
The Vagrant post-processor [creates a temporary directory](https://github.com/mitchellh/packer/blob/abc4350f75999d7dc6040045f7ff20bab3b5f4bc/post-processor/vagrant/post-processor.go#L98) where it copies the artifact (.vmdk file) before compressing it and turning it into a .box

That's pretty inconvenient for me seeing as how my resulting .vmdk is 4.1GB and my /tmp partition only 3GB.

I don't really understand why this is done. After working around my /tmp size issue I noticed that even though the `keep_input_artifact` configuration setting is set to false (default), I can see the .vmdk file in two places at once. Both are then deleted when the post-processor is done.

```
4.1G    /tmp/kenny/packer420113976/packer-virtualbox-iso-1414158038-disk1.vmdk
4.1G    /home/kenny/packer/project/output-virtualbox-iso/packer-virtualbox-iso-1414158038-disk1.vmdk
```

Could a configuration setting be added to make use of the vmdk file in $PWD/output-virtualbox-iso/ instead of (needlessly?) copying it over to /tmp?

I imagine that the current behavior is inconvenient for people using packer on a CI server. In such an environment the created files should really be confined to the workspace and not create large files in /tmp

**Comment by adrahon** [comment]
This is a workaround and not a fix, but you can define the temp dir at packer invocation with:
`TMPDIR=/var/tmp packer build centos7.json`
