### ISSUE TITLE
Upgrade to latest GopherCloud API

### ISSUE THREAD

**Issue by mitchellh** [mitchellh/packer#1626]
This will likely fix a lot of bugs since we're pinned at a super old (July 2014) version right now. But we're going to remain pinned until we can figure out the upgrade process.

**Comment by jenspinney** [comment]
Hi @mitchellh,

I went ahead and submitted a pull request for the issue I'm running into. It's a one line fix (which has been fixed in the latest version of gophercloud), but without it I can't use packer on HP's public cloud. I'd love it if you could take a look.

The PR is [here](https://github.com/mitchellh/gophercloud-fork-40444fb/pull/1).

Thanks!
Jen

**Comment by stenstad** [comment]
Any progress on migrating over to the new openstack/identity API in gophercloud?

All our users have their own domains, so only Identity V3 works to get valid tokens. I think this might be the case for more and more Openstack deployments going forward.

**Comment by jenspinney** [comment]
One possible issue keeping packer from migrating over to the latest gophercloud could be the lack of nova-based floating IP support, which did exist in the old version and is used by packer. From [this](https://github.com/rackspace/gophercloud/pull/330) pull request, though, it sounds like **neutron**-based floating IP support is the new standard for OpenStack.

I have no idea how common it is for different OpenStack deployments to have neutron-based floating IP support vs nova-based, but if there are OpenStack setups out there that only work with nova floating IPs, the migration would break them.

**Comment by stenstad** [comment]
Development on nova-networking has basically halted, and most development effort targets neutron. There are probably some older deployments still using nova-networking, and it has not been deprecated yet, even if that seems to be the plan.

If I understand the documentation correctly, Rackspace now uses Neutron, as does HP Cloud. As do we.

I think Packer shoud migrate to the new Gophercloud, and that users that need to use an old OpenStack platform should just stay with an older version of Packer+Gophercloud instead.

**Comment by jenspinney** [comment]
Makes sense.

**Comment by einarf** [comment]
Gophercloud is pretty close to having a working identity v3 support now. Commits this week should include proper extraction of a service catalog. The previous implementation was completely broken. The only remaining issue I have with Gophercloud is how to deal with token hashing.

I'm working on an openstack-id3 builder (Identity v3 using the new Gophercloud API), but I guess that one could also be turned into something more generic.

**Comment by einarf** [comment]
I have a working builder using the new gophercloud now. Need to wait for my PR in gophercloud to go through first so it can actually create an image. I have only tested it under identity v3, so maybe smart to make a PR tomorrow (hopefully) as a separate builder.

**Comment by erikkri** [comment]
@einarf is it possible to build both your PR in gophercloud and your builder to test using Zetta with packer?

**Comment by einarf** [comment]
@erikkri Yes. I'll clone repos and push up brances in a bit.

**Comment by einarf** [comment]
New builder is located here :
https://github.com/ZettaIO/packer/tree/openstack-id3-builder/builder/openstack_id3

Requires this branch to be merged to gophercloud (Waiting for PR to be accepted):
https://github.com/ZettaIO/gophercloud/tree/serveraction-createimage

The above is needed for gophercloud to actually created snapshots/images of servers.

My simple test template :

```json
{
  "builders": [
    {
      "type": "openstack-id3",
      "openstack_provider": "openstack",
      "provider": "https://some.keystone.server/v3",
      "domain": "<insert domain>",
      "project": "<insert project name>",
      "username": "<insert username>",
      "password": "<insert password>",
      
      "image_name": "packer-test-image",
      "source_image": "<insert image id here>",
      "flavor": <insert flavor id here>,
      "floating_ip_pool": "Public",
      "networks": ["<network id>"],
      "security_groups": ["default"],
      
      "ssh_username": "ubuntu",
      "ssh_port": "22"
    }
  ],
  "provisioners": [{
    "type": "shell",
    "inline": [
      "sleep 30",
      "sudo apt-get update",
      "sudo apt-get install -y nginx"
    ]
  }]
}
```

Not entirely sure how to do this PR, but I guess we can figure it out.

**Comment by einarf** [comment]
Think I'm pretty much done with the port now. Just trying to figure out something wonky with the sshinterface/pool selection part. Hopefully it works like the old builder with v2 support as well.

**Comment by einarf** [comment]
Would be nice to have this builder tested more. Especially for identity v2.

**Comment by einarf** [comment]
Looks like @droyo got this working fine under identity v2 now after two fixes related to floating IP.

**Comment by einarf** [comment]
@jenspinney Did you give the builder I ported a try? It should work for HP Helion openstack.
