### ISSUE TITLE
Mishandling of symlinks

### ISSUE THREAD

**Issue by israelshirk** [mitchellh/packer#1627]
Working with the Docker communicator tonight I found that there's a false dichotomy in a few spots regarding file treatment since symlinks aren't considered.  The Docker one should be fixed in the PR mentioned below.

It looks a similar issue was resolved in the SSH communicator in #449; but there's another copy in the file provisioner at `provisioner/file/provisioner.go`, lines 80-90:

```go
	info, err := os.Stat(p.config.Source)
	if err != nil {
		return err
	}

	// If we're uploading a directory, short circuit and do that
	if info.IsDir() {
		return comm.UploadDir(p.config.Destination, p.config.Source, nil)
	}

	// We're uploading a file...
	f, err := os.Open(p.config.Source)
	if err != nil {
		return err
	}
	defer f.Close()

	fi, err := f.Stat()
	if err != nil {
		return err
	}

	err = comm.Upload(p.config.Destination, f, &fi)
```

I'm mixed on how to resolve that one without soiling interfaces and am a bit short on time ATM - would someone else have time to pick it up?

Thanks!

**Comment by bkeroackdsc** [comment]
I'm running into this with the Ansible provisioner and Docker builder. Our playbooks contain symlinks which do not appear to be followed when copying into the container.

**Comment by arturhoo** [comment]
I am having the same problem when Ansible files are copied over to the machine: symlinks aren't followed.

**Comment by mitchellh** [comment]
I think the PRs fixed the specific issues. As we find more please open an issue.
