### ISSUE TITLE
ssh_private_key_file is of limited use without key_pair_name parameter

### ISSUE THREAD

**Issue by renat-sabitov** [mitchellh/packer#1635]
It's possible now to specify a key to use instead of a generated key for amazon EBS builders.  However, it results in launching an instance with an empty key pair and, to my understanding, suggesting that the key will be put on the source instance authorized_keys beforehand.

This behaviour could be significantly improved by providing a "key_pair_name" parameter, which will be used along with "ssh_private_key_file" to let amazon put public key to the instance on start.

**Comment by jantman** [comment]
This also appears related to #1697
