### ISSUE TITLE
Failed stating file: disk-flat.vmdk

### ISSUE THREAD

**Issue by parabolic** [mitchellh/packer#1636]
- **packer version:** 0.7.1
- **builder:** vmware-iso
- **post-processors:** compress

```
"post-processors": [
       {
          "output":"/misc/test.tar.gz",
         "type": "compress",
         "format": "tar.gz"
       }
     ]
```

Hi,
It seems that I am having problems with the post-processors. When using compress the post processor always appends -flat.vmdk when searching for the disk file. I tried with setting the vmdk_name

`"vmdk_name":"diskflat",`

and then I got this error

```
==> Some builds didn't complete successfully and had errors:
--> vmware-iso: 1 error(s) occurred:
* Post-processor failed: Failed stating file: /vmfs/volumes/vmware_persistent/output-vmware-iso/diskflat-flat.vmdk
==> Builds finished but no artifacts were created.
```

When I don't have the vmdk_name set I get this error

```
==> Some builds didn't complete successfully and had errors:
--> vmware-iso: 1 error(s) occurred:
* Post-processor failed: Failed stating file: /vmfs/volumes/vmware_persistent/output-vmware-iso/disk-flat.vmdk
==> Builds finished but no artifacts were created.
```

Which is obvious that it's appending the `-flat.vmdk`. I looked at the code but couldn't find nothing.

Thanks for your help!
Cheers

**Comment by braddeicide** [comment]
I'm having this issue.

I changed the disk_type_id to eagerzeroedthick and now disk-flat.vmdk is being created mid run as i watch the storage (not really the correct solution to a bug) however by the time the post-processor runs it's called disk.vmdk so fails.  I disabled the compaction to see if that was renaming it but it didn't help.

The error occurs in the vagrant post-processor

2017/12/29 10:16:06 packer: 2017/12/29 10:16:06 starting remote command: vmkfstools -c 40960M -d eagerzeroedthick -a lsilogic /vmfs/volumes/NFS/outputs/disk.vmdk

==> vmware-iso: Running post-processor: vagrant
2017/12/29 11:05:57 ui: ==> vmware-iso (vagrant): Creating Vagrant box for 'vmware' provider
==> vmware-iso (vagrant): Creating Vagrant box for 'vmware' provider
    vmware-iso (vagrant): Copying: /vmfs/volumes/NFS/outputs/disk-flat.vmdk
2017/12/29 11:05:57 ui:     vmware-iso (vagrant): Copying: /vmfs/volumes/NFS/outputs/disk-flat.vmdk
2017/12/29 11:05:57 [INFO] (telemetry) ending vagrant
2017/12/29 11:05:57 [INFO] (telemetry) found error: open /vmfs/volumes/NFS/outputs/disk-flat.vmdk: no such file or directory
2017/12/29 11:05:57 ui: ==> vmware-iso: Running post-processor: vsphere-template
2017/12/29 11:05:57 [INFO] (telemetry) Starting post-processor vsphere-template
==> vmware-iso: Running post-processor: vsphere-template
    vmware-iso (vsphere-template): Waiting 10s for VMware vSphere to start
2017/12/29 11:05:57 ui:     vmware-iso (vsphere-template): Waiting 10s for VMware vSphere to start
2017/12/29 11:06:07 ui:     vmware-iso (vsphere-template): Choosing datacenter...
    vmware-iso (vsphere-template): Choosing datacenter...
2017/12/29 11:06:07 ui:     vmware-iso (vsphere-template): Creating or checking destination folders...
    vmware-iso (vsphere-template): Creating or checking destination folders...
2017/12/29 11:06:07 ui:     vmware-iso (vsphere-template): Marking as a template...
    vmware-iso (vsphere-template): Marking as a template...
2017/12/29 11:06:08 [INFO] (telemetry) ending vsphere-template
2017/12/29 11:06:08 Flagging to keep original artifact from post-processor 'vsphere-template'
2017/12/29 11:06:08 ui error: Build 'vmware-iso' errored: 1 error(s) occurred:

* Post-processor failed: open /vmfs/volumes/NFS/outputs/disk-flat.vmdk: no such file or directory

**Comment by braddeicide** [comment]
I disabled vagrant and it appears the vmware-iso builder thinks there's more disks than there are

==> Builds finished. The artifacts of successful builds are:
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "builder-id", "mitchellh.vmware-esx"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "id", "packer-openbsd62-amd64"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "string", "VM files in directory: /vmfs/volumes/NFS/outputs"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "files-count", "6"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "file", "0", "/vmfs/volumes/NFS/outputs/disk-flat.vmdk"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "file", "1", "/vmfs/volumes/NFS/outputs/disk.vmdk"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "file", "2", "/vmfs/volumes/NFS/outputs/packer-openbsd62-amd64.nvram"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "file", "3", "/vmfs/volumes/NFS/outputs/packer-openbsd62-amd64.vmsd"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "file", "4", "/vmfs/volumes/NFS/outputs/packer-openbsd62-amd64.vmx"}
2017/12/29 12:02:51 machine readable: vmware-iso,artifact []string{"0", "file", "5", "/vmfs/volumes/NFS/outputs/packer-openbsd62-amd64.vmxf"}
