### ISSUE TITLE
Populate node attributes from a json file

### ISSUE THREAD

**Issue by consultantRR** [mitchellh/packer#1638]
I see that the chef-solo provisioner has a "json" parameter in order to provide node attributes to chef-solo. Is there any way to populate that from a separate json file? Meaning: I would like to specify node attributes for chef-solo in a json file that is separate from the packer template itself, rather that explicitly including them in-line in the packer template. Is there an easy way to do this in the current version of packer?

**Comment by sethvargo** [comment]
This is not currently possible, but seems like a good idea.

**Comment by nicka** [comment]
For now we use something like this:
```
"provisioners": [
    {
      "type": "file",
      "source": "packer/{{user `NAME`}}/attributes.json",
      "destination": "/tmp/attributes.json"
    },
    { "type": "chef-solo",
      "cookbook_paths": [ "packer/{{user `NAME`}}/cookbooks" ],
      "execute_command": "{{if .Sudo}}sudo {{end}}chef-solo --no-color -c {{.ConfigPath}} -j /tmp/attributes.json"
    }
]
```

**Comment by mitchellh** [comment]
I think the workaround above is fine, this hasn't been highly requested. On the other hand, if there were a PR, I'd be happy to merge it.

**Comment by wbotelhos** [comment]
Hi @mitchellh ,

Do you have idea to implement it?
It would be great! (:

**Comment by rickard-von-essen** [comment]
@wbotelhos see [the comment above](https://github.com/hashicorp/packer/issues/1638#issuecomment-76970127).

**Comment by SwampDragons** [comment]
From @curiositycasualty in #6986

> Adding more details to #1638 since it is locked.
> Feel free to close this issue if there's no actionable feedback in it for you.
> 
> In implementing the work around described in the parent issue, I noticed that packer passes its run_list property (for both chef provisioners) via a first-boot.json file it writes to /tmp/packer-chef-cache (by default).
> Which means that if you follow the workaround but don't include a run_list key in your json file, chef will run with an empty run_list.
> 
> This feels like only a partial workaround since it means that if you've passed a run_list property to a chef-* provisioner, it is ignored.
> As a full(-er) workaround, I've been templating a {{user `chef_run_list`}} into the chef-* provisioner's execute_command's chef-client arguments like so:
> 
> ...
>     {
>       "destination": "/tmp/attributes.json",
>       "source": "attributes/{{build_name}}.json",
>       "type": "file"
>     }
> ...
>     {
> ...
>       "execute_command": "sudo chef-client --runlist '{{user `chef_run_list`}}' --no-color -c {{.ConfigPath}} -j /tmp/attributes.json",
>       "type": "chef-client"
>     }
> ...
> Hopefully this helps someone else stuck in the same rut.
