### ISSUE TITLE
File Upload not uploading directory on Windows to correct location

### ISSUE THREAD

**Issue by anthony-7** [mitchellh/packer#1641]
File provisioner is not uploading directories to the right location on a Windows EC2 instance. I create a directory, and upload a file to that directory successfully. I then try to upload a directory into that directory and it appears that nothing gets uploaded. Looking at the debug log data, there are no obvious errors and it seems as if everything is working. It detects I'm uploading a directory, I can see upload messages for all the subdirectories and Sink messages for all the files. 

Doing a global search for one of the files in the directory structure, I find that the contents of my directory have been uploaded to `c:\cygwin64\home\Administrator\c?packerTemp\` instead of `c:\packerTemp\MyWebServer`

``` json
  {
    "type": "shell",
    "inline": ["cmd /c \"md c:\\packerTemp\""]
  },
  {
    "type": "file",
    "source": "chef-windows-11.16.4-1.windows.msi",
    "destination": "c:\\packerTemp\\chef-windows-11.16.4-1.windows.msi"
  },
  {
    "type": "file",
    "source": "MyWebServer",
    "destination": "c:\\packerTemp"
  }
```

**Comment by mwhooker** [comment]
Going to close this since there's been many changes to the way we upload files since this was opened. If anyone still gets this error please reopen or open another issue. Thanks!
