### ISSUE TITLE
Download file from build process

### ISSUE THREAD

**Issue by arosenhagen** [mitchellh/packer#1652]
To better keep track of installed software packages I want to download a file after the build process (inside the VM). Something like 
```
dpkg-query -l > installed-software.txt
```
Is there any possibility to transfer a file back to the host?

**Comment by jsmpereira** [comment]
:+1: 
This would be very useful. I have the same need in the context of keeping track of docker images pulled into the build artifact.

**Comment by mitchellh** [comment]
Done
