### ISSUE TITLE
Hyper-V builder & vagrant post-processor - artifacts

### ISSUE THREAD

**Issue by pbolduc** [mitchellh/packer#1653]
In [vagrant Hyper-V plugin](https://github.com/mitchellh/vagrant/blob/efd1d5e11bfc5a72c7a1d1eae294b4751d841544/plugins/providers/hyperv/action/import.rb), the output box requires a folder structure that has a "Virtual Machines" and "Virtual Hard Disks" sub-folders. 

```
vm-directory
  +- Virtual Machines\vm.xml
  +- Virtual Hard Disks\vm.vhdx
```

In the [vagrant Hyper-V Post-Processor](https://github.com/mitchellh/packer/blob/master/post-processor/vagrant/hyperv.go), it looks likes all the artifacts are being flattened into a single flat folder.

When the virtual machine is exported, the export folder already has this structure and the artifacts resemble:

```
artifacts := &artifact{
    dir: "win2008-standard",
    f: [2]string{"win2008-standard\Virtual Machines\win2008-standard.XML", 
                 "win2008-standard\Virtual Hard Disks\win2008-standard.vhdx"},
```

I am thinking the vagrant Hyper-V Post-Processor needs to maintain the folder structure provided by the Hyper-V builder artifacts.  Please let me know if I am missing something obvious.

**Comment by sethvargo** [comment]
Cross-linking with https://github.com/mitchellh/vagrant/issues/5542 for reference.
