### ISSUE TITLE
Boolean 'true' user variables turn into '1' in script provisioner

### ISSUE THREAD

**Issue by tomtaylor** [mitchellh/packer#1654]
I've noticed that a boolean user variable of `true` is turned into a `1` string when it is interpolated into an inline script.

For example:

```json
{
  "provisioners": [
    {
      "inline": [
        "echo \"Test key: {{user `test_key`}}\"",
      ],
      "type": "shell"
    }
  ],
  "variables": {
    "test_key": true
  }
}
```

This echos "1". I can understand why this is happening, but I'd expect these to be turned into "true" strings, I think. I haven't checked fully with the shell provisioner, but I'd expect the same there, as environment variables.

**Comment by IevgenKabanets** [comment]
Any workaround? Apart from accepting this as it is?
Also, user variables set with '-var' option are converted to another string: "true" or "false".

**Comment by mitchellh** [comment]
If its not set as a string, the value it turns into will be some equivalent value. We happen to decode true to "1" as a string. If you want it as a string, please set it as such for an exact value.

**Comment by IevgenKabanets** [comment]
@mitchellh, if variable is set to true -> it's turned into string (at least this is what I see currently).
But why not true => 1 or true, bool converts to bool value? 
Sorry if I'm missing something...
