### ISSUE TITLE
Cannot modify the PATH environment variable in Docker images

### ISSUE THREAD

**Issue by portergoodness** [mitchellh/packer#1660]
I have been having trouble replacing the the **ENV** Docker functionality in Packer when modifying the PATH variable.  

The use case we have for this is to build a Docker image that, amongst other things, installs and configures Java.  This typically involves setting a JAVA_HOME environment variable and then adding it to the PATH.  Once our image is built, others will use the image, but they are expecting JAVA_HOME to be in the path (without them having to launch Docker with the environment variables).

I have tried two approaches to this in Packer, both fail, one takes longer to fail than the other.
1. Setting via Builder _run_command_
   I tried setting environment variables in the Docker **builder** by adding the docker arguments to set variables ("-e", "PATH=$PATH:/run").  When I run this template [https://gist.github.com/portergoodness/613b3e1fc39da3701558] it takes a few minutes for Packer to eventually fail.  Here is the log [https://gist.github.com/portergoodness/7caac4dacac983d38fcd].
2. Setting via script provisioner _environment_vars_
   I tried setting environment variables on an individual script **provisioner** in the _environment_vars_ configuration.  When I run this template [https://gist.github.com/portergoodness/933802839fbdb01d429d] it fails faster than the first test case, but still fails.  Here is the log [https://gist.github.com/portergoodness/5545103e704a39ae8f8c].
3. Setting a environment variable other than _PATH_
   This case is a sanity check to make sure these approaches actually work and that the issue is the PATH environment variable and not the approaches.  By changing **PATH** to something else, like **NOTPATH** for instance, Packer successfully builds the image.  For test case 3, I modified the second test case, by running this template [https://gist.github.com/portergoodness/d267d9ce1f4793efd850] which successfully builds an image.  I also tried modifying the first test case in the same way and it worked as well.

**Comment by IronicBadger** [comment]
Sorry for dragging up an old post, is this still the case or is there a more elegant solution nowadays?

**Comment by rickard-von-essen** [comment]
Support for setting `ENV` was added in #4202.
