### ISSUE TITLE
Can't run post-processor "compress" in vmware-iso over remote ESXi

### ISSUE THREAD

**Issue by stephenranjit** [mitchellh/packer#1664]
It creates the target tar file on my local machine and then tries to stat a file on my local machine instead on the remote ESXi datastore. is it not designed to compress remotely? is there an alternative to compress files remotely?

==> vmware-iso: Running post-processor: compress
==> vmware-iso (compress): Creating archive for 'mitchellh.vmware-esx'
Build 'vmware-iso' errored: 1 error(s) occurred:

* Post-processor failed: Failed stating file: /vmfs/volumes/datastore1/output-vmware-iso/disk-flat.vmdk

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: 1 error(s) occurred:

* Post-processor failed: Failed stating file: /vmfs/volumes/datastore1/output-vmware-iso/disk-flat.vmdk

==> Builds finished but no artifacts were created.

**Comment by mitchellh** [comment]
This isn't designed to compress remotely right now, just locally. The ESX builder is a weird one that we're going to improve in other ways.
