### ISSUE TITLE
change provider name from "vmware" to "vmware_desktop" cause name inconsistent

### ISSUE THREAD

**Issue by beelit94** [mitchellh/packer#1671]
for example, if I want to build virtualbox and vmware in parallel, 
there will be a problem for vmware box
In the end,
the box name I created would be 
*output_name*_vmware.box
but the url on vagrant cloud would be 
http://*prefix*/*output_name*_vmware_desktop.box

This would cause download url error

following is the post processor I wrote
```javascript
[
        "type": "vagrant",
        "vagrantfile_template": "vagrantfile-windows_2008_r2.template",
        "output": "{{user `output_name`}}_{{.Provider}}.box",
        "keep_input_artifact": true
      },
      {
        "type": "vagrant-cloud",
        "box_tag": "{{user `box_tag`}}",
        "access_token": "{{user `cloud_token`}}",
        "version": "{{user `version`}}",
        "box_download_url": "{{user `box_download_prefix`}}{{user `output_name`}}_{{.Provider}}.box"
      }
]
```

**Comment by sethvargo** [comment]
You should use `{{.Buildname}}` here for finer control as suggested by @tnarik :smile:
