### ISSUE TITLE
Post-processor fails when no resource_pool set

### ISSUE THREAD

**Issue by bemeyert** [mitchellh/packer#1677]
Hi all,
since version 0.7.1/2 (sry, not sure which one) the vsphere post-processor no longer works when there is no resource pool available on the ESX-host. The old trick with a whitespace in the `resource_pool` variable does no longer work. With 0.7.2 (i guess) came a slash '/' at the end of the ovftool locator. Before this commit I had just a whitespace at the end now there is '.../Resources/ /' (slash-whitespace-slash) and ovftool fails.
This *once* worked:

    "post-processors": [
      {
        "type": "vsphere", 
        "resource_pool": " ",
     [...]

The affected lines are https://github.com/mitchellh/packer/blob/v0.7.2/post-processor/vsphere/post-processor.go#L131-L137

So, how can I upload to Vsphere without having any Resourcepools? Currently my workaround is to *not* use the post-processor and upload manually with `ofvtool`.

**Comment by jphalip** [comment]
I suspect this started breaking after this commit: https://github.com/mitchellh/packer/commit/f61cc3f99c1819f985a0f401f1871a5c64b1f425

If no value is provided for `"resource_pool"` then you end up with something like `".../Resources//"` and if a space value `" "` is provided as in the old hack then you end up with `".../Resources/ /", none of which are valid.

A proper fix, I think, would be to change this code so that you'd end up with `".../Resources/"` if no `"resource_pool"` value is provided, therefore making that parameter effectively optional.

**Comment by bemeyert** [comment]
@jphalip Jep, it works with `".../Resources/"`. I just verified it with our ESX-Servers and ovftool.

**Comment by jphalip** [comment]
@bemeyert Thank you for checking. Could you also please check if it also works without "Resources/" altogether. I've reviewed the ovftool specs and it looks like the "Resources/" part is only needed if directly followed by an actual resource pool name.

So, the idea is that we'd either use `"<datacenter name>/host/<host name>/Resources/<resource pool>"` if a `"resource_pool"` parameter is provided, or simply `"<datacenter name>/host/<host name>"` if no `"resource_pool"` is provided.

**Comment by bemeyert** [comment]
@jphalip It seems to work. A test with `<datacenter>/host/<host or cluster name>/` uploaded the VM. And just for the sake of completeness I also tried it without the slash at the end which worked too.

BTW: I'm using ESX 5.5!

**Comment by rylarson** [comment]
This PR fixes this problem

https://github.com/mitchellh/packer/pull/1868#issuecomment-72565724

**Comment by bemeyert** [comment]
Just checking if this is still alive. Can someone please tell me the status of this?

**Comment by mitchellh** [comment]
Fixed by #1868

**Comment by sharumpe** [comment]
Awesome. Is possible for that fix to be in 0.7.6?

**Comment by mitchellh** [comment]
@sharumpe 0.8.0 wll come out in the next couple weeks

**Comment by sharumpe** [comment]
That is great, thanks for everyone's work on this!
