### ISSUE TITLE
Substitute variables in HTTP text responses

### ISSUE THREAD

**Issue by langri-sha** [mitchellh/packer#1684]
When using Packer variables to customize the build process, most of these end up exposed to the guest environment through boot commands. Unfortunately, developing the actual builds means one ends up idling while the variables get streamed, especially if you can count them by the dozens.

If the HTTP server would be extended to substitute variables, for text responses only, it would be possible to gracefully expose these by other means:

```
# template.json
{
    "boot_commands": [
        "curl http://{{.HTTPIP}}:{{.HTTPPort}}/settings.sh | sh"
    ]
}

# settings.sh
export FOO={{user `foo`}}
```

I understand there are many alternative ways to manage user customizations, but being that the files are already distributed by Packer's HTTP server, there is some practical benefit if variable substitution can be used.

**Comment by sethvargo** [comment]
Would #1673 satisfy your use case?

**Comment by langri-sha** [comment]
Yes, #1673 would perfectly satisfy my use case! I guess this makes my issue a duplicate of.

**Comment by sethvargo** [comment]
:smile:
