### ISSUE TITLE
chef-client provisioner hangs when creating directory

### ISSUE THREAD

**Issue by ziuchkovski** [mitchellh/packer#1686]
The chef-client provisioner hangs on 'Creating directory: /tmp/packer/chef-client'.

This appears to be a problem with https://github.com/mitchellh/packer/blob/master/provisioner/chef-client/provisioner.go#L337 which assumes passwordless sudo.  Adding the current user as a passwordless sudoer resolves the problem.  Without this, packer hangs indefinitely.

**Comment by sethvargo** [comment]
@ziuchkovski as Michael said - I believe you are actually getting an error (or being asked for a sudo password). Are you able to confirm this by performing the steps manually?

**Comment by mitchellh** [comment]
You have two choices now:

1.) Disable sudo on Chef (an option exists)
2.) Disable PTY on SSH (an options exists)

In master.
