### ISSUE TITLE
Excessive AWS API request rate

### ISSUE THREAD

**Issue by blalor** [mitchellh/packer#1688]
Is it possible to batch and throttle AWS API requests when building AMIs?  I built 26 AMIs at once this morning (CI FTW!) and kind of broke some of our other automation. :-P  Here's what my Cloudtrail logs look like during the period I was running the Packer builds:
![5oph](https://cloud.githubusercontent.com/assets/109915/5150606/fc73c65c-71a1-11e4-834c-21d165c96c53.png)

I have 13 AMIs defined in my config, and I was running two Packer instances, one for paravirtual and one for HVM.  Obviously the two Packer instances can't coordinate, but even if I ran those serially, Packer was responsible for 3-4 requests per second at its peak.  Can the AMI builders be made to coordinate a bit so that the requests can be batched?

**Comment by mitchellh** [comment]
Fixed! We changed to aws-go which does automaticac exponential backoff for retries.
