### ISSUE TITLE
Salt Provisioner fails to copy state files if /srv/salt already exists on target 

### ISSUE THREAD

**Issue by dennisfoconnor** [mitchellh/packer#1699]
I noticed this when I was building a docker image from a previously provisioned docker image. If the ``/srv/salt`` directory already exists on the target it copies ``/tmp/salt/states`` to ``/srv/salt/states``. 

I am using Packer v 0.72.

There is a work around. I place the following shell provisioner above my salt provisioner:
```
{
   "type": "shell",
   "inline":  "rm -r /srv/salt"
}
```

**Comment by ajmath** [comment]
Thank you! I have been hitting this one way or another for the past few months and finally dug into it tonight only to discover it's been resolved an hour ago.
