### ISSUE TITLE
SaltStack provisioner fails to copy minion file on FreeBSD

### ISSUE THREAD

**Issue by amontalban** [mitchellh/packer#1702]
Hey guys,

I'm doing my first test with Packer creating FreeBSD images at my work. The problem is that we provision servers using SaltStack and it seems that when Packer try to copy minion file it fails because it tries to copy to /etc/salt/minion (Despite the fact I didn't provide any minion file as I don't want to at the moment).

I'm installing SaltStack from FreeBSD ports in order to keep things tidy and also because the bootstrap script uses wget and FreeBSD has fetch installed by default.

Here is the code:

```
{
  "type": "salt-masterless",
  "skip_bootstrap": "true",
  "local_state_tree": "../../salt/salt",
  "local_pillar_roots": "../../salt/pillar"
},
```

And here is the error:

``` text
==> virtualbox-ovf: Uploading files/grains => /tmp/grains
==> virtualbox-ovf: Provisioning with shell script: /var/folders/xl/t0zszpc14z5g5wpvl5_bby1m0000gn/T/packer-shell954184491
==> virtualbox-ovf: Provisioning with Salt...
    virtualbox-ovf: Creating remote directory: /tmp/salt
    virtualbox-ovf: Creating directory: /tmp/salt
    virtualbox-ovf: Uploading local state tree: ../../salt/salt
    virtualbox-ovf: Creating directory: /tmp/salt/states
    virtualbox-ovf: Moving /tmp/salt/states to /srv/salt
    virtualbox-ovf: mv: rename /tmp/salt/states to /srv/salt: No such file or directory
==> virtualbox-ovf: Unregistering and deleting imported VM...
==> virtualbox-ovf: Deleting output directory...
Build 'virtualbox-ovf' errored: Unable to move /tmp/salt/states to /srv/salt: &{%!d(string=Unable to move /tmp/salt/minion to /etc/salt/minion: &{%!d(string=Bad exit status: 1)})}
```

**Comment by boyonwheels** [comment]
We have the same issue. It's because the FreeBSD port/pkg installs Saltstack under /usr/local/etc/salt. This is different than the Saltstack defaults. I work around this issue by skipping Packer's built-in provisioner and using a shell script instead. For example (using an inline script) with the assumption that the provisioning account is in the sudoer group:

		"provisioners": 
		[
			{
				"type": "shell",
				"inline": [
										"sudo pkg install -y py27-salt-2014.7.2",
										"sudo ln -s /usr/local/etc/salt /etc/salt",
										"sudo mkdir /usr/local/etc/salt/states",
										"sudo mkdir /srv",
										"sudo ln -s /usr/local/etc/salt /srv/salt"
									] 
			},
			{
				"type": "salt-masterless",
				"skip_bootstrap": "true",
				"local_state_tree": "foo/bar/baz/states",
				"minion_config": "spam/eggs/minion"
			}
		]
