### ISSUE TITLE
virtualbox http error

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [mitchellh/packer#1709]
Hi,
When using Packer Version 0.7.2, the default http port and IP generated when using the virtualbox builder does not seem to work. See the GIST link for JSON, Kickstart and Packer Log.
https://gist.github.com/anandvenkatanarayanan/46f261ac0d70a7cea8ca

The exact error message from Anaconda is 
![snapshot1](https://cloud.githubusercontent.com/assets/6889702/5242936/2ad37ace-7963-11e4-8b4d-0818006d2e40.png)

I also did some tests to figure what is going on in the background, but that does not throw any clue. 

I see a daemon process listening on port 8891

```
anandv@anandv-desktop:~/source/PackerFiles$ netstat -a | grep 8891
tcp6       0      0 [::]:8891               [::]:*                  LISTEN     
```

But a wget on the localhost fails. 

```
anandv@anandv-desktop:~/source/PackerFiles$ wget http://localhost:8891/kickstart-rhel-server-6.5-x86_64.cfg
--2014-12-01 13:51:35--  http://localhost:8891/kickstart-rhel-server-6.5-x86_64.cfg
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8891... connected.
HTTP request sent, awaiting response... 404 Not Found
2014-12-01 13:51:35 ERROR 404: Not Found.
```

I cannot also connect to the 10.0.2.2 address.

However if I replace the http address in the JSON template with another IP, packer is able to build. So I guess this is a problem in figuring out the correct HTTP IP to use with VirtualBox? 

Thanks
Anand V

**Comment by dhartford** [comment]
Similar issue with packer server: centos6,5    guest setup: centos6.5/vmware-iso

The HTTP_DIRECTORY as packer's hosting webserver is only serving IPv6, but not IPv4.  the .HTTPIP configuration is showing IPv4 address.

Similar confirmation approach - VNC to system-in-progress, see the HTTP_DIRECTORY port.

cmd> netstat -a |grep 8812
tcp6       0      0 [::]:8812               [::]:*                  LISTEN

Attempts to manually disable IPv6 did not help (http://wiki.centos.org/FAQ/CentOS6#head-d47139912868bcb9d754441ecb6a8a10d41781df).  

No options visible to have the HTTP_DIRECTORY server force IPv4 usage (probably the ideal).

**Comment by pasikarkkainen** [comment]
For some reason this seems to still be broken in Packer v1.1.2.
http server only listens on tcp6.

I'm running Packer on CentOS 7.4 host.

**Comment by pasikarkkainen** [comment]
It seems even though the packer http servers shows as listening on "tcp6" it doesn't matter, it still works over ipv4 aswell.
