### ISSUE TITLE
Add support for Docker provisioner

### ISSUE THREAD

**Issue by themasterchef** [mitchellh/packer#1710]
Currently there is a Docker _builder_ in Packer which, given a single Dockerfile, builds it, and chucks out a VM of some kind. We would like to do a similar thing, but instead of one Dockerfile, we wish to pile several Docker images onto a Packer-built VM (various DBs, cache stores, and self-executing WAR file app servers) and get, say, an all-in-one .OVA file out. This will enable totally automated production of standalone VMs of multi-tier apps by combining existing Docker images that devs are using, which I expect others beside ourselves will find useful.

Vagrant, which is vaguely similar in spirit to Packer, calls this a Docker _provisioner_, and the way it works is in the [docs](http://docs.vagrantup.com/v2/provisioning/docker.html). TL;DR - it applies multiple images to the outer Vagrant box as shown below, and crucially there is also some support for setting environment variables (really important if, say, you want to set a DB user and password when setting up the DB container, then pass these credentials to the app server containers):

```
Vagrant.configure("2") do |config|
  config.vm.provision "docker" do |d|
    d.pull_images "ubuntu"
    d.pull_images "vagrant"
  end
end
```

Is it possible to do the same in Packer? Or alternatively, should people looking for this kind of feature really look at [DinD](https://github.com/jpetazzo/dind) (Docker in Docker) instead?

**Comment by rickard-von-essen** [comment]
I would say that this is to specialised to motivate a provisioner and also super easy to do with for example `shell` provisioner.

**Comment by rickard-von-essen** [comment]
Unless there is any more motivation I'm voting for closing this.

**Comment by rickard-von-essen** [comment]
Closing since this is trivial with the `shell` provisioner.
