### ISSUE TITLE
Headless mode fails on machine without X session

### ISSUE THREAD

**Issue by dragon788** [mitchellh/packer#1724]
This is a bug in Virtualbox, but could (should?) be easily worked around in Packer. https://www.virtualbox.org/ticket/10250

USE CASE:
When working on a build system (Jenkins), we don't want to require X to be installed or running. We perform our builds inside a chroot (or Docker container) and therefore don't guarantee any X displays are present or available.  If we enable headless mode, in order to work around this bug we need to disable accelerate3d for the VM in order to allow it to start.

WORKAROUND:
We are adding ["modifyvm","{{.Name}}", "--acccelerate3d", "off"] to our template.json in order to work around this issue. Would it be possible for Packer to be smart about headless and automatically disable 3D acceleration (with a non-critical WARNING) to the user about this state? That way if we are building on a desktop versus the CI system we can utilize the 3D acceleration without changing the template every time.

**Comment by sethvargo** [comment]
It looks like this issue has been fixed in VirtualBox. Do you still need a work-around in Packer?

**Comment by dragon788** [comment]
I think perhaps this needs documented under the Virtualbox provisioners in the Packer docs as it wasn't a very obvious solution. That would probably work just as well as trying to code around the edge case of people doing this on a headless machine. We ended up making headless a user var that gets passed into our template if it is running on the CI system, otherwise it defaults to non-headless.

**Comment by mitchellh** [comment]
I'd be happy to add more smarts to Packer, but would request a PR for that from someone who is closer to being able to test it. In the mean time, we have a good workaround here in this issue, and we can update the docs to point this out.
