### ISSUE TITLE
Cannot use ' within an environment variable value

### ISSUE THREAD

**Issue by sparkprime** [mitchellh/packer#1733]
It is necessary for packer to replace ' with '"'"' or '\'' (i.e. come out of the string context, then a literal ' which is either "'" or \' then return to the string context).

    {
        "builders": [
            {
              "type":     "null",
              "host":     "127.0.0.1",
              "ssh_username":   "XXX",
              "ssh_password":   "YYY"
            }
        ],
        "provisioners": [
          {
             "environment_vars": [
                "K=simon's\ncat"
             ],
             "inline": [
                "echo \"$K\""
             ],
             "type": "shell"
          }
        ]
    }

**Comment by mitchellh** [comment]
Dup of #2067. Yours was first but I saw and triaged the other one first. Sorry!
