### ISSUE TITLE
Stalls with multiple provisioners of the same type for the docker builder

### ISSUE THREAD

**Issue by alexintel** [mitchellh/packer#1734]
Packer 0.7.2 seems to stall with the multiple provisioners of the same type for the docker builder. This affects shell provisioner and does not work for inline, script, or scripts type in any combination (same type, or different types)

How to reproduce:
- CentOS 6.6 x64
- packer 0.7.2 x64
- Docker version 1.3.1, build c78088f/1.3.1
- uname -a: Linux localhost.localdomain 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- base docker image centos:centos6

```json
{
  "builders": [
    {
      "type": "docker",
      "image": "centos:centos6",
      "export_path": "myimage-centos-6.6-x86_64-docker-{{timestamp}}.tar",
      "pull": "false"
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "sleep 15",
        "yum -y install sudo",
        "echo 'this is a test1'",
        "sudo echo 'this is a test2'"
      ]
    },
    {
      "type": "shell",
      "inline": [
        "echo 'This test will never work1'",
        "sudo echo 'This test will never work2'"
      ]
    }
  ]
}
```

**Comment by mitchellh** [comment]
@warwickp Fixed your crash (unrelated to this issue)

**Comment by mitchellh** [comment]
This is fixed
