### ISSUE TITLE
Build from Kickstart file

### ISSUE THREAD

**Issue by djhaskin987** [mitchellh/packer#1736]
It would be AWESOME if one of the builder types was something like 'kickstart', which would output a kickstart (or preseed?) file for use on either virtual *or* physical hardware. The kickstart file could then be run and used to go from a blank box to fully up and running. It would provide a way to use packer to generate a kickstart file from easier-to-use and better provisioners like puppet or salt. This way, we could put all of our system configuration in salt or puppet, use it to provision our packer templates, spin up a VM via another builder type to test the image, and then use the kickstart builder for use on our physical (production) hardware. :+1:

**Comment by sethvargo** [comment]
Hi @djhaskin987 

Thank you for opening an issue. This seems out of scope for Packer IMO. Packer is designed to create Virtual machines, docker images, etc by applying provisioners. In a way, a kickstart file is a provisioner. There does not exist a way to "output" a kickstart file from a provision because they are both inputs to generating the final output artifact - does that make sense?

**Comment by djhaskin987** [comment]
I believe what I mean is that you add "kickstart" as a builder.

Say I want to create a centOS vagrant box. I set the "build_type" as "virtualbox-kickstart" and give it the URL to the kickstart file I want it to use. Kickstart then downloads and installs the entire OS, and anything else it does. Then, on top of that install, I can use one of the standard provisioners like puppet to further customize it. Then packer takes the VM I have just spun up and turns it into a Vagrant box.

The same goes for a preseed file.

This is essentially asking if we can have a "virtualbox-pxe" build type. I would not use "virtualbox-iso" because the kickstart specifies which ISO to use already. I would not use "virtualbox-ovf" because I am starting from scratch and just want to make a new machine. 

That would be really neat.

**Comment by sethvargo** [comment]
@djhaskin987 I'm confused.. your original issue is asking for a kickstart file as output:

> which would output a kickstart (or preseed?) file for use on either virtual or physical hardware

Is that not what you are asking for? Can you please explain more?

**Comment by djhaskin987** [comment]
I was confused, you're right. I was originally asking for something to output a kickstart file.

I wanted a way to test the set up of a particular machine via vagrant, then deploy it to a physical machine. But packer only makes virtual machines. I guess what I'm asking is for a way to deploy also to physical machines: a kickstart file, a self-installing ISO, ... something for physical realm. That way I can test the configuration of a machine on virtual, but physically deploy the same configuration using a different type of builder.

**Comment by sethvargo** [comment]
I don't think it's unfeasible to _accept_ a kickstart file in Packer as a builder, but I think it's incredibly difficult and out of scope to _produce_ a kickstart file. Does that make sense?

**Comment by djhaskin987** [comment]
Yea, makes sense. A kickstart file would be good to accept, but I can see
how producing one is hard. one can dream though :D you can close this,
thanks for the patience.

Daniel Jay Haskin
http://djhaskin987.github.io/

**Comment by sethvargo** [comment]
Let's keep this open, but I'm going to edit the title a bit :smile:

**Comment by djhaskin987** [comment]
K, thanks :)


Daniel Jay Haskin
http://djhaskin987.github.io/

**Comment by mitchellh** [comment]
Its been awhile and no one I know if is planning on working on this. It sounds like an interesting idea and I'd love to see a PR or more design documents around it, but since none of us over here plan on doing this in the short term, I'm going to close this.
