### ISSUE TITLE
SSH credentials not configurable for Openstack builder

### ISSUE THREAD

**Issue by poolpog** [mitchellh/packer#1750]
The AWS EBS builder provides a configuration parameter for both ssh_username ans ssh_prvate_key.

The Openstack builder provides only ssh_username

To me this is either a bug in the documentation, or a bug in the builder, that SSH creds are not configurable.

Please advise
-JDS

**Comment by mrjsilverman** [comment]
[Solved] One needs clout-init on the base image.

I'd like to respectfully request that this requirement be added to the Packer documentation somewhere. I searched everywhere (everywhere I could think to search) and I could not find this mentioned.

Thanks

**Comment by mitchellh** [comment]
Fixed
