### ISSUE TITLE
Create a "Public" Amazon AMI?

### ISSUE THREAD

**Issue by d11wtq** [mitchellh/packer#1762]
I'm using Packer to produce AMIs that need to be public, and currently have to manually change the permissions of the AMI to "Public" after Packer has run. Is there any way to have the AMI be Public automatically, either with a Builder option, or with a post-processor?

**Comment by sethvargo** [comment]
Hi there,

Thank you for using Packer. Please ask these types of usage questions on the mailing list. We like to keep the GitHub issue tracker for feature requests and bugs :smile:.

As @riywo said, you need to set the `ami_groups` option.
