### ISSUE TITLE
Recalculate spot price if spot request status is "price-too-low"

### ISSUE THREAD

**Issue by delitescere** [mitchellh/packer#1763]
When `"spot_price": "auto"` between the calculation of the spot price and the requesting of a spot instance at that price, the price can (and did) change.

The request is left with a status of `price-too-low`. This, of course, can resolve if the price drops, but it would be better when polling the status of the spot request to detect that status, recalculate the auto price, issue a new spot request, and cancel the first one.

**Comment by CpuID** [comment]
Related: https://github.com/mitchellh/packer/issues/4145

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
