### ISSUE TITLE
Check early in AWS AMI build process if name already exists

### ISSUE THREAD

**Issue by ecweaver** [mitchellh/packer#1774]
If the ami_name already exists, the Create-Image call will fail, after a potentially lengthy build process.  

IWBNI there were a check early in the sequence that can see whether the name exists.  This could be skipped if -force is given on the build command.

   If it gets a permissions error on the Describe Images call, it should shrug and carry on.

**Comment by catsby** [comment]
Fixed in #2187 , we now display an error message within the first second or so if there's a name conflict
