### ISSUE TITLE
Validating a template not possible when output directory exists

### ISSUE THREAD

**Issue by berendt** [mitchellh/packer#1777]
While running a build it is not possible to validate a template file. It should be possible to validate a template file even a build is currently running.

```
% /opt/packer/packer validate packer.json
Template validation failed. Errors are shown below.

Errors validating build 'virtualbox-iso'. 1 error(s) occurred:

* Output directory 'output-virtualbox-iso' already exists. It must not exist.
```

**Comment by marsmensch** [comment]
+1
@mitchellh also just ran into this issue. Would it be possible to simply add PACKER_BOX_NAME add as prefix to the output directory to enable validation without the risk of breaking too much.

**Comment by gjngeldenhuis** [comment]
+1 
Would be really useful, additionally an empty directory should really be treated as valid.
