### ISSUE TITLE
Error when cookbook has invalid metadata

### ISSUE THREAD

**Issue by myappleguy** [mitchellh/packer#1778]
```
[0;32m    amazon-ebs: Chef Client failed. 0 resources updated in 1.309319533 seconds[0m
[0;32m    amazon-ebs: [2014-12-17T18:50:25-05:00] ERROR: Cookbook loaded at path(s) [/tmp/packer-chef-solo/cookbooks-0/vpc-repo-all] has invalid metadata: The `name' attribute is required in cookbook metadata[0m
[0;32m    amazon-ebs: [2014-12-17T18:50:25-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)[0m
```

This is not one of my cookbooks that I added in the provisioners cookbook path.
I am using chef-solo provisioner.

I have not been able to find any information about why this happens other than there was a chef update last year that required adding `name` to the metadata file.

**Comment by mitchellh** [comment]
This is a Chef configuration issue, not much Packer can do about it!
