### ISSUE TITLE
VNC connection fails when headless=false and vmware player

### ISSUE THREAD

**Issue by georgevicbell** [mitchellh/packer#1798]
Receiving: Error connection to VNC: dial tcp 127.0.0.1:5909: ConnectEx tcp: No connection could be made because the target machine actively refused it

The connection is successful when headless=true, fails when false.

I've read that potentially this is an issue with number of VNC connections allowed by vmware player. Perhaps a more helpful error message when running in this configuration would be helpful if that's the case.

Running latest version of packer, vmware player, vix, qemu on windows.

**Comment by sethvargo** [comment]
Hey @georgevicbell 

Have you enabled VNC?

**Comment by mitchellh** [comment]
Closing due to lack of response.
