### ISSUE TITLE
packer cant find builders. Allways return "No builder returned for name. "

### ISSUE THREAD

**Issue by brpaz** [mitchellh/packer#1807]
Hi.
I am starting working with packer but doesnt matter the value of "type" in builders section, it allways gives the same error: "No builder returned for name: "

Here is my packer.json

```
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "guest_os_type": "Ubuntu_64",
      "iso_url": "http://releases.ubuntu.com/14.04/ubuntu-14.04.1-server-amd64.iso",
      "ssh_username": "packer",
      "ssh_password": "packer",
      "ssh_wait_timeout": "30s",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
    }
  ],
  "provisioners": [
    {
      "type": "puppet-masterless",
      "manifest_file": "puppet/manifests/init.pp",
      "hiera_config_path": "puppet/hiera.yaml",
      "modules_path": [ "puppet/modules", "puppet/vendor/modules"],
      "manifest_dir": "puppet/manifests/"
    }
  ],
  "post-processors": [
    "vagrant"
  ]
}
```

*Result of packer inspect command:*

```
Variables:

  <No variables>

Builders:

  virtualbox-iso

Provisioners:

  puppet-masterless
```

*Result of packer validate:*

```
Failed to create build 'virtualbox-iso': 

No builder returned for name: virtualbox-iso
```

I have tried, virtualbox-iso, digitalocean, etc. all the same error.
I am missing something obvious?

I am on Linux Mint 17 with  Packer v0.7.5

Thank you.

**Comment by rickard-von-essen** [comment]
How did you install? What's the result of running:
```ls -l `which packer ` ```

Packer plugins are executables named packer-virtualbox-iso etc. Are you missing those? 

Run with debug (see docs) and gist the output.

**Comment by brpaz** [comment]
Thanks.  I found the problem. Somehow, when extracting the zip from packer website I only copied the main packer bin file. all the others were missing from my system.
