### ISSUE TITLE
'packing' prebuilt artefacts

### ISSUE THREAD

**Issue by techdragon** [mitchellh/packer#1810]
**_Background_**
I have a pretty complex build pipeline that can cleanly produce both VMWare and VirtualBox vagrant _.box files, and their associated metadata.json files. These are complete, ready to go, do *_NOT*\* need anything done to them, they are 100% shippable and ready for immediate use. I ship them to AWS S3 and they can be fetched manually with the URL and then used by Vagrant with the Vagrant files I'm also building. Im trying to use Hashicorp's Atlas and while its nice and all, its _way_ easier to use with Packer (Which is a pretty cool tool :+1:), for these specific Vagrant boxes, the the only way I have been able to build to 'integrate' them with Atlas is with a very awkward shell script that creates appropriate curl commands building inline JSON blobs before making raw HTTP requests to the Atlas API. All in all, kind of a sub optimal way to work with what are generally such nice tools. I look at Packer and think to myself "damn it would be nice to just use packer after I had built my artefacts" but I can't, and heres why.

**_Issue_**
Packer _expects_ it will be mucking about doing all this work itself. Which makes using it for Vagrant & Vagrant-Cloud related post-processing or just for the Packer -> Atlas push functionality, after you have built your own otherwise perfectly fine machine images, very very broken.

A quick example of how hard it is to use any of the things Packer offers without letting it build your VM.  The only way I've been able to worked out from the documentation, to be get packer to not build a VM is using the "null" builder (which is both not really meant for this job and not really "null" and would be better called the "ssh" or "debug" builder, you probably can't change the name now its in use for this, but perhaps the functionality is still able to be changed :pray: ), ... then we configure no provisioners. Now doing this requires setting up some kind of 'dummy ssh server' for the null builder to connect to otherwise you have to boot up the machine image in question which may or may not even be possible if like me, your build toolchain has evolved to produce virtual machine disk images without requiring you install every hypervisor you intend on building images for, which is pretty damn handy and I really don't want to give up. Vagrant and Packer are nice, but I kinda like being able to build KVM, VirtualBox, VMWare, HyperV, and quite a few others, all from the one linux machine without needing any of the respective hypervisors installed. :smiley:  After we jump that hurdle, we run into the fact the the Vagrant Cloud post-processor, requires using the Vagrant post-processor, which again, expects to be able to open up the machine image to work inside it. And lastly we have the Push function to Atlas which might be able to (after jumping the aforementioned very annoying SSH related hurdle) work... but isn't documented enough yet for me to actually tell if I can point it at my already existing build artefacts or not, and if it can't be, then the entire thing is a wash.

It feels very odd that the simple use case of "Here is my metadata.json and my virtual_machine_name.box, you can skip building them, please just push them to the magical cloud place" is so neglected. This is a rather long winded feature request but when I want to use (and even pay for) something (vagrant and vagrant-cloud/Atlas) and my choices are "do it yourself with HTTP requests using curl/requests/etc, just don't get too relaxed, were currently changing things!", "completely rebuild your pipeline" or "further complicate your build pipeline using some custom minimal LiveCD based thing to populate the disk after it pulls down the root filesystem from some extra process you need to configure to serve the LiveCD the files, and don't forget those extra VMWare and you are now running a Windows machine to build linux servers, so don't forget to get that Windows licence" :sob: ... It becomes very hard to resist making it crystal clear how frustrating the lack of the feature is.

P.S. None of this is a complaint, I actually really like pretty much **_everything_** Hashicorp has built, except Packer, and both this feature request and my, hopefully soon to be resolved, dislike of packer are merely the product of 2 months of trying to work with Vagrant, Vagrant Cloud ne. Atlas, and using the ChromeOS build tools to produce multiple new virtual machine images for multiple hypervisors on a pretty much daily basis. :weary:

**Comment by mwhooker** [comment]
Hey, I'm not sure this is still an issue for you, but I thought I'd link to a gist that someone at the company maintains for doing just this https://gist.github.com/pearkes/b26b79b772ed34e53fc3

I know you've already looked at the DIY HTTP solutions, but unfortunately I think that's the best option. I don't think this is a use-case for packer that we want to support, since packer is all about building images, not so much the uploading them part.

Another option would be to look at https://github.com/hashicorp/atlas-go and make a really simple CLI to do what you need. We'd be happy to assist with questions about that on the project or in #hashicorp on [slack](https://signup.hangops.com/)
