### ISSUE TITLE
packer.io site using SSLv3

### ISSUE THREAD

**Issue by hdeadman** [mitchellh/packer#1813]
The corporate outbound SSL proxy where I work isn't allowing me to connect to https://www.packer.io because:

"...McAfee Web Gateway is currently inhibiting connections to some or all sites using SSLV3. The error displayed will say Handshake failed on the top-portion of the banner."

I can get there in other ways but it would be nice if that site server could use a newer form of encryption or allow http browsing.

**Comment by sethvargo** [comment]
Hi @hdeadman 

Thank you for the report. We use a CDN for our docs, but my research is showing that [SSLv3 is disabled for our docs](https://www.ssllabs.com/ssltest/analyze.html?d=www.packer.io&s=104.28.0.48). Is it possible that your proxy servers are caching an old result? Or CDN has completely disabled SSLv3 quite some time ago.

**Comment by hdeadman** [comment]
Thanks, I will pass along that info and close this ticket because it seems that our proxy is at a minimum complaining about the wrong thing. Maybe it doesn't like the multi-domain cert where the CN in the cert doesn't match the host header. (I don't know much about that type of cert or how common it is). 

![image](https://cloud.githubusercontent.com/assets/1556777/5620580/358e7a3c-94fb-11e4-9dcd-8517fc6b206d.png)

![image](https://cloud.githubusercontent.com/assets/1556777/5620593/5b732c7a-94fb-11e4-9160-73b94256b455.png)
