### ISSUE TITLE
"packer --version" doesn't work

### ISSUE THREAD

**Issue by gnawhleinad** [mitchellh/packer#1816]
On my Windows 7 Ultimate x64 machine with https://dl.bintray.com/mitchellh/packer/packer_0.7.5_windows_amd64.zip:

```batch
> packer --version
usage: packer [--version] [--help] <command> [<args>]

Available commands are:
    build       build image(s) from template
    fix         fixes templates from old versions of packer
    inspect     see components of a template
    push        push template files to a Packer build service
    validate    check that a template is valid
    version     Prints the Packer version
```

I can also reproduce the above on my Mac OS X 10.10.1 x64 machine with https://dl.bintray.com/mitchellh/packer/packer_0.7.5_darwin_amd64.zip.

However, with a development build of packer (on my Mac), the output is correct:

```bash
$ ./packer --version
0.7.5
```

**Comment by gnawhleinad** [comment]
See https://gist.github.com/gnawhleinad/0875fd7aba5963dd3a22 for the log on my Mac.

**Comment by sethvargo** [comment]
This has already been reported and is fixed on master
