### ISSUE TITLE
Packer and Virtualbox shoud report more descriptive error if VT-x is being used by another hypervisor.

### ISSUE THREAD

**Issue by nvtkaszpir** [mitchellh/packer#1820]
Improvement suggestion:
If virtualbox returns error due to VT-x is being used by another hypervisor, then it should be also reported to the console. Otherwise currently packer tries to execute SSH connection even though Virtualbox is returning error.

See around line 265 https://gist.github.com/nvtkaszpir/4e5a5fdb63a7e2e5d2cb

Packer version: 0.7.5  9cd66feeacbd9cb318b72eb5ed59428c5b8c37ac+CHANGES
VBoxManage --version output: 4.3.20r96996

Well, I just hit that when I totally forgot about running qemu-kvm in the background.

**Comment by mitchellh** [comment]
This should be fixed on master. VBoxManage doesn't always exit with exit code non-zero on errors, and we now use a regexp to find that.
