### ISSUE TITLE
packer push throws client: 422 Unprocesable Entity error

### ISSUE THREAD

**Issue by jameskyle** [mitchellh/packer#1821]
I modified the atlas demo app slightly to build a virtualbox box since I don't have an AWS account. I also removed the atlas post processor for simplicity. The modified template is below.

When I run:

    packer push -create example-template.json

I get

    Error uploading: client: 422 Unprocessable Entity

Here's the full debug log:

    2015/01/08 12:20:00 [INFO] Packer version: 0.7.5  9cd66feeacbd9cb318b72eb5ed59428c5b8c37ac+CHANGES
    2015/01/08 12:20:00 Packer Target OS/Arch: darwin amd64
    2015/01/08 12:20:00 Built with Go Version: go1.3.3
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: amazon-chroot = /usr/local/bin/packer-builder-amazon-chroot
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: amazon-ebs = /usr/local/bin/packer-builder-amazon-ebs
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: amazon-instance = /usr/local/bin/packer-builder-amazon-instance
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: digitalocean = /usr/local/bin/packer-builder-digitalocean
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: docker = /usr/local/bin/packer-builder-docker
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: googlecompute = /usr/local/bin/packer-builder-googlecompute
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: null = /usr/local/bin/packer-builder-null
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: openstack = /usr/local/bin/packer-builder-openstack
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: parallels-iso = /usr/local/bin/packer-builder-parallels-iso
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: parallels-pvm = /usr/local/bin/packer-builder-parallels-pvm
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: qemu = /usr/local/bin/packer-builder-qemu
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: virtualbox-iso = /usr/local/bin/packer-builder-virtualbox-iso
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: virtualbox-ovf = /usr/local/bin/packer-builder-virtualbox-ovf
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: vmware-iso = /usr/local/bin/packer-builder-vmware-iso
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: vmware-vmx = /usr/local/bin/packer-builder-vmware-vmx
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: atlas = /usr/local/bin/packer-post-processor-atlas
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: compress = /usr/local/bin/packer-post-processor-compress
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: docker-import = /usr/local/bin/packer-post-processor-docker-import
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: docker-push = /usr/local/bin/packer-post-processor-docker-push
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: docker-save = /usr/local/bin/packer-post-processor-docker-save
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: docker-tag = /usr/local/bin/packer-post-processor-docker-tag
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: vagrant = /usr/local/bin/packer-post-processor-vagrant
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: vagrant-cloud = /usr/local/bin/packer-post-processor-vagrant-cloud
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: vsphere = /usr/local/bin/packer-post-processor-vsphere
    Warning! One or more of the builds in this template does not
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: ansible-local = /usr/local/bin/packer-provisioner-ansible-local
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: chef-client = /usr/local/bin/packer-provisioner-chef-client
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: chef-solo = /usr/local/bin/packer-provisioner-chef-solo
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: file = /usr/local/bin/packer-provisioner-file
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: puppet-masterless = /usr/local/bin/packer-provisioner-puppet-masterless
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: puppet-server = /usr/local/bin/packer-provisioner-puppet-server
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: salt-masterless = /usr/local/bin/packer-provisioner-salt-masterless
    2015/01/08 12:20:00 [DEBUG] Discoverd plugin: shell = /usr/local/bin/packer-provisioner-shell
    2015/01/08 12:20:00 Detected home directory from env var: /Users/jkyle
    2015/01/08 12:20:00 Detected home directory from env var: /Users/jkyle
    2015/01/08 12:20:00 Attempting to open config file: /Users/jkyle/.packerconfig
    2015/01/08 12:20:00 File doesn't exist, but doesn't need to. Ignoring.
    2015/01/08 12:20:00 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[vmware-iso:/usr/local/bin/packer-builder-vmware-iso vmware-vmx:/usr/local/bin/packer-builder-vmware-vmx amazon-instance:/usr/local/bin/packer-builder-amazon-instance qemu:/usr/local/bin/packer-builder-qemu virtualbox-ovf:/usr/local/bin/packer-builder-virtualbox-ovf null:/usr/local/bin/packer-builder-null openstack:/usr/local/bin/packer-builder-openstack parallels-pvm:/usr/local/bin/packer-builder-parallels-pvm amazon-ebs:/usr/local/bin/packer-builder-amazon-ebs digitalocean:/usr/local/bin/packer-builder-digitalocean googlecompute:/usr/local/bin/packer-builder-googlecompute docker:/usr/local/bin/packer-builder-docker amazon-chroot:/usr/local/bin/packer-builder-amazon-chroot parallels-iso:/usr/local/bin/packer-builder-parallels-iso virtualbox-iso:/usr/local/bin/packer-builder-virtualbox-iso] PostProcessors:map[docker-import:/usr/local/bin/packer-post-processor-dohave an Atlas post-processor. Artifacts from this template will
    not appear in the Atlas artifact registry.

    cker-import docker-tag:/usr/local/bin/packer-post-processor-docker-tag vagrant-cloud:/usr/local/bin/packer-post-processor-vagrant-cloud vsphere:/usr/local/bin/packer-post-processor-vsphere compress:/usr/local/bin/packer-post-processor-compress docker-push:/usr/local/bin/packer-post-processor-docker-push docker-save:/usr/local/bin/packer-post-processor-docker-save vagrant:/usr/local/bin/packer-post-processor-vagrant atlas:/usr/local/bin/packer-post-processor-atlas] Provisioners:map[chef-solo:/usr/local/bin/packer-provisioner-chef-solo file:/usr/local/bin/packer-provisioner-file puppet-masterless:/usr/local/bin/packer-provisioner-puppet-masterless puppet-server:/usr/local/bin/packer-provisioner-puppet-server salt-masterless:/usr/local/bin/packer-provisioner-salt-masterless shell:/usr/local/bin/packer-provisioner-shell ansible-local:/usr/local/bin/packer-provisioner-ansible-local chef-client:/usr/local/bin/packer-provisioner-chef-client]}
    2015/01/08 12:20:00 Setting cache directory: /Users/jkyle/Projects/atlas-examples/getting-started/ops/packer_cache
    2015/01/08 12:20:00 Detected home directory from env var: /Users/jkyle
    This is just a warning. Atlas will still build your template
    and assume other post-processors are sending the artifacts where
    they need to go.

    Builds: virtualbox-iso

    Error uploading: client: 422 Unprocessable Entity
    2015/01/08 12:20:01 waiting for all plugin processes to complete...

And here's the modified json.

     {
        "builders": [{
                "boot_command": [
                    "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort}}/centos7.ks<enter>"
                ],
                "boot_wait": "5s",
                "disk_size": 40000,
                "guest_additions_path": "/home/vagrant/linux.iso",
                "guest_os_type": "RedHat_64",
                "http_directory": "http",
                "iso_checksum": "04e99a4f1a013b95a7ebc9a90ffa9ac64d28eb9872bc193fbd7c581ec9b6a360",
                "iso_checksum_type": "sha256",
                "iso_url": "http://mirror.stanford.edu/yum/pub/centos/7/isos/x86_64/CentOS-7.0-1406-x86_64-Minimal.iso",
                "shutdown_command": "sudo -S shutdown -P now",
                "ssh_password": "vagrant",
                "ssh_username": "vagrant",
                "ssh_wait_timeout": "20m",
                "type": "virtualbox-iso",
                "vboxmanage": [
                    [
                        "modifyvm",
                        "{{.Name}}",
                        "--memory",
                        "1024"
                    ],
                    [
                        "modifyvm",
                        "{{.Name}}",
                        "--cpus",
                        "1"
                    ]
                ],
                "vm_name": "centos-7.0-x86_64"
            }
        ],
        "push": {
          "name": "jkyle/example-build-configuration"
        },
        "provisioners": [
        {
            "type": "shell",
            "inline": [
                "sleep 30",
                "sudo apt-get update",
                "sudo apt-get install apache2 -y"
            ]
        }],
        "post-processors": []
    }

**Comment by sethvargo** [comment]
Hey @jameskyle,

I am sorry your are having problems with the Atlas push strategy in Packer. We have added some additional logging output that will go out with the next release, making future issues like this easier to debug. Unfortunately that makes that does not help in this case :frowning:.

Just to be certain - can you confirm that the `ATLAS_TOKEN` environment variable is set when you run that `packer` command?

Atlas does not currently support VirtualBox or VMware builders (it is coming soon though), so it does not surprise me that the build is failing. However, the error message we are returning should certainly say that! I just verified that our server is, in fact, returning a 422 with a JSON error, but the client is not rendering the text properly. You should see an error like "VirtualBox builder is not currently supported in Atlas", but for some reason our API client is swallowing that error.

So, to conclude, your specific issue is that Vbox is not currently supported (but that is coming soon). However, I have created https://github.com/hashicorp/atlas-go/issues/22 to track the strange error swallowing, which would have given an error explaining that.

**Comment by jameskyle** [comment]
Yes, ATLAS_TOKEN is set. It also creates the initial build slug on atlas.

The rest makes perfect sense, thanks @sethvargo!
