### ISSUE TITLE
Failed to create build 'amazon-ebs'

### ISSUE THREAD

**Issue by jasonwatt** [mitchellh/packer#1833]
Just updated to 7.5 and am now getting this error when i try to validate my files.
   Failed to create build 'amazon-ebs': 
   Incompatible API version with plugin. Plugin version: 3, Ours: 4

any help would be appriciated

**Comment by jasonwatt** [comment]
figured it out... stupid symlink issue with old files

**Comment by sunil592002** [comment]
Also check which packer it is loading. Because our updated packer is in the directory /usr/local/packer, where as when we run packer build it is checking /usr/bin/packer, where the plugins are missing. So update the bash profile and env variable, so that it works fine

**Comment by ramsumanthr** [comment]
Great, it worked. thanks a lot.
