### ISSUE TITLE
ansible not found by packer

### ISSUE THREAD

**Issue by runseb** [mitchellh/packer#1834]
Hi, I am running packer 0.7.5 on a ubuntu 14.04 machine (created by vagrant).
I installed ansible 1.8.2 by hand , it's in the PATH at /usr/local/bin

but when I try to create a packer image with the docker (1.01) provisioner I get:

    Build 'docker' errored: Error executing Ansible: ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook could not be found. Verify that it is available on the
PATH after connecting to the machine.

    ==> Some builds didn't complete successfully and had errors:
    --> docker: Error executing Ansible: ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1   ansible-playbook could not be found. Verify that it is available on the
    PATH after connecting to the machine.

    ==> Builds finished but no artifacts were created.

the template calls the provisioner like this:

    "provisioners": [
      {
        "type": "ansible-local",
        "playbook_file": "local.yml"
      }
    ],

**Comment by tbaylis** [comment]
I got stuck in the same problem. ```ansible-local``` is a provisioner which runs in the guest system, in your case it is inside the docker container. This is quite a step from what I expected from an ```ansible``` provisioner. Luckily, the issue has been discussed in issue #1555.

If you don't mind running ```ansible``` inside your docker container, you can instead use a base image which comes with ansible preinstalled. I used ```ansible/ubuntu14.04-ansible:stable``` from https://registry.hub.docker.com/u/ansible/ubuntu14.04-ansible/

**Comment by runseb** [comment]
thanks, I thought it was something like this.
I pull the image you referenced and everything worked fine. (once I got my playbook working :) )
