### ISSUE TITLE
Plugin process exited panic

### ISSUE THREAD

**Issue by caleyg** [mitchellh/packer#1838]
I'm using Packer with Docker in the following virtual environment:
```bash
[root@docker ~]# uname -r
2.6.32-504.3.3.el6.x86_64
[root@docker ~]# cat /etc/redhat-release
CentOS release 6.6 (Final)
```

Sometimes during the build process the container is unable to resolve yum dependancies so I'll just kill the build and start over. Most times this can be done with no issues with my network connection to the VM at all. However everytime I interrupt the build with packer, I get a printed !!! CRASH !!! screen. Sometimes though it seems that either packer or docker is doing something to the network. 

```bash
!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 
!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[root@docker docker]# Write failed: Broken pipe
Caley-Mac:~ caleygoff$
```

Pushing Control + C to stop the build will sometimes result in the connection to the VM as a whole being dropped. Tailing the logs while logged into the VM via the console I can see the bridge entering a disabled state. I have eth0 bridged to br0 (default KVM bridge networking). Some of the logs are below. 

Sometimes this works fine however often other times the network connection to the VM is dropped. I'm including a gist of the logs as well.

https://gist.github.com/caleyg/4e1c315e7154ae47dead 

 ```bash
[root@dev1 ~]# virsh console docker.dev.creativeminds.com
Connected to domain docker.dev.creativeminds.com
Escape character is ^]
[root@docker docker]# tail -f /var/log/*

==> /var/log/docker <==
= OK (0)
[80544d1a] -job kill(8d1ccdfbd9833e4a15ab5e482254aa0b198f062af7571e63950f223a2e498c2a, KILL) = OK (0)
[info] DELETE /v1.15/containers/8d1ccdfbd9833e4a15ab5e482254aa0b198f062af7571e63950f223a2e498c2a
[80544d1a] +job rm(8d1ccdfbd9833e4a15ab5e482254aa0b198f062af7571e63950f223a2e498c2a)
[80544d1a] +job log(destroy, 8d1ccdfbd9833e4a15ab5e482254aa0b198f062af7571e63950f223a2e498c2a, centos:6)
[80544d1a] -job log(destroy, 8d1ccdfbd9833e4a15ab5e482254aa0b198f062af7571e63950f223a2e498c2a, centos:6) = OK (0)
[80544d1a] -job rm(8d1ccdfbd9833e4a15ab5e482254aa0b198f062af7571e63950f223a2e498c2a) = OK (0)
br0: port 2(veth7c263bb) entering disabled state
device veth7c263bb left promiscuous mode
br0: port 2(veth7c263bb) entering disabled state
 
==> /var/log/messages <==
Jan 13 20:28:22 docker kernel: br0: port 2(veth7c263bb) entering disabled state
Jan 13 20:28:22 docker kernel: device veth7c263bb left promiscuous mode
Jan 13 20:28:22 docker kernel: br0: port 2(veth7c263bb) entering disabled state
```

**Comment by mitchellh** [comment]
Fixed: https://github.com/mitchellh/packer/commit/ce275969e464145e674bd64e478c8c23fe398a62
