### ISSUE TITLE
ISO file in packer_cache has incorrect file extension

### ISSUE THREAD

**Issue by rasschaert** [mitchellh/packer#1839]
I've got an ISO file at a URL that looks like http://www.example.org/index.php?download=os-1.0.0.iso.

When running packer build with this URL in my template, the ISO file ends up in my packer_cache folder as 9af8e85876f27fe2ccebc42c91068b742edc90bc63952eab568fdbbb7c84992f.**php**. A moment later packer fails with the following error:
```
==> virtualbox-iso: Error attaching ISO: VBoxManage error: VBoxManage: error: Could not get the storage format of the medium '/home/kenny/dir/packer_cache/9af8e85876f27fe2ccebc42c91068b742edc90bc63952eab568fdbbb7c84992f.php' (VERR_NOT_SUPPORTED)
```

From looking at https://github.com/mitchellh/packer/issues/202, I gather that once upon a time packer was aware of this issue and had a workaround.

```
    // VirtualBox is really dumb and can't figure out that the file is an
    // ISO unless it has a ".iso" extension. We can't modify the cache
    // filenames so we just do a copy.
```

So my current issue looks like a regression.

(Packer v0.7.5, VirtualBox 4.3.20)

**Comment by mitchellh** [comment]
Yeah this looks like a regression for years, in fact. Taking a look.
