### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by adkatrit** [mitchellh/packer#1840]
Are there plans to release a packer client API?   It would be preferable for me to be able to call Packer methods directly in my orchestration code as opposed to running cli commands and incurring another installation dependency(the Packer binary).

Perhaps this is already doable by importing mitchellh/packer/packer, but I cannot find the corresponding docs. 

Thanks!

**Comment by vtolstov** [comment]
+1 , if packer can be runned as daemon and have api - it can be used by more tools...

**Comment by vtolstov** [comment]
ping...
Also i think that in some cases api can be like in docker, so we can replace docker via packer and all works =)

**Comment by vtolstov** [comment]
@adkatrit what do you thinks about api, what it need to be, does packer need internal auth system or something else?
I need api too, but not have view of complete api methods.
Now i think about only POST config, run build, get build status, download artifacts.

**Comment by mitchellh** [comment]
This isn't planned. You can use Packer source as a library itself (not too difficult), but be sure to use something like Godeps since we don't promise internal compat.

**Comment by vtolstov** [comment]
Nice idea, to use packer as library and write own server. Thanks!
