### ISSUE TITLE
Tutorial source ID wrong region

### ISSUE THREAD

**Issue by romain-fayoux** [mitchellh/packer#1841]
I might be wrong but in your intro packer tutorial, the source AMI "source_ami": "ami-3d50120d" you're using in the "build" step is only valid for the AWS region "us-west-2" and not "us-east-1".

**Comment by onlydole** [comment]
:+1:

**Comment by sergiopantoja** [comment]
+1

Getting this error if I follow the tutorial's `example.json` exactly:
```
$ packer build example.json
amazon-ebs output will be in this color.

==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Error querying AMI: The image id '[ami-3d50120d]' does not exist (InvalidAMIID.NotFound)
Build 'amazon-ebs' errored: Error querying AMI: The image id '[ami-3d50120d]' does not exist (InvalidAMIID.NotFound)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error querying AMI: The image id '[ami-3d50120d]' does not exist (InvalidAMIID.NotFound)

==> Builds finished but no artifacts were created.
```

The correct Ubuntu 14.04 image for us-east-1 is `ami-9eaa1cf6`.

**Comment by romain-fayoux** [comment]
Great, just saw your pull request, I am new to github so didn't know I could propose to fix stuff myself, I shall try next time !
