### ISSUE TITLE
Instances launched by amazon-ebs builder don't have a name

### ISSUE THREAD

**Issue by ajmath** [mitchellh/packer#1842]
According to the changelog, a feature was added in 0.5.0 that set a name of "Packer Builder" to any instance launched by the amazon builders (issue #642).  We rely on this name tag being present to help cleanup hung packer instances.  We are currently using version 0.7.2 and the issue is present.

**Comment by catsby** [comment]
This should be fixed in the latest release (0.7.5 at time of writing). 
I can't reproduce it with the latest, but if you can please let me know.

Thanks!
