### ISSUE TITLE
Allow for multiple instances of the same builder

### ISSUE THREAD

**Issue by njsaunders** [mitchellh/packer#1845]
With the new AWS instance types (c4, r3, t2) only supporting HVM virtualisation and the old m1 only supporting paravirtual it would be extremely useful to be able to have both registered out of the same template.

I've tried added two amazon-chroot builders to the template, but it dies with:

    Failed to parse template: 1 error(s) occurred:
    * builder with name 'amazon-chroot' already exists

**Comment by rickard-von-essen** [comment]
It's possible, see https://packer.io/docs/templates/builders.html

> ## Named Builds
> Each build in Packer has a name. By default, the name is just the name of the builder being used. In  general, this is good enough. Names only serve as an indicator in the output of what is happening. If you want, however, you can specify a custom name using the name key within the builder definition.

> This is particularly useful if you have multiple builds defined that use the same underlying builder. In this case, you must specify a name for at least one of them since the names must be unique.

**Comment by njsaunders** [comment]
Awesome - Thank you!

**Comment by lmayorga1980** [comment]
Google search brought me here ...

Did it with a different builder but worked...

```json

    "builders": [
    {
      "type": "virtualbox-ovf",
      "name": "virtualbox-ovf-iis",
      "vm_name": "windows2019-iis",
     ...
    },
    {
      "type": "virtualbox-ovf",
      "name": "virtualbox-ovf-sql",
      "vm_name": "windows2019-sqlserver",
```
