### ISSUE TITLE
Add ability to specify mount options

### ISSUE THREAD

**Issue by gdhbashton** [mitchellh/packer#1848]
Hi,

I'm using the `amazon-chroot` builder and have bumped into a silly problem with XFS - it will refuse to mount a filesystem with duplicate UUID. There is a `nouuid` option I can pass to `mount` to stop this behaviour, but there's no way to get that into the commandline that Packer executes.

Since our `source_ami` is the same each time, that means we can never take advantage of the parallelism that Packer offers :(

Cheers,
Gavin.

**Comment by pas256** [comment]
I've had this issue as well.
+1

**Comment by catsby** [comment]
Hey all – https://github.com/mitchellh/packer/pull/2296 should address this by adding a `mount_options` configuration option, which accepts a string of options to supply to mount, ex:

```javascript
{
  "builders": [
    {
      "type": "amazon-chroot",
      "region": "us-west-2",
      "source_ami": "ami-dfc39aef",
      "ami_name": "packer-chrooting-{{timestamp}}",
      "mount_options": ["nouuid"]
    }
  ]
}
```

Each option will be prefixed with the `-o` and sent to the `mount` command. Let me know if that works, or if you have any trouble here. Thanks!
