### ISSUE TITLE
Error deploying to vSphere as a Post Processor

### ISSUE THREAD

**Issue by ehime** [mitchellh/packer#1851]
Information has been censored due to sensitivity.

Here is the issue I am having connecting to vSphere with our packer manifest and 
the error we are receiving, I am hoping you can shed some light on things we need 
such as permissions and such that might be throwing us off. Firstly though the error:

    ==> vmware-iso: Running post-processor: vsphere
    2015/01/19 14:42:05 ui:     vmware-iso (vsphere): Uploading output/OracleLinux-R6-U6-Server-x86_64-vmware/packer-oracle-6.6-x86_64.vmx to vSphere
    2015/01/19 14:42:05 packer-post-processor-vsphere: 2015/01/19 14:42:05 Starting ovftool with parameters: 
      --noSSLVerify=false 
      --acceptAllEulas 
      --name=PackerTest 
      --datastore= 
      --diskMode=thin 
      --network=NETWORK
      --vmFolder=/ 
    output/OracleLinux-R6-U6-Server-x86_64-vmware/packer-oracle-6.6-x86_64.vmx
    vi://USERNAME:PASSWORD@HOST/DATACENTER/host/CLUSTER/Resources/ /

        vmware-iso (vsphere): Uploading output/OracleLinux-R6-U6-Server-x86_64-vmware/packer-oracle-6.6-x86_64.vmx to vSphere
    2015/01/19 14:42:07 Deleting original artifact for build 'vmware-iso'
    2015/01/19 14:42:07 ui error: Build 'vmware-iso' errored: 1 error(s) occurred:

    * Post-processor failed: Failed: exit status 1
    Stdout: Opening VMX source: output/OracleLinux-R6-U6-Server-x86_64-vmware/packer-oracle-6.6-x86_64.vmx
    Error: Locator does not refer to an object: vi://USERNAME:PASSWORD@HOST/DATACENTER/host/CLUSTER/Resources/ /
    Completed with errors

If you look at the portion that I highlighted in red, I believe that this is a large portion of the issue we are having but am unable to validate.

I ran a test just to upload the VMX straight through ovftool and WAS able to validate that this would work

    ovftool                                                                       \
      --name=ConnectionTest                                                       \
      --network=HOST                                                              \
    output/OracleLinux-R6-U6-Server-x86_64-vmware/packer-oracle-6.6-x86_64.vmx    \
    vi://${USERNAME}:${PASSWORD}@HOST:443

Here is the post-processor for my Packer file:

    "post-processors": [{
      "type":           "vsphere",
      "host":           "HOST",
      "username":       "{{user `username`}}",
      "password":       "{{user `password`}}",

      "vm_name":        "PackerTest",
      "vm_network":     "NETWORK",
      "vm_folder":      "/",

      "datacenter":     "DATACENTER",
      "cluster":        "CLUSTER",

      "resource_pool":  " ",
      "disk_mode":      "thin"
    }],

Please contact me directly for further information, thanks.
~jd

**Comment by rylarson** [comment]
I ran into the same problem with this today. The problem is that setting `resource_pool = " "` doesn't work anymore. If you look at the `vi://` url, you have a `Resources/ /` at the end (a space in the URI) that is invalid. 

I believe this pull request fixes the problem: https://github.com/mitchellh/packer/pull/1868

**Comment by ehime** [comment]
Awesome,  when I get back into work on Monday I'll see if this works.
Thanks for the heads up.

**Comment by ehime** [comment]
Looks like even after building I receive the following error

1 error(s) occurred:
* resource_pool must be set

This is after a clean build, so I'm not sure what's going on?

**Comment by ehime** [comment]
Scratch that, I had to actually clone those changes into $GOPATH/src/github.com/mitchellh/packer
and make && make dev

Looks to be running now, I'll see if this fixes my issue

**Comment by ehime** [comment]
Looks like another one of the issues that I just ran across is that the uri needs to be wrapped in double quotes and NOT be encoded/sanitized. Working on rewriting Packer now

**Comment by ehime** [comment]
Fixed with: https://gist.github.com/ehime/59561ef4141971d6d169

Added additional settings
  --ipAllocationPolicy
  --compression
  --powerOn
