### ISSUE TITLE
Build break from change in golang/appengine

### ISSUE THREAD

**Issue by jenspinney** [mitchellh/packer#1857]
If I update dependencies and run `make bin`, I get the following errors:

==> Getting dependencies...
\# github.com/rasa/oauth2-fork-b3f9a68/google
../../rasa/oauth2-fork-b3f9a68/google/appenginevm.go:42: undefined: appengine.Context
../../rasa/oauth2-fork-b3f9a68/google/appenginevm.go:52: undefined: appengine.Context
../../rasa/oauth2-fork-b3f9a68/google/appenginevm.go:97: undefined: appengine.Context
../../rasa/oauth2-fork-b3f9a68/google/appenginevm.go:101: undefined: appengine.Context
../../rasa/oauth2-fork-b3f9a68/google/appenginevm.go:106: undefined: appengine.Context
../../rasa/oauth2-fork-b3f9a68/google/appenginevm.go:107: undefined: appengine.Context
make: *** [bin] Error 2

Google committed a refactor of appengine.Context yesterday which seems to be causing this: https://github.com/golang/appengine/commit/1c3fdc51e1021e4822cf8475c97d3a14a2a6648e

**Comment by vogxn** [comment]
This is annoying. Is there no way to build a specific builder? I'm trying to ingest a patch ( #1367 ) by @renat-sabitov-sirca that is already well over a month behind on being merged.

**Comment by vogxn** [comment]
googlecompute builds for me with changes as implemented in this PR: https://github.com/rasa/oauth2-fork-b3f9a68/pull/1

**Comment by rasa** [comment]
Fixed in https://github.com/rasa/oauth2-fork-b3f9a68/commit/94a7bc9691e0841393b875eaad68fbfd069b2a18
