### ISSUE TITLE
Unable to create DigitalOcean snapshots

### ISSUE THREAD

**Issue by mjp182** [mitchellh/packer#1859]
Hi, 
I've been unable to generate a snapshots of a CentOS 7 droplet.  The droplet is successfully created but then I keep getting the same error:
<pre>Build 'digitalocean' errored: Error creating snapshot: digitalocean request error: map[id:unprocessable_entity message:Droplet already has a pending event.]</pre>

I've included my packer.json template and output log in this gist:
https://gist.github.com/mjp182/07bcad4758faed9bd363

I'm at a loss so any help would be really appreciated.  Thanks.

**Comment by vtolstov** [comment]
I can't check this because i can modify go code for DO builder, but i don't have DO account and can't retest changes. Some time ago i have cloned api of DO in my service, but now we busy and can't modify our cloned api according to do.

**Comment by mjp182** [comment]
Thanks for taking a look.  Since I have a DO account, I'll look at the go code for the DO builder.  Saw the below article yesterday (via @sethvargo).  Seems like a good starting point. 
https://www.digitalocean.com/community/questions/api-data-structure-changes-break-clients

**Comment by frduarte** [comment]
same error here
```
2015/02/04 18:23:23 ui: ==> digitalocean: Creating snapshot: packer-1423068802
2015/02/04 18:23:23 packer-builder-digitalocean: 2015/02/04 18:23:23 sending new request to digitalocean: https://api.digitalocean.com/v2/droplets/40295XX/actions buffer: {"type":"snapshot","name":"packer-1423068802"}
==> digitalocean: Creating snapshot: packer-1423068802
2015/02/04 18:23:23 packer-builder-digitalocean: 2015/02/04 18:23:23 response from digitalocean: {"id":"unprocessable_entity","message":"Droplet already has a pending event."}
2015/02/04 18:23:23 ui error: ==> digitalocean: Error creating snapshot: digitalocean request error: map[id:unprocessable_entity message:Droplet already has a pending event.]
2015/02/04 18:23:23 ui: ==> digitalocean: Destroying droplet...
2015/02/04 18:23:23 packer-builder-digitalocean: 2015/02/04 18:23:23 sending new request to digitalocean: https://api.digitalocean.com/v2/droplets/40295XX buffer:
==> digitalocean: Error creating snapshot: digitalocean request error: map[id:unprocessable_entity message:Droplet already has a pending event.]
==> digitalocean: Destroying droplet...
2015/02/04 18:23:23 ui: ==> digitalocean: Deleting temporary ssh key...
2015/02/04 18:23:23 packer-builder-digitalocean: 2015/02/04 18:23:23 sending new request to digitalocean: https://api.digitalocean.com/v2/account/keys/673XXX buffer:
==> digitalocean: Deleting temporary ssh key...
2015/02/04 18:23:24 ui error: Build 'digitalocean' errored: Error creating snapshot: digitalocean request error: map[id:unprocessable_entity message:Droplet already has a pending event.]
```

**Comment by vtolstov** [comment]
As i understand pending event goes from shutdown, that does not goes immediately.
But as i say - i can't help, i don't have DO api key.

**Comment by justincampbell** [comment]
I'm occasionally experiencing this issue. I made a naive patch to simply retry after 30 seconds if there's an error during snapshot creation: https://github.com/justincampbell/packer/commit/846ae96c5f88c12afa5d996eeeb9716353ca3d66

Output:

```
==> digitalocean: Gracefully shutting down droplet...
==> digitalocean: Creating snapshot: test-1423847942
==> digitalocean: Error creating snapshot: digitalocean request error: map[id:unprocessable_entity message:Droplet already has a pending event.]
==> digitalocean: Waiting 30 seconds to try again...
==> digitalocean: Creating snapshot: test-1423847942
==> digitalocean: Waiting for snapshot to complete...
==> digitalocean: Destroying droplet...
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' finished.
```

I'll have more time next week to clean this up if it seems like a suitable solution.

**Comment by mjp182** [comment]
Cool, thanks Justin.  I'll try this later tonight.

**Comment by pearkes** [comment]
@justincampbell Hey! I've encountered this in Terraform before, and DO now has workable solution that I don't think Packer uses. They basically returned a `locked` bool that tells us whether or not we can operate on the Droplet.

See how it's implemented [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/digitalocean/resource_digitalocean_droplet.go#L383-L388).

I think we should probably move in that direction.

**Comment by pearkes** [comment]
You can see their docs about the response [here](https://developers.digitalocean.com/#retrieve-an-existing-droplet-by-id) too.

**Comment by justincampbell** [comment]
@pearkes Thanks! I'll explore that.

**Comment by sethvargo** [comment]
Hi all,

We just merged some changes into Packer master that fix up a lot of the DigitalOcean API inconsistencies. I don't think that directly fixes this issue, but I would be curious to know if we are seeing any different output, etc?

**Comment by mojotalantikite** [comment]
Just wanted to say I was experiencing the same issue, but went ahead and built the latest packer binaries from master and now things are building fine. Here's some output from one of the last runs:

```
==> digitalocean: Gracefully shutting down droplet...
==> digitalocean: Creating snapshot: base-2015-03-12
==> digitalocean: Waiting for snapshot to complete...
==> digitalocean: Destroying droplet...
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' finished.

==> Builds finished. The artifacts of successful builds are:
--> digitalocean: A snapshot was created: 'base-2015-03-12' in region 'New York 3'
```

**Comment by sethvargo** [comment]
This is fixed on master because it was fixed upstream and will be in the next release. Thank you fir reporting!
