### ISSUE TITLE
Incorrect settings put into Virtualbox box config for ssh

### ISSUE THREAD

**Issue by pixie79** [mitchellh/packer#1865]
Hi,

I have used the virtualbox-iso module to build box image with packer. When I create the image with packer I set the ssh_key_path variable to {{user `home`/.ssh/vagrant}} this works during the build however once the file is build and you try to import the box image it defaults back to using the wrong path to find the key.

```text
$ vagrant ssh-config (output)
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/mark/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

IdentityFile should by dynamic and match the keypath given during the test. If i have multiple boxes installed they might not all use the same key so needing to overwrite the insecure_private_key under .vagrant.d would be wrong.

Mark

**Comment by mitchellh** [comment]
After the box is created, you must tell Vagrant where to find the key file using the Vagrantfile. This data isn't persisted since you may use a different SSH key for image creation than for running. You can use the `vagrantfile_template` parameter to set this.
