### ISSUE TITLE
packer --version doesn't report version

### ISSUE THREAD

**Issue by erikj** [mitchellh/packer#1866]
Packer v0.7.5, OSX and CentOS7

`$ packer version` works as expected, but `$ packer --version`, which is specified in the first line of usage, does not:

```
$ packer --version
usage: packer [--version] [--help] <command> [<args>]
...
```

Obviously a minor thing, but confused me for a few minutes.

Packer's a great tool, thanks!

**Comment by jenspinney** [comment]
Looks like a duplicate of https://github.com/mitchellh/packer/issues/1805 and https://github.com/mitchellh/packer/issues/1797. Sounds like this has already been fixed in master.

**Comment by erikj** [comment]
> Looks like a duplicate of #1805 and #1797. Sounds like this has already been fixed in master.

yep, sorry about that-- I searched only open issues.
