### ISSUE TITLE
Packer push to Atlas Error uploading: client: 422 Unprocessable Entity error

### ISSUE THREAD

**Issue by hyperfocus1337** [mitchellh/packer#1869]
Hello,

I'm experiencing the error in the title when trying to do ```packer push -create -token=xxx template.json```

Here is my Packer template: https://github.com/hyperfocus1337/packer-virtualbox-atlas-template

Debug: https://gist.github.com/hyperfocus1337/32a85a7702e176b0a181

**Comment by sethvargo** [comment]
Hey @hyperfocus1337 

Sorry you are having problems uploading to Atlas. Can you tell me - is this a private resource? Have you set the ATLAS_TOKEN environment variable?

**Comment by hyperfocus1337** [comment]
Yes I think it's private in Atlas. In my ~/.bash_profile I have set "export ATLAS_TOKEN=`cat ~/.vagrant.d/data/vagrant_login_token`"

Is this the information you need?

**Comment by sethvargo** [comment]
@hyperfocus1337 it looks like you are [pulling the environment variable `atlas_token`](https://github.com/hyperfocus1337/packer-virtualbox-atlas-template/blob/master/utopic-vb.json#L3), not `ATLAS_TOKEN` in your config. If you are using ATLAS_TOKEN, you do not need to specify the token in your config, it will be picked up automatically.

**Comment by hyperfocus1337** [comment]
I changed ```atlas_token``` to ```ATLAS_TOKEN``` and ran ```packer push -create -token=xxx template.json``` again which didn't solve the problem yet. I have updated my Packer template and the description for clarification: https://github.com/hyperfocus1337/packer-virtualbox-atlas-template

**Comment by sethvargo** [comment]
@hyperfocus1337 can you please remove all declarations of manually specifying the Atlas token in your template and just use the environment variable (or specify it via the `-token` flag on the command line) please?

**Comment by hyperfocus1337** [comment]
Used this template:

```
{
  "push": {
      "name": "hyperfocus/utopic-vb"
  },

  "provisioners": [

      {
      "type": "shell",
      "execute_command": "echo 'vagrant' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "scripts": [
        "provision/build_time.sh",
        "provision/apt.sh",
        "provision/sudo.sh",
        "provision/vagrant.sh",
        "provision/vbox.sh",
        "provision/cleanup.sh",
        "provision/ansible.sh"
      ]}
  ],

  "builders": [
    {
      "type": "virtualbox-iso",
      "boot_command": [
        "<esc><esc><enter><wait>",
        "/install/vmlinuz noapic preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>",
        "debian-installer=en_US auto locale=en_US kbd-chooser/method=us <wait>",
        "hostname={{ .Name }} <wait>",
        "fb=false debconf/frontend=noninteractive <wait>",
        "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=us keyboard-configuration/variant=us console-setup/ask_detect=false <wait>",
        "initrd=/install/initrd.gz -- <enter><wait>"
      ],
      "boot_wait": "10s",
      "disk_size": 20480,
      "guest_os_type": "Ubuntu_64",
      "headless": "false",
      "http_directory": "http",
      "iso_checksum": "91BD1CFBA65417BFA04567E4F64B5C55",
      "iso_checksum_type": "md5",
      "iso_url": "http://releases.ubuntu.com/14.10/ubuntu-14.10-server-amd64.iso",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_wait_timeout": "10000s",
      "shutdown_command": "echo 'shutdown -P now' > shutdown.sh; echo 'vagrant'|sudo -S sh 'shutdown.sh'",
      "guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",
      "virtualbox_version_file": ".vbox_version",
      "vm_name": "ubuntu-14.10-server-amd64",
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "512"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "1"
        ]
      ]
    }
  ],

  "post-processors": [{

    "type": "vagrant",
      "output": "builds/ubuntu-14.10-server-amd64.box",

    "type": "atlas",
      "artifact": "hyperfocus/utopic-vb",
      "artifact_type": "virtualbox",
      "metadata": {
        "created_at": "{{timestamp}}"
      }
  }]
}
```

With command: ```packer push -create -token=xxx utopic-vb.json ```

Still fails with: ``` Error uploading: client: 422 Unprocessable Entity ```

**Comment by sethvargo** [comment]
@hyperfocus1337 can you please remove the vagrant post-processor and try again? That does not appear to be a valid post-process block - I think you want:

```json
  "post-processors": [
    {
      "type": "vagrant",
      "output": "builds/ubuntu-14.10-server-amd64.box"
    },
    {
      "type": "atlas",
      "artifact": "hyperfocus/utopic-vb",
      "artifact_type": "virtualbox",
      "metadata": {
        "created_at": "{{timestamp}}"
      }
    }
  ]
```

Right now the post-processor isn't being recognized as Atlas.

Similarly, Atlas does not (yet) support building VirtualBox or VMware images. That is coming very soon - I believe the server is returning an error message indicating that, but we have not compiled a new Packer binary with https://github.com/hashicorp/atlas-go/commit/4d0838044233eb99ad75d57b7b596015b3dd73a0 which would output that error.

Please let me know if you have any questions.

**Comment by hyperfocus1337** [comment]
Thanks for the correction, json can be really frustrating to work with. But tested it and still the same issue, but your answer clarifies it. I'll see the feature in the near future then.

**Comment by sethvargo** [comment]
@hyperfocus1337 yea - if I run on Packer master with the updated debug output, I get an error that says `"virtualbox" is not currently supported`.
