### ISSUE TITLE
Error setting up SSH config: asn1: structure error: length too large

### ISSUE THREAD

**Issue by isuftin** [mitchellh/packer#1871]
I am attempting to follow the initial tutorial [here](https://www.packer.io/intro/getting-started/build-image.html). Unfortunately I am not having much luck. I try to launch an EC2 image but unfortunately, it seems as though Packer is unable to SSH into it using the RSA keys I have. 

I am able to SSH into the image in another terminal  while Packer is trying to SSH in as well. 

The main error I am seeing from Packer is: "packer-builder-amazon-ebs: 2015/01/24 23:31:57 Error getting SSH config: Error setting up SSH config: asn1: structure error: length too large"

Because security concerns, the base AMI we have boots up and pulls down user keys from a secured S3 bucket. Due to this, I am unable to allow Packer to create temporary keys to get access.

Here is the pastebin of the issue I am seeing: http://pastebin.com/K0iuFszm

I've googled around a bit and have tracked that error message down to here: https://golang.org/src/encoding/asn1/asn1.go?m=text

Though I've found the error, I have no idea what the issue is aside from perhaps my RSA key is too long?

**Comment by rickard-von-essen** [comment]
See #1445
Are you using an unencrypted ssh key?

**Comment by isuftin** [comment]
The key is, in fact, encrypted: "Proc-Type: 4,ENCRYPTED". I suppose I've been using an ssh-agent in order to handle the encrypt/decrypt mechanism with the convenience of flying through with no passphrase. So as I understand it, I am not able to use an encrypted key, the ssh scheme that Packer uses will not ask me for my pass phrase and will not use the ssh-agent active on my system (since I'm guessing that it doesn't use the OS's SSH executable). I think this gives me a direction for next steps in our setup plans. 

Thank you!

**Comment by rickard-von-essen** [comment]
It is correct that it don't uses openssh, it uses a native go library for
ssh.
