### ISSUE TITLE
Remote file disappears during shell provision run

### ISSUE THREAD

**Issue by matt-richardson** [mitchellh/packer#1872]
We are using packer (0.7.5) with a windows guest (Win2012r2) running on aws (using the amazon-ebs builder).

We are using the [packer windows](https://github.com/joefitzgerald/packer-windows) approach, installing openssh during first boot, then doing the rest of the provisioning run via packer provisioners after that.

For the last few days, I've been fighting with issues when executing a shell provisioner, similar to:

```json
{
    "type": "shell",
    "remote_path": "/tmp/script.bat",
    "binary": true,
    "execute_command": "{{.Vars}} cmd /c C:/Windows/Temp/script.bat",
    "scripts": [
      "./scripts/vagrant-ssh.bat",
      "./scripts/enable-rdp.bat",
      "./scripts/chef.bat",
      "./scripts/win-updates.bat"
    ]
  }
```

Randomly, we are getting an error ` The batch file cannot be found.` when the batch file executes a child command. It appears (after investigation using the -debug flag and using procmon) that the file is getting deleted somehow. 

This doesn't always happen in the same spot, but does always appear after running a child command (eg, powershell), and that exits and returns to flow of execution to the calling batch file.

When this happens (and packer pauses before tearing it down), if I look in the temp folder, the batch file does not exist. (OpenSSH symlinks /tmp/ to c:\windows\temp).

The child command is returning a 0 error code.

I've spent a few hours poring over the code, and even though I'm no golang programmer, I cant find anywhere that this might be happening.

Can anyone suggest further avenues to investigate?

**Comment by matt-richardson** [comment]
I'm suspecting (but unable to prove it yet) that its got something to do with re-using the same file name over multiple shell provisioners. Is this supported?

**Comment by matt-richardson** [comment]
Further info on the batch files - when running locally (via rdp), they complete in exactly the way they should. When running over ssh, they complete exactly the way they should.

**Comment by matt-richardson** [comment]
We have come to the conclusion that we are hitting asynchronous file deletion, e.g. as in http://blogs.msdn.com/b/oldnewthing/archive/2012/09/07/10347136.aspx.

Running each provisioner with a different filename seems to be the solution.

**Comment by sethvargo** [comment]
Hi @matt-richardson 

Do you think there's anything Packer could do to make this a better experience?

**Comment by matt-richardson** [comment]
Hi @sethvargo.

From what I see (without digging into the code), is that if you dont pass a `remote_path` param, then it uses `/tmp/script.sh`. If you do, it overrides this value with whatever is provided.

Maybe, if remote_path is not provided, use a random filename on the target machine.
If it is provided, and there are multiple shell provisioners, we could throw an exception / warning if they use the same name.
We would probably only want to do this on windows (however, this introduces extra complexity/code paths).

Otherwise... We could try deleting the file before uploading the new one, ensuring that the old one is completely gone before writing the new one.

Thoughts?

**Comment by mitchellh** [comment]
I think adding a random number to the end of the script name seems like a fine idea.

**Comment by matt-richardson** [comment]
Thanks @mitchellh!
