### ISSUE TITLE
'No common prefix for achiving files' fails on windows while a common prefix is available

### ISSUE THREAD

**Issue by schutm** [mitchellh/packer#1874]
Hi,

my build fails with:
* Post-processor failed: No common prefix for achiving files: [output-virtualbox-iso\packer-virtualbox-iso-1422310773-disk1.vmdk output-virtualbox-iso\packer-virtualbox-iso-1422310773.ovf]

I suspect this is happening because at packer/post-processor/atlas/util.go, line 29 only checks a for a forward slash '/', while on windows the paths are with backslashes '\'.

**Comment by mitchellh** [comment]
Fixed
