### ISSUE TITLE
Failed to load library libeay32.dll:126

### ISSUE THREAD

**Issue by wimvandijck** [mitchellh/packer#1876]
Hi,

I'm trying to create a VMWare image from an iso, on Windows 7.
Packer v0.7.5

It seems that the vmware-vdiskmanare cannot find the libeay32.dll. However, this file is in the path. I have tried putting it in several locations, but to no avail.
Windows is not my field of expertise, so I'm a bit at a loss here.
Any pointers would be welcome.

```text
D:\data\bento\packer>packer build -var mirror=file:///d:/data/bento/packer/iso rhel-6.2-x86_64.json
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: file:///D:/data/bento/packer/iso/rhel-server-6.2-x86_64-dvd.iso
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Error creating disk: VMware error: SSLLoadSharedLibrary: Failed to load library libeay32.dll:126
==> vmware-iso: Win32 object usage: GDI 4, USER 1
==> vmware-iso: CoreDump: Writing minidump to C:\Users\dbevand\AppData\Roaming\VMware\vmware-vdiskmanager-4216.dmp
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error creating disk: VMware error: SSLLoadSharedLibrary: Failed to load library libeay32.dll:126
Win32 object usage: GDI 4, USER 1
CoreDump: Writing minidump to C:\Users\dbevand\AppData\Roaming\VMware\vmware-vdiskmanager-4216.dmp

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error creating disk: VMware error: SSLLoadSharedLibrary: Failed to load library libeay32.dll:126
Win32 object usage: GDI 4, USER 1
CoreDump: Writing minidump to C:\Users\dbevand\AppData\Roaming\VMware\vmware-vdiskmanager-4216.dmp

==> Builds finished but no artifacts were created.
```

**Comment by rickard-von-essen** [comment]
Could you rerun with debug and gist the log. Also it can be good to try the commands that packer tries to run from the command line, since it seams like your install of VMWare Workstation might be broken.

**Comment by wimvandijck** [comment]
Hey rickard-von-essen. Thanks.

https://gist.github.com/wimvandijck/9592a219f5958124310d

There you go.
I thought of the same thing (running the commands manually), but I couldn't figure out what they were.
(Can you tell, I'm a newbie at packer?). (and, i'm behind a corp firewalled proxy that for some reason won't allow us to go to anything in the .io tld, so I'm afraid I can't rtfm too much :-/ )

I've been playing with it on my personal osx machine, where i've never had issues, and i'm trying to port what i did to my work setup, which is a ms-centric world, which, as said, is not my expertise...

**Comment by mitchellh** [comment]
Hm, I'm going to have to ask for help here. I'm not sure what is causing this, but Packer executes the VMware executables directly with `os/exec` (direct execution). Does Windows have env vars to setup DLL paths or something? Sorry, not sure what to do here.

**Comment by mitchellh** [comment]
(Closing without response)
