### ISSUE TITLE
Invalid value for field 'resource.sourceDisk'

### ISSUE THREAD

**Issue by diddek** [mitchellh/packer#1877]
Hi,

I am trying to create a gce image using the following builder:
{
"builders":[{
  "type": "googlecompute",
  "account_file": "xxx.json",
  "project_id": "xxx",
  "source_image": "ubuntu-1404-trusty-v20141212",
  "zone": "europe-west1-b",
  "image_name": "xxx",
  "image_description": "",
  "machine_type": "n1-standard-1",
  "ssh_username": "root"
}],
"provisioners":[{}]

(with a shell script in the provisioner that runs fine)

However, all I get is an abort and the following message:

googlecompute: Error waiting for image: googleapi: Error 400: Invalid value for field 'resource.sourceDisk': 'https://www.googleapis.com/compute/v1/projects/xxx/zones/europe-west1-b/disks/packer-UUID'.  Referenced resource was not found., invalid

The packer-UUID does exist when I check GCE.

I installed the latest version from git and did a build.

Could you let me know what I am doing wrong?

Kind regards,

Dirk

**Comment by erjohnso** [comment]
Hi Dirk,

I just tried to reproduce this with 0.7.5 on a Mac and it worked fine for me. The only difference to what you have above is I used a US based zone.

Have you tried running the build with `-debug` enabled?

**Comment by diddek** [comment]
Hi Eric,

Thanks - I will retry here and follow up on the ticket.

Kind regards,

Dirk

**Comment by diddek** [comment]
Hi Erik,

Using a US based zone works indeed, so I tried with a different Europe zone - and that worked too.

Strange, not sure why it now works (the only difference is the zones).

Thanks anyway!

Kind regards,

Dirk
