### ISSUE TITLE
builder/packer: Running post-processor/vagrant on Windows guest fails copying C: 

### ISSUE THREAD

**Issue by rickard-von-essen** [mitchellh/packer#1881]
Running packer with the _parallels-builder_ and _vagrant-post-processor_ when building a Windows vagrant box cases a error when trying to copying ```Windows Disks/C```.

Example error message:
```
==> parallels-iso: Running post-processor: vagrant
==> parallels-iso (vagrant): Creating Vagrant box for 'parallels' provider
    parallels-iso (vagrant): Copying: output-parallels-iso/packer-parallels-iso.pvm/VmInfo.pvi
    parallels-iso (vagrant): Copying: output-parallels-iso/packer-parallels-iso.pvm/Windows Disks/C
Build 'parallels-iso' errored: 1 error(s) occurred:

* Post-processor failed: open output-parallels-iso/packer-parallels-iso.pvm/Windows Disks/C: no such file or directory

==> Some builds didn't complete successfully and had errors:
--> parallels-iso: 1 error(s) occurred:

* Post-processor failed: open output-parallels-iso/packer-parallels-iso.pvm/Windows Disks/C: no such file or directory

==> Builds finished but no artifacts were created.
```

**Comment by rickard-von-essen** [comment]
A solution should be to ignore everything under ```Windows Disks``` in the vagrant post-processor.

CC: @legal90 what do you think? Was this reacently added to PD? I don't seem to have bumped in to this before.

**Comment by rickard-von-essen** [comment]
(somewhat related to PD ticket no:57099480)

**Comment by legal90** [comment]
@rickard-von-essen Seems like it is better to ignore `Windows Disks` folder to avoid such messages.
There are no important things, only broken simlinks. 

I'm not sure, but this functionality has been implemented long time ago. I'll figure it out.

**Comment by mefellows** [comment]
Just ran into this issue myself so decided to see if it fixes the issue. Simply excluding that directory seems to do the trick - i'll submit a PR shortly.

**Comment by rickard-von-essen** [comment]
@mefellows or you can take it from https://github.com/rickard-von-essen/packer/commit/798458481ac114ee718ccce2ef5c482a86974861
I'll merge it to master now...
