### ISSUE TITLE
Build -machine-readable in a common machine-readable format

### ISSUE THREAD

**Issue by nyetsche** [mitchellh/packer#1884]
The `-machine-output` provides csv output, which is a good start, but it'd be great if the output could be tailored to say, JSON. 

Our use case is that we're using Packer in a continuous integration environment - once an AMI is built, another step needs that output to use the location/AMI. The metadata (name, tags, etc.) would also be great thought not nearly as essential.

**Comment by reinh** [comment]
A huge :+1:. We also use packer as a part of an automated build system and currently resort to regexp match to determine the AMI id. I'm not sure what use case the current "machine readable" format it is intended to support, but for common uses like "find the AMI is" it is useless.

**Comment by smedefind** [comment]
We're in the exact same boat and would love this feature.

**Comment by ronlipke** [comment]
👍

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but isn't something we're targeting for 1.0, so I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
