### ISSUE TITLE
Packer times out waiting for ssh on Oracle VM Server

### ISSUE THREAD

**Issue by TobyHFerguson** [mitchellh/packer#1886]
When I attempt to install an Oracle VM Server the installation of the OS succeeds and I can (in a separate shell) ssh as the root user into the (rebooted) server. However Packer just waits until its ssh timeout has expired and then halts the build:
```
[toby@dell-server-0 Bonny_Doon]$ ~/packer/packer build -var-file ovs-3.2.1.json template.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: file:///net/qnap1/Public/OVM-3.2.1/OVS-3.2.1-517.iso
==> virtualbox-iso: Starting HTTP server on port 8426
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 2659)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm ovs-3.2.1 --memory 2048 --vram 10
    virtualbox-iso: Executing: modifyvm ovs-3.2.1 --cpus 2
    virtualbox-iso: Executing: modifyvm ovs-3.2.1 --nic2 intnet --intnet2 intnet_2
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Build was halted.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Build was halted.

==> Builds finished but no artifacts were created.
```
To reproduce:

clone the Packer_ssh_timeout branch from my Bonny_Doon repository on github
Provide the necessary ISO (from edelivery.oracle.com) as referenced in the ovs-3.2.1.json variables file
execute
```
packer build -var-file ovs-3.2.1.json template.json 
```
and it should eventually fail.

**Comment by rickard-von-essen** [comment]
Rerun with debug logging, see docs for instructions and gist the log. If possible also provide your config (json, scripts etc).

**Comment by TobyHFerguson** [comment]
Rickard,

gist created: https://gist.github.com/TobyHFerguson/1d4888eeeede1220af80

The only thing missing (I believe) is the OVS-3.2.1 iso.

Thanks for your help.

Toby



On Sat, Jan 31, 2015 at 12:52 AM, Rickard von Essen <
notifications@github.com> wrote:

> Rerun with debug logging, see docs for instructions and gist the log. If
> possible also provide your config (json, scripts etc).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/packer/issues/1886#issuecomment-72310055>.
>



-- 
toby

**Comment by rickard-von-essen** [comment]
It seams like you don't specify a ```ssh_password```.

The error message is quite helpful:

> Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**Comment by TobyHFerguson** [comment]
Ah - I misunderstood what the notion of a default password was! I specified
'vagrant' in the kickstart file but you're right: I didn't specify it in
the template. Silly me. Apologies for wasting your time. There're none so
blind as those that cannot see.

Thanks,

Toby

On Mon, Feb 2, 2015 at 1:12 PM, Rickard von Essen <notifications@github.com>
wrote:

> It seams like you don't specify a ssh_password.
>
> The error message is quite helpful:
>
> Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate,
> attempted methods [none password], no supported methods remain
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/packer/issues/1886#issuecomment-72538694>.
>



-- 
toby
