### ISSUE TITLE
--version flag error

### ISSUE THREAD

**Issue by tphummel** [mitchellh/packer#1891]
I just upgraded packer on ubuntu 14.04 from 0.7.1 to 0.7.5. At some point after 0.7.1 the `--version` flag stopped working even though the usage text says --version is valid. `packer version` works fine though.

```shell
~$ packer --version
usage: packer [--version] [--help] <command> [<args>]

Available commands are:
    build       build image(s) from template
    fix         fixes templates from old versions of packer
    inspect     see components of a template
    push        push template files to a Packer build service
    validate    check that a template is valid
    version     Prints the Packer version

~$ echo $?
1

~$ packer version
Packer v0.7.5

~$ echo $?
0

```

**Comment by sethvargo** [comment]
Hi @tphummel 

This has been fixed in https://github.com/mitchellh/packer/pull/1756 and will be present in the next release.

**Comment by tphummel** [comment]
Oops. I'm sorry for the duplicate. I did a search and didn't see anything at first brush. Thanks.
