### ISSUE TITLE
Packer Docs : AWS AMI ID is invalid

### ISSUE THREAD

**Issue by hanxue** [mitchellh/packer#1892]
On the page https://www.packer.io/intro/getting-started/build-image.html , the example AMI-ID provided `ami-3d50120d` does not exist in US-East-1, but in US-West-2 (Oregon)

Might want to update it to, say, `ami-84aa1cec`

**Comment by jenspinney** [comment]
This was fixed in https://github.com/mitchellh/packer/pull/1856, but the site hasn't been redeployed yet.

**Comment by macarthy** [comment]
Hi,

I'd changed to the AMI mentioned in the #1856 so example.json is like so :

```
 },
 "builders": [{
   "type": "amazon-ebs",
   "access_key": "{{user `aws_access_key`}}",
   "secret_key": "{{user `aws_secret_key`}}",
   "region": "us-east-1",
   "source_ami": "ami-9eaa1cf6",
   "instance_type": "t2.micro",
   "ssh_username": "ubuntu",
   "ami_name": "packer-example {{timestamp}}"
 }]
```
However I get different build errors, relating to VPC

```
packer build -var 'aws_access_key=mykey' -var 'aws_secret_key=keykeykey' example.json
amazon-ebs output will be in this color.

==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 5503c2ec-45e5-5ebf-28ba-b8346c208bd0
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing SSH access on the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)

==> Builds finished but no artifacts were created.

```

Obviously it will confusing to newbies, to set up vpc and security groups etc. Maybe change the instance type to something else might be an idea?

**Comment by blaskey** [comment]
T2 instance types will only run  in a VPC: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances.html#t2-instances-vpc-support

I switched "instance_type" : "t2.micro" to "instance_type": "m3.medium"  (with source_ami ami-9eaa1cf6) and successfully completed the getting-started example.

**Comment by betweenbrain** [comment]
Confirming that @blaskey's change works for ` source_ami ami-9eaa1cf6`

**Comment by jezard** [comment]
@blaskey's change works for me too using a source_ami which I created from an existing instance.

**Comment by mattymaloney** [comment]
Another option for resolving this issue is to specify `subnet_id` and `vpc_id` values in the json build template.

e.g.

```
"builders": [{
  "type": "amazon-ebs",
  ...
  "vpc_id": "vpc-0a1b2c3d",
  "subnet_id": "subnet-5a6b7c8d"
}]
```
