### ISSUE TITLE
Trying to build two boxes from one OVF

### ISSUE THREAD

**Issue by alecgoebel** [mitchellh/packer#1893]
This fails on importing appliance as the image already exists.  

```
==> slave-centos-vbox: Importing VM: boxes/base/base-centos.ovf
==> master-vbox: Importing VM: boxes/base/base-centos.ovf
==> master-vbox: Error importing VM: VBoxManage error: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
==> master-vbox: Interpreting /Users/agoebel/proj/giet/boxes/base/base-centos.ovf...
==> master-vbox: OK.
==> master-vbox: 0%...
==> master-vbox: Progress state: VBOX_E_FILE_ERROR
==> master-vbox: VBoxManage: error: Appliance import failed
==> master-vbox: VBoxManage: error: Could not create the imported medium '/Users/agoebel/VirtualBox VMs/base-centos/base-centos-disk1.vmdk'.
==> master-vbox: VBoxManage: error: VMDK: could not create new file '/Users/agoebel/VirtualBox VMs/base-centos/base-centos-disk1.vmdk' (VERR_ALREADY_EXISTS)
==> master-vbox: VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Appliance, interface IAppliance
==> master-vbox: VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 779 of file VBoxManageAppliance.cpp
==> master-vbox: Deleting output directory...
Build 'master-vbox' errored: Error importing VM: VBoxManage error: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /Users/agoebel/proj/giet/boxes/base/base-centos.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the imported medium '/Users/agoebel/VirtualBox VMs/base-centos/base-centos-disk1.vmdk'.
VBoxManage: error: VMDK: could not create new file '/Users/agoebel/VirtualBox VMs/base-centos/base-centos-disk1.vmdk' (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Appliance, interface IAppliance
VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 779 of file VBoxManageAppliance.cpp
```

Is there a sensible way to do this?  I essentially have my CentOS base image and I'm trying to use packer to install specific software onto two versions.  I'd install from the iso again but I'm going to have similar issues with windows down the line and I have a base image for that fully updated and patched.

**Comment by rickard-von-essen** [comment]
Did you try to set different names for the VMs using the ```vm_name``` settings?

**Comment by alecgoebel** [comment]
I had not, but adding it to the conflicting entries did not change anything.  I've run it a few times today and it seems to be a race condition of whether "master-vbox" or "slave-centos-vbox" errors.  Out of the 10 or so times I've run it, it worked correctly exactly once.

**Comment by mitchellh** [comment]
This is certainly an issue with VirtualBox itself. I've seen this before outside of Packer (just pure VBox), too. The easiest fix is to delete that directory prior to importing... No better way. :(

**Comment by tomjrob** [comment]
@mitchellh: I know this issue is closed, but it seems to be closest to what I'm attempting.

I'm running into the same error as above when trying to use parallel virtualbox-ovf builders from a single source .ovf. Setting the vm_name doesn't seem to change the target path for the disk as can be seen at item 9 when doing a manual `VBoxManage import -n --vsys 0 --vmname test /path/to/.ovf`.

```
Virtual system 0:
 0: Suggested OS type: "Windows7_64"
    (change with "--vsys 0 --ostype <type>"; use "list ostypes" to list all possible values)
 1: VM name specified with --vmname: "test"
 2: Number of CPUs: 1
    (change with "--vsys 0 --cpus <n>")
 3: Guest memory: 2048 MB
    (change with "--vsys 0 --memory <MB>")
 4: Network adapter: orig NAT, config 3, extra slot=0;type=NAT
 5: CD-ROM
    (disable with "--vsys 0 --unit 5 --ignore")
 6: IDE controller, type PIIX4
    (disable with "--vsys 0 --unit 6 --ignore")
 7: IDE controller, type PIIX4
    (disable with "--vsys 0 --unit 7 --ignore")
 8: SATA controller, type AHCI
    (disable with "--vsys 0 --unit 8 --ignore")
 9: Hard disk image: source image=packer-win7_64-1439122079-disk1.vmdk, target path=/Users/tomjrob/VirtualBox VMs/packer-win7_64-1439122079/packer-win7_64-1439122079-disk1.vmdk, controller=8;channel=0
    (change target path with "--vsys 0 --unit 9 --disk path";
    disable with "--vsys 0 --unit 9 --ignore")
```

I believe the fact that the source .ovf file seems to always be imported at the same target location is causing the error.

Am I doing something unsupported or wrong here? I'm interested to know if there is any way of doing multiple (5) parallel builds of virtualbox-ovf type using a single base .ovf image as the source?

**Comment by noonat** [comment]
I also ran into this today trying to do multiple parallel builds from the same OVF file. Works fine with only one OVF build at a time, but fails with more than one.
