### ISSUE TITLE
Option to skip artifact creation

### ISSUE THREAD

**Issue by bbialek-raise** [mitchellh/packer#1896]
I'm using packer to run a script with a shell provisioner but I do not need an AMI created so I exit 1:
```
==> amazon-ebs: Provisioning with shell script: checker
    amazon-ebs: [CHECKER] script completed!  Exiting.
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 1
```

This does what I need but I'm looking for an option that would make the non zero exit unnecessary and for packer to skip creating the AMI right after.  Is there an option for this?  If not, can this be a future feature?

**Comment by pleschev** [comment]
Dup of #1740?

**Comment by bbialek-raise** [comment]
Thanks!  I'll follow the issue you referenced.
