### ISSUE TITLE
ftbfs - atlas-go UploadBuildConfigVersion arguments changed

### ISSUE THREAD

**Issue by bhundven** [mitchellh/packer#1898]
Build log plus discovery of UploadBuildConfigVersion's build issue:
https://gist.github.com/bhundven/00b459e12f29cbfa4e0b

I can checkout a commit prior to:
https://github.com/hashicorp/atlas-go/commit/31b3c9c74514049767120dc093ed662740814b13
...I choose: 137646809ce33b755be51e5e82b40775217ff74d
and it worked fine.

This was reproduced with a clean GOPATH.

**Comment by sethvargo** [comment]
Hi @bhundven 

This is a known issue and will be fixed in https://github.com/mitchellh/packer/pull/1895. Thank you for reporting.
