### ISSUE TITLE
Add App Container / Rocket Builder

### ISSUE THREAD

**Issue by nchammas** [mitchellh/packer#1905]
There is a new [App Container specification](https://github.com/appc/spec/).

The spec already has a few runtime implementations, the most prominent of which is [Rocket](https://github.com/coreos/rocket), from the CoreOS team. Another implementation is [jetpack](https://github.com/3ofcoins/jetpack).

If I understand correctly, the promise of the appc spec is that once you build an image according to that spec, any number of runtimes which implement the spec can run the image.

It would be great if Packer could build images according to this spec as well.

Given the App Container spec's early state, I understand this request may not be actionable for a while.

**Comment by kelseyhightower** [comment]
@nchammas I had a chat with @mitchellh about this during FOSDEM. I'm going to hack on this, expect a PR soon.

**Comment by kelseyhightower** [comment]
@mitchellh Let me know if you've already started working on this one.

**Comment by kelseyhightower** [comment]
The first open question I have is regarding the starting point for building an ACI. Currently there are no "base" ACIs for ubuntu, fedora, etc. We have a couple of options here:

* [bootstrap the OS](http://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#Examples) and run the provisioners in a chroot
* Use the host OS and package up the dirs that need to make up the final ACI.

I would love some community feedback here before I head down the wrong path.

**Comment by AntonioMeireles** [comment]
@kelseyhightower fwiw i 'd vote for the 1st option, for full reproducibility/reliability.

**Comment by rasschaert** [comment]
Another +1 for the first option.

**Comment by blalor** [comment]
+1

**Comment by blalor** [comment]
Bootstrapping is unfortunately rather distribution-dependent.  For Fedora-based distributions, [ami-creator](https://github.com/bluestatedigital/ami-creator) (my fork) works well, and I use it for building base AMIs that are then fed into Packer.  I'm also using it to build base ACIs.  I believe there are similar tools for Debian-based distributions.  It really would be nice to somehow have this built into Packer, but I understand that's a hard problem to solve.  At a minimum, having an ACI builder that could take an image URL as a starting point would be useful.

**Comment by nchammas** [comment]
A lot has changed in this space since I first opened this issue. Is this still relevant?

**Comment by blalor** [comment]
I think it is.  There's first-class support for Docker in Packer, so it'd be nice to see first-class support for building ACIs.  [acbuild](https://github.com/appc/acbuild) exists today as a tool for building ACIs outside of Packer.

**Comment by mwhooker** [comment]
Happy to look at PRs, but this isn't something we're planning to implement for 1.0.  Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
