### ISSUE TITLE
Windows environment variables in variables section

### ISSUE THREAD

**Issue by kocsismate** [mitchellh/packer#1911]
Hi,

I am afraid that currently it is not possible to default variable values from environment variables on Windows.

Here is an excerpt of my template:

```json
"variables": {
    "aws_access_key": "{{env `AWS_ACCESS_KEY`}}",
    "aws_secret_key": "{{env `AWS_SECRET_KEY`}}",
}
```

The 2 envvars are properly set in my system variables section, so eg. running ``echo %AWS_ACCESS_KEY%`` gives me the expected value.

However ``packer inspect`` gives me the same result as the template above:

```
"aws_access_key":  "{{env `AWS_ACCESS_KEY`}}"
"aws_secret_key":  "{{env `AWS_SECRET_KEY`}}"
```

I don't know if it is really a bug or I just misunderstood something.

**Comment by matt-richardson** [comment]
You don't need to explicitly specify these. The [docs](https://www.packer.io/docs/builders/amazon-ebs.html) state that you can just have the environment vars and they will be picked up:

* access_key (string) - The access key used to communicate with AWS. If not specified, Packer will use the environment variables AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY (in that order), if set.
...
* secret_key (string) - The secret key used to communicate with AWS. If not specified, Packer will use the environment variables AWS_SECRET_ACCESS_KEY or AWS_SECRET_KEY (in that order), if set.

**Comment by kocsismate** [comment]
Ah, sure! Thanks for your feedback!

It worked after omitting the access_key and secret_key parameters (and it's also OK, when I keep my explicit declaration). So now, I can't imagine what was the problem last time... Maybe I forgot to reopen the shell when I refreshed my environment variables? Anyway, I close this "issue".
