### ISSUE TITLE
Error when using a variable as a boolean

### ISSUE THREAD

**Issue by noonat** [mitchellh/packer#1913]
I see that #418 is supposed to allow me to use a variable as a boolean, but this doesn't seem to be working anymore. For example, with a config that looks like this:

```json
{
  "variables": {
    "keep": false
  },
  "post-processors": [
    {
      "keep_input_artifact": "{{user `keep`}}",
      "output": "build/virtualbox-iso.box",
      "type": "vagrant"
    }
  ],
  ...
}
```

I get this error:

```bash
$ packer validate packer.json
Failed to parse template: 1 error(s) occurred:
* Post-processor #2.1: 'keep_input_artifact' expected type 'bool', got unconvertible type 'string'

$ packer build packer.json
Failed to parse template: 1 error(s) occurred:
* Post-processor #2.1: 'keep_input_artifact' expected type 'bool', got unconvertible type 'string'
```

**Comment by noonat** [comment]
Opened pull request #1914, which seems to fix it.

**Comment by mitchellh** [comment]
Fixed

**Comment by sci-burns** [comment]
I am using packer 0.10.2 and am getting this exact error on this exact field.  I want to make the vagrant post processor option `keep_input_artifacts` configurable.

Did this regress?

**Comment by rickard-von-essen** [comment]
@sci-burns most likely not. My guess is that you have a broken installation of Packer. Check the note on the packer download page. If you still have problems open a new issue and provide a packer log.

**Comment by sci-burns** [comment]
Actually, it appears to be - I should have read more closely, somebody already opened a regression issue: #2630

**Comment by cassianoleal** [comment]
Has this logic been inverted in 1.0? I'm seeing this now:

```
$ packer -version
Packer v1.0.0

$ cat test.json
{
  "variables": {
    "packer_ssh_agent_auth": true
  }
}

$ packer validate test.json
Failed to parse template: 1 error(s) occurred:

* variable packer_ssh_agent_auth: '' expected type 'string', got unconvertible type 'bool'```

There's no mention to how Packer templates deal with bools in https://www.packer.io/docs/templates/user-variables.html

**Comment by rickard-von-essen** [comment]
@cassianoleal user variables are _string -> string_ maps. Quote your `true` and it should work (with the exception of #2630).

**Comment by cassianoleal** [comment]
@rickard-von-essen Thanks, that seems to work.

It's quite confusing because I never know if the string will work down the line. Also, I usually expect a JSON file to accept valid JSON types.
