### ISSUE TITLE
When specifying post processor vagrant and builder is amazon-ebs, this should probably error

### ISSUE THREAD

**Issue by digitaljedi2** [mitchellh/packer#1918]
Unless this is not a bug, If I had a template that indicated a builder of amazon-xxx and postprocessor of type vagrant i should probably not produce a .box file that is a couple hundred bytes in length, I should probably error as this combination of builder/postproc doesn't really do anything.

**Comment by rickard-von-essen** [comment]
Could you clarify why you think this is a bug.

**Comment by digitaljedi2** [comment]
is a 500 byte box file (which won't import, be of use) is designed as expected?

**Comment by rickard-von-essen** [comment]
Sorry read MB, not bytes. Please supply a example config.

**Comment by digitaljedi2** [comment]
Template validates..

$ packer validate busted-image.json
Template validated successfully.

# Using the Ubuntu trusty amd64 ebs hvm ami
$ cat busted-image.json
{
  "variables": {
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "us-east-1",
      "source_ami": "ami-08f8b160",
      "instance_type": "c3.large",
      "ssh_username": "ubuntu",
      "ami_name": "busted-box-{{timestamp}}"

    }
  ],
  "provisioners" : [
    {
      "type": "shell",
      "inline": [
        "sudo rm /boot/grub/menu.lst",
        "sudo update-grub-legacy-ec2 -y",
        "# The below command seems to be the only way to do an unattended dist-upgrade",
        "sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' dist-upgrade",
        "sudo ucf --purge /boot/grub/menu.lst",
        "sudo apt-get -y update",
        "sudo apt-get -y dist-upgrade"
      ]
    },
    {
      "type": "shell",
      "scripts": [
        "scripts/dostuff.sh"
      ],
      "type": "shell"
    }
  ],
  "post-processors": [
    {
      "compression_level": "6",
      "keep_input_artifact": true,
      "output": "bustedbox.box",
      "type": "vagrant"
    }
  ]
}
==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

us-east-1: ami-d0c08bb8
--> amazon-ebs: 'aws' provider box: bustedbox.box

$ du -h bustedbox.box
4.0K	bustedbox.box

However curious I tried...
$ vagrant box add bustedbox bustedbox.box
==> box: Adding box 'bustedbox' (v0) for provider:
    box: Downloading: file:///bustedbox.box
==> box: Successfully added box 'bustedbox' (v0) for 'aws'!

Interesting, should I attempt to make a Vagrantfile and watch my mind be blown? Or do I already know what's going to happen?

**Comment by sethvargo** [comment]
Vagrant has first-class support for EC2, and it is theoretically possible to package a vagrant box for vagrant with vagrant-ec2.

**Comment by digitaljedi2** [comment]
This appears to be resolved in latest 0.7.x version of packer.  Closing.
