### ISSUE TITLE
Packer --version option is broken

### ISSUE THREAD

**Issue by alexintel** [mitchellh/packer#1927]
Packer version 0.7.5

Trivial issue: --version option is not working as documented. From the usage example one might expect --version option to work in the same way as 'packer version' command.
packer --version
usage: packer [--version] [--help] <command> [<args>]

Available commands are:
    build       build image(s) from template
    fix         fixes templates from old versions of packer
    inspect     see components of a template
    push        push template files to a Packer build service
    validate    check that a template is valid
    version     Prints the Packer version

Although this works as expected and documented:
packer version
Packer v0.7.5

**Comment by sethvargo** [comment]
Hi @alexintel 

This has been fixed in https://github.com/mitchellh/packer/pull/1756 and will be present in the next release.
