### ISSUE TITLE
Amazon instance builder doesn't inherit $PATH from profile.d scripts when running ec2 tools

### ISSUE THREAD

**Issue by bhourigan** [mitchellh/packer#1929]
On Amazon Linux the ec2 ami tools are installed in /opt/aws/bin, which is added to $PATH via /etc/profile.d/aws-apitools-common.sh. when sudo -n is invoked in builder/amazon/instance/builder.go the profile.d scripts are not loaded, so the command fails.

**Comment by catsby** [comment]
closing because #1930 was merged, thanks!
