### ISSUE TITLE
Amazon instance builder uses deprecated parameter when calling ec2-upload-bundle

### ISSUE THREAD

**Issue by bhourigan** [mitchellh/packer#1931]
The parameter --region has been renamed to --location in ec2-upload-bundle since at least 1.5.2.

**Comment by ramsey** [comment]
According to the documentation, this is the other way around:
http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/CLTRG-ami-upload-bundle.html

For `--location`:
> Deprecated. Use the `--region` option instead, unless your bucket is constrained to the EU location (and not eu-west-1). The `--location` flag is the only way to target that specific location restraint.

**Comment by ramsey** [comment]
FYI, I came across this because my bundle upload failed with this message:

    amazon-instance: --location has invalid value 'us-east-1'

So, it's at least broken if you set your region to "us-east-1" in the Packer JSON file. `--location` accepts "US" but not "us-east-1," for some reason.

**Comment by catsby** [comment]
I just merged #2196 which changes the flag to `--region`.
