### ISSUE TITLE
Fetch subnet_id if vpc_id is specified

### ISSUE THREAD

**Issue by ossareh** [mitchellh/packer#1935]
Hi,

Please see: https://gist.github.com/ossareh/33910638e985f8356dbe

We're not using the default VPC in our AWS account so we supply vpc_id, however packer is fetching a subnet_id from the default VPC, as such when trying to create an instance there is an error.

If vpc_id is specified packer should use a subnet_id from that VPC.

**Comment by henrysher** [comment]
@ossareh may i know your configuration for packer? according to the packer document, subnet_id and vpc_id are both required in your case, do you have set the specified vpc_id in your config file?

**Comment by catsby** [comment]
Hey @ossareh – I'm sorry you ran into this issue. 

Packer does not really fetch subnets at all. Any AWS account created after 2013-12-04 comes with a Default VPC. That VPC itself has default subnets. When you do not specify a `vpc_id` in your Packer config, an instance is launched in your default VPC. In the Default VPC, if no subnet is specified, AWS with use one of the defaults. That logic is on the AWS side though, Packer does not make the subnet selection. 

Unfortunately, it's not currently possible for users to designate a default subnet for a VPC (docs on that are [here][1]). That means that if you specify a VPC that is not the default, there is no automatic subnet selection. As a result, Packer needs a `subnet_id` to be specified if you're launching an instance in a non-default VPC. 

Given this, I believe the only thing we can do here is update the documentation to specify that a `subnet_id` should be supplied if you're using a non-default VPC. 

Thanks for writing in. I'll update the documentation shortly.

If you're interested, more info on Default VPCs can be read here:

- http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/default-vpc.html

[1]: https://aws.amazon.com/vpc/faqs/
