### ISSUE TITLE
Vmware-iso fails to boot if os type is specified

### ISSUE THREAD

**Issue by spuder** [mitchellh/packer#1943]
If you have the following line in your packer file and you use the vmware-iso builder on OSX with VmWare fusion, then the machine will fail to start. The failure is silent. 

    "guest_os_type": "Ubuntu_64",

Video Showing problem
https://www.youtube.com/watch?v=AGt1Rm0vnoA

Google Groups discussion
https://groups.google.com/forum/#!topic/packer-tool/qjGb34DnFc4

PackerFile

```json
{
  "variables": {
    "ssh_name": "vagrant",
    "ssh_pass": "vagrant"
  },
  "builders": [
    {
      "type": "vmware-iso",
      "iso_urls": [
        "iso/ubuntu-14.04.1-server-amd64.iso",
        "http://releases.ubuntu.com/14.04.1/ubuntu-14.04.1-server-amd64.iso"
      ],
      "iso_checksum_type": "md5",
      "iso_checksum": "ca2531b8cd79ea5b778ede3a524779b9",
      "ssh_username": "{{user `ssh_name`}}",
      "ssh_password": "{{user `ssh_pass`}}",
      "ssh_wait_timeout": "6m",
      "shutdown_command": "echo {{user `ssh_pass`}} | sudo -S shutdown -P now",
      "http_directory" : "http",
      "guest_os_type": "Ubuntu_64",
      "boot_wait": "10s",
      "boot_command": [
        "<esc><esc><enter><wait>",
        "/install/vmlinuz noapic ",
        "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
        "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
        "fb=false debconf/frontend=noninteractive ",
        "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
        "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
        "initrd=/install/initrd.gz -- <enter>"
      ]
    }
  ]
}
```

The work around is to remove the offending line from the packerfile

"guest_os_type": "Ubuntu_64",

**Comment by rickard-von-essen** [comment]
For VMware Fusion the guest os type should be ```ubuntu-64```.

For great examples of packaging vagrant boxes with packer see [bento](https://github.com/chef/bento), specially [ubuntu-14.10-amd64.json](https://github.com/chef/bento/blob/master/packer/ubuntu-14.10-amd64.json).

**Comment by spuder** [comment]
I still think this is a bug, or at least a feature request because. 

- `packer validate` did not catch this error
- `packer build --debug` showed no information about why the VM wouldn't start. 
- There is no documentation that lists why 'Ubuntu_64' is treated differently than 'ubuntu-64'

**Comment by rickard-von-essen** [comment]
Ok, agreed. The documentation should state which command to run to see the valid values (in the same way as the virtualbox-iso builder does).

```packer validate``` validates the syntax nothing more.

Debug logging is enabled with ```PACKER_LOG```, see http://www.packer.io/docs/other/debugging.html

**Comment by dragon788** [comment]
Here's a site with a very nice list of the vmx guest os options for VMware. http://sanbarrow.com/vmx/vmx-guestos.html

**Comment by mitchellh** [comment]
Not much more I can do than this, since VMware itself doesn't give us an error and I don't think I want to hardcode all the valid values in Packer. :) This should help though:

![2015-06-10 at 11 30 am](https://cloud.githubusercontent.com/assets/1299/8090648/33760920-0f64-11e5-8cd1-7db9f8d2dce3.png)
