### ISSUE TITLE
Support encrypted data bag secret

### ISSUE THREAD

**Issue by tas50** [mitchellh/packer#1945]
Similar to how the validation key is currently handled you should be able to provide a local path to your encrypted data bag secret so that your chef client runs can use this.  Currently you have to use a file then shell provisioner before the chef client provisioner to upload the file and then move a file into place.  The workflow could be greatly simplified for new users.

**Comment by rbowlby** [comment]
+1, first hour with packer and more logic I'm now adding to a shell provisioner. :(

**Comment by fishnix** [comment]
:+1:  yes please!

**Comment by eherot** [comment]
:+1:

**Comment by ronlipke** [comment]
👍

**Comment by ronlipke** [comment]
Thank you!
