### ISSUE TITLE
Source AMI not tagged when using the ami_regions option

### ISSUE THREAD

**Issue by andresvia** [mitchellh/packer#1946]
I'm not sure if this was a deliberated decision or if it is a bug, also packer is not smart enough to detect that the source instance is running in one of the regions specified in `ami_regions`, as a result I end with duplicated artifact in one of the regions and the source one is not tagged or included in the output.

Let me know if you need me to perform any other test.

	1424716048,,ui,say,==> amazon-ebs: Stopping the source instance...
	1424716048,,ui,say,==> amazon-ebs: Waiting for the instance to stop...
	1424716071,,ui,say,==> amazon-ebs: Creating the AMI: xx-base 14.04 1424715727
	1424716072,,ui,message,    amazon-ebs: AMI: ami-Region1-dd3823
	1424716072,,ui,say,==> amazon-ebs: Waiting for AMI to become ready...
	1424716206,,ui,say,==> amazon-ebs: Copying AMI (ami-Region1-dd3823) to other regions...
	1424716206,,ui,message,    amazon-ebs: Copying to: us-west-1
	1424716206,,ui,message,    amazon-ebs: Copying to: us-west-2
	1424716206,,ui,message,    amazon-ebs: Copying to: us-east-1
	1424716206,,ui,message,    amazon-ebs: Waiting for all copies to complete...
	1424718356,,ui,say,==> amazon-ebs: Modifying attributes on AMI (ami-Region1-dd3831)...
	1424718356,,ui,message,    amazon-ebs: Modifying: description
	1424718357,,ui,message,    amazon-ebs: Modifying: users
	1424718357,,ui,say,==> amazon-ebs: Modifying attributes on AMI (ami-Region2-f2a170)...
	1424718357,,ui,message,    amazon-ebs: Modifying: description
	1424718357,,ui,message,    amazon-ebs: Modifying: users
	1424718358,,ui,say,==> amazon-ebs: Modifying attributes on AMI (ami-Region3-456445)...
	1424718358,,ui,message,    amazon-ebs: Modifying: description
	1424718358,,ui,message,    amazon-ebs: Modifying: users
	1424718358,,ui,say,==> amazon-ebs: Adding tags to AMI (ami-Region1-dd3831)...
	1424718358,,ui,message,    amazon-ebs: Adding tag: "Name": "xx-base 14.04 1424715727"
	1424718358,,ui,message,    amazon-ebs: Adding tag: "CreatedAt": "1424715727"
	1424718358,,ui,message,    amazon-ebs: Adding tag: "ubuntu-version": "trusty"
	1424718358,,ui,message,    amazon-ebs: Adding tag: "build_number": "xyz"
	1424718358,,ui,say,==> amazon-ebs: Adding tags to AMI (ami-Region2-f2a170)...
	1424718358,,ui,message,    amazon-ebs: Adding tag: "Name": "xx-base 14.04 1424715727"
	1424718358,,ui,message,    amazon-ebs: Adding tag: "CreatedAt": "1424715727"
	1424718358,,ui,message,    amazon-ebs: Adding tag: "ubuntu-version": "trusty"
	1424718358,,ui,message,    amazon-ebs: Adding tag: "build_number": "xyz"
	1424718359,,ui,say,==> amazon-ebs: Adding tags to AMI (ami-Region3-456445)...
	1424718359,,ui,message,    amazon-ebs: Adding tag: "Name": "xx-base 14.04 1424715727"
	1424718359,,ui,message,    amazon-ebs: Adding tag: "CreatedAt": "1424715727"
	1424718359,,ui,message,    amazon-ebs: Adding tag: "ubuntu-version": "trusty"
	1424718359,,ui,message,    amazon-ebs: Adding tag: "build_number": "xyz"
	1424718359,,ui,say,==> amazon-ebs: Terminating the source AWS instance...
	1424718366,,ui,say,==> amazon-ebs: Deleting temporary security group...
	1424718366,,ui,say,==> amazon-ebs: Deleting temporary keypair...
	1424718366,,ui,say,Build 'amazon-ebs' finished.
	1424718366,,ui,say,\n==> Builds finished. The artifacts of successful builds are:
	1424718366,amazon-ebs,artifact-count,1
	1424718366,amazon-ebs,artifact,0,builder-id,mitchellh.amazonebs
	1424718366,amazon-ebs,artifact,0,id,us-west-1:ami-Region1-dd3831%!(PACKER_COMMA)us-east-1:ami-Region2-f2a170%!(PACKER_COMMA)us-west-2:ami-Region3-456445
	1424718366,amazon-ebs,artifact,0,string,AMIs were created:\n\nus-west-1: ami-Region1-dd3831\nus-east-1: ami-Region2-f2a170\nus-west-2: ami-Region3-456445
	1424718366,amazon-ebs,artifact,0,files-count,0
	1424718366,amazon-ebs,artifact,0,end
	1424718366,,ui,say,--> amazon-ebs: AMIs were created:\n\nus-west-1: ami-Region1-dd3831\nus-east-1: ami-Region2-f2a170\nus-west-2: ami-Region3-456445

**Comment by henrysher** [comment]
quite similiar to #2123, after avoiding the duplicate ami, this issue will not appear any more. I have submitted a PR #2175, wish could help.

**Comment by mitchellh** [comment]
Fixed by #2175

**Comment by andresvia** [comment]
Thank you guys!
