### ISSUE TITLE
Need  ENV or config to change /tmp location

### ISSUE THREAD

**Issue by dantran** [mitchellh/packer#1948]
My releng env has small /tmp space and packer will fail to run.  Please add a way to configure tmp directory

**Comment by sethvargo** [comment]
You can set `TMPDIR`. This is not a Packer-specific (or even Go-specific) thing. Most OSes obey the `TMPDIR` setting. I believe it's `TEMP_DIR` on Windows, but I am not sure about that.

If you set that envvar on all your releng-managed machines, most tools will use the different directory :smile:.

**Comment by dantran** [comment]
Thanks
