### ISSUE TITLE
Link atlas app

### ISSUE THREAD

**Issue by derek-adair** [mitchellh/packer#1950]
I'd like to be able to link applications in my packer templates.  This seems pretty crucial in the workflow of creating vagrant boxes that mirror prod.  I didn't see anything here so i figured I'd submit.  Currently I work around this by keeping my app code near my packer script and using a file provisioner.

**Comment by mitchellh** [comment]
We're working on this in Atlas :) I don't think this is a Packer issue at the moment. We're still reworking parts of this workflow.
