### ISSUE TITLE
after resize a vagrant box, packer build has issue with ssh

### ISSUE THREAD

**Issue by SydOps** [mitchellh/packer#1951]
Hi 

I followed [Resize a Hard Disk for a Virtual Machine
](https://gist.github.com/christopher-hopper/9755310) to resize my vagrant box (centos 6.5) and then package it (named `package.box`)

I can add box with `package.box` in vagrant and vagrant up/ssh without issue. 

But when i try to use it as virtualbox_ovf in packer, 

    tar -xz < package.box

my template.json (builders part)

```
  "builders": [
    {
      "headless": "true",
      "name": "centos6-x86_64-vagrant",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now",
      "source_path": "box.ovf",
      "ssh_username": "packer",
      "ssh_password": "packer",
      "type": "virtualbox-ovf",
      "ssh_wait_timeout": "30s",
      "vm_name": "centos6-x86_64-vagrant"
    }
  ],
```

It is on hold at "Waiting for SSH to become available..."

What's the issue?

my packer and vagrant version are all latest (packer 0.75, vagrant 1.7.2)

**Comment by SydOps** [comment]
when `packer build`, I try to ssh it directly, I can't 

    ssh -p 2300 127.0.0.1

here is the error message:

```
==> centos6-x86_64-vagrant: Downloading or copying Guest additions
    centos6-x86_64-vagrant: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> centos6-x86_64-vagrant: Importing VM: tmp/vagrant/box.ovf
==> centos6-x86_64-vagrant: Creating forwarded port mapping for SSH (host port 2300)
==> centos6-x86_64-vagrant: Starting the virtual machine...
    centos6-x86_64-vagrant: WARNING: The VM will be started in headless mode, as configured.
    centos6-x86_64-vagrant: In headless mode, errors during the boot sequence or OS setup
    centos6-x86_64-vagrant: won't be easily visible. Use at your own discretion.
==> centos6-x86_64-vagrant: Waiting 10s for boot...
==> centos6-x86_64-vagrant: Typing the boot command...
==> centos6-x86_64-vagrant: Waiting for SSH to become available...
==> centos6-x86_64-vagrant: Timeout waiting for SSH.
==> centos6-x86_64-vagrant: Unregistering and deleting imported VM...
==> centos6-x86_64-vagrant: Deleting output directory...
Build 'centos6-x86_64-vagrant' errored: Timeout waiting for SSH.
```

**Comment by sethvargo** [comment]
Are you using a non-standard SSH port? I think you may need to tell Packer the [SSH port](https://www.packer.io/docs/builders/virtualbox-iso.html#ssh_port).

**Comment by SydOps** [comment]
I didn't set SSH port in Vagrant, all default, here is my Vagrantfile:

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "box"
end
```

After saw your reply, I add ssh_port in template.json as below

    "ssh_port": "22"

But after `packer build`, ssh timeout waiting again.

**Comment by sethvargo** [comment]
@SydOps it looks like you are trying to use port 2300 though, not 22.

```text
==> centos6-x86_64-vagrant: Creating forwarded port mapping for SSH (host port 2300)
```

**Comment by SydOps** [comment]
@sethvargo 

Thanks.

When run packer build, it does forward port mapping with random port. It is controlled by packer. 

In template.json, I didn't set port mapping and I have pasted the content in my question already.

**Comment by AGovorukha** [comment]
SOLVED
add to your builder definition next strings:

                "ssh_host_port_min":    "2345",
                "ssh_host_port_max":    "2345",
                "vboxmanage":   [
                        ["modifyvm", "{{.Name}}", "--natpf2", "packerssh,tcp,,2345,,22"]
                ]

The probles is, that 
2015/03/25 11:46:32 ui: ==> virtualbox-ovf: Creating forwarded port mapping for SSH (host port 2345)
==> virtualbox-ovf: Creating forwarded port mapping for SSH (host port 2345)
2015/03/25 11:46:32 packer-builder-virtualbox-ovf: 2015/03/25 11:46:32 Executing VBoxManage: []string{"modifyvm", "ubuntu14_1427276749", "--natpf1", "packerssh,tcp,127.0.0.1,2345,,22"}

doesn't work.
I don't know why.
So, you can add your own rule manually. And it's work fine.

**Comment by sethvargo** [comment]
@SydOps can you confirm this solves your issue?

**Comment by eanderton** [comment]
I have a similar problem now: the VirtualBox builder doesn't know to connect to the forwarded SSH port.  So while VirtualBox sets a random port to forward (e.g. 3113), the builder still tries to connect to port 22.  And setting ssh_port doesn't automatically get set to that random port either.  So you wind up having to do something like what  @AGovorukha did above:
```  
  "ssh_host_port_min":    "2345",
  "ssh_host_port_max":    "2345",
  "ssh_port": "2345",
```

To me, this looks like a bug since the port range is documented as supporting parallelized builds, yet the builder doesn't use the allocated port number to connect via SSH, if `ssh_port` is not specified.

**Comment by mitchellh** [comment]
No response
