### ISSUE TITLE
scp Implementation

### ISSUE THREAD

**Issue by madhurranjan** [mitchellh/packer#1958]
Hi ,
I'm a great fan of packer. Specifically, your scp implementation is great and covers a lot of details .I'm trying to write my own simple scp implementation but I'm having trouble. I specifically had a question regarding https://github.com/mitchellh/packer/blob/master/communicator/ssh/communicator.go#L407 

Looks like you pass the source directory name ? I'm trying to do the same but it throws up error. Can you share any implementation experience that I can use?

**Comment by mitchellh** [comment]
I don't remember, sorry. I used the RCP and Oracle blogs as references.
