### ISSUE TITLE
Packer is intermittently halting the VM before provisioning is complete.

### ISSUE THREAD

**Issue by neilluna** [mitchellh/packer#1961]
Packer is intermittently halting the VM before provisioning is complete.

Packer sometimes halts the VM before provisioning is complete. The point at which it halts the VM seems random. I created a placeholder provisioning script that does nothing except count up to 10 minutes. In my tests, the point at which Packer halts the VM is sometimes 5 seconds into the script, and sometimes 8 minutes into the script.

The json, provisioner, output, and log files can be found here.
https://gist.github.com/neilluna/06b751a3e3233937111f

**Comment by mitchellh** [comment]
I think this was a bug upstream in the SSH library we were using which is now fixed. The SSH library was reporting early that the script exited.

**Comment by neilluna** [comment]
So, the latest stable version of Packer should not have the problem anymore?

**Comment by mitchellh** [comment]
It is unreleased but the master branch should yes, as long as you make sure you update all your upstreams (`make updatedeps`)
