### ISSUE TITLE
Page https://www.packer.io/docs/builders/virtualbox-iso.html is not properly escaped

### ISSUE THREAD

**Issue by lyrixx** [mitchellh/packer#1962]
![screenshot1](https://cloud.githubusercontent.com/assets/408368/6476531/69b28c92-c217-11e4-9c69-880fdbf5b1dc.png)

```diff
- "&lt;esc&gt;&lt;esc&gt;&lt;enter&gt;&lt;wait&gt;",
+ "<esc><esc><enter><wait>",
```

;)

**Comment by dragon788** [comment]
I had fixed this, but apparently Travis CI was having issues when the PR (https://github.com/mitchellh/packer/pull/1883) got merged. I'll make another fork and request it again.

**Comment by dragon788** [comment]
Made a new PR (https://github.com/mitchellh/packer/pull/1980). @sethvargo Do you know which tool is used to parse the .markdown files into HTML and serve it up? I have a feeling if this doesn't render correctly then it is a bug in that tool and not the documentation.

**Comment by sethvargo** [comment]
We use middleman and middleman-hashicorp

**Comment by dragon788** [comment]
@sethvargo I believe this is resolved, as when I looked at those pages this week I saw the correct characters in the boot command examples.

**Comment by mitchellh** [comment]
I believe you :)
