### ISSUE TITLE
Floppy filenames changed

### ISSUE THREAD

**Issue by majkinetor** [mitchellh/packer#1963]
I have this issue where scripts I use during Windows setup have their names changed. It was usually only casing but now I have also extension shortening. 

In template I have:

`` "floppy_files": [ "./Autounattend.xml", "./scripts" ]``

`ls ./scripts`
<pre>
_provision.ps1
_setup.ps1
enable-rdp.ps1
enable-winrm.ps1
Get-WUInstall.ps1
Install-GuestAdditions.ps1
Install-OpenSSH.ps1
oracle-cert.cer
Proxy.psm1
Set-PinnedApplication.ps1
set-proxy.ps1
Set-VarDefaults.ps1
vagrant.pub
vagrant-ssh.ps1
windows-features.ps1
windows-tweaks.ps1
windows-update.ps1
</pre>
 
`_setup.ps1` runs from Autounatended.xml as a first boot command. It contains ` ls A:`

<pre>
    Directory: A:\

Mode                LastWriteTime     Length Name                                                                                                                                       

-----          3/4/2015   1:58 PM       9192 Autounattend.xml                                                          
-----          3/4/2015   1:58 PM      70328 Get-WUInstall.ps1                                                         
-----          3/4/2015   1:58 PM       1262 Additions.ps1Additions.ps1                                                
-----          3/4/2015   1:58 PM       3548 Install-OpenSSH.ps1                                                       
-----          3/4/2015   1:58 PM       7334 PROXY.PSM                                                                 
-----          3/4/2015   1:58 PM       3148 Set-PinnedApplication.ps1                                                 
-----          3/4/2015   1:58 PM        836 Set-VarDefaults.ps1                                                       
-----          3/4/2015   1:58 PM       1180 _provision.ps1                                                            
-----          3/4/2015   1:58 PM        814 _SETUP.PS1                                                                
-----          3/4/2015   1:58 PM        328 enable-rdp.ps1                                                            
-----          3/4/2015   1:58 PM       1801 enable-winrm.ps1                                                          
-----          3/4/2015   1:58 PM       1419 oracle-cert.cer                                                           
-----          3/4/2015   1:58 PM        353 set-proxy.ps1                                                             
-----          3/4/2015   1:58 PM        781 vagrant-ssh.ps1                                                           
-----          3/4/2015   1:58 PM        409 VAGRANT.PUB                                                               
-----          3/4/2015   1:58 PM        409 windows-features.ps1                                                      
-----          3/4/2015   1:58 PM       3126 windows-tweaks.ps1                                                        
-----          3/4/2015   1:58 PM       1911 windows-update.ps1                                                        
                                                    
</pre>

Notice `PROXY.PSM` (should be `Proxy.psm1`) and files in upper case (all are one word file names) and strange `Additions.ps1Additionsps1` file.

**Comment by majkinetor** [comment]
Note that if I rename file `Proxy.psm1` to `Proxy-module.psm1` everything works OK.

**Comment by rasa** [comment]
The `Additions.ps1Additions.ps1` issue is documented/addressed at https://github.com/mitchellh/go-fs/pull/2
Not sure about `Proxy.psm1` becoming `PROXY.PSM` but that's probably in https://github.com/mitchellh/go-fs` as well. I've filed https://github.com/mitchellh/go-fs/issues/5 there for it.

**Comment by mitchellh** [comment]
Upstream bug, parts are fixed, one issue remains.
