### ISSUE TITLE
Potential for openstack availability zone support?

### ISSUE THREAD

**Issue by mcameron** [mitchellh/packer#1967]
Please can we add support for specifying availability zones in openstack?

Currently building an instance gets stuck for me scheduling since an AZ is not specified.  

Attempting to pass availability zone:
1425652806,,ui,error,1 error(s) occurred:\n\n* Unknown configuration key: availability_zone

**Comment by jgoldschrafe** [comment]
I need this as well, I'll take a look at adding it tonight.

**Comment by mitchellh** [comment]
Done by #2016

**Comment by mcameron** [comment]
Thank you.
