### ISSUE TITLE
vmware-iso: ESXi iso_checksum_type=none always upload the ISO

### ISSUE THREAD

**Issue by dantran** [mitchellh/packer#1974]
When I set isoChecksumType as 'none' the iso always upload to esx foreach each build.  Can it just reuse the iso at esx' packer_cache to speed up the build?

**Comment by israelshirk** [comment]
@dantran I'm not seeing this on ESXi 5.5 with packer v0.7.5; here's my configuration:
```json
		{
			"type": "vmware-iso",
			"name": "rhel6-vsphere",

			"guest_os_type": "rhel6-64",

			"iso_url": "file:///{{ pwd }}/iso/rhel-server-6.6-x86_64-dvd.iso",
			"iso_checksum": "4907e3ee01b5455b98654b136ab9833b6e672067051417d269f5c896cc7f3cf4cc878deb923022784d51ba523de63f2ee2ea3633a833aab2667704bfb09baab3",
			"iso_checksum_type": "none",

			"remote_type": "esx5",
			"remote_username": "root",
			"remote_password": "********",
			"remote_host": "1.2.3.4",
			"remote_datastore": "datastore",
			"remote_cache_directory": "/packer",

			"vmx_data": {
				"ethernet0.virtualDev": "vmxnet3",
				"ethernet0.networkName": "VM Network",
				"ethernet0.displayName": "VM Network",
				"ethernet0.connectionType": "bridged",
				"memSize": 2048
			},

			"vmdk_name": "disk",
			"version": "9",

			"floppy_files": [
				"kickstarts/rhel-6.6/ks.cfg",
				"drivers/rhel6/x86_64/kmod-vmware-tools-vmxnet3-1.3.1.0-2.6.32.71.el6.x86_64.5.el6.x86_64.rpm",
				"drivers/rhel6/x86_64/vmware-tools-foundation-9.4.11-1.el6.x86_64.rpm",
				"drivers/rhel6/x86_64/vmware-tools-vmxnet3-common-9.4.11-5.el6.x86_64.rpm"
			],

			"disk_size": "40000",

			"ssh_username": "vagrant",
			"ssh_password": "vagrant",
			"ssh_wait_timeout": "1000s",
			"ssh_host": "{{ user `ip_address` }}",

			"tools_upload_path": "/home/vagrant",
			"headless": false,
			"shutdown_command": "echo 'vagrant' | sudo -S /sbin/shutdown -h now",

			"boot_command": [ "<tab> text ks=floppy IPADDRESS={{ user `ip_address` }} NETMASK={{ user `netmask` }} GATEWAY={{ user `gateway` }}<enter><wait>" ],
			"boot_wait": "5s"
		}

```

Probably a good bit of it is copy+paste/environment-specific stuff.  If you can post your template and any variables you're using, I'd be glad to help troubleshoot/resolve it with you after we wrap up our big release in the next couple weeks - there's a lot of tweaky stuff that I've run into on ESX that doesn't seem to happen on Workstation/Fusion.

**Comment by dantran** [comment]
I have the similiar setup, but the iso_url is from http.

packer always does the download and pushing into esx for each build

Where does packer download the ISO to?

**Comment by israelshirk** [comment]
Looks like it downloads to local from the URL validates the checksum, then uploads to ESX and validates the checksum again - 

https://github.com/mitchellh/packer/blob/master/builder/vmware/iso/builder.go#L301

If you run packer with `PACKER_LOG=1 packer ....` does it indicate that the unwanted checksum is happening after download to local or upload to ESX?

**Comment by dantran** [comment]
here is the log

2015/03/30 09:30:12 packer-builder-vmware-iso: 2015/03/30 09:30:12 Starting download: http://xxxx.mycom.com:8081/nexus/content/groups/public/com/suse/sles/11.3-SNAPSHOT/sles-11.3-20150213.063858-1-x86_64-GM-DVD1.iso
2015/03/30 09:30:17 ui: [0;32m    vmware-iso: Download progress: 0%[0m
[0;32m    vmware-iso: Download progress: 0%[0m
2015/03/30 09:30:22 ui: [0;32m    vmware-iso: Download progress: 21%[0m
[0;32m    vmware-iso: Download progress: 21%[0m
2015/03/30 09:30:27 ui: [0;32m    vmware-iso: Download progress: 39%[0m
[0;32m    vmware-iso: Download progress: 39%[0m
2015/03/30 09:30:32 ui: [0;32m    vmware-iso: Download progress: 53%[0m
[0;32m    vmware-iso: Download progress: 53%[0m
2015/03/30 09:30:37 ui: [0;32m    vmware-iso: Download progress: 73%[0m
[0;32m    vmware-iso: Download progress: 73%[0m
2015/03/30 09:30:42 ui: [0;32m    vmware-iso: Download progress: 98%[0m
[0;32m    vmware-iso: Download progress: 98%[0m
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 opening new ssh session
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 starting remote command: test -e /vmfs/volumes/VLUN_122/vmxxx-esx
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 remote command exited with '1': test -e /vmfs/volumes/VLUN_122/vmxxx-esx
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 opening new ssh session
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 starting remote command: mkdir -p /vmfs/volumes/VLUN_122/vmxxx-esx
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 remote command exited with '0': mkdir -p /vmfs/volumes/VLUN_122/vmxxx-esx
2015/03/30 09:30:43 ui: [1;32m==> vmware-iso: Creating floppy disk...[0m
[1;32m==> vmware-iso: Creating floppy disk...[0m
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Floppy path: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/tmp/packer504160713
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Initializing block device backed by temporary file
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Formatting the block device with a FAT filesystem...
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Initializing FAT filesystem on block device
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Reading the root directory from the filesystem
2015/03/30 09:30:43 ui: [0;32m    vmware-iso: Copying: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/packer/config/info[0m
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Adding file to floppy: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/packer/config/info
[0;32m    vmware-iso: Copying: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/packer/config/info[0m
2015/03/30 09:30:43 ui: [0;32m    vmware-iso: Copying: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/packer/sles11sp3/autoyast.xml[0m
[0;32m    vmware-iso: Copying: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/packer/sles11sp3/autoyast.xml[0m
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Adding file to floppy: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/packer/sles11sp3/autoyast.xml
2015/03/30 09:30:43 ui: [1;32m==> vmware-iso: Uploading Floppy to remote machine...[0m
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Remote uploading: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/tmp/packer504160713
[1;32m==> vmware-iso: Uploading Floppy to remote machine...[0m
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 opening new ssh session
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 starting remote command: mkdir -p /vmfs/volumes/Packer15/vmxxx-esx_packer_cache
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 remote command exited with '0': mkdir -p /vmfs/volumes/Packer15/vmxxx-esx_packer_cache
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Verifying checksum of /vmfs/volumes/Packer15/vmxxx-esx_packer_cache/packer504160713
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 opening new ssh session
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 starting remote command: nonesum -c
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 remote command exited with '127': nonesum -c
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 opening new ssh session
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Starting remote scp process:  scp -vt /vmfs/volumes/Packer15/vmxxx-esx_packer_cache
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Started SCP session, beginning transfers...
2015/03/30 09:30:43 packer-builder-vmware-iso: 2015/03/30 09:30:43 Copying input data into temporary file so we can read the length
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 [DEBUG] Uploading packer504160713: perms=C0644 size=1474560
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 SCP session complete, closing stdin pipe.
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 Waiting for SSH session to complete.
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 scp stderr (length 36): Sink: C0644 1474560 packer504160713
2015/03/30 09:30:44 ui: [1;32m==> vmware-iso: Uploading ISO to remote machine...[0m
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 Remote uploading: /space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/.external-resources/packer/cache/1bd9604ab330a1b108d39704422541ba3efa5ca2fe767c2ecd7279ae03eb9ea7.iso
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 opening new ssh session
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 starting remote command: mkdir -p /vmfs/volumes/Packer15/vmxxx-esx_packer_cache
[1;32m==> vmware-iso: Uploading ISO to remote machine...[0m
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 remote command exited with '0': mkdir -p /vmfs/volumes/Packer15/vmxxx-esx_packer_cache
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 Verifying checksum of /vmfs/volumes/Packer15/vmxxx-esx_packer_cache/1bd9604ab330a1b108d39704422541ba3efa5ca2fe767c2ecd7279ae03eb9ea7.iso
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 opening new ssh session
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 starting remote command: nonesum -c
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 remote command exited with '127': nonesum -c
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 opening new ssh session
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 Starting remote scp process:  scp -vt /vmfs/volumes/Packer15/vmxxx-esx_packer_cache
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 Started SCP session, beginning transfers...
2015/03/30 09:30:44 packer-builder-vmware-iso: 2015/03/30 09:30:44 Copying input data into temporary file so we can read the length
2015/03/30 09:31:37 packer-builder-vmware-iso: 2015/03/30 09:31:37 [DEBUG] Uploading 1bd9604ab330a1b108d39704422541ba3efa5ca2fe767c2ecd7279ae03eb9ea7.iso: perms=C0644 size=3362783232
2015/03/30 09:33:15 packer-builder-vmware-iso: 2015/03/30 09:33:15 SCP session complete, closing stdin pipe.

**Comment by israelshirk** [comment]
That's interesting; can you post your packer template too?

**Comment by dantran** [comment]
here is the template, note: the vars are passing via a varfile

{

"variables": {
    "homedir": "",
    "isoUrl": "",
    "isoChecksum": "",
    "isoChecksumType": "md5",
    "sshWaitTimeout":"4500s",
    "remoteHost": "",
    "remoteUsername":"",
    "remotePassword":"",
    "remoteDatastore":"",
    "remoteCacheDatastore":"",
    "remoteCacheDirectory":"packer_cache",
    "remoteOutputDirectory":"",
    "vmNetwork":"",
    "vmNetworkAdapter":"",
    "vmName" :"",
    "vncPortMin":"5987",
    "vncPortMax":"5990",
    "bootCommand":""
    }
,
"builders": [{
  "type": "vmware-iso",
  "iso_url": "{{user `isoUrl`}}",
  "iso_checksum":"{{user `isoChecksum`}}",
  "iso_checksum_type": "{{user `isoChecksumType`}}",
  "ssh_username": "root",
  "ssh_password":"changeme",
  "ssh_wait_timeout": "{{user `sshWaitTimeout`}}",
  "shutdown_command": "echo '/sbin/shutdown -h -P now' > /tmp/shutdown.sh; echo 'vagrant'|sudo -S sh '/tmp/shutdown.sh'",
  "remote_type":"esx5",
  "remote_host":"{{user `remoteHost`}}",
  "remote_datastore":"{{user `remoteDatastore`}}",
  "remote_username":"{{user `remoteUsername`}}",
  "remote_password":"{{user `remotePassword`}}",
  "remote_cache_datastore":"{{user `remoteCacheDatastore`}}",
  "remote_cache_directory":"{{user `remoteCacheDirectory`}}",
  "output_directory":"{{user `remoteOutputDirectory`}}",
  "vnc_port_min":"{{user `vncPortMin`}}",
  "vnc_port_max":"{{user `vncPortMax`}}",
  "headless":"true",
  "vm_name":"{{user `vmName`}}",
  "floppy_files" : ["{{user `homedir`}}/config/info", "{{user `homedir`}}/sles11sp3/autoyast.xml"],
  "guest_os_type":"linux",
  "boot_command": ["{{user `bootCommand`}}"],
  "vmx_data" : {
  "config.version"  : "8",
  "virtualHW.version" : "7",
  "pciBridge0.present" : "TRUE",
  "pciBridge4.present" : "TRUE",
  "pciBridge4.virtualDev" : "pcieRootPort",
  "pciBridge4.functions" : "8",
  "pciBridge5.present" : "TRUE",
  "pciBridge5.virtualDev" : "pcieRootPort",
  "pciBridge5.functions" : "8",
  "pciBridge6.present" : "TRUE",
  "pciBridge6.virtualDev" : "pcieRootPort",
  "pciBridge6.functions" : "8",
  "pciBridge7.present" : "TRUE",
  "pciBridge7.virtualDev" : "pcieRootPort",
  "pciBridge7.functions" : "8",
  "vmci0.present" : "TRUE",
  "virtualHW.productCompatibility" : "hosted",
  "powerType.powerOff" : "soft",
  "powerType.powerOn" : "hard",
  "powerType.suspend" : "hard",
  "powerType.reset" : "soft",
  "numvcpus" : "4",
  "vcpu.hotadd" : "TRUE",
  "scsi0.present" : "TRUE",
  "scsi0.sharedBus" : "none",
  "scsi0.virtualDev" : "lsilogic",
  "scsi1.present" : "TRUE",
  "scsi1.sharedBus" : "none",
  "scsi1.virtualDev" : "lsilogic",
  "scsi2.present" : "TRUE",
  "scsi2.sharedBus" : "none",
  "scsi2.virtualDev" : "lsilogic",
  "scsi3.present" : "TRUE",
  "scsi3.sharedBus" : "none",
  "scsi3.virtualDev" : "lsilogic",
  "memsize" : "16384",
  "mem.hotadd" : "TRUE",
  "ide0:0.present" : "TRUE",
  "ide0:0.fileName" : "CD/DVD drive 1",
  "ide0:0.deviceType" : "atapi-cdrom",
  "ide0:0.startConnected" : "FALSE",
  "ethernet0.present" : "TRUE",
  "ethernet0.virtualDev" : "{{user `vmNetworkAdapter`}}",
  "ethernet0.wakeOnPcktRcv" : "FALSE",
  "ethernet0.networkName" : "{{user `vmNetwork`}}",
  "ethernet0.addressType" : "vpx",
  "tools.syncTime" : "TRUE",
  "guestOS" : "sles11-64",
  "tools.upgrade.policy" : "manual",
  "floppy0.present" : "FALSE",
  "cleanShutdown" : "FALSE",
  "replay.supported" : "FALSE",
  "replay.filename" : ""
  }
 }],

	"provisioners": [
                {
                  "type": "file",
                  "source": "{{user `homedir`}}/payload/",
                  "destination": "/tmp/"
                },
		{
                 "type": "shell",
		 "script": "{{user `homedir`}}/commons/configure.sh"
		 },
                {
                 "type": "shell",
                 "script": "{{user `homedir`}}/vmware/zero-disk.sh"
                }
	]
}

**Comment by dantran** [comment]
here is the json var file

{
    "homedir": "/space/jenkins/trand8/.jenkins-slave/workspace/vmxxx-ova/target/packer",
    "isoUrl": "http://xxxx.mycom.com:8081/nexus/content/groups/public/com/suse/sles/11.3-SNAPSHOT/sles-11.3-20150213.063858-1-x86_64-GM-DVD1.iso",
    "isoChecksum": "480b70d50cbb538382dc2b9325221e1b",
    "isoChecksumType": "none",
    "sshWaitTimeout":"4500s",
    "remoteHost": "vesx15.mycom.com",
    "remoteDatastore":"VLUN_122",
    "remoteCacheDatastore":"Packer15",
    "remoteCacheDirectory":"vmxxx-esx_packer_cache",
    "remoteOutputDirectory":"vmxxx-esx",
    "remoteUsername":"vmxxx",
    "remotePassword":"password",
    "vmNetwork":"VM Network",
    "vmName" :"vmxxx-esx",
    "vmNetworkAdapter" :"vmxnet3",
    "vncPortMin":"5987",
    "vncPortMax":"5990",
    "bootCommand":"<down><left><home><wait5>info=floppy:<wait5>/info<enter>"
 }

**Comment by israelshirk** [comment]
So a non-kosher way to temporarily work around this would be to just create a blank script on your ESX host called `nonesum` which always exits with code 0; I'd expect a proper behavior would be to not call the function in the first place, but there are a few idiosyncracies/strange logic things going on that would fix it at a higher level - I'll probably PR that instead when I get around to it.

**Comment by dantran** [comment]
Thank you for helping out,  looking forward with the fix.

**Comment by dantran** [comment]
The trick to create empty nonesum executable helps.  the ISO does not get push into ESX, however it always download from my http server.  

Not sure why for md5 type, it does not get dowload but use the one inder local packer cache

**Comment by israelshirk** [comment]
I found that last one today as well, it's in #2007

**Comment by dantran** [comment]
I also try to trick packer by creating a dummy  nonsum executable at esx, so it skips the iso update, but it also skips the floppy upload where the file name is random for each packer run.  Packer tells the VM to pick up the virtual floppy, but floppy  never reach the ESX
