### ISSUE TITLE
Cloudfront very slow to down installers from - mirror available?

### ISSUE THREAD

**Issue by sammcj** [mitchellh/packer#1978]
FYI - Cloudfront is *very* slow to download from in Australia.

It would be nice if packer had a mirror that wasn't on Amazon because waiting 15 minutes to download 83MB on a GbE connection is not fun.

```
aria2c https://dl.bintray.com/mitchellh/packer/packer_0.7.5_linux_amd64.zip
[#1 SIZE:2.2MiB/83.2MiB(2%) CN:1 SPD:92.0KiBs ETA:15m]
```

**Comment by sethvargo** [comment]
Hi there,

We use bintray to host our binaries. I'll check with them. Thanks!

**Comment by klousiaj** [comment]
I'm seeing what seems to be a similar problem from the East Coast in the US. 

Downloading packer and seeing download speeds of ~15KB/s. 

I've opened a ticket with bintray as well.

![bintray-download-packer](https://cloud.githubusercontent.com/assets/4754718/7289474/b8634766-e93e-11e4-941d-9926c96bec25.png)

**Comment by mitchellh** [comment]
Bintray has generously offered our projects binary hosting. They use Cloudfront + S3. Sorry if your QoS is not good but this is definitely an upstream issue.
