### ISSUE TITLE
-force should stop and unregister virtual machine if it already exists

### ISSUE THREAD

**Issue by icnocop** [mitchellh/packer#1982]
Hi.

I'd like to request that the -force option stop and unregister the virtual machine if it already exists.

Otherwise, the build fails with the "Error registering VM" error:

```
==> vm1: 
==> vm1: Stdout: (vim.fault.AlreadyExists) {
==> vm1: dynamicType = <unset>, 
==> vm1: faultCause = (vmodl.MethodFault) null, 
==> vm1: name = "1053", 
==> vm1: msg = "The specified key, name, or identifier already exists.", 
==> vm1: }
```

packer template snippet:

<pre>
    "builders": [
        {
             "type": "vmware-iso",
             "remote_type": "esx5"
        }
    ]
</pre>

Thank you.

**Comment by kevinkjt2000** [comment]
I would love if packer had this, since I just ran into it.  This works for virtualbox-iso, but not vmware-iso.
