### ISSUE TITLE
Support for RHEV virtual machines

### ISSUE THREAD

**Issue by rothgar** [mitchellh/packer#1984]
[Red Hat Enterprise Virtualization](http://www.redhat.com/en/technologies/virtualization) is based on KVM but I could not find any documentation or issues saying it is supported or not. QEMU is already supported but would need additional configuration to talk to a Virtual Desktop Server Manager to create machines based on KVM images.

**Comment by mitchellh** [comment]
I'd be happy to support this if it isn't already through QEMU. Please advise on how to do so or better yet make a PR! Thanks.
