### ISSUE TITLE
The default ec2-upload-bundle command doesn't take into consideration the case when IAM Roles are used

### ISSUE THREAD

**Issue by gozer** [mitchellh/packer#1985]
If we are using a builder with no aws access keys, because we are instead using IAM Roles, the invocation of ec2-upload-bundle should just omit the:

 -a {{.AccessKey}}
 -s {{.SecretKey}}

options entirely. Otherwise, the AWS cli will not even attempt to use its role.

**Comment by catsby** [comment]
#2204 omits the key and secret, are you able to test it out?

**Comment by gozer** [comment]
Yes, that worked! I tested with my own packer build at 35b8df18162f8849eb28f1bed53f67c1421aacd4

One thing I am pretty certain is unrelated, however, is that the image name generated is now literally "image-{{timestamp}}"

I suspect it's coming from this bit of code, and somehow the value isn't being interpolated:
 
    builder/amazon/instance/builder.go:72
    b.config.BundlePrefix = "image-{{timestamp}}"
