### ISSUE TITLE
Packer push to atlas Error starting upload: upload: resource not found

### ISSUE THREAD

**Issue by tayzlor** [mitchellh/packer#1986]
This looks related to https://github.com/mitchellh/vagrant/issues/4968

...but for packer, instead of vagrant. I'm running packer 0.7.5.

If I look in the atlas web UI, I see the name of my build configuration, but the details are empty, and the field just collapses itself.

my push config is just 

```
"push": {
    "name": "tayzlor/me-ubuntu-14.04_amd64",
  },
```

Secondary, (maybe this is a second issue). If I push once and I get the upload error, If I try to push again I get 

```client: 422 Unprocessable Entity```

Subsequently I cannot do any further pushes until I change the "name" inside the packer config. It seems that packer wont allow me to do more than 1 push with a single name. Even if I go and delete the build configuration (through the web interface) it wont allow me to push with the same name again.
I have successfully exported my ATLAS_TOKEN environment variable (and also done the vagrant login to atlas - though that shouldn't matter since we're using packer here)

**Comment by sethvargo** [comment]
Hi @tayzlor 

I am sorry you are having issues with Packer + Atlas. Can you try running Packer from master and seeing if you get the same error (or better error output)? We fixed a number of issues that have not yet been released with regard to atlas + packer :smile:

**Comment by tayzlor** [comment]
Thanks @sethvargo . Confirmed working with latest master. Closing.
