### ISSUE TITLE
Time is non-monotonic only in Packer

### ISSUE THREAD

**Issue by Spenser309** [mitchellh/packer#1987]
Hi,

I recently installed Packer and Virtualbox on a RHEL5 Machine. I'm noticing that my timeouts are not accurate which led me turn on PACKER_LOG=1 .  I then found this line in the output

2015/03/17 16:39:49 packer-builder-virtualbox-iso: 2015/10/12 04:39:47 stdout:
2015/03/17 16:39:49 packer-builder-virtualbox-iso: 2015/03/17 16:39:49 stderr:
2015/03/17 16:39:49 packer-builder-virtualbox-iso: 2015/03/17 16:39:49 Executing VBoxManage: []string{"controlvm", "packer-CentOS 6.6-1426635548", "keyboardputscancode", "9f"}

See how the first line says that the time is 16:39:49 on the left and 04:39:47 on the right (also, a different day of the year).  How is this possible?

Thanks,
Spenser

**Comment by mitchellh** [comment]
I honestly don't know why the times are so wide apart, but the times will certailnly dfifer in some cases. The right is when the log message was actually created and sent to the Packer plugin host (packer itself) and the left is when the plugin host outputted the message.
