### ISSUE TITLE
Make handshake attempts configurable

### ISSUE THREAD

**Issue by pschirch** [mitchellh/packer#1988]
Hi,

I actually  create a packer template for OES 11 SP2 with SLES SP3 with packer v0.7.5. This distribution uses an autoinst.xml for autoinstall. Different from basic SLES installation process the OES setup consists of two parts. Part one is the basic SLES setup, part two is the additionally OES configuration. During OES configuration, the Novell LUM service is configured and starts the SSH service as a related one. In this state, the SSH configuration do not allow keyboard-interactive authentication. I can't force the right configuration. It will be automatically configured correctly in a future step during OES configuration. So Packer try to connect before setup has finished and failed:

```bash
2015/03/18 08:06:58 packer-builder-virtualbox-iso: 2015/03/18 08:06:58 Attempting SSH connection...
2015/03/18 08:06:58 packer-builder-virtualbox-iso: 2015/03/18 08:06:58 reconnecting to TCP connection for SSH
2015/03/18 08:06:58 packer-builder-virtualbox-iso: 2015/03/18 08:06:58 handshaking with SSH
2015/03/18 08:06:58 packer-builder-virtualbox-iso: 2015/03/18 08:06:58 handshake error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain
2015/03/18 08:06:58 packer-builder-virtualbox-iso: 2015/03/18 08:06:58 SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain
2015/03/18 08:06:58 packer-builder-virtualbox-iso: 2015/03/18 08:06:58 Detected authentication error. Increasing handshake attempts.
2015/03/18 08:06:58 ui error: ==> virtualbox-iso: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain
```

If I use the debug flag, packer wait for pressing the enter key and the OES configuration will continue succesfully. After that the keyboard interactive authentication is available.

The handshake attempts are [hard coded](https://github.com/mitchellh/packer/blob/master/common/step_connect_ssh.go#L157). In this usecase it should be configurable.

```json
 "ssh_max_handshake_attempts": x,
```

Another option is to allow SSH authentication with a key instead keyboard-interactive.

Any advice?

**Comment by tomzo** [comment]
Hi

I'd love to see this in openstack builder. In fact any any builder should support it.

I am using packer to provision windows in private openstack. In my configuration windows has to boot, run cloud-init-like script, update ssh configuration, reboot and only then I ssh connection is possible. During this long cycle ssh comes up, but refuses authentication, then goes down (reboot), then comes up again, refuses, then finally I can log-in. With current 10 ssh attempts it is just not enough, my server gets terminated before it reboots again.

I am not a go developer, but I think I could implement this. Some tips on where this should be implemented would be nice though.

**Comment by einarf** [comment]
Definitly needed. Got the same issue just now when using cloud-init. Should be a fairly simple thing to add.

**Comment by pschirch** [comment]
This feature is still **highly required**. Any plans to implement this?

**Comment by tomzo** [comment]
It is not a priority for me at the moment. 
But I have it scheduled in about 3 weeks. I am going to do it together with similar issue in terraform.

**Comment by mitchellh** [comment]
I got a PR #2237 open now that will fix this.
