### ISSUE TITLE
Error uploading script: SCP failed to start.

### ISSUE THREAD

**Issue by SaschaMoellering** [mitchellh/packer#1991]
Hi,

I just want to created an updated AMI of the new ECS-preview3 image (ami-801544e8) and I get the following strange error:

```text
2015/03/19 14:28:42 Waiting on builds to complete...
2015/03/19 14:28:42 Starting build run: amazon-ebs
2015/03/19 14:28:42 Running builder: amazon-ebs
2015/03/19 14:28:42 ui: ==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Inspecting the source AMI...
2015/03/19 14:28:43 ui: ==> amazon-ebs: Creating temporary keypair: packer 550acf0a-5931-c303-fe6d-95a3cd538911
==> amazon-ebs: Creating temporary keypair: packer 550acf0a-5931-c303-fe6d-95a3cd538911
2015/03/19 14:28:44 packer-builder-amazon-ebs: 2015/03/19 14:28:44 Using specified security groups: [sg-9c6bfff8]
2015/03/19 14:28:44 ui: ==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Launching a source AWS instance...
2015/03/19 14:28:46 ui:     amazon-ebs: Instance ID: i-29f7a606
2015/03/19 14:28:46 ui: ==> amazon-ebs: Waiting for instance (i-29f7a606) to become ready...
    amazon-ebs: Instance ID: i-29f7a606
2015/03/19 14:28:46 packer-builder-amazon-ebs: 2015/03/19 14:28:46 Waiting for state to become: running
2015/03/19 14:28:46 packer-builder-amazon-ebs: 2015/03/19 14:28:46 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
==> amazon-ebs: Waiting for instance (i-29f7a606) to become ready...
2015/03/19 14:29:06 packer-builder-amazon-ebs: 2015/03/19 14:29:06 Waiting for SSH, up to timeout: 5m0s
2015/03/19 14:29:06 ui: ==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Waiting for SSH to become available...
2015/03/19 14:29:21 packer-builder-amazon-ebs: 2015/03/19 14:29:21 TCP connection to SSH ip/port failed: dial tcp 54.165.195.217:22: i/o timeout
2015/03/19 14:29:37 packer-builder-amazon-ebs: 2015/03/19 14:29:37 TCP connection to SSH ip/port failed: dial tcp 54.165.195.217:22: connection refused
2015/03/19 14:29:42 packer-builder-amazon-ebs: 2015/03/19 14:29:42 TCP connection to SSH ip/port failed: dial tcp 54.165.195.217:22: connection refused
2015/03/19 14:29:48 packer-builder-amazon-ebs: 2015/03/19 14:29:48 TCP connection to SSH ip/port failed: dial tcp 54.165.195.217:22: connection refused
2015/03/19 14:29:53 packer-builder-amazon-ebs: 2015/03/19 14:29:53 TCP connection to SSH ip/port failed: dial tcp 54.165.195.217:22: connection refused
2015/03/19 14:29:58 packer-builder-amazon-ebs: 2015/03/19 14:29:58 Attempting SSH connection...
2015/03/19 14:29:58 packer-builder-amazon-ebs: 2015/03/19 14:29:58 reconnecting to TCP connection for SSH
2015/03/19 14:29:58 packer-builder-amazon-ebs: 2015/03/19 14:29:58 handshaking with SSH
2015/03/19 14:29:59 ui: ==> amazon-ebs: Connected to SSH!
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 Running the provision hook
==> amazon-ebs: Connected to SSH!
2015/03/19 14:29:59 ui: ==> amazon-ebs: Provisioning with shell script: /var/folders/2h/gqlg1s9n5p1dqflnzyss537h_1yydw/T/packer-shell752415821
==> amazon-ebs: Provisioning with shell script: /var/folders/2h/gqlg1s9n5p1dqflnzyss537h_1yydw/T/packer-shell752415821
2015/03/19 14:29:59 packer-provisioner-shell: 2015/03/19 14:29:59 Opening /var/folders/2h/gqlg1s9n5p1dqflnzyss537h_1yydw/T/packer-shell752415821 for reading
2015/03/19 14:29:59 packer-provisioner-shell: 2015/03/19 14:29:59 [INFO] 38 bytes written for 'uploadData'
2015/03/19 14:29:59 [INFO] 38 bytes written for 'uploadData'
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 opening new ssh session
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 Starting remote scp process:  scp -vt /tmp
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 Started SCP session, beginning transfers...
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 Copying input data into temporary file so we can read the length
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 [DEBUG] Uploading script.sh: perms=C0644 size=38
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 SCP session complete, closing stdin pipe.
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 Waiting for SSH session to complete.
2015/03/19 14:29:59 packer-builder-amazon-ebs: 2015/03/19 14:29:59 non-zero exit status: 127
2015/03/19 14:29:59 packer-provisioner-shell: 2015/03/19 14:29:59 Retryable error: Error uploading script: SCP failed to start. This usually means that SCP is not
2015/03/19 14:29:59 packer-provisioner-shell: properly installed on the remote system.
```

There seems to be a problem with scp but I'm not sure what exactly is the problem.

Thanks and Regards,
Sascha

**Comment by SaschaMoellering** [comment]
Did a test with the final ECS AMI (ami-3b76114c), same problem.

**Comment by joekhoobyar** [comment]
This is still happening, as far as I can tell.

**Comment by mikeyhill** [comment]
Having same issue here.  Centos 6.6

==> Some builds didn't complete successfully and had errors:
2015/05/09 05:23:20 machine readable: amazon-ebs,error []string{"SCP failed to start. This usually means that SCP is not\nproperly installed on the remote system."}
2015/05/09 05:23:20 ui error: --> amazon-ebs: SCP failed to start. This usually means that SCP is not
properly installed on the remote system.

Scp is available on the AMI this image is being built from.

**Comment by pbecotte** [comment]
I was also trying to build an AMI based on the ECS image- is there a workaround for this?  I just need to run a 5 line shell provisioner, it seem like I shouldn't need scp?

**Comment by joekhoobyar** [comment]
At the very least, there should be an option to use SFTP instead.

**Comment by ainoya** [comment]
I had same problem, so I use `user_data_file` option instead of `provisioners` as a temporary expedient.

**Comment by lucianot54** [comment]
I'm not alone with this problem... Do you have Tricks to execute custom script on ecs image?

**Comment by catsby** [comment]
Hello – does anyone have a sample config I can use to reproduce this issue? Reading the comments, it's hard to tell if this is Packer issue or an ECS AMI issue. 

Thanks!

**Comment by pbecotte** [comment]
This is a combination.  Using an AMI that doesn't have SCP installed causes the failure because there's no backup provision.

I got it with the following config-

{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us-east-1",
    "source_ami": "ami-d05e75b8",
    "instance_type": "t2.medium",
    "ssh_username": "ubuntu",
    "ami_name": "jenkins_slave_docker_{{timestamp}}"
  }],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "sleep 30",
        "sudo apt-get update && sudo apt-get install -y default-jre git python-pip",
        "sudo pip install requests==2.5.3 docker-compose",
        "wget -qO- https://get.docker.com/ | sh",
        "sudo usermod -aG docker ubuntu"
      ]
    }
  ]
}

**Comment by mitchellh** [comment]
The file upload/download capabilities of Packer only use SCP. You must have SCP installed if you wish to use those features. It is completely optional if you _dont_ use those features. 

I'd be happy to support SFTP as well, but have no intention of doing this myself since SCP works fine for almost everyone. If I saw an SFTP PR though, I'd be happy to merge it.

**Comment by pbecotte** [comment]
Obviously that is completely your perogative.  But I would think you could execute inline shell commands without SCP or SFTP or any other file transfer mechanism.  There is also the matter that it is completely unexpected to get file transfer errors when you don't have any file transfer commands anywhere in your config.  Maybe a better error message?

**Comment by tomwilkie** [comment]
I've got a _very_ hacked up branch here that works using sftp: https://github.com/tomwilkie/packer/tree/sftp

If anyones interested I can tidy it up and submit a PR.

**Comment by 2opremio** [comment]
@mitchellh I am working on adding an extra option for the ssh communicator: `ssh_file_transfer_method` which can be set to `scp` or `sftp` (`scp` by default). Would that be acceptable for a PR? Or would you rather get an automatic fallback to `sftp` when `scp` is not installed in the remote host (i.e. without exposing it to the user).

**Comment by j0nesy** [comment]
Looking forward to this fix being pulled.  Ran into this problem today trying to provision the latest ECS AMI.  My workaround for now is to use the non-ECS AMI which works with scp and add the command to install the ECS agent during provisioning.  This is working, but it is not as nice as being able to use the AMI that already has it.

**Comment by 2opremio** [comment]
@j0nesy As a temporary solution until SFTP-support is merged, you could also use our hacked-up version of packer, which forces SFTP instead of SCP by default: see https://github.com/weaveworks/integrations/tree/master/aws/ecs#build-your-own-weave-ecs-ami.

**Comment by jcusa** [comment]
@2opremio thanks for the fix. I ran into the exact same issue while trying to customize the ECS-optimized AMI by amazon. Google search lead me here. I am glad it got merged in last year.

**Comment by 2opremio** [comment]
You're welcome ! :)

**Comment by seb-steuer** [comment]
Hi,

I'm fighting with this too as base image im using doesnt have sftp.
I thought using user-data to install it would help but it doesnt work
Maybe packer doesnt wait for user data to fully execute before starting ssh provisioner? or for some reason the user data is not executed either.
I will look into that possibility too

kind regards

**Comment by rickard-von-essen** [comment]
@seb-steuer This is a very old issue. Ask for help on the mailing list instead.
