### ISSUE TITLE
Why are droplet level configurations (region, size...) needed when using a digitalocean builder?

### ISSUE THREAD

**Issue by NeMO84** [mitchellh/packer#1992]
I should preface this question by clarifying that I am just getting familiar with Packer and may not fully be aware of the best practices and most assumptions.

What is the purpose of providing instance(droplet) level configuration for generating base images?

My understanding, and please correct me if I am wrong, is that packer allows you to generate base machine images for different platforms. And then use those base images to spin up instances (droplets) with specific attributes such as: size, region, private_networking...

So I would think that having size, region, and maybe other settings which are really run time settings when booting an instance should be the responsibility of the deployment service. 

Are these settings really only for the creation aspect of the image but have no bearing on the base image that is generated? If so, should private_networking have any reason to be configured at this point?

**Comment by mitchellh** [comment]
It is to specify the size of the instance you want to use for creating the image. For example: if creating the image requires compiling a lot of software, perhaps you want a larger one, then you will launch it on a smaller instance. Or, if its a lot of IO, just a small will do.

**Comment by NeMO84** [comment]
Makes sense. Thanks.
