### ISSUE TITLE
Public listings of packer templates

### ISSUE THREAD

**Issue by derek-adair** [mitchellh/packer#1994]
It would be *amazing* to be able to share packer templates, similar to how vagrant boxes are shared.  I can't even describe how useful hub.docker.com has been for me.  I feel like this would be a great boon in my exploration of packer and give the community a place to communicate / share tricks, tips and techniques.

**Comment by sethvargo** [comment]
Going to defer to @mitchellh on this. I agree it would be useful, but I am not sure this is something we want to support at this time.

**Comment by mitchellh** [comment]
Agreed with @sethvargo. Eventually, but not yet...
