### ISSUE TITLE
Directory upload truncated

### ISSUE THREAD

**Issue by poolpog** [mitchellh/packer#1996]
I'm not sure the root cause of this, but the problem is as follows.

Details
* Trying to build AWS EC2 image
* Packer v0.7.5
* ansible 1.7.2
* Mac OS 10.9.5 (mavericks) workstation
* AWS EC2 source image: CentOS 6.4 bashton1 hvm (ami-eec75e87)

**Description**
Directories uploaded via either the File provisioner or the Ansible provisioner seem to be truncated at around 24MB. The directory tree contains several symlinks to other directories and files within the tree. The symlinked files are *converted to actual files* by Packer, using either provisioner. Also, the truncation seems to happen only on those files that are converted symlinks.

The directory I am trying to upload is our entire Ansible directory structure. The entire thing is about 8.5M on disk. However, when expanding symlinked dirs, it grows to around 22M.

Files that are truncated seem to get truncated at around 46 or 48 bytes.

I discovered this when my Anisble playbook was failing with syntax errors, and the file that had the error was only 48 bytes long.

I don't have a reproducible test case, but I will create one if this bug gets any traction.

**Workaround**
I created a tarball of the Ansible dir I wanted to upload. I uploaded that via the File provisioner. I untarred it via the Inline Shell provisioner.  I removed the "playbook_dir" directive from the Ansible provisioner stanza. The Ansible provisioner then works.

**Comment by seelensonne** [comment]
We're also experiencing this issue.

* Packer 0.7.5 running OS X 10.0.2 with VMware Fusion 7.1.1
* Builder `vmware-iso` building a CentOS 7.1 VM
* Ansible 1.8.4 running on CentOS 7.1 (via `ansible-local` provisioner)

It does not seem to be size-related though... we upload a `playbook_directory` that's a mere 184 KB.

It does however seem to be symlink-related... our `playbook_directory` contains symlinks to a bunch of SSH host keys, and a symlink to a public SSH key for the root user. Packer expands the symlinks and the host keys are fine, but the root user's public key gets truncated at exactly 38 characters.

For the host keys, the symlink points to a directory (works fine). For the root user's public key, the symlink points to an individual `xxx.pub` file (get truncated).

**Comment by mitchellh** [comment]
This should be fixed by #1765
