### ISSUE TITLE
Update help to include details on multiple packer builders

### ISSUE THREAD

**Issue by Cyclic** [mitchellh/packer#1998]
It would be great if the documentation provided a method for specifying the type output boxes. I don't see any details about the post-processors output having multiple providers in an array and doing packer build --help does not provide this.

**Comment by sethvargo** [comment]
Hi @Cyclic 

Could you please clarify what you mean by "output box"? Do you mean post-processor?

Thanks!

**Comment by Cyclic** [comment]
Hi @Mitchellh,

I just meant output, .box, under post-processor, yes.

Thank you!

**Comment by mitchellh** [comment]
I don't understand still, could you please submit a PR? The website is quite easy to update, it is just in the `website` directory. Thanks!
