### ISSUE TITLE
Vmware providers does not resolve the host IP properly

### ISSUE THREAD

**Issue by Trenker** [mitchellh/packer#1999]
The Vmware provider for Vmware Workstation for Linux does not properly resolve the host IP config, which leads to preseed and installerconfigs not being loaded. Some digging revealed, that it used `ifconfig` to get the IP of the vmnet adapter, and some regex. That regular expression did not only find the address, but also it's prefix.

An example:

My ifconfig outputs:

```shell
...
vmnet8    ...
          inet Adress:172.16.15.1  Bcast:172.16.15.255  ...
```

Which caused packer to enter `Adress:172.16.15.1` as the IP address.

After changing

```go
re := regexp.MustCompile(`inet\s*(?:addr:)?(.+?)\s`)
```

to

```go
re := regexp.MustCompile(`inet[^\d]+([\d\.]+)\s`)
```

in `builder/vmware/common/host_ip_config.go`, line 47, it worked.

Do you want a pull request for this?

**Comment by sethvargo** [comment]
Hi @Trenker 

Thank you for the report. PRs are always welcome!
