### ISSUE TITLE
amazon-ebs failing without a message

### ISSUE THREAD

**Issue by ZepedaMcMillan** [mitchellh/packer#2001]
After digging through and resolving specific IAM issues, I'm getting an error without a message:

amazon-ebs output will be in this color.

==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 5512e984-c174-21f1-a444-0b1be3a0e864
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing SSH access on the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance:
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: 

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: 

==> Builds finished but no artifacts were created.

Note that with the latest AWS updates, iam:PassRole must be granted in the IAM role for your packer instance. I'm guessing this is related to IAM, but not having an error message makes it difficult to track down.

**Comment by veselinkantsev** [comment]
With '*-var iam_instance_profile*', I had to append '*iam:PassRole*' to the permissions listed under [Using An IAM Instance Profile](https://www.packer.io/docs/builders/amazon.html).

**Comment by ZepedaMcMillan** [comment]
I added iam:PassRole and still got the failure. I'm not certain if this is vpc related or not, but having an error message would be helpful in my case. I'm sure it's something to do with our security settings, but can't isolate it at the moment

**Comment by veselinkantsev** [comment]
@ZepedaMcMillan CloudTrail might be useful in tracking down which API call is failing.

**Comment by krzysztofszarek** [comment]
I had the same issue and I found error log in Cloud Trail:
```
Error codeServer.InsufficientInstanceCapacity
```
so I changed subnet and it works fine. Hope it'll help.

**Comment by catsby** [comment]
Hey @ZepedaMcMillan – do you have packer config handy that reproduces this? If you do and don't mind sharing, please be sure to omit any secrets therein. If not, anything else you can offer that will help me reproduce is greatly appreciated.

Thanks!

**Comment by ZepedaMcMillan** [comment]
@catsby I was actually able to determine the issue. We were using the new C4 instances to pack our AMIs to ensure that enhanced networking was enabled, but our region ran out of slots for C4 instances. Once I switched the instances to C3.large, everything went through fine. 

It would have been helpful to get that information in the exception returned by packer, but it's probably only available in cloudtrail.

**Comment by catsby** [comment]
@ZepedaMcMillan that's ... odd. We're supposed to share the error:

- https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_run_source_instance.go#L160

on that line, `err` is not nil, but it also doesn't have anything to say... 
I'm curious if we could get more info out of it by casting it to an `awserr.Error` , but I'm not sure I can reproduce that myself. How many C4's slots are there typically?

**Comment by ZepedaMcMillan** [comment]
@catsby I'm not sure what the AWS limit is per account. The error message that I saw in cloudtrail indicated that it wasn't account specific but region specific, and that there just wasn't enough hardware available to facilitate the number of c4 instances I was trying to spin up.

**Comment by catsby** [comment]
ah... well.. it's very, very strange that the error was seemingly empty.. 

Am I OK to close this then?

**Comment by ZepedaMcMillan** [comment]
yes... go ahead and close it. Thanks for the assistance :+1:

**Comment by catsby** [comment]
Thanks for reporting!
