### ISSUE TITLE
Impoperly defined behaviour of 'shutdown_command'

### ISSUE THREAD

**Issue by Kounavi** [mitchellh/packer#2011]
Possibly related to this issue: #1029
Related error message: TCP connection to SSH ip/port failed: dial tcp <ipv4_address:port> connection refused

I'm experiencing this issue also but I have noticed something that I couldn't find anywhere before following the aforementioned solution. Specifically, I've noticed that this is consistent if I specify a 'shutdown_command' in packer and a reboot command takes place somewhere in a specified script. 
If I remove the 'shutdown_command' packer will restart the machine and continue with the next available script in place until it is shutdown properly from within the final script since it cannot shutdown when the 'shutdown_command' is specified. Also, packer will complain if no 'shutdown_command' is specified which is dubious since it actually won't work with scripts that reboot!

Basically, shouldn't this be clarified in the docs at least? :)
Also, packer should suppress the dubious warning although I understand that this may be troublesome and require more effort than mandated.

For reference here is the doc of shutdown_command:
```
shutdown_command (string) - The command to use to gracefully shut down the machine once all
the provisioning is done. By default this is an empty string, which tells Packer to just
forcefully shut down the machine.
```

Recommended doc:
```
shutdown_command (string) - The command to use to gracefully shut down the machine once all
the provisioning is done. By default this is an empty string, which tells Packer to just
forcefully shut down the machine unless a shutdown command takes place inside script so this may
safely be omitted. If one or more scripts require a reboot it is suggested to leave this blank
since reboots may fail and specify the final shutdown command in your last script.
```

**Comment by mitchellh** [comment]
Fixed
