### ISSUE TITLE
Concurrent vmware builds - not possible due to single VNC port

### ISSUE THREAD

**Issue by dantran** [mitchellh/packer#2012]
Since ESX VNC only listen to one VNC port, this means packer cannot build more than one VMs concurrently to the same ESX?

**Comment by dantran** [comment]
Hi can some confirm this?

**Comment by lokeshmadan** [comment]
Hi Can someone confirm on this, if this will be taken care in coming releases ? We are also facing the same issue.

**Comment by mitchellh** [comment]
This should now be fixed, but please let me know if it is not.

**Comment by dantran** [comment]
Not sure how this can get fixed where the ESX only allow 2 VNC port, one for with secure connection
and I can can confirm this is not working for me with boht packer 0.7.5 and 0.8

Maybe there is a way to 'tune' ESX allowing multiple VNC servers?
