### ISSUE TITLE
development environment appears to be broken

### ISSUE THREAD

**Issue by vogxn** [mitchellh/packer#2013]
I am trying to ingest some Pull Requests and alter some packer code. I have the code cloned locally, can test, can build and the binaries appear to be going into the $GOPATH. But the binaries are always getting built for `0.7.5` which is the latest packer release. Any changes I make to my tree are not appearing in the binary. What am I doing wrong? Earlier, dirty versions (development versions) showed `packer -v` to be the HEAD of the commit on which it was built, but now shows `0.7.5` always.

```bash
~/workspace/go/src/github.com/vogxn/packer/bin/packer -v
0.7.5
```

**Comment by sethvargo** [comment]
Hi @vogxn 

I am sorry you are having issues building Packer from master. Can you please try the following:

```shell
make updatedeps
make dev
```

This will make `bin/packer`.

**Comment by vogxn** [comment]
Hello @sethvargo 

Thanks for your reply. I am able to build fine using the steps you mentioned but the version of packer that is built does not have changes committed to the local tree. Only the `0.7.5` version appears to be built always. I added some additional `ui.Say` statements to my tree but do not see them in the built binary that is in `bin/packer`

**Comment by mitchellh** [comment]
The build scripts put the final binaries in two places: `./bin` and `$GOPATH/bin`.
