### ISSUE TITLE
Packer deletes existing versions of Vagrant boxes

### ISSUE THREAD

**Issue by Alaneor** [mitchellh/packer#2014]
Yesterday, I published a new version of my box. Today, I wanted to update one of the providers, not knowing that Packer does not allow that. This would be fine, except that Packer, once it errored out, deleted the whole version, including other providers.

**Preferrably, the boxes should remain intact if nothing has been uploaded, or at least other providers should remain available.**

Here is the log that led to the deletion of my previously-published version:

```
==> virtualbox-ovf (vagrant-cloud): Verifying box is accessible: dreamscapes/archlinux
    virtualbox-ovf (vagrant-cloud): Box accessible and matches tag
==> virtualbox-ovf (vagrant-cloud): Creating version: 2015.04.01
    virtualbox-ovf (vagrant-cloud): Version exists, skipping creation
                                                    ^^^^^^^^^^^^^^^^^
==> virtualbox-ovf (vagrant-cloud): Creating provider: virtualbox
==> virtualbox-ovf (vagrant-cloud): Cleaning up provider
    virtualbox-ovf (vagrant-cloud): Provider was not created, not deleting
==> virtualbox-ovf (vagrant-cloud): Cleaning up version
    virtualbox-ovf (vagrant-cloud): Deleting version: 2015.04.01
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Packer version: b49d74d (master)

**Comment by mitchellh** [comment]
Fixed. We just don't ever delete the version. I don't think there is any safe way to do it, so let's just not!

**Comment by Alaneor** [comment]
Excellent, thank you!
