### ISSUE TITLE
Chef Provisioner fails when creating staging directory with docker builder.

### ISSUE THREAD

**Issue by colinfkennedy** [mitchellh/packer#2015]
Packer is failing when trying to create the staging directory in my docker container.

My Packer version is: Packer v0.7.5
Docker version: 1.4.1

This is running on a Centos 6.6 vagrant VM, with both packer and docker installed on the vm. I can supply my packer template if needed.

This is the [gist](https://gist.github.com/colinfkennedy/5f0392a19f120810a753) for the full output from my packer build.

This is the part failing:

    2015/04/03 14:11:13 packer-builder-docker: 2015/04/03 14:11:13 Running the provision hook
    2015/04/03 14:11:13 ui:     docker: Creating directory: /tmp/packer-chef-client
        docker: Creating directory: /tmp/packer-chef-client
    2015/04/03 14:11:13 packer-builder-docker: 2015/04/03 14:11:13 Executing in container 73e4ebd3d3ecd34548f79893aca1150b779f59f27ec14281c54b2e9eea099ac8: "(mkdir -p '/tmp/packer-chef-client') >/packer-files/cmd043685979 2>&1; echo $? >/packer-files/cmd043685979-exit"
    2015/04/03 14:11:15 packer-builder-docker: 2015/04/03 14:11:15 [INFO] RPC endpoint: Communicator ended with: 1
    2015/04/03 14:11:15 [INFO] 0 bytes written for 'stderr'
    2015/04/03 14:11:15 [INFO] 0 bytes written for 'stdout'
    2015/04/03 14:11:15 [INFO] RPC client: Communicator ended with: 1
    2015/04/03 14:11:15 [INFO] RPC endpoint: Communicator ended with: 1
    2015/04/03 14:11:15 packer-provisioner-chef-client: 2015/04/03 14:11:15 [INFO] 0 bytes written for 'stderr'
    2015/04/03 14:11:15 packer-provisioner-chef-client: 2015/04/03 14:11:15 [INFO] 0 bytes written for 'stdout'

**Comment by colinfkennedy** [comment]
I also tried adding a shell provisioner to the beginning of my provisioners list to try create the tmp staging directories and set permissions on them:

    {
            "type": "shell",
            "inline": ["echo 'creating tmpdir'", "mkdir /tmp/packer-chef-solo", "chmod 777 /tmp/packer-chef-solo", "mkdir /etc/chef", "chmod 777 /etc/chef", "echo done"]
      }


However this fails too, as it can't upload the script. Here is the [gist](https://gist.github.com/colinfkennedy/d9f379834f1829f0229f)

Are there problems with permissions for the user packer is using to ssh to the docker container?

**Comment by mitchellh** [comment]
Fixed by #1993
