### ISSUE TITLE
Packer v0.7.5 - VMware VM - CD/DVD  Drive unsupported

### ISSUE THREAD

**Issue by nimeops** [mitchellh/packer#2023]
Hi, 
VMWare VMs created have CD/DVD  Drive not available (unsupported).
Need to delete and recreate it

![2015-04-07 10_18_08-frpe1eeumcolx1v - virtual machine properties](https://cloud.githubusercontent.com/assets/7293261/7019375/978194f2-dd0f-11e4-9cdf-ccc09f3b8fd8.png)

**Comment by rickard-von-essen** [comment]
Could you elaborate a bit, please. Post some information about your version of VMWare, OS, Packer etc. and config, logs etc.

**Comment by nimeops** [comment]
Sure sorry :
VMWare ESXi 5.5
Packer v0.7.5
OS Debian

**Comment by dragon788** [comment]
Was this VM created with the vmware-iso or vmware-vmdk builder, and which output/post processor was used? This is something I've typically seen when trying to copy a vm from a desktop VMware product directly to an ESXi product without using their converter or the new VMware Workstation 11 "push" capability.

**Comment by nimeops** [comment]
Hi, 
with the vmware-iso.

**Comment by israelshirk** [comment]
Do you have a copy of the relevant VMX files?

**Comment by dragon788** [comment]
Are you requiring the CD-ROM exist for adding additional software or just concerned about the existence of the unsupported hardware? You could do a post_vmx_data to remove the CD drive and then add it via the Vagrantfile if you needed it?

**Comment by michaeltlombardi** [comment]
Current builds with packer 10.1, esxi 5.5/6.0 seem to no longer have this issue. @nimeops, is this an ongoing problem?

**Comment by mwhooker** [comment]
Going to close since this appears to be fixed
