### ISSUE TITLE
Ansible Provisioner cannot complete on docker build

### ISSUE THREAD

**Issue by stefan79** [mitchellh/packer#2028]
Hi,
I am running a trusty Ubuntu VM with packer 0.7.5. I am running docker 1.5.0.

I am trying to build a docker image and provision it with ansible.  I cannot get packer to create a directory in the container:

```
2015/04/09 18:49:39 packer-builder-docker: 2015/04/09 18:49:39 Executing in container c65c29e2b8f13cb37212a519dddceb6e53a5e9a809d5af2eddd602cbc13d6dce: "(mkdir -p '/tmp/packer-provisioner-ansible-local') >/packer-files/cmd165116022 2>&1; echo $? >/packer-files/cmd165116022-exit"
2015/04/09 18:49:41 packer-builder-docker: 2015/04/09 18:49:41 [INFO] RPC endpoint: Communicator ended with: 1
```

Manually I seem to be able to create the directory. Is there something I am doing wrong?

**Comment by mitchellh** [comment]
This is fixed
