### ISSUE TITLE
On failure hook

### ISSUE THREAD

**Issue by rickeyski** [mitchellh/packer#2031]
Given that systemd no longer provides a useful error message when a service doesn't come up, it would be quite useful to pass a command in before packer kills the build.

I was able to do the following to resolve my issue using, https://github.com/rickeyski/packer/commit/6b69571d284dfaa36f573562835bce1d302a3cc9, but I assume there is a better / more generic solution for the use case.

Thanks

**Comment by mitchellh** [comment]
We've talked about this some, but we prefer that you wrap Packer in a script for this.

**Comment by rickeyski** [comment]
Do you have any suggestions on how to wrap packer to accomplish this? I can't think of a way that wrapping packer would work because the instance being built is shut down before any other commands can be sent to it from the wrapper.

Thanks in advance.
