### ISSUE TITLE
go source error in packer/builder/vmware/common/output_dir_local.go

### ISSUE THREAD

**Issue by laboger** [mitchellh/packer#2041]
A bug was reported to me by a user who tried to build packer on a ppc64le machine using gccgo from gcc 5.0, and when running testcases as part of the make, the following failure occurred:

2015/03/18 10:07:14 Waiting max 10s for shutdown to complete
2015/03/18 10:07:14 ui: Waiting for VMware to clean up after itself...
2015/03/18 10:07:14 No more lock files found. VMware is clean.
2015/03/18 10:07:14 VM shut down.
2015/03/18 10:07:14 ui: Forcibly halting virtual machine...
2015/03/18 10:07:14 ui: Waiting for VMware to clean up after itself...
2015/03/18 10:07:14 No more lock files found. VMware is clean.
2015/03/18 10:07:19 VM shut down.
2015/03/18 10:07:19 ui: Forcibly halting virtual machine...
2015/03/18 10:07:19 ui: Waiting for VMware to clean up after itself...
2015/03/18 10:07:19 No more lock files found. VMware is clean.
2015/03/18 10:07:19 VM shut down.
--- FAIL: TestStepShutdown_locks (0.00s)
	testing.go:278: should not have returned so quickly
2015/03/18 10:07:19 Suppressing messages in VMX
FAIL
FAIL	github.com/mitchellh/packer/builder/vmware/common	5.764s
 and the testcase step_shutdown_test failed.

After debugging it was found that the error was due to not finding the lock file, which was due to the following code in packer/builder/vmware/common/output_dir_local.go on the return from ListFiles:

return files, filepath.Walk(d.dir, visit)

The error occurred because of the order of evaluation in go, since the call to filepath.Walk was updating the files array.  The gccgo bugzilla can be found here:  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65772

The function ListFiles can be changed and the testcase then works:

err := filepath.Walk(d.dir, visit)
return files, err

**Comment by mitchellh** [comment]
This looks to be fixed.
