### ISSUE TITLE
No builder returned for name: amazon-ebs error

### ISSUE THREAD

**Issue by catsclaw** [mitchellh/packer#2043]
I built packer from source using the instructions at https://github.com/mitchellh/packer#developing-packer but when I try to create a template I get: "No builder returned for name: amazon-ebs"

What's going on? Do I have to install the builders separately?

**Comment by einarf** [comment]
Should work fine if you do a `make dev` in the packer source folder and execute the binary from the same location with `./bin/packer`

**Comment by catsclaw** [comment]
`root@ubuntu:/opt/go/src/github.com/mitchellh/packer# ./bin/packer`
`bash: ./bin/packer: No such file or directory`

There's a packer binary in `/opt/go/bin` but not `/opt/go/src/github.com/mitchellh/packer/bin`

**Comment by catsclaw** [comment]
Does anyone have any suggestions? I followed the instructions for building from scratch, but they don't appear to work.

**Comment by einarf** [comment]
`GOPATH` set to `/opt/go/` and you build with `make dev`?

**Comment by catsclaw** [comment]
Yes, and yes.

**Comment by einarf** [comment]
`export PATH=/opt/go/bin:$PATH`?

**Comment by catsclaw** [comment]
I just retried everything, and now it's working. No idea what changed.
