### ISSUE TITLE
File provisioner creates files with all bytes set to zero (Openstack provisioner)

### ISSUE THREAD

**Issue by agy** [mitchellh/packer#2044]
I've been testing Packer with Rackspace (Openstack provisioner) and discovered that files copied over to my image are the correct size but all bytes of the file are filled with zeros.

*See workaround below*

I have tested with Packer 0.7.5 and 0.7.2 on OSX and Linux.

### Steps to reproduce:

Packer version:

    $ packer version
    Packer v0.7.5

Packer template:

*Note:*
8226139f-3804-4ad6-a461-97ee034b2005 is the Rackspace provided image id for Ubuntu 14.04

    $ cat test-template.json
    {
        "variables": {
            "rax_username": "XXXXXX",
            "rax_api_key": "YYYYYY"
        },
        "builders": [
            {
              "type": "openstack",
              "username": "{{user `rax_username`}}",
              "api_key": "{{user `rax_api_key`}}",
              "openstack_provider": "rackspace",
              "provider": "rackspace-us",
              "region": "ORD",
              "ssh_username": "root",
              "flavor": "performance1-8",
              "source_image": "8226139f-3804-4ad6-a461-97ee034b2005",
              "image_name": "test-packer"
            }
        ],
        "provisioners": [
            {
                "type": "file",
                "source": "/etc/hosts",
                "destination": "/root/hosts"
            }
        ]
    }

Validate Template:

    $ packer validate test-template.json
    Template validated successfully.

Build Template:

    $ packer build test-template.json
    openstack output will be in this color.

    ==> openstack: Creating temporary keypair for this instance...
    ==> openstack: Waiting for server (abd49b6b-487a-4ca5-a306-b173c86d2bf2) to become ready...
    ==> openstack: Waiting for SSH to become available...
    ==> openstack: Connected to SSH!
    ==> openstack: Uploading /etc/hosts => /root/hosts
    ==> openstack: Creating the image: test-packer
    ==> openstack: Image: bfbb68c5-XXXX-XXXX-XXXX-078fc90d5367
    ==> openstack: Waiting for image to become ready...
    ==> openstack: Terminating the source server...
    ==> openstack: Deleting temporary keypair...
    Build 'openstack' finished.

Boot Image:

    $ nova boot --flavor performance1-8 --image bfbb68c5-XXXX-XXXX-XXXX-078fc90d5367 packer-img

SSH into the new instance:

    $ ssh root@ip.address.of.instance

Check file size of uploaded file:

    root@packer-img:~# ls -al hosts
    -rw-r--r-- 1 root root 214 Apr 15 20:17 hosts

Check contents of uploaded file:

    root@packer-img:~# cat hosts

Try determine the type of file:

    root@packer-img:~# file hosts
    hosts: data

Stat the file:

    root@packer-img:~# stat hosts
      File: ‘hosts’
      Size: 214         Blocks: 0          IO Block: 4096   regular file
    Device: ca01h/51713d    Inode: 1189072     Links: 1
    Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
    Access: 2015-04-15 20:17:08.588558000 +0000
    Modify: 2015-04-15 20:17:08.596558000 +0000
    Change: 2015-04-15 20:17:08.596558000 +0000
     Birth: -

Hexdump the file:

    root@packer-img:~# hexdump -v hosts
    0000000 0000 0000 0000 0000 0000 0000 0000 0000
    0000010 0000 0000 0000 0000 0000 0000 0000 0000
    0000020 0000 0000 0000 0000 0000 0000 0000 0000
    0000030 0000 0000 0000 0000 0000 0000 0000 0000
    0000040 0000 0000 0000 0000 0000 0000 0000 0000
    0000050 0000 0000 0000 0000 0000 0000 0000 0000
    0000060 0000 0000 0000 0000 0000 0000 0000 0000
    0000070 0000 0000 0000 0000 0000 0000 0000 0000
    0000080 0000 0000 0000 0000 0000 0000 0000 0000
    0000090 0000 0000 0000 0000 0000 0000 0000 0000
    00000a0 0000 0000 0000 0000 0000 0000 0000 0000
    00000b0 0000 0000 0000 0000 0000 0000 0000 0000
    00000c0 0000 0000 0000 0000 0000 0000 0000 0000
    00000d0 0000 0000 0000
    00000d6

### Workaround

Calling `sync` as the last step in the template seems to write changes correctly to disk.

Create a new template:

    $ diff -u test-template.json new-template.json
    --- test-template.json	2015-04-15 17:16:43.000000000 -0400
    +++ new-template.json	2015-04-15 17:16:12.000000000 -0400
    @@ -22,12 +22,6 @@
                 "type": "file",
                 "source": "/etc/hosts",
                 "destination": "/root/hosts"
    +        },
    +        {
    +            "type": "shell",
    +            "inline": [
    +                "sync"
    +            ]
             }
         ]
    }

Follow the same steps as above, building, booting and logging into the new instance:

    root@packer-img:~# cat hosts
    ##
    # Host Database
    #
    # localhost is used to configure the loopback interface
    # when the system is booting.  Do not change this entry.
    ##
    127.0.0.1   localhost
    255.255.255.255 broadcasthost
    ::1             localhost

**Comment by trumant** [comment]
I've been bitten by this issue before on a private OpenStack installation. Likewise, adding the sync fixed the issue. Perhaps a doc improvement is called for at a minimum

**Comment by mitchellh** [comment]
I've added this to the docs. This is the same as AWS as well.
