### ISSUE TITLE
Atlas Post-Processor: Interpolate in metadata block

### ISSUE THREAD

**Issue by pearkes** [mitchellh/packer#2048]
We need to be able to interpolate the template in the nested metadata block in the atlas post-processor:

```json
{
    "type": "atlas",
    "only": ["virtualbox-iso"],
    "artifact": "pearkes/test",
    "artifact_type": "vagrant.box",
    "metadata": {
        "provider": "virtualbox",
        "version": "0.0.1",
        "created_at": "{{timestamp}}"
    }
}]
```

**Comment by sethvargo** [comment]
This is also related to https://github.com/mitchellh/packer/issues/1861.

**Comment by mitchellh** [comment]
This is fixed now!

**Comment by pearkes** [comment]
![](http://ww2.kqed.org/pop/wp-content/uploads/sites/12/2013/12/tumblr_mb5kpkGBLu1qdj4i3o1_500.gif)
