### ISSUE TITLE
Error while following official documentation tutorial - The specified instance type can only be used in a VPC

### ISSUE THREAD

**Issue by tomazy** [mitchellh/packer#2056]
My AWS account is quite old (at least 2008) but I had no idea it would cause problems when following the official [tutorial](http://www.packer.io/intro/getting-started/build-image.html). I'm not sure how often people hit this wall, but I think it would be good to include some kind of warning in the tutorial at least. I can imagine someone less patient to give up giving this awesome tool a try.

In my case setting the instance type to `m3.medium` helped (thanks mbarrin from #packer-tool IRC channel for help)

Bellow is the output of the failing `packer build` command:
```
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 5534df0f-08d4-acaa-fc4e-8f69d2c7b545
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing SSH access on the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)

==> Builds finished but no artifacts were created.
```

**Comment by sethvargo** [comment]
Ping @KFishner

**Comment by ming-relax** [comment]
I have the same issue, I use aws everyday.

**Comment by Mihailoff** [comment]
+1

**Comment by KFishner** [comment]
@tomazy thanks for the heads up — I'll add a note for users on AWS classic and what settings to change

**Comment by catsby** [comment]
Hey all – https://github.com/mitchellh/packer/pull/1870 updated the documentation to resolve this issue. Thanks for reporting! Let us know if you run into anything else

**Comment by mblakele** [comment]
Googling "packer VPCResourceNotSpecified" brought me here. Seems like this was fixed in the doc-updates branch, but I still see t2.micro and the old AMI at https://www.packer.io/intro/getting-started/build-image.html and https://www.packer.io/docs/templates/introduction.html

**Comment by proffalken** [comment]
Agreed, this is still an issue on the documentation website.

**Comment by oryband** [comment]
PING. Still an issue.

**Comment by kaikousa** [comment]
Happened to me today, steps to overcome this:

* pick a subnet from your default VPC that AWS automatically creates
* create a security group with inbound rule of `protocol: SSH, port: 22, source: 0.0.0.0/0`
* add the following properties to the amazon-ebs -builder
```
"subnet_id": "subnet-123456",
"security_group_id": "sg-1234-allow-ssh"
```

Previously I didn't have this problem but today when I started building images to the production account instead of staging account I hit the wall with this error.

**Comment by dannenberg** [comment]
Still no note or change in the tutorial.

**Comment by rickard-von-essen** [comment]
Open a new issue if there is a problem with the docs or better open a PR with a suggested fix.
