### ISSUE TITLE
Affecting builder behaviour from command line

### ISSUE THREAD

**Issue by tusharm** [mitchellh/packer#2057]
Hello,

I am using `amazon-ebs` builder to generate AMIs. The builder is also configured to copy the generated AMI to multiple regions, which obviously takes a lot of time (sometimes about an hour or so). It would be ideal if I have the flexibility to include/exclude the AMI copying bit using, say, a command-line flag for quick testing. 
Generically, is it possible to selectively enable/disable builder behavior from command line? Can user variables help here? Or a custom post processor?

Thanks

**Comment by tusharm** [comment]
Looked at #1202 and I was able to make this work.
```
 "variables":
  {
    "regions": "us-east-1,us-west-1"
  }
```
and 
```
 "builders":
    [
      {
        ...
        "ami_regions": "{{user `regions`}}",
       ...
      }
   ]
```
The invocation looks like this when AMI copying needs to be skipped:
`packer build -var 'regions=' template/my_template.json`

**Comment by mitchellh** [comment]
Looks like you got it to work!
