### ISSUE TITLE
Packer 0.7.5 - Ubuntu 14.04 - Docker builder - Shell Provisioner can't start the script

### ISSUE THREAD

**Issue by ronthepanda** [mitchellh/packer#2065]
##### Problem
Packer hangs at "Provisioning with shell script" for a long time, then fails. I think it's very similiar with [this](https://github.com/mitchellh/packer/issues/2040) and [this](https://github.com/mitchellh/packer/issues/1752), just on Ubuntu.

##### System
Packer 0.7.5
Ubuntu 14.04.2 64 Bit

##### Docker Version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

##### Packer.json
[Here](https://gist.github.com/ronthepanda/19f12b6dcb68992c070d)

##### Errorlog
[Here](https://gist.github.com/ronthepanda/d321776cdef7571fbece)

**Comment by rickard-von-essen** [comment]
Duplicate, closing in favour of #2040
