### ISSUE TITLE
Don't raise error when a key start by _ in the configuration

### ISSUE THREAD

**Issue by lyrixx** [mitchellh/packer#2066]
The configuration is in a json format, and that prevent me to comment some part of the "code".
I would to be able to write comment, for instance about the base AMI I choose.
I tried something like that:

```json
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "region": "eu-west-1",
      "comment": "test",
      "source_ami": "ami-2596f652",
      "instance_type": "t1.micro",
      "ssh_username": "ubuntu",
      "ami_name": "packer-quick-start {{timestamp}}"
    }
```

But of course, it does not work :(

**Comment by mitchellh** [comment]
We're not supporting comments in JSON currently, but something like this is a good idea.

**Comment by sethvargo** [comment]
Would also be fixed by https://github.com/mitchellh/packer/issues/1768
