### ISSUE TITLE
How to place multiple provisioner types in a single provisioner block with environment_vars and the right JSON syntax

### ISSUE THREAD

**Issue by hyperfocus1337** [mitchellh/packer#2070]
JSON is hell. I'm trying to solve the syntax of my template for hours now.. can't seem to figure it out. Checked to see if there were any examples that matched the syntax I needed using Github search but couldn't find it. 

Sublime text doesn't give me any JSON syntax errors, but ```packer inspect``` tells me:

```
2 error(s) occurred:

* Unknown configuration key: destination
* Unknown configuration key: source
```

My template:

```
{
"variables": {
    "cleanup_pause": "",
    "cm": "ansible",
    "cm_version": "1.9.1",
    "custom_script": ".",
    "ftp_proxy": "{{env `ftp_proxy`}}",
    "headless": "",
    "http_proxy": "{{env `http_proxy`}}",
    "https_proxy": "{{env `https_proxy`}}",
    "install_vagrant_key": true,
    "iso_checksum": "",
    "iso_name": "vivid-server-amd64.iso",
    "iso_path": "iso",
    "iso_url": "http://cdimage.ubuntu.com/ubuntu-server/daily/current/vivid-server-amd64.iso",
    "no_proxy": "{{env `no_proxy`}}",
    "rsync_proxy": "{{env `rsync_proxy`}}",
    "hostname": "vagrant",
    "ssh_fullname": "vagrant",
    "ssh_password": "vagrant",
    "ssh_username": "vagrant",
    "update": "false",
    "version": "0.1.0"
  },

"provisioners": [
  {
   "environment_vars": [
     "CM={{user `cm`}}",
     "CM_VERSION={{user `cm_version`}}",
     "CLEANUP_PAUSE={{user `cleanup_pause`}}",
     "UPDATE={{user `update`}}",
     "INSTALL_VAGRANT_KEY={{user `install_vagrant_key`}}",
     "SSH_USERNAME={{user `ssh_username`}}",
     "SSH_PASSWORD={{user `ssh_password`}}",
     "http_proxy={{user `http_proxy`}}",
     "https_proxy={{user `https_proxy`}}",
     "ftp_proxy={{user `ftp_proxy`}}",
     "rsync_proxy={{user `rsync_proxy`}}",
     "no_proxy={{user `no_proxy`}}"
   ],

  "type": "file",
     "source": "/Volumes/MFiles/Dropbox/Cloudserver/Ansible/playbooks/nginx/deploy",
     "destination": "/opt",

  "type": "shell",
    "execute_command": "echo '{{ user `ssh_password` }}' | {{.Vars}} sudo -E -S bash '{{.Path}}'",
    "scripts": [
      "provision/script/update.sh",
      "provision/script/vagrant.sh",
      "provision/script/sshd.sh",
      "provision/script/vmtool.sh",
      "provision/script/minimize.sh",
      "provision/script/cleanup.sh",
      "provision/script/cmtool.sh",
      "provision/ansible/ansible-2-bootstrap.sh",
      "provision/ansible/ansible-3-apparmor.sh",
      "provision/ansible/ansible-4-firewall.sh",
      "provision/ansible/ansible-5-nginx.sh",
      "provision/ansible/ansible-6-php.sh",
      "provision/ansible/ansible-7-percona.sh",
      "provision/ansible/ansible-8-logrotate.sh",
      "provision/ansible/ansible-9-backups.sh"
    ]
  }
],

"builders": [
    {
      "boot_command": [
        "<esc><esc><enter><wait>",
        "/install/vmlinuz noapic ",
        "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
        "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
        "hostname={{ user `hostname` }} ",
        "fb=false debconf/frontend=noninteractive ",
        "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
        "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
        "passwd/user-fullname={{ user `ssh_fullname` }} ",
        "passwd/user-password={{ user `ssh_password` }} ",
        "passwd/user-password-again={{ user `ssh_password` }} ",
        "passwd/username={{ user `ssh_username` }} ",
        "initrd=/install/initrd.gz -- <enter>"
      ],

      "disk_size": 10140,
      "guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",
      "guest_os_type": "Ubuntu_64",
      "hard_drive_interface": "sata",
      "headless": "{{ user `headless` }}",
      "http_directory": "http",
      "iso_checksum_type": "none",
      "iso_urls": [
        "{{ user `iso_path` }}/{{ user `iso_name` }}",
        "{{ user `iso_url` }}"
      ],

      "shutdown_command": "echo '{{ user `ssh_password` }}'|sudo -S shutdown -P now",
      "ssh_password": "{{ user `ssh_password` }}",
      "ssh_username": "{{ user `ssh_username` }}",
      "ssh_wait_timeout": "10000s",
      "type": "virtualbox-iso",
      "virtualbox_version_file": ".vbox_version",
      "vm_name": "ubuntu1504",
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "512"
        ],

        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "1"
        ]
      ]
    }
  ],

"post-processors": [
    {
      "keep_input_artifact": false,
      "output": "box/ubuntu1504-{{user `cm`}}{{user `cm_version`}}-{{user `version`}}.box",
      "type": "vagrant"
    }
  ]
}
```

Would be very grateful if someone could point me in the right direction. Thx.

**Comment by rickard-von-essen** [comment]
The error message seams quite clear. You are not ending your _file provisioner_ block.

A correct example:
```json
"provisioners": [
  {
     "type": "file",
     "source": ".....",
     "destination": "...."
  },
  {
     "environment_vars": [ "CM={{user `cm`}}" ],
     "type": "shell",
     "execute_command": "...."
  }
]
```

**Comment by hyperfocus1337** [comment]
Worked, thank you very much!

**Comment by shashanksinha89** [comment]
I am still getting the error, already checked the provisioner block . Please see the below error I am geting.

1 error(s) occurred:

* unknown configuration key: "destination"

Below is the template that I am using for this.
{
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "echo 'vagrant'|sudo -S sh '{{.Path}}'",
      "override": {
        "vmware-iso": {
          "scripts": [
            "scripts/base.sh",
            "scripts/vagrant.sh",
            "scripts/vmware.sh",
            "scripts/cleanup.sh"
          ]
        }
      }
    }
  ],
  "post-processors": [
    {
      "type": "vagrant",
      "override": {
        "virtualbox": {
          "output": "centos-6-6-x64-virtualbox.box"
        },
        "vmware": {
          "output": "centos-6-6-x64-vmware.box"
        }
      }
    }
  ],
  "builders": [
    {
      "type": "vmware-iso",
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
      ],
      "boot_wait": "10s",
      "headless": "true",
      "disk_size": 40520,
      "guest_os_type": "centos-64",
      "http_directory": "http",
      "iso_checksum": "4ed6c56d365bd3ab12cd88b8a480f4a62e7c66d2",
      "iso_checksum_type": "sha1",
      "iso_url": "http://ftp.iij.ad.jp/pub/linux/centos/6.6/isos/x86_64/CentOS-6.6-x86_64-minimal.iso",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_wait_timeout": "10000s",
      "shutdown_command": "echo '/sbin/halt -h -p' > /tmp/shutdown.sh; echo 'vagrant'|sudo -S sh '/tmp/shutdown.sh'",
      "tools_upload_path": "/apps_data_01/lib/vmware/isoimages/linux.iso",
      "vmx_data": {
        "memsize": "1024",
        "numvcpus": "2",
        "cpuid.coresPerSocket": "1"
      }
   },
   {
      "type": "file",
      "source": "/apps_data_01/lib/vmware/isoimages/",
      "destination": "/home/vagrant"
   }
  ]
}

**Comment by cbednarski** [comment]
@shashanksinha89 Can you open a new github issue for this, please?

**Comment by btaouil** [comment]
I have the same issue as @shashanksinha89  it seems to happen when I add file uploader to a builder. I am not getting the error when I add the file uploader part to a provisioner.
