### ISSUE TITLE
Add URL support - source_path - virtualbox-ovf builder 

### ISSUE THREAD

**Issue by ronhoffmannn** [mitchellh/packer#2071]
Some minutes ago, i tried to grab an .ova/ofv file through a given url. Then i realized, that only a relativ/absolute path is valid. Here is, what i wanted to do.

```
"builders": [
    {
        "type": "virtualbox-ovf",
        "source_path" : "http://cloud-images.ubuntu.com/ubuntu-core/15.04/core/stable/current/core-stable-amd64-cloud.ova"
    }
],
```

What do you think about it? :)

**Comment by mitchellh** [comment]
Dup #1195
