### ISSUE TITLE
ssh_port directive in qemu builder ignored

### ISSUE THREAD

**Issue by james-portman** [mitchellh/packer#2074]
When using a non-standard ssh port (done via kickstart post section during build) with the qemu builder,
packer continually fails to connect to ssh after the install is complete and VM has rebooted.
(SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:2222: connection reset by peer)

If I log into the newly installed OS through the qemu UI, change the ssh port back to port 22, and restart sshd then packer is suddenly able to connect to ssh and shuts the VM down as expected.

This implies that ssh_port which was set correctly in the build json to 2020 (port ssh is listening on inside the VM) is being ignored and port is being forwarded to 22 on the VM.

This is using the current version from the main packer.io website, on Fedora 21;
https://dl.bintray.com/mitchellh/packer/packer_0.7.5_linux_amd64.zip

centos6.json;
{
  "builders":
  [
    {
      "type": "qemu",
      "iso_url": "http://__REMOVED__/6.6/isos/x86_64/CentOS-6.6-x86_64-minimal.iso",
      "iso_checksum": "eb3c8be6ab668e6d83a118323a789e6c",
      "iso_checksum_type": "md5",
      "output_directory": "output",
      "ssh_wait_timeout": "30s",
      "shutdown_command": "shutdown -P now",
      "disk_size": 13000,
      "format": "raw",
      "headless": false,
      "accelerator": "kvm",
      "http_directory": "httpdir",
      "http_port_min": 10082,
      "http_port_max": 10089,
      "ssh_host_port_min": 2222,
      "ssh_host_port_max": 2229,
      "ssh_username": "root",
      "ssh_password": "__ROOTPASS__",
      "ssh_port": 2020,
      "ssh_wait_timeout": "90m",
      "vm_name": "centos6",
      "net_device": "virtio-net",
      "disk_interface": "virtio",
      "boot_wait": "5s",
      "boot_command":
      [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos6 method=http://__REMOVED__/6/os/x86_64/<enter><wait>"
      ],
      "qemuargs": [
        [ "-m", "1024" ]
      ]
    }
  ],
  "post-processors":
  [
    {
      "type": "compress",
      "output": "output/centos6.tar.gz"
    }
  ]
}

**Comment by james-portman** [comment]
Further to this:
I can see the virtualbox builder implementing the forward here specifically using the guest port passed in from config;
https://github.com/mitchellh/packer/blob/master/builder/virtualbox/common/step_forward_ssh.go#L58

but cannot see where this is done for qemu

**Comment by james-portman** [comment]
Thanks for the fix,
do you know what release/live version this will go into?

**Comment by mitchellh** [comment]
0.8.0
