### ISSUE TITLE
googlecompute builder 400 Bad Request

### ISSUE THREAD

**Issue by enxebre** [mitchellh/packer#2077]
Packer v0.7.5 Whe using googlecompute builder following the docs for using my account_file.json I got:

2015/04/28 13:02:46 packer-builder-googlecompute: 2015/04/28 13:02:46 [INFO]   -- Private Key Length: 912
2015/04/28 13:02:46 packer-builder-googlecompute: 2015/04/28 13:02:46 [INFO] Instantiating GCE client using...
2015/04/28 13:02:46 ui: ==> googlecompute: Checking image does not exist...
==> googlecompute: Checking image does not exist...
2015/04/28 13:02:46 ui: ==> googlecompute: Creating temporary SSH key for instance...
==> googlecompute: Creating temporary SSH key for instance...
2015/04/28 13:02:46 ui: ==> googlecompute: Creating instance...
==> googlecompute: Creating instance...
2015/04/28 13:02:46 ui:     googlecompute: Loading zone: europe-west1-b
    googlecompute: Loading zone: europe-west1-b
2015/04/28 13:02:47 ui error: ==> googlecompute: Error creating instance: Get https://www.googleapis.com/compute/v1/projects/esoteric-state-92909/zones/europe-west1-b?alt=json: oauth2: cannot fetch token: 400 Bad Request
==> googlecompute: Response: {
==> googlecompute:   "error" : "invalid_grant"
==> googlecompute: }
==> googlecompute: Error creating instance: Get https://www.googleapis.com/compute/v1/projects/esoteric-state-92909/zones/europe-west1-b?alt=json: oauth2: cannot fetch token: 400 Bad Request
==> googlecompute: Response: {
==> googlecompute:   "error" : "invalid_grant"
==> googlecompute: }

thanks

**Comment by dcarlino** [comment]
Does this happen consistently?

http://stackoverflow.com/questions/11973162/google-analytics-api-oauth-exception-invalid-grant-with-service-account-same has two possible reasons for invalid_grant. Is the clock on the machine where you're running Packer synced?

**Comment by enxebre** [comment]
I reckon it was some proxy related stuff as I was behind a proxy when not working even if I had set the http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY variables. It is working now that I have direct connection to the internet though.
thanks!
