### ISSUE TITLE
parallel_tools_mode

### ISSUE THREAD

**Issue by clivecrous** [mitchellh/packer#2079]
From the documentation "The functions of each of these should be self-explanatory."

They're not, not at all.

**Comment by rickard-von-essen** [comment]
@clivecrous could you elaborate a bit. What is unclear, do you have any suggestions on what should be explained?

**Comment by clivecrous** [comment]
@rickard-von-essen :

What is the difference between "upload" & "attach"?

What gets uploaded? What gets attached?

I've experimented a bit and it appears the iso is uploaded, but I've been unable to get attach to work since I have no idea what's going to be attached. I've noticed that there are issues if I try attach to a folder within a folder I'm using for other temporary files (scripts and the like) but it's incredibly difficult to try guess how to use attach not knowing what's meant to be happening.

Unfortunately I can't elaborate more since there's no documentation giving me even the slightest clue how those work or what they do or what the expected outcome is especially with relation to other commands like "parallels_tools_guest_path" ... is that a path of an iso as a file? ... a mounted iso? ... a folder? does upload/attach alter what it is?

**Comment by rickard-von-essen** [comment]
Thanks, that gives me some hints on what to write in the docs. Would the following explain better:

> ### parallels_tools_guest_path
> (string) - The path in the VM to upload Parallels Tools. This only takes effect if parallels_tools_mode is "upload". This is a configuration template that has a single valid variable: Flavor, which will be the value of parallels_tools_flavor. By default the upload path is set to prl-tools-{{.Flavor}}.iso. When a non absolut path is given the base is relative to the home directory of the user specified by ssh_username.

> ### parallels_tools_mode 
> (string) - The method by which Parallels Tools are made available to the guest for installation. Valid options are "upload", "attach", or "disable". If the mode is "attach" the Parallels Tools iso will be attached as a CD device to the VM. If the mode is "upload" the Parallels Tools iso will be uploaded to the path specified by parallels_tools_guest_path. The default value is "upload".

Feel free to sugest any further improvements or better wording.

**Comment by clivecrous** [comment]
Ahhh sweet, thank you so much yea that's fantastic!

doh CD rom I didn't think to look there, now attach becomes exactly what I was looking for

**Comment by rickard-von-essen** [comment]
I'll close this when I have done a PR for the docs. (I'll also update the VirtualBox docs).

**Comment by kikitux** [comment]
Attach will connect the ISO to the CD/DVD of the vm

then in your script you should do something like

mkdir -p /mnt/dvd
mount /dev/dvd /mnt/dvd

<command_for_additions_install>

umount /dev/dvd
eject /dev/dvd


In upload, you get a copy on the home of the user being used, so then you do:

mkdir -p /mnt/dvd
mount ~/*iso /mnt/dvd

<command_for_additions_install>

umount /dev/dvd
rm ~/*iso

or similar
