### ISSUE TITLE
Add prctl_post in builder Parallels

### ISSUE THREAD

**Issue by gildas** [mitchellh/packer#2080]
Could we get a prctl_post the same way VMware and Virtualbox have (vmxdata_post, vboxmanage_post)?

Currently, there is no way to execute prctl just before the post-processor.

**Comment by rickard-von-essen** [comment]
@gildas I have created a fix for this. It would be awesome if you could test this.

You can download my dev build from https://www.dropbox.com/s/qjmmlsip0cxzqcj/packer_2080.zip?dl=0
or build it yourself from source if you are comfortable with that.

**Comment by gildas** [comment]
@rickard-von-essen, fantastic. I will give it a try, maybe, tomorrow morning (JST).
We are right in the middle of the Golden Week in Japan, and the entire country is more or less off.
So, that makes me a little slower than usual...

**Comment by gildas** [comment]
Hey Rickard, Sorry for the big delay.
I just tested it and it is working very well.

Will this be in 0.8.0?

**Comment by rickard-von-essen** [comment]
Yes, see #2126

**Comment by gildas** [comment]
Groovy! Thanks again for the big help!
