### ISSUE TITLE
Add support for VMware Workstation 11 and Player 7

### ISSUE THREAD

**Issue by blopker** [mitchellh/packer#2085]
Both Workstation 11 and Player 7 fail to work with Packer on Linux. Packer is unable to detect 11's and 7's version number since it only looks for Workstation 10 and 9 and Player 6 and 5.

Bother 11 and 7 error with: `Build 'vmware-vmx' errored: Cloning is not supported with VMWare Player version 5. Please use VMWare Player version 6, or greater.`

The commands in 11 and 7 seemed to not have changed so it should just be a matter of adding drivers for them with an updated version number.

**Comment by sci-burns** [comment]
I am hitting this with Packer 0.7.5.  Tried moving back from Workstation 110 to 10.06 and still hist this issue.  Any suggestions?

```
$ sudo vmware --version
VMware Workstation 10.0.6 build-2700073
$ sudo vmplayer --version
VMware Player 6.0.6 build-2700073
```

**Comment by blopker** [comment]
As far as I can tell, this is not actually a issue with the version detection. The error message is misleading.

However, I never did get Packer working with Workstation or Player. I'm told it should work with Player Pro, Fusion Pro. I think my main issue was that I was trying to do this inside a VM, but I have no idea.
