### ISSUE TITLE
Mechanism to extract files from the build machine

### ISSUE THREAD

**Issue by apparentlymart** [mitchellh/packer#2086]
When running tests (for example, ServerSpec) inside packer it would be convenient to have a mechanism to copy files from the machine being built out into the host machine, so that test report files can be archived.

Post-processors run after the build machine is already shut down and the image artifact created, so it seems like this step is too late.

The simplest solution would likely be to have a funny sort of provisioner that acts like the opposite of the file upload provisioner, downloading a file out of the VM. This is technically possible, but it feels weird from a terminology standpoint to call that a "provisioner".

**Comment by apparentlymart** [comment]
If this feature sounds useful I can write some code for it. I think I'd just make a new provisioner, but I'd love to hear other design ideas too.

**Comment by mitchellh** [comment]
Done in master, and documented.
