### ISSUE TITLE
Build command doesn't exit with code 1 if a provisioner fails

### ISSUE THREAD

**Issue by caccialdo** [mitchellh/packer#2088]
Hi,

Had this annoying issue which kept Travis telling me my builds were successful even if some provisioner in the `packer build ... config.json` command failed. It seems that this command doesn't exit with the code of its child processes.

Currently, my workaround is to call `set -e` before executing that command so that child processes exit codes are passed to their parent.

**Comment by mitchellh** [comment]
I'm not sure this is a bug. Packer executes the shell provisioners in a shell, and that shell will exit with code 0 unless you do something like "set -e" with the "inline" option. Any scripts should properly report their code. Am I incorrect?

**Comment by caccialdo** [comment]
Indeed, setting `set -e` works but shouldn't it be there by default?
