### ISSUE TITLE
Packer crashes with unix socket binding error due long tmp directory 

### ISSUE THREAD

**Issue by dantran** [mitchellh/packer#2091]
Hi, my Releng does not allow the writing to the default /tmp directory, so I use $TMPDIR env to set it under our Jenkins job workspace directory and if this is long enough will cause Packer to crash

Here is the stack trace

2015/05/02 09:45:18 waiting for all plugin processes to complete...
panic: listen unix /space/jenkins/trand8/.jenkins-slave/workspace/skyline-ova/brs-installer/.external-resources/tmp/packer-plugin455105171: bind: invalid argument
2015/05/02 09:45:18 packer-builder-vmware-iso: 
2015/05/02 09:45:18 packer-builder-vmware-iso: goroutine 16 [running]:
2015/05/02 09:45:18 packer-builder-vmware-iso: runtime.panic(0x879c60, 0xc20803b9c0)
2015/05/02 09:45:18 packer-builder-vmware-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/panic.c:279 +0xf5
2015/05/02 09:45:18 packer-builder-vmware-iso: main.main()
2015/05/02 09:45:18 packer-builder-vmware-iso: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/plugin/builder-vmware-iso/main.go:11 +0x67
2015/05/02 09:45:18 packer-builder-vmware-iso: 
2015/05/02 09:45:18 packer-builder-vmware-iso: goroutine 19 [finalizer wait]:
2015/05/02 09:45:18 packer-builder-vmware-iso: runtime.park(0x412ce0, 0xb6b190, 0xb69349)
2015/05/02 09:45:18 packer-builder-vmware-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1369 +0x89
2015/05/02 09:45:18 packer-builder-vmware-iso: runtime.parkunlock(0xb6b190, 0xb69349)
2015/05/02 09:45:18 packer-builder-vmware-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1385 +0x3b
2015/05/02 09:45:18 packer-builder-vmware-iso: runfinq()
2015/05/02 09:45:18 packer-builder-vmware-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/mgc0.c:2644 +0xcf
2015/05/02 09:45:18 packer-builder-vmware-iso: runtime.goexit()
2015/05/02 09:45:18 packer-builder-vmware-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1445
2015/05/02 09:45:18 packer-builder-vmware-iso: 
2015/05/02 09:45:18 packer-builder-vmware-iso: goroutine 20 [syscall]:
2015/05/02 09:45:18 packer-builder-vmware-iso: os/signal.loop()
2015/05/02 09:45:18 packer-builder-vmware-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
2015/05/02 09:45:18 packer-builder-vmware-iso: created by os/signal.init·1
2015/05/02 09:45:18 packer-builder-vmware-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/os/signal/signal_unix.go:27 +0x32
2015/05/02 09:45:18 /space/jenkins/trand8/.jenkins-slave/workspace/skyline-ova/brs-installer/.external-resources/packer/0.7.5-SNAPSHOT/packer-builder-vmware-iso: plugin process exited
2015/05/02 09:45:18 ui error: Failed to create build 'vmware-iso': 

plugin exited before we could connect
2015/05/02 09:45:18 waiting for all plugin processes to complete...

build-vmware.sh:[FAILED]: Packer build failed due to error...
Failed to create build 'vmware-iso': 

plugin exited before we could connect

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/mitchellh/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dantran** [comment]
note the log show packer/7.5.0-SNAPSHOT,  it is a real packer 7.5.0 release, we just name snapshot until GA in case we need to pickup a new version of packer

**Comment by rickard-von-essen** [comment]
@dantran Could you provide the full log (see [Packer docs - Debugging](http://packer.io/docs/other/debugging.html)) and maybe a minimal config.json to reproduce this.

**Comment by dantran** [comment]
i am very sure you can reproduce it easily at linux by setting TMPDIR=log/path for any packer command

and I also found this

http://man7.org/linux/man-pages/man7/unix.7.html

are we hitting the unix socket file limit of  108 char?

**Comment by mitchellh** [comment]
Yes, that is the case. Packer requires unix sockets to work. Please try to find a slightly shorter path somewhere. Sorry. There also isn't really a better way we can start the plugins to show errors so this is what its going to be for now.
