### ISSUE TITLE
ami_block_device_mappings with different snapshot_id per region

### ISSUE THREAD

**Issue by roumano** [mitchellh/packer#2094]
Hi,
I'm trying to create several ami with ami_regions argument
    In the documention, I don't found how to add ami_block_device_mappings with snapshot_id per region
So my ami in different region have the same snapshot_id where it's not possible.

 As snapshot_id are different per region, it's will be great if we can specify somehere each snapshot_id per region in the "ami_block_device_mappings (array of block device mappings)"

**Comment by catsby** [comment]
Hello –

Copying the AMI generated to the various regions uses the [CopyImage][1] API call, which at present doesn't offer anyway for us to adjust the block devices. It doesn't seem that the API allows us to modify block devices per region in this way.

Hopefully I'm understanding your situation correctly. You're say that you supply a `snapshot_id`in your `ami_block_device_mappings` configuration, but after your AMI is copied to the various regions, the resulting AMIs are not usable? 

Thanks for helping to clarify. 


[1]: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CopyImage.html

**Comment by roumano** [comment]
My issue is : ami_block_device_mappings will be the same on different region
as the snapshot_id of it is only available in one region, the ami is unsable for other region

**Comment by mitchellh** [comment]
@roumano Yep, but as @catsby said we don't have any control over that with the `CopyImage` API call. If you want to create multiple AMIs with different block devices, just use multiple builders. The `ami_regions` field won't work for that and I don't see a way to make it work for that.
