### ISSUE TITLE
[Ansible + SSH] Deleted task in host are not delete onto target

### ISSUE THREAD

**Issue by lyrixx** [mitchellh/packer#2096]
I use packer + ssh to test my packer configuration because I think it's the fastest way to test it.

And I'm using ansible to configure my node.

Step to reproduce:

1. Create an empty playbook
2. Add a new task in it. Let's call it `main.yml`. the task can just "write something in a files"
3. run packer
4. removed the `main.yml` task.
5. run packer again

=> the task `main.yml` is always executed because it's still present on the "cache" folder in `/tmp/packer-provisioner-ansible-local` on the remote node.

Why ? because packer use `scp` to [transfert the files](https://github.com/mitchellh/packer/blob/c8b3dfff5fa8470f7d639c3e6b09f15ff09fa7c2/communicator/ssh/communicator.go#L139-L171).

IMHO, `rsync` is a better tools to transfert files. WDYT?

**Comment by rickard-von-essen** [comment]
IMHO this scenario is slightly out of scope for packer.

**Comment by mitchellh** [comment]
I think it does make sense for Packer to actually remove that folder prior to provisioning.
