### ISSUE TITLE
Atlas * Post-processor failed: Error uploading: Metadata must have 'provider' key

### ISSUE THREAD

**Issue by paul** [mitchellh/packer#2099]
I get the above error when using this template.json when pushing to atlas:

```json
    "post-processors": [
      [{
        "type": "vagrant",
        "keep_input_artifact": false
      },
    {
      "type": "atlas",
      "only": ["virtualbox-iso"],
      "artifact": "{{user `atlas_username`}}/{{user `atlas_name`}}",
      "artifact_type": "vagrant.box",
      "metadata": {
        "created_at": "{{timestamp}}"
      }
    },
    {
      "type": "atlas",
      "only": ["amazon-ebs"],
      "artifact": "{{user `atlas_username`}}/{{user `atlas_name`}}",
      "artifact_type": "aws.ami",
      "metadata": {
        "created_at": "{{timestamp}}"
      }
    }]
```

The `amazon-ebs` one works, but the vagrant/virtualbox one gives that error:

![](https://dl.dropboxusercontent.com/s/k1eqfn2f5m10yv3/2015-05-05%20at%209.18%20PM.png)

**Comment by pearkes** [comment]
@paul When uploading `artifact_type` of `vagrant.box` you need to set a provider that will be used with Vagrant. In this case, you should be setting `virtualbox`. So:

```
    {
      "type": "atlas",
      "only": ["virtualbox-iso"],
      "artifact": "{{user `atlas_username`}}/{{user `atlas_name`}}",
      "artifact_type": "vagrant.box",
      "metadata": {
        "created_at": "{{timestamp}}",
        "provider": "virtualbox"
      }
    }
``` 

This stores the box properly and Atlas so Vagrant can determine what provider to use when pulling it donw.

**Comment by paul** [comment]
Thanks.

Is that documented anywhere that I should have looked first? All I found 
about post-processor metadata was from the packer docs 
(https://www.packer.io/docs/post-processors/atlas.html#metadata) which 
does not have much to say about what fields to use.

Also, is there a better place to ask questions like this? It wasn't 
really a problem that deserved a GitHub issue, I think.

**Comment by mitchellh** [comment]
Updated docs!

**Comment by punkrokk** [comment]
You should update the example config on this page also:

**Comment by cbednarski** [comment]
@punkrokk This issue is pretty old. Can you open a PR or a new issue, please? Thanks!
