### ISSUE TITLE
shell provisioner hangs on lengthy scripts

### ISSUE THREAD

**Issue by gildas** [mitchellh/packer#2100]
I have a powershell script that takes roughly 12 minutes to complete successfully.
When I execute it through a powershell provisioner, like (in packer.json):
```json
{
  "type":  "shell",
  "remote_path":  "/cygdrive/c/Windows/Temp/script-install-things.ps1",
  "execute_command": "{{.Vars}} powershell -NoLogo -ExecutionPolicy ByPass -File C:/Windows/Temp/script-install-things.ps1",
  "scripts":
  [
    "./scripts/install-things.ps1"
  ]
 },
```
Packer will at some point hang, not show any Write-Output/Write-Host the script emits, and not return anymore (I have to hit ^C to stop the build).

Does this ring a bell to anybody?

- if the scripts lasts less than roughly 6 minutes, all is good.
- The builder does not matter, I can reproduce this in Virtualbox, VMWare, and Parallels.
- I did configure winrm in the VM properly (I think), see the gist: [config-winrm.cmd](https://gist.github.com/gildas/d3a9d71ea5a9a240140a)

**Comment by mitchellh** [comment]
This should be fixed upstream. Thanks!
