### ISSUE TITLE
Support replacing placeholders in vagrantfile with user variables

### ISSUE THREAD

**Issue by marcofranssen** [mitchellh/packer#2101]
I would really love to have support for replacing variables in my vagrant template file with user variables.

Vagrantfile.template

``` ruby
    config.vm.define {{boxname}}
    config.vm.box {{boxname}}
    config.ssh.forward_agent {{forwardSshAgent}}
```

packer.json

``` json
{
    "variables": {
        "boxname": 1,
        "memory": 1024,
        "forwardSshAgent": true,
        "vram": 12,
        "disk_size": 20000
    },
    "builders": [{
        "vm_name": "{{user `boxname`}}",
```

This way you can reuse a lot of logic and configuration already in the packer file and have them automatically with the same values in the vagrant box Vagrantfile.

**Comment by dev-head** [comment]
+1 what he said

**Comment by tylert** [comment]
This might, ultimately, use a similar templating system as #1673.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the mailing list
for more details on 1.0.
