### ISSUE TITLE
with Amazon instance-store builder, needing ec2-migrate-image after provisioners complete

### ISSUE THREAD

**Issue by jamesyouknowwho** [mitchellh/packer#2103]
Hello,
I'm trying to run ec2-migrate-image commands after a instance-store builder is complete. I would like to keep the bundle_vol_command and bundle_upload_command within my builder and not deal with running these commands from inside a shell.

It seems like I would need a new builder to be run in series (after the desired volume has been bundled/uploade) to do this work.  How would I run the builds in series and how do i grab the Manifest upload location from the previous builder output.  The Manifest pat currently has a time stamp in it to prevent clobber, but perhaps just remove timestanp (and allow clobber) and then i would know the path, or is there a better way?

Thanks,
Paul

**Comment by mitchellh** [comment]
You can use the `ami_regions` setting to copy an image even with the instance builder.
