### ISSUE TITLE
unify provider names (vmware vs. vmware_desktop)

### ISSUE THREAD

**Issue by arosenhagen** [mitchellh/packer#2104]
This is a follow-up of https://github.com/mitchellh/vagrant/issues/5227.
I tracked the problem down to the following code: https://github.com/mitchellh/packer/blob/e422a4544915b58e0f89e0cd341175809ed48423/post-processor/vagrant-cloud/post-processor.go#L191
```
func providerFromBuilderName(name string) string {
	case "vmware":
		return "vmware_desktop"
}
```
The main part here is, that we use {{.Provider}} in a packer template and use that in reference to Atlas/Vagrant (e.g. https://github.com/ffuenf/vagrant-boxes/blob/master/packer/debian-6.0.10-amd64.json#L156). In this case we get "vmware" for {{.Provider}} where Atlas and Vagrant expects "vmware_desktop".
Is there any way to always get "vmware_desktop"?

**Comment by mitchellh** [comment]
The "vmware" you get in the filename shouldn't affect the provider metadata for Atlas. That is the the first part you linked to and quoted: we always return "vmware_desktop".
