### ISSUE TITLE
Resume ISO (and other) Downloads

### ISSUE THREAD

**Issue by clivecrous** [mitchellh/packer#2106]
I have a standalone CI builder (packer runner) that re-builds on commit. It often fails to download ISOs where wget can automatically resume.

I'd like to see either support for download retries / resuming or perhaps a configuration setting to use an external configurable download tool/command to better deal with these situations.

**Comment by vtolstov** [comment]
I thinks this is not big problem, you can download image before packer starts, but in case of packer - i thinks we need resume_download flag and try to do range requests.

**Comment by clivecrous** [comment]
It is a problem on a remote server that I don't have access to that's attempting to download / create / upload without human assistance.

**Comment by mitchellh** [comment]
This shouldn't be too difficult to add directly to `common.StepDownload` with some changes.
