### ISSUE TITLE
Apply globs to directory structures in push includes

### ISSUE THREAD

**Issue by sheldonh** [mitchellh/packer#2114]
Currently, `packer push` uses Golang's [filepath.Glob](http://golang.org/pkg/path/filepath/#Glob) to determine the set of files to push.

Rather than excluding the set of files that I know to be sensitive today, I would prefer to only include the set of files that I know to be relevant today.

But `filepath.Glob` doesn't support `**`, so there's no way for me to "include this entire directory tree, e.g.

```json
"push": {
  "name": "sheldonh/appliance",
  "include": [
    "scripts/*"
  ]
}
```

This only includes `scripts/debian`, but not `scripts/debian/cleanup.sh`.

It would be wonderful if either `scripts` or `scripts/**` would include the entire directory tree under `scripts`.

**Comment by sheldonh** [comment]
Just to add to that, it would also be wonderful if I could exclude files deep in the directory tree without specifying the path to each, e.g.

```json
"push": {
  "name": "sheldonh/appliance",
  "exclude": [
    "**/*.key",
    "**/*_key.pem"
  ]
}
```

Yes, I know these files shouldn't be in the git repo at all. But I'm trying to demonstrate the value of Atlas to a team with a very old Puppet repo that is used to build over 90 classes of system, of which they have over 2,500 instances in production. It would be wonderful if I could demonstrate the value of automated nightly builds with Atlas (and testing with Terraform) *before* initiating the holy war on secrets in git. :-)

**Comment by sethvargo** [comment]
Hi @sheldonh 

Thank you for opening an issue. I actually think we fixed this in master, but we have not cut a new release yet. Could you please try building from master and let me know if that fixes the issue?

**Comment by sethvargo** [comment]
@sheldonh specifically: https://github.com/hashicorp/atlas-go/pull/32

**Comment by mitchellh** [comment]
Closing due to lack of response, I think its fixed.

**Comment by sheldonh** [comment]
Sorry. Had to chase a workaround for other reasons, so this got
deprioritised a bit.

I'll feed back if I have a problem.
