### ISSUE TITLE
merge compress post processor to packer core

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#2119]
I want to merge my post processor to packer core, please check does it possible:

my code lives in https://github.com/vtolstov/packer-post-processor-compress

**Comment by mitchellh** [comment]
Oh this looks really good! I'll take a look!

**Comment by cbednarski** [comment]
This is merged now, thanks @vtolstov!

**Comment by vtolstov** [comment]
Does I can create pull request to ressurect bgzf compressor and additional
option for compressor format?
19 июня 2015 г. 22:54 пользователь "Chris Bednarski" <
notifications@github.com> написал:
