### ISSUE TITLE
VMWare post-processor does not remove its VM in VMWare's Virtual Machine Library

### ISSUE THREAD

**Issue by gildas** [mitchellh/packer#2122]
When packer calls the VMWare post-processor, it will not remove the VM from VMWare's Virtual Machine Library after its task is complete.

**Comment by kelseyhightower** [comment]
@gildas I was seeing this issue as well, then I set headless = true in my configuration template and the problem seemed to go away -- might be a good work-around for now.

```
"builders": [{
    "type": "vmware-vmx",
    "headless": true,
    ....
```

**Comment by mitchellh** [comment]
We see this in Vagrant as well, and I've also reached out to VMware, and there isn't really a way for external processes to remove things from this. I haven't found where this data is stored so we can't really remove it. If you have any more info on how we could remove it, then please let us know.

@kelseyhightower is correct and headless will sometimes hide it. I think if the GUI is open when you start a headless VM is still shows up, or something weird like that.
