### ISSUE TITLE
Packer fails to find new AWS EC2 Instance

### ISSUE THREAD

**Issue by lokulin** [mitchellh/packer#2128]
Often packer fails to find a newly created AWS EC2 instance.  Usually the instance is actually created and the API is just being slow to realise it.

Retrying the check to see if the instance has been created would probably fix this.

In our environment, in the previous 28 days packer has failed to find 204 successfully created instances causing us to have to manually mop up the instances, keys and groups.

**Comment by renat-sabitov** [comment]
https://github.com/mitchellh/packer/pull/1764

**Comment by renat-sabitov** [comment]
Also https://github.com/mitchellh/goamz/pull/180

**Comment by lokulin** [comment]
@renat-sabitov had already tried patching in #180 , but #1764 looks like it will fix this particular problem and is a better solution than my PR.  I'll patch our fork and see how we go.  Thanks.

**Comment by mitchellh** [comment]
Fixed by #1764
