### ISSUE TITLE
Consider *not* enforcing that all variables are declared

### ISSUE THREAD

**Issue by nevir** [mitchellh/packer#2138]
I have `var-file`s that contain values that I want to share amongst multiple images (for example, values for `source_ami` for ec2 builders). I don't want to use _all_ of those variables in each packer template.

Currently, if you provide more variables than the template declares, you end up with `Unknown user variables: <extra var>` errors.

I'm working around this by wrapping `packer build` with a script that only supplies the variables declared in the template. It's not great :(

**Comment by mitchellh** [comment]
Done
