### ISSUE TITLE
Modular templates and hashmaps

### ISSUE THREAD

**Issue by smaftoul** [mitchellh/packer#2140]
I have a collection of modular templates with values from variables. Now I want to add   a modular "ami_block_device_mappings" for my amazon-ebs builder. The problem I encounter is that the ami_block_device_mappings is an array of hashmaps and I can't seem to find a way to pass a hashmap to the template. Is that something doable ?

**Comment by mitchellh** [comment]
There isn't a way to do this right now and we don't plan on adding this in the near future. Sorry! We recommend using an external script to generate the JSON for Packer.
