### ISSUE TITLE
Packer uses ec2-upload-bundle w/ --region option for older ec2-upload-bundle installs that should use --location instead

### ISSUE THREAD

**Issue by sandbender** [mitchellh/packer#2142]
Related to issue #1931 

We're using (we were - I had to manually update by hand so this would work) ec2-ami-tools version 1.4.0.2 (ancient, I know, but this is 'latest' as available from 3rd party repos on Ubuntu Precise afaict).

After upgrading packer to 0.7.5, my builds fails due to Packer attempting to use --region - for the older version of ec2-upload-bundle we had, this sounds like it *should* be --location instead.

**Comment by catsby** [comment]
Closing; the flag for the current version is `--region`. If you need to use older versions of the tools, you can provide custom `bundle_vol_command` or `bundle_upload_command` in your configuration.

**Comment by agarwal0515** [comment]
using packer version 0.8.2 still getting unable to upload bundle,
tried writing custom bundle_upload_command, still getting same error
