### ISSUE TITLE
Environment variables not being recognized in Ubuntu 12.04

### ISSUE THREAD

**Issue by brenzenb** [mitchellh/packer#2144]
I've got an error on Linux that I can't reproduce on Mac OSX. 
After setting my environment variables:
`export AWS_ACCESS_KEY="some_valid_key"`
`export AWS_SECRET_KEY="some_valid_secret"`

I try to reference them in test.json file:
```
{
  "variables": {
    "aws_access_key":  "{{env `AWS_ACCESS_KEY`}}",
    "aws_secret_key": "{{env `AWS_SECRET_KEY`}}"
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us-east-1",
    "source_ami": "ami-b8b061d0",
    "instance_type": "t1.micro",
    "ssh_username": "ubuntu",
    "ami_name": "base_ami {{timestamp}}",
}
```

Calling `packer build test.json` works as expected on Mac OSX with this configuration, but fails on Ubuntu with the following error:
```
amazon-ebs output will be in this color.

==> amazon-ebs: Creating temporary keypair for this instance...
Build 'amazon-ebs' errored: Error creating temporary keypair: AWS was not able to validate the provided access credentials (AuthFailure)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error creating temporary keypair: AWS was not able to validate the provided access credentials (AuthFailure)

==> Builds finished but no artifacts were created.
```

However, if I replace the environment variables in test.json with the same text I exported, it works. So I can confirm that the credentials are valid, and that my permissions for that instance are working as expected. 

The last clue I have is that calling `packer inspect test.json` actually returns different output for each environment. 

In Mac OSX: 
```
Optional variables and their defaults:

  aws_access_key = {{env `AWS_ACCESS_KEY`}}
  aws_secret_key = {{env `AWS_SECRET_KEY`}}

Builders:

  amazon-ebs

Provisioners:

  shell
```

In Ubuntu:
```
Optional variables and their defaults:

  aws_access_key = {{{env `AWS_ACCESS_KEY`}} %!s(bool=false)}
  aws_secret_key = {{{env `AWS_SECRET_KEY`}} %!s(bool=false)}

Builders:

  amazon-ebs

Provisioners:

  shell
```

Anyone have an idea what's happening?

Thanks,
   Brian

**Comment by mitchellh** [comment]
This should be fixed in master. The entire template processing changed. I wonder if you may have built between merges while it was broken (unknowingly) momentarily?
