### ISSUE TITLE
"CTRL" or "ALT" in boot_command?

### ISSUE THREAD

**Issue by Silex** [mitchellh/packer#2146]
Hello,

Is it possible to use keys like `Ctrl-Alt-F2` with boot_command?

**Comment by dragon788** [comment]
You can send literal keypresses with arrow braces eg. <esc>, but I don't know that simultaneous keypresses work properly in this mode since it is done over VNC.

**Comment by tamascsaba** [comment]
This issue is similar: https://github.com/mitchellh/packer/issues/810

**Comment by michaeltlombardi** [comment]
Should this have been closed by #3767?

**Comment by Silex** [comment]
Looks like it. Thanks!
