### ISSUE TITLE
SSH cannot access guests with static IP

### ISSUE THREAD

**Issue by Silex** [mitchellh/packer#2147]
Hello,

I'm using the `virtualbox-iso` type and the ISO I install uses a static ip after reboot (`10.11.12.13`). I cannot change this.

The problem is that after having installed the OS, packer cannot find the SSH server because it didn't use virtualbox's DHCP.

Here is my current attempt (see the natpf1 rule in `vboxmanage`):

``` json
{
  "builders": [
    {
      "vm_name": "test",
      "type": "virtualbox-iso",
      "guest_os_type": "Ubuntu_64",
      "guest_additions_mode": "disable",
      "disk_size": 20000,
      "headless": true,
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
        [ "modifyvm", "{{.Name}}", "--natpf1", "delete", "packerssh" ],
        [ "modifyvm", "{{.Name}}", "--natpf1", "packerssh,tcp,0.0.0.0,2222,10.11.12.13,22" ]
      ],
      "iso_url": "test.iso",
      "iso_checksum": "xxxxxxxxxxxxxxxxxxx",
      "iso_checksum_type": "md5",
      "boot_command": "I<enter>",
      "boot_wait": "10s",
      "ssh_username": "root",
      "ssh_key_path": "ssh/passwordless-key",
      "ssh_host_port_min": 2222,
      "ssh_host_port_max": 2222,
      "ssh_wait_timeout": "600s",
      "shutdown_command": "shutdown -h now"
    }
  ]
}
```

Unfortunately it doesn't work :-( Any workaround? Maybe bridged mode?

**Comment by Silex** [comment]
Hooray I found a fix :heart_eyes: :

``` json
{
  "builders": [
    {
      "vm_name": "test",
      "type": "virtualbox-iso",
      "guest_os_type": "Ubuntu_64",
      "guest_additions_mode": "disable",
      "disk_size": 20000,
      "headless": true,
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
        [ "modifyvm", "{{.Name}}", "--natnet1", "10.11.12/24" ],
        [ "modifyvm", "{{.Name}}", "--natpf1", "delete", "packerssh" ],
        [ "modifyvm", "{{.Name}}", "--natpf1", "packerssh,tcp,0.0.0.0,2222,10.11.12.13,22" ]
      ],
      "iso_url": "test.iso",
      "iso_checksum": "xxxxxxxxxxxxxxxxxxx",
      "iso_checksum_type": "md5",
      "boot_command": "I<enter>",
      "boot_wait": "10s",
      "ssh_username": "root",
      "ssh_key_path": "ssh/passwordless-key",
      "ssh_host_port_min": 2222,
      "ssh_host_port_max": 2222,
      "ssh_wait_timeout": "600s",
      "shutdown_command": "shutdown -h now"
    }
  ]
}
```

Now the problem is that it requires me to use `ssh_host_port_min/max` which is not very convenient.

**Comment by Silex** [comment]
Is there a way to access `sshHostPort` from within the template?

**Comment by mitchellh** [comment]
Yay! @Silex There isn't, just force the port to a single...

**Comment by Silex** [comment]
@mitchellh: that is a bit annoying, because now the packer builder has to manage ports as well (I want to parallelize builds, so I need to find the next unused port). I tried to find a way to *modify* natpf rules in VirtualBox but couldn't, do you happen to know of a way? It seems we can only delete & set them again, for which I'd need to know what `sshHostPort` packer decided to use.

Is there a way to execute shell commands before the VM start? That'd allow me to make a script that rewrites the `natpf` by querying for the rule first and thus using the correct port.

**Comment by Silex** [comment]
@mitchellh: is there a way to execute shell commands right before the VM start? That'd allow to make a script that rewrites the natpf by querying for the rule first and thus using the correct port.

It'd also allow for much more customizations.

**Comment by mrjcleaver** [comment]
For the interested:
 $ json-diff 1.json 2.json 
 {
   builders: [
     {
       vboxmanage: [
         ...
 +        [
 +          "modifyvm" 
 +          "{{.Name}}"
 +          "--natnet1" 
 +          "10.11.12/24" 
 +        ]
         ...
         ...
       ]
     }
   ]
  }
