### ISSUE TITLE
Add image size to OpenStack builder

### ISSUE THREAD

**Issue by m1keil** [mitchellh/packer#2154]
I do realize that the OpenStack builder is in some sort of limbo state, but when you do have the time, it would be really great if image-size config could be added to it.
Currently OpenStack images are 25GB by default which is a bit too big (or small) when compressed in RAW format.

**Comment by trumant** [comment]
@m1keil - Can you point me to the relevant OpenStack API doc for nova or glance API where this config is explained? I can't seem to find any reference to it.

**Comment by m1keil** [comment]
@trumant - sure, I think [this](http://developer.openstack.org/api-ref-compute-v2.html#createServer) is a good reference. See the `block_device_mapping` part.
I think gophercloud [got it integrated](https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/extensions/bootfromvolume/requests.go) in their API already

**Comment by trumant** [comment]
Thanks @m1keil Hopefully I'll have time this week to attempt to add this feature.

**Comment by m1keil** [comment]
Sure, no worries.
Here's the command line I finally made it work:
```nova boot --flavor m3.tiny --security-groups default --key-name test --block-device source=image,dest=volume,id=<image_id>,bootindex=0,device=vda,size=<size_in_gb> <instance_name>```

I found some info [here](https://wiki.openstack.org/wiki/BlockDeviceConfig) as well.

**Comment by mitchellh** [comment]
@trumant With the latest OpenStack merge, adding this should be pretty easy. Here is the API you'd need to use: https://github.com/rackspace/gophercloud/blob/fab1f3d270f58c199398e892c2c9c234fe2147d8/openstack/compute/v2/extensions/bootfromvolume/requests.go

**Comment by mitchellh** [comment]
@trumant Also, take a look at the latest OpenStack code for some good examples, it has gotten MUCH easier due to using the official lib now.

**Comment by nilsivbar** [comment]
Implemented  bootfromvolume extension on local repo but ran into another bug when using block device volumes. Just for info if someone else reads this and want try an implementation.
https://bugs.launchpad.net/mos/+bug/1666450

If we used destinationtype local the volumesize was always ignored and set to 40GB which was the problem which we wanted to get around from the beginning.
