### ISSUE TITLE
Vagrant post-processor on Windows does not honor {{}} completion in vagrantfile_template

### ISSUE THREAD

**Issue by gildas** [mitchellh/packer#2162]
My packer config generates its vagrant box like this:
```json
    {
      "type":                "vagrant",
      "keep_input_artifact": false,
      "compression_level":   1,
      "vagrantfile_template": "templates/{{user `template`}/vagrantfile.template",
      "output": "./boxes/{{user `template`}}/{{.Provider}}/{{user `template`}}-{{user `version`}}.box"
    }
```

When I run packer on Linux and OS/X, alles klar Kommissar.
But, if I run packer on Windows with the same config, I get this:

```sh
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: open templates/{{user `template`}}/vagrantfile.template: The system cannot find the path specified.
...
==> Builds finished but no artifacts were created.
```

If I enter the actual path manually, packer on Windows is happy.

Unfortunately, I don't see any easy in-packer-config workaround as we can only use "only", "override", "except" with builders but not OS.

So, either I will have to use 2 different packer config files and choose the proper one in my Rakefile or I give up on {{ }} and use ERB (e.g.).
Unless this can be fixed, of course. :wink:

**Comment by sethvargo** [comment]
Hi @gildas 

Thank you for opening an issue. We recently refactored a bunch of core to support interpolation. Can you please give master a try?

**Comment by mitchellh** [comment]
This should be fixed on master. :)
