### ISSUE TITLE
Packer push creates weird archive on Windows

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2165]
When `packer push` is performed on Windows the file paths inside the archive use the Windows path separator, e.g. `scripts\install.sh`. This `\` becomes part of the **filename** rather than being used as a path separator. When `packer build` in Atlas tries to read the file, it's missing because it's not in the correct path.

I think this is actually a bug in [hashicorp/atlas-go/archive](https://github.com/hashicorp/atlas-go/tree/master/archive), so I'll look into fixing it there.

Some workarounds in the mean time:

1. Change paths in your packer template to `\\` if everyone running `packer push` is going to use Windows
2. Run `packer push` only from an OS with similar path separators to those used in your template
3. Use a flat file structure in your packer project (e.g. don't use subfolders)

**Comment by mitchellh** [comment]
I agree that this is a bug in our archive library. I'm guessing Windows does fine with turning `/` into `\` so we should just do a basic string replace on the entry names.

**Comment by cbednarski** [comment]
This issue should be resolved by https://github.com/hashicorp/atlas-go/issues/38

/cc @mitchellh @catsby
