### ISSUE TITLE
use docker-push post processor when running qemu-builder

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#2186]
I have very specific use-case - create from the bottom docker image using distributive iso image.
So i have already worked qemu builder that creates vm image.
I can able to run in provisioning tar command and create filesystem archive, also i have ability to copy from vm this image to host system.

How the best deploy this image to docker? As i understand docker-import and docker-push only work in case of docker builder.

**Comment by vtolstov** [comment]
Now i create post processor that have ability to modify builderid of artifact =)

**Comment by mitchellh** [comment]
You can modify the docker-push post-processor to allow qemu builds if it is able to make valid docker images. I'd be happy to accept that PR.

**Comment by vtolstov** [comment]
@mitchellh so please merge this - #1909
downloading files very needed feature for various needs =)

**Comment by vtolstov** [comment]
I'm happy to add pr to docker-push/import post processors.
