### ISSUE TITLE
Support docker image metadata (volumes, ports, labels, etc) and layers

### ISSUE THREAD

**Issue by kapilt** [mitchellh/packer#2193]
Without its not clear why one would use packer for docker since it leaves so many core features on the floor.

**Comment by mitchellh** [comment]
Good call, tagged.

**Comment by nhuisman** [comment]
I'd love to see at least a way to preserve previous layers that were inherited from a base image.

**Comment by cornfeedhobo** [comment]
is there any hope of this getting merged soon?

**Comment by davidkarlsen** [comment]
+1

**Comment by bechtoldt** [comment]
+1

**Comment by cornfeedhobo** [comment]
For anyone watching, I made an updated Dockerfile handler as a work around.

https://github.com/cornfeedhobo/packer-post-processor-docker-dockerfile

**Comment by rickard-von-essen** [comment]
Support for this was just added in #4202
