### ISSUE TITLE
Use chroots/cgroups onto rootfs mount instead of booting

### ISSUE THREAD

**Issue by kapilt** [mitchellh/packer#2194]
There's a significant amount of garbage on the rootfs otherwise (logs, ssh|d keys, cloudinit state) that reflects the build environment.

**Comment by mitchellh** [comment]
Are you talking about the Amazon chroot builder? I'd be happy to field this in a PR, but don't have any plans on doing this in the short term.

**Comment by kapilt** [comment]
fair enough, its a bit different then what packer currently does. if you look at distro images, their clean, never booted, so no leftovers files and state from buildtime or buildenv. typically done via bootstrapping the image on a qemu nbd or loopback device, the same technique could be used for most of the provisioners, and then using qemu-convert for vhd, qcow2, raw, etc.
