### ISSUE TITLE
Can't create volume from snapshot for HVM EBS source AMI

### ISSUE THREAD

**Issue by Soliah** [mitchellh/packer#2195]
Trying to build an AMI using the Ubuntu AMI [ami-3f176c05](https://console.aws.amazon.com/ec2/home?region=ap-southeast-2#launchAmi=ami-3f176c05) as the source. However when trying to attach a volume created from a snapshot I get the following error:

```
Build 'amazon-ebs' errored: Error launching source instance: InvalidParameterCombination: The parameter iops is not supported for standard volumes.
        status code: 400, request id: []
```

As far as I can tell this should be supported? It works for a PV EBS source AMI, and if I remove the ` "launch_block_device_mappings"` key it works fine.

Main builder config is:

```
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "ap-southeast-2",
      "source_ami": "ami-3f176c05",
      "instance_type": "t2.medium",
      "ssh_username": "ubuntu",
      "ami_name": "OpenVPN Ubuntu 14.04 LTS {{isotime | clean_ami_name}}",
      "ami_description": "OpenVPN Ubuntu 14.04 AMI",
      "iam_instance_profile": "...",
      "vpc_id": "...",
      "subnet_id": "...",
      "associate_public_ip_address": true,
      "launch_block_device_mappings": [{
        "device_name": "/dev/xvdf",
        "snapshot_id": "...",
        "delete_on_termination": true,
        "volume_type": "standard"
      }]
    }
  ]
```

I'm using packer compiled from source @ edf3415 as I needed some fixes.

**Comment by catsby** [comment]
Hey @Soliah can you checkout #2197? It should address this issue
