### ISSUE TITLE
Convert vmware_ish to vmware_desktop

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2203]
There are a few other types of `vmware_*` identifiers in the wild, like `vmware_fusion` and `vmware_workstation`. These should all just be `vmware_desktop`.

This shows up in a few places like Vagrant and Atlas, but we can also fix it in Packer by rewriting these values to `vmware_desktop` whenever we build an image.

/cc @mitchellh Any objections to this?

**Comment by mitchellh** [comment]
No objections.

**Comment by mitchellh** [comment]
Although, I don't think Packer ever sees this value anywhere? It writes out `vmware_desktop` for the Vagrant post-processor.

**Comment by cbednarski** [comment]
Ahh so this is just an Atlasism?

**Comment by sethvargo** [comment]
I think `vagrant package` writes out different types maybe, or used to. It used to be different.

**Comment by mitchellh** [comment]
@cbednarski I don't think Atlas even writes them out, so much as just mirroring what was uploaded. I've spent years trying to track these down. :) HAHA.

**Comment by mitchellh** [comment]
(Goign to close this, I don't think its in Packer, but please prove me wrong)
