### ISSUE TITLE
Packer script interrupted during run

### ISSUE THREAD

**Issue by jerryely** [mitchellh/packer#2213]
when I use packer to create virtualbox virtual machines using shell provisioner, I have problems where scripts are interrupted in the middle of the run and the next script in the list is started.
I have created a gist "Packer script interrupted during run " with the .json file, the packer debug output and a copy of the script that gets interrupted.

It is very repeatable but not to the 'second' in terms of timing. 

I have tried to solve this in the google group but cant find a problem in my configurations.
![oops](https://cloud.githubusercontent.com/assets/10730138/8113889/13cd3a22-103f-11e5-8bf5-7cd408295abd.png)

**Comment by mitchellh** [comment]
Did you forget to link the gist? :) Can you show me that?

**Comment by jerryely** [comment]
Sorry. New to gist. 
<script src="https://gist.github.com/jerryely/4bb8f7b5aad6b568e685.js"></script>

**Comment by mitchellh** [comment]
Can you please get clean log output? Raw text no formatting. There is a lot of HTML and it is effectively impossible to parse as-is. Thanks.

**Comment by jerryely** [comment]
I would like to withdraw the issue at this time as the problem may be originating from the current release of VirtualBox.
Regards,
Jerry

**Comment by jerryely** [comment]
I would like to withdraw the issue at this time as the problem may be originating from the current release of VirtualBox. 
The relevant bug is listed as https://www.virtualbox.org/ticket/13839.

Apparently the nic on the vm goes up and down which is not obvious from watching the build. If the nic drops during an ssh session running a script, the ssh reconnects and picks up with the next script even though there was one there that is either already running, or was killed when the connection dropped. 

In either case, the next script is started and the build is out of order.

I am testing the mentioned workaround for VB and seems to have improved the situation but to early to tell if completely resolved.

FYI
Jerry

**Comment by mitchellh** [comment]
Thanks,I think it is too!
