### ISSUE TITLE
packer push doesn't work when the repo contains a symlink

### ISSUE THREAD

**Issue by gposton** [mitchellh/packer#2215]
We use packer w/ salt to build AMIs and install our application on those AMIs (immutable infrastructure).

Our current setup has the application code living at the root of the github repo alongside the packer template and the salt modules.

In order to have salt install our application and still be able to have the app code at the root level of the repo, we create a symlink from /salt/salt-states/application/files/app to /src

packer push errors when trying to copy the resources to Atlas.

Our repo structure looks like this

    ├── README.md
    ├── Vagrantfile
    ├── packer.json
    ├── salt
    │   ├── config
    │   │   └── minion.cfg
    │   ├── salt-pillars
    │   │   └── Readme.md
    │   └── salt-states
    │       ├── application
    │       │   ├── files
    │       │   │   ├── employment_screening -> ../../../../src
    │       │   │   ├── salt_id_rsa
    │       │   │   ├── salt_id_rsa.pub
    │       │   │   └── ssh_config
    │       │   └── init.sls
    ├── src
        ├── lots_of_code.py
        ├── ...

Error:

    ➜  employment_screening git:(register_ami_with_atlas) ✗ packer push packer.json
    Error archiving: Failed copying file to archive: /Users/glennposton/src/employment_screening/salt/salt-        states/application/files/employment_screening

    ➜  employment_screening git:(register_ami_with_atlas) ✗ ls -l salt/salt-states/application/files
    total 32
    lrwxr-xr-x  1 glennposton  staff    15 May  8 15:14 employment_screening -> ../../../../src
    -rw-r--r--  1 glennposton  staff  1679 May  8 15:14 salt_id_rsa
    -rw-r--r--  1 glennposton  staff   381 May  8 15:14 salt_id_rsa.pub
    -rw-r--r--  1 glennposton  staff    65 May  8 15:14 ssh_config

**Comment by mitchellh** [comment]
This should be fixed in master if you update the upstream dependencies. It'll be fixed in 0.8.0. :)
