### ISSUE TITLE
Versions of deps

### ISSUE THREAD

**Issue by swills** [mitchellh/packer#2234]
With the docs on doing development, could you please provide the info on versions of deps used to build releases? This is often done using godeps or some other tool. Thanks!

**Comment by mitchellh** [comment]
Master.

We won't version until Go provides an official solution.

**Comment by swills** [comment]
Ok, but this leaves no way to rebuild a release reliably, which is too bad.

**Comment by mitchellh** [comment]
Correct, and it is. 

We adopted this in later projects but haven't had a release since then on Packer. We'll likely do the same with Packer, but we just haven't released yet.

**Comment by swills** [comment]
Ah, ok, thanks for the info. :)
