### ISSUE TITLE
Vagrant Post-Processor cannot find files to build box

### ISSUE THREAD

**Issue by sbarnden** [mitchellh/packer#2246]
Trying to work on issue #2219 I cannot produce the required box files. Issue #2219 looks to be due to a failure to delete the VDI file before making the box which in the latest build from master seems to be occuring correctly. However now the box files are not being created due to a cannot find file error:
![image](https://cloud.githubusercontent.com/assets/11027711/8155780/cc386650-1386-11e5-9b06-d3630cb3508e.png)

Trying to build from a recent sync to master (Commit: common: revert some changes from #2121 for Windows) as I cannot get Tag v0.7.5 to compile due to OAuth2 API changes.

Have confirmed objects are staged to the TempDir:
![image](https://cloud.githubusercontent.com/assets/11027711/8155865/91b6000e-1387-11e5-870e-f11dbc6c57b0.png)

It looks like the change in:
post-processor/vagrant: interpolation

Is not returning a valid output path. From the log:
2015/06/15 17:35:29 packer-post-processor-vagrant.exe: 2015/06/15 17:35:29 Turning dir into box: C:\Users\scobarn\AppData\Local\Temp\packer920763175 =>

No output path is given. Worked in v0.7.5 and this seems to be the only post-processing change since then. Will continue to try and debug tomorrow.

**Comment by sbarnden** [comment]
Issue is with the interpolate render function being passed the output variable as the raw string instead of performing the variable lookup.

In my build.json file:
	"variables": {
....
		"output": "C:\\PackerBuild\\oracle_6.6_developer.box",
....
	"post-processors": [
		{
			"type": "vagrant",
			"output": "{{user `output`}}",
....

From some debug logic placed in the Render function of the Interpolate package:
func Render(v string, ctx *Context) (string, error) {
        log.Printf("Rendering value %s",v)
        return (&I{Value: v}).Render(ctx)
}

Produced this log entry:
2015/06/16 13:23:55 packer-post-processor-vagrant.exe: 2015/06/16 13:23:55 Rendering value {{user `output`}}

Replacing the variable in my JSON file to specify the output in the post-processor block worked successfully:
....
	"post-processors": [
		{
			"type": "vagrant",
			"output": "oracle_6.6_developer.box",
....

2015/06/16 13:11:47 packer-post-processor-vagrant.exe: 2015/06/16 13:11:47 Rendering value oracle_6.6_developer.box

And the box file was created successfully.

**Comment by mitchellh** [comment]
This is fixed now
