### ISSUE TITLE
enhancement: packer 'get' for grabbing and using plugins

### ISSUE THREAD

**Issue by reppard** [mitchellh/packer#2249]
I'm not sure how much work would be involved but I think a feature similar to terraform's 'get' sub-command would be a great addition to packer for managing plugin dependencies.  Has this been discussed or planned for a future release?  Thanks for all the great work you guys do.

Reppard

**Comment by mitchellh** [comment]
I don't think this is necessary since plugins are just binaries that you put in the your pwd or Packer's directory. The install process is so simple I don't think this is useful.
