### ISSUE TITLE
Latest build fails due to SSH variable errors

### ISSUE THREAD

**Issue by sbarnden** [mitchellh/packer#2261]
Trying to build and run from latest master (commit 4258a4102933ecd3acfafd1389e129ebc4fb3d03) fails due to SSH key issue:

2015/06/16 13:57:32 Build 'virtualbox' prepare failure: 2 error(s) occurred:

* unknown configuration key: "ssh_password"
* unknown configuration key: "ssh_username"
2015/06/16 13:57:32 ui error: 2 error(s) occurred:

* unknown configuration key: "ssh_password"
* unknown configuration key: "ssh_username"

Removing those configurations from the JSON file results in:
2015/06/16 13:55:03 Build 'virtualbox' prepare failure: 1 error(s) occurred:

* An ssh_username must be specified
2015/06/16 13:55:03 ui error: 1 error(s) occurred:

* An ssh_username must be specified

Not sure what changes need to be made for the new method of configuring SSH?

**Comment by mitchellh** [comment]
You need to update dependencies

**Comment by sbarnden** [comment]
Ran:
[developer@localhost packer]$ make updatedeps
go get -d -v -p 2 ./...

Before performing the build. Tried again with checking out master and running make updatedeps again.

Same result. Do I need to delete the whole repository and start from scratch? Not sure why make updatedeps is not working correctly.

Performing make also raises errors in various builder_test.go files although the binaries still compile Ok.

**Comment by mitchellh** [comment]
Looks like you have an old version of master where `updatedeps` didn't work. We fixed it yesterday, could you pull and try again

**Comment by sbarnden** [comment]
Pulled latest master and updated mapstructure, now it is working. Thanks for the assistance.
