### ISSUE TITLE
New openstack client supports identity v3 (changelog)

### ISSUE THREAD

**Issue by einarf** [mitchellh/packer#2264]
You might want to add to the changelog that the new openstack client supports authentication with the identity v3 api (before only v2 was supported) because of the new gophercloud API. That is definitely a major feature worth mentioning.

I can verify that this works.

**Comment by mitchellh** [comment]
Will do! :)

**Comment by mitchellh** [comment]
Done

**Comment by einarf** [comment]
:thumbsup:
