### ISSUE TITLE
Packer crash with 0.7.5

### ISSUE THREAD

**Issue by johnthedebs** [mitchellh/packer#2274]
Ran Packer via a script that accidentally inserted an extra arg, so that it was run effectively like this: `packer "" validate template.json`

Here's the crash output: https://gist.github.com/johnthedebs/1ed7dd82057881502912

**Comment by sethvargo** [comment]
I just confirmed this is still an issue (even on the latest master). Thank you for reporting!

**Comment by mitchellh** [comment]
Fixed: https://github.com/mitchellh/cli/commit/8102d0ed5ea2709ade1243798785888175f6e415

(run `updatedeps` if you're building locally)
