### ISSUE TITLE
Proxy settings for Packer under Linux are CASE SENSITIVE

### ISSUE THREAD

**Issue by dragon788** [mitchellh/packer#2275]
I tried to use the following command to set the proxy for Packer to use, it wasn't honoring it. 

```export http_proxy='http://myproxyname:3128'; export https_proxy=$http_proxy```

So I made a second attempt with ALL CAPS, and it worked. 

```export HTTP_PROXY=$http_proxy; export HTTPS_PROXY=$http_proxy```

This is really annoying as it requires a lot of trial and error and at first made me think somehow proxy support wasn't present.

**Comment by dragon788** [comment]
I found that Packer does support proxy via this, https://github.com/mitchellh/packer/issues/252

**Comment by cbednarski** [comment]
Linux and OS X environment variables are always case sensitive (maybe not on Windows?), but the de-facto standard is to use `ALL_CAPS` always. It seems like http_proxy may be some weird exception to this?

The env lookup is from go's std lib http://golang.org/pkg/net/http/#ProxyFromEnvironment.

I don't use proxy settings so I don't know exactly what the right thing to do here is. @dragon788 Do you see this as an application bug or a documentation problem?

**Comment by dragon788** [comment]
Possibly both, I think Packer should sanely handle any text that matches
HTTP_proxy and upper or lowercase it as appropriate, but noting in the
documentation the proper format by default is upper case would be helpful
as well, it was only by chance that I tried switching the case to see if it
was something as silly as that.

**Comment by cbednarski** [comment]
Hm.. looks like the go implementation actually looks for both upper and lowercase env variables:

http://golang.org/src/net/http/transport.go?s=4805:4862#L292

Not sure why this isn't getting picked up.

**Comment by cbednarski** [comment]
@dragon788 I'm wondering whether some calls in packer have proxy support while others do not. Do you have a log from a failed run I can reference?

**Comment by dragon788** [comment]
I'll see if I can get it tomorrow. I will admit I'm using the packer
windows plugins to get WinRM support before it gets merged properly, so it
could be a bug in their fetching support and not core packer functionality.
It might be a bug to track pending on the merge.

**Comment by mitchellh** [comment]
@cbednarski Historical trivia: This issue has always been a pain to make work 100% since each API client for things treats proxies differently. Some do it automatically, some require you to make a custom HTTP client, etc. I think there isn't much better we can do then adding them one at a time as we go.

**Comment by mitchellh** [comment]
@dragon788 Can you help also let us know which builder this was?

**Comment by dragon788** [comment]
I was trying to build with packer-windows-virtualbox-iso when I got the
error.

**Comment by mitchellh** [comment]
Ah, it was during the download of a ISO? This should be fixed in master, that uses the API linked by @cbednarski which is in the Go stdlib and checks for lower and uppercase (but not mixed).
