### ISSUE TITLE
doc'd datatype for puppet-server facter is confusing

### ISSUE THREAD

**Issue by mohae** [mitchellh/packer#2277]
Sorry, I already submitted a pull request without first creating an issue. This issue is for https://github.com/mitchellh/packer/pull/2276.

The docs for puppet server currently show the datatype for facter to be `hash`, which I found confusing as it should be `object of key/value strings`, I think.

I also found the documentation for facter in the puppet masterless provisioner to be inconsistent with how I see it in the documentation for other Packer components that use objects of key/value strings.

The proposed fix is to use `object of key/value strings` as the datatype for facter in both the Puppet server and Puppet masterless provisioners.

**Comment by cbednarski** [comment]
This has been merged. Thanks!
