### ISSUE TITLE
iso_url Path validity check failure

### ISSUE THREAD

**Issue by onaclov2000** [mitchellh/packer#2279]
When entering a file:// path (I think it's supposed to be file:/// with 3 slashes) packer crashes.

I assume that packer should do a "path exists" check then if it doesn't probably kick up an error message and exit without crashing. (I assume).

Please see the gist here:
https://gist.github.com/onaclov2000/cbef7a88680d616f4b16

For sanity sake, once I add that missing / in, it starts to work fine (well the md5 is wrong, and other issues, but it doesn't crash, and fails as expected :))

**Comment by cbednarski** [comment]
@onaclov2000 Thanks for the report!

@pearkes reported a similar-looking crash today too. I'm going to use this issue to track both.

**Comment by pearkes** [comment]
@cbednarski Just for completeness here's the log from the other:

https://gist.github.com/pearkes/d99913f0895e8881fd11

Looks like that's a bug for waiting for SSH, so probably different.

**Comment by mitchellh** [comment]
@pearkes I just pushed a fix for that crash.

**Comment by mitchellh** [comment]
I fixed this issue in here: https://github.com/mitchellh/packer/commit/897888fde3d12d9ea627a423714f4296c49826db

I went ahead and fixed it since i"ve been working off and on on acceptance tests for this for awhile so I'm pretty familir with the code, and its an edge case as it is.

**Comment by onaclov2000** [comment]
Thanks folks, really liking packer
