### ISSUE TITLE
Can't use PrivateKeyFile on AWS without providing a KeyPairName

### ISSUE THREAD

**Issue by ColinHebert** [mitchellh/packer#2281]
It seems that the recent changes in the way the KeyPair is managed in Packer for AWS broke the use of a private key file that doesn't rely on a key pair existing in AWS

In particular we can see that now, a key pair name is always set (whether it's needed or not)
https://github.com/mitchellh/packer/blob/master/builder/amazon/common/run_config.go#L42

Followed by assumptions about the key pair not being set (which is now impossible) has an impact on the configuration:
https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_key_pair.go#L25

Now, building an image with packer providing only the private key file results in messages such as

> 1434669095,amazon-ebs,error,Error launching source instance: InvalidKeyPair.NotFound: The key pair 'packer 55834f31-2f68-7b3f-c518-86fb895e55eb' does not exist\n        status code: 400%!(PACKER_COMMA) request id: []

The key doesn't exist obviously (because it isn't needed).

**Comment by ColinHebert** [comment]
CC @nyetsche @yosssi who worked on the new settings.

**Comment by mitchellh** [comment]
Thanks for the report. I think we had a couple PRs that we merged that caused this issue and we'll fix it ASAP.

**Comment by mitchellh** [comment]
This should be all fixed up. There was a weird interaction. Verified with acceptance tests. Thanks!
