### ISSUE TITLE
launch_block_device_mappings complaining about encryption flag

### ISSUE THREAD

**Issue by Soliah** [mitchellh/packer#2285]
So I'm trying to reproduce this, using the an Ubuntu Cloud AMI [ami-cf047ff5](https://console.aws.amazon.com/ec2/home?region=ap-southeast-2#launchAmi=ami-cf047ff5)

```
aws ec2 run-instances \
  --instance-type t2.medium
  --subnet-id ... \
  --key-name ... \
  --image-id ami-cf047ff5 
  --block-device-mappings "[{\"DeviceName\": \"/dev/sda1\",\"Ebs\":{\"VolumeSize\":64,\"DeleteOnTermination\":true}}]"
```

This works fine and the root volume get's set to 64GB:

```
ubuntu@ip-10-0-3-242:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       63G  790M   60G   2% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            492M   12K  492M   1% /dev
tmpfs           100M  324K   99M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            497M     0  497M   0% /run/shm
none            100M     0  100M   0% /run/user
```

Trying to do this in packer with the same base AMI fails with the following:

```
==> amazon-ebs: Error launching source instance: InvalidBlockDeviceMapping: the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified.
==> amazon-ebs:         status code: 400, request id: []
```

```
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "ap-southeast-2",
      "source_ami": "ami-cf047ff5",
      "instance_type": "t2.medium",
      "ssh_username": "ubuntu",
      "ami_name": "...",
      "ami_description": "...",
      "iam_instance_profile": "...",
      "vpc_id": "...",
      "subnet_id": "...",
      "associate_public_ip_address": true,
      "launch_block_device_mappings": [{
        "device_name": "/dev/sda1",
        "volume_size": 64,
        "delete_on_termination": true
      }]
    }
  ],
```

I'm using Packer v0.8.0.dev (f41429b6b43c0740732e32805f4f7fd91d08e46e)

**Comment by catsby** [comment]
Hey @Soliah – I hit this last week and I just merged a related PR that may fix this, the change is here:

- https://github.com/mitchellh/packer/commit/c9714ce69e5a68ef673b2455909cfee4070cc4e3#diff-39e61ef1894bbf830fdb06f9678c97baR45

Can you rebuild from `master` (at least 42000dd) and try again, and let me know if you're still hitting this?

**Comment by willmcg** [comment]
I was hitting this problem with my builds as well and can verify that failure complaining about encryption flags and snapshot IDs has been resolved by this change. Thanks!

I've hit another problem further down the line near the end of the build when packer starts the AMI creation step when I have defined an ami_block_device_mapping[] with entries for /dev/sda1 (root) and /dev/sdf. I get the following failure:

    ==> amazon-ebs: Error creating AMI: InvalidBlockDeviceMapping: /dev/sdf is being assigned to multiple times.
    ==> amazon-ebs: 	status code: 400, request id: []

I'll create a new issue for this problem,

**Comment by Soliah** [comment]
Can also confirm this fixed the issue for me. Thanks!

**Comment by catsby** [comment]
Thanks for confirming!

**Comment by catsby** [comment]
@willmcg if you're still hitting that, let me know. An example config (clean of any secrets) will help too!
