### ISSUE TITLE
Shell provisioner script file remove breaks reboot tolerance during a build.

### ISSUE THREAD

**Issue by willmcg** [mitchellh/packer#2286]
After updating to latest HEAD @ f41429b, the use case where I have a shell provisioner script that does a reboot in the middle of a sequence of other scripts has broken. The reboot is performed by a simple standalone script reboot.sh that just does this (as per recommendations):

    reboot
    sleep 60

The behavior I see is that once the instance starts reboot and the SSH session is terminated (about 15 seconds after reboot start), packer resumes execution but errors out and dies because it tries to use SSH again to delete the temporary script as added by this change:

commit 5d38ee939b41796837a77e507e8874ac57036294
    Merge pull request #2259 from mitchellh/b-shell-delete
    provisioner/shell: remove file after exec [GH-1536]

The problem in this case is that the deletion code is not wrapped with the same retry logic as the code that executes the script and so when it fails to establish an SSH connection to the instance it aborts the entire build. In this case, there is no way the delete code will be able to establish a session as the instance is in the middle of a reboot so the entire build is aborted with output like this:

    packer-provisioner-shell: 2015/06/21 17:51:47 [INFO] RPC client: Communicator ended with: 0
    packer-builder-amazon-ebs: 2015/06/21 17:51:47 opening new ssh session
    packer-builder-amazon-ebs: 2015/06/21 17:51:47 ssh session open error: 'use of closed network connection', attempting reconnect
    packer-builder-amazon-ebs: 2015/06/21 17:51:47 reconnecting to TCP connection for SSH
    packer-builder-amazon-ebs: 2015/06/21 17:52:02 reconnection error: dial tcp 54.85.207.161:22: i/o timeout
    ui: ==> amazon-ebs: Terminating the source AWS instance...
    [INFO ] ==> amazon-ebs: Terminating the source AWS instance...
    packer-builder-amazon-ebs: 2015/06/21 17:52:03 Waiting for state to become: terminated
    packer-builder-amazon-ebs: 2015/06/21 17:52:03 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
    ui: ==> amazon-ebs: Deleting temporary security group...
    [INFO ] ==> amazon-ebs: Deleting temporary security group...
    ui: ==> amazon-ebs: Deleting temporary keypair...
    [INFO ] ==> amazon-ebs: Deleting temporary keypair...
    ui error: Build 'amazon-ebs' errored: Error removing temporary script at /tmp/script_7943.sh: dial tcp 54.85.207.161:22: i/o timeout
    Builds completed. Waiting on interrupt barrier...

Prior to this script delete code being added, the next shell provisioner script would run and just sit in the retry loop until it could establish a new SSH session when the instance finishes its reboot and we get the expected reboot-tolerant behavior. Now the delete code introduces a new failure point that cannot handle a non-contactable instance.

I believe the delete code either needs to wait for the instance to reboot with the same kind of retry logic or simply be tolerant of the case where it cannot establish an SSH session and allow the build to continue.

To check my theory I commented out the new script delete and now my builds again work and correctly wait for the instance to reboot between shell provisioner steps.

**Comment by mitchellh** [comment]
Good catch, I think we need to wrap it in a retry!

**Comment by willmcg** [comment]
I can verify that this fix now works on my build that we previously broken. Thanks!
