### ISSUE TITLE
Snappy build

### ISSUE THREAD

**Issue by onaclov2000** [mitchellh/packer#2290]
I have been fiddling a bit, but can't seem to find a way to build a Snappy Ubuntu OS Image. Is this an option at some point, has someone done this?

(I downloaded the .img.xz, unzipped to .img, and then at the suggestion if the internets, renamed to ISO, i ran md5sum and setup a .json, but no luck, it gives me a variaty of failures and I assume that means that it's having issues with it not being an ISO, I also tried renaming to .img again and re-running).

The first error is shown below:

==> snappy 1435012922: Error attaching ISO: VBoxManage error: VBoxManage.exe: er
ror: Could not get the storage format of the medium 'C:\Users\me\ubuntu-15.
04-snappy-amd64-generic.img' (VERR_NOT_SUPPORTED)

**Comment by mitchellh** [comment]
VirtualBox only supports ISO
