### ISSUE TITLE
Starting from a disk image, rather than an ISO

### ISSUE THREAD

**Issue by marcosscriven** [mitchellh/packer#2293]
At the moment, I have a handcrafted script [here](https://github.com/marcosscriven/vagrant-openwrt/blob/master/build.sh) that downloads and unpacks a raw disk image, converts it to a VirtualBox VDI, and creates a VM for Vagrant.

However, rather than manually trying to patch the image with configuration (which is fragile and version-specific), I'd rather just attach a vanilla image to a VM and run an automated session. Unfortunately there's no equivalent wrapping of the ```keyboardputscancode``` function in Vagrant, and repeating the work of Packer's ```boot_command``` seems pointless. Without that, there's no automatic way to get ssh setup on the VM.

I can almost achieve this in Packer at the moment just through additional config in the builder:

```
      "vboxmanage": [
          ["convertfromraw", "openwrt.img", "openwrt.vdi"],
          ["storageattach", "{{ .Name }}", "--storagectl", "SATA Controller", "--port", "0", "--type", "hdd", "--medium", "openwrt.vdi"],
          ["modifyvm", "{{ .Name }}", "--boot1", "disk"]
      ],
```

Of course there's two problems with that:

1. I had to download and unpack the raw image myself (obviously I can do that with a bash script, but it would be nice to not to have to).
2. I had to just specify a valid ISO anyway, even though I'm not using it.

I've been browsing the Packer VirtualBox builder code, and it seems this would be almost identical to the ISO builder. There's three things we'd need:

1. We could still use the iso download functionality, but we'd need automatic unpacking. This has already been raised in #463 
2. Use ```convertfromraw``` to convert the image to a VDI.
3. Make the ```--type``` argument here configurable https://github.com/mitchellh/packer/blob/master/builder/virtualbox/iso/step_attach_iso.go#L41 

Of course, it wouldn't then be an ```iso``` builder per se, but an ```image``` builder. It would seem a shame to have to have an entirely separate builder for this, but by the same token overloading the ```iso_``` options might be confusing too.

I guess we could go a step further and just have a builder bootable from anything - anything that can be attached with the ```storageattach``` function, with an optional ```convertfromraw``` beforehand.

I'm happy to PR, but obviously it would require some discussion first on where this functionality would go (separate builder, iso builder with overloaded config, iso build changed to a generic image builder), and how we should expose this in config.

**Comment by marcosscriven** [comment]
The more I think about it, the more I think it would be better to deprecate the separate ```iso``` and ```ovf``` builders (keeping them around for however long you deem appropriate), and go back to a single VirtualBox builder that:

1) Optionally starts from an existing VM (from an ovf, ova, or even .vbox per #869)
2) Specify a list of URLs that specify images/isos/floppys to attach, which are automatically unpacked and converted to VDIs if necessary. If you've imported from a VM rather than from scratch, you'd could optionally specify one of them to boot from)
3) Choose the output format (with the same options as input)

It seems that in the code the only real difference between the builders is that the ```ovf``` one imports a VM, whereas the ```iso``` one has to setup a minimal one.

**Comment by mitchellh** [comment]
This sounds like a good idea. I'd stray away from merging the builders for now and rather just put the `img` code into the `iso` builder or `ovf` builder. I'm not exactly sure how this process works so I'd leave you to it. 

If you want to make a PR, I'd happily look!
