### ISSUE TITLE
REQUEST - Increase sleep time when waiting for AMI state 

### ISSUE THREAD

**Issue by johnleetran** [mitchellh/packer#2303]
We love packer, we use it for building our AMIs.  But we always have compile our own version of packer because of 1 line in the packer code.

https://github.com/mitchellh/packer/blob/master/builder/amazon/common/state.go#L136

Could you increase the sleep time to something like 10 seconds?  We are consistently getting throttling issues if we leave it as 2.

**Comment by catsby** [comment]
Hey @johnleetran – at which part do you start to receive throttling issues, waiting for the AMI to become available? It should be easy enough to extend this wait time, but I'd like to make 2 seconds the default and then just extend this single operation, if possible.

**Comment by johnleetran** [comment]
Most of the time we get throttling errors at  

-waiting for AMI to become available
-waiting for ec2 instance to terminate/stop

It would be great if there is an option in the packer CLI in which you can specify the value of the wait time.

Thank you for following up, we love packer and has built our workflow around it

**Comment by mitchellh** [comment]
@johnleetran Is this in Packer 0.8? Our upstream API layer should be doing exponentional backoff on top of our sleep times in the case of throttling issues.

**Comment by johnleetran** [comment]
@mitchellh we are currently using Packer 0.7.  we are in the progress of upgrading to 0.8.  

The reason I made this request is because we were looking to use 0.8 and i got tired of manually compiling packer because of the trolling issue.  If this is fixed in 0.8, then fantastic.  Will try and let you know if any issues.

**Comment by mitchellh** [comment]
Ah, yes. I'm fairly confident 0.8 will fix this only because we use the same library as we do in Terraform and all these bug reports went away in Terraform when we switched to it. Please give it a shot!
