### ISSUE TITLE
Unexpected EOF in qemu builder causes crash in Packer 0.8.0

### ISSUE THREAD

**Issue by tylert** [mitchellh/packer#2311]
My template works fine with Packer 0.7.5 but crashes with 0.8.0.

https://github.com/tylert/packer-build/blob/master/debian/jessie/base-64.json

On Mac OS X 10.10.3, "packer validate" causes a crash (no qemu binary there to test further).  On Debian 8.1.0 for amd64, "packer validate" and "packer build -only=qemu" both cause the same crash.

```
Template validation failed. Errors are shown below.

Errors validating build 'qemu'. unexpected EOF


!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/mitchellh/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Contents of crash.log:
https://gist.github.com/tylert/8f6c157bf3d09c09cf9e

Please confirm this is not simply a "User Too Stupid Error".

**Comment by cbednarski** [comment]
@tylert A crash is definitely our bad. Thanks for the report! The crash log and template are really helpful.

**Comment by mitchellh** [comment]
Looks like the crash is actually coming from the compress post-processor. Retagging.
