### ISSUE TITLE
Cannot tag EC2 AMIs copied to other regions

### ISSUE THREAD

**Issue by rosstimson** [mitchellh/packer#2319]
Since upgrading to Packer 0.8.0 my template will no longer build EC2 AMIs as it fails to tag AMIs that are copied to other regions.

The `packer build` will return an error like so:

```
==> amazon-ebs: Pausing before cleanup of step 'StepPreValidate'. Press enter to continue.
Build 'amazon-ebs' errored: Error retrieving details for AMI (ami-ec5c67f1): InvalidAMIID.NotFound: The image id '[ami-ec5c67f1]' does not exist
	status code: 400, request id: []
 
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error retrieving details for AMI (ami-ec5c67f1): InvalidAMIID.NotFound: The image id '[ami-ec5c67f1]' does not exist
	status code: 400, request id: []
 
==> Builds finished but no artifacts were created.
```

However, I can double check the AMI does indeed exist with:

```
% aws --region=eu-central-1 ec2 describe-images --image-ids ami-ec5c67f1
{
    "Images": [
        {
            "VirtualizationType": "hvm",
            "Name": "test_tagging_2015-06-25T16-54-54Z",
            "Hypervisor": "xen",
            "SriovNetSupport": "simple",
            "ImageId": "ami-ec5c67f1",
```

I do the initial build in `eu-west-1` and copy to various regions.  The tagging error occurs at seemingly random regions but I can always manually verify that the AMI Packer claims doesn't exist is in one of the regions.  I can only assume Packer is now only checking for the AMI in my default region (`eu-west-1`).

I've created a gist (https://gist.github.com/rosstimson/b38019f514c12972988f) with a test Packer template to reproduce this issue (there is a sudoers script that is needed to bundle up Amazon Linux).  The gist also includes full `--debug` output from a failing `packer build` and output from manually checking the AMI exists, I hope this helps.

**Comment by catsby** [comment]
Hello – I believe this was fixed in https://github.com/mitchellh/packer/pull/2316, which was merged just a few hours ago. Are you able to build Packer and confirm for me? 

Otherwise, we'll have a v0.8.1 maintenance release in the coming week. Thanks!

**Comment by rosstimson** [comment]
@catsby You sir, are an absolute legend - this is indeed fixed now.  Many thanks and I look forward to a v0.8.1 release, a proper release rather than building from HEAD will help me out immensely.
