### ISSUE TITLE
manifest of installed packages

### ISSUE THREAD

**Issue by jdamick** [mitchellh/packer#2326]
I would like to be able to generate a manifest of the installed packages (rpm, deb, etc) on my image after the processors run but prior to creating the Artifact (ex. an AMI).

Where does this make the most sense? As a custom plugin processor that runs last?  Or an enhancement to packer itself?    

Since the processors can't enhance the artifact I can't really play off the same idea as atlas that adds metadata in the artifact State via "atlas.artifact.metadata"..  So I suppose I'd need to create 2 plugins..   thoughts?

**Comment by mitchellh** [comment]
You can do this as a provisioner, and then the `file` provisioner can download it.

Please ask usage questions on the mailing list.
