### ISSUE TITLE
No longer supporting softlayer?

### ISSUE THREAD

**Issue by ldanielw1** [mitchellh/packer#2334]
Hey guys,

I just upgraded packer to 0.8.0, and I realized the builder for softlayer is no longer present - would it be possible to reinstate softlayer support?

**Comment by cbednarski** [comment]
@ldanielw1 I don't know that we had a special softlayer builder in `v0.7.0`. Did you get a [third-party builder](https://github.com/leonidlm/packer-builder-softlayer)? Maybe you need a new version of this plugin?

**Comment by mitchellh** [comment]
Agreed, we've never shipped a plugin for softlayer, so this must've been some 3rd party thing.
