### ISSUE TITLE
Packer v0.8.0 - DigitalOcean build fails with private_networking option in config

### ISSUE THREAD

**Issue by ciarand** [mitchellh/packer#2339]
This is a non-working template file:

```json
{
  "variables": {
    "digitalocean_pat": "{{env `DIGITAL_OCEAN_API_TOKEN`}}"
  },
  "builders": [{
    "type": "digitalocean",
    "api_token": "{{user `digitalocean_pat`}}",
    "region": "sfo1",
    "size": "2gb",
    "image": "fedora-22-x64",
    "droplet_name": "whatever",
    "private_networking": true,
    "snapshot_name": "whatever--{{timestamp}}"
  }]
}
```

It fails with this message:

```
digitalocean output will be in this color.

==> digitalocean: Creating temporary ssh key for droplet...
==> digitalocean: Creating droplet...
==> digitalocean: Waiting for droplet to become active...
==> digitalocean: Waiting for SSH to become available...
==> digitalocean: Timeout waiting for SSH.
==> digitalocean: Destroying droplet...
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.
```

Checking the DO control panel indicates the droplet was created successfully AND responds to SSH requests from the Internet At Large™, but Packer seems to timeout.

The exact same config, but with no `private_networking` option works:

```json
{
  "variables": {
    "digitalocean_pat": "{{env `DIGITAL_OCEAN_API_TOKEN`}}"
  },
  "builders": [{
    "type": "digitalocean",
    "api_token": "{{user `digitalocean_pat`}}",
    "region": "sfo1",
    "size": "2gb",
    "image": "fedora-22-x64",
    "droplet_name": "whatever",
    "snapshot_name": "whatever--{{timestamp}}"
  }]
}
```

I tried with `private_networking` set to true and false, and the only way I could get it to stop timing out waiting for the SSH connection was by removing the option entirely. My understanding was that private networking on DO is an additional thing, and that it didn't preclude public networking. Am I wrong or is this a bug?

**Comment by cbednarski** [comment]
@ciarand Thanks for the bug report! I just tried this and it looks like packer is trying to connect to the droplet via the private IP rather than a public IP, which obviously won't work.

We will get this fixed soon but in the mean time you can build these without private networking enabled (and enable it later) or use packer v0.7.5. Sorry about the inconvenience!
