### ISSUE TITLE
"Unsupported protocol scheme" / openstack rackspace

### ISSUE THREAD

**Issue by L3on1d** [mitchellh/packer#2341]
Hi guys! I'm faced some problem with packer. Can't push template to atlas...I'm always getting "Unsupported protocol scheme", but can do "packer build" without problem and create image in my rackspace environment. Dunno what I'm doing wrong, seems problem in my template. Below my example...
![problem](https://cloud.githubusercontent.com/assets/11537656/8397806/d8f32dbc-1de0-11e5-9c5e-b4e4338e7ffc.JPG)

```json
{
  "variables": {
    "identity_endpoint": "{{env `OS_AUTH_URL`}}",
    "username": "{{env `OS_USERNAME`}}",
    "password" : "{{env `OS_PASSWORD`}}",
    "tenant_id" : "{{env `OS_TENANT_ID`}}",
    "region_name" : "{{env `OS_REGION_NAME`}}"
  },
  "builders": [{
    "type": "openstack",
    "openstack_provider": "rackspace-us",
    "username": "{{user `username`}}",
    "password" :"{{user `password`}}",
    "region": "{{user `region_name`}}",
    "tenant_id": "{{user `tenant_id`}}",
    "source_image": "93346217-ef91-4983-803e-2027891d1cdb",
    "flavor": "general1-1",
    "ssh_username": "root",
    "image_name": "Web test {{timestamp}}"
    }],
    "push": {
      "name": "My username/rackspace",
      "vcs": false
    },
    "provisioners": [
    {   
        "type": "shell",
        "inline": "apt-get update && apt-get -y install apache2"
    }],
    "post-processors": [
      {
        "type": "atlas",
        "artifact": "My username/rackspace",
        "artifact_type": "rackspace.debianweb",
        "metadata": {
         "created_at": "{{timestamp}}"
        }
      }
    ]
}
```

**Comment by L3on1d** [comment]
Solved. Removed variables and added parameters as plain text.

**Comment by mitchellh** [comment]
Ah, this is probably from the variables not being set in Atlas? I imagine there could be a lot better error message coming from the OpenStack API. If you feel inclined, please report an error there. We don't do Packer-side validation because OpenStack required auth params are pretty endpoint-specific.

**Comment by onaclov2000** [comment]
I am seeing a similar error, but have no variables, not sure how to work around it.

**Comment by cbednarski** [comment]
@onaclov2000 Please open a new issue.
