### ISSUE TITLE
Have to add env to execute_command in FreeBSD shell (tcsh)

### ISSUE THREAD

**Issue by ciarand** [mitchellh/packer#2343]
Hey, I don't even know if this should even be in the issues / docs - I just didn't see it in the issues when I searched and it caused me a little bit of trouble at first.

Packer fails on FreeBSD whenever it uses the shell provisioner and copies a shell script to the target machine because it uses the `KEY=VALUE cmd` format. [The default `execute_command`][default] is:
```
chmod +x {{.Path}}; {{.Vars}} {{.Path}}
```
Which turns out a command that looks like:
```
chmod +x mycmd; SOME_PACKER_VARIABLE=foo mycmd
```
This fails on FreeBSD because the default shell interprets `SOME_PACKER_VARIABLE=foo` as the (missing) command instead of `mycmd`. The working FreeBSD version looks like:
```
chmod +x {{.Path}}; env {{.Vars}} {{.Path}}
```

Tested with `Packer v0.8.0`, `FreeBSD v10.1` on DigitalOcean using the `shell` provisioner. You can test using [this config][fixed].

[fixed]: https://github.com/ciarand/red-shirt/blob/6be148784ba6d8eedb46563f65cd9eab414a330e/build.json#L17
[default]: https://github.com/mitchellh/packer/blob/v0.8.0/provisioner/shell/provisioner.go#L88-L90

**Comment by cbednarski** [comment]
@ciarand Thanks for the bug report. I suspect this may be because [FreeBSD's default shell is not `bash`](https://www.freebsd.org/doc/en_US.ISO8859-1/articles/linux-users/shells.html). Maybe we should call `sh` explicitly so we have a more consistent shell across *nix and BSD.

**Comment by cbednarski** [comment]
@ciarand I did some digging and there is not a great way to do this across shells, so I added an explicit FreeBSD example to the docs.

**Comment by ciarand** [comment]
That's perfect, thanks @cbednarski

**Comment by killua99** [comment]
Hi, Do you know why I'm having this message? 

virtualbox-iso: env: /tmp/script_7943.sh: No such file or directory

My template.json look like this.

    {
        "provisioners": [
            {
                "type": "shell",
                "execute_command": "chmod +x {{.Path}}; env {{.Vars}} {{.Path}}",
                "scripts": [
                    "{{template_dir}}/scripts/base.sh",
                    "{{template_dir}}/scripts/virtualbox.sh",
                    "{{template_dir}}/scripts/vmware.sh",
                    "{{template_dir}}/scripts/vagrant.sh",
                    "{{template_dir}}/scripts/puphpet.sh",
                    "{{template_dir}}/scripts/cleanup.sh",
                    "{{template_dir}}/scripts/zerodisk.sh"
                ]
            }
        ],
        "builders": [
            {
                "type": "virtualbox-iso",
                "boot_command": [
                    "<enter><wait>",
                    "<enter><wait>",
                    "{{ .Name }}<enter><wait>",
                    "<down><spacebar>",
                    "<down><spacebar>",
                    "<down><spacebar><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<wait10>",
                    "<wait10>",
                    "<wait10>",
                    "<wait10>",
                    "vagrant<enter><wait>",
                    "vagrant<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait10>",
                    "<right><enter><wait>",
                    "<enter><wait>",
                    "<right><enter><wait>",
                    "a<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "vagrant<enter><wait>",
                    "Vagrant User<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "wheel<enter><wait>",
                    "<enter><wait>",
                    "tcsh<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "<enter><wait>",
                    "vagrant<enter><wait>",
                    "vagrant<enter><wait>",
                    "<enter><wait>",
                    "yes<enter><wait>",
                    "no<enter><wait>",
                    "<enter><wait5>",
                    "<left><enter><wait>",
                    "sed -i -e 's/#PermitRootLogin no/PermitRootLogin yes/' /etc/ssh/sshd_config<enter><wait>",
                    "chsh -s sh root<enter><wait>",
                    "exit<enter><wait>",
                    "<enter>",
                    "<wait10>",
                    "<wait10>",
                    "<wait10>"
                ],
                "boot_wait": "35s",
                "disk_size": 20480,
                "guest_os_type": "FreeBSD_64",
                "http_directory": "http",
                "iso_checksum": "0c3d64ce48c3ef761761d0fea07e1935e296f8c045c249118bc91a7faf053a6b",
                "iso_checksum_type": "sha256",
                "iso_url": "http://ftp.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/10.1/FreeBSD-10.1-RELEASE-amd64-disc1.iso",
                "ssh_username": "root",
                "ssh_password": "vagrant",
                "ssh_port": 22,
                "ssh_wait_timeout": "10000s",
                "shutdown_command": "poweroff; poweroff",
                "vboxmanage": [
                    ["modifyvm", "{{.Name}}", "--memory", "2048"],
                    ["modifyvm", "{{.Name}}", "--cpus", "4"]
                ]
            }
        ],
        "post-processors": [
            {
              "type": "vagrant",
              "compression_level": 9
            }
        ]
    }

**Comment by ciarand** [comment]
@killua99 try rerunning with PACKER_LOG=1 for more verbose output. I used that to debug the issue when it occurred for me

**Comment by killua99** [comment]
I solve it, but with a full rewrite of the packer json.

You can take a look what I did there.

https://github.com/killua99/packer-templates/tree/freebsd-10.1-x86_64/freebsd-10.1-x86_64

The machine now assemble well without the puphpet.sh script.

Now, I'm trying to install puppet during the process, I'm working on the first steps to build a puphpet option and first I need to finish the packer recipe.
