### ISSUE TITLE
Error launching source instance: OptInRequired while following packer.io/intro/getting-started/build-image.html

### ISSUE THREAD

**Issue by grange74** [mitchellh/packer#2346]
While following the get started documentation on packer.io, i got  "Error launching source instance: OptInRequired" when building. It seems that the AMI in the example (ami-c65be9ae) is from the Amazon Marketplace and needs to have the Terms Accepted before it can be used. 

While it isn't that hard to go to the marketplace URL provided by the error message and then click continue and then click Manual Launch and then click Accept Terms button. Obviously it would be better not to see an error message the first time you run packer.

I tried 2 other AMI ids and they both worked fine without needing to accept terms (redis got installed and the new AMI created was able to be launched). 
From the Quick Start AMIs, ami-d85e75b0
From the Community AMIs, ami-de0d9eb7

The Community AMI is actually referenced in the main README.md so it seems logical to update packer.io/intro/getting-started/build-image.html to match this. 

I will create a PR for this.

Full packer (version 0.8.0) output with error:
```
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 559122e0-c47c-d4fc-9594-917c1eab3a6e
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit http://aws.amazon.com/marketplace/pp?sku=e0rcty0t3zp1mkin7a899fmgw
==> amazon-ebs: 	status code: 401, request id: []
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit http://aws.amazon.com/marketplace/pp?sku=e0rcty0t3zp1mkin7a899fmgw
	status code: 401, request id: []

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit http://aws.amazon.com/marketplace/pp?sku=e0rcty0t3zp1mkin7a899fmgw
	status code: 401, request id: []

==> Builds finished but no artifacts were created.
```

**Comment by mitchellh** [comment]
Thanks for the report and the PR. I think the error message here is actually quite good, so I'm going to leave it as-is, but the PR to avoid it in the first place was well appreciated. thanks!

**Comment by grange74** [comment]
I definitely agree that the error message is clear and should remain. 
I have also seen it in Terraform and it allowed me to quickly fix the problem.

**Comment by zubiks** [comment]
I am getting the appended errors below when initiating the "terraform apply plan"

Error applying plan:
1 error(s) occurred:

* aws_instance.example: Error launching source instance: OptInRequired: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe.
	status code: 401, request id: b51e7d7f-baf2-405b-b3c2-43b1e928cb28
It is  pretty obvious of what the error is pointing to but I assume it is an example which should be embedded in free tier subscription. Please advise - your help is highly appreciated

**Comment by grange74** [comment]
@zubiks while your message seems similar, i think it is a different problem. If you've just signed up for an AWS account then you may just need to wait 24hrs and retry as per https://forums.aws.amazon.com/thread.jspa?threadID=43708. 
If the problem continues then i'd recommend creating a new issue in the Terraform project.

**Comment by anmolnagpal** [comment]
@grange74 

Getting same error 

```

==> amazon-ebs: Prevalidating AMI Name...
    amazon-ebs: Found Image ID: ami-0f80e87c
==> amazon-ebs: Creating temporary keypair: packer_58abf68f-8b0f-4d06-3b03-7b9dc11058f8
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit http://aws.amazon.com/marketplace/pp?sku=bvwuiw5gzcrcpqtslqfaanxnt
==> amazon-ebs: 	status code: 401, request id: df69d531-7b14-497f-908a-bf6763279ceb
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit http://aws.amazon.com/marketplace/pp?sku=bvwuiw5gzcrcpqtslqfaanxnt
	status code: 401, request id: df69d531-7b14-497f-908a-bf6763279ceb
```

**Comment by grange74** [comment]
@anmolnagpal If you want to use that particular Ami (ami-0f80e87c) and many others you will have to accept the terms through the AWS marketplace. I don't believe it can be done automatically. If you want to do that then to the link (http://aws.amazon.com/marketplace/pp?sku=bvwuiw5gzcrcpqtslqfaanxnt) provided by the error message, click on the "Continue" button and then on accepted the terms(i.e. go to Manual Launch tab and then click on Accept Software Terms button). You only need to do this once per AMI.
If the problems persists i would recommend creating a new issue as this has been closed.

**Comment by pappavic** [comment]
@grange74 how did you find the AMI which does not require acceptance of terms?

**Comment by grange74** [comment]
Tbh i don't remember as it was 3 years ago. My only guess would that i looked at the "Launch Instance" dialog in the AWS web console and picked one of the AMIs in the Quick Start (or possibly even Community AMIs).
