### ISSUE TITLE
0.8.0 - EC2 ami_block_device_mappings not mapping ephemeral devices correctly.

### ISSUE THREAD

**Issue by aspring** [mitchellh/packer#2360]
Im currently running a local build based off (https://github.com/mitchellh/packer/commit/8657b1e9d81f147747122870032c81acb3bd663c) to test https://github.com/mitchellh/packer/pull/2320 and while 2320 looks good, there is an issue where the ephemeral block devices are not configured correctly.

In the 0.7.5 Block Device configuration that I would see as a result of the AMI building process would look something like this for the resulting image:
BLOCKDEVICEMAPPING	EBS	/dev/sda1		snap-c2a1718d	8	true	standard		Not Encrypted
BLOCKDEVICEMAPPING	EPHEMERAL	/dev/sdb	ephemeral0
BLOCKDEVICEMAPPING	EPHEMERAL	/dev/sdc	ephemeral1
BLOCKDEVICEMAPPING	EPHEMERAL	/dev/sdd	ephemeral2
BLOCKDEVICEMAPPING	EPHEMERAL	/dev/sde	ephemeral3

In the 0.8+ version I am seeing the following:
BLOCKDEVICEMAPPING	EBS	/dev/sda1		snap-2e113358	8	true	standard		Not Encrypted
BLOCKDEVICEMAPPING	EBS	/dev/sdb			0	false	standard		Not Encrypted
BLOCKDEVICEMAPPING	EBS	/dev/sdc			0	false	standard		Not Encrypted
BLOCKDEVICEMAPPING	EBS	/dev/sdd			0	false	standard		Not Encrypted
BLOCKDEVICEMAPPING	EBS	/dev/sde			0	false	standard		Not Encrypted

As best I can tell this line 
https://github.com/mitchellh/packer/blob/master/builder/amazon/common/block_device.go#L50 where setting EBS should be based off of the VirtualName being one of the ephemeral device names.  

I performed a local fix here(https://github.com/aspring/packer/commit/9db281ac0f8933fecb0db3b1f0e789944b055e3a), however, I am not entirely sure of its correctness.

WIth this fix in place, I see the following:
BLOCKDEVICEMAPPING	EBS	/dev/sda1		snap-1a210c69	8	true	standard		Not Encrypted
BLOCKDEVICEMAPPING	EPHEMERAL	/dev/sdb	ephemeral0
BLOCKDEVICEMAPPING	EPHEMERAL	/dev/sdc	ephemeral1
BLOCKDEVICEMAPPING	EPHEMERAL	/dev/sdd	ephemeral2
BLOCKDEVICEMAPPING	EPHEMERAL	/dev/sde	ephemeral3

**Comment by cbednarski** [comment]
@aspring Thanks for the report. I think we need some more tests around this feature to verify it's working as intended. If you want to PR your fix I can look into adding tests to it.

**Comment by aspring** [comment]
@cbednarski I have pushed the change as is without any tests, as while it works well for me, Im just not fluent enough in the AWS API to be totally confident in the change.

**Comment by cbednarski** [comment]
@aspring Thanks! I'm not super familiar with volumes myself so I'll need to do some reading. ;)
