### ISSUE TITLE
too many open files when running with 8 builders

### ISSUE THREAD

**Issue by ldanielw1** [mitchellh/packer#2361]
I noticed that there have been other issues regarding having too many files open. I wanted to follow up to ask - is there any way we can help expose where cleanup needs to happen? I have 8 builders, and I'm already running out of space for open files.

And if there isn't any way to have this many builders, would it be possible to have packer delay building some of the builders until some of the others have finished?

**Comment by mitchellh** [comment]
Hm, this problem should be mostly gone. We now only open a 1 TCP connection (over unix domain socket) per builder, and one per provisioner, and so on. Even with 8 builders, there should only be at most _dozens_ of file handles open. What builders are you running, and how many file handles are you seeing open? Can you list the open file handles?

**Comment by ldanielw1** [comment]
hm. One sample builder is this:
	"aws_builder_ap-southeast-1": {
		"name": "aws-ap-southeast-1",
		"type": "amazon-ebs",
		"access_key": "ACCESS_KEY",
		"secret_key": "SECRET_KEY",
		"region": "ap-southeast-1",
		"source_ami": "SOURCE_AMI",
		"instance_type": "m3.large",
		"ssh_username": "ec2-user",
		"ami_name": "AMI {{timestamp}}",
		"ssh_timeout": "15m"
	},

How can I see what file handles are open?

**Comment by mitchellh** [comment]
I'm actually not sure off the top of my head. Are you using the latest versin of Packer as well? This is an issue we just haven't heard of in many many releases (maybe over a year). We even benchmarked our file handles at some point with some REALLY large templates, and they were reasonable (in the hundreds, for something like 24 concurrent builds). 

Just google for your platform and try to find the open file handles, that would help.

**Comment by mitchellh** [comment]
Also, how many file handles are you talking about here? Is it low enough that you can simply up the file handles for your user?

**Comment by ldanielw1** [comment]
i'm on 0.8.0, mac. I'll get back to you soon on how many file handles are being used by my machine

**Comment by ldanielw1** [comment]
I'm only seeing 267 open files for packer... after I get the errors:

Failed to initialize build 'aws-sa-east-1': error initializing provisioner 'file': fork/exec /aspera/usr/builder/packer/mac/packer/packer-provisioner-file: too many open files

Failed to initialize build 'aws-us-west-1': error initializing builder 'amazon-ebs': fork/exec /aspera/usr/builder/packer/mac/packer/packer-builder-amazon-ebs: too many open files

Failed to initialize build 'aws-us-west-2': error initializing builder 'amazon-ebs': fork/exec /aspera/usr/builder/packer/mac/packer/packer-builder-amazon-ebs: too many open files


It's always these three regions that die, so I'm not sure what's going on...

**Comment by ldanielw1** [comment]
I have upgraded to 0.8.1 but the issue is still here. any tips?

**Comment by cbednarski** [comment]
@ldanielw1 267 open files seems perfectly reasonable. You can try increasing your file limits using ulimit, but this is specific to your computer / environment. An example o[n OSX](http://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard).

If you are using a mounted filesystem, shared volume, VM or other level of indirection you may run into more complications. Unfortunately we don't have the means to troubleshoot that type of thing.

**Comment by ldanielw1** [comment]
Ah. well I am on osX... but I am also on a mounted filesystem.

Perhaps you are unable to help troubleshoot, but do you have any tips or recommendations on what I can do...?
