### ISSUE TITLE
Option force seems to not being used when tagging docker images.

### ISSUE THREAD

**Issue by i0rek** [mitchellh/packer#2362]
This is what I get when I try to tag an image with an existing tag:

```
$ packer build -force template.json
* Post-processor failed: Error tagging image: exit status 1
Stderr: Error response from daemon: Conflict: Tag latest is already set to image a0e3da923c43e27477f0b9dd213fb508385294eb9067aab9e95e66e8fcae23a5, if you want to replace it, please use -f option
```

I started digging around, so far I didn't found the issue yet.

**Comment by mitchellh** [comment]
Strange from #2055, this is just a separate configuration. We can make it work with the `-force` flag as well though.

**Comment by i0rek** [comment]
thanks for the pointer. because of the lack of docs I didn't expect to work that way.

**Comment by i0rek** [comment]
I would be fine with closing this issue.
