### ISSUE TITLE
packer-builder-virtualbox-iso build fails when running multiple builds concurrently and one build finishes first

### ISSUE THREAD

**Issue by endthestart** [mitchellh/packer#2375]
I have been able to reproduce this issue almost 100% of the time. We are using a combination of shell scripts and ansible-local to provision our virtual machines. If I run multiple builds at the same time to create various virtual machines, when a build finishes another build stops at exactly the same time. This happens consistently and I have captured the log output. You can see in the logs that one machine is finished and it is shutting down the plugins. Once the plugins are shut down ansible-local fails and packer attempts to move on to the next step.

If I run each build independently I do not run into this issue. I have also been unable to recreate the issue locally on OS X. The builds are taking place on an Ubuntu 14.04 LTS server running Jenkins and Packer 0.8.0. I was also able to reproduce this with CentOS 6.6. I switched the OS to Ubuntu to see if it was specific to CentOS and it appears it is not. 

```
==> /tmp/packer-log302087976 <==
2015/06/30 16:01:48 waiting for all plugin processes to complete...
==> /tmp/packer.log <==
2015/06/30 16:01:48 waiting for all plugin processes to complete...
==> /tmp/packer-log302087976 <==
2015/06/30 16:01:48 /usr/local/packer/packer-provisioner-file: plugin process exited
2015/06/30 16:01:48 /usr/local/packer/packer-provisioner-shell: plugin process exited
==> /tmp/packer.log <==
2015/06/30 16:01:48 /usr/local/packer/packer-provisioner-file: plugin process exited
2015/06/30 16:01:48 /usr/local/packer/packer-provisioner-shell: plugin process exited
==> /tmp/packer-log302087976 <==
2015/06/30 16:01:48 /usr/local/packer/packer-provisioner-ansible-local: plugin process exited
==> /tmp/packer.log <==
2015/06/30 16:01:48 /usr/local/packer/packer-provisioner-ansible-local: plugin process exited
==> /tmp/packer-log302087976 <==
2015/06/30 16:01:48 /usr/local/packer/packer-provisioner-shell: plugin process exited
==> /tmp/packer.log <==
2015/06/30 16:01:48 /usr/local/packer/packer-provisioner-shell: plugin process exited
==> /tmp/packer-log302087976 <==
2015/06/30 16:01:48 /usr/local/packer/packer-builder-virtualbox-iso: plugin process exited
==> /tmp/packer.log <==
2015/06/30 16:01:48 /usr/local/packer/packer-builder-virtualbox-iso: plugin process exited
==> /tmp/packer-log302087976 <==
2015/06/30 16:01:48 /usr/local/packer/packer-post-processor-vagrant: plugin process exited
==> /tmp/packer.log <==
2015/06/30 16:01:48 /usr/local/packer/packer-post-processor-vagrant: plugin process exited
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-builder-virtualbox-iso: 2015/06/30 16:01:48 remote command exited with '0': cd /tmp/packer-provisioner-ansible-local && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/pb_screen_dms.yml --extra-vars user=vagrant --tags packer --sudo -c local -i /tmp/packer-provisioner-ansible-local/screen_dms_base.yml
2015/06/30 16:01:48 packer-builder-virtualbox-iso: 2015/06/30 16:01:48 [INFO] RPC endpoint: Communicator ended with: 0
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 [INFO] 0 bytes written for 'stderr'
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 [INFO] 9475 bytes written for 'stdout'
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 [INFO] RPC client: Communicator ended with: 0
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 [INFO] RPC endpoint: Communicator ended with: 0
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-provisioner-ansible-local: 2015/06/30 16:01:48 [INFO] 0 bytes written for 'stderr'
2015/06/30 16:01:48 packer-provisioner-ansible-local: 2015/06/30 16:01:48 [INFO] 9475 bytes written for 'stdout'
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-provisioner-ansible-local: 2015/06/30 16:01:48 [INFO] RPC client: Communicator ended with: 0
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 ui: ==> virtualbox-iso: Provisioning with shell script: ../scripts/cleanup.sh
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-provisioner-shell: 2015/06/30 16:01:48 Opening ../scripts/cleanup.sh for reading
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-provisioner-shell: 2015/06/30 16:01:48 [INFO] 66 bytes written for 'uploadData'
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 [INFO] 66 bytes written for 'uploadData'
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-builder-virtualbox-iso: 2015/06/30 16:01:48 opening new ssh session
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-builder-virtualbox-iso: 2015/06/30 16:01:48 ssh session open error: 'use of closed network connection', attempting reconnect
2015/06/30 16:01:48 packer-builder-virtualbox-iso: 2015/06/30 16:01:48 reconnecting to TCP connection for SSH
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-builder-virtualbox-iso: 2015/06/30 16:01:48 reconnection error: dial tcp 127.0.0.1:3503: connection refused
==> /tmp/packer.log <==
==> /tmp/packer-log500233114 <==
2015/06/30 16:01:48 packer-provisioner-shell: 2015/06/30 16:01:48 Retryable error: Error uploading script: dial tcp 127.0.0.1:3503: connection refused
==> /tmp/packer.log <==
```

**Comment by endthestart** [comment]
{
  "variables": {
    "headless_flag": "false"
  },
  "builders": [
    {
      "type": "virtualbox-iso",
      "output_directory": "box_name",
      "vm_name": "packer-box_name",
      "virtualbox_version_file": ".vbox_version",
      "headless": "{{user `headless_flag`}}",
      "guest_os_type": "RedHat_64",
      "disk_size": 40960,
      "iso_url": "http://fake-url.dev/CentOS-6.6-x86_64-minimal.iso",
      "iso_checksum": "4ed6c56d365bd3ab12cd88b8a480f4a62e7c66d2",
      "iso_checksum_type": "sha1",
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-6.6-x86_64/ks.cfg<enter><wait>"
      ],
      "boot_wait": "15s",
      "http_directory": "../http",
      "guest_additions_path": "VBoxGuestAdditions.iso",
      "ssh_username": "root",
      "ssh_password": "root",
      "ssh_port": 22,
      "ssh_wait_timeout": "10000s",
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "1024"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "1"
        ]
      ],
      "shutdown_command": "echo 'vagrant'|sudo -S /sbin/halt -h -p"
    }
  ],
  "post-processors": [
    {
      "output": "../build/box_name.box",
      "type": "vagrant",
      "compression_level": 9
    }
  ],
  "provisioners": [
    {
      "type": "file",
      "source": "../ansible/roles/repos/files/epel.repo",
      "destination": "/etc/yum.repos.d/epel.repo"
    },
    {
      "type": "shell",
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
      "scripts": [
        "../scripts/ansible.sh"
      ]
    },
    {
      "type": "ansible-local",
      "extra_arguments": [
        "--extra-vars user=vagrant",
        "--tags packer",
        "--sudo"
      ],
      "inventory_file": "../ansible/inventory/box_name_base.yml",
      "playbook_file": "../ansible/pb_box_name.yml",
      "playbook_dir": "../ansible"
    },
    {
      "type": "shell",
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
      "scripts": [
        "../scripts/cleanup.sh"
      ]
    }
  ]
}

**Comment by cbednarski** [comment]
@endthestart Thanks for the report. I'm guessing there's some kind of filesystem collision between runs that causes one of the concurrent runs to clobber the other one(s).

For example, packerA might write ansible.sh to the filesystem and then packerB deletes it before packerA is finished using it. I haven't dug into this yet, just a suspicion.

**Comment by endthestart** [comment]
@cbednarski As a follow-up, I attempted to monitor a few directories for files that are created/deleted during the process. I was unable to see anything that stands out. I'm not entirely sure I understand how the packer_cache directory is being utilized, but maybe some file in there is causing the VM to crash? Is it possible that the VBoxAdditions.iso file in being unmounted and removed from the filesystem and causing the other VMs to crash? I think this issue might be more related to VirtualBox than Packer itself, but again I am able to run many builds concurrently on my OS X machine. If I run a higher number of parallel builds I tend to get VirtualBox specific errors in the output. If I limit the building to 2 or 3 VMs at a time then I get the same timeout errors where the VM just stops responding and Packer is unable to provision. 

As such, is there anything specific you think I can look at in regards to files, cache, settings? Are there any log settings I can monitor and paste here that will help you figure out the issue? I'm able to reproduce this 99% of the time, so it should be easy to get new logs if there is anything that can help.

**Comment by cbednarski** [comment]
I have not looked at the code for this yet but my guess is that there is some logic that does not currently handle the possibility of concurrent builds running in the same folder from the same template. I'd further speculate that two or more builds collide over the same resources (vm, disk, etc.).

Based on re-reading your description, I'm inclined to think this is not actually supported behavior in the first place, and may be working unintentionally as a quirk of how the VMware plugin is implemented.

Can you try creating a new workspace for each build in Jenkins? (Don't just delete the workspace, actually create a unique workspace for each build.) You can set this in Advanced Project Options -> Use Custom Workspace using something like this:

    workspace/${JOB_NAME}/build-number-${BUILD_NUMBER}

![screen shot 2015-07-26 at 17 05 42](https://cloud.githubusercontent.com/assets/649798/8896665/9725445e-33b8-11e5-8f33-27520807a1c8.png)
