### ISSUE TITLE
0.8.0 applies the only one last id of `security_group_ids`  to amazon-ebs

### ISSUE THREAD

**Issue by darklore** [mitchellh/packer#2380]
Thanks for great devops tools. 

My packer template is here.

```
"builders": [
    {
      "type": "amazon-ebs",
      "region": "{{user `region`}}",
      "ssh_username": "{{user `ssh_username`}}",
      "vpc_id": "{{user `vpc_id`}}",
      "subnet_id": "{{ user `subnet_id`}}",
      "security_group_ids": "sg-91533ef4,sg-43d7ba26",
      "instance_type": "t2.micro",
      "source_ami": "{{user `source_ami`}}",
      "ami_name": "{{user `project_name`}}-{{user `recipe_name`}}-{{user `cookbook_version`}}",
      "associate_public_ip_address": true
    }
]
```

I ran `packer build` with packer 0.8.0, and found that only one id of `security_group_ids` (sg-43d7ba26) was applied to a target instance. `sg-91533ef4` was not applied.

Then I switched to packer 0.7.5, and found both of ids are applied.

Is this spec of 0.8.0?
Is there a way to set multiple security group ids ?

**Comment by matt-richardson** [comment]
`security_group_ids` is meant to be an array, rather than a comma delimted string, isn't it?

**Comment by darklore** [comment]
Yes.

I modified my template to use array of strings ( `"security_group_ids": ["sg-91533ef4", "sg-43d7ba26"],` ) and tried again but result was same. Only "sg-43d7ba26" was applied.

**Comment by smerrill** [comment]
I have a fix for this in #2831. Would you mind testing that change out?

**Comment by cbednarski** [comment]
@darklore I think this was fixed in https://github.com/mitchellh/packer/pull/2381 if not, please reopen. Thanks!

**Comment by darklore** [comment]
Thank you!
I confirmed this issue was fixed in packer 0.8.1.

**Comment by thrashr888** [comment]
This might have returned. I'm using Packer 0.8.2 and I'm having the same problem. It was working for me with Packer 0.8.1.

**Comment by cristim** [comment]
It still happens with the current code.

**Comment by rickard-von-essen** [comment]
@cristim Open a new issue.

**Comment by cristim** [comment]
@rickard-von-essen thanks, I created #4870
