### ISSUE TITLE
Remove "ssh_wait_timeout" value from virtualbox/vmware builder basic examples

### ISSUE THREAD

**Issue by tylert** [mitchellh/packer#2382]
Commit 3cc90768a2509a2046aaba1b646fa6d3c814048e removed the "ssh_wait_timeout" option from the "Optional" sub-section of the "Configuration Reference" sections of the following website pages:
* https://packer.io/docs/builders/virtualbox-iso.html
* https://packer.io/docs/builders/virtualbox-ovf.html
* https://packer.io/docs/builders/vmware-iso.html

However, it is still shown in each of the examples on those pages and seems to not be available in the communicator template (https://packer.io/docs/templates/communicator.html).

In the "Basic Example" section of the virtualbox-iso, virtualbox-ovf and vmware-iso pages:
```
{
    ...
    "ssh_wait_timeout": "30s",
    ...
}
```

Perhaps it would be a bit less confusing to remove this value from the examples on those pages (and rely on their sensible default values).

**Comment by laapsaap** [comment]
https://www.packer.io/docs/builders/qemu.html has it too.
I wasted 30mins because I thought this problem was something else.

**Comment by tylert** [comment]
@laapsaap did you submit a pull-request to correct the issue in the docs?
