### ISSUE TITLE
Automatically share aws images with others?

### ISSUE THREAD

**Issue by ldanielw1** [mitchellh/packer#2384]
Is there any way I can use packer to also automatically give some AMIs permissions to be viewed/launched by other users? I have a demo account I'd like to share amis with, and have been doing it manually this whole time.

I saw the ami_users variable, but I haven't been able to get it to work...

**Comment by mitchellh** [comment]
Yes this should be able to be done with the `ami_users` setting. Please ask usage questions to the mailing list. Issues are just for bugs.
