### ISSUE TITLE
Adding "min_packer_version" to packer template crashes 0.8.1

### ISSUE THREAD

**Issue by tylert** [mitchellh/packer#2385]
Adding in the new "min_packer_version" key/value (as described at https://packer.io/docs/templates/introduction.html) causes a crash in Packer 0.8.1 (Mac OS X 10.10.4) while attempting to run "packer validate".  Removing "min_packer_version" proceeds as expected with no crash.

```
{
  "builders": [
  ...
  ],
  "description": "Bla bla bla",
  "min_packer_version": "0.8.0",
  "post-processors": [
  ...
  ],
  ...
}
```

Example template that causes the crash:
https://github.com/tylert/packer-build/blob/c93252f25e83743d368bf1d26be995d53c5a13ea/debian/jessie/base-64.json

Contents of crash.log are here:
https://gist.github.com/tylert/41e4dc91acd5640386d3

**Comment by tylert** [comment]
This also fails to crash Packer 0.8.0.

**Comment by gtmtech** [comment]
+1

**Comment by cbednarski** [comment]
Minimal repro:

```
{
  "builders":[
    {
      "type":"file",
      "target":"2385_output.txt",
      "content":"testing!"
    }
  ],
  "min_packer_version":"0.8.0"
}
```

**Comment by jakirkham** [comment]
+1

**Comment by glennr** [comment]
+1
