### ISSUE TITLE
Allow to upload result of post processor to Atlas

### ISSUE THREAD

**Issue by vladistan** [mitchellh/packer#2388]
Looks like Atlas post processor allows only to upload artifacts produced by builder.  It would be great to allow uploading artifacts produced by post processor.   For example it will benefit this Vagrant provider  https://github.com/gosddc/vagrant-vcenter

**Comment by cbednarski** [comment]
Heyo! You can now do this using the [artifice post-processor](https://www.packer.io/docs/post-processors/artifice.html), which allows you to override which files are used as the artifact.
