### ISSUE TITLE
warning message: No entry for terminal type 'unknown', using dumb terminal settings?

### ISSUE THREAD

**Issue by ldanielw1** [mitchellh/packer#2393]
I'm getting this "dumb terminal" message during packer build process. Is this anything to worry about? I don't remember this existing before I upgraded to 0.8.0 (though I upgraded again to 0.8.1 and issue is still there)

aws_us-east-1: No entry for terminal type "unknown";
aws_us-east-1: using dumb terminal settings.

**Comment by purgatorio** [comment]
I was running into the same issue as you. It looks like there is a change to how SSH functions in the 0.8.0 release: https://github.com/mitchellh/packer/blob/master/CHANGELOG.md#080-june-23-2015

This may give you some more information about it as well: https://github.com/mitchellh/packer/issues/1804

I ended up having to set "ssh_pty: true"" in a few of my builders to get them to pass: https://www.packer.io/docs/templates/communicator.html#ssh_pty

**Comment by ldanielw1** [comment]
This worked for me - thanks!
