### ISSUE TITLE
'vmware-vmx' builder throws 'Cloning is not supported...' error

### ISSUE THREAD

**Issue by mhsiemaszko** [mitchellh/packer#2395]
Hi, 

I wanted to reuse the output of 'vmware-iso' (built via ESXi host in our dataceter), which works very well, to install our custom software on top of OS + required 3rd party dependencies (the contents of the VM image that 'vmware-iso' outputs) using the 'vmware-vmx' builder that comes with Packer (using v. 0.8.1). 

Unfortunately, Packer throws the "Build 'vmware-vmx' errored: Cloning is not supported with VMWare Player version 5. Please use VMWare Player version 6, or greater" error. 

Regardless of whether it's VMware Player 7.1.0 + VMware VIX API + qemu-img or VMware Workstation 11.1.2 build-2780323. 

I also deliberately downgraded to VMware Workstation 10.0.6 build-2700073 seeing the VMware driver for version 10 @ https://github.com/mitchellh/packer/tree/master/builder/vmware/common but that did not help either - same error. 

The OS where I run the 'vmware-vmx' is CentOS release 6.3

These are trial versions of VMware Player / VMware Workstation that I tested 'vmware-vmx' with - 

I did read both https://github.com/mitchellh/packer/issues/972 and https://github.com/mitchellh/packer/issues/2085 - 

Does this feature (i.e. Cloning) only work on licensed VMware Player / VMware Workstation versions and if so which version was Packer tested against? I need to make sure this actually works and know the exact versions (e.g up to VMware Workstation 10.0.6, etc.)

Thank you for your help.

**Comment by cbednarski** [comment]
@mhsiemaszko Cloning and linked cloning are licensed / paid features in VMware Workstation and Fusion / Fusion Pro.

We test the majority of packer's functionality against VMware Player. We'd welcome pull requests to improve the error messaging around this, but we don't have the bandwidth to maintain a compatibility matrix at the moment.

**Comment by bstock92** [comment]
>Cloning and linked cloning are licensed / paid features in VMware Workstation and Fusion / Fusion Pro.

@cbednarski Should these features work on trials of Workstation/Fusion Pro?

**Comment by bstock92** [comment]
**Cloning is not supported with VMWare Player version 5. Please use VMWare Player version 6, or greater.**

May require a full, paid license of Workstation Pro:
- https://groups.google.com/forum/#!topic/packer-tool/p-gp73piL3o
   - Did this person have their Trial license expire, or does the Packer clone feature require a non-Trial license of Workstation Pro?
- However, vmrun clone works:
    - vmrun clone input/output-vmw-base/packer-vmw-base.vmx output/packer-vmw-base-clone.vmx full
- Ask for clarification: https://github.com/hashicorp/packer/issues/2395
