### ISSUE TITLE
When using WinRM communicator the connection does not complete after 0.8.1

### ISSUE THREAD

**Issue by pecigonzalo** [mitchellh/packer#2399]
Basically as the title says, when starting a new build (vmware or virtualbox) the builder works up till the point it tries to connect to WinRM, seems to never detect the connection coming up.

https://gist.github.com/pecigonzalo/7fbed10ed07deb651b35

```
  "builders": [
    {
      "type": "virtualbox-iso",
      "vm_name": "{{user `W2K12R2_BASE_NAME`}}",
      "iso_url": "{{user `SOURCE_URL`}}/Windows Server/2012/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso",
      "iso_checksum_type": "md5",
      "iso_checksum": "FB101ED6D7328ACA6473158006630A9D",
      "headless": false,
      "boot_wait": "50s",
      "guest_additions_mode": "attach",
      "communicator": "winrm",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "guest_os_type": "Windows2012_64",
      "disk_size": 61440,
      "format": "ovf",
      "floppy_files": [
        "./answer_files/W2K12R2/Autounattend.xml",
        "./scripts/init.bat",
        "./scripts/oracle-cert.cer",
        "./scripts/enable-winrm.ps1"
      ],
      "output_directory": "{{user `OUTPUT_DIRECTORY`}}/{{user `W2K12R2_BASE_NAME`}}",
      "vboxmanage": [
        [
          "modifyvm", "{{.Name}}", "--memory", "2048"
        ],
        [
          "modifyvm", "{{.Name}}", "--cpus", "2"
        ]
      ]
    }
  ],
```

**Comment by ducke** [comment]
Like you, I have the same problem.
Add under vboxmanage
```json
 [
"modifyvm", "{{.Name}}", "--natpf1", "guestwinrm,tcp,127.0.0.1,5985,,5985"
]
```

**Comment by pecigonzalo** [comment]
That would point in the direction of the WinRM communicator not connecting in the right port.
I do see Packer create a port FW from random host port to an internal 5985 like it does on SSH. (Its even still using SSH in some of the text) so its just not trying to connect on it as the port FW is there.

Ill check if i can spot the error on the code.

**Comment by burtlo** [comment]
I assume this is the same issue I am currently having creating images. I saw this in Packer released 0.8.0 and it seems to also be present in Packer 0.8.1.

I have seen this on MacOSX 10.10.4 and Windows 8.1 Pro.

### Packer File

```json
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": "",
    "aws_keypair": "{{env `AWS_KEYPAIR`}}"
  },
  "builders": [{
    "type": "amazon-ebs",
    "communicator": "winrm",
    "region": "us-east-1",
    "ami_regions": [ "us-west-1" ],
    "source_ami": "ami-478d782c",
    "instance_type": "t2.micro",
    "winrm_username": "Administrator",
    "ami_name": "Windows 2012R2 - TEST"
  }],

  "provisioners": [{
    "type": "powershell",
    "inline": [
      "Invoke-WebRequest https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chefdk-0.6.2-1.msi -OutFile chefdk.msi",
      "Start-Process chefdk.msi /qn -Wait"
    ]

  }]
}
```

### Output

```
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 559df2ae-de99-221d-e2c6-d6bd386a104b
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 5985 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-34549f9c
==> amazon-ebs: Waiting for instance (i-34549f9c) to become ready...
==> amazon-ebs: Waiting for auto-generated password for instance...
    amazon-ebs: It is normal for this process to take up to 15 minutes,
    amazon-ebs: but it usually takes around 5. Please wait.
    amazon-ebs:
    amazon-ebs: Password retrieved!
==> amazon-ebs: Waiting for WinRM to become available..
```

This step waits for a long time and never connects.

**Comment by burtlo** [comment]
I started to search around to understand more about Packer and WinRM and came upon the conversation here which seems to fit my situation https://github.com/packer-community/packer-windows-plugins/issues/28. In there is a gist to a working solution https://gist.github.com/mefellows/0373408377337ab62ff5.

**Comment by pecigonzalo** [comment]
I dont see how that issue is related to this. The problem here seems to be WinRM not trying to connect on the correct port. Thats why when using :
```
[
          "modifyvm",
          "{{.Name}}",
          "--natpf1",
          "guestwinrm,tcp,127.0.0.1,5985,,5985"
        ]
```
it works.

There might be a variable we can use in the form of:
```
"builders": [{
      "type": "virtualbox-windows-ovf",
      "source_path": "thepath.iso",
      "headless": false,
      "boot_wait": "30s",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "winrm_wait_timeout": "5m",
      "winrm_port": "{{ .theForwardedSSHPort }}",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
     }]
```

But i did not find it yet.

**Comment by pecigonzalo** [comment]
The issue is on :
https://github.com/mitchellh/packer/blob/ea225488d1a84c13cc36d338271acd6686b2dd97/helper/communicator/step_connect_winrm.go#L98
That references the default WinRM port for the gust, not the dynamically mapped one on virtualbox, thats why it works on VMWare (VMware connects directly not trough NAT).
SSH references a function that i assume retrieves the allocated port on the NAT.

Ill try and figure out how to add this, @mitchellh mind throwing some light im struggling to understand the  ```func(multistep.StateBag)``` from step_connect_ssh.go and how to replicate the functionality on winrm.

**Comment by ducke** [comment]
:+1:

**Comment by pecigonzalo** [comment]
Submitted a pull request.

**Comment by charleslieferando** [comment]
I am also seeing the same issue with packer 0.10.1. My configuration is:

`{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },
  "builders": [{
    "ami_description": "Base Windows Server 2012 R2 machine",
    "type": "amazon-ebs",
    "communicator": "winrm",
    "winrm_username": "Administrator",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "eu-west-1",
    "source_ami": "ami-29eb7e5a",
    "instance_type": "m3.medium",
    "ssh_username": "ubuntu",
    "ami_name": "base-ami-{{timestamp}}",
    "ami_regions": ["eu-central-1"],
    "force_deregister": true,
    "tags": {
    	"Name": "base-ami",
    	"Os_name": "windows",
    	"Os_release": "2012 R2",
    	"Created_at": "{{isotime}}"
  	}
  }]
}`

and it gets stuck

`packer build -var 'aws_access_key=****' -var 'aws_secret_key=****' machine.json
amazon-ebs output will be in this color.

==> amazon-ebs: Force Deregister flag found, skipping prevalidating AMI Name
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 576aa3b6-281b-1f37-36c4-9bc1a9e9c074
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 5985 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-affe8f23
==> amazon-ebs: Waiting for instance (i-affe8f23) to become ready...
==> amazon-ebs: Waiting for auto-generated password for instance...
    amazon-ebs: It is normal for this process to take up to 15 minutes,
    amazon-ebs: but it usually takes around 5. Please wait.
    amazon-ebs:  
    amazon-ebs: Password retrieved!
==> amazon-ebs: Waiting for WinRM to become available...
==> amazon-ebs: Timeout waiting for WinRM.
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Timeout waiting for WinRM.

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Timeout waiting for WinRM.

==> Builds finished but no artifacts were created.`

**Comment by fewknow** [comment]
I am having the same issue with openstack.
==> Builds finished but no artifacts were created.
sam.flint@sflint-53:~/Documents/repos/PeopleMatter/ansible/pack/servers (master)*$ packer build packer_windows.json
openstack output will be in this color.

==> openstack: Discovering enabled extensions...
==> openstack: Loading flavor: 8
    openstack: Verified flavor. ID: 8
==> openstack: Creating temporary keypair: packer 5810bdb0-66ec-5d76-428a-18a76b7b23d7 ...
==> openstack: Created temporary keypair: packer 5810bdb0-66ec-5d76-428a-18a76b7b23d7
==> openstack: Successfully converted BER encoded SSH key to DER encoding.
==> openstack: Launching server...
    openstack: Server ID: ec58ed3c-8773-4758-a251-d64989a90132
==> openstack: Waiting for server to become ready...
==> openstack: Waiting for password since WinRM password is not set...
    openstack: Password retrieved!
==> openstack: Waiting for server (ec58ed3c-8773-4758-a251-d64989a90132) to become RackConnect ready...
==> openstack: Waiting for WinRM to become available...
==> openstack: Timeout waiting for WinRM.
==> openstack: Terminating the source server: ec58ed3c-8773-4758-a251-d64989a90132 ...
==> openstack: Deleting temporary keypair: packer 5810bdb0-66ec-5d76-428a-18a76b7b23d7 ...
Build 'openstack' errored: Timeout waiting for WinRM.

==> Some builds didn't complete successfully and had errors:
--> openstack: Timeout waiting for WinRM.

####################################################
######################packer json######################
######################################################


{
  "variables": {
    "source_ami": "{{env `RACKSPACE_BASE_IMAGE`}}",
    "username": "{{ env `OS_USERNAME` }}",
    "windows_password": "{{env `RACKSPACE_WINDOWS_PASSWORD`}}",
    "winrm_password": "{{ env `WINRM_PASSWORD`}}",
    "winrm_username": "{{ env `WINRM_USERNAME`}}"
  },
  "builders": [
    {
      "type": "openstack",
      "openstack_provider": "rackspace",
      "username": "{{ user `username`}}",
      "password": "{{ user `windows_password` }}",
      "region": "IAD",
      "communicator": "winrm",
      "source_image": "{{ user `source_ami` }}",
      "image_name": "windows-app-server-{{timestamp}}",
      "flavor": "8",
      "winrm_username": "{{ user `winrm_username` }}",
      "winrm_password": "{{ user `winrm_password` }}",
      "winrm_timeout": "20m",
      "ssh_interface": "private",
      "ssh_ip_version": "4",
      "identity_endpoint": "https://identity.api.rackspacecloud.com/v2.0",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "rackconnect_wait": true,
      "user_data_file": "../../prep_winrm.txt"
    }
  ],
  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "../../playbooks/mja.yml"
    }
  ]
}

**Comment by rickard-von-essen** [comment]
@charleslieferando @fewknow Since this is fixed a year ago this is not what you are seeing. Please don't hijack old and closed issues. 

Ask for help on  _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

If you are certain that you are seeing a bug open a _new_ issue and provide the required info.

Locking this..
