### ISSUE TITLE
set artifact before post processor runs

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#2403]
I have qemu builder, that bootstrap some vm , create tarball from filesystem and download to local file system.
After that i want to use this tarball as docker image for docker post processor, but for this i need to say that my tarball is artifact, instead of this docker post processor runs with qemu disk image as artifact. Does this is suitable for builder or i need to use local shell post processor (this is looks more ugly, but works now)

**Comment by cbednarski** [comment]
@vtolstov I think we would need to overload the artifact list somewhere. For instance we could make a new post-processor that lets you arbitrarily add / remove / set files in the artifact list, or overload them in the builder output or similar. I'm not sure if this would have weird side-effects, though, like breaking cleanup operations.

**Comment by vtolstov** [comment]
Interesting, I'm already write post-processor for setting needed builderId, adding files may be useful, for cleanup we can use exiting keep_input_artifact feature and remove unneded artifacts in this post processor...
I'm try to write this processor and check, after that I can create pr.

**Comment by vtolstov** [comment]
close the issue, because artifict already created.
