### ISSUE TITLE
Post-processor to upload OpenStack images to Glance

### ISSUE THREAD

**Issue by jhftrifork** [mitchellh/packer#2409]
A la [post-processor for vsphere](https://github.com/mitchellh/packer/blob/master/post-processor/vsphere/post-processor.go), [for Vagrant Cloud](https://github.com/mitchellh/packer/blob/master/post-processor/vagrant-cloud/step_upload.go), etc., we would like a post-processor for OpenStack, to upload built VM images to a Glance instance.

**Comment by jhftrifork** [comment]
As of now, I'm working on this task.

**Comment by vtolstov** [comment]
I'm start upload post processor,but now it supports only ssh, but technical
is simple to add
08 июля 2015 г. 10:47 пользователь "James H. Fisher" <
notifications@github.com> написал:

**Comment by jhftrifork** [comment]
Hi @vtolstov I'm planning to use https://github.com/rackspace/gophercloud for this. I've extended it to include a Go wrapper around the Glance API.

**Comment by vtolstov** [comment]
@jhftrifork what do you think about integrating to  http://git.selfip.ru/vtolstov/packer-post-processor-upload ?
I think that upload post processor can support many storage backends and we can use one for all backends, back end may be present by some interface that can store files.
I want to move my work to github, so we can work together...

**Comment by jhftrifork** [comment]
@vtolstov I'd be more than happy to collaborate. I've been asked to work on a post-processor in the core packer repo. Would you be willing to move your work to the core packer repo, under the MPL2 license?

**Comment by vtolstov** [comment]
OK, I'm try
08 июля 2015 г. 13:22 пользователь "James H. Fisher" <
notifications@github.com> написал:

**Comment by vtolstov** [comment]
@jhftrifork please check pr 2410

**Comment by jhftrifork** [comment]
@vtolstov could you write `website/source/docs/post-processors/upload.html.markdown` to explain how to use the post-processor?

**Comment by vtolstov** [comment]
I'm now integrate swift support to uploader, after that i'm write docs, but now usage is very simple - you need to provide endpoint in URL like for ssh:
ssh://login:passw@host:port/path/?key=~/.ssh/key&timeout=20s

so for glance you can something like:
glance:// as scheme and other stuff in this like manner...

**Comment by imduffy15** [comment]
Hey all,

What more is required to get this merged?

**Comment by OldCrowEW** [comment]
hi, any progress on completing this?

**Comment by imduffy15** [comment]
Completed but the functionality still isn't merged in the gophercloud
libraries.

I would suggest looking at #3139 and using python glance or open stack
client.

**Comment by VMTrooper** [comment]
Hello @imduffy15. +1 for interest in a formal OpenStack post-processor.

In the meantime, I will try the shell-local example that you posted.

**Comment by cbednarski** [comment]
Hey folks, we're tracking this issue here: https://github.com/mitchellh/packer/issues/2678

I'm closing this one as a duplicate.
