### ISSUE TITLE
EOF on Atlas post-processor

### ISSUE THREAD

**Issue by jedineeper** [mitchellh/packer#2411]
Getting some weird errors trying to run a virtualbox build into vagrant and then into atlas.

```
==> virtualbox-iso: Running post-processor: atlas
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 1 error(s) occurred:

* Post-processor failed: unexpected EOF

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

eu-west-1: ami-baf6b4cd
--> amazon-ebs: jedineeper/aem-author/amazon.ami (v2)
panic: runtime error: index out of range
```

std/crash output; https://gist.github.com/jedineeper/952a9a57f7041c87f3e6

**Comment by cbednarski** [comment]
@jedineeper Thanks for the report! Can you try with [packer 0.8.1](https://packer.io/downloads.html) and see if the problem persists?

We've changed quite a bit so this may be fixed already, but if the crash persists in 0.8.1 I'd like to get an 0.8.1 stack trace.

**Comment by jedineeper** [comment]
@cbednarski I've run the test again with 0.8.1 and the problem looks to persist. :(

I've updated the gist in the OP with the new logs.

**Comment by cbednarski** [comment]
@jedineeper Thanks for the update log. We'll check it out.

**Comment by cbednarski** [comment]
@jedineeper I repro'd this with an old version of the code. However, the code path was changed in 0.8.0 and this should no longer occur. Can you run `packer version` and verify you're not still running 0.7.5?

This is the code in question:

	include := make([]string, 0, len(fs)) // 0.7.5 (crashes)
	for i, f := range fs {
		include[i] = strings.Replace(f, path, "", 1)
	}

	include := make([]string, len(fs))  // 0.8.0+ (safe)
	for i, f := range fs {
		include[i] = strings.Replace(f, path, "", 1)
	}

The only way this could crash in 0.8.0+ is if the string slice is not zero-indexed, which I think is impossible.

If you can reproduce this with 0.8.1 then there's something wonky going on with the underlying data structure. I can rewrite this as 

	include := []string{}
	for _, f := range fs {
		include = append(include, strings.Replace(f, path, "", 1))
	}

to make it independent of the index value, but afaik this should not be necessary.

If you can repro with packer 0.8.1 please post a log and a minimal sample config that I can use to make a test (your gist seems to be from 0.7.5).

Thanks!
