### ISSUE TITLE
getting Public DNS Name as a variable from the amazon builder

### ISSUE THREAD

**Issue by dayer4b** [mitchellh/packer#2412]
I'd love to be able to use the Public DNS Name as a variable in the `shell-local` provisioner when using the `amazon-ebs` builder.

I've looked at the code for template interpolation, but I'm not sure how to do this.

enhancement please?

**Comment by dayer4b** [comment]
I should explain the use case for this.  I do a lot of application deploys using tools like Capistrano and Fabric.  If I had the Public DNS Name of the EC2 instance, then I could use the `shell-local` provisioner to execute the `cap deploy`, etc.  This way I could deploy my application and make an AMI of it all at once with Packer.

Currently, I rely on the AWS CLI, but I'd love to get away from that.  Thanks!

**Comment by EmmN** [comment]
+1

**Comment by nickmalcolm** [comment]
The above is the exact use case I'm after too. Is it possible to find this in a variable anywhere, which we can include in a `command` template?

**Comment by rickard-von-essen** [comment]
There are a endless list of variables that can be wanted in `shell-local` that expose information from the builder. This pollutes the post-processor with logic from _all_ builders. 

I recommend that you use `shell` provisioner to write whatever info you need to a tmp file, the the `file` provisioner to download it and source the file in `shell-local`. 

@mwhooker close?

**Comment by mwhooker** [comment]
I would recommend using the manifest post-processor to get the ami ID, and then in your shell script you can use the aws cli tools to get the public dns name
