### ISSUE TITLE
puppet server: client_cert_path & client_private_key_path not honoured

### ISSUE THREAD

**Issue by igalic** [mitchellh/packer#2413]
when trying to provision a vm with the puppet [`server-provisioner`](https://packer.io/docs/provisioners/puppet-server.html), we are getting the following errors:
```
igalic@levix:~/src/vm-templates (ubuntu-14.04-x86_64 *%=) $ packer validate template.json
Errors validating build 'vmware-iso'. 2 error(s) occurred:

* client_cert_dir must point to a directory
* client_private_key_dir must point to a directory
```
when adding those two options, which are [neither mentioned in the docs](https://packer.io/docs/provisioners/puppet-server.html), nor in [the source](https://github.com/mitchellh/packer/blob/v0.8.1/provisioner/puppet-server/provisioner.go#L16-L47), we're getting:
```
igalic@levix:~/src/vm-templates (ubuntu-14.04-x86_64 *%=) $ packer validate template.json
Template validation failed. Errors are shown below.

Errors validating build 'vmware-iso'. 2 error(s) occurred:

* unknown configuration key: "client_cert_dir"
* unknown configuration key: "client_private_key_dir"
```

**Comment by durist** [comment]
I ran into this as well-- it's unclear whether what's required is paths to certificate files, or to directories containing those files, and if the latter, what the certificate files need to be named.

**Comment by zhangguangyan** [comment]
I ran into this as well. Is anyone looking at this issue?

**Comment by rickard-von-essen** [comment]
Closing this since these are now in the docs.

**Comment by rickard-von-essen** [comment]
@zhangguangyan gist a full debug log and link it here,  you probably have a broken installation.
