### ISSUE TITLE
Crash when using winrm communicator 0.8.1

### ISSUE THREAD

**Issue by trodemaster** [mitchellh/packer#2416]
Packer crashed when using winrm to build a windows vm. 

2015/07/08 15:47:03 packer-builder-vmware-iso: panic: runtime error: invalid memory address or nil pointer dereference
2015/07/08 15:47:03 packer-builder-vmware-iso: [signal 0xb code=0x1 addr=0x20 pc=0xe0132]
2015/07/08 15:47:03 packer-builder-vmware-iso: 

Full crash log
https://gist.githubusercontent.com/trodemaster/e0672bb523e444b9bb22/raw/winrmcrash.log

**Comment by trodemaster** [comment]
Host system is OS X 10.10.4
builder is vmware-iso
VMware Fusion 7.1.2

**Comment by cbednarski** [comment]
@trodemaster Thanks for the report and log. I've snipped a relevant part of the stack trace here.

```
2015/07/08 15:47:03 packer-builder-vmware-iso: goroutine 23280 [running]:
2015/07/08 15:47:03 packer-builder-vmware-iso: io.Copy(0x0, 0x0, 0x9a9018, 0xc2134ed860, 0x0, 0x0, 0x0)
2015/07/08 15:47:03 packer-builder-vmware-iso: 	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:364 +0x272
2015/07/08 15:47:03 packer-builder-vmware-iso: created by github.com/mitchellh/packer/communicator/winrm.runCommand
2015/07/08 15:47:03 packer-builder-vmware-iso: 	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/communicator/winrm/communicator.go:89 +0x10e
2015/07/08 15:47:03 packer-builder-vmware-iso: 
```
