### ISSUE TITLE
chained builders

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#2419]
I have maybe my own use case, but may be someone else needed this:
* build qemu image via qemu builder
* pass qemu builder artifact to another qemu builder, that builds image from previous image
  * post-process build by compressor
  * create docker image from qemu qemu builder (use own plugin that change artifact type and files)
* use docker image by docker builder and modify base docker image to something else
  * deploy docker image to registry

**Comment by cbednarski** [comment]
@vtolstov Thanks for the suggestion. This is on our radar but there is not currently a good way to do this.

**Comment by vtolstov** [comment]
2015-07-09 17:47 GMT+03:00 Chris Bednarski <notifications@github.com>:

> @vtolstov <https://github.com/vtolstov> Thanks for the suggestion. This
> is on our radar but there is not currently a good way to do this.


May be simple add sequence element to builder, if it absent then = 0, so
each builder independent, if > 0, sort builders by this number and run from
start to end...?

**Comment by cbednarski** [comment]
I think we need to be able to override the artifact list so downstream steps can pick it up.

The problem is we probably have to change all of the builders, provisioners, and post-processors at the same time and it's a fairly large change to both configuration and implementation. I'd like to have some time to think about it rather than tacking it on.

The use-cases you provided are great, though. They'll be helpful to consider when planning this out.

**Comment by vtolstov** [comment]
@cbednarski what do you think about http://git.selfip.ru/vtolstov/packer-post-processor-artifact/src/master/artifact/post-processor.go ?

this my tries to create artifact post processor that can change builder type and include exclude artifacts. I'm succeseful build tar from qemu vm, download it and push to docker registry

**Comment by cbednarski** [comment]
@vtolstov I wanted to give you a heads up that I will look at this soon. I have not yet had a chance to look at your PR in detail.

Related to #2403

**Comment by cbednarski** [comment]
To update anyone looking, the artifact-post-processor is [available here](https://www.packer.io/docs/post-processors/artifice.html).

@vtolstov To fully address your original suggestion I think we'll rethink how packer works. Probably a good post-1.0 design topic. I'm going to close for this for now but will keep it in mind.
