### ISSUE TITLE
centos7 error : sudo: sorry, you must have a tty to run sudo

### ISSUE THREAD

**Issue by lylianmeyemezu** [mitchellh/packer#2420]
Building centos7 image on aws and azure with the following variables 
"communicator": "ssh" ,
 "ssh_pty" : false

**Comment by cbednarski** [comment]
@lylianmeyemezu You can use `"ssh_pty" : true` to work around Cent's requirement to have a TTY. Otherwise you'll have to disable this sudo setting. Please see #1804 for more info.

**Comment by RichardHightower** [comment]
I was not sure where `"ssh_pty"` : true went. I ran into the same issue. I got around it by adding a user data file to the aws image. 

#### files/user-data
```sh
#!/bin/bash

sed -i -e '/Defaults    requiretty/{ s/.*/# Defaults    requiretty/ }' /etc/sudoers

```

It wipes out centos needing tty for sudo. 

Then I just add that to my packer builder.

#### amazon-ebs builder
```javascript
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "region": "{{user `aws_region`}}",
      "source_ami": "{{user `aws_ami_image`}}",
...
      "user_data_file" : "files/user-data.txt"   <------------------ THIS to use user data.
    }
  ],
```

That fixed it. 
Here is the complete work in progress.

#### base-image-centos7-for-DCOS (in progress)
```javascript
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": "",
    "aws_region": "us-east-1",
    "aws_ami_image": "ami-6d1c2007",
    "aws_instance_type": "m4.large"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "region": "{{user `aws_region`}}",
      "source_ami": "{{user `aws_ami_image`}}",
      "instance_type": "{{user `aws_instance_type`}}",
      "ssh_username": "centos",
      "ami_name": "base-centos-7-dcos-{{timestamp}}",
      "tags": {
        "OS_Version": "LinuxCentOs7",
        "Release": "7",
        "Description": "Base CentOs7 image with prerequisites for DC/OS"
      },
      "user_data_file" : "files/user-data.txt"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "sudo yum upgrade -y",
        "sudo yum update -y",
        "sudo systemctl stop firewalld",
        "sudo systemctl disable firewalld"
      ]
    },
    {
      "type": "file",
      "source": "files/overlay.conf",
      "destination": "/etc/modules-load.d/overlay.conf"
    },
    {
      "type": "shell",
      "inline": [
        "sudo reboot"
      ]
    },
    {
      "type": "shell",
      "inline": [
        "echo DONE"
      ],
      "pause_before": "60s"
    }
  ]
}
```

**Comment by RichardHightower** [comment]
Hmmm... https://www.packer.io/docs/templates/communicator.html seems I found the `"ssh_pty"`. Seems I have only ever used the default `communicator` so never ran into this before.

**Comment by SydOps** [comment]
@RichardHightower  solution is helpful, but sometime it takes time to finish user-data script.

Adding the following provisioner to the packer template, allows for the cloud-init process to fully finish before packer starts provisioning the source AMI.

https://www.packer.io/docs/other/debugging.html
```
{
  "type": "shell",
  "inline": [
    "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done"
  ]
}
```

**Comment by swimmingchar** [comment]
on redhat6 ,I use ansible with sudo,see this error,I use  @RichardHightower the way ,but see that all ways.

**Comment by rickard-von-essen** [comment]
Hi @swimmingchar, thanks for reaching out. 
You need to unset `Defaults    requiretty` in `/etc/sudoers`. For more info see Ansibles docs for [Become](http://docs.ansible.com/ansible/become.html).

This ticket is really old so it's probably not relevant to the issue you're seeing. If you're still think this is a bug, would you please open a new issue with the debug log and a json that reproduces the issue? 

Or if you would like get help with troubleshooting this you can use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool).

See https://www.packer.io/community/

Thanks!
