### ISSUE TITLE
provisioning failed in version 0.8.1 due to "you must have a tty to run sudo"

### ISSUE THREAD

**Issue by charlesxu2000** [mitchellh/packer#2423]
Env:
Packer 0.8.1, vmware-iso provider.

Error:
vmware-iso: sudo: sorry, you must have a tty to run sudo
(looks like the base.sh can not comment out the "Defaults requiretty" in /etc/sudoers

Log:
015/07/09 11:07:42 packer-builder-vmware-iso: 2015/07/09 11:07:42 opening new ssh session
2015/07/09 11:07:42 packer-builder-vmware-iso: 2015/07/09 11:07:42 starting remote command: chmod 0755 /tmp/script_7943.sh
2015/07/09 11:07:42 packer-builder-vmware-iso: 2015/07/09 11:07:42 remote command exited with '0': chmod 0755 /tmp/script_7943.sh
2015/07/09 11:07:42 packer-builder-vmware-iso: 2015/07/09 11:07:42 [INFO] RPC endpoint: Communicator ended with: 0
2015/07/09 11:07:42 [INFO] RPC client: Communicator ended with: 0
2015/07/09 11:07:42 [INFO] RPC endpoint: Communicator ended with: 0
2015/07/09 11:07:42 packer-provisioner-shell: 2015/07/09 11:07:42 [INFO] RPC client: Communicator ended with: 0
2015/07/09 11:07:42 packer-builder-vmware-iso: 2015/07/09 11:07:42 opening new ssh session
2015/07/09 11:07:42 packer-builder-vmware-iso: 2015/07/09 11:07:42 starting remote command: echo 'vagrant'|sudo -S sh '/tmp/script_7943.sh'
2015/07/09 11:07:42 packer-builder-vmware-iso: 2015/07/09 11:07:42 remote command exited with '1': echo 'vagrant'|sudo -S sh '/tmp/script_7943.sh'
2015/07/09 11:07:42 packer-builder-vmware-iso: 2015/07/09 11:07:42 [INFO] RPC endpoint: Communicator ended with: 1
2015/07/09 11:07:42 ui:     vmware-iso: sudo: sorry, you must have a tty to run sudo
2015/07/09 11:07:42 [INFO] 45 bytes written for 'stderr'
2015/07/09 11:07:42 [INFO] 0 bytes written for 'stdout'
2015/07/09 11:07:42 [INFO] RPC client: Communicator ended with:

This was working under Packer 0.7.5

**Comment by sethvargo** [comment]
Hi @charlesxu2000 

One of the changes in Packer 0.8 is that we no longer allocate a TTY by default. Please see #2420 for more information. Thanks!
