### ISSUE TITLE
cannot stat '/packer-files/upload321089613': No such file or directory

### ISSUE THREAD

**Issue by evadnoob** [mitchellh/packer#2436]
I'm having issues getting the docker builder/provisioning working.  The symptom appears to be that packer "hangs" waiting for the exit code from a command in the container.

run:
```
PACKER_LOG=1 packer build minimal_docker_ubuntu.json
```

I have created a gist with the log and a couple of docker builds that are having the issue.  
https://gist.github.com/evadnoob/38c5720937c5286ef61b

```
docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

```
packer version
Packer v0.8.1
```

**Comment by evadnoob** [comment]
I see this same issue now: https://github.com/mitchellh/packer/issues/901

**Comment by cbednarski** [comment]
@evadnoob Thanks for the report. I'm going to merge your notes into #901 and close this one. Thanks!

**Comment by cbednarski** [comment]
@evadnoob Thanks, reopening this since the previous issue was closed but not resolved.

**Comment by kudos** [comment]
I'm having this exact same issue.

```
root@9c28a69dc872:/# cat packer-files/cmd987799172
cp: cannot stat '/packer-files/upload512058233': No such file or directory
```

I've tried with Docker running in latest Virtualbox 4 and VMWare Fusion 7.1.2, but I haven't tried a Docker older than 1.7.0 yet.

**Comment by evadnoob** [comment]
Just for the record I was using older docker 1.6.x, same issue.

**Comment by rbclark** [comment]
Exact same here as well on OSX 10.10.4 with packer 0.8.2 and docker 1.7.1

    root@514e07ad6cb9:/# cat packer-files/cmd550444073
    cp: cannot stat '/packer-files/upload413803378': No such file or directory
