### ISSUE TITLE
Blank/empty values are passed on to EBS-Provisioner cause API errors

### ISSUE THREAD

**Issue by tb3088** [mitchellh/packer#2440]
Something must have change in the AWS API recently such that it can no longer gracefully accept blanks (aka ""). Specifically this bit of Packer JSON

"launch_block_device_mappings": [
        {
          "device_name" : "{{user `disk0_name`}}",
          "virtual_name": "{{user `disk0_virtual`}}",
          "volume_size" : "{{user `disk0_size`}}",
          "volume_type" : "{{user `disk0_type`}}",
          "delete_on_termination": "{{user `disk0_delete`}}",
          "snapshot_id" : "{{user `disk0_snapshot`}}",
          "encrypted"   : "{{user `disk0_encrypt`}}",
          "iops"        : "{{user `disk0_iops`}}",
          "no_device"   : "{{user `disk0_nodev`}}"
        },

On successive disks stanzas (eg. disk1_...) if "virtual_name" is "" it calls the API with said blank value instead of silently eating it. This now apparently generates an API error whereas before it was silently ignored by the AWS API.

The EBS Provisioner needs to silently eat blank values if they are known to cause API errors. In some cases, "" (blank) is probably fine. I don't know which attributes are newly picky, but it needs to get tracked down.

Clearly "virtual_name" can not be forwarded if the value is blank.
A change is needed in v0.7.2 to armor up against the AWS API change.

==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: Value ({{user `disk0_virtual`}}) for parameter virtualName is invalid. Expected format: 'ephemeral<NUMBER>' (InvalidParameterValue)

In Packer 0.8.1 the error is not caught properly(?)
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-b5e2554b
==> amazon-ebs: Waiting for instance (i-b5e2554b) to become ready...
==> amazon-ebs: Error waiting for instance (i-b5e2554b) to become ready: unexpected state 'shutting-down', wanted target 'running'

**Comment by tb3088** [comment]
Packer 0.8.1 in -debug is invoking with these settings (formatted and sorted for readability):

2015/07/13 16:24:34 packer-builder-amazon-ebs: 2015/07/13 16:24:34 
Config: {PackerConfig:{PackerBuildName:amazon-ebs PackerBuilderType:amazon-ebs PackerDebug:true PackerForce:false 

PackerUserVars:map[disk1_encrypt:false disk1_name:/dev/sdf 
disk0_nodev:false 
disk0_encrypt:false 
disk0_virtual: 
disk0_type:gp2 
disk0_iops:0 
disk0_snapshot: 
disk0_size:15 
disk0_delete:true 
disk0_name:/dev/sda1

disk1_size:60 disk1_type:gp2 disk1_snapshot: 
...
source_ami:ami-36a0ba5e

**Comment by tb3088** [comment]
Small correction. 0.7.5 works fine even with blank virtual_name values. I was mistakenly using 0.7.2 on another machine. The problem with 0.8.1 remains however.

**Comment by umang1912** [comment]
facing the exact same issue. @tb3088  - found any workaround?

**Comment by tb3088** [comment]
only v0.75 works at all for me.

**Comment by WyseNynja** [comment]
I would also like to start using 0.8, but am blocked by this.

AWS console says, "Client.InvalidParameterCombination: Could not create volume with size 0GiB from snapshot 'null'"
