### ISSUE TITLE
Objects in user variables

### ISSUE THREAD

**Issue by warroyo** [mitchellh/packer#2441]
is it possible to handle objects in user variables? For example using the chef-solo provisioner I would like to pass the json attributes as a user variable. It seems like with the current implementation this is not possible.

`Error reading variables in 'test.json': json: cannot unmarshal object into Go value of type string`

I have a file called `test.json` that looks contains the following:

```
{
"metadata":{"somekey":"somevalue"}
}

```

I receive the error above when passing the file in with the  `var-file` option.

is there a specific reason this is not implemented? It would not be necessary to parse the deeply nested object it would just need to set the user variable `metadata` to an object so it could be used by object types in the packer.json

**Comment by wizurijyq** [comment]
hmm why this one is closed?

**Comment by rickard-von-essen** [comment]
Preprocess the template with jq, sed, python, ruby etc.

**Comment by wizurijyq** [comment]
can you give an example?

**Comment by rickard-von-essen** [comment]
Please ask on the mailing list.
