### ISSUE TITLE
VMWare does not shutdown the machine on termination

### ISSUE THREAD

**Issue by pecigonzalo** [mitchellh/packer#2452]
As title says when using the VMWare builder (VMWare Workstation 10) if i terminate the build for any reason, packer does not terminate the machine and delete everything, in most cases it doesnt even shutdown the machine.

**Comment by pecigonzalo** [comment]
Im working on a pull request to fix this. FYI so we dont duplicate work

**Comment by pecigonzalo** [comment]
Will close this issue as i cant reproduce it again.

**Comment by cbednarski** [comment]
Thanks for following up. If you run into this again please reopen!
