### ISSUE TITLE
packer is not going to building using go1.2.1

### ISSUE THREAD

**Issue by monsterzz** [mitchellh/packer#2453]
I'm trying to build it on Ubuntu 14.04 Trusty, using `golang` from upstream repositories.

    $ dpkg -s golang | grep Version
    Version: 2:1.2.1-2ubuntu1

    $ go version
    go version go1.2.1 linux/amd64

    $ make updatedeps
    go get -u github.com/mitchellh/gox
    go get -u golang.org/x/tools/cmd/stringer
    go list ./... \
		| xargs go list -f '{{join .Deps "\n"}}' \
		| grep -v github.com/mitchellh/packer \
		| sort -u \
		| xargs go get -f -u -v
    flag provided but not defined: -f

When I changed `-f` to `-fix` I get another errors

    ...
    github.com/pierrec/lz4
    # github.com/pierrec/lz4
    ../../pierrec/lz4/lz4.go:86: undefined: sync.Pool
    ...
    github.com/rackspace/gophercloud/openstack
    # google.golang.org/cloud/compute/metadata
    ../../../google.golang.org/cloud/compute/metadata/metadata.go:54: unknown net.Dialer field 'KeepAlive' in struct literal
    ...
    make: *** [updatedeps] Error 123

It seems that dependencies will not compile under golang1.2 and we need to update documentation to reflect this change.

**Comment by umang1912** [comment]
the documentation mentions that go 1.4+ is required - 

##### If you wish to work on Packer itself or any of its built-in providers, you'll first need Go installed (version 1.4+ is required). Make sure Go is properly installed, including setting up a GOPATH.

**Comment by monsterzz** [comment]
Yeah, but in contributor docs said that we need at least 1.2. I've
submitted PR to address that issue.
