### ISSUE TITLE
Packer doesn't work with Rackspace when 2 factor authentication is enabled

### ISSUE THREAD

**Issue by ace22b** [mitchellh/packer#2457]
I can't seem to get new packer version to work with Rackspace when 2 factor is enabled.

Error I get is:

```
* Expected HTTP response code [200 203] when accessing [POST https://identity.api.rackspacecloud.com/v2.0/tokens], but got 401 instead
{"unauthorized":{"code":401,"message":"Additional authentication credentials required"}}
```

If I set SDK_API_KEY=$OS_API_KEY I get:

```
* The base Identity V2 API does not accept authentication by APIKey
```

Looking at gophercloud it looks like they have Rackspace specific module with APIKey support:
https://github.com/rackspace/gophercloud/blob/master/rackspace/auth_env.go

Packer version is 0.8.1
Relevant configuration files/full log here: https://gist.github.com/ace22b/9c8011d114ab623dcad3

Thanks.

**Comment by cbednarski** [comment]
@ace22b Thanks for the report and configs -- very helpful!

**Comment by tdooner** [comment]
I was able to fix this error with this patch:

```
diff --git a/builder/openstack/access_config.go b/builder/openstack/access_config.go
index ca33495..1d7adeb 100644
--- a/builder/openstack/access_config.go
+++ b/builder/openstack/access_config.go
@@ -8,7 +8,7 @@ import (

        "github.com/mitchellh/packer/template/interpolate"
        "github.com/rackspace/gophercloud"
-       "github.com/rackspace/gophercloud/openstack"
+       openstack "github.com/rackspace/gophercloud/rackspace"
 )

 // AccessConfig is for common configuration related to openstack access
```

However, it would be great (and great for Rackspace...) if users could authenticate with them without having to build their own version of packer, as we will have to do until this is fixed.

**Comment by tdooner** [comment]
Hey, @aggroskater I saw you pop up in another Rackspace-related issue; is this still your bailiwick? Perhaps you know some Go-knowledgable rackers that could help?

**Comment by aggroskater** [comment]
Howdy everyone. My apologies for not noticing this earlier. For closure's sake --on my end, at least-- I'm no longer with Rackspace :) I've fired off an email to a colleague that's still at the Rack though, for what it's worth. It'd be great if they could get someone to officially take on an ambassador role; packer looks like an important project in its ecosystem.

**Comment by brandfocus** [comment]
+1

**Comment by brandfocus** [comment]
Until this is resolved we have had to create a new user with permission only to create and edit servers. With two factor disabled on this account it appears to work without a problem when authenticating without the API key using a password instead.

**Comment by mwhooker** [comment]
we've updated to `gophercloud/gophercloud` since this was opened. Please open a new issue if this is still a problem

**Comment by deepshikhaaa** [comment]
I'm facing this issue. Authentication is failing when using API key to configuration options. Can anyone help me out in this?

**Comment by rickard-von-essen** [comment]
@deepshikhaaa please ask for help on the [mailing list](https://groups.google.com/group/packer-tool).
