### ISSUE TITLE
amazon-ebs builder: IAM Role requires additional policy statement

### ISSUE THREAD

**Issue by bmatsuo** [mitchellh/packer#2458]
I was having problems creating a minimal AWS IAM policy to let packer build images. The symptoms are like those encountered in #577. However the resolution to #577 did not stop the failures I was seeing. It turns out that additional authorization was needed to launch instances *with an attached IAM policy*. I think the docs should probably be updated to mention the potential need for additional policies.

Symptoms:

The user was authorized to call the EC2 RunInstances API, but all calls from packer would fail with the error message

> ==> amazon-ebs: Error launching source instance: You are not authorized to perform this operation.

Resolution:

It turns out that using the amazon-ebs builder's `iam_instance_profile` requires the user to have an additional permission (beyond what is mentioned in the builder [docs](http://www.packer.io/docs/builders/amazon.html)).

I found a [blog post](http://blogs.aws.amazon.com/security/post/Tx3M0IFB5XBOCQX/Granting-Permission-to-Launch-EC2-Instances-with-IAM-Roles-PassRole-Permission) which explained that in order to launch an instance with an IAM role the user policy must allow the `iam:PassRole` action on the role resource. Instead of using an explicit ARN(s) for roles I just added the following statement to my policy and now packer can build images using amazon-ebs.

```
        {
            "Sid": "PackerIAMPassRole",
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": [
                "*"
            ]
        }
```

**Comment by cbednarski** [comment]
@bmatsuo Good catch, thanks.

**Comment by cbednarski** [comment]
I added a note about this in b533a4b833d87359d9c436796f7b34850465ca79

If you have a chance, can you review it and let me know if it addresses your concerns? Thanks!

**Comment by malachany** [comment]
I know this is old, but thanks for this. Fixed my issues.

**Comment by dgulli** [comment]
only problem with a wildcard resource is you're basically saying passrole can be used against anything rather than ec2?
