### ISSUE TITLE
HTTPIP and HHTPORT do not get evaluated  when using virtualbox 

### ISSUE THREAD

**Issue by gg-lit** [mitchellh/packer#2461]
Hi,

I am using packer to create a CentOS image for virtualbox, the variable HTTPIP and HTTPPort do not get evaluated. When anaconda receives the boot command, it is showing 
ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg
and the installation continues as manual and not using kickstart.

The issue  seems to be present in packer 8.0 and 8.1. I reverted back to version 7.5 and problem is not present. 
![workspace 1_063](https://cloud.githubusercontent.com/assets/9350631/8726640/60253a6e-2bd3-11e5-8124-019d4da1d774.png)

I have run packer with PACKER_LOG=1 enabled and saved the output, please let me know where to upload.

**Comment by cbednarski** [comment]
Thanks for the report! [gists](https://gist.github.com/) are a great way to share logs and configs.

I tried this with one of my packer configs and I did not experience the same problem. If you can share a minimal config that doesn't work as expected, that would be helpful.

**Comment by gg-lit** [comment]
Please find them here
https://gist.github.com/gg-lit/b4acf904c9fef85f78fd

**Comment by cbednarski** [comment]
How are you passing these variables to packer? Are you using `-var-file`? I'm guessing these need to be re-interpolated.

**Comment by gg-lit** [comment]
Yes with the -var-file, the full command is:
packer build -var-file=variables.json centos-6.6-vbox.json

**Comment by tylert** [comment]
I had a similar problem with {{.Version}} when I tried to move it from the builder to a user variable.  Interpolation of configuration templates inside user variables might all exhibit this same behaviour in this case (and might fit another existing open ticket).

**Comment by fuhbar** [comment]
Are there any plans to implement the variable interpolation inside user defined variables? Furthermore are there plans to add more data types than just only string as user variable (Array, Boolean)?
