### ISSUE TITLE
Packer should permit extra variables in var-file

### ISSUE THREAD

**Issue by rvandegrift** [mitchellh/packer#2466]
Right now, if my var-file defines `myvar` without being defined in the template's variables section, packer bails with `Unknown user variables: myvar`.  It'd be nice if packer would tolerate this situation.

Some of our templates require pre or post processing steps that packer does not handle.  To reduce repetition, it'd be nice to have a single per-app/per-customer JSON file with all such parameters, packer's included.

As a workaround, we can define all such parameters as variables in all templates.  This isn't very maintainable - a non-packer change requires updating all packer templates.

**Comment by cbednarski** [comment]
Does [`-var-file`](https://www.packer.io/docs/templates/user-variables.html) do what you want? It's described under "From A File".

**Comment by rvandegrift** [comment]
`-var-file` is how I hit this issue.  Maybe I've done something wrong?

```sh
$ cat vars.json
{
        "my_variable": "xyz"
}
$ cat template.json
{
    "builders": [
        {
            "type": "amazon-ebs",
            "access_key": "YOUR KEY HERE",
            "secret_key": "YOUR SECRET KEY HERE",
            "region": "us-east-1",
            "source_ami": "ami-de0d9eb7",
            "instance_type": "t1.micro",
            "ssh_username": "ubuntu",
            "ami_name": "packer-quick-start {{timestamp}}"
        }
    ]
}
$ ~/packer/packer validate -var-file=vars.json template.json      
Failed to parse template: 1 error(s) occurred:

* Unknown user variables: my_variable
```

My current workaround is to add this to template.json:
```javascript
"variables": {
        "my_variable": ""
    },
```

**Comment by tb3088** [comment]
This is a legitimate beef with Packer's parser. The final template JSON absolutely must know all variables you might want to inject. That it only handles strings is another of those $@)#@ issues when Go has proper integer, boolean, and array data types.

More and more people are resorting to dynamically generating the template file from some inputs (eg. Yaml to Json) to get around the limitations with the native parser and feeding to Packer via STDIN or pre-generated file. It's as if Packer was written with the notion that the templates were essentially static. Mind-boggling.

**Comment by rvandegrift** [comment]
I just tried 0.8.2, this bug is fixed there.  I'm stuck on 0.7.5 because of #2398, but I'll be good once that's fixed.

FWIW, I'm not sure I see value in further flexibility.  Any preprocessor or template system would make dynamic generation easy - cpp, m4, sed, etc.

**Comment by cbednarski** [comment]
@rvandegrift Thanks for following up with this. We overhauled interpolation in `0.8.0` and missed a few spots. `0.8.*` point releases are cleaning up some of the edges we missed.
