### ISSUE TITLE
Missing default values for "disk_cache" and "disk_discard" in QEMU builder docs

### ISSUE THREAD

**Issue by tylert** [mitchellh/packer#2467]
The current builder docs for QEMU are missing the default values used for the "disk_cache" and "disk_discard" settings.

https://packer.io/docs/builders/qemu.html

```
disk_cache (string) - The cache mode to use for disk. Allowed values values include any of "writethrough", "writeback", "none", "unsafe" or "directsync".

disk_discard (string) - The discard mode to use for disk. Allowed values include any of "unmap" or "ignore".
```

**Comment by tylert** [comment]
Also, update the description for 'headless' to match virtualbox-iso and vmware-iso more closely too and remove the duplicate word 'values' for disk_cache.

**Comment by cbednarski** [comment]
LGTM, thanks!
