### ISSUE TITLE
Attaching EBS to a windows box ---- not working 

### ISSUE THREAD

**Issue by dushyant28** [mitchellh/packer#2469]
I am trying to attach an EBS volume using the following but it doesn't seems to be working for me. Although it executes without any errors. Kindly help on this.

``` javascript
"ami_block_device_mappings": [
    {
      "device_name": "xvdh",
      "volume_type": "gp2",
      "volume_size": "1",
      "delete_on_termination": true,
      "encrypted": false
    }
]
```

**Comment by TimCorwin** [comment]
I am working with Dushyant on this, and we need to attach EBS volumes to windows instances; we have a chef recipe that can handle all the mounting etc, but really don't want to put aws-cli on every windows production AMI we produce...is there any way to just get the raw EBS volume attached for windows?

Thanks!

**Comment by cbednarski** [comment]
As these are calls to AWS I don't think they should be any different for windows in particular. I think the minimum volume size for EBS is 8, though. Can you try increasing that `volume_size` to at least 8?

If you would like to see more of what packer is doing you can also run with [`PACKER_LOG=1` and/or the `-debug` flag](https://packer.io/docs/other/debugging.html).

**Comment by TimCorwin** [comment]
I've increased volume_size to 8, and run in both -debug and with the packer_log environmental variable set; I'm still not seeing any errors related to generating volumes, but checking Amazon, only the root volume defined in the AMI is being created.

**Comment by dushyant28** [comment]
Any updates on this ?

**Comment by Chhed13** [comment]
Is this issue alive? We have the same winbdows problem.
Can it be solved any way or is their any workaround? Now it complitely blocks us.

**Comment by TimCorwin** [comment]
I never saw a fix and we abandoned the approach that required it, unfortunately

**Comment by Chhed13** [comment]
It seems that I found the key - using "no_device": "" allow to avoid ec2config, wich doesn't adjusted yet and disk is mapped!
And if you want to map disk on boot - use "launch_block_device_mappings" block enstead of "ami_block_device_mappings".
And hooray!!!!! it's alive!

**Comment by mwhooker** [comment]
It seems like there's enough information here to solve the issue. We can't support non-standard windows installs (ie not using [ec2config](http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/UsingConfig_WinAMI.html)), but would be happy to accept a PR to the docs.

If you believe this is an issue with packer, please open a new ticket with an entire json that will let us reproduce the issue. thanks!
