### ISSUE TITLE
Partial version numbers

### ISSUE THREAD

**Issue by jedineeper** [mitchellh/packer#2476]
Hi guys,

Partially an Atlas question; is the current Atlas build number available as a variable?

In an attempt to do semantic versioning I'd like to include the version number in the metadata for the postprocessor, but I'd like to allow Atlas to manage the patch number and only increase the major/minor myself when I know I've a release or breaking change?

When I include a version value in the metadata it is recognised and overrules the value provided by Atlas but I'd like to combine the two?

Don't know if anyone has considered this?

**Comment by cbednarski** [comment]
@jedineeper [Atlas provides some build metadata](https://atlas.hashicorp.com/help/packer/builds/build-environment), `ATLAS_BUILD_NUMBER` and `ATLAS_BUILD_CONFIGURATION_VERSION`, when it runs. I think you should be able to combine these with user vars to set the version. E.g.

```json
{
  "variables":{
    "atlas_build_number":"{{ env `ATLAS_BUILD_NUMBER`}}"
  },

  "post-processors":[
    {
      "type":"atlas",
      "metadata":{
        "version":"{{user `semver`}}+{{user `atlas_build_number`}}"
      }
    }
  ]
}
```

**Comment by jedineeper** [comment]
Thanks @cbednarski, that sounds perfect. I'll do some experimenting and reopen if necessary.
