### ISSUE TITLE
Compress post-provisioner generates artifact named packer_<no value>_<no value>

### ISSUE THREAD

**Issue by erhudy** [mitchellh/packer#2477]
When using Packer 0.8.2 on the template at https://github.com/erhudy/packer-templates/blob/develop/ubuntu-14.04/template.json, running `packer build -only=virtualbox-iso template.json` produces a Vagrant box with the expected name of `bcpc-ubuntu1404-virtualbox.box`, and a compressed artifact with the unexpected name of `packer_<no value>_<no value>`, instead of the configured name `bcpc-ubuntu1404-virtualbox.tar.gz`.

`file` indicates that it is gzipped data, so it appears that the requested filename is probably being read properly when determining what method to use to compress, the filename just doesn't get used (probably because of some weirdness in the override patterns).

**Comment by cbednarski** [comment]
Thanks for the report! To clarify, this only happens when using the `-only` flag?

**Comment by erhudy** [comment]
Tested and it happens without `-only`; in addition, the file gets clobbered depending on the order the builders ran in (e.g., running with `-parallel=false` means the `vmware-iso` build result will clobber `virtualbox-iso`).
