### ISSUE TITLE
unknown configuration key: "atlas_url"

### ISSUE THREAD

**Issue by samdunne** [mitchellh/packer#2478]
Hey guys,

`* unknown configuration key: "atlas_url"` is an error I'm getting while trying to use the atlas post-processor as documented [here](https://www.packer.io/docs/post-processors/atlas.html)

I'm using packer 0.8.2

[Debug output](https://gist.github.com/samdunne/a1cf4a11d6782ddd73ea)

[Reproducible Packer JSON](https://gist.github.com/samdunne/7511f1a06e3fa2e2a518)

Let me know if you need more information.

**Comment by cbednarski** [comment]
Thanks for the report! Maybe an oversight on our part since there's only one Atlas. Will look into this soon.

**Comment by cbednarski** [comment]
Turns out this is hard-coded upstream so changing this will involve a bit more work.
