### ISSUE TITLE
amazon-ebs builder: Packer does not automatically choose available AWS availability zones

### ISSUE THREAD

**Issue by zdexter** [mitchellh/packer#2485]
I did not specify `availability_zone` in my `amazon-ebs` builder configuration. I received:

```
Build 'amazon-ebs' errored: Error launching source instance: InsufficientInstanceCapacity: We currently do not have sufficient m4.large capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get m4.large capacity by not specifying an Availability Zone in your request or choosing us-east-1d, us-east-1e, us-east-1c.
    status code: 500, request id: []

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: InsufficientInstanceCapacity: We currently do not have sufficient m4.large capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get m4.large capacity by not specifying an Availability Zone in your request or choosing us-east-1d, us-east-1e, us-east-1c.
    status code: 500, request id: []
```

Packer [amazon-ebs builder documentation](https://www.packer.io/docs/builders/amazon-ebs.html) states that Packer will let Amazon auto-assign the availability zone:

> `availability_zone` (string) - Destination availability zone to launch instance in. Leave this empty to allow Amazon to auto-assign.`

However, as implied by the above errors, Packer appears to have requested `us-east-1a` explicitly.

Packer version: **0.8.1**

**Comment by zdexter** [comment]
Perhaps this is not actually a Packer bug, and Amazon chooses an availability zone even if there is insufficient capacity.

**Comment by cbednarski** [comment]
@zdexter I don't think insufficient capacity is going to be easy for me to test. Do you have a recommendation here? Would you like to close this?

**Comment by CpuID** [comment]
Feels like something you probably need mocked APIs for, to test reliably. Not sure if Packer has any or not.
