### ISSUE TITLE
Unable to remove --retcode-passthrough from salt-call in salt-masterless provisioner

### ISSUE THREAD

**Issue by david-thorman** [mitchellh/packer#2486]
It would nice if there was a way to remove that option since there are cases like mine where some salt-states will fail, but I don't want the entire build to fail because of it.

It seems like the best way to implement this would be to have an option in that provisioner that allows you send custom arguments to the salt call that is performed, similar to the way that arguments can be passed to the salt-bootstrap script.

I might be able to put some work in on this, but if anyone else can implement it quickly it would be greatly appreciated.

**Comment by cbednarski** [comment]
There's a PR open for this here: https://github.com/mitchellh/packer/pull/2488
