### ISSUE TITLE
uploads of shell script from Windows to Unix break due to line endings

### ISSUE THREAD

**Issue by jonathankarsh** [mitchellh/packer#2489]
Hope I'm not repeating a known issue. I haven't found any references to this exact problem.

The shell provisioner normally uses a `dos2unix` style conversion for scripts. This isn't currently supported for the file provisioner, so when packer is used on a Windows machine to build a Unix VM, and shell scripts are uploaded for later execution, issues _may_ happen due to the `\r\n` line ending in these shell scripts.

**Comment by pecigonzalo** [comment]
Are you saving the scripts with Windows or Unix line endings? I dont know if this is as intended or a bug actually if you are saving as Windows they get uploaded as is.

**Comment by jonathankarsh** [comment]
The scripts I'm uploading through the file provisioner are in git. I think that would be the most common case.
Github isn't git, but it's probably *the* place to go to for this sort of documentation.. please see:
https://help.github.com/articles/dealing-with-line-endings/#platform-windows vs.
https://help.github.com/articles/dealing-with-line-endings/#platform-mac vs.
https://help.github.com/articles/dealing-with-line-endings/#platform-linux

So on Windows we will most commonly have CRLF locally (but only LF when committing to git). On Linux and Mac we would probably have LF locally and in git.

The interesting thing to note here is that the shell provisioner already handles this issue, again probably considering that these shell scripts would come from a git repository, or just that people will have CRLF on Windows.

My claim is that the file provisioner will sometimes be used for shell scripts that must be executed later, and that an option to convert CRLF to LF would really help.

**Comment by cbednarski** [comment]
> My claim is that the file provisioner will sometimes be used for shell scripts that must be executed later, and that an option to convert CRLF to LF would really help.

Agreed -- this is a UX enhancement, not a bug. Right now if the script is wrong on your host it will be wrong when it's uploaded. I think we can apply the EOL fix without issue; if so we'll just Do The Right Thing.
