### ISSUE TITLE
rackconnect_wait does not check correct metadata for all RackSpace VM flavours

### ISSUE THREAD

**Issue by darrenhaken** [mitchellh/packer#2492]
This issue relates to the OpenStack builder, specifically when using it with RackSpace.

During server creation, RackSpace will attempt to install automation tools on the machine and it's important it's not interrupted as it seems to lead to corrupted VM's (or other issues).

It looks like Packer already supports checking for this using the rackconnect_wait param but it doesn't cover all cases. 

RackSpace can use different metadata keys to provide progress on installing automation services.
After speaking with RackSpace it looks like this is based on the VM flavour you use.  

At the moment the rackconnect_wait function within Packer is checking for "rackconnect_automation_status", but it also needs to check for "rax_service_level_automation".

FYI Our flavour of VM doesn't actually have "rackconnect_automation_status" but does have ""rax_service_level_automation"

We're working on a fix for this and will provide a PR, we really hope you accept this and deploy a new version of Packer. We'd love to contribute back.

**Comment by aggroskater** [comment]
An aside: I'd recommend having separate checks for rackconnect and managed cloud automation, as any given Rackspace cloud account could have neither, either, or both.

**Comment by cbednarski** [comment]
> We're working on a fix for this and will provide a PR, we really hope you accept this and deploy a new version of Packer. We'd love to contribute back.

@darrenhaken I appreciate the effort you're putting into this. It's definitely not something I'll get around to in the short term. I'll gladly accept PRs to improve this.
