### ISSUE TITLE
Windows AMI using Chef-Solo Provisioner

### ISSUE THREAD

**Issue by jonathanan** [mitchellh/packer#2495]
Is it possible to create a windows AMI using chef-solo provisioner? I am using the winrm communicator that is now supported in Packer 0.8 but am running into issues with the direction of slashes.
```
{
        "builders": [{
                "type": "amazon-ebs",
                "access_key": "...",
                "secret_key": "...",
                "region": "us-east-1",
                "source_ami": "ami-810cddea",
                "instance_type": "m3.medium",
                "ami_name": "packer-test-wse",
                "iam_instance_profile": "S3ReadAccess",
                "security_group_id": "...",
                "user_data_file": "{{template_dir}}/setup_winrm.txt",
                "communicator": "winrm",
                "winrm_username": "Administrator"
        }],

        "provisioners": [
                {
                        "type": "powershell",
                        "script": "download_chef.ps1"
                },
                {
                        "type": "chef-solo",
                        "skip_install" : "true",
                        "staging_directory" : "\\windows\\temp",
                        "prevent_sudo" : true,
                        "execute_command" : "c:\\opscode\\chef\\bin\\chef-solo --no-color -c {{.ConfigPath}} -j {{.JsonPath}}",
                        "cookbook_paths": ["./cookbooks"],
                        "json": {...},
                        "run_list": [...]
                }
        ]
}
```

This is my build output:
```
==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 55b03a14-3676-c703-b655-a8a00eaa
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-308a08d9
==> amazon-ebs: Waiting for instance (i-308a08d9) to become ready...
==> amazon-ebs: Waiting for auto-generated password for instance...
    amazon-ebs: It is normal for this process to take up to 15 minutes,
    amazon-ebs: but it usually takes around 5. Please wait.
    amazon-ebs:
    amazon-ebs: Password retrieved!
==> amazon-ebs: Waiting for WinRM to become available...
==> amazon-ebs: Connected to WinRM!
==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Provisioning with shell script: download_chef.ps1
==> amazon-ebs: Provisioning with chef-solo
    amazon-ebs: Creating directory: \windows\temp
    amazon-ebs: Creating directory: \windows\temp/cookbooks-0
    amazon-ebs: The syntax of the command is incorrect.
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error uploading cookbooks: Non-zero exit status.
```
I know I can get this done with using only powershell provisioners but was wondering if chef-solo was supported. Thanks!

**Comment by cbednarski** [comment]
Thanks for the bug report! Windows paths are tricky. I think this one may need a drive identifier, like `C:\`

    "staging_directory" : "\\windows\\temp",

Also, you may have better luck with unix-style paths `/`? Sometimes this works, but sometimes it creates files with / in the filename (rather than a folder).

Can you let me know if either of these things helps? If so we can add to the documentation or possibly use [`ToSlash`](http://golang.org/pkg/path/filepath/#ToSlash) to do it automatically.

**Comment by jonathanan** [comment]
I've actually tried both of those variations and receive the same result. The drive identifier doesn't seem to be needed since there is no error right after the `\windows\temp` directory gets created.

You could try testing real quick with `md c:/path/to/something` in a cmd prompt. I get `The syntax of the command is incorrect`. However, I believe newer versions of windows support unix-style paths in the command prompt. I am doing this quick test on windows 7.

**Comment by maheshkawatra** [comment]
Do we have a solution to this issue? I am having similar issue.

**Comment by markhuge** [comment]
This should eliminate the need for a powershell shim, yes?: https://github.com/mitchellh/packer/pull/1215

**Comment by blairham** [comment]
Just so you know the error you are getting is due to "mkdir -p" this is an invalid command on windows and is hard coded in the provisioner.

**Comment by kbarry-x** [comment]
This appears to be addressed partially here:
https://github.com/mitchellh/packer/issues/1317

**Comment by jonathanan** [comment]
I'm going to close this issue as it is addressed here https://github.com/mitchellh/packer/pull/1215. Hopefully this will be in the release 0.9.

For now, I am using the powershell provisioner as a workaround for downloading chef and running it.
