### ISSUE TITLE
packer provisioning get stuck while building docker container

### ISSUE THREAD

**Issue by renethio** [mitchellh/packer#2497]
sorry this has been mentioned before but didn't find the one could work for me.
I am trying to build docker container using packer but while building the image it get stuck on the provisioning stage and then throw an error

-bash-4.1$ packer version
Packer v0.7.5

-bash-4.1$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0

both packer and docker running on centos:6.6

-bash-4.1$ packer build add.json
docker output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: ubuntu
    docker: Pulling repository ubuntu
    docker: d2a0ecffe6fa: Pulling image (latest) from ubuntu
    docker: d2a0ecffe6fa: Pulling image (latest) from ubuntu, endpoint: https://registry-1.docker.io/v1/
    docker: d2a0ecffe6fa: Pulling dependent layers
    docker: 83e4dde6b9cf: Download complete
    docker: b670fb0c7ecd: Download complete
    docker: 29460ac93442: Download complete
    docker: d2a0ecffe6fa: Download complete
    docker: d2a0ecffe6fa: Download complete
    docker: Status: Image is up to date for ubuntu:latest
==> docker: Starting docker container...
    docker: Run command: docker run -v /tmp/packer-docker034820413:/packer-files -d -i -t ubuntu /bin/bash
    docker: Container ID: 5dfd626f9486c4d7a5938085d3aa86b6de5ec34ecde756fbd3a4cfa3d3df0dd7
==> docker: Provisioning with shell script: /tmp/packer-shell432627756

**Comment by svett** [comment]
I have a same problem in packer 0.8.6. I am using `Boot2Docker-cli version: v1.8.0
Git commit: 9a26066` and docker:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 19:47:52 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

This is my `template.json`:

```
{
  "builders": [
    {
      "type": "docker",
      "image": "ubuntu",
      "commit": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "script": "setup.sh"
    }
  ]
}
```

The `setup.sh` is:

```
#!/bin/bash
set -x
set -e
echo Hello
```

This is a part of the log after running `PACKER_LOG=debug packer build template.json`:

```
==> docker: Provisioning with shell script: setup.sh
2015/08/31 11:15:18 packer-provisioner-shell: 2015/08/31 11:15:18 Opening setup.sh for reading
2015/08/31 11:15:18 packer-provisioner-shell: 2015/08/31 11:15:18 [INFO] 37 bytes written for 'uploadData'
2015/08/31 11:15:18 [INFO] 37 bytes written for 'uploadData'
2015/08/31 11:15:18 packer-builder-docker: 2015/08/31 11:15:18 Executing in container 8c8f8bade4be6d12c6898e1cbcd912ae529eabc7cd3d1b94ad2e805e8d0c6b2a: "(command cp /packer-files/upload262206050 /tmp/script_7943.sh) >/packer-files/cmd300663385 2>&1; echo $? >/packer-files/cmd300663385-exit"
2015/08/31 11:15:20 packer-builder-docker: 2015/08/31 11:15:20 Waiting for exit code to appear for remote command...
```

It hangs on provisioning. @mitchellh Do you know any work around?

**Comment by georgebashi** [comment]
I've just hit the same thing. Might be something to do with docker-machine? Mine just hangs indefinitely.

**Comment by jessechahal** [comment]
I ran into the same issue and if you read through google, github issues, and the offical packer documentation for docker you'll see only Linux is supported for the docker builder. Supposedly there is a fix in the master branch that might make it so OSX and windows are supported. I haven't tried to build packer from source yet to try this out but please report back here if you're able to get it working for a non-linux os.

**Comment by tylert** [comment]
@jessechahal are you talking about https://github.com/mitchellh/packer/issues/2675 or a different issue?

This is the first time I have heard that the docker builder doesn't support OS X and I didn't come across any mention in the official docs about a lack of support for OS X--however, I did actually come here looking for a solution since it would appear that it isn't working :)  (I guess I picked a really bad time to start playing with the docker builder.)

I am also trying to get Packer 0.9.0 + docker builder working on OS X and am running into a similar issue with it hanging:
```
2016/03/04 14:04:41 packer: 2016/03/04 14:04:41 Waiting for container to finish starting
2016/03/04 14:04:41 ui:     docker: Container ID: 11ffdcc09d824e6cee3703a3bb11c473ddf0db2c59fb0024e118415bcfae1d46
    docker: Container ID: 11ffdcc09d824e6cee3703a3bb11c473ddf0db2c59fb0024e118415bcfae1d46
2016/03/04 14:04:41 ui: ask: ==> docker: Pausing after run of step 'StepRun'. Press enter to continue.
==> docker: Pausing after run of step 'StepRun'. Press enter to continue.

2016/03/04 14:04:55 ui: scan err: unexpected newline
2016/03/04 14:04:55 ui: ask: ==> docker: Pausing after run of step 'StepConnect'. Press enter to continue.
==> docker: Pausing after run of step 'StepConnect'. Press enter to continue.
2016/03/04 14:04:58 ui: scan err: unexpected newline
2016/03/04 14:04:58 packer: 2016/03/04 14:04:58 Running the provision hook
2016/03/04 14:04:58 ui: ==> docker: Provisioning with shell script: /var/folders/7k/y1s717md333bdctmfw17dvxh0000gn/T/packer-shell684031071
==> docker: Provisioning with shell script: /var/folders/7k/y1s717md333bdctmfw17dvxh0000gn/T/packer-shell684031071
2016/03/04 14:04:58 packer: 2016/03/04 14:04:58 Opening /var/folders/7k/y1s717md333bdctmfw17dvxh0000gn/T/packer-shell684031071 for reading
2016/03/04 14:04:58 packer: 2016/03/04 14:04:58 [INFO] 24 bytes written for 'uploadData'
2016/03/04 14:04:58 [INFO] 24 bytes written for 'uploadData'
2016/03/04 14:04:58 packer: 2016/03/04 14:04:58 Executing in container 11ffdcc09d824e6cee3703a3bb11c473ddf0db2c59fb0024e118415bcfae1d46: "(command cp /packer-files/upload669586505 /tmp/script_7258.sh) >/packer-files/cmd686361876 2>&1; echo $? >/packer-files/cmd686361876-exit"
2016/03/04 14:05:00 packer: 2016/03/04 14:05:00 Waiting for exit code to appear for remote command...
```

Attaching to the running container while packer is stuck waiting for it yields the following stuff:
```
root@11ffdcc09d82:/packer-files# ls -l
total 16
-rw-r--r--. 1 root root 75 Mar  4 19:05 cmd686361876
-rw-r--r--. 1 root root  2 Mar  4 19:05 cmd686361876-exit
root@11ffdcc09d82:/packer-files# cat cmd686361876
cp: cannot stat '/packer-files/upload669586505': No such file or directory
root@11ffdcc09d82:/packer-files# cat cmd686361876-exit
1
```

My template:
```
{
  "builders": [
    {
      "export_path": "{{user `export_path`}}",
      "image": "{{user `image`}}",
      "type": "docker"
    }
  ],
  "description": "{{user `description`}}",
  "min_packer_version": "0.9.0",
  "post-processors": null,
  "provisioners": [
    {
      "inline": [
        "echo hello"
      ],
      "type": "shell"
    }
  ],
  "variables": {
    "description": "Test Docker",
    "export_path": "foo.tar",
    "image": "ubuntu"
  }
}
```

**Comment by tylert** [comment]
Oh, I'm running my stuff against a vagrant VM under OS X  https://github.com/coreos/coreos-vagrant

```
git clone https://github.com/coreos/coreos-vagrant
cp user-data.sample user-data
cp config.rb.sample config.rb
vagrant up
export DOCKER_HOST=tcp://172.17.8.101:2375
packer build test.json
```

**Comment by tylert** [comment]
Ok, awesome.  Yay!  The following work-around succeeds...

```
linuxvm$ wget https://releases.hashicorp.com/packer/0.9.0/packer_0.9.0_linux_amd64.zip
linuxvm$ unzip packer_0.9.0_linux_amd64.zip
linuxvm$ ./packer build test.json
```

**Comment by tylert** [comment]
See also #3102 and #3222.

**Comment by rljohnsn** [comment]
I believe I'm seeing the same thing. Although my packer install is a little old. Just installed latest Docker for Mac

```
() $ docker --version
Docker version 1.12.0, build 8eab29e
() $ packer --version
0.8.6
```

Mac OS: 10.11.5

Running packer with --debug I see the following in the log. The build hangs indefinitely.

```
2016/08/03 12:38:39 packer-builder-docker: 2016/08/03 12:38:39 Executing in container 31e8b21914101a38a6462d8e804f20551f257ee4dcb7b37bb6dc0b9c914ee273: "(set -e; mkdir -p /tmp/packer-chef-solo/cookbooks-0; command cp -R /packer-files/dirupload578185716/* /tmp/packer-chef-solo/cookbooks-0) >/packer-files/cmd414577859 2>&1; echo $? >/packer-files/cmd414577859-exit"
2016/08/03 12:38:43 packer-builder-docker: 2016/08/03 12:38:43 Command stdout: "cp: failed to close '/packer-files/dirupload578185716/eght_jetty/templates/default/9.3/etc/jetty-requestlog.xml.erb': Input/output error"
2016/08/03 12:38:43 packer-builder-docker: 2016/08/03 12:38:43 Command stdout: "cp: failed to close '/packer-files/dirupload578185716/eght_jetty/templates/default/9.3/etc/jetty-ssl.xml.erb': Input/output error"
2016/08/03 12:38:43 packer-builder-docker: 2016/08/03 12:38:43 Command stdout: "cp: cannot fstat '/packer-files/dirupload578185716/eght_jetty/templates/default/9.3/etc/jetty.conf.erb': Input/output error"
2016/08/03 12:38:43 packer-builder-docker: 2016/08/03 12:38:43 Command stdout: "cp: failed to close '/packer-files/dirupload578185716/eght_jetty/templates/default/9.3/etc/jetty.conf.erb': Input/output error"
2016/08/03 12:38:43 packer-builder-docker: 2016/08/03 12:38:43 Command stdout: "cp: failed to close '/packer-files/dirupload578185716/eght_jetty/templates/default/9.3/etc/jetty.erb': Input/output error"
```

**Comment by mwhooker** [comment]
There have been a bunch of changes since this issue was reported. Please try upgrading to the latest docker-machine and packer, and then open a new issue if you're still seeing this issue. We need to be able to reproduce the issue to diagnose the problem
