### ISSUE TITLE
What automated testing exists in Packer?

### ISSUE THREAD

**Issue by darrenhaken** [mitchellh/packer#2499]
I'm trying to make changes to Packer and submit a PR.
I'd like to be able to test any changes I make but I can't see any automated tests in the project.

Can someone provide clarity on this?
I'm new to golang (very) so maybe I'm just not looking in the right place.

**Comment by cbednarski** [comment]
Tests are found adjacent to the files they test. For example, if you want to add tests for the file builder, you will find the tests in `builder/file/*_test.go`.

You can run these tests via:

    go test -v ./builder/file/...

Or run all the tests via:

    go test -v ./...

Note that there are some intermittent failures in the winrm communicator tests so you may see those fail (sometimes they pass). Also, some of the acceptance tests that create resources (e.g. in AWS or GCE) require you to set `PACKER_ACC=1` like this:

    PACKER_ACC=1 go test -v ./builder/amazon/...

You don't need to run the acceptance tests with `PACKER_ACC=1` before you PR, but if you're tweaking one of those builders it would be helpful.

**Comment by darrenhaken** [comment]
Thanks, I can't see any tests any lower level than the builder. Are these files untested or tested through the builder?

Also could you explain can you explain where the callsite is to execute the Run function of the steps.
I looked up usages of Run for the step_wait_for_rackconnect but the IDE said there wasn't any.

Sorry for silly questions, as I said new to Go Lang :)

**Comment by cbednarski** [comment]
> I can't see any tests any lower level than the builder. Are these files untested or tested through the builder?

These are tested through acceptance tests, if they are tested. Packer's test covered is not stellar at the moment.

> Also could you explain can you explain where the callsite is to execute the Run function of the steps.
I looked up usages of Run for the step_wait_for_rackconnect but the IDE said there wasn't any.

Sure. `builder/openstack/builder.go` has a `Run` function. It includes data structure called `steps` that looks like this: 

	steps := []multistep.Step{
		&StepLoadExtensions{},
		&StepLoadFlavor{
			Flavor: b.config.Flavor,
		},
		&StepKeyPair{
			Debug:        b.config.PackerDebug,
			DebugKeyPath: fmt.Sprintf("os_%s.pem", b.config.PackerBuildName),
		},
		&StepRunSourceServer{
			Name:             b.config.ImageName,
			SourceImage:      b.config.SourceImage,
			SecurityGroups:   b.config.SecurityGroups,
			Networks:         b.config.Networks,
			AvailabilityZone: b.config.AvailabilityZone,
			UserData:         b.config.UserData,
			UserDataFile:     b.config.UserDataFile,
		},
		&StepWaitForRackConnect{
			Wait: b.config.RackconnectWait,
		},
		&StepAllocateIp{
			FloatingIpPool: b.config.FloatingIpPool,
			FloatingIp:     b.config.FloatingIp,
		},
		&communicator.StepConnect{
			Config: &b.config.RunConfig.Comm,
			Host: CommHost(
				computeClient,
				b.config.SSHInterface),
			SSHConfig: SSHConfig(b.config.RunConfig.Comm.SSHUsername),
		},
		&common.StepProvision{},
		&StepStopServer{},
		&stepCreateImage{},
	}

Essentially this is a list of steps that packer will invoke in order. You'll notice `StepWaitForRackConnect` about halfway down.

The step runner is a wrapper that helps us handle cancellation of a build (via `Ctrl-C`). Each step is wrapped in a goroutine which we can terminate if the user presses `Ctrl-C`. This also gives us an opportunity to clean up any resources we've created in the mean time (running vms, etc.).
