### ISSUE TITLE
Windows Packer with other ISO support?

### ISSUE THREAD

**Issue by mavenraven** [mitchellh/packer#2508]
Hello, I've created a repo for building a windows dev vagrant box that includes Visual Studio Ultimate (https://github.com/pivotal-cf/greenhouse-dev-base-box). Unfortunately, since I'm using a shell script to ensure everything is in place (and the repo I forked from uses make and curl), I don't think that I can just push this to Atlas and have it build. Is there any first class support in packer for iso's other than the OS? Thanks!

**Comment by cbednarski** [comment]
I'm not sure what you mean by first-class support for other ISOs. Do you mean downloading ISOs? I took a look and it looks like you're doing the following:

1. download several files
2. run packer build

If you want to use this workflow with Atlas you will need to perform step 1 on your computer or build machine, and then packer push the template and all other files to Atlas.

However, you could download many of these things inside the VM. The only ISO you need at the start is the OS installer.

**Comment by mavenraven** [comment]
@cbednarski So the use case that we're interested in is installing VS Ultimate on the box. According to this: https://github.com/joefitzgerald/packer-windows/blame/master/iso/README.md#L3, we cannot grab the iso directly from MSDN. I'm currently exploring this solution:  http://nuts4.net/post/loading-additional-iso-s-within-packer-io, which seems to work well, but again, the packer template has no way of knowing about the file.

You mentioned that `packer push` pushes files other than just the template. Does it push the entire directory it is ran in? The docs aren't really clear about that.

**Comment by cbednarski** [comment]
Yes push includes other files in the same directory, unless they are ignored.

You could also put these files in s3 and use signed URLs to download them.
