### ISSUE TITLE
Timeout Waiting for SSH error - Packer 0.8.2 and 0.8.6, VMware Fusion 7.1.2, VBox 4.3.2.2

### ISSUE THREAD

**Issue by dgoldssfo** [mitchellh/packer#2509]
Hi, 

I'm experiencing a "Timeout Waiting for SSH" error when using packer 0.8.2 to generate a VM. Same exact set up works perfectly with packer 0.7.5. Also, a similar job on VirtualBox works fine in either 0.7.5 or 0.8.2.

Here's the standard output:

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: file:///Users/davidgoldsmith/VM/iso/CentOS-6.6-x86_64-bin-DVD1.iso
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8113
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Waiting 5s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...
==> vmware-iso: Timeout waiting for SSH.
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Timeout waiting for SSH.

Thanks,

David

**Comment by cbednarski** [comment]
Hi David, can you [try increasing `boot_wait` to 15s](https://packer.io/docs/builders/vmware-iso.html#boot_wait)? I've noticed that builds sometimes fail because packer starts typing the boot sequence before VMware is ready.

**Comment by dgoldssfo** [comment]
Thanks, Ed. The initial boot works fine. Does this problem happen on the second boot, after the OS has installed itself and before the provisioners run?

I actually tried changing it from 5s to 10s before submitting this issue, and it didn't seem to be the problem.

**Comment by dgoldssfo** [comment]
Chris, I gave setting bot_wait to 15s, but it didn't make a difference. I still get "Build 'vmware-iso' errored: Timeout waiting for SSH."

**Comment by cbednarski** [comment]
Sorry for the delay in getting back to you. Thanks for trying `boot_wait`! Sorry to hear that didn't resolve the issue for you. If you boot with a GUI you will be able to see what is happening inside the VM. You can do this using [`headless: "false"`](https://packer.io/docs/builders/vmware-iso.html#headless) in your builder config.

You can also try [-debug](https://packer.io/docs/other/debugging.html) mode and/or `PACKER_LOG=1`, though it sounds like your failure is happening before `-debug` will be useful.

I have had trouble with CentOS minimal build because it does not bring up a network interface by default. I notice you're using the full CentOS 6.6 DVD so this may not be your issue. However, using the GUI to watch the VM status should help you diagnose this sort of thing.

If you think this is a bug in packer can you share a minimal template that reproduces the issue so I can investigate? Thanks!

**Comment by cahlen** [comment]
I'm having the same problem.  Did this ever get resolved?

**Comment by jared52au** [comment]
Came here to find a solution to this as well (using 0.8.5). However, I failed to have the 'reboot' directive in my kickstart file so it wasn't rebooting after a successful install.

**Comment by dgoldssfo** [comment]
FYI, I do have a reboot directive in my kickstart file and still get the problem.

**Comment by jared52au** [comment]
Does the VM reboot and return to the login prompt?






On Tue, Aug 18, 2015 at 3:33 PM -0700, "dgoldssfo" <notifications@github.com> wrote:












FYI, I do have a reboot directive in my kickstart file and still get the problem.

**Comment by dgoldssfo** [comment]
I'm having trouble recalling. I guess given the amount of questions on 
this issue I should do some troubleshooting as Chris suggested. I will 
do so if I can find time today or tomorrow.

**Comment by cahlen** [comment]
The only way I could fix it was by editing my kickstart file and using dhcp instead of static.  I really wanted  to use static, but is just provisioned as a work around.  i.e., changing my kickstart to dhcp fixed the hang.

**Comment by dgoldssfo** [comment]
My kickstart file uses dhcp.

Perhaps it would be helpful to post it here:

# Install OS instead of upgrade
install
# Use CDROM installation media
cdrom
# Set up root user and authentication configuration
rootpw "changeit"
authconfig --nisdomain=openrock.org --enableshadow --passalgo=sha512
# System keyboard
keyboard us
# System language
lang en_US
# SELinux configuration
selinux --disabled
# Firewall configuration
firewall --disabled --ssh --service=ssh
# Installation logging level
logging --level=info
# Reboot after installation
reboot
# System timezone
timezone --isUtc America/Los_Angeles
# Network information
network  --bootproto=dhcp --device=eth0 --onboot=on --noipv6 
--hostname=forgerock.openrock.org
# System bootloader configuration
bootloader --append="crashkernel=auto rhgb quiet" --location=mbr 
--driveorder="sda"
# GNOME
xconfig --startxonboot --defaultdesktop gnome
# Partition clearing information
zerombr
clearpart --all  --drives=sda
  # Disk partitioning information
part /     --ondisk=sda --size=12200  --fstype=ext4  --asprimary
part swap  --ondisk=sda --size=3072
  %packages
# Required for GNOME support
@Desktop
@Desktop Platform
@General Purpose Desktop
@X Window System
@Internet Browser
# Some nice fonts
# Less overhead than downloading the whole @Fonts group
dejavu-sans-mono-fonts
liberation-mono-fonts
dejavu-sans-fonts
# Required for packer operation
openssh-clients
# Packages that might come in handy in some situations
# Developer stuff
dos2unix
mc
emacs
gcc
git
subversion
sendmail
# Monitoring
nc
iotop
sysstat
# Needed for VBox Guest Additions
SDL
%end

**Comment by jared52au** [comment]
Does the kickstart complete successfully and reboot to a running server? Can you ssh to it?






On Tue, Aug 18, 2015 at 3:41 PM -0700, "dgoldssfo" <notifications@github.com> wrote:










My kickstart file uses dhcp.



Perhaps it would be helpful to post it here:



# Install OS instead of upgrade

install

# Use CDROM installation media

cdrom

# Set up root user and authentication configuration

rootpw "changeit"

authconfig --nisdomain=openrock.org --enableshadow --passalgo=sha512

# System keyboard

keyboard us

# System language

lang en_US

# SELinux configuration

selinux --disabled

# Firewall configuration

firewall --disabled --ssh --service=ssh

# Installation logging level

logging --level=info

# Reboot after installation

reboot

# System timezone

timezone --isUtc America/Los_Angeles

# Network information

network  --bootproto=dhcp --device=eth0 --onboot=on --noipv6 

--hostname=forgerock.openrock.org

# System bootloader configuration

bootloader --append="crashkernel=auto rhgb quiet" --location=mbr 

--driveorder="sda"

# GNOME

xconfig --startxonboot --defaultdesktop gnome

# Partition clearing information

zerombr

clearpart --all  --drives=sda

  # Disk partitioning information

part /     --ondisk=sda --size=12200  --fstype=ext4  --asprimary

part swap  --ondisk=sda --size=3072

  %packages

# Required for GNOME support

@Desktop

@Desktop Platform

@General Purpose Desktop

@X Window System

@Internet Browser

# Some nice fonts

# Less overhead than downloading the whole @Fonts group

dejavu-sans-mono-fonts

liberation-mono-fonts

dejavu-sans-fonts

# Required for packer operation

openssh-clients

# Packages that might come in handy in some situations

# Developer stuff

dos2unix

mc

emacs

gcc

git

subversion

sendmail

# Monitoring

nc

iotop

sysstat

# Needed for VBox Guest Additions

SDL

%end

**Comment by jared52au** [comment]
I tried your kickstart file and it seems that when it finishes installing the packages, it doesn't reboot even though the directive is there. Not sure why...

**Comment by jared52au** [comment]
Had this issue trying to do a build on a remote ESX host. Did more research and didn't realize there was an ssh_timeout setting. So try adding a "ssh_timeout": "10000s" to your json file (or some number of seconds (s) or minutes (m)) and see if it completes.

**Comment by dgoldssfo** [comment]
Weird. I tried 0.8.2 again (on a different machine) and packer crapped out about two thirds of the way through the OS installation:

==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8178
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Waiting 5s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...
==> vmware-iso: Timeout waiting for SSH.
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.

**Comment by jared52au** [comment]
Was that after adding the ssh_timeout setting to your template?

**Comment by dgoldssfo** [comment]
Before. I just tried building again - added "ssh_timeout": "1000s" to my builder - and was able to create the build successfully with packer-0.8.2.

Maybe Chris or Mitchell could weigh in here - do we now need to add ssh_timeout to our builders when running 0.8.2 or higher, or is this a workaround that might point to a bug fix?

Also - Chris - I did try adding headless: "false" in my builder and it did not show any useful information.

Thanks,

David

**Comment by dgoldssfo** [comment]
I verified that this bug is still present in 0.8.6. 

Also verified that the workaround of adding "ssh_timeout": "1000s" to my builder works in 0.8.6.

**Comment by puneetk** [comment]
I am using the bento boxes from https://github.com/chef/bento and am getting the same issue

```
$ packer version
Packer v0.8.6
```
Command to build
```
packer build -only=virtualbox-iso  ubuntu-14.10-amd64.json
```
Output
```
virtualbox-iso output will be in this color.
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/14.10/ubuntu-14.10-server-amd64.iso
==> virtualbox-iso: Starting HTTP server on port 8403
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 3682)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm ubuntu-14.10-amd64 --memory 384
    virtualbox-iso: Executing: modifyvm ubuntu-14.10-amd64 --cpus 1
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: WARNING: The VM will be started in headless mode, as configured.
    virtualbox-iso: In headless mode, errors during the boot sequence or OS setup
    virtualbox-iso: won't be easily visible. Use at your own discretion.
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Timeout waiting for SSH.
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.
```
This is with Virtual Box 5.0. Will try with packer 0.7.5 to see if it works fine with older versions.

**Comment by puneetk** [comment]
```
diff --git a/ubuntu.json b/ubuntu.json
index 556fcd6..606092c 100644
--- a/ubuntu.json
+++ b/ubuntu.json
@@ -29,7 +29,7 @@
       ],
       "disk_size": "{{ user `disk_size` }}",
       "guest_os_type": "{{ user `vmware_guest_os_type` }}",
-      "headless": "{{ user `headless` }}",
+      "headless": true,
       "http_directory": "http",
       "iso_checksum": "{{ user `iso_checksum` }}",
       "iso_checksum_type": "{{ user `iso_checksum_type` }}",
@@ -73,7 +73,7 @@
       "guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",
       "guest_os_type": "{{ user `virtualbox_guest_os_type` }}",
       "hard_drive_interface": "sata",
-      "headless": "{{ user `headless` }}",
+      "headless": true,
       "iso_checksum": "{{ user `iso_checksum` }}",
       "iso_checksum_type": "{{ user `iso_checksum_type` }}",
       "iso_urls": [
@@ -206,7 +206,7 @@
     "disk_size": "65536",
     "docker": "false",
     "ftp_proxy": "{{env `ftp_proxy`}}",
-    "headless": "",
+    "headless": "true",
     "http_proxy": "{{env `http_proxy`}}",
     "https_proxy": "{{env `https_proxy`}}",
     "install_vagrant_key": "true",
``` 
This works, basically setting headless: true instead of headless: "true" works for me.

**Comment by ybizeul** [comment]
I have the same problem, but it seems so stupid I'm wondering what I'm missing :

Packer just killed the installer because the VM takes too much time to install... The installation is currently running when Packer decides to stop and timeout.

Where do I configure a different timeout value?

```
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: http://cdimage.debian.org/debian-cd/8.5.0/amd64/iso-cd/debian-8.5.0-amd64-netinst.iso
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Creating additional hard drives...
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8990
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Waiting 10s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...
==> vmware-iso: Timeout waiting for SSH.
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Timeout waiting for SSH.
```

Template file :
```
{
  "builders": [
    {
      "type": "vmware-iso",
      "iso_url": "http://cdimage.debian.org/debian-cd/8.5.0/amd64/iso-cd/debian-8.5.0-amd64-netinst.iso",
      "iso_checksum": "3e1b9029a0cf188730646c379d15073f",
      "iso_checksum_type": "md5",
      "ssh_username": "root",
      "shutdown_command": "shutdown -P now",
      "disk_size":7168,
      "disk_type_id": 0,
      "disk_additional_size": [ 204800 ],
	  "http_directory": "./",
	  "boot_command": [
	  "<tab><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>priority=critical debian-installer/locale=en_US keyboard-configuration/xkb-keymap=us auto url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<enter>"
	  ]
    }
  ]
} 
```

**Comment by jared-wilkinson** [comment]
Anywhere in the builders section should work but right under "ssh_username" : "root" would probably be a good place.

**Comment by ybizeul** [comment]
You lost me :-) What are you answering to?

**Comment by jared-wilkinson** [comment]
Sorry, i was answering where to put the timeout value. It goes in the builder's section. I was just saying you can put it right under the line with your ssh username. I am on my phone so I can't copy your code block but under "ssh_username" : "root" just add:

"ssh_timeout" : "10000"

The 10000 is seconds Packer will wait for ssh to become available so set it to however many seconds you need. 

Hope that is clearer.

**Comment by ybizeul** [comment]
Oh boy... I'm ashamed... The answer is all over the place and I didn't see it. Ok let me try this.

**Comment by jared-wilkinson** [comment]
No worries. It's rare i get to help people with stuff like this and I overlook obvious answers all the time!

**Comment by mwhooker** [comment]
just built the benobox successfully `packer build -only=virtualbox-iso ubuntu-15.10-amd64.json` with the latest version of packer. I think this is fixed. Please open a new issue if you run into this

**Comment by Shubhamingle82396** [comment]
I still have timeout error i had also tried "ssh timeout:10000" but no luck

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
