### ISSUE TITLE
User variables are always(?) expected to be strings

### ISSUE THREAD

**Issue by mstrache** [mitchellh/packer#2510]
After updating from packer 0.7.5 to 0.8.2 (applies to 0.8.1 too) all my configuration that previously worked like charm suddenly failed with error messages like this:

> variable vm_disk_size: '' expected type 'string', got unconvertible type 'float64'

The configuration packer complains about:

``` javascript
{
  "variables": {
    "vm_disk_size": 10240,
    ...
  },
  "builders": [
    {
      "disk_size": "{{user `vm_disk_size`}}",
      ...
    }
  ]
}
```

Running `packer validate` on them succeeded as expected:

> Template validated successfully.

**Comment by cbednarski** [comment]
This change was introduced in 0.8.0 but I don't recall the reason. If you wrap these in quotes it should work. The same applies to "true" and "false" boolean values.

**Comment by mstrache** [comment]
That's sad, cause I use racker to create my configurations from modular ruby files (something that would be great if supportet by packer natively) and do some math to calculate ports and stuff.

**Comment by mattpatey** [comment]
@cbednarski Unfortunately arrays don't seem to be supported at all. An array stored as a user variable results in the following error:

```
* variable boot_command: '' expected type 'string', got unconvertible type '[]interface {}'
```

Attempting to wrap the list in quotation marks results in the validation passing, but you land up with a string when the variable is used, instead of an array. For example, storing `boot_command` as a user variable results in a literal version of the string used to define the array, commas and quotation marks included, which obviously doesn't work as a boot command.

**Comment by johnt337** [comment]
Any plans to address the support for array? We tend to use patterns like this to lookup security groups by name (so we can destroy and recreate resources indiscriminately):

``` bash
#!/bin/bash

# http://stackoverflow.com/questions/1527049/bash-join-elements-of-an-array
function join { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }

export PACKER_LOG=1
export PACKER_LOG_PATH=./packer.log

export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
export AWS_REGION=$AWS_DEFAULT_REGION

SIZE="m4.xlarge"
VPC_NAME="MyVPC Name"
SUBNET_NAME="MySubnet Name"
SG_NAMES="'MyGroup <- WINRM','MyGroup <- RDP','MyGroup VPC','MyGroup -> NAT'"
AMI=$(grep $AWS_DEFAULT_REGION ./amis.map | awk -F: '{print$2}')
VPC=$(aws ec2 describe-vpcs --filter=Name=tag-value,Values="${VPC_NAME}" | jq '.Vpcs[0].VpcId'|tr -d '"')
SUBNET=$(aws ec2 describe-subnets --filters=Name=vpc-id,Values=$VPC,Name=tag-value,Values="${SUBNET_NAME}" | jq '.Subnets[0].SubnetId' | tr -d '"')
SGS=$(aws ec2 describe-security-groups --filter=Name=tag-value,Values="${SG_NAMES}" | jq '.SecurityGroups[].GroupId' | tr -d '"')
SECURITY_GROUPS="\"$(join "\",\"" ${SGS[@]})\""

echo "Using packer log level: ${PACKER_LOG}"
echo "Using packer log: ${PACKER_LOG_PATH}"
echo "Using region: ${AWS_REGION}"
echo "Using VPC: '${VPC_NAME}': ${VPC}"
echo "Using SUBNET: '${SUBNET_NAME}': ${SUBNET}"
echo "Using AMI: ${AMI}"
echo "Using Security Groups: ${SECURITY_GROUPS}"

packer build --var region=$AWS_REGION --var vpc_id=$VPC --var subnet_id=$SUBNET --var base_ami=$AMI --var instance_type=$SIZE --var security_groups=$SECURITY_GROUPS amazon-sysprep.json
```

This tends to fall apart quickly as we have to lookup and hard code security group id values in templates.
I suppose we could pre-render the template to work around this before calling packer...

**Comment by tb3088** [comment]
I suspect this will get marked "won't fix". What IS needed, however, are datatype conversion functions (eg. bool(), int()) that convert the strings into suitable representations for in-line code like this:

{{ if bool(user `noop`) }} ... {{end}}
or
{{ if gt int(user `disk0`) 200 }} ... {{end}}

**Comment by rickard-von-essen** [comment]
This have been fixed.
