### ISSUE TITLE
user_data_file: default user not persistent

### ISSUE THREAD

**Issue by asebastian-r7** [mitchellh/packer#2524]
When creating a new AMI with a cloudinit cloud-config specifying a custom default user everything goes great until the AMI gets passed on to amazon. Amazon still creates it's own default_user (ubuntu) regardless of what I have passed in through the cloud-config. It would be nice for the cloud-config to persist so when I create instances from my AMI, I still get _my_ default user. Am I attempting the impossible?

Example config:
```txt
#cloud-config
system_info:
   default_user:
     name: cloud-user
     lock_passwd: True
     gecos: CloudUser
     groups: [adm, audio, cdrom, dialout, dip, floppy, netdev, plugdev, sudo, video]
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
```
Here is a working example of the above using the ec2 command line interface: https://alestic.com/2014/01/ec2-change-username/

**Comment by asebastian-r7** [comment]
Was able to get around this by doing the following in a shell provisioner:
```bash
cat << EOF >/etc/cloud/cloud.cfg 
#cloud-config
users:
  - default

system_info:
   default_user:
     name: cloud-user
     lock_passwd: True
     gecos: CloudUser
     groups: [adm, audio, cdrom, dialout, dip, floppy, netdev, plugdev, sudo, video]
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
EOF
```
Would still be nice if the user-data I pass in to packer persists all the way through the build pipeline. Thoughts?

**Comment by cbednarski** [comment]
I think you will want to do this when you boot the instance, e.g. using [Terraform's `user_data` field](https://terraform.io/docs/providers/aws/r/instance.html). I skimmed [the](http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-RunInstances.html) [docs](http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-RegisterImage.html) and it looks to me like `user-data` is a property of the instance, not the image.

**Comment by asebastian-r7** [comment]
Ah makes sense, closing!
