### ISSUE TITLE
validate does not work with long environment variables

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2528]
This will always fail validation, even if the environment variable is specified. To fix, shorten to e.g. `SOURCE_FILE`. I'm not sure if this is actually a bug or shell limitation or just something that needs to be documented, but likely a bug in the `validate` command.

```
{
  "variables": {
    "source":"{{env `SOURCE_FILE_WITH_AN_ENVIRONMENT_VARIABLE_THAT_IS_REALLY_LONG`}}"
  },
  "builders": [
    {
      "type":"file",
      "source":"{{ user `source` }}",
      "target":"blah.txt"
    }
  ]
}
```

**Comment by carinadigital** [comment]
Atlas uses a long environment variable name ATLAS_BASE_ARTIFACT_AWS_AMI_ID for injected AMI Artifacts into packer templates.

The long name bug means we can't validate templates, before pushing them to atlas.
