### ISSUE TITLE
Saltstack errors not triggering Packer failures

### ISSUE THREAD

**Issue by kayvonghaffari** [mitchellh/packer#2532]
I've noticed that certain SaltStack errors don't cause Packer to fail. Packer seems to continue building and ultimately creates an AMI claiming that the build was successful. 

![screen shot 2015-07-30 at 11 36 10 am](https://cloud.githubusercontent.com/assets/8127158/8993657/16ca224c-36bb-11e5-9622-85864cdc12a2.png)
![screen shot 2015-07-30 at 11 36 36 am](https://cloud.githubusercontent.com/assets/8127158/8993659/1aa5ccae-36bb-11e5-97b5-210f31c709c2.png)

**Comment by cbednarski** [comment]
Packer marks a provisioner failed if the exit code is non-zero. It looks like salt marked your runs as "Succeeded" and indicates zero failures. I think if you want this to fail in packer you'll need to tweak your salt scripts to fail the run instead.

**Comment by mafrosis** [comment]
This old issue I think can be safely closed - it's not a problem with packer but with the salt state configuration. I can assist @kayvonghaffari with fixing his state files if he's interested :)
