### ISSUE TITLE
Amazon AMI - force_deregister not working

### ISSUE THREAD

**Issue by bscott** [mitchellh/packer#2541]
When setting the param force_deregister, I get the following error:

```
1 error(s) occurred:

* Unknown configuration key: force_deregister
```

**Comment by cbednarski** [comment]
Thanks for the report! This looks like it's in [the right spot in the code](https://github.com/mitchellh/packer/blob/master/builder/amazon/common/ami_config.go#L20). I also tested this out and it seems to work for me.

```
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "us-west-2",
      "source_ami": "{{user `source_ami`}}",
      "instance_type": "t2.micro",
      "ssh_username": "ubuntu",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "ami_name":"cbednarski-2371-{{timestamp}}",
      "force_deregister":"true"
    }
  ],
```

This was added in packer `0.8.0`. Are you still using `0.7.5`?

**Comment by bscott** [comment]
@cbednarski Yes, verified I'm still on 0.7.5, I always forget to check the version. Thank you!
