### ISSUE TITLE
{{.Flavor}} seems to have no value for Parallels builder

### ISSUE THREAD

**Issue by Alaneor** [mitchellh/packer#2543]
When I specify a Parallels guest tools flavor in my json configuration, the `{{.Flavor}}` has no value when used as a template variable.

On console during build, I see:

`parallels-pvm: Uploading Parallels Tools for 'lin' to path: '/tmp/prl-tools-<no value>.iso'`

My configuration file contains the following relevant key/value pairs:

```json
{
  "type": "parallels-pvm",
  "parallels_tools_flavor": "lin",
  "parallels_tools_guest_path": "/tmp/prl-tools-{{.Flavor}}.iso"
}
```

I am using latest release version, 0.8.2. Thanks for your help!

**Comment by rickard-von-essen** [comment]
I can confirm this on master (@a5d4732f45c0d3d576437b11afac2f43862e5c32), and also in the ```parallels-iso``` builder (which uses the same code for this).

**Comment by rickard-von-essen** [comment]
I hade a hard time solving this until I realised it was only a spelling mistake. Thank you for reporting.
