### ISSUE TITLE
Templates are hard to generate automatically

### ISSUE THREAD

**Issue by psander-scalearc** [mitchellh/packer#2553]
Template parsing involves so many nested quoting conventions (single quotes, double quotes, backticks, {{ and }}, { and }, square bracket pairs, etc. etc.) that it's difficult to use macro preprocessors or other tools to generate templates automatically.  For example, there isn't a good way to strip inline comments.

Tools like M4 can perform computations that are not supported by Packer's templates, but have incompatible quoting conventions by default.  In the case of M4, new quoting conventions can be defined but the sheer number of existing conventions within the Template parser makes it difficult to come up with a new one that leaves the original source code readable.

**Comment by cbednarski** [comment]
Thanks for the feedback! Writing and reusing configs is definitely a pain point. Making configuration files more flexible and using a non-JSON data format are things we're thinking about, but we don't have a great solution right now. We've talked about using [HCL](https://github.com/hashicorp/hcl), for example, but we would need a way to convert existing packer configs to that format so we can be backwards-compatible and not have to support two config syntaxes.

Right now templates are JSON. I think the data format is fairly machine portable as a result, even though it's a pain to write by hand. To support comments you could use a format like YAML to deterministically convert to/from JSON and retain the same structure. Both JSON and the `{{ }}` template notation are implemented in the go standard library, and JSON is supported pretty much everywhere.

If you don't want to write this yourself you might like [aspring/racker](https://github.com/aspring/racker). If you want to roll your own you could use a template language like jinja, twig, handlebars, etc.
