### ISSUE TITLE
The box you attempted to add doesn't match the provider you specified.

### ISSUE THREAD

**Issue by shashanksinha89** [mitchellh/packer#2554]
Scenario: I have used packer template for image creation , used vmware-iso builder and vmware-iso post-processor to create final artifact.

When I am adding the box to vagrant, I am geting below error. I have already installed vagrant-vcloud plugin. Please help me out.

vagrant box add centos-6-6-x64-vmware.box --name test --provider=vcloud
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'test' (v0) for provider: vcloud
    box: Unpacking necessary files from: file:///vol_01/vagrant_env/centos-6-6-x64-vmware.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: vcloud
Provider of box: vmware_desktop

**Comment by rickard-von-essen** [comment]
vmware-iso builder and vagrant post processor can't create VMware vCloud boxes. vCloud is boxes are completely different from VMware desktop products.

**Comment by shashanksinha89** [comment]
Ok got your point. I am new to this but want to clear one more thing using
vagrant vcloud plugin we can push boxes to vcloud director.
I have seen couple of articles for doing this boxes were getting launched
in vcloud environment.
Or else is there any way I can use use packer to deploy machines on vcloud?

**Comment by cbednarski** [comment]
@shashanksinha89 On the deploy side people typically use Terraform. Terraform doesn't support vCloud either (see https://github.com/hashicorp/terraform/issues/102), but you might be able to find a plugin for it.

Basically:

- Packer builds the artifacts
- Vagrant runs them on your development machine
- Terraform deploys them to prod

And each tool supports plugins to add custom features like this one.

**Comment by rickard-von-essen** [comment]
The [Vagrant vCloud plugin](https://github.com/frapposelli/vagrant-vcloud) can run (*up*) VM instances on vCloud Director.

Apparently there is a third party plugin from VMware that can create a vagrant vmware vcloud box with packer. Use Packer to build VMware VM images on VMware Workstation/Fusion/ESXi/(Player) and then us [packer-post-processor-vagrant-vmware-ovf](https://github.com/gosddc/packer-post-processor-vagrant-vmware-ovf). There is a short explanation on how to use it on there Github page.

**Comment by shashanksinha89** [comment]
@rickard-von-essen Yes I'll try this out. This is work . Thanks !!

**Comment by shashanksinha89** [comment]
@cbednarski Thanks man !!!

**Comment by shashanksinha89** [comment]
@rickard-von-essen It worked like a charm :+1:
