### ISSUE TITLE
SSH timeout when provisioning across AWS regions

### ISSUE THREAD

**Issue by mmmorris1975** [mitchellh/packer#2555]
I have a build farm that runs Packer in the us-east-1 region, and I build some images out in us-west-2, and some in us-east-1.  Regions are linked via a VPN tunnel.  For instances built in the us-east-1 region (same region as build farm), I see no issues, but I see SSH timeouts when performing any builds in us-west-2.

I'm using the packer-generated security groups for my builds, which only allow access to TCP port 22.  If I modify the security group Packer creates in us-west-2 (while the builder is in the 'Waiting for SSH' status) to also allow ALL ICMP traffic, the SSH timeout issues disappear, and I can build images out in us-west-2.

I think it would be advisable to update the packer-supplied AWS security group rules to allow SSH from anywhere, and ALL ICMP from anywhere.

**Comment by cbednarski** [comment]
We can probably make this change, though ICMP is disabled by default in EC2. In the mean time you can use the `security_group_id` option to setup your own security group in advance for Packer to use.

**Comment by mmmorris1975** [comment]
Right, in the meantime, that's what I've done (SSH and ALL ICMP open to 0.0.0.0/0), and it's working as expected.  I'm going to go out on a limb and say this is somewhat of an edge case...cross-region image building in an AWS VPC environment.
