### ISSUE TITLE
amazon-ebs sudo issue

### ISSUE THREAD

**Issue by ilk** [mitchellh/packer#2558]
Packer version 8.0.2

Here is my test-json file:

```
{
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "xxx",
    "secret_key": "xxx",
    "region": "eu-central-1",
    "source_ami": "ami-02b78e1f",
    "instance_type": "t2.small",
    "ssh_username": "admin",
    "ami_name": "base-ami {{isotime| clean_ami_name}}",
    "ami_virtualization_type": "hvm",
    "run_tags": {"Name":"packerami"},
    "vpc_id": "vpc-xxx",
    "subnet_id" : "subnet-xxx"
  }],
  "provisioners": [{
    "type": "shell",
    "pause_before": "5s",
    "inline": [
      "id",
      "sudo su",
      "id"
    ]
  }]
}
```

and this is the output from packer:

```
    amazon-ebs: uid=1000(admin) gid=1000(admin) groups=1000(admin),4(adm),20(dialout),24(cdrom),25(floppy),29(audio),30(dip),44(video),46(plugdev)
    amazon-ebs: sudo: unable to resolve host ip-172-42-1-162
    amazon-ebs: uid=1000(admin) gid=1000(admin) groups=1000(admin),4(adm),20(dialout),24(cdrom),25(floppy),29(audio),30(dip),44(video),46(plugdev)
```

Why packer can't become root? Its an debian base image, the default user is admin and a password is not required. 

When I'm testing sudo apt-get install w3m -y for example it works (sudo: unable to resolve host ip-172-42-1-162) is also shown but it works.

**Comment by cbednarski** [comment]
It looks to me like your sudo action is successful since there is no error from `sudo su`. However, each shell provisioner is executed in its own shell so you will need to `sudo` before each command.

If sudo does not work you may need to [swap the pty setting](https://packer.io/docs/templates/communicator.html#ssh_pty). This is a common issue with CentOS / RHEL but not Debian. You can [read more about this here](https://github.com/mitchellh/packer/issues/1804).

**Comment by ilk** [comment]
But in the docs (https://www.packer.io/docs/provisioners/shell.html) it's written:

> inline (array of strings) - This is an array of commands to execute. The commands are concatenated by  newlines and turned into a single file, so they are all executed within the same context. This allows you to change directories in one command and use something in the directory in the next and so on. Inline  scripts are the easiest way to pull off simple tasks within the machine.

**Comment by rickard-von-essen** [comment]
The shell script:
```bash
id
sudo su
id
```

Works perfectly fine. But ```sudo``` executes the following command (```su```) under _root_ privileges. That doesn't mean the rest of the script, that's not how shell scripts works.

 This shell script should give you what you expect and work fine:
```bash
id
sudo id
```

For a more in depth guide see [Advanced Bash-Scripting Guide](http://www.tldp.org/LDP/abs/html/)

**Comment by cbednarski** [comment]
Poor explanation on my part. Thanks @rickard-von-essen
