### ISSUE TITLE
Variable number of security groups for aws-elb builder

### ISSUE THREAD

**Issue by usmanismail** [mitchellh/packer#2559]
We have a use case where we want to use the same build profile in two different environments. In one environment  we need to attach 1 security group to the AMI builder instance and the other environment requires 3 because of our VPN / IP Tunneling configuration. However, there is no way I can find to make the number of security groups variable. Short of using two almost identical templates I can't find anyway of setting up packer to build our AMIs. 

Is it possible to set an OnlyIF style tag inside the builder section? or have some semantics for selecting builder configuration based on input parameters. 

Alternatively we could (admittedly hacky) solution is to skip empty string security groups ids in the list of security groups.

**Comment by mwhooker** [comment]
I assume you mean the amazon-ebs builder. We support multiple security groups now
