### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by darrenhaken** [mitchellh/packer#2562]
We have been battling with an issue with RackSpace around SSH key generation. 
It looks like SSH keys returned via RackSpace are causing errors within Packer/golang when parsing the SSH key byte array. 

To get around this we've been using a new feature in the OpenStack builder that allows us to defined & supply an SSH key rather than relying on the one generated by RackSpace. 

At the moment we've had to build Packer from source as it's not in the latest release.
I was wondering when you were planning to make the next release?

**Comment by cbednarski** [comment]
`0.8.3` will be out in the next few days.
