### ISSUE TITLE
amazon-ebs volume_size is unknown

### ISSUE THREAD

**Issue by matthieu-ravey** [mitchellh/packer#2563]
Here is the builder part of my configuration:

```json
"builders": [{
    "type": "amazon-ebs",
    "region": "us-east-1",
    "source_ami": "ami-3d73d356",
    "instance_type": "m3.large",
    "ssh_username": "core",
    "ami_name": "temp",
    "volume_size": 20
  }]
```

when I validate this here is the error I get: `unknown configuration key: "volume_size"` I tried to use a string instead of an integer by I still get the same issue.

**Comment by matthieu-ravey** [comment]
I've realized that you need to put it in a "ami_block_device_mappings" array. So I've done the following now:
```json
"builders": [{
    "type": "amazon-ebs",
    "region": "us-east-1",
    "source_ami": "ami-3d73d356",
    "instance_type": "m3.large",
    "ssh_username": "core",
    "ami_block_device_mappings": [{
      "device_name": "/dev/xvda",
      "snapshot_id": "snap-6da4d2fe",
      "volume_type": "standard",
      "volume_size": 20
    }]
  }]
```

It works but it will change the default size for the AMI that will be created. What I'd like to do is change the disk size of the instance that is launched to create the AMI.

**Comment by matthieu-ravey** [comment]
I did not see that you need to wrap the `volume_size` option in the `launch_block_device_mappings` block. I did that and it worked. I'm sorry, you can close the issue.

**Comment by cbednarski** [comment]
:+1: Thanks for following up!

**Comment by dhdanno** [comment]
This was not clear in the documentation https://www.packer.io/docs/builders/amazon-ebs.html

**Comment by rickard-von-essen** [comment]
The indentation have been fixed on master and the site will be updated when next release is done.
