### ISSUE TITLE
[Packer 0.8.2] Cannot provide AWS_ACCESS_KEY_ID as an environment variable to packer script

### ISSUE THREAD

**Issue by siddhuwarrier** [mitchellh/packer#2570]
Packer version: 0.8.2

I have a Packer script with the following lines:

```
   "variables": {
    "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
  ...},
"builders": [{
...
    "access_key": "{{user `aws_access_key`}}",
}]
```

I have the AWS_ACCESS_KEY_ID variable set. When I run `packer build` without the var aws_access_key set, I get the following error:

```
$ packer build myjson.json
==> amazon-ebs: Error querying AMI: AuthFailure: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'MYVALIDACCESSKEY'
```

`MYVALIDACCESSKEY` is a valid access key.

**Comment by siddhuwarrier** [comment]
To note: if I were to unset AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and use the credentials in ~/.aws/credentials, configured using the aws command-line tools, things work just fine.

**Comment by cbednarski** [comment]
I think this error is from the AWS API, not from packer. Do you have your `access_key_id` and `secret_access_key` values swapped? I think `access_key_id` usually starts with `AKI` and only the secret part should have slashes in it.

**Comment by siddhuwarrier** [comment]
Hi




Thanks for getting back to me. I did think this might be the problem, so I even tried swapping them around to see if that might fix it. But no luck. :-(



—

**Comment by cbednarski** [comment]
Can you check that your credentials are set correctly via `env`?

    $ env | grep AWS
    AWS_ACCESS_KEY_ID=AKIA....
    AWS_SECRET_ACCESS_KEY=....

This minimal config works for me with the packer `0.8.2` release and packer built from master:

```
{
  "variables": {
    "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
    "aws_secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
    "source_ami": "ami-5189a661"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "us-west-2",
      "source_ami": "{{user `source_ami`}}",
      "instance_type": "t2.micro",
      "ssh_username": "ubuntu",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "ami_name":"cbednarski-{{timestamp}}"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": ["exit 1"]
    }
  ]
}
```

Can you show me how you're invoking packer? E.g. `packer build aws.json`. Also what OS are you running this from?

**Comment by vsheffer** [comment]
I am using 0.8.3 and am experiencing the same thing as **siddhuwarrier**.  In addition, his suggestion of using the credentials in .aws/credentials works as well.

I'm invoking Packer with the following command line:
```
packer build -only=amazon-ebs packer.json
```

**Comment by siddhuwarrier** [comment]
Hi,

Terribly sorry, I somehow missed this in my inbox. Yes, my env is set
correctly, as vsheffer was pointing out.

I was running Packer on OS X 10.10 Yosemite.

Cheers,

Siddhu

On 8 August 2015 at 00:31, Chris Bednarski <notifications@github.com> wrote:

> Can you check that your credentials are set correctly via env?
>
> $ env | grep AWS
> AWS_ACCESS_KEY_ID=AKIA....
> AWS_SECRET_ACCESS_KEY=....
>
> This minimal config works for me with the packer 0.8.2 release and packer
> built from master:
>
> {
>   "variables": {
>     "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
>     "aws_secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
>     "source_ami": "ami-5189a661"
>   },
>   "builders": [
>     {
>       "type": "amazon-ebs",
>       "region": "us-west-2",
>       "source_ami": "{{user `source_ami`}}",
>       "instance_type": "t2.micro",
>       "ssh_username": "ubuntu",
>       "access_key": "{{user `aws_access_key`}}",
>       "secret_key": "{{user `aws_secret_key`}}",
>       "ami_name":"cbednarski-{{timestamp}}"
>     }
>   ],
>   "provisioners": [
>     {
>       "type": "shell",
>       "inline": ["exit 1"]
>     }
>   ]
> }
>
> Can you show me how you're invoking packer? E.g. packer build aws.json.
> Also what OS are you running this from?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/packer/issues/2570#issuecomment-128858801>.
>



-- 
Website: http://www.siddhuw.info
Source code repository: http://www.github.com/siddhuwarrier

**Comment by mwhooker** [comment]
this should be working now, and we will probably rework how this whole system works after 1.0
