### ISSUE TITLE
Unable to extract .zip produced by 'Compress' post-processor

### ISSUE THREAD

**Issue by dsudduth** [mitchellh/packer#2572]
Hello,

I am unable to extract a **.zip** file produced by the **Compress** post-processor.  The error received states that it is not a valid archive file. I am using Packer along with Packer-Windows on Windows 2012 R2.
## Snippet from Win_7.json

``` json
{
      "type": "compress",
      "only": ["vmware-iso"],
      "keep_input_artifact": false,
      "output": "win_7.zip"
    }
```
## Command Executed

To run Packer, I am executing `packer build -only vmware-iso win_7.json` via an elevated Poweshell prompt.

Please let me know if I can provide any further details that may assist in investigating the issue.

**Comment by dsudduth** [comment]
<img width="505" alt="ds-dev" src="https://cloud.githubusercontent.com/assets/1160973/9152782/52a03414-3deb-11e5-96c9-060350baaf40.png">

**Comment by cbednarski** [comment]
Thanks for the report. Which version of packer are you using? `packer version` to see.

**Comment by dsudduth** [comment]
@cbednarski  - Thanks for following up.  I'm running Packer `v0.8.2`.  This particular version was installed via Chocolatey.

**Comment by mwhooker** [comment]
It's been a few years since this was reported. There have been a couple major changed to go since this was opened, and I suspect it's been fixed.

If this is still an issue, please open a new ticket with a complete json that will reproduce it.

**Comment by mwhooker** [comment]
It's been a few years since this was reported. There have been a couple major changed to go since this was opened, and I suspect it's been fixed.

If this is still an issue, please open a new ticket with a complete json that will reproduce it.
