### ISSUE TITLE
packer 0.8.3 vmware-iso builder cannot read the virtual machine configuration file

### ISSUE THREAD

**Issue by skares** [mitchellh/packer#2574]
Hi,

with packer 0.8.3 vmware-iso builds failed. I always get  a "cannot read the virtual machine configuration file" and die build stops. 
When i use the 0.8.2 module it works. Any Ideas ?

best regards

Sven

**Comment by skares** [comment]
I captured the vmx file which is created and which is not readable. I tried to open with vmware workstation 11 and the programm told me that the file is  "corrupted" 

.encoding = "UTF-8"
RemoteDisplay.vnc.enabled = "false"
RemoteDisplay.vnc.port = "5900"
bios.bootOrder = "hdd,CDROM"
checkpoint.vmState = ""
cleanShutdown = "TRUE"
config.version = "8"
displayName = "packer-vmware-iso"
ehci.pciSlotNumber = "34"
ehci.present = "TRUE"
ethernet0.addressType = "generated"
ethernet0.bsdName = "en0"
ethernet0.connectionType = "nat"
ethernet0.displayName = "Ethernet"
ethernet0.linkStatePropagation.enable = "FALSE"
ethernet0.pciSlotNumber = "33"
ethernet0.present = "TRUE"
ethernet0.virtualDev = "e1000"
ethernet0.wakeOnPcktRcv = "FALSE"
extendedConfigFile = "packer-vmware-iso.vmxf"
floppy0.filename = "C:\Users\skares\AppData\Local\Temp\packer189376687"
floppy0.filetype = "file"
floppy0.present = "TRUE"
guestOS = "windows8srv-64"
gui.fullScreenAtPowerOn = "FALSE"
gui.viewModeAtPowerOn = "windowed"
hgfs.linkRootShare = "TRUE"
hgfs.mapRootShare = "TRUE"
ide1:0.deviceType = "cdrom-image"
ide1:0.fileName = "C:/data/Scripts/Projekte/w2012r2-packer/packer-windows/iso/en_windows_server_2012_r2_with_update_x64_dvd_4065220.iso"
ide1:0.present = "TRUE"
isolation.tools.hgfs.disable = "FALSE"
memsize = "2048"
msg.autoanswer = "true"
numvcpus = "2"
nvram = "packer-vmware-iso.nvram"
pciBridge0.pciSlotNumber = "17"
pciBridge0.present = "TRUE"
pciBridge4.functions = "8"
pciBridge4.pciSlotNumber = "21"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge5.pciSlotNumber = "22"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge6.pciSlotNumber = "23"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
pciBridge7.pciSlotNumber = "24"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
powerType.powerOff = "soft"
powerType.powerOn = "soft"
powerType.reset = "soft"
powerType.suspend = "soft"
proxyApps.publishToHost = "FALSE"
remotedisplay.vnc.enabled = "TRUE"
remotedisplay.vnc.port = "5900"
replay.filename = ""
replay.supported = "FALSE"
scsi0.pciSlotNumber = "16"
scsi0.present = "TRUE"
scsi0.virtualDev = "lsisas1068"
scsi0:0.fileName = "disk.vmdk"
scsi0:0.present = "TRUE"
scsi0:0.redo = ""
sound.startConnected = "FALSE"
tools.syncTime = "TRUE"
tools.upgrade.policy = "upgradeAtPowerCycle"
usb.pciSlotNumber = "32"
usb.present = "FALSE"
uuid.action = "create"
virtualHW.productCompatibility = "hosted"
virtualHW.version = "9"
vmci0.id = "1861462627"
vmci0.pciSlotNumber = "35"
vmci0.present = "TRUE"
vmotion.checkpointFBSize = "65536000"

**Comment by cbednarski** [comment]
Thanks for the report! The change we made here was to CamelCasing some of the configuration options. Previously they were generated in lowercase so they were ignored by VMware. I tested this with VMware fusion. I doubt that workstation uses a different format, but maybe there are some additional configs in your VMX that I did not have in mine.

**Comment by cbednarski** [comment]
If you have a copy of your VMX from 0.8.2 (or can generate another one) can you share this so I can compare them with a diff tool?

**Comment by trodemaster** [comment]
I just ran into this issue as well. It appears that packer just doesn't create the vmx or the vm folder when I have my vmx data setup. See this gist for example of the packer vmx_data https://gist.github.com/trodemaster/027d9ff3da2d109957a6

Here is what that config looks like built into a vmx file. 
https://gist.github.com/trodemaster/d374952a6bcf87ba570b

**Comment by cbednarski** [comment]
To update this here, there was an unintended BC break as a result of #2309, which tries to support the `virtualSSD` option. In short, some VMX entries are case-sensitive (`virtualSSD` is one of them) so we removed the code that `toLowercase()`s all of the options, which is likely what's causing this to break. I'm going to revert this and release a patched version that does this more selectively, so if this is breaking your builds please use 0.8.2 and keep your eyes open for 0.8.4. Sorry about the inconvenience!

**Comment by cbednarski** [comment]
@trodemaster Thanks for posting your vmx-data. I was able to verify that reverting the toLowercase changes fixes this issue. I'll push out the new version in a few minutes.

I'd like to add this to the acceptance suite later but I'm going to get the fix out now since 0.8.3 is busted.

**Comment by cbednarski** [comment]
This is released (actually as 0.8.5 -- 0.8.4 was skipped).
