### ISSUE TITLE
Changelog for 0.8.3

### ISSUE THREAD

**Issue by WyseNynja** [mitchellh/packer#2575]
I noticed that 0.8.3 is available at packer.io, but the CHANGELOG has 0.8.2 as the latest. Am I missing something?

**Comment by cbednarski** [comment]
Nope I goofed. I'll be adding this shortly.

**Comment by tersmitten** [comment]
Thanks

**Comment by cbednarski** [comment]
This was added in 3a6cac97dd99aecbda7a641b71d1066aa40eb756
