### ISSUE TITLE
Packer jumps to next provisioner after reboot with inline-shell provisioner

### ISSUE THREAD

**Issue by hsanjuan** [mitchellh/packer#2580]
This might be related to #2216 . Basically, something like

``` shell
# reboot.sh
ip link set down eth0
reboot
sleep 10
```

would work on a regular script-based shell provisioner, but not when using it inline.

In the first case, it correctly runs the next script file to be processed after the reboot. In the inline-case, it reboots but forgets about whatever lines were left and jumps to the next provisioner.

**Comment by cbednarski** [comment]
Thanks for the report. I suspect there is an idiosyncrasy with inline that makes this execute differently.

In the mean time, you might be able to work around this using `"pause_before": "10s"` on the following provisioner, as documented on the [provisioners page](https://packer.io/docs/templates/provisioners.html).

**Comment by mwhooker** [comment]
sorry, there's no way to pick back up in the middle of an inline script. I recommend creating multiple shell provisioners
