### ISSUE TITLE
ui error: ==> vmware-iso: Error starting VM: VMware error: Error: The operation was canceled

### ISSUE THREAD

**Issue by shashanksinha89** [mitchellh/packer#2586]
I am getting this error when I am trying to create a box using packer.I am using below products

VMware-Player-6.0.6-2700073.x86_64.bundle
VMware-VIX-1.13.6-2700073.x86_64.bundle

![image](https://cloud.githubusercontent.com/assets/13620565/9217610/6991dab6-40e7-11e5-8b76-84cccff6eddb.png)

**Comment by rickard-von-essen** [comment]
Please rerun with [debug](http://packer.io/docs/other/debugging.html) enabled and gist the log and your config json.
