### ISSUE TITLE
file provisioner and downloading multiple files

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#2588]
Now file provisioner able to download file one by one. But if i want to download /boot/*
it fails , because ssh communicator interface for download get io.Writer, but scp sends filename on the stream.
How to fix this? Add new method like DownloadMultiple and use it, or modify Download method to get params like src, dst path?

**Comment by cbednarski** [comment]
Yes I think we need to expand the communicator interface to support `DownloadDir`, which mirrors `UploadDir`. This will allow us to download a directory all at once.

I think for now the easiest way to do this is to create a tar inside the VM / container and then you only need to download one file.

**Comment by vtolstov** [comment]
@cbednarski i create pr for downloaddir to ssh communicator #2618
