### ISSUE TITLE
Add config option to override builderid in artifice

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2591]
This will allow us to use artifice in conjunction with some of the docker post-processors.
- [ ] Implement configuration override
- [ ] Add docs / examples for use with different docker post-processors

/cc @vtolstov

**Comment by vtolstov** [comment]
i think that changing builder Id not needed, we need to change all stuff to allow artifacts from artifice post-processor

**Comment by cbednarski** [comment]
That's a great point @vtolstov. I think this is probably less complicated for the user since it should "just work" in most cases.
