### ISSUE TITLE
0.8.5 - QEMU builder drops the .qcow2 file extension

### ISSUE THREAD

**Issue by borzwazie** [mitchellh/packer#2601]
We recently upgraded from 0.7.5 to 0.8.5. Some of our Packer builds use the QEMU builder to create qcow2 images.

As of 0.8.5, the images are still created, but the .qcow2 file extension is dropped. For example, our normal image name looks like this:

"vm_name": "appname.appversion.kvm"

In 0.7.5, this would result in a qcow image with the following name:

appname.appversion.kvm.qcow2

In 0.8.5, we get a qcow image with the following name:

appname.appversion.kvm

It still seems to be a correct qcow image, it just drops the file extension.

Tested on Ubuntu 14.04 with separate /opt/packer_0.7.5 and /opt/packer_0.8.5 directories, symlinked to "/opt/packer".

**Comment by borzwazie** [comment]
Relevant .json snippet from the build:

    "builders":
    [
        {
                "name": "kvm",
                "vm_name": "{{user `vm_name`}}.kvm",
                "type": "qemu",
                "format": "qcow2",
                "accelerator": "kvm",
                "qemu_binary": "qemu-system-x86_64",
                "qemuargs": [
                                [ "-m", "2048M" ],
                                [ "-smp", "1" ]
                ],

**Comment by vtolstov** [comment]
This is expected, if you need ext please add it to file name
14 авг. 2015 г. 16:59 пользователь "borzwazie" <notifications@github.com>
написал:

**Comment by borzwazie** [comment]
The QEMU builder docs say differently, and it behaved the way the docs described in 0.7.5:

https://www.packer.io/docs/builders/qemu.html

vm_name (string) - This is the name of the image (QCOW2 or IMG) file for the new virtual machine, without the file extension. By default this is "packer-BUILDNAME", where "BUILDNAME" is the name of the build.

I will note that the VMWare builder correctly attaches the .vmdk extension to the vm_name when creating files.

**Comment by cbednarski** [comment]
Thanks for the report. I don't know what the correct functionality here is -- it seems like there is a discrepancy between the docs and the current behavior, at least. I'll take a look to see what changed here.

**Comment by vtolstov** [comment]
This is changed by my patch,because I need identical file names not
depended to image format. I think we need fix docs for this.
14 авг. 2015 г. 22:48 пользователь "Chris Bednarski" <
notifications@github.com> написал:

**Comment by borzwazie** [comment]
Are you changing this for all the builders? Or is this just an exception we'll have to remember for QEMU?
