### ISSUE TITLE
vbox-iso: iso_interface causes boot to fail

### ISSUE THREAD

**Issue by noahjl** [mitchellh/packer#2602]
Team,

When using virtualbox-iso build type if you set iso_interface to sata and have the guest_additions_mode set to attach virtualbox will fail to boot. It looks like it attempts to boot the ide iso first (guest additions in this case). 

[Gist with template, log, and screenshot](https://gist.github.com/noahjl/75e941aecf0f1af94536)

OS is Fedora 22, and VirtualBox 5, no extensions. 
Packer 0.8.5

**Comment by styro** [comment]
Yes I just ran into this. It would be nice if the `step_attach_guest_additions.go` module picked up on the `iso_interface` setting like `step_attach_iso.go` does instead of hard coding an IDE controller.

If nobody beats me to this, it might become my first reason to learn some Go :)

**Comment by mwhooker** [comment]
hmm, would be happy to see a PR that resolves this, but I fear it may be an upstream issue. I tried changing the device/port of the guest additions ISO and didn't have any success. May be related to https://www.virtualbox.org/ticket/6979

However, this is not something we're targeting for 1.0, so I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
