### ISSUE TITLE
File provisioner doesn't respect destination as directory

### ISSUE THREAD

**Issue by mattolenik** [mitchellh/packer#2604]
It would seem impossible to copy a file into a directory without specifying the full destination file name. E.g.:

```
{
  "type": "file",
  "source": "{{ user `some_passed_in_path`}}",
  "destination": "/root/"
}
```

I did this and it ended up copying the file to /root/root! I don't know the exact name of the file, as it is a versioned file that's passed into the template, so I can't specify the full destination path without passing in _another_ variable. This seems very strange and is contrary to every file copy convention I'm familiar with.

**Comment by cbednarski** [comment]
> I don't know the exact name of the file, as it is a versioned file that's passed into the template, so I can't specify the full destination path without passing in another variable.

The `source` and `destination` field can be named independently. In other words, you can always use `"destination": "/tmp/myfile"` even if `source` is `~/icecream1234` or `~/icecream1236`. Behind the scenes this data might flow over a variety of transport mechanisms so we don't necessarily adhere to the semantics of any particular transport.

If you don't want to name the file you might want to [upload the directory instead](https://packer.io/docs/provisioners/file.html). Something like:

```
/tmp/files/
└── lfkdsjfaroiauweradsfsd
```

```
{
  "type": "file",
  "source": "/tmp/files/",
  "destination": "/root/"
}
```

`lfkdsjfaroiauweradsfsd` will be copied to `/root/lfkdsjfaroiauweradsfsd` even though you don't specify the name.

**Comment by mattolenik** [comment]
Using a constant file name might work, but in other scenarios it doesn't if the consumer of the file expects the name to be intact. Why would the variety of transports affect how the file is placed, though? Why can't Packer simply look at the basename of the file, and save that if the destination ends in a trailing slash?

**Comment by mwhooker** [comment]
I think this behavior has changed since you opened this. You should be able to upload a passed in file to a directory. please open a new ticket if this is still a problem for you
