### ISSUE TITLE
Support of yaml for packer var files

### ISSUE THREAD

**Issue by aacebedo** [mitchellh/packer#2609]
Packer variables files (passed through -var-file) only supports json. 
Is it possible to add yaml support (as json is a subset of the latter) ?

**Comment by cbednarski** [comment]
Thanks for opening an issue. We don't currently support yaml but it's possible to use another tool to convert yaml to json as part of your build process. I've also considered using yaml because it support comments, so I'm going to leave this open for feedback.

Related: https://github.com/mitchellh/packer/issues/1768

**Comment by aacebedo** [comment]
Hi !
Thank you for this answer. 
I will wait for the implementation as in my case, converting the yaml to json won't be efficient.

Regards.

**Comment by paulvollmer** [comment]
+1 for `yaml` var-files

**Comment by Otann** [comment]
:+1: for yaml configuration

**Comment by rbishop** [comment]
I'd prefer to avoid yaml. While it's nice that Ansible uses yaml I think it would be better if Packer used HCL to be consistent with other HashiCorp tools.

**Comment by aacebedo** [comment]
According to doc, HCL is compatible with JSON. As YAML is a superset of JSON it may be possible to implement the config files a way that it would be compatible with the 3 approaches?

**Comment by Otann** [comment]
@rbishop YAML is not a different language, just another form of same data structures, why would it bring inconsistencies?

**Comment by rbishop** [comment]
It would be inconsistent if Packer used Yaml and Terraform used HCL. I find HCL to be much nicer than Yaml. The Yaml spec and various parsers are a mess.

**Comment by necrose99** [comment]
yeah I'm Dyslexic ,  I for one hate the json format , reading is one thing trying to twerk it is another. 
even if it's transparent to the users json/yaml yaml/json i/o is doable. and gems perl's py's node-js's you name it.  json isnt bad but give a 45 mins or so it as the "code walks the page" ({[, the more c++ like hell-nested the worse it is.  and then look away try n shake off the dyslexia scraping back in eyes head just begins to feel like lava in my eyes.... 

yaml or the like dont hurt my eyes. , bash isnt so nested to death or even some python-ish like ... 
however if yaml is used needs a good Parser 

might have an [ Atom.io ] drop down list for us json chalanged people.

**Comment by jessechahal** [comment]
personally I find yaml less readable and even more annoying to edit then JSON. But native comment support is worth the headache. I agree with @aacebedo in that it would be nice maybe to add support to markup languages that act as a superset to JSON. I haven't used HCL but it can't be worse then JSON or YAML....right????

**Comment by cbednarski** [comment]
Hey folks! Thanks for the feedback here. As several of you have noted the primary benefit with YAML is comments but benefits stop there. I think YAML will cause more confusion and maintenance in the long run so I'm not planning to do this. We are planning to do HCL in the long run which should resolve a lot of the pain points around JSON. In the mean time, feel free to use a pre-processing tool to make this stuff easier for you!

**Comment by vtolstov** [comment]
=( I'm not agree with closing this issue. HCL we waiting is more then half of year, but it not comes to packer, also yaml have binding for all languages instead of hcl.

**Comment by aacebedo** [comment]
I Don't really understand why YAML would not be able to fulfill the requirements HCL is trying to.
YAML is not so hard to understand, it has been especially designed to be human readable. Having a new language will force us to use new bindings and to parse from a standard to another. IMHO It is an additional complexity with not so much benefits.

**Comment by necrose99** [comment]
I'd Settle for Python or etc scipt/s YAML to HCL or JSON , and Validation prior to import to packer. 
simple script that makes sure its valid for packer , ie just a callable support script  if anyone cares to 

contribute great. ie a packer plug-in ..., and anyone whom makes a plug in can or scripts can. 
an I/O plugin would allow this without being a nuisance to the packer team..  and any 3rd party could simply contribute.  or any other extensions to add custom scriptable support to packer. 

ether that or A 'GUI' editor php-script  etc , that produces nice clean JSON/HCL were the like of me would have to work very hear to break it.  might also be another nice contribution.

**Comment by arehmandev** [comment]
I've had success using the JSON to YAML converted in Atom, modifying what I wish then reconverting back to JSON. Would be ideal to just accept both JSON and YAML format like Kube does

**Comment by psprowls** [comment]
Comments.

**Comment by darkn3rd** [comment]
JSON is painful, YAML would be great, easier to read, especially for any multi-line embedded shell scripts.

**Comment by rickard-von-essen** [comment]
See https://github.com/hashicorp/packer/issues/1768#issuecomment-272921740
