### ISSUE TITLE
user_data string must be base64 encoded in 0.8.5

### ISSUE THREAD

**Issue by eikenb** [mitchellh/packer#2616]
In 0.7.5 I had a config for an Amazon EC2 EBS builder which contained a 'user_data' field. The field contained a simple one line string. After upgrading to 0.8.5 it now raises this error...

==> aws: Error launching source instance: InvalidParameterValue: Invalid BASE64 encoding of user data
==> aws: 	status code: 400, request id: []

If I manually base64 the string and put that in the user_data field it works.

Looks like whatever base64 encoded the user_data field broke.

**Comment by cbednarski** [comment]
Thanks for the report. There is a PR open for this here #2539 that I think should fix this. Can you try it out and let me know?
