### ISSUE TITLE
Running packer push from Windows command line results in "authentication failed"

### ISSUE THREAD

**Issue by noilly** [mitchellh/packer#2617]
I am following the tutorial on the Atlas website on how to build Vagrant boxes with Packer and Atlas. Having set the ATLAS_TOKEN environment variable and successfully verifying, the `packer push` command does not authenticate. I have also tried adding the `-token` flag without success.

I am running this in a Windows 8 machine. I have had the same results with versions 0.8.2 and 0.8.5.

**Comment by cbednarski** [comment]
Heyo! Sorry about the delay on this. I don't have a windows 8 vm on hand to test this right now. Since this is related to Atlas can you reach out to support@hashicorp.com? Thanks!
