### ISSUE TITLE
Make docker-import postprocessor show docker stdout/stderr output

### ISSUE THREAD

**Issue by sanmai-NL** [mitchellh/packer#2620]
My import failed, and `packer` emitted this last part of the log:

```
==> docker: Running post-processor: docker-import
    docker (docker-import): Importing image: Container
    docker (docker-import): Repository: docker.clarin.eu/alpine__python_3:0.99
Build 'docker' errored: 1 error(s) occurred:

* Post-processor failed: Error importing container: exit status 1

==> Some builds didn't complete successfully and had errors:
--> docker: 1 error(s) occurred:

* Post-processor failed: Error importing container: exit status 1

==> Builds finished but no artifacts were created.
```

In the previous, no clue is given by the docker-import postprocessor/packer as to why the import failed.

After I issued the import command (the command line invoked by packer based on the source code), `docker` gave me the following helpful error message:

```
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
```

My feature request is to ensure that all output on stdout/stderr emitted by Docker will be emitted by Packer as well.

**Comment by gsaslis** [comment]
👍  

Agree this would be helpful, as I ran into the same issue...
 @sanmai-NL thanks dude!

**Comment by evanstachowiak** [comment]
Packer also returns 0 in this scenario. I think when docker errors, Packer should emit that error as well when exiting.
