### ISSUE TITLE
Document the environment variable "CHECKPOINT_DISABLE" and rename it to "PACKER_CHECKPOINT_DISABLE" for consistency

### ISSUE THREAD

**Issue by tylert** [mitchellh/packer#2622]
It seems that the "CHECKPOINT_DISABLE" environment variable should perhaps be renamed to "PACKER_CHECKPOINT_DISABLE" to make it more consistent with other values from https://packer.io/docs/other/environmental-variables.html.

This variable should perhaps also be added to that page of the documentation, perhaps, along with some background links such as:

* https://checkpoint.hashicorp.com/
* https://github.com/hashicorp/go-checkpoint
* https://docs.vagrantup.com/v2/other/environmental-variables.html (for comparison)

**Comment by cbednarski** [comment]
Hm. I agree that we should document this but I also think this is easier if everything uses the same environment variable. Going to chat with some other folks on this one.

**Comment by cbednarski** [comment]
This should be `CHECKPOINT_DISABLE` for all of the HashiCorp tools so you only have to set it once. There is a PR open to [update the vagrant docs](https://github.com/mitchellh/vagrant/pull/6166).

**Comment by tylert** [comment]
Excellent, thanks!
