### ISSUE TITLE
DigitalOcean builder does not output metadata

### ISSUE THREAD

**Issue by sethvargo** [mitchellh/packer#2625]
The DO builder does not output any metadata (such as the region), which is important for Atlas. 

DO doesn't let you spin up a droplet in nyc3 that was created in nyc1, for example.

**Comment by szegoio** [comment]
+1
Right now I can't create a DO image using Packer, then provision from it via terraform (or anything else).

**Comment by mwhooker** [comment]
It looks like we already capture the above https://github.com/mitchellh/packer/blob/master/builder/digitalocean/artifact.go#L12-L19

Please reopen if this is still an issue
