### ISSUE TITLE
Packer randomly reboots FreeBSD machine during middle of shell provisioning

### ISSUE THREAD

**Issue by Vodurden** [mitchellh/packer#2631]
When building a FreeBSD machine on Windows 7 using the VirtualBox provisioning on packer 0.8.5 packer seems to decide to shutdown the machine during the middle of executing a script. Sometimes this occurs early in the process, sometimes later and occasionally it doesn't occur at all.

Running the process with the `-debug` flag seems to prevent the issue from occurring. After the shutdown packer seems to believe that machine was correctly shutdown and will package it into a box. This issue also seems to occur both with and without the vagrant post-provisioner.

To reproduce: Run `packer build freebsd.json` in this folder: https://github.com/Vodurden/devbox/tree/freebsd-packer-random-reboot/boxes/FreeBSD-10.1-RELEASE

The issue also occurs when running `packer build devbox.json` in this folder: https://github.com/Vodurden/devbox/tree/freebsd-packer-random-reboot/boxes/DevBox (please ignore the Vagrantfile - it was an attempt to work around this issue).

Here is a gist from running `PACKER_LOG=1 packer build freebsd.json` that exhibits the issue: https://gist.github.com/Vodurden/2740b2d9c8a948cffe50

Please let me know if there's any additional information I can provide.

**Comment by cbednarski** [comment]
Thanks for the report! I looked at the log and I don't see anything aberrant in packer's behavior. This could be a race condition, which is hard to spot, but is consistent with `-debug` making the problem go away. It could also be something weird in your provisioning scripts where the pause introduced by `-debug` hides the problem.

I glanced at your freebsd configs but it looks like the log is from your devbox build; I haven't looked through those scripts yet.

**Comment by Vodurden** [comment]
I might have misremebered but I'm fairly sure the gist is from the FreeBSD box build. The logs can be a bit confusing but the FreeBSD build folder lives inside a folder called `DevBox/boxes/FreeBSD-10.1-relaease`.

The reason I'm fairly sure it was the FreeBSD build is you can see in the logs: `2015/08/19 20:45:46 Setting cache directory: E:\Projects\DevBox\boxes\FreeBSD-10.1-RELEASE\packer_cache` and that directory is definitely the `freebsd.json` directory.

I'm happy to do another set of debug runs if needed. I'm not at my machine right now but I'll do a run on `FreeBSD-10.1-release` again when I get back.

**Comment by Vodurden** [comment]
Here's another log from running `freebsd.json`. Hopefully it will shed more light:

https://gist.github.com/Vodurden/040ca8e82e81c1d762d4

I have also found that building my `devbox` steps using the `Vagrantfile` in that repository works and doesn't exhibit this issue despite running the same scripts.

**Comment by Vodurden** [comment]
An update on this issue. I am able to reproduce it in debug mode using the following command:

`packer build -debug freebsd.json <<< '\n'`

`<<< '\n'` immediately bypasses the `-debug` breakpointing for each step. With that in place the issue occurs frequently when running commands that need to download/build things.

I'm currently working around this issue by minimizing my use of packer to the bare minimum necessary to provision a vagrant-compatible FreeBSD image and then using a `Vagrantfile` and `vagrant package` to perform all other provisioning. This isn't bulletproof so I also run a second shell script to check if the first succeeded. 

Based on the behavior I've seen it appears that the issue revolves around packer believing a shell script is finished prematurely. Interestingly the position in the script it exits at isn't consistent (event with `-debug`).

**Comment by mwhooker** [comment]
was unable to build with your test script.

I believe this is related to the shell scripts causing a disconnect, either by restarting the host or resetting the network. There's a new option, `expect_disconnect` for the shell scripts. I would advice setting that to `false`, and opening another ticket if the scripts still seem to appear to complete successfully
