### ISSUE TITLE
_ comment is not ignored?

### ISSUE THREAD

**Issue by nitrocode** [mitchellh/packer#2632]
Unsure of why I'm getting errors. I'm running Packer v0.8.5 (released 9 days ago)

According to this commit

https://github.com/mitchellh/packer/pull/2230/files

all _ prefixed strings are comments but my json file is failing on unknown configuration keys.

    $ packer validate ubuntu_64.json
    Template validation failed. Errors are shown below.
    
    Errors validating build 'virtualbox-iso'. 4 error(s) occurred:
    
    * unknown configuration key: "_comment_ignore_boot_command"
    * unknown configuration key: "_comment_ignore_iso_checksum"
    * unknown configuration key: "_comment_ignore_iso_checksum_type"
    * unknown configuration key: "_comment_ignore_iso_url"

**Comment by leroux** [comment]
@nitrocode, from https://github.com/mitchellh/packer/blob/facbb6577d060cd841c9c761d5e7320539640743/website/source/docs/templates/introduction.html.markdown#comments:

> Important: Only root level keys can be underscore prefixed. Keys within builders, provisioners, etc. will still result in validation errors.

**Comment by mitchellh** [comment]
Correct.

**Comment by nitrocode** [comment]
Ah I didn't realize it's only for ROOT level keys. I suppose I'll preprocess my json.

Thank you,
