### ISSUE TITLE
Lacking detail err msg: "Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error:"

### ISSUE THREAD

**Issue by nitrocode** [mitchellh/packer#2633]
```
$ packer validate ubuntu_64.json    
Template validated successfully.
```

Json code: https://gist.github.com/nitrocode/79dfb7f75b5105043323

```
$ export PACKER_LOG_PATH="/var/log/packer.log"
$ export PACKER_LOG=10
$ packer build -debug ubuntu_64.json
```

output: https://gist.github.com/nitrocode/1204cfd8327f3dcd04e9

I cannot find any virtualbox logs to figure out what's wrong. Inside the packer_cache directory, there are only 2 iso files. One has over 2 GB which is my custom-ubuntu.iso file and the other has 0 bytes likely due to the mysterious error above...

Also found https://github.com/mitchellh/packer/issues/2063 from April of this year and that person did not have VT-x enabled. I checked my BIOS and VT-x is enabled and I can deploy OVAs and install ISOs without any issue from Virtualbox. 

What could I be doing wrong?

FYI, an easy way to know if you have VT-x enabled on Linux:

```
sudo apt-get update && sudo apt-get install -y msr-tools
sudo modprobe msr
sudo rdmsr 0x3A
```

Which should and does return 5 for me. 

Source: http://askubuntu.com/a/104017

**Comment by supersteves** [comment]
I saw the same error. Not sure if it's the same underlying problem. I had headless false, and the virtualbox window appeared very briefly before disappearing and printing ```Error starting VM: VBoxManage error:```.

Here's how I worked around the lack of logs to diagnose it.

I enabled debug
```packer build --debug ...```

and pressed enter a few times

and when the error had occurred, I opened the main VirtualBox app and saw the temporary VM listed, and tried to start it. Whereupon I saw the details of the underlying problem. In my case I had added some VBoxManage commands to the builder config which had broken the network card configuration.

**Comment by cbednarski** [comment]
@nitrocode Sorry for the late reply. If you're still experiencing this issue can you share your packer configs and any relevant scripts so I can reproduce this?

**Comment by karouf** [comment]
I know the issue has been open for a long time but I encountered the same thing and thought that it might be useful.
I assume that like me @nitrocode is running packer on Linux without any GUI.
For me, the fix was simply to add `"headless": true` to the virtualbox-iso builder config.
The [packer docs](https://www.packer.io/docs/builders/virtualbox-iso.html#headless) explain that packer tries to launch the VirtualBox GUI by default.

**Comment by mwhooker** [comment]
Good to get some debugging tips around setting "headless". I'm not sure they're related to the opening post, though.
