### ISSUE TITLE
Puppet (masterless) `module_paths` overwrites default module path

### ISSUE THREAD

**Issue by Rican7** [mitchellh/packer#2634]
An older, and somewhat controversial set of issues is mirrored in the Vagrant repo (mitchellh/vagrant#1207 and mitchellh/vagrant#2677).

Currently, when using the `module_paths` configuration option for the `puppet-masterless` provisioner, the default module path is overwritten, making it impossible to use any modules that exist as part of the base image without hard-coding a full `execute_command` string (which changes per Packer version, and therefore breaks compatibility with Packer configurations).

The default, configured, or somehow environmentally detected, module path should probably be appended to the `--modulepath=` string in the execute command to not break base image guest modules.

**Comment by cbednarski** [comment]
It seems like `execute_command` does actually do what you want right now. Also, while `execute_command` may change packer's default behavior as we accommodate changes in the world around us (puppet, APIs, OSes, etc.), specifying your own `execute_command` for your own stuff should be fine. Have you run into problems doing this before?

**Comment by Rican7** [comment]
That's what I'm trying to avoid. Providing a custom `execute_command` configuration parameter means awkwardly copying and pasting the default and defeats most, if not all, of the verification and feature affordances that Packer itself provides. It also makes for an all around more cumbersome configuration, as the implementation essentially "leaks".

That's the reason I've also proposed #2635.

**Comment by cbednarski** [comment]
I see some legit use cases for the scenario you're describing, but I also think it could be a surprising break in backwards-compatibility. By contrast I think #2635 can be applied cleanly with no break in BC.

I'm going to leave this issue open for now. I'm not necessarily opposed but I'd like to understand the BC implications a bit better before changing this.
