### ISSUE TITLE
Puppet (masterless) provision configuration should allow for appending custom options

### ISSUE THREAD

**Issue by Rican7** [mitchellh/packer#2635]
The **Vagrant** puppet provisioner [has an `options` configuration parameter][vagrant-puppet-masterless-options] that is allows for the entry of a custom array of strings to be appended to the execute command during puppet application.

This provides a _very useful_ way to customize the puppet application process when an otherwise unsupported option is needed for the puppet application process.

Currently, the only way to customize the puppet application process is to **change the entire executable command string** via the `execute_command` configuration parameter. The issue with that, is that the puppet command string changes between different versions/releases of **Packer**, and therefore providing a custom `execute_command` string can cause compatibility issues between versions, making the configuration less portable.

I simply propose that Packer add an `options` (or `execute_options`, etc) configuration parameter to the Puppet masterless provisioner to provide similar behavior to Vagrant's version. :smiley: 

[vagrant-puppet-masterless-options]: https://docs.vagrantup.com/v2/provisioning/puppet_apply.html

**Comment by Rican7** [comment]
Implemented in PR #2910.

**Comment by Rican7** [comment]
@cbednarski can we close this now that it's been implemented in #2910?

**Comment by cbednarski** [comment]
@Rican7 Thanks for the heads up!

**Comment by Rican7** [comment]
:+1:
