### ISSUE TITLE
Random shell upload filename is not random

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2640]
I've seen dozens of logs posted with the "random" shell script name `/tmp/script_7943.sh`. I'm pretty certain this is not random. It's likely the random function is using a constant seed or something similar.

**Comment by trodemaster** [comment]
Would this fix apply to powershell provisioner? Doesn't seem so from the fix. Was also wondering if the random name is generated for each script if you you use a list of scripts?
