### ISSUE TITLE
error initiazing box from atlas

### ISSUE THREAD

**Issue by lylianmeyemezu** [mitchellh/packer#2643]
Hi, 
I've created a centos7.1 virtual with packer and uploaded to atlas.
I got erros below

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'lmeyemezu/centos7.1-chefdk-toolchain' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'lmeyemezu/centos7.1-chefdk-toolchain'
    default: URL: https://atlas.hashicorp.com/lmeyemezu/centos7.1-chefdk-toolchain
==> default: Adding box 'lmeyemezu/centos7.1-chefdk-toolchain' (v0.0.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/lmeyemezu/boxes/centos7.1-chefdk-toolchain/versions/0.0.1/providers/virtualbox.box
    default: Progress: 100% (Rate: 2049k/s, Estimated time remaining: --:--:--)
The "metadata.json" file for the box 'lmeyemezu/centos7.1-chefdk-toolchain' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

http://docs.vagrantup.com/v2/boxes/format.html
```

unzipping the box created locally with "keep_input_artifact" : true, i do see a metadata.json file.

**Comment by cbednarski** [comment]
Thanks for the report! I have seen this once before but I don't know the reason this happens, so unfortunately I can't suggest a work-around either.

**Comment by lylianmeyemezu** [comment]
don't worry. Thanks for replying

**Comment by lmeyemezu** [comment]
Hi,
I try to upload manually
curl -v -X PUT --upload-file centos7.1-chefdk-toolchain.box "https://binstor
e.hashicorp.com/d25eaad0-4a2e-40cd-aacd-d81dbabe4fe7"
*   Trying 54.209.15.110...
* Connected to binstore.hashicorp.com (54.209.15.110) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Program Files (x86)\Git\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.0, TLS handshake, Client hello (1):
* TLSv1.0, TLS handshake, Server hello (2):
* TLSv1.0, TLS handshake, CERT (11):
* TLSv1.0, TLS handshake, Server key exchange (12):
* TLSv1.0, TLS handshake, Server finished (14):
* TLSv1.0, TLS handshake, Client key exchange (16):
* TLSv1.0, TLS change cipher, Client hello (1):
* TLSv1.0, TLS handshake, Finished (20):
* TLSv1.0, TLS change cipher, Client hello (1):
* TLSv1.0, TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / DHE-RSA-AES128-SHA
* Server certificate:
*        subject: serialNumber=RlUJkxnL21tPDK-hCoN5WyrI6GDuCqiE; OU=GT33562476; OU=See www.rapidssl.
com/resources/cps (c)14; OU=Domain Control Validated - RapidSSL(R); CN=*.hashicorp.com
*        start date: 2014-09-01 01:43:46 GMT
*        expire date: 2016-09-03 05:38:42 GMT
*        subjectAltName: binstore.hashicorp.com matched
*        issuer: C=US; O=GeoTrust, Inc.; CN=RapidSSL CA
*        SSL certificate verify ok.
> PUT /d25eaad0-4a2e-40cd-aacd-d81dbabe4fe7 HTTP/1.1
> User-Agent: curl/7.41.0
> Host: binstore.hashicorp.com
> Accept: */*
> Content-Length: 880851108
> Expect: 100-continue
>
< HTTP/1.1 100 Continue

It hangs waiting response from web server.
