### ISSUE TITLE
Determine AMI ID during packer build

### ISSUE THREAD

**Issue by gamename** [mitchellh/packer#2644]
Hi,

Is there some way to determine the AMI ID of a build while packer is still running?  

I have a template that is packer push'd to Atlas. One of the builds in it creates an Amazon AMI (see below for the abbreviated template).   At the place indicated, how can I get the newly-created AMI ID to add to the "description" field?

Thanks,
-Tennis 

```
{
  "variables": {
    "atlas_name": "nextgxdx/centos7dev",
    ********* SNIP *******  
},
  "push": {
    "name": "{{user `atlas_name` }}",
    "vcs": false
  },
  "builders": [
    {
      "type": "amazon-ebs",
      ****** SNIP ****
    }
  ],
  "provisioners": [
    {
    **********SNIP*************
    }
  ],
  "post-processors": [
    [
      {
        "type": "atlas",
        "artifact": "{{ user `atlas_name` }}",
        "artifact_type": "vagrant.box",
        "only": [
          "amazon-ebs"
        ],
        "metadata": {
          "provider": "aws",
          "version":  "{{ user `atlas_version` }}",
          "description": "{{ user `atlas_description` }}"  <----- HOW TO ADD AMI ID HERE???
        }
      }
    ]
  ]
}

```

**Comment by cbednarski** [comment]
Thanks for opening a ticket! Packer is mostly stateless and there are a few pieces needed to make this work. I'm not exactly sure what's involved in implementing this, but likely something like this:

1. Add metadata to the artifact which includes the AMI ID, so it can be passed through to the post-processor
2. Make AMI ID from the artifact available for interpolation in the post-processor
3. Make `description` a two-pass interpolation so we can interpolate the user variable and then re-interpolate the AMI ID.

I'm not sure whether I can put more data into the artifact without changing the interface, or if I can make this a special case for AMIs in Atlas. I'm also not sure what the implications are for validating the config with 2-phase interpolation, so this will involve some digging.

**Comment by gamename** [comment]
@cbednarski - Good ideas.  What about exporting the AMI ID into an env var just after the build, but before the post-processors. Possible?

**Comment by cbednarski** [comment]
We could export it, but packer only reads environment variables at the start of the template parsing when it evaluates the variables section. Thereafter env vars are ignored.

Assuming we could export it, there might be some convoluted way to get it into a shell script and back into a custom post-processor that way but for a first class solution I don't think it will work.

**Comment by gamename** [comment]
@cbednarski Yeah, I see your point.  Write to a file and parse it maybe?

**Comment by gamename** [comment]
@cbednarski - How about this?  I can [run a script](http://aws.amazon.com/code/1825) during the build which will get the info which can then be saved to a file.   Would there be any way to append that to the description in the post-processor?

**Comment by dbanttari** [comment]
`grep` can be helpful here:
cat builds/packer.log | grep "amazon-ebs: AMI: ami-" | grep -i -o 'ami-[a-z0-9]\+' > ami.txt

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
