### ISSUE TITLE
Packer Deletes ISO if iso_checksum is wrong

### ISSUE THREAD

**Issue by jared52au** [mitchellh/packer#2645]
Yesterday I noticed a behavior I thought was odd and I've decided to report it to see if it's a bug or a feature. I changed the iso_url to a different ISO but I forgot to change the iso_checksum. When packer ran, it errored as expected, but it also deleted the ISO from the directory I referenced it from. I had to go download the CentOS 7 ISO 2 or 3 times because I couldn't figure out why it was disappearing and then I noticed when it was happening.

Is this expected? If so, how do I keep it from deleting the ISO, other then remembering to use the right hash, or to use different template files?

**Comment by cbednarski** [comment]
Thanks for the report. This was [reported last week](https://github.com/mitchellh/packer/issues/2603) and is [fixed in master](https://github.com/mitchellh/packer/pull/2605). It will go out in the next packer release. Sorry about the inconvenience!

**Comment by jared52au** [comment]
Sorry about that. I guess I didn't do a good enough search to see if it already exists. Thanks.

**Comment by sesas** [comment]
Is this change out already?  Is it possible to have packer not delete the downloaded `iso`s even if it's not a local file?
