### ISSUE TITLE
Documentation oversight

### ISSUE THREAD

**Issue by centromere** [mitchellh/packer#2647]
For the amazon-ebs builder, [the documentation](https://www.packer.io/docs/builders/amazon-ebs.html#user_data) states:
> user_data (string) - User data to apply when launching the instance. Note that you need to be careful about escaping characters due to the templates being JSON. It is often more convenient to use user_data_file, instead.

However, when I try to set some cloud-config directives, I get this error:
```
==> amazon-ebs: Error launching source instance: InvalidParameterValue: Invalid BASE64 encoding of user data
==> amazon-ebs: 	status code: 400, request id: []
```
Base64 encoding the data fixes the error, but the documentation doesn't make it clear that this is a requirement.

**Comment by cbednarski** [comment]
Hi, thanks! You are correct that this needs to be base64-encoded. There is actually [a PR open to fix this](https://github.com/mitchellh/packer/pull/2539) so rather than fix the docs we'll make it work the expected way.

**Comment by cbednarski** [comment]
ldoc
