### ISSUE TITLE
Salt provisioner: remote_state_tree option problem

### ISSUE THREAD

**Issue by mafrosis** [mitchellh/packer#2652]
**Problem**

The change introduced in 769c82b added two new variables `RemoteStateTree` and `RemotePillarTree`, which break the Salt provisioner for me. These variables allow the user to specify where on the packer-built guest OS that the Salt state and pillar files will be uploaded.

These new variables correspond to the Salt config options `file_roots` and `pillar_roots`, which traditionally are set in the minion's config file at `/etc/salt/minion`.

The change in 769c82b provides a way for a user to configure the specific paths for their states and pillar files on the guest OS, without having to go to the effort of writing a minion config (which would be passed in the Packer variable `minion_config`).

The issue is that `remote_state_tree` and `remote_pillar_roots` are passed to `salt` as command line arguments, which override any configuration supplied in the minion config - and this breaks my build.

**Proposed Solution**

Modify the provisioner such that if `minion_config` is supplied, the parameters `--file-root` and `--pillar-root` will not be passed onto salt (see [line 197](https://github.com/mitchellh/packer/blob/master/provisioner/salt-masterless/provisioner.go#L197) in `provisioner.go`).

I believe this is a safe compromise which likely does not break existing functionality.

I will submit a patch for this, and updated docs explaining the interaction between the various salt provisioner config options.

cc @moinfar @SeMeKh

**Comment by cbednarski** [comment]
Thanks for opening a ticket! This sounds reasonable to me.

I think we could solve this by building the options list dynamically and only setting options that have a (non-default) value.

**Comment by moinfar** [comment]
@mafrosis
Sorry for the mess I made.
I can fix this issue if you don't mind.

**Comment by mafrosis** [comment]
@cbednarski I'll send in a pull req in the next couple days :+1: 

@moinfar no problem! I'm happy to work on a solution, as I also would like the provisioner to support multiple `file_roots`, as Salt does. Did you add those two new variables to avoid passing a `minion_config`? Will my suggested solution work for you?
