### ISSUE TITLE
Disable/Enable headless via parameters

### ISSUE THREAD

**Issue by imduffy15** [mitchellh/packer#2658]
When debugging packer builds it is nice to be able to have the hypervisors run in GUI mode. This means modifying the packer file to set the `headless` option accordingly.

Using variables I thought it would be possible to do `headless: {{user 'headless_mode'}}` (ignore the straight quotes github is stripping the proper ones.) to pass a bool in. However this appears to cause syntax issues (bug)?

**Comment by cbednarski** [comment]
If you use a user variable like this you will need to enclose it in quotes. There are a few tickets open for this not working as expected with booleans, so let me know if that doesn't work.

**Comment by imduffy15** [comment]
Hey Chris,

Placing quotes around it makes it be taken as a string which results in an
error as a boolean is expected.

**Comment by imduffy15** [comment]
Closing this due to finding a work around. 

If you set headless to null and force it to be inputted it appears to accept without issue. 

```json
{
    "builders": [{
         ....
        "headless": "{{ user `headless` }}",
         ....
     }],
     .....
     .....
     "variables": {
          "headless": null
      }
}
```
