### ISSUE TITLE
AMI still in 

### ISSUE THREAD

**Issue by makered** [mitchellh/packer#2659]
I have seen this a number of times now. I kick off packer with an amazon-ebs builder and it completes successfully:

```
...
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: app@0.0.1
    amazon-ebs: AMI: ami-835b4ca3
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Modifying attributes on AMI (ami-835b4ca3)...
    amazon-ebs: Modifying: description
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.
```

Then I wait for 20 seconds and attempt to check on the state of the AMI via ```describeImages``` however the state of the AMI is returned as "**pending**".

Could this be a packer issue or ```describeImages``` not returning consistent results?

Thanks

**Comment by cbednarski** [comment]
The `describeImages` call is [cached and eventually consistent](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html). I believe packer marks this a success when the `createImage` call returns successfully, but it may take some additional time before `describeImages` shows the same data. Amazon recommends polling with exponential backoff until `describeImages` returns the results you're looking for.

**Comment by makered** [comment]
Makes sense, thanks!
