### ISSUE TITLE
Make admin password of booted instance available as template variable

### ISSUE THREAD

**Issue by carlpett** [mitchellh/packer#2663]
I'm trying to build Windows images on OpenStack with packer, but I'm having some issues getting started. Our OpenStack provider has cloud-init Windows images which we'd like to use as the base image. In those, there is an admin account with credentials set during first boot, and this password is returned when booting the machine. 

In order to use WinRM, we need to set the `winrm_password` option to this admin password. I tried figuring out how to export it as a configuration template variable so I could just put `{{ .AdminPass }}`, but I'm not very fluent in Go, unfortunately. 

From the [gophercloud docs](http://godoc.org/github.com/rackspace/gophercloud/openstack/compute/v2/servers#Server) it seems this property is already exposed, so I'm guessing it just needs to be exposed somehow to the templating system?

**Comment by joekhoobyar** [comment]
+1 on this

**Comment by carlpett** [comment]
I noticed that this is implemented for Amazon (https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_get_password.go). How much work would it be to reuse that code?

**Comment by jgeorgeson** [comment]
I know this is long closed, and the Communicator certainly seems able to validate a WinRM connection using the obtained generated password, but I can't actually reference `{{.WinRMPassword}}` in my provisioners. I notice that the Amazon builder is calling [`commonhelper.SetSharedState()`](https://github.com/hashicorp/packer/blob/022b559c2fd00fc2981a3367515f165c44cdf267/builder/amazon/common/step_get_password.go#L99) while the OpenStack builder is not. Is this the little bit of missing magic that would let me reference `{{.WinRMPassword}}` in my provisioners (those that support it, such as shell-local and powershell)?

**Comment by SwampDragons** [comment]
Yes, this is only implemented for a subset of builders, and I don't believe OpenStack is one of them.  I'd happily review a PR adding support for this to OpenStack; if you call that setsharedstate function then yes, the password will become available to you in the provisioners that allow you to reference it.

**Comment by midekra** [comment]
+1 - would be nice to reference {{.WinRMPassword}} from the openstack builder in the provisioners.

**Comment by rickard-von-essen** [comment]
This has been resolved long ago. If you are missing a feature or want to report a bug open a [new issue](https://github.com/hashicorp/packer/issues/new).
