### ISSUE TITLE
Use environment variables to specify AMI size.

### ISSUE THREAD

**Issue by flyinprogrammer** [mitchellh/packer#2664]
Given I want to pass my AMI volume sizes in as environment variables.
When I do something like this in packer.json:

```
{
    "variables": {
        "project_name": "{{env `PROJECT_NAME`}}",
        "packer_ami_id": "{{env `PACKER_AMI_ID`}}",
        "volume_size": "{{env `VOLUME_SIZE`}}"
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "source_ami": "{{user `packer_ami_id`}}",
            "instance_type": "t2.medium",
            "ssh_username": "ec2-user",
            "ssh_timeout": "5m",
            "ami_name": "{{user `project_name`}}-{{timestamp}}",
            "ami_regions": ["us-west-2"],
            "launch_block_device_mappings": [ {
                "device_name": "/dev/sda1",
                "volume_size": "{{user `volume_size`}}" ,
                "volume_type": "gp2"
            } ]
        }
    ]
}
```

Then I expect the volume_size of the root partition of the AMI to be what I specified.

Actual:

```
* cannot parse 'launch_block_device_mappings[0].volume_size' as int: strconv.ParseInt: parsing "": invalid syntax
```

Notes:
The same thing happens with amazon-chroot and root_volume_size. (https://github.com/mitchellh/packer/pull/2289#issuecomment-133592516)

**Comment by flyinprogrammer** [comment]
Seems like we would want this to be a helper of the "user" function to test for int64 and use that instead of string that way we can still be type driven? I imagine we have a similar thing for bool? idk. if someone can show me where this should be written I have no problem contributing some tests and a PR?

Just trying to help, not create more work for maintainers.

**Comment by cbednarski** [comment]
Thanks for opening an issue. As you mentioned I think we need to generally coerce strings to match the expected type (though I'm curious that this doesn't happen already via reflection).

**Comment by rstruber** [comment]
Would just like to express my need for this as well. Taking dynamic volume sizes from jenkins would be handy.
```
{
    "variables": {
        "disk": "4096"
    },
    "builders": [
        {
            "type": "qemu",
            "disk_size": "{{user `disk`}}",
            ...
        }
    ]
}
```

Build result:
```
1 error(s) decoding:
* cannot parse 'disk_size' as uint: strconv.ParseUint: parsing "${DISK}": invalid syntax
```

**Comment by mwhooker** [comment]
I think this is working

```
~/dev/packertest ᐅ cat 2664.json
{
    "variables": {
        "volume_size": "{{env `VOLUME_SIZE`}}"
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "source_ami": "ami-1234",
            "instance_type": "t2.medium",
            "ssh_username": "ec2-user",
            "ssh_timeout": "5m",
            "ami_name": "2664-{{timestamp}}",
            "ami_regions": ["us-west-2"],
            "launch_block_device_mappings": [ {
                "device_name": "/dev/sda1",
                "volume_size": "{{user `volume_size`}}" ,
                "volume_type": "gp2"
            } ]
        }
    ]
}
~/dev/packertest ᐅ VOLUME_SIZE=200 packer validate 2664.json
Template validated successfully.
~/dev/packertest ᐅ packer validate 2664.json
Template validation failed. Errors are shown below.

Errors validating build 'amazon-ebs'. 1 error(s) decoding:

* cannot parse 'launch_block_device_mappings[0].volume_size' as int: strconv.ParseInt: parsing "": invalid syntax
```

**Comment by buzztroll** [comment]
I see this issue with 1.2.5.  Here is the relevant part of my template:

```
{
  "variables": {
    "data_format": "5.0",
    "volume_byte_size": "128",
    "data": "",
    "dataset_name": "",
    "license_file": "{{env `STARDOG_LICENSE`}}",
    "region": "",
    "aws_az": "",
    "deploy_name": "{{env `DEPLOY_NAME`}}"
  },
  "builders": [
    {
      "type": "amazon-ebsvolume",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "region": "{{user `region`}}",
      "source_ami": "{{user `source_ami`}}",
      "instance_type": "{{user `instance_type`}}",
      "availability_zone": "{{user `aws_az`}}",

...

      "ebs_volumes" : [
        {
          "volume_type": "gp2",
          "device_name": "/dev/xvdf",
          "volume_size": "{{user `volume_byte_size`}}" ,
          "delete_on_termination": false,

....
```

And this is the error message:

`* cannot parse 'ebs_volumes[0].volume_size' as int: strconv.ParseInt: parsing "{{user `volume_byte_size`}}": invalid syntax`

**Comment by rickard-von-essen** [comment]
@buzztroll open a new issue.

**Comment by gowthamakanthan** [comment]
Do we have any fix for this issue? am getting the same error.

Errors validating build 'vsphere-iso'. 3 error(s) decoding:

* cannot parse 'CPUs' as int: strconv.ParseInt: parsing "": invalid syntax
* cannot parse 'RAM' as int: strconv.ParseInt: parsing "": invalid syntax
* cannot parse 'disk_size' as int: strconv.ParseInt: parsing "": invalid syntax
[vshpere]# packer -version
1.4.0
[vshpere]#

**Comment by SwampDragons** [comment]
Thanks for reaching out, but this issue has been closed for several years.  If you're experiencing a new one, it's a lot easier for us to track if you open a new issue with full steps to reproduce.
