### ISSUE TITLE
Shell provisioner hangs with no error if used with WinRM

### ISSUE THREAD

**Issue by highlyunavailable** [mitchellh/packer#2670]
If the user accidentally uses the `shell` provisioner instead of the `powershell` or `windows-shell` provisioner with a WinRM communicator, there is no error message printed about missing SSH data - the build will actually proceed right up until the point it hits the `shell` provisioner, then hangs with no error.

**Comment by pecigonzalo** [comment]
Will it timeout eventually?

**Comment by highlyunavailable** [comment]
It didn't after 35 minutes. It may eventually.

**Comment by pecigonzalo** [comment]
Can you re run it with debug logs? ill try and fix this

**Comment by cbednarski** [comment]
Thanks for the report. Unfortunately it's very difficult for us to troubleshoot without a packer config and minimal repro case -- if you are still experiencing a problem please open an new issue with additional details. Thanks!

**Comment by highlyunavailable** [comment]
Not sure what else you need to repro this, it's pretty self-evident.

Make a build using the WinRM communicator, then use the Shell provisioner instead of Powershell. Packer hung when I tried it by accident.

**Comment by pecigonzalo** [comment]
@highlyunavailable well for starters you could post the debug logs and gist to your packer file as requested.

**Comment by DaveDingle75** [comment]
@pecigonzalo - I am experiencing this issue with Packer 1.2.1.  Are you still willing to look at this issue?  I am happy to assist by, for starters, providing my test Windows 7 JSON file and WinRM settings files:

https://github.com/DaveDingle75/packer-windows

I have left Packer running for well over a 2 hours (with a 1 hour WinRM timeout setting) and it didn't timeout/error.

Thanks!

**Comment by pecigonzalo** [comment]
@DaveDingle75 sorry for the late reply, it seems this is sorted already. :D

**Comment by DaveDingle75** [comment]
@pecigonzalo No worries at all.  Thanks for getting back anyway 👍
