### ISSUE TITLE
docker-save failing

### ISSUE THREAD

**Issue by Andrew415** [mitchellh/packer#2673]
Hi, I have a current version of packer and docker failing to save a docker image with the page at https://www.packer.io/docs/post-processors/docker-save.html using 

{
  "type": "docker-save",
  "path": "foo.tar"
} 

properly. The build normally completes just fine but I get this error:

"==> docker: Running post-processor: docker-save
Build 'docker' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type: packer.docker
Can only save Docker builder artifacts.

==> Some builds didn't complete successfully and had errors:
--> docker: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type: packer.docker
Can only save Docker builder artifacts.

==> Builds finished but no artifacts were created."

Someone reported a similar error a couple years ago but no resolution was posted. Maybe someone out there knows how to change the artifact type that gets passed to docker for this but that is over my head.

**Comment by cbednarski** [comment]
Thanks for opening an issue. `docker-save` is meant to be used following a `docker-import`. From my reading of the documentation if you're using the docker builder you can `commit` and then use the `docker-tag` and `docker-push` post-processors and you should not need to use `docker-save`.

`docker-save` is only needed if you used `export` followed by `docker-import` (which I think is a bit convoluted in the typical case).

**Comment by rickard-von-essen** [comment]
@predatorian3 ask om the mailing list for help.
