### ISSUE TITLE
Import box to AWS

### ISSUE THREAD

**Issue by darksheer** [mitchellh/packer#2674]
I'd like to propose a feature request for Packer to import a box into AWS EC2. We're currently using Packer and Vagrant for automated build processes of our virtual machines, but we'd like to be able to deploy one or multiple machines in AWS as either instances or AMI's. 

Right now we have to use a wrapper script around Packer to automatically import the box after Packer completes. This capability would honestly be well suited for both Packer and Vagrant to allow users options on when they want an image pushed into EC2.

I'd be more than happy to open a similar ticket for Vagrant ad well, but didn't want to cross post before getting some initial feedback on the capability. 

I tried searching around to see if this has been requested yet and didn't see anything referencing it.

**Comment by darksheer** [comment]
Just checking back on this.

**Comment by cbednarski** [comment]
Thanks for opening an issue! You'll be happy to know that this has been implemented here: https://github.com/mitchellh/packer/pull/2962, and is currently pending review! I can't promise exactly when this will be released but if you feel comfortable building packer from source please try it out and leave your feedback in the PR.

**Comment by darksheer** [comment]
Awesome -- thank you packer team!
