### ISSUE TITLE
Support docker builds using remote docker (boot2docker, etc.)

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2675]
Currently you can't run a docker build on OSX even if you are using boot2docker or have set your docker port to point to a Linux host. Instead you have to run packer inside a VM which is rather tedious.

This issue manifests as a hang when running a docker build, and is rather confusing.

I *think* this can be fixed by using `docker cp` in the implementation of `Upload()` and `UploadDir()` in the docker builder communicator, which will offload the remote tunnel operation to the docker client. This requires the docker client to be installed on the same machine as packer, but this is currently a requirement anyway, so I don't think this matters.

**Comment by cbednarski** [comment]
The same issue is referenced in a few places:

- #901
- #1752
- #2436

901 suggests a fix using `TMPDIR`.

**Comment by cornfeedhobo** [comment]
I am experiencing the same issues on an OpenSuse 13.2 host.
Docker 1.7.1
Packer 0.7.5

Example json:
```
{
  "builders": [{
    "type": "docker",
    "image": "python:2.7",
    "commit": true
  }],
  "provisioners": [{
    "type": "file",
    "source": "python-entrypoint.sh",
    "destination": "/tmp/entrypoint.sh"
  }]
}
```

Log entries relevant to the issue:
```
...
2015/09/07 18:36:51 Running builder: docker
2015/09/07 18:36:51 ui: ==> docker: Creating a temporary directory for sharing data...
2015/09/07 18:36:51 ui: ask: ==> docker: Pausing after run of step 'StepTempDir'. Press enter to continue.
==> docker: Creating a temporary directory for sharing data...
==> docker: Pausing after run of step 'StepTempDir'. Press enter to continue. 
...
2015/09/07 18:37:25 packer-builder-docker: 2015/09/07 18:37:25 Running the provision hook
2015/09/07 18:37:25 ui: ==> docker: Uploading python-entrypoint.sh => /tmp/entrypoint.sh
2015/09/07 18:37:25 packer-provisioner-file: 2015/09/07 18:37:25 [INFO] 279 bytes written for 'uploadData'
2015/09/07 18:37:25 [INFO] 279 bytes written for 'uploadData'
==> docker: Uploading python-entrypoint.sh => /tmp/entrypoint.sh
2015/09/07 18:37:25 packer-builder-docker: 2015/09/07 18:37:25 Executing in container 957ed0f031a4d5d7c7b9962b24e5e70cd14a05b1999f890ee5d1b6fd8307b0ec: "(cp /packer-files/upload041300568 /tmp/entrypoint.sh) >/packer-files/cmd969348567 2>&1; echo $? >/packer-files/cmd969348567-exit"
2015/09/07 18:37:27 ui error: ==> docker: Upload failed: Upload failed with non-zero exit status: 1
2015/09/07 18:37:27 ui: ask: ==> docker: Pausing before cleanup of step 'StepRun'. Press enter to continue.
...
```

I have checked, and every temporary directory that packer makes, for the purposes of copying files, is empty. I have also tried using `TMPDIR=$HOME/tmp` just to be sure, and the same thing happens; empty folders.

**Comment by qckanemoto** [comment]
+1
