### ISSUE TITLE
Salt Stack provisionner is doing the bootstrap in the Unix way

### ISSUE THREAD

**Issue by rach** [mitchellh/packer#268]
Salt stack has a full support for the Salt minion on Windows.

http://docs.saltstack.com/topics/installation/windows.html

I'm not using Windows but maybe an option to allow to pick the window bootstrap will be nice in the future.

The current code run the unix way to boostrap Salt Stack

https://github.com/mitchellh/packer/blob/da4a7c3b7014b85fc319cd71f71bda9a6f3e6e2a/provisioner/salt-masterless/provisioner.go#L92

@thatch45 is that bootstrap  as easy on Window server?

**Comment by mitchellh** [comment]
This hasn't been requested yet but we'd be happy to see a PR for this. The next version of Packer has a ton of support for Windows so this would be useful. But, until there is a need, closing.
