### ISSUE TITLE
Licensed ESXi 6: vmrun error unable to connect to host: specified version not found

### ISSUE THREAD

**Issue by nitrocode** [mitchellh/packer#2680]
I have a licensed ESXi 6 server and VIX 1.13, VMware Player 7.1.2, vmware-vdiskmanager 7.1.0, and packer 0.8.6 installed on a Windows Server 2012. I have enabled SSH on the ESXi server and can connect to it via SSH without an issue.

My custom-ubuntu-64.json config is valid

    > cat custom-ubuntu-64.json
    {
            "builders": [{
                    "type": "vmware-iso",
                    "communicator": "ssh",
                    "guest_os_type": "custom-ubuntu-64",
                    "ssh_host": "10.59.1.119",
                    "ssh_username": "root",
                    "ssh_password": "secretpw",
                    ...
            }]
    }

This is my `packer build` output

    > packer build custom-ubuntu-64.json
    vmware-iso output will be in this color.
    
    ==> vmware-iso: Downloading or copying ISO
        vmware-iso: Downloading or copying: http://build/custom.iso
    ==> vmware-iso: Creating virtual machine disk
    ==> vmware-iso: Building and writing VMX file
    ==> vmware-iso: Starting virtual machine...
    ==> vmware-iso: Error starting VM: VMware error: Unable to connect to host.
    ==> vmware-iso: Error: The specified version was not found
    ==> vmware-iso: Waiting 4.9804668s to give VMware time to clean up...
    ==> vmware-iso: Deleting output directory...
    Build 'vmware-iso' errored: Error starting VM: VMware error: Unable to connect to host.
    Error: The specified version was not found
    
    ==> Some builds didn't complete successfully and had errors:
    --> vmware-iso: Error starting VM: VMware error: Unable to connect to host.
    Error: The specified version was not found

    ==> Builds finished but no artifacts were created.

I googled the VM error and came across a few posts that mentioned that vmrun may the issue. I uninstalled, removed the directories, cleaned registry with ccleaner, and reinstalled without any luck. I also tested vmrun from the commandline and it seemed to work fine.

    > vmrun -T esx -h https://10.59.1.119/sdk -u root -p secretpw list
    Total running VMs: 1
    [ha-datacenter/datastore1] appliance/mycustomappliance.vmx

Has anyone else run into this issue?

**Comment by pecigonzalo** [comment]
Did you specify the remote_* configurations???
I dont see them on your file.
https://www.packer.io/docs/builders/vmware-iso.html#remote_type

**Comment by nitrocode** [comment]
Yep that was it. I forgot to update this post. 

Thank you.

**Comment by pecigonzalo** [comment]
:+1:
