### ISSUE TITLE
var set from command line overridden by definition in var-file

### ISSUE THREAD

**Issue by guatebus** [mitchellh/packer#2682]
Packer v0.8.6

when calling "packer build -var x=y -var-file=z.json", and user var 'x' is also defined in z.json, the value of x is set to the value defined in the z.json var-file

current packer documentation states:
"variables set from the command-line override all other methods of setting variables"
(https://www.packer.io/docs/templates/user-variables.html)

This began after upgrade to packer v0.8.6. Not sure if passing -var-file before the -var options to the packer build command has different outcome.

**Comment by cbednarski** [comment]
Thanks for opening a ticket. I think these are supposed to be evaluated in order, and the last one will stick. Can you try this instead?

    packer build -var-file=z.json -var x=y

**Comment by richid** [comment]
Running into the same issue after upgrading from `0.7.5`. Rearranging the order and putting the `var` after the `var-file` does indeed work but I believe this is still a bug, or at least a bug in the documentation.

From the docs:
> And as mentioned above, no matter where a -var-file is specified, a -var flag on the command line will always override any variables from a file.

**Comment by dragon788** [comment]
This should definitely be updated in the docs if the behavior has changed.
