### ISSUE TITLE
UUID mismatch in chef-client provisioner

### ISSUE THREAD

**Issue by tas50** [mitchellh/packer#2683]
I'm running into a very odd issue trying to use the chef-client provisioner.  After getting tons of issues with the client/node names not matching which caused issues with the chef server I switched to modifying the chef-client execute command and passing the node name in there instead of relying on the node_name attribute in the client.rb file.  I'm setting my execute_command like this:

"execute_command": "{{if .Sudo}}sudo {{end}}chef-client --no-color -c {{.ConfigPath}} -N packer-{{uuid}} -o 'recipe[core]'"

This results in the following command being run during the packer run:

aws: Executing Chef: sudo chef-client --no-color -c /tmp/packer-chef-client/client.rb -N packer-55ddfab9-80f6-b197-849c-5a1ac162e4f0 -o 'recipe[core]'

My run then fails and when packer tries to clean it up I get this message:

Build 'aws' errored: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.

Command: sudo knife node delete packer-55ddfab7-f09a-9a2b-f7c8-661fdfeca3e6 -y -c /tmp/packer-chef-client/knife.rb

Not that the cleanup is trying to use a different node name then the client run.  These should both be packer-{{uuid}} so I'm confused on how they can differ.

**Comment by cbednarski** [comment]
Thanks for the bug report. If you're still running into this problem can you share a minimal repro example including a packer template and chef scripts?
