### ISSUE TITLE
Templating File Provisioner

### ISSUE THREAD

**Issue by usmanismail** [mitchellh/packer#2686]
We have a use case where one of two almost identical files is uploaded based on a user parameter. i.e. Upload production config or staging config based on which environment the user specified when running packer. Right now we use the user parameter to generate the file name and hence select for the file we want. Alternatively we could upload a template and then use a shell provisioner with a sed command. Both of these solutions are fairly hacky. 

It would be great to have a simple template system which could upload files and replace strings. i.e.

        {
            "type": "file",
            "source": "some_folder/somefile.txt",
            "template_vars": [
                    "SOME_VARIABLE_NAME=SOME_VARIABLE_VALUE"
            ]
        },

**Comment by cbednarski** [comment]
Thanks for the suggestion. Packer supports this by way of configuration management tools (puppet and chef) and also via pre-processing and provisioning via shell. The most significant bonus to each of those alternatives is that they can be run and debugged outside of the context of a packer run, which I think makes them easier to work with. Also, some of these templating use-cases can be quite complex and I'm not sure Packer could ever do a better job than other tools that are already available.
