### ISSUE TITLE
Docs on packer.io specify incorrect environment variable for temporary AWS tokens

### ISSUE THREAD

**Issue by ddohler** [mitchellh/packer#2687]
The docs [specify](https://www.packer.io/docs/builders/amazon-ebs.html#token) that temporary AWS session tokens should be provided via the environment variable `AWS_SECURITY_TOKEN`. This works on Packer version `0.7.1`. However, upon upgrading to Packer `0.8.5`, this no longer works; placing the session token in `AWS_SECURITY_TOKEN` causes Packer to fail as follows:

```
==> app: Error querying AMI: AuthFailure: AWS was not able to validate the provided access credentials
==> app:  status code: 401, request id: []
Build 'app' errored: Error querying AMI: AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: []
```

This appears to be related to a change in the underlying AWS SDK; [this post specifies](http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs) that temporary session tokens must be placed in `AWS_SESSION_TOKEN` -- making this change solves the problem under Packer 0.8.5.

**Comment by cbednarski** [comment]
Thanks for opening an issue. Between 0.7 and 0.8 we switched from goamz to aws-sdk-go and likely overlooked this change.
