### ISSUE TITLE
virtualbox-iso duplicate boot cmd keypresses

### ISSUE THREAD

**Issue by rrva** [mitchellh/packer#2690]
About 30% of the time I get duplicate keypresses sent to the boot prompt for the virtualbox-iso builder.

I use

 "boot_command": [
        "<tab> inst.text inst.sshd url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/postinstall selinux=0 elevator=noop<enter>"
      ],

Any character in this text can become duplicated, tripled etc causing boot failures.
It's a bit random when and which chars, and how many duplicates.

**Comment by rrva** [comment]
Rebooting the build machine actually solved the problem. Was with OSX 10.11, VirtualBox 5.0.2, packer 0.8.6.

**Comment by rickard-von-essen** [comment]
Related to #1796 see @mitchellh's explanation there.

**Comment by rrva** [comment]
Ok, sorry for the dupe.
