### ISSUE TITLE
ssh: Build 'aws-ebs' errored: Retryable error

### ISSUE THREAD

**Issue by johnny-die-tulpe** [mitchellh/packer#2691]
After provisioning aws-ebs failed with exit > 0

For me its seems like related to https://github.com/mitchellh/packer/issues/2004

Packer v0.8.6

```
==> aws-ebs: Terminating the source AWS instance...
==> aws-ebs: No AMIs to cleanup
==> aws-ebs: Deleting temporary keypair...
Build 'aws-ebs' errored: Retryable error: Error removing temporary script at /tmp/script_7943.sh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Some builds didn't complete successfully and had errors:
--> aws-ebs: Retryable error: Error removing temporary script at /tmp/script_7943.sh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Builds finished but no artifacts were created.
```

**Comment by carcus88** [comment]
I have a similar issue with Packver v0.8.6 as well. This used to work in previous version and now after the windows update provision script I get the following

    Build 'windows-server-2012-r2-datacenter-virtualbox' errored: Retryable error: Error removing temporary script at /cygdrive/c/Users/vagrant/win-updates.ps1: Timeout during SSH handshake

The build fails even though the box is fine and a 3 hour build process is all for not.

**Comment by webratz** [comment]
I also can reproduce this in my setup after upgrade from 0.7.5 to 0.8.6

**Comment by cbednarski** [comment]
Thanks for the report. If you are still experiencing this issue can you provide a minimal repro case (example packer template, scripts, etc.)?

**Comment by webratz** [comment]
right now I wasn't able to reproduce it on my local notebook. I'll try to test this in an production environment.

**Comment by bwhaley** [comment]
I encountered this with v.0.8.6 by having a provisioner script that removes the SSH user, e.g.

    #/usr/sbin/userdel -f -r ${sshuser}

This worked in previous versions. I'm guessing that something changed so that a new SSH connection is used to delete the script?

**Comment by jamesongithub** [comment]
just hit this on `v0.10.0`

```
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Retryable error: Error removing temporary script at /tmp/script_7943.sh: dial tcp 10.180.100.96:22: i/o timeout
```

**Comment by mwhooker** [comment]
A lot has changed since this issue was reported, so going to close for now. If you continue to run into this, please make sure you try with the latest version of packer, and, if possible, a json file which reproduces this issue.
