### ISSUE TITLE
downloads the same ISO file separately

### ISSUE THREAD

**Issue by keo** [mitchellh/packer#2695]
is this a bug or a feature?

packer downloads the exact same ISO file for different builders... if the URL and checksum matches, why not re-use it?

**Comment by bdwyertech** [comment]
Yeah, I noticed this too for Vagrant and VMware.  I think this is a bug.

**Comment by vtolstov** [comment]
Can you share debug log for this issue? Sometimes ago i'm write pr to able resume download and nothing needs to be downloaded if file ok.

**Comment by bdwyertech** [comment]
I think I know why this is.  The `virtualbox-iso` downloader supplies an extension, whereas `vmware-iso` does not.  I will make a PR.
