### ISSUE TITLE
Need a winrm_private_ip option

### ISSUE THREAD

**Issue by joekhoobyar** [mitchellh/packer#2704]
The `ssh_private_ip` option is useful for us - can we have a corollary with winrm?  Is this difficult to implement?

**Comment by davidneudorfer** [comment]
+1 this would be helpful as well.

**Comment by zsims** [comment]
Just FYI, the current `ssh_private_ip` option will also work with the WinRM communicator.

**Comment by MartinSGill** [comment]
+1 just ran into this problem

Also thanks @zsims for the answer, this is not obvious.
