### ISSUE TITLE
Parse included templates

### ISSUE THREAD

**Issue by mbrgm** [mitchellh/packer#271]
As a user
I want to be able to include templates in other templates
In order to build DRY modular templates

This is inspired by the [bento](https://github.com/opscode/bento) project. My proposal is to parse templates, which were included using Go's `{{ template "foo" }}`. 

### templates/common.json
```json
{
    "ssh_port": 22,
    ...
}
```

### templates/ubuntu/ubuntu.json
```json
{
    {{ template "../common" }}
    "guest_os_type": "Ubuntu_64",
    ...
}
```

### templates/ubuntu/13.04-server-amd64.json
```json
{
    {{ template "ubuntu" }}
    "iso_url": "iso/ubuntu-13.04-server-amd64.iso",
    ...
}
```
### Result
This would yield the following template:
```json
{
    "ssh_port": 22,
    "guest_os_type": "Ubuntu_64",
    "iso_url": "iso/ubuntu-13.04-server-amd64.iso",
    ...
}
```

## Issues

The above approach leads to invalid json files. So maybe the templates with include statements should have a different filetype, e.g. `.json.templ`. Another possibility would be to not use the `{{{ template "foo" }}}` syntax and introduce an `"include"` key in json templates, which specifies the template file to be included, e.g. `"include": "../common"`.

**Comment by mitchellh** [comment]
I was wrong in my initial comment, this never came :) And we're not planning this in the short term. We've gotten a lot of mileage without it and for now we're just recommending folks pre-process and output JSON to do this. Sorry!
