### ISSUE TITLE
Build VMWare (CentOS) image on ESXi: Kickstart failed due to "/dev/sr0 is write-protected, mounting read-only

### ISSUE THREAD

**Issue by charlesxu2000** [mitchellh/packer#2710]
Building CentOS VMWare image on ESXi v5.5 and got error during kickstart:

============= Log from VM console ===============
OK] Started Media check on /dev/sr0
        Mounting Configuration File System …
[OK] Started Show Plymouth Boot Screen
[OK] Reached target Paths
[OK] Reached target Basic System
[OK] Mounted Configuration File System.
dracut-initqueue[571]: mount: /dev/sr0 is write-protected, mounting read-only
dracut-initqueue[571]: RTNETLINK answers: File exists

Entering emergency mode. Exist to shell to continue

dracut:/#  <Need to manually type exit to proceed>

Starting installer, one moment ….
anaconda 19.31.123-1 for CentOS 7 started.

Not asking for VNC because of an automated install
Not asking for VNC because we don’t have a network
Starting automated install.
Generating updated storage configuration
storage configuration failed: failed to find a suitable stage1 device

<Need to manually choose the CentOS configuration options...>
===================================================

Not sure anyone tried to build CentOS 7 image on ESXi v5.5?

**Comment by charlesxu2000** [comment]
I double checked the ESXi server can get the kickstart cfg file (by using wget from ESXi server)
Also, I have static IP configured in kickstart cfg file:
network --onboot yes --device eth0 --bootproto static --ip x.x.x.x --netmask 255.255.255.0 --gateway x.x.x.x --nameserver x.x.x.x --noipv6

But from the log, ESXi can not get the IP address:

[root@localhost:~] esxcli --formatter csv network vm port list -w 2373791
ActiveFilters,DVPortID,IPAddress,MACAddress,PortID,Portgroup,TeamUplink,UplinkPortID,vSwitch,
,,0.0.0.0,00:0c:29:02:a1:87,33554443,VM Network,vmnic0,33554434,vSwitch0,

I wonder should Packer configure the IP address of the VM? ( I learned from somewhere that Packer current does not use VM API to provision the VM, so the IP address provision is done by kickstart?)

**Comment by rickard-von-essen** [comment]
The kickstart doesn't fail because of _"mount: /dev/sr0 is write-protected, mounting read-only"_.
I think everything will work if you switch to DHCP. This is more a usage question see the [community page](https://packer.io/community) for info on geting help.

**Comment by charlesxu2000** [comment]
Currently we don't have DHCP for the ESXi. 
The question is: 
Where is the VM gets its IP address? I have static IP address defined in the kickstart config file, but the VM cli complained about not be able to get the IP address. Seems we need to have IP address assigned before the kickstart.

**Comment by rickard-von-essen** [comment]
Try using a floppy for the kickstart file, see the bottom of [Docs - vmware-iso](http://packer.io/docs/builders/vmware-iso.html). Use env PACKER_LOG=1 to see a lot of debug printouts.

**Comment by charlesxu2000** [comment]
After mount kickstart file as floppy, it logged error message:
"storage configuration failed: failed to find a suitable stage1 device".

Then it prints out a list of setting (such as Timezone, Software selection, ..) which assume to be picked up from kickstart file.
From packer log, there is no useful info regarding this. 

Not sure the "storage configuration failed." is the root cause or not at this time. The only variable I can think about is we use static IP (no DHCP) but it should not be related.

**Comment by charlesxu2000** [comment]
The root cause is CentOS 7 has different kickstart cmd. I tried CentOS 6.7 and it can proceed further (although stuck at the media check, but it is much further).

Question:
Is there anyone successfully kickstarted CentOS 7?

**Comment by rickard-von-essen** [comment]
See the [bento project for good working examples](https://github.com/chef/bento)

**Comment by amitinfo2k** [comment]
It's due to n/w issue. I have raised the similar issue:  https://github.com/mitchellh/packer/issues/2715
which has workaround but, it's blocking the automation.

**Comment by Limech** [comment]
We had a similar problem with XenServer. Solution was to provide the same static IP that's in the kickstart file to the boot_command in the packer json file.
I.e.
`"boot_command": [
        "<tab> ip=xxx.xxx.xxx.xxx netmask=255.255.255.0 ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
            ],`
This should allow the VM to do the HTTP request to get the kickstart file and for the installation to start.

**Comment by rickard-von-essen** [comment]
I'm closing this since this doesn't seems like a bug.

Ask questions on _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool).

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
