### ISSUE TITLE
Support building using bhyve and xhyve

### ISSUE THREAD

**Issue by rickard-von-essen** [mitchellh/packer#2711]
Support building on FreeBSD using [bhyve](http://bhyve.org/) and on OS X using [xhyve](https://github.com/mist64/xhyve).

I just start started an experimental implementation for this and I'll post a WIP PR for this as soon as I have something slightly useful. Possibly within a week.

**Comment by cbednarski** [comment]
Slick! :+1:

**Comment by jevonearth** [comment]
+1

**Comment by nickschuch** [comment]
Got any code I can check out? Happy to help out!

**Comment by rickard-von-essen** [comment]
I have done some prof-of-concept code. I can hand over that if you really want to hack on this now, but I put this on hold since there is currently some problems with using xhyve/bhyve.

The most important are:
- Only raw disk image supported, but qcow2 is coming. (Ongoing, see https://github.com/xhyve-xyz/xhyve/pull/1)
- Using a network requires executing as super user. This is probably something that we have to live with, at least on OS X.
- Setting up network and detecting dhcp lease must be handled. This could be a interesting point to work on.

@nickschuch Feel free to email me if you want to pursue any of this right now and I can try to get you started.

**Comment by ringods** [comment]
@rickard-von-essen almost a year has passed. Are the problems with xhyve/bhyve you bumped into resolved meanwhile?

**Comment by rickard-von-essen** [comment]
From time to time I do some progress on this ;-). But most of my time goes in to smaller changes and fixes. 

The thing I've been working on lately is connecting and typing `boot_command` over serial line. Currently I'm using a library that requires cgo so to get it in to Packer I also need to rewrite that to be buildable without cgo and support darwin and freebsd. 

If someone wants to help this might go faster.

**Comment by rickard-von-essen** [comment]
I'm actively working on this, just very slowly. I'll close this for now since it won't happen before 1.0, hopefully I can at least have something of beta/alpha quality to share within 6 months. Will reopen then.

**Comment by olevole** [comment]
+1 for FreeBSD/bhyve

@rickard-von-essen in 2017 still no bhyve in packer builders, work is suspended?

Serial and grub_bhyve-based boot method just awful and I'm not sure that it's necessary and/or can be easily implemented . But UEFI-based boot works fine and we can focus on it.

**Comment by rickard-von-essen** [comment]
Unfortunately I've no time to work on this currently. I have some hope to work on it during next year but don't expect to much.
