### ISSUE TITLE
Having a `clean_ami_name` configuration template function, but for Google

### ISSUE THREAD

**Issue by kvz** [mitchellh/packer#2716]
Hi, I'm not usually one for fanboyism but I can't overstate how much I admire what you have accomplished. I'm a user of nearly all Hashicorp's projects and you've made my life dealing with systems infinitely better.

I tried to create a Google Cloud Engine variant of our image, which is suffixed with a version such as `v14.4.3`. Apparently GCE wants only dashes:

``` bash
--> tosip-main-googlecompute40: Error waiting for image: googleapi: Error 400: Invalid value for field 'resource.name': 'tosip-main-googlecompute40-v14.4.3'.  Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

For Amazon, there already is a [clean_ami_name](https://www.packer.io/docs/templates/configuration-templates.html#clean_ami_name) function that you can use in your templates like so

``` JSON5
"ami_name": "tosip-main-ec2-instance-{{user `tosip_version` | clean_ami_name}}",
```

(although not really needed here as Amazon supports periods in AMI names)

Would it make sense to have a `| replace '.' '-'` or `| slug` or `| clean_gce_image_name` function?

I can work around this by having a separate `tosip_version_dashed` variable, but it seems to me if there's a function accommodating this use-case for Amazon, there might as well be one for Google?

**Comment by cbednarski** [comment]
Yeah this sounds like a good idea -- thanks for suggesting it! Do you have a link to docs for the naming rules for GCE images?

**Comment by kvz** [comment]
Sure:

> name
> string
> Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression [a-z]([-a-z0-9]*[a-z0-9])? which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.

From: <https://cloud.google.com/compute/docs/reference/latest/images>

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

Check out https://github.com/mitchellh/packer/blob/master/builder/amazon/common/template_funcs.go for the best place to start on this.
