### ISSUE TITLE
packer hangs on vsphere post-processing module

### ISSUE THREAD

**Issue by splashx** [mitchellh/packer#2720]
After waiting a lounge time for post-processing to finish I decided to kill the process and log into the logs.
From that, I replayed what packer is trying to do and got:

``` bash
$ ovftool --noSSLVerify=false --acceptAllEulas --name=ELK-elastic-GI --datastore=Diskarray_900 --diskMode=thin --network=VM_Network --vmFolder=ELK-Forensics-GI output-elastic-vmware/ELK-elastic-GI.vmx vi://username:password@172.16.2.42/DATACENTER/host/
Opening VMX source: output-elastic-vmware/ELK-elastic-GI.vmx
Accept SSL fingerprint (0C:3B:C6:FA:04:24:7C:59:5A:F7:74:06:09:B6:D9:B0:D9:60:9C:A5) for host 172.16.2.42 as target type.
Fingerprint will be added to the known host file
Write 'yes' or 'no'
```

ovftool supports `--targetSSLThumbprint` and `--targetPEM`\- this should be mapped to post-processing module options when using `--noSSLVerify=false`.

**Comment by mwhooker** [comment]
hey, I hate saying 'please make a PR', but after we've discussed this has a very very low chance of ever being a priority for us to do so we'd rather close this issue than have it stagnate for years to come.

In the meantime, I would use the `options` setting to pass those in yourself.
