### ISSUE TITLE
Non-deterministic network issues with virtualbox-iso builder

### ISSUE THREAD

**Issue by psander-scalearc** [mitchellh/packer#2723]
I'm seeing non-deterministic network issues using the virtualbox-iso builder.  In these cases, I run a series of Packer builds with identical inputs (no changes to machine configuration, Packer data, provisioning scripts, contributing ISO and RPM files, user credentials, etc.).  The only difference between successive runs is the time of day and a serial number.  I'm using a recently patched CentOS 6.6 installation, Virtual Box 5.0.2 r102096, and Packer 0.8.2.  The build is launched via a down-rev Hudson slave.

To give some scope, this procedure produces an OVA image using Virtual Box, then edits it for its target which is VMware.  The procedure instantiates a Virtual Box VM, adds an SCSI controller and two disks, installs CentOS 6.6 from ISO image (with kickstart script served by Packer's http server), and runs a Bash provisioning script that installs additional RPMs and runs some SQLite commands, and finally removes some persistent state from the VM's network configuration.  The VM's network interface is NAT'ed during the installation and provisioning, and is changed to a bridged network as a post-build action.

The issue is that network operations mysteriously fail.  In some cases, Anaconda complains that it cannot load the kickstart script.  In others, ssh times out after the ISO install completes but before the provisioning script runs.  I have also seen time-outs while shutting down the VM gracefully.

In the case where ssh times out, I can run "netstat -l -A inet -n" and see that the port-mapped ssh port is listening.  Stopping and starting the sshd service on the guest OS has no apparent effect.

I don't seem to be able to add my Packer configuration file as an attachment, so I will add it as a later comment.  Note that the variables at the top are intended to be overridden by the script that invokes Packer.

I believe this is a problem with Packer rather than with CentOS or Virtual Box.  How would I change this produce a repeatable and robust process?

**Comment by psander-scalearc** [comment]
{
  "variables": {
    "version_number": "noversion",
    "build_number": "nobuild",
    "product": "noproduct",
    "provision_script": "provision.bash",
    "motd_file": "/dev/null",
    "rpm_url": "http://hudson.dev.scalearc.net/latest_builds/IDB3_COMMON_BRANCH/3.8/installer/idb_installer-3.8.0-1.x86_64.rpm",
    "iso_url": "http://hudson-slave-isobuild.dev.scalearc.net/downloads/CentOS/CentOS-6.6/mirror/CentOS-6.6-x86_64-minimal.iso",
    "cleanup_script": "cleanup.bash",
    "kickstart_dir": ".",
    "output_dir": "output-virtualbox-iso",
    "bridge_adapter": "en0",
    "is_cloud": "0",
    "headless": "true"
  },
  "builders": [{
    "type": "virtualbox-iso",
    "headless": "{{user `headless`}}",
    "output_directory": "{{user `output_dir`}}",
    "iso_url": "{{user `iso_url`}}",
    "iso_checksum_type": "none",
    "ssh_username": "root",
    "ssh_password": "r00t.!@.",
    "ssh_timeout": "30m",
    "format": "ova",
    "guest_additions_mode": "disable",
    "guest_os_type": "Linux_64",
    "hard_drive_interface": "scsi",
    "iso_interface": "ide",
    "vm_name": "{{user `product`}}-{{user `version_number`}}-{{user `build_number`}}",
    "vboxmanage": [
      ["showvminfo", "{{.Name}}"],
      ["storagectl", "{{.Name}}",
                     "--name", "SCSI Controller",
                     "--hostiocache", "on"],
      ["createhd", "--filename", "{{user `output_dir`}}/{{.Name}}-root.vmdk",
                   "--size", "40960",
                   "--format", "VMDK"],
      ["storageattach", "{{.Name}}",
                        "--storagectl", "SCSI Controller",
                        "--port", "0",
                        "--device", "0",
                        "--medium", "{{user `output_dir`}}/{{.Name}}-root.vmdk",
                        "--type", "hdd"],
      ["createhd", "--filename", "{{user `output_dir`}}/{{.Name}}-data.vmdk",
                   "--size", "102400",
                   "--format", "VMDK"],
      ["storageattach", "{{.Name}}",
                        "--storagectl", "SCSI Controller",
                        "--port", "1",
                        "--device", "0",
                        "--medium", "{{user `output_dir`}}/{{.Name}}-data.vmdk",
                        "--type", "hdd"],
      ["modifyvm", "{{.Name}}","--cpus","2"],
      ["modifyvm", "{{.Name}}","--memory","2048"]
    ],
    "vboxmanage_post": [
      ["modifyvm", "{{.Name}}",
                   "--nic1", "bridged",
                   "--bridgeadapter1", "{{user `bridge_adapter`}}"]
    ],
    "http_directory": "{{user `kickstart_dir`}}",
    "boot_command": [
      "<esc>",
      "xx-invalid-loader-will-try-again<enter>",
      "linux ks=http://{{.HTTPIP}}:{{.HTTPPort}}/setup.ks<enter>"
    ],
    "shutdown_command": "halt"
  }],
  "provisioners": [
    {
      "type": "shell",
      "script": "{{user `provision_script`}}",
      "environment_vars": [
        "RPMURL={{user `rpm_url`}}"
      ]
    },
    {
      "type": "file",
      "source": "{{user `cleanup_script`}}",
      "destination": "/tmp/{{user `cleanup_script`}}"
    },
    {
      "type": "file",
      "source": "{{user `motd_file`}}",
      "destination": "/etc/motd"
    },
    {
      "type": "shell",
      "inline": ["set -x",
                 "chown root.root /etc/motd",
                 "chmod 644 /etc/motd",
                 "mkdir -p /system",
                 "echo {{user `is_cloud`}} > /system/iscloud.txt",
                 "chmod 644 /system/iscloud.txt",
                 "rm -f /etc/udev/rules.d/70-persistent-net.rules",
                 "cd /etc/sysconfig/network-scripts",
                 "ln ifcfg-eth0 ifcfg-eth0.orig",
                 "sed -e '/^HWADDR=/d' -e '/^UUID=/d' ifcfg-eth0 | if [[ {{user `is_cloud`}} -eq 0 ]]; then sed -e '/^BOOTPROTO=/d'; else cat; fi > ifcfg-eth0.new",
                 "mv -f ifcfg-eth0.new ifcfg-eth0"
      ]
    }
  ]
}

**Comment by psander-scalearc** [comment]
In one run in which Anaconda complains about being unable to read the kickstart file, the VM's console presents a message that it cannot download the file from http://10.0.2.2:16005/setup.ks .  The IP address part of the URL does not match the IP address of the host running the Virtual Box hypervisor (which is 10.0.0.39).  When I run "netstat -a -t" on the host, I can see port 16005 listening on any interface.  When I run "ifconfig -a" on the host, I do not see any interface configured with the 10.0.2.2 address.  Editing the URL on the Virtual Box console to match the host's IP address leads to another failure.  If I look at the VM's network settings, particularly the Port Forwarding configuration, I see only the SSH port forwarded from the host's localhost IP to the guest's SSH port, which I think is expected.  The Virtual Box "Network Operations Manager" shows no active network operations.

**Comment by cbednarski** [comment]
Thanks for sharing your configuration. I do not see anything in there that looks suspect. It sounds like there is either a bug in VirtualBox or a race condition in packer's HTTP server setup or guest VM networking configuration, though without a consistent repro this will be hard for me to track down.

We've fixed quite a few bugs since the 0.8.2 release. I'm curious whether you can reproduce this problem using a build from master. Also I presume you are running this on a CentOS _host_ OS too, but if you are running on Windows there are a slew of networking-related fixes [since 5.0.2](https://www.virtualbox.org/wiki/Changelog).

**Comment by mwhooker** [comment]
Please try with updated versions of virtualbox and packer, and open another issue if the problem persists
