### ISSUE TITLE
privilege enabled docker container

### ISSUE THREAD

**Issue by snowsky** [mitchellh/packer#2724]
When Packer is working with Docker, Packer will spin up a container without --privileged option. Is there any plan to add --privilege parameter?

**Comment by tim95030** [comment]
I would like to know this too. I need to do some iptables things and without privilege I cannot.

**Comment by tim95030** [comment]
I may have found a solution. I set the run_command attribute to ["--privileged=true","-d", "-i", "-t", "{{.Image}}", "/bin/bash"]

**Comment by snowsky** [comment]
Yes, it can work, but have to change the codes.

**Comment by cbednarski** [comment]
Thanks for opening an issue. I've seen a few requests for this. I think it should be fairly easy to add a configuration option for this.

**Comment by ktf** [comment]
+1

**Comment by snowsky** [comment]
Do you know how to add a new attribute in Config struct? I have added "Privileged bool" and "privileged" in json file, but the packer binary is unable to decode it and gave me "* unknown configuration key: "privileged"".
