### ISSUE TITLE
qemu-kvm: Unknown device 'lsi53c895a' for bus 'PCI'

### ISSUE THREAD

**Issue by joshuacox** [mitchellh/packer#2730]
I'm building a qemu image on centOS
```
# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 
# uname -r
3.10.0-229.11.1.el7.x86_64

```
machine, I added `/usr/libexec` to my PATH,
and I set  `"qemu_binary": "qemu-kvm",` in my template
 but I still get qemu complaining about `qemu-kvm: Unknown device 'lsi53c895a' for bus 'PCI'` am I forgetting something on CentOS?

```
2015/09/10 14:31:48 packer-builder-qemu: 2015/09/10 14:31:48 Executing /usr/libexec/qemu-kvm: []string{"-m", "512M", "-vnc", "0.0.0.0:87", "-drive", "file=output-qemu/RancherOS,if=scsi,cache=writeback,discard=ignore", "-cdrom", "/root/rancheros-packer/packer_cache/b222b05350d7071d882f72f156abe308d1997eb65797a1d2f0b27cc1fa88b7d8.iso", "-machine", "type=pc,accel=kvm", "-device", "virtio-net,netdev=user.0", "-boot", "once=d", "-name", "RancherOS", "-netdev", "user,id=user.0,hostfwd=tcp::2226-:22"}
    qemu: In headless mode, errors during the boot sequence or OS setup
    qemu: won't be easily visible. Use at your own discretion.
2015/09/10 14:31:48 packer-builder-qemu: 2015/09/10 14:31:48 Started Qemu. Pid: 3977
2015/09/10 14:31:48 packer-builder-qemu: 2015/09/10 14:31:48 Qemu stderr: qemu-kvm: Unknown device 'lsi53c895a' for bus 'PCI'
```

**Comment by cbednarski** [comment]
Thanks for opening an issue, and sorry for the late reply on this! It looks like this problem is a side effect of using the SCSI disk option. I've done some googling and it seems like this is a bug in QEMU, but it's also possible packer's default behavior here is wrong. If you're still experiencing this issue can you a minimal repro case so I can troubleshoot? Thanks!

**Comment by vtolstov** [comment]
I thinks this is may be already fixed, https://bugzilla.redhat.com/show_bug.cgi?id=1019220

**Comment by cbednarski** [comment]
@vtolstov Looks like that is also closed as wontfix.

I'm going to close this one. If anyone is still experiencing this problem please open an issue with a repro. Thanks!
