### ISSUE TITLE
ansible-local: execute remote

### ISSUE THREAD

**Issue by nschloe** [mitchellh/packer#2732]
I'm a first-time user of packer and its ansible-local plugin. If I understand correctly, packer takes the entire `roles` directory and moves it to the remote location and calls Ansible there.

This, unfortunately, is a problem for me since my `roles` directory contains a bunch of large files and also some keys which I don't want to see anywhere else but my machine. Luckily, Ansible is made for that purpose (namely to call it locally and move/do stuff on a remote machine). Is there a way to use Ansible in that way through packer?

**Comment by andrenarchy** [comment]
@mitchellh is there a way to get the target host's IP+port in a template? Then we could call ansible on the machine where packer runs (with `shell-local`).

**Comment by rickard-von-essen** [comment]
See PR #1969

**Comment by andrenarchy** [comment]
That's exactly what we need. Hopefully, #1969 will be merged soon.
