### ISSUE TITLE
Source Code - Packer self-references itself from github

### ISSUE THREAD

**Issue by jcoutch** [mitchellh/packer#2735]
I forked the codebase to look at adding some new functionality, and being fairly new to Go, spent about half the day trying to figure out why I kept getting messages about methods not existing on an interface, when they clearly did.

After looking at the imports, you're referencing "github.com/mitchellh/packer" in a handful of files, which causes Go to pull it down from your repo as a dependency, instead of using the source code I just modified.  As soon as I replaced the code deep in my gopath with the code I wrote, it compiled successfully.

One example is in rpc/build.go, which references the packer folder from github.  I'm attempting to add a feature to disable removing artifacts on a failure, which required some changes to packer/build.go, but those changes were never compiled into the code because it was pulling from your github repo.  :-/

**Comment by cbednarski** [comment]
Thanks for opening an issue, and sorry about the confusion here! When working on go projects it's best to have them live in your `GOPATH`. This avoids the problem you described. The easiest way to do this is to use `go get` to clone the repo. So for example if you `go get github.com/mitchellh/packer` it will land in the right place and you will not have the issue where `go build` tries to download the files again. This is a go best practice and is not unique to packer.

> After looking at the imports, you're referencing "github.com/mitchellh/packer" in a handful of files,

An unfortunate side effect of the self-import is that `go get -u` will end up checking out the master branch each time you try to update the dependencies. The `Makefile` has an `updatedeps` target that tries to help with this.

All around, though, I think these are things we could make more apparent in the documentation, and maybe fix by changing some of the circular dependencies.

**Comment by jcoutch** [comment]
But what about in the instance where I run "go get github.com/jcoutch/packer"
so I can work on my fork?  Since there's self-references to
github.com/mitchellh/packer, like you said, it'll want to use the master
branch from your repo as the reference instead of from my repo.

To work around it, I was making all my changes directly in the
github.com/mitchellh/packer directory in my gopath and copying them back to
my repo so I could commit...but that feels dirty...and could lead to me
missing files when I copy them back into my branch.  I guess I could do a
find/replace on the self reference to point at my repo, then remember to
change it back before any pull requests...but that also feels dirty.

Maybe it's just me not grasping how Go works.  I'm coming from the .NET
side of development, and this is my first real exposure to the language.
:-)

Thanks for your response, and also want to say thanks for the time the
community invests in this project!  It has definitely been useful in
building out base dev images for use with Vagrant.

**Comment by cbednarski** [comment]
You're right, this is an unintuitive aspect of go build / go get.

> But what about in the instance where I run "go get github.com/jcoutch/packer"
> so I can work on my fork?  Since there's self-references to
> github.com/mitchellh/packer, like you said, it'll want to use the master
> branch from your repo as the reference instead of from my repo.

What I would recommend for this is to `go get github.com/mitchellh/packer` and set your fork as an upstream:

    git remote add jcoutch https://github.com/jcoutch/packer
    git checkout -b new-feature
    ...
    git push -u jcoutch new-feature

This way you can push to your fork to create a PR but the code on disk still lives in the spot where the go cli tools are expecting to find it.

**Comment by tb3088** [comment]
Could we get relevant parts of this thread added to CONTRIBUTING.md?

After 'go get' I moved the src/github.com/mitchellh/packer directory out of the way and then symlinked to my project working directory. chdir to 'packer' and you can switch to whatever branch you had in mind. You can safely run `go build -o bin/packer.exe .` or make, or `[GOPATH=...] [ PACKER_DEV=1] scripts/build.sh`.

I'm on Windows+Cygwin and you'll need my PR to fix a few things. I have successfully run `make releasebin`. Be warned that using Make will pollute your Git tree with master branch checkouts of vendor stuff courtesy of `govendor sync`. So either copy your Git tree over (rsync is very fast) or stick to the other methods described.

**Comment by mwhooker** [comment]
made a pr for some contrib help. I don't think we're planning on changing how we do imports, as it's best practice to use absolute imports.
