### ISSUE TITLE
How to specify filename of virtualbox-ovf output ?

### ISSUE THREAD

**Issue by AaronO** [mitchellh/packer#2740]
This isn't a major issue since you can easily just call a `mv` after `packer build`.

But it would be nice to be able to specify the full name of the output rather than it being:

```
output-{{ .Name }}/packer-{{ .Name }}-{{ timestamp }}.ova
```

It would be nice to be able to have (for example):

```
output-{{ .Name }}/{{ .Name }}-{{user `version`}}.ova
```

or even simply:

```
output-{{ .Name }}/{{ .Name }}.ova
```

I wasn't able to find a way to change it in the docs or after skimming through the code.

**Comment by rickard-von-essen** [comment]
I think ```output_directory``` and ```vm_name``` should handle this?

**Comment by AaronO** [comment]
@rickard-von-essen Thanks, that should do the job.

I saw the `output_directory` but missed `vm_name`. I think most people (who want to customize the output path) would be interested in both options, so maybe we should update the docs so that `output_directory` mentions `vm_name`.

Thanks for your help.
