### ISSUE TITLE
Change log messages for step_forward_ssh

### ISSUE THREAD

**Issue by rickard-von-essen** [mitchellh/packer#2743]
Both **VirtualBox** and **Qemu** builders have a step_forward_ssh, this is somewhat dubious now when there are several ```Communicators```. We should at least update the log messages to not confuse users.

**Comment by Akasurde** [comment]
@rickard-von-essen I would like to work on this issue, let me know if it is already fixed.

**Comment by rickard-von-essen** [comment]
@Akasurde I opened a PR some time a go, see above. If you want to contribute it is always welcome with a review and test of the PR.

And there are always other small bugs to take a stab at. Feel free to ping me if you want a review or some advice.

**Comment by Akasurde** [comment]
@rickard-von-essen Thanks for advice. I am interested in contributing to project but not sure where to start from. Started from easyfix. If you have something with which I can help, do let me know.
