### ISSUE TITLE
Packer for Rackspace image Error "* Get /: unsupported protocol scheme """

### ISSUE THREAD

**Issue by zhenghuan** [mitchellh/packer#2747]
Hi

I tried to build a image for Rackspace in Packer.But after some hours troubleshooting, I still faced the error....Anybody can help?
With same username and apikey, I can use Vagrant-rackspace plugin to create server in Rackspace.

2015/09/15 14:16:14 ui: rackspace-test output will be in this color.
2015/09/15 14:16:14 ui: 
2015/09/15 14:16:14 Build debug mode: true
2015/09/15 14:16:14 Force build: false
2015/09/15 14:16:14 Preparing build: rackspace-test
Debug mode enabled. Builds will not be parallelized.
rackspace-test output will be in this color.

2015/09/15 14:16:14 Build 'rackspace-test' prepare failure: 1 error(s) occurred:

* Get /: unsupported protocol scheme ""
2015/09/15 14:16:14 ui error: 1 error(s) occurred:

* Get /: unsupported protocol scheme ""
2015/09/15 14:16:14 waiting for all plugin processes to complete...
1 error(s) occurred:

* Get /: unsupported protocol scheme ""
2015/09/15 14:16:14 /home/huan/packer_cmd/bin/packer-builder-openstack: plugin process exited
2015/09/15 14:16:14 /home/huan/packer_cmd/bin/packer-provisioner-shell: plugin process exited

json file:
{
  "builders": [
     {
     "name": "rackspace-test",
     "type": "openstack",
     "username": "mmmm",
     "password": "*mmmm",
     "region": "DFW",
     "tenant_id": "*mmmm",
     "ssh_username": "root",
     "image_name":" CentOS 6",
     "source_image": "aa68fd54-2f9a-42c3-9901-4035e2738830",
     "flavor": "2",
     "api_key":"mmmm",
     "openstack_provider":"rackspace"
      }
  ],
  "provisioners": [
    {
     "type": "shell",
     "inline": [
        "sudo yum install memcached"
    ]
  }]
}

Thanks
Huan

**Comment by rickard-von-essen** [comment]
Duplicates #2597
