### ISSUE TITLE
Console output shows control characters on windows

### ISSUE THREAD

**Issue by JorritSalverda** [mitchellh/packer#2752]
In Windows, whether I use the command prompt, powershell or bash weird control characters show up in the output when running packer:

←[1;32m==> googlecompute: Creating temporary SSH key for instance...←[0m
←[1;32m==> googlecompute: Creating instance...←[0m
←[0;32m    googlecompute: Loading zone: europe-west1-b←[0m

**Comment by JorritSalverda** [comment]
$ packer --version
0.8.6

**Comment by JorritSalverda** [comment]
Just found the -color=false option. Can I set this permanently so I don't have to provide it each time?

**Comment by joth** [comment]
You could try https://www.packer.io/docs/other/environmental-variables.html#PACKER_NO_COLOR

**Comment by JorritSalverda** [comment]
That works.. Thanks.
