### ISSUE TITLE
met an error with the msg "* Get /: unsupported protocol scheme """, what does it mean?

### ISSUE THREAD

**Issue by Gary-Xie** [mitchellh/packer#2758]
When I try to build an image with openstack builder in my private openstack, I met the error like below.
-------------------------------------------------------------------------
ubuntu@testtrusty:~$ packer build -debug openstack.json
Debug mode enabled. Builds will not be parallelized.
openstack output will be in this color.

1 error(s) occurred:

* Get /: unsupported protocol scheme ""
--------------------------------------------------------------------------

This is my template json file. Please double check it.

{
        "variables": {
                "build_number": "0",
                "OS_AUTH_URL": "http://***.***.***:***/v2.0",
                "OS_TENANT_ID": "fe37c1c3529a45619fa1ca3021587f19",
                "OS_TENANT_NAME": "test"
        },
        "builders":[{
                "type": "openstack",
                "username": "mybuilder",
                "password": "************",
                "flavor": "2",
                "ssh_username": "ubuntu",
                "region": "Region1",
                "image_name": "Packer bosh-lite image1",
                "source_image":"04433b1b-015e-4a95-9bec-395f681430a2",
                "security_groups":["default"],
                "use_floating_ip": true,
                "floating_ip":""
        }],
        "provisioners": [{
            "type": "file",
            "source": "bosh-release.tgz",
            "destination": "/home/ubuntu/tmp/bosh-release.tgz"
        },{
            "type": "file",
            "source": "bosh-warden-cpi-release.tgz",
            "destination": "/home/ubuntu/tmp/bosh-stemcell-2776-warden-boshlite-ubuntu-trusty-go_agent.tgz"
        },{
            "type": "packer-bosh",
            "assets_dir": "/home/ubuntu/go/src/github.com/cppforlife/packer-bosh/bosh-provisioner/assets",
            "manifest_path": "bosh_lite_manifest.yml",
            "ssh_password": "ubuntu"
        },{
            "type": "shell",
            "inline": "usermod vcap -a -G ubuntu"
        },{
            "type": "shell",
            "execute_command": "sudo -E {{ .Path }}",
            "remote_path": "/opt/bosh-provisioner/packer-shell.sh",
            "scripts": [
                "scripts/set-temp-dir.sh",
                "scripts/install-cli-tools.sh",
                "scripts/clean-up.sh",
                "scripts/shrink-disk.sh"
        ]
        }]
}

**Comment by rickard-von-essen** [comment]
Duplicates #2597

**Comment by Gary-Xie** [comment]
yes, duplicated. And I find the solution in #2595 to set env variables including OS_AUTH_URL, OS_USERNAME,OS_PASSWORD and OS_TENANTNAME. But I still insist it is a bug. I think it should output some useful and meaningful error msg. And I don't know why these variable couldn't be read from json file as I defined.

**Comment by geefinator** [comment]
+1, not sure when this broke exactly but I know for a fact it did used to pull this out of the config and not rely on the ENV variables, because my images were working up until just recently.  Frustrating.

**Comment by rickard-von-essen** [comment]
The docs have been updated, see [Docs OpenStack](https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/openstack.html.markdown) until next release when the site will be updated.

**Comment by rickard-von-essen** [comment]
Closing this in favour of #2597
