### ISSUE TITLE
Get source ami by name

### ISSUE THREAD

**Issue by JorritSalverda** [mitchellh/packer#2760]
When creating a new ami using the amazon-ebs builder you have to create a unique ami_name name for the resulting ami. I would like to use this unique name in my next packer build as the base ami. Instead of collecting the ami from the console output I like to be able to use the unique name from the first build.

When using that name I get the following error:

amazon-ebs: Error querying AMI: InvalidAMIID.Malformed: Invalid id: "unique-name-from-first-build" (expecting "ami-...")

Either having another optional field besides source_ami or letting source_ami resolve both real ami ids and unique names would be welcome.

**Comment by cbednarski** [comment]
Thanks for the suggestion. This sounds similar to https://github.com/mitchellh/packer/issues/2756 and maybe can be implemented in a similar way.

**Comment by lalyos** [comment]
@JorritSalverda You can use [atlas post-processor](https://www.packer.io/docs/post-processors/atlas.html) which uploads the Artifact to [atlas](https://atlas.hashicorp.com).

## base image

For example we also use a common base image (named as docker) for other images.
When we build the base image it has a postprocessor like:
```
...
"post-processors": [
    {
      "type": "atlas",
      "artifact": "sequenceiq/docker",
      "artifact_type": "amazon.image",
      "metadata": {
        "created_at": "{{timestamp}}",
        "created" :"{{ isotime \"2006-01-02 15:04:05 -0700\" }}",
        "image_name": "{{ user `image_name` }}",
        "docker_version": "{{ user `docker_version` }}"
      }
    }
  ]
...
```

You have to set the `ATLAS_TOKEN` env variable which you get at [settings/token](https://atlas.hashicorp.com/settings/tokens)

You can make the artifact *public* at https://atlas.hashicorp.com/yourname/artifacts/yourartifact/access, so an unaothorized atlas API request can list all the artifact versions:
```
curl -sL https://atlas.hashicorp.com/api/v1/artifacts/sequenceiq/docker/amazon.image/search
```

## child image

So a dependent image can use a `source_ami` variable, which can be queried from atlas:
```
latestBase=$( curl -sL https://atlas.hashicorp.com/api/v1/artifacts/sequenceiq/docker/amazon.image/search \
  | jq '.versions[0].metadata.ami_id' -r
)

packer build -var source_ami=${latestBase} packer.json
```

## terraform 

By using the atlas postprocessor, you can easily automate ec2 provisioning with terraform (@mitchellh for president). For example without even knowing the exact `ami-xxxxx`, you can referenc by artfifact name and type. Even you can use the metadata provided by your own packer variable at build time ((like `docker_version` in our case) 

```
resource "atlas_artifact" "docker" {
  name = "sequenceiq/docker"
  type = "amazon.image"
  # version = "2"
  metadata {
    docker_version = "1.8.3"
  }
}

resource "aws_instance" "docker" {
  ami = "${atlas_artifact.docker.metadata_full.region-eu-central-1}"
 ...
}
```

**Comment by miry** [comment]
@lalyos do you have example how to use similar approach but without atlas? May be with https://www.packer.io/docs/post-processors/shell-local.html ?

**Comment by mwhooker** [comment]
You can use the manifest post-processor to output the AMI of the previous build, and inject that into your next build.

You might also be able to implement this with https://www.packer.io/docs/builders/amazon-ebs.html#source_ami_filter
