### ISSUE TITLE
VBoxManage: error: Invalid UUID or filename

### ISSUE THREAD

**Issue by apannwitz** [mitchellh/packer#2764]
Hello,

when I try to build a simple ubunto box I get the following error. Did I miss something?

packer build ./ubuntu_64/ubuntu_64.json
virtualbox-iso output will be in this color.

Warnings for build 'virtualbox-iso':

* A checksum type of 'none' was specified. Since ISO files are so big,
a checksum is highly recommended.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/precise/ubuntu-12.04.3-server-amd64.iso
==> virtualbox-iso: Starting HTTP server on port 9001
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Error attaching ISO: VBoxManage error: VBoxManage: error: The medium '/opt/packer.io/packer_cache/0a4e26dbd818741c101d6a9a67ef06643d0ce2873d03a6f4edfe18468c0b3613.iso' can't be used as the requested device type
==> virtualbox-iso: VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
==> virtualbox-iso: VBoxManage: error: Invalid UUID or filename "/opt/packer.io/packer_cache/0a4e26dbd818741c101d6a9a67ef06643d0ce2873d03a6f4edfe18468c0b3613.iso"
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error attaching ISO: VBoxManage error: VBoxManage: error: The medium '/opt/packer.io/packer_cache/0a4e26dbd818741c101d6a9a67ef06643d0ce2873d03a6f4edfe18468c0b3613.iso' can't be used as the requested device type
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/opt/packer.io/packer_cache/0a4e26dbd818741c101d6a9a67ef06643d0ce2873d03a6f4edfe18468c0b3613.iso"

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error attaching ISO: VBoxManage error: VBoxManage: error: The medium '/opt/packer.io/packer_cache/0a4e26dbd818741c101d6a9a67ef06643d0ce2873d03a6f4edfe18468c0b3613.iso' can't be used as the requested device type
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/opt/packer.io/packer_cache/0a4e26dbd818741c101d6a9a67ef06643d0ce2873d03a6f4edfe18468c0b3613.iso"

==> Builds finished but no artifacts were created.

Regards
Alex

**Comment by rickard-von-essen** [comment]
See the docs for how to run packer with verbose debugging, rerun and gist the full log,  and config. Also search the closed issues for similar messages.  This sounds familiar.

**Comment by apannwitz** [comment]
ok, thank you and sorry for the trouble. This was obviously a virtual box issue. I had to enable virtualisation in BIOS, reinstall virtual box and set  "headless": "true" in the template file. Now it works!
