### ISSUE TITLE
block device mappings do not work with snapshots

### ISSUE THREAD

**Issue by ryedin** [mitchellh/packer#2765]
The error is:

```
==> amp.ami.couch: Error launching source instance: InvalidBlockDeviceMapping: snapshotId can only be modified on EBS devices
==> amp.ami.couch:  status code: 400, request id: []
```

My builder config is below:

```
"builders": [{
      "name": "amp.ami.couch",
      "type": "amazon-ebs",
      "ami_name": "{{ user `aws_ami_name` }}-Couch-{{timestamp}}",
      "source_ami": "ami-5189a661",
      "access_key": "{{ user `aws_access_key` }}",
      "secret_key": "{{ user `aws_secret_key` }}",
      "region": "{{ user `aws_instance_region` }}",
      "instance_type": "{{ user `aws_instance_type` }}",
      "ssh_username": "ubuntu",
      "launch_block_device_mappings": [{
        "device_name": "/dev/sdb",
        "volume_type": "gp2",
        "snapshot_id": "snap-a5c5d3f9",
        "delete_on_termination": true
      }],
      "tags": {
        "Name": "{{ user `aws_ami_tag_name` }}"
      }
    }]
```

Here’s the weird part… if I remove the snapshot_id it works fine. I have also tried adding (“no_device”: true) to the mapping with no luck. However, further testing reveals that if I change the device name to “/dev/sdd”, now I can use a snapshot. 

So this tells me that the issue has something to do with overwriting the base AMI’s ephemeral device mapping, but if that’s the case I would not expect it to work with “device_name”: “/dev/sdb” at all, yet it does when I leave out the snapshot_id. I would then expect the no_device: true setting to work to allow me to use that device name, but it doesn’t. NOTE: without a snapshot_id, that device name works even _without_ setting a value for no_device - so it's creating an EBS volume an overwriting the ephemeral mapping on the base AMI in this case but that fails when adding a snapshot_id.

At any rate, I’ll just use /dev/sdd since that seems to work. Let me know if you agree this looks like a bug regarding how mappings work when trying to overwrite an ephemeral mapping on the base AMI.

**Comment by JeanVelloen** [comment]
As a workaround try updating your builder config to the following:

"builders": [{
      "name": "amp.ami.couch",
      "type": "amazon-ebs",
      "ami_name": "{{ user `aws_ami_name` }}-Couch-{{timestamp}}",
      "source_ami": "ami-5189a661",
      "access_key": "{{ user `aws_access_key` }}",
      "secret_key": "{{ user `aws_secret_key` }}",
      "region": "{{ user `aws_instance_region` }}",
      "instance_type": "{{ user `aws_instance_type` }}",
      "ssh_username": "ubuntu",
      "launch_block_device_mappings": [{
        "device_name": "/dev/sdb",
        "volume_type": "gp2",
        "snapshot_id": "snap-a5c5d3f9",
        "delete_on_termination": true
      }],
      "launch_block_device_mappings": [{
        "device_name": "/dev/sdb",
        "volume_type": "gp2",
        "delete_on_termination": true
      }],
      "tags": {
        "Name": "{{ user `aws_ami_tag_name` }}"
      }
    }]

The "launch_block_device_mappings" tells packer what snapshot to use when creating the additional disk resource, and the "ami_block_device_mappings" defines how the additional disk is defined when the ami artifact is created.

**Comment by mwhooker** [comment]
I think @JeanVelloen is right on with the solution.
