### ISSUE TITLE
remote_path not honored for inline scripts

### ISSUE THREAD

**Issue by dpetzel** [mitchellh/packer#2766]
I noticed today running 0.8.6 (and 0.7.5) that when setting `remote_path` for inline script the value is ignored. The value works fine when using the `scripts` option though.

Here is my provisioner

```
    {
      "type": "shell",
      "remote_path": "/home/ec2-user/sleep.sh",
      "inline": [ "sleep 30" ]
    },
```

And here is the debug output

```
2015/09/22 13:25:03 packer-builder-amazon-ebs: 2015/09/22 13:25:03 Running the provision hook
2015/09/22 13:25:03 ui: ==> my_builder: Provisioning with shell script: /tmp/packer-shell710744309
==> my_builder: Pausing after run of step 'StepConnect'. Press enter to continue. ==> my_builder: Provisioning with shell script: /tmp/packer-shell710744309
```

This may in fact be the intended behavior. If that is the case maybe a little note on the docs is all that is called for here, but I personally think inline should honor it. In our case we are not allowed to put executable code in `/tmp`, so we have to upload files elsewhere. Its currently easy enough to work around by just putting things into script files.

**Comment by cbednarski** [comment]
This is odd. I reviewed the implementation and the way this appears to work is:

1. inline scripts are written to temporary files
2. list of inline scripts is added to list of other scripts
3. scripts are uploaded and executed (regardless of inline vs. file this code path is the same)

I'm curious where that's going sideways.

**Comment by mwhooker** [comment]
unable to reproduce this with latest packer
