### ISSUE TITLE
403 forbidden in download mirror

### ISSUE THREAD

**Issue by smiller171** [mitchellh/packer#2767]
Your download mirror has broken permissions right now. Can't retrieve zip files

**Comment by cbednarski** [comment]
Thanks for the report. We're aware of this and we're working with our provider to resolve this. You can check our status here: https://status.hashicorp.com

I'm going to leave this open in case other folks have the same issue, but please check [status.](https://status.hashicorp.com) to see when it is resolved.

**Comment by smiller171** [comment]
I've put up a mirror for the latest Linux 64 bit build https://s3.amazonaws.com/cerebrant-resources/packer/packer_0.8.6_linux_amd64.zip

**Comment by cbednarski** [comment]
This has been resolved. Thanks!
