### ISSUE TITLE
amazon-ebs builder: specify iam role of packer instance 

### ISSUE THREAD

**Issue by sheldonkwok** [mitchellh/packer#2769]
Hi all,
Is it possible to specify the iam role of the packer instance being launched for provisioning?

**Comment by kylegoch** [comment]
Hi!
This question is better suited for the [Packer Google Group](https://groups.google.com/forum/#!forum/packer-tool). The issues section is for bug tracking of Packer itself.

But to answer your question, you sure can. See [iam_instance_profile](https://packer.io/docs/builders/amazon-ebs.html#iam_instance_profile) in the config documentation. However, this is not working in any version above 0.8.0, see issue #2611

**Comment by sheldonkwok** [comment]
Ah, I just thought it didn't exist since that flag didn't work when I tried it. Should've looked for the issue. Thanks!
