### ISSUE TITLE
Agent forwarding at SSH communicator

### ISSUE THREAD

**Issue by vkruoso** [mitchellh/packer#2782]
I see that #1066 implemented agent forwarding support at the shell provisioner. The problem is that when using the ansible provisioner, there is no option that behaves the same way. Is there any way to have agent forwarding while using the ansible provisioner?

One workaround would be to use the shell provisioner to execute the ansible command, but that sounds extreme as I would have to copy files myself, and handle the command string myself.

Maybe this is also necessary for other provisioners?

**Comment by markpeek** [comment]
I just tried the below (on a real github private repo) and the ssh agent forwarding worked for me. Note: using sudo in the ansible file will likely fail due to environment variables being stripped. Do you have an example of it not working?

```
---
- hosts: all

  tasks:
  - name: git test
    git: repo=git@github.com:nonexistantorg/myprivaterepo.git dest=/home/vagrant/myprivaterepo
         accept_hostkey=True
```

**Comment by vkruoso** [comment]
I've implemented the workaround in my first comment, it works but looks very bad. It may be the case that I'm using sudo by default on all ansible commands (sudo: true in the playbook). I'll sure give it a try without sudo and will let you know if it works.

Thanks for your answer.

**Comment by markpeek** [comment]
If sudo is required you might want to check out the comments [here](http://stackoverflow.com/questions/24124140/ssh-agent-forwarding-with-ansible) with the /etc/sudoers changes. Note: I would probably remove that line afterwards to put sudoers back to a pristine and more secure state.

**Comment by vkruoso** [comment]
Correction: in the git task we are setting ``sudo: no``. Maybe it is because I'm running a very old version of ansible (the one from ubuntu 14.04 mirror). Let me give one more spin to be sure.

**Comment by vkruoso** [comment]
It was probably a problem in my local agent that did not had the correct key installed. Now I'm having problems due to the fact that ansible is being run using the local mode, since I download the repositories at paths that are relative to the working directory. Of course, this issue can now be closed. Sorry for any inconvenience.

**Comment by markpeek** [comment]
Thanks for the updates. If you still get a reproducible ssh forwarding issue, please let me know. Good luck wrangling your ansible config into shape.
