### ISSUE TITLE
Knife.rb template cannot be customized

### ISSUE THREAD

**Issue by tim95030** [mitchellh/packer#2783]
I have a self signed certificate for my chef server. The only way I have been able to get this to work with the chef-client was to overwrite the template to include trusted_certs and point to a directory with my cert. I now have that working, but then it tries to delete the node and the same error occurs. I looked at the source and there appears to be no way to customize the knife template to add the trusted_certs there. As such please add this. Alternatively if there was a way to add a trusted cert this would be more ideal since what I am doing now is a lot of work to upload the file and move it around and replace all these templates.

**Comment by domofactor** [comment]
+1 for this!

I was however able to get it everything working with a chef-server using a self-signed ssl cert and the following JSON snippet as a workaround.

```
 "provisioners": [{
    "type": "shell",
    "inline": ["mkdir /etc/chef"]
  },
  {
    "type": "file",
    "source": "/home/ubuntu/.chef/trusted_certs",
    "destination": "/etc/chef"
  },
  {
    "type": "chef-client",
    "server_url": "<REDACTED>",
    "validation_client_name": "myorg-validator",
    "validation_key_path": "myorg-validator.pem",
    "staging_directory": "/etc/chef",
    "chef_environment": "{{ user `chef_environment`}}",
    "run_list": ["apt::default"]
  }],
```

**Comment by cbednarski** [comment]
Thanks for opening a ticket. I think this is already possible via https://www.packer.io/docs/provisioners/chef-client.html#config_template If this option doesn't do what you want please re-open. We should add knife.rb somewhere in the docs to make this easier to find.
