### ISSUE TITLE
Creating a Windows 2012 Server Domain Controller image using Packer

### ISSUE THREAD

**Issue by carlskii** [mitchellh/packer#2788]
Hi,

I'm trying to create a Windows 2012 Server Domain Controller using the Packer PowerShell provisioner. I have the following PS that  is called from the Packer provisioner. e.g.

    {
      "type": "powershell",
      "script": ["./scripts/InstallNewForest.ps1"]
    } 

The PS Script looks like this:

    $Password = ConvertTo-SecureString -AsPlainText -String "Passw0rd1£@3451" -Force
    
    # Create New Forest, add Domain Controller
    $domainname = "contoso.com"
    $netbiosName = "CONTOSO"
    
      Import-Module ADDSDeployment
      Install-ADDSForest `
       -CreateDnsDelegation:$false `
       -SafeModeAdministratorPassword $Password `
       -DatabasePath "C:\Windows\NTDS" `
       -DomainMode "Win2012" `
       -DomainName $domainname `
       -DomainNetbiosName $netbiosName `
       -ForestMode "Win2012" `
       -InstallDns:$true `
       -LogPath "C:\Windows\NTDS" `
       -NoRebootOnCompletion:$true `
       -SysvolPath "C:\Windows\SYSVOL" `
       -Force:$true

This all appears to run OK. I then initiate the Windows reboot using the Packer provisioner. Like this:

    {
      "type": "windows-restart"
    }

This restarts the machine as expected and Packer continues to create a working image.

However, when I then boot and login into the new image the server is prompting me to run the DC Promo wizard. If I try setting the `-NoRebootOnCompletion:$true` to `$false` and run the PS script manually it works as expected.

**Comment by rickard-von-essen** [comment]
Ask questions at http://groups.google.com/group/packer-tool or IRC, see http://packer.io/community

**Comment by carlskii** [comment]
Thanks
