### ISSUE TITLE
Docker file downloader truncates larger files

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2793]
When downloading larger (50mb+) files from docker using the file provisioner, the files are sometimes truncated.

I suspect this is a race condition but I have not yet assessed it.

**Comment by justincampbell** [comment]
Simple reproduction here: https://gist.github.com/justincampbell/9dd8d9065b9f9f82b3a8

**Comment by jmccarthy** [comment]
Replaced /dev/urandom with /dev/zero for deterministic hashes, executed 5 trials on OS X + boot2docker + packer 0.8.6 with no deviation in hashes:

```
Attempt #1 ==================
    docker: 2f282b84e7e608d5852449ed940bfc51  /tmp/result-big
    docker: b6d81b360a5672d80c27430f39153e2c  /tmp/result-small
==> docker: Downloading /tmp/result-small => result-small
==> docker: Downloading /tmp/result-big => result-big
==> docker: Executing local command: md5 result-big result-small
    docker: MD5 (result-big) = 2f282b84e7e608d5852449ed940bfc51
    docker: MD5 (result-small) = b6d81b360a5672d80c27430f39153e2c
Attempt #2 ==================
    docker: 2f282b84e7e608d5852449ed940bfc51  /tmp/result-big
    docker: b6d81b360a5672d80c27430f39153e2c  /tmp/result-small
==> docker: Downloading /tmp/result-small => result-small
==> docker: Downloading /tmp/result-big => result-big
==> docker: Executing local command: md5 result-big result-small
    docker: MD5 (result-big) = 2f282b84e7e608d5852449ed940bfc51
    docker: MD5 (result-small) = b6d81b360a5672d80c27430f39153e2c
Attempt #3 ==================
    docker: 2f282b84e7e608d5852449ed940bfc51  /tmp/result-big
    docker: b6d81b360a5672d80c27430f39153e2c  /tmp/result-small
==> docker: Downloading /tmp/result-small => result-small
==> docker: Downloading /tmp/result-big => result-big
==> docker: Executing local command: md5 result-big result-small
    docker: MD5 (result-big) = 2f282b84e7e608d5852449ed940bfc51
    docker: MD5 (result-small) = b6d81b360a5672d80c27430f39153e2c
Attempt #4 ==================
    docker: 2f282b84e7e608d5852449ed940bfc51  /tmp/result-big
    docker: b6d81b360a5672d80c27430f39153e2c  /tmp/result-small
==> docker: Downloading /tmp/result-small => result-small
==> docker: Downloading /tmp/result-big => result-big
==> docker: Executing local command: md5 result-big result-small
    docker: MD5 (result-big) = 2f282b84e7e608d5852449ed940bfc51
    docker: MD5 (result-small) = b6d81b360a5672d80c27430f39153e2c
Attempt #5 ==================
    docker: 2f282b84e7e608d5852449ed940bfc51  /tmp/result-big
    docker: b6d81b360a5672d80c27430f39153e2c  /tmp/result-small
==> docker: Downloading /tmp/result-small => result-small
==> docker: Downloading /tmp/result-big => result-big
==> docker: Executing local command: md5 result-big result-small
    docker: MD5 (result-big) = 2f282b84e7e608d5852449ed940bfc51
    docker: MD5 (result-small) = b6d81b360a5672d80c27430f39153e2c
```

**Comment by justincampbell** [comment]
@jmccarthy I was using random so that compression wouldn't make the file size negligible. It shouldn't affect the test results, since the file is written and not modified after the initial `dd`.

**Comment by jmccarthy** [comment]
Got it.  I was unable to repro interactively even when using /dev/urandom -- the hashes matched every time I ran it manually.

**Comment by justincampbell** [comment]
Maybe it's the host OS? I was testing on an Ubuntu Vagrant box: https://github.com/justincampbell/packer-docker-vagrantfile

**Comment by jedineeper** [comment]
Hi guys, I reported this to @cbednarski initially, and I can repro this with the test case above?

https://gist.github.com/jedineeper/ee4e2ce74f09964b2885

Using packer 0.8.6 on a relatively up to date Ubuntu 14.04 virtualbox vm running under Windows7 Pro?

```
$ docker version                                                                                              
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Comment by cbednarski** [comment]
> Sounds from your comments above that it might well be my env though. :( Will run some checks in the meantime.

Even if that's the case we should fix it. I will be looking into this soon (likely later today).

**Comment by cbednarski** [comment]
After some further testing I think this is actually a race condition in the RPC layer between the file provisioner and the docker builder plugins, rather than a race condition in the docker download implementation.

Bytes copied from the container seems to match, though bytes copied to the `downloadWriter` are wrong. Since this does not fail every time, I've repro'd using [Justin's test script](https://gist.github.com/justincampbell/9dd8d9065b9f9f82b3a8) and [this python script](https://gist.github.com/cbednarski/be7f677a2ba96209c431). In one case this ran successfully about 15 times before hitting a mismatch.

I reimplemented the docker download communicator using `go-dockerclient` and ran into the same issue. The log below is from master (using the same code as 0.8.6).

```
2015/10/08 21:37:33 packer-builder-docker: 2015/10/08 21:37:33 Downloading file from container: 7e211a0af6e1b8b964a77b03873ccdd8bd195c98bd135559414c003b65d72cdb:/tmp/big
2015/10/08 21:37:34 packer-builder-docker: 2015/10/08 21:37:34 Copied 104857600 bytes for /tmp/big
2015/10/08 21:37:34 [INFO] 104857600 bytes written for 'downloadWriter'
-- it breaks here --
2015/10/08 21:37:34 packer-provisioner-file: 2015/10/08 21:37:34 [INFO] 104300032 bytes written for 'downloadWriter'
2015/10/08 21:37:34 packer-provisioner-file: 2015/10/08 21:37:34 [ERR] 'downloadWriter' copy error: write big: bad file descriptor
```

The failure logs from [my branch](https://github.com/mitchellh/packer/tree/b-2793) are slightly different because the implementation has changed, but they allude to the same problem.

**Comment by mitchellh** [comment]
@cbednarski Is this the custom communicator perhaps that Docker has that we built? In that case that sounds like a good fix scenario.
