### ISSUE TITLE
reduce the packer size

### ISSUE THREAD

**Issue by SydOps** [mitchellh/packer#2796]
The packer zip package is 132MB, I use it only for `amazon_ebs` build. 

I want to slim the package and upload to internal repostory. Should it be fine to only keep two files to run `packer validate & build`?
```
packer
packer-builder-amazon-ebs
```

**Comment by cbednarski** [comment]
Yep, that should work. Also, in packer 0.9.0 plugins will be compiled into the main binary so the entire thing will be around 26mb. See https://github.com/mitchellh/packer/pull/2608
