### ISSUE TITLE
support scheduler_hints for openstack builder

### ISSUE THREAD

**Issue by perarnau** [mitchellh/packer#2801]
In Openstack users can pass "scheduler hints" to the compute service to influence where an instance will be created. Those hints may also be required if Openstack Climate is active.  

Please consider adding an option to the Openstack Builder so that users can specify those hints in a packer template.

**Comment by mwhooker** [comment]
This isn't something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
