### ISSUE TITLE
Packer error on atlas

### ISSUE THREAD

**Issue by marouenj** [mitchellh/packer#2802]
Hi,

I get the following error at the very end of the build:

    ==> virtualbox-iso: Running post-processor: atlas
        virtualbox-iso (atlas): Uploading artifact version...
    Build 'virtualbox-iso' errored: 1 error(s) occurred:

    * Post-processor failed: Error uploading: Put https://binstore.hashicorp.com/984cc632-8b1c-4690-86b5-05ca87d7adc0: EOF

    ==> Some builds didn't complete successfully and had errors:
    --> virtualbox-iso: 1 error(s) occurred:

    * Post-processor failed: Error uploading: Put https://binstore.hashicorp.com/984cc632-8b1c-4690-86b5-05ca87d7adc0: EOF

    ==> Builds finished but no artifacts were created.

Hope someone can help.

**Comment by cbednarski** [comment]
@marouenj Thanks for the report! Our engineers were investigating some QOS issues related to this service earlier today. Hopefully this is a blip and will be working for you if you try again, but if it is not can you reach out via support@hashicorp.com so we can get some more info?
