### ISSUE TITLE
Switch docker builder over to go-dockerclient

### ISSUE THREAD

**Issue by markpeek** [mitchellh/packer#2809]
This is a placeholder issue to switch the docker code to use go-dockerclient which would clean up the existing code (e.g., the upload/download code). Due to needing more recent API changes (such as archive to copy from host to container) this would require updating the docker minimum requirement to 1.8+.

Related to: #901, #1752, #2436, #2581, #2675, #2697, #2807, #2832, #3102, #3222

**Comment by cbednarski** [comment]
I'm starting on this for the docker communicator as part of the work on #2793. I don't plan to do it all at once.

**Comment by jfusterm** [comment]
Hi @cbednarski , any plans to implement this anytime soon?

**Comment by rickard-von-essen** [comment]
@jfusterm I have started this work but it's progressing slowly, see #3921.

**Comment by mwhooker** [comment]
going to close and take care of in 4186
