### ISSUE TITLE
packer crash while building Windows box with Virtualbox on Linux

### ISSUE THREAD

**Issue by gildas** [mitchellh/packer#2817]
packer crash while building Windows box with Virtualbox on Linux
VM: Windows 2012R2
Virtualbox: 5.0.6
Linux: Mint Rebecca
Packer: 0.8.6

crash.log gist: https://gist.github.com/gildas/9f687899d625e7ff2f3f

**Comment by gildas** [comment]
Loading the crash log again.

**Comment by mwhooker** [comment]
There have been a lot of changes to packer since this was opened. Please try with the latest packer and open a new issue if you continue to see this crash. Thanks!
