### ISSUE TITLE
lin flavour no more available in parallels 11

### ISSUE THREAD

**Issue by faxioman** [mitchellh/packer#2820]
I'm unable to create a parallels box after upgrading parallels to Pro 11.
The error is:
```
Couldn't find Parallels Tools for the 'lin' flavor! Please, check the
value of 'parallels_tools_flavor'. Valid flavors are: 'win', 'lin',
'mac', 'os2' and 'other'
```
My parallels_tools_flavor settings is "lin"

**Comment by rickard-von-essen** [comment]
What is the output of:
```
prlctl --version
packer version 
packer validate <template.json>
```

**Comment by faxioman** [comment]
prlctl --version
```
prlctl version 11.0.1 (31277)
```
packer version 
```
Packer v0.8.6
```
packer validate <template.json>
```
Template validated successfully.
```

**Comment by faxioman** [comment]
Sorry, sorry, sorry :(
For some reason the file prl-tools-lin.iso was missing in my parallels installation.

Sorry again.
