### ISSUE TITLE
Building AWS EBS Windows AMI fails with SSH timeout error

### ISSUE THREAD

**Issue by rajinders** [mitchellh/packer#2823]
I am trying to build my very first Windows AWS EBS AMI.

I did a packer validate and I was told that `ssh_username` is required.
I am not sure why this is the case for a windows AMI.
Packer build fails due to SSH timeout error.

I am using a Windows Server 2012 R2 AMI from us east.

``` json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "us-east-1",
      "source_ami": "ami-c9cea0ac",
      "instance_type": "t1.micro",
      "ami_name": "polaris-web-101215 {{timestamp}}",
      "ami_description": "Polaris Web Base AMI Sept 2015",
      "ssh_username": "polarisadmin",
      "tags": {
         "OS_Version": "Windows 2012 R2",
         "Release": "Sept 2015"
        }
      }
   ],

  "provisioners": [
     {
       "type": "powershell",
       "inline": ["dir c:\\", "New-NetFirewallRule -DisplayName \"Allow Port 80\" -Direction Inbound -LocalPort 80 -Protocol TCP -Action Allow"]    
     }
  ]   
}
```

**Comment by rickard-von-essen** [comment]
I doubt that the source image provides SSH access. Verify how you connect to the image, if you use RDP see http://packer.io/docs/templates/communicator.html how to configure that properly.

Usage questions should be directed to Google Groups or IRC, see http://packer.io/community .
