### ISSUE TITLE
missing field in UploadArtifactOpts

### ISSUE THREAD

**Issue by megahall** [mitchellh/packer#2829]
I am getting this error compiling against `master` using `make dev`. I am posting here in case anybody else is running into this:

    1 errors occurred:
    --> darwin/amd64 error: exit status 2
    Stderr: # github.com/mitchellh/packer/post-processor/atlas
    post-processor/atlas/post-processor.go:168: unknown atlas.UploadArtifactOpts field 'CompileID' in struct literal

I worked around it using this but I am not sure if it's safe:

    diff --git a/post-processor/atlas/post-processor.go b/post-processor/atlas/post-processor.go
    index 7b8a4d9..08b0adb 100644
    --- a/post-processor/atlas/post-processor.go
    +++ b/post-processor/atlas/post-processor.go
    @@ -165,7 +165,7 @@ func (p *PostProcessor) PostProcess(ui packer.Ui, artifact packer.Artifact) (pac
                    ID:       artifact.Id(),
                    Metadata: p.metadata(artifact),
                    BuildID:  p.config.buildId,
    -               CompileID:  p.config.compileId,
    +               //CompileID:  p.config.compileId,
            }

            if fs := artifact.Files(); len(fs) > 0 {

**Comment by markpeek** [comment]
This is probably due to an out of date [atlas-go](https://github.com/hashicorp/atlas-go). Please try running ```make updatedeps``` to update it.

**Comment by StefanScherer** [comment]
Got the same error, but `make updatedeps` helped.

**Comment by cbednarski** [comment]
Dependencies are now vendored so you should not run into this problem anymore.
