### ISSUE TITLE
Permission denied errors when ansible uploads roles the second time

### ISSUE THREAD

**Issue by mtb-xt** [mitchellh/packer#2838]
I have two ansible provisioners, which are uploading all the roles:

```
{
             "type": "ansible-local",
             "playbook_file": "../../ansible/server-media.yml",
             "playbook_dir": "../../ansible",
             "inventory_file": "files/packer-media.hosts",
             "extra_arguments": [
                "--connection=local"
             ]
        },
        {
             "type": "ansible-local",
             "playbook_file": "../../ansible/application-media.yml",
             "playbook_dir": "../../ansible",
             "inventory_file": "files/packer-media.hosts",
             "extra_arguments": [
                "-e branch=production",
                "--connection=local"
             ]
        },    
```

Some of the roles are checked out from git and have files with read only permissions in them, like _ansible-consul_ role:

```
[user@shinkiro ansible]$ ls -lA roles/ansible-consul/.git/objects/pack/
total 124
-r--r--r-- 1 user user  18572 Oct 12 12:38 pack-dd44504d0b7a7557b71a6eb676ba2d86312feed2.idx
-r--r--r-- 1 user user 102850 Oct 12 12:38 pack-dd44504d0b7a7557b71a6eb676ba2d86312feed2.pack
```

When the second provisioner tries to upload the roles it fails with permission denied error from scp:

```
Build 'amazon' errored: Error uploading playbook_dir directory: scp: /tmp/packer-provisioner-ansible-local/roles/ansible-consul/.git/objects/pack/pack-dd44504d0b7a7557b71a6eb676ba2d86312feed2.idx: Permission denied

==> Some builds didn't complete successfully and had errors:
--> amazon: Error uploading playbook_dir directory: scp: /tmp/packer-provisioner-ansible-local/roles/ansible-consul/.git/objects/pack/pack-dd44504d0b7a7557b71a6eb676ba2d86312feed2.idx: Permission denied
```

This issue is fixed by adding an inline shell command to delete the folder in /tmp, but maybe the provisioner should either cleanup after every invocation or allow to exclude certain folders from uploads (like .git folders). Or is there some 'official' way to get around this and I'm not aware of it?

**Comment by worstadmin** [comment]
Bumping this. Hit it all the time

**Comment by cbednarski** [comment]
Thanks for the report. I think the fix is probably for us to use a randomly-named tmp folder to avoid this. E.g. `/tmp/packer-provisioner-ansible-local-34092874`.

**Comment by jhughes-mc** [comment]
Just ran into this, definitly an annoyance.

**Comment by alkhatib** [comment]
Running into this error, any workarounds?

**Comment by mwhooker** [comment]
Hi all. The solution here is to use a unique `staging_directory` for each of the builders. I've also put up a PR #4472 which should solve this. If someone here can test I can merge it in
