### ISSUE TITLE
clean up orphaned vm post build using vmware-iso builder and remote_host

### ISSUE THREAD

**Issue by jbarnett1981** [mitchellh/packer#2841]
Tested on Packer 0.8.6 and ESXi 5.5u2 host

After a successful vmware-iso build that connects to a given ESXi host via the remote_host field in the template, packer finishes up without error, but leaves behind an orphaned VM. This should be deleted as part of packer's post-build cleanup. Most likely people will be adding the .vmx to the inventory manually (or programmatically like I am) after the build, and with an orphan still out there adding the vmx to the inventory will fail.

**Comment by Sher-Chowdhury** [comment]
Hi jbarnett1981, 

Just wondering, once the packer build has completed, how do you make use of the end product? When I use the remote_host option, I found that I can't then use the vsphere post processor feature to upload it to our vsphere server.

**Comment by jbarnett1981** [comment]
@Sher-Chowdhury Well when you use the remote_host option, packer connects to a specific ESXi host and datastore and creates the build on that remote datastore. In this case you're not creating an image locally on the host running packer so they'll be no artifacts from the builder to then pass to a post processor. So it sounds like your workflow is acting normally...

The way I'm doing it is via the remote_host option in the vmware-iso builder. Once this is complete, I have an available vmdk/vmx, etc in my remote datastore within vSphere and from there I use pyvmomi to programmatically remove the stale orphan (as noted in this bug report) and add the image to the inventory as a template. 

Hope that helps!

**Comment by gobins** [comment]
I have noticed this issue as well. After a lot packer builds, we noticed that there are a lot of orphaned VMs. Not sure if the files were left for the post-processor to pick up and publish them.

**Comment by rickard-von-essen** [comment]
@rhass See #582 and #1824.

**Comment by mwhooker** [comment]
tracking in #4526
