### ISSUE TITLE
packer fails to start on OpenBSD

### ISSUE THREAD

**Issue by ajacoutot** [mitchellh/packer#2842]
It seems packer needs support for procfs which is not available in OpenBSD (amd64).
(packer_0.8.6_openbsd_amd64.zip)

$ uname -mrsv                                                  
OpenBSD 5.8 GENERIC.MP#1456 amd64
$ ./packer                                                     
Couldn't start Packer: readlink /proc/curproc/file: no such file or directory

**Comment by markpeek** [comment]
This appears to be due to [osext](https://github.com/mitchellh/osext/blob/master/osext_procfs.go#L21) not having the correct way to get the executable pathname from OpenBSD. I saw this [stackoverflow](http://stackoverflow.com/questions/31494901/how-to-get-the-executable-path-on-openbsd) question about the general issue. Do you know the canonical way to get the full path to the current executable in OpenBSD?

**Comment by ajacoutot** [comment]
Unfortunately, there's no safe and portable way to achieve that. And there's no native way on OpenBSD.
I don't speak go but as far as I can tell, it's only used to find the plugins directory.
Couldn't we make the first check out of the three ("First, look in the same directory as the executable") non fatal if it fails?

**Comment by ajacoutot** [comment]
That ugly workaround seems to work for now:
# mkdir -p /proc/curproc/
# ln -sf /path/to/packer /proc/curproc/file

I am definitely not advertising this, it is very bad and can have unexpected effects -- I am just saying that it allows me to use packer on OpenBSD until we can find a proper solution :-)

**Comment by ajacoutot** [comment]
Hi @markpeek 

This allows me to run Packer on OpenBSD :-)
https://github.com/kardianos/osext/pull/11

Hopefully it will make its way in soon...

**Comment by markpeek** [comment]
Excellent. Thanks for writing the openbsd osext code. I just posted a review comment on your change there. @mitchellh has deprecated https://github.com/mitchellh/osext so I will keep this open to track switching packer to use https://github.com/kardianos/osext.

**Comment by ajacoutot** [comment]
Indeed, that's why I didn't fork packer but kardianos.
That's excellent, thank you.

**Comment by cbednarski** [comment]
It looks like this has been fixed in master so I'm going to close this issue. Thanks @ajacoutot for the report and @markpeek for the fix!
