### ISSUE TITLE
Shrinking qcow2 images for QEMU builders

### ISSUE THREAD

**Issue by wzur** [mitchellh/packer#2853]
Hi there,

I use Packer to create Vagrant boxes for libvirt provider and to store them in HashiCorp's Atlas service. When I use zerodisk.sh script as per examples for other builders. As a result the image grows to the max defined size - 20GB in my case. I cannot figure out how and where I could insert something like `qemu-img convert -O qcow2 box.img original_image.qcow2` to shrink the image back to the size actually used.

At the moment I don't use zerodisk.sh at all, but that 'costs' me about 1GB of space too. This is still better than 20GB

Many thanks in advance,
  Waldemar

**Comment by cbednarski** [comment]
Thanks for the report! It sounds like this is something the QEMU plugin should take care of automatically.

**Comment by wzur** [comment]
ok - what is the way forward? Should I create a new feature request, or I just did that?

Waldemar

**Comment by vtolstov** [comment]
this is already created by me , check pr #2748

**Comment by cbednarski** [comment]
@vtolstov That looks great! Thanks for linking :grinning:

**Comment by wzur** [comment]
I don't know Go at all, apart of being similar to other programming languages, but just looking at builder.go for virtualbox-iso builder, the qemu builder is 'missing' an export step, which effectively has been implemented by @vtolstov. Is there any chance that change gets into a packer release any time soon?

**Comment by markpeek** [comment]
Closing and we will track this enhancement in PR #2748
