### ISSUE TITLE
Also is there a common encryption tool in packer to Encrypting and decrypting items in json like ohh say passowrds. that was going to be the next item i added packer but 

### ISSUE THREAD

**Issue by athingisathing** [mitchellh/packer#2857]
Is there a common encryption tool in packer to Encrypting and decrypting items in json like ohh say passowrds.

I would like to work on this but wanted to see if I was missing anything going on. I don't see any pulls or issues on it.

**Comment by cbednarski** [comment]
Thanks for opening an issue! Packer does not handle encryption of secrets, and we have no plans for it to do so.

There are many tools you can use to encrypt secrets, such as [gpg](https://www.gnupg.org), [vault](https://vaultproject.io), [AES](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard), [fernet](https://github.com/fernet/spec), and others. However, Packer is not a security tool and this is out of scope for the project.

**Comment by athingisathing** [comment]
How do you have secrets in plain text... I am not saying packer should be in the secrets game but encrypting and decrypting passwords based on a key is simple and makes for a better product for everyone.

**Comment by cbednarski** [comment]
@athingisathing The recommended way to pass secrets into a build is [by way of variables](https://www.packer.io/docs/templates/user-variables.html), rather than storing them in your packer template.

**Comment by athingisathing** [comment]
Duuuuuu thanks sorry for the stupid question!
