### ISSUE TITLE
Add tags to temporary security groups

### ISSUE THREAD

**Issue by matthiasfeist** [mitchellh/packer#2859]
In my team we had some build that crashed leaving our aws account with a lot of temporary packer security groups. Unfortunately those security groups to not get tagged so it is a nightmare to try to find out which can be be deleted safely and which can't.

So I would like to suggest to add the specified tags to the all temporary created resources as well.

**Comment by cbednarski** [comment]
Thanks for the suggestion. By default packer prefixes all of the security group names with `packer-` so you can easily identify and delete them. If you want to avoid deleting in-progress builds you can run a reaper script that deletes SGs older than a certain amount of time, or you can [create a security group in advance](https://www.packer.io/docs/builders/amazon-ebs.html#security_group_id) and share it between build jobs so packer does not need to create them for each build.
