### ISSUE TITLE
amazon-instance builder does not source `access_key` and `secret_key` from the standard locations.

### ISSUE THREAD

**Issue by grahamc** [mitchellh/packer#2861]
When running packer with the environment variables configured as as described in https://packer.io/docs/builders/amazon.html#specifying-amazon-credentials, the bundle upload step fails to run, as the command bundle upload command does not receive the credentials.

Here is how I've configured my environment (note: this does work with the `amazon-ebs` builder):

```
$ env
AWS_ACCESS_KEY_ID=MYACCESSKEY
AWS_SECRET_ACCESS_KEY=MYSECRETACCESSKEY
```

however the command called is:

```
Running: sudo -i -n ec2-upload-bundle -b mybucketname     \
    -m /tmp/image-1445612318.manifest.xml -a  -s  -d /tmp \
    --batch --region us-east-1 --retry
```

Note the `-a -s` segment: no key is passed here. However, this is not just a case of the output being scrubbed. If I alter my template file to explicitly specify access_key and secret_key, the parameters are passed correctly:

config:

``` json
{
    "builders": [
        {
            "type": "amazon-instance",
            "access_key": "{{user `access_key`}}",
            "secret_key": "{{user `secret_key`}}",
```

command called:

```
sudo -i -n ec2-upload-bundle -b mybucketname         \
    -m /tmp/image-1445614150.manifest.xml            \
    -a MYACCESSKEY -s MYSECRETACCESSKEY              \
    -d /tmp --batch --region us-east-1 --retry
```

**Comment by cbednarski** [comment]
Thanks for the detailed report. Unfortunately I think there's a bug in how we read environment variables for AWS or in how we pass them into the AWS library.

Related: https://github.com/mitchellh/packer/issues/2496 and https://github.com/mitchellh/packer/issues/2570
