### ISSUE TITLE
add checksum value to output

### ISSUE THREAD

**Issue by acqant** [mitchellh/packer#2862]
Is it zero?  It would help to print what the calculated checksum is.

    alpha-bvlt-r1n21: Error downloading: checksums didn't match expected: 63de1f09c49c9d7767719bb075f6acbf

**Comment by acqant** [comment]
Not sure if I'm the only one but I get this a lot on downloads.
bad Content-Length "-3780"

**Comment by cbednarski** [comment]
@acqant Thanks for opening an issue. I'm missing some context on what's happening here. Are you using the file provisioner? Are you trying to download packer from the website? I'm not sure.

Can you tell me which packer version you're using, which command you're running, and share a minimal template to reproduce, if relevant? Thanks!

**Comment by acqant** [comment]
Sorry Chris, this is from the json config downloading a iso file.  
My workflow is using jenkins which watches a chef repo and calls packer to make qcow and vagrant box files.  That works great.  I can download an ubuntu iso from the ubuntu download sites.

The next step is to use either the qcow or vagrant image that jenkins build and stores as an artifact.  It's that next packer job that is trying to pull the qcow file from jenkinks that always fails.

I worked around it by pulling the file down in the jenkins job and configuring packer to read the file system.  It seems jenkins http server specific.

**Comment by cbednarski** [comment]
Sorry to keep this open for so long. It sounds like the issue you described has to do with Jenkins and I'm not sure there's anything we can do on packer's side to resolve that.

If you are still having a problem with packer please feel free to open a new issue with more information about how you have setup your packer templates. Thanks!
