### ISSUE TITLE
New platform: LXD

### ISSUE THREAD

**Issue by battlemidget** [mitchellh/packer#2864]
Hi!

I would like to get a discussion started around the possibility of having LXD supported as a platform. Has this been asked before? Is this something that the packer team would be interested in? 

Thanks
Adam

**Comment by cbednarski** [comment]
@battlemidget Thanks for opening an issue! This is fairly new (and also fairly old since it's LXC under the hood) and I have not spent much time with it. I'd be happy to look at a PR for this but I don't have plans to implement this myself.

**Comment by battlemidget** [comment]
Cool, I'll take a stab at it

**Comment by sl1pm4t** [comment]
+1

**Comment by jgoldschrafe** [comment]
+1 @battlemidget, I'd love to collaborate on this if you have any public code thus far

**Comment by filterfish** [comment]
@battlemidget, given that this has no PRs associated with it surely it's been superceded by #3625?

**Comment by battlemidget** [comment]
Yea I'll close this one
