### ISSUE TITLE
Unable to disable headless mode

### ISSUE THREAD

**Issue by spyderdyne** [mitchellh/packer#2868]
what can I do to see why my vm cant be connected to via ssh if there is no way to disable headless mode?

$ packer -v
0.8.6

http://pastebin.com/B6zLxeUN

http://pastebin.com/0azhShPE

I have tried "headless": "false", and "headless": false, but it always tells me headless mode is enabled.

Thanks.

**Comment by cbednarski** [comment]
@spyderdyne The default is not headless. Does this still happen if you remove that option completely? Also, which version of virtual box are you using?

**Comment by spyderdyne** [comment]
VBox gui states 4.3.28

excluding the headless directive still shows headless disabled on push.

I have deleted my template and am being forced to use existing images for my project now since I am unable to create sane ones.  I will try to revisit this when I have some time.

Thanks.

**Comment by cbednarski** [comment]
Sorry you were not able to get this working. Since this issue is old I'm going to close but if you are still encountering a problem please open a new issue. Thanks!
