### ISSUE TITLE
pass .HTTPIP & .HTTPPort to usr or env variables

### ISSUE THREAD

**Issue by trodemaster** [mitchellh/packer#2869]
This is a feature request and currently works as designed. However I would find it very useful to access files shared by the packer http server within the running guest OS during build. 

Example usage in a windows template
https://gist.github.com/trodemaster/6f98b7bb349624898744

Log output showing the current result. See line 129
https://gist.github.com/trodemaster/eee75b1c1fd7002a1ebb

Streaming files from the host via HTTP is 1000x faster than the winrm file provisioner. I see value in using this as an alternative file transfer mechanism. Likely users would find other uses as well.

**Comment by cbednarski** [comment]
@trodemaster Thanks for opening an issue! I've run into this myself and I agree this would be a useful enhancement.

**Comment by trodemaster** [comment]
True on the caveat. Limiting it by builder type seems like an option. BTW builder/QEMU is also one I would need for this. Remote VMs is not a use case I have for this capability.

**Comment by AndrewFarley** [comment]
+1
