### ISSUE TITLE
how to tell packer not to delete the artifacts when an error occurs?

### ISSUE THREAD

**Issue by vvchik** [mitchellh/packer#2870]
it would be great if there was a way to tell packer not to delete the artifacts when an error occurs.

**Comment by cbednarski** [comment]
@vvchik thanks for the suggestion! I think this is a great idea and would be very useful. There is a ticket open for this here https://github.com/mitchellh/packer/issues/409 so I'm going to close this one, but feel free to provide any additional feedback in 409. Thanks!
