### ISSUE TITLE
File provisioner: .sock "files" are tried to be copied

### ISSUE THREAD

**Issue by vemv** [mitchellh/packer#2872]
If a directory I intend to copy contains a socket (e.g. "/var/rails/testapp/tmp/sockets/unicorn.sock"), the File Provisioner will try to copy it, failing the build.

Smart behavior would be skipping these .sock files I think?

Cheers - Victor

**Comment by cbednarski** [comment]
@vemv You've asked the file provisioner to do something and it can't, so it errors. This is preferable to the file provisioner silently ignoring things.

I think it is more straightforward to resolve this either by making sure there are no socket files in your upload directory, or by creating a tarball with the files you want to upload.

**Comment by vemv** [comment]
As I see it, a socket is a non-file. If I ask to copy a directory, then non-files are irrelevant and safe to skip silently (or semi-silently by logging the incident but not failing the task).

Feel free to close the issue if you disagree.

Cheers - Victor

**Comment by dave2** [comment]
I'd disagree with this. tar knows how to store such files (as nodes). That sockets have nothing to read from when something is not listening doesn't make it any less a file in how it's accessed. They are opened/read/written/closed exactly like files, but happen to be backed by a device or socket. I don't think that makes them "non-files" at all, not in a strict filesystem sense.

**Comment by mwhooker** [comment]
I don't think there's a good solution we can implement before 1.0. I recommend using existing tools to filter the file before uploading

**Comment by mwhooker** [comment]
related to #1811
