### ISSUE TITLE
Shell provisioner docs should indicate -e for Ubuntu example

### ISSUE THREAD

**Issue by vemv** [mitchellh/packer#2873]
If `mv`, `cp`, `chmod`, `git clone`, and surely many other commands visibly fail, the build isn't failed, producing useless artifacts.

Proof:

![screen shot 2015-10-27 at 05 24 59](https://cloud.githubusercontent.com/assets/1162994/10749490/1f22e046-7c6b-11e5-916e-8f922b541824.png)

Here one can see how cp, chmod, and update-rc.d all failed, but the build went on.

---

[The documentation](https://www.packer.io/docs/provisioners/shell.html) for inline shebang notes:

> Important: If you customize this, be sure to include something like the -e flag, otherwise individual steps failing won't fail the provisioner.

However, the example below for Ubuntu does not set the `-e` flag. We should add the `-e` flag here.

@cbednarski

**Comment by vemv** [comment]
Forgot to say, the script is passed as a file, not inline.

Maybe when passed as a file, internally this file could be split into lines and &&'ed?

`line1 && line2 && ...`

**Comment by rickard-von-essen** [comment]
You need to run your script with ```set -e``` to exist the script on the first command with a non 0 exit code.

See
http://www.tldp.org/LDP/abs/html/options.html
http://www.tldp.org/LDP/abs/html/exit-status.html

**Comment by vemv** [comment]
Ah yes, I see it's mentioned here https://www.packer.io/docs/provisioners/shell.html

I did originally read that doc page, but not that bit in particular (I had no reason to).

However, in the first FAQ item (which I _did_ follow), you accidentally recommend to use bash without -e.


> On Ubuntu, the /bin/sh shell is dash. If your script has bash-specific commands in it, then put #!/bin/bash at the top of your script. Differences between dash and bash can be found on the DashAsBinSh Ubuntu wiki page`

Please update `then put #!/bin/bash` to `then put #!/bin/bash -e`.

Thanks!

Victor
