### ISSUE TITLE
Debugging "Timeout Waiting for SSH"

### ISSUE THREAD

**Issue by NathanDotTo** [mitchellh/packer#2874]
Hi 

I am running packer build -debug in an attempt to debug why SSH is not working. According to #653 I should see the IP address that SSH is failing on, and so be able to try SSHing to that address myself to debug this. BUT, see below, no IP address, or really anything at all to help me debug.

==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Timeout waiting for SSH.
==> virtualbox-iso: Pausing before cleanup of step 'StepTypeBootCommand'. Press enter to continue. 

So, what can one do to debug this issue please?

Note that this build is only failing on my MBP, whilst it works perfectly well on my iMac, both running 10.11.1. I even have the same files, synced via DropBox, so this seems to be quite specific to something on this MBP, which is odd, and so well worth debugging.

Many thanks

Nathan

**Comment by NathanDotTo** [comment]
Hi

This time I ran the initial build with WIFI initially turned off whilst the VM was created (Virtual Box), and the SSH worked. I had to turn the WIFI back on at a later stage of the build so that the yum installs and so on would work, of course.

The overall build is still not healthy, and seems to be stuck now because a public key is not installed.

This makes me suspect some interaction with the public WIFI in this airport terminal (Barajas T4). This is not the debug I was looking for, but this *might* be helpful for someone else ...

Regards

Nathan

**Comment by rickard-von-essen** [comment]
Enable debug logging, PACKER_LOG=1 see the docs for more details.

**Comment by NathanDotTo** [comment]
https://www.packer.io/docs/other/debugging.html

Many thanks

Nathan

—
Nathan John Sowatskey
Full Stack Developer - Programmable Infrastructure, DevOps and SDN
nathan@nathan.to <mailto:nathan@nathan.to>
www.linkedin.com/in/nathandevops
XMPP: nathandotto@im.koderoot.net <mailto:nathandotto@im.koderoot.net>
Google: nathanjohnsowatskey@gmail.com <mailto:nathanjohnsowatskey@gmail.com>
Skype: nathan_sowatskey <skype:nathan_sowatskey>
Twitter: NathanDotTo
GitHub: https://github.com/DevOps4Networks
http://www.kipling.org.uk/poems_if.htm <http://www.kipling.org.uk/poems_if.htm>

**Comment by NathanDotTo** [comment]
I was able to replicate this issue on a different WIFI connection, to which I have regular access.

The first thing I was looking for was the IP address and port that was being used for SSH. 

There is a LOT of debug printed, but the actual IP address and port are NOT displayed in most messages which are of this format:

2015/10/31 11:46:22 packer-builder-virtualbox-iso: 2015/10/31 11:46:22 [INFO] Attempting SSH connection...
2015/10/31 11:46:22 packer-builder-virtualbox-iso: 2015/10/31 11:46:22 reconnecting to TCP connection for SSH
2015/10/31 11:46:22 packer-builder-virtualbox-iso: 2015/10/31 11:46:22 handshaking with SSH

This message is useful, but appears rarely:

2015/10/31 11:47:18 packer-builder-virtualbox-iso: 2015/10/31 11:47:18 [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:52321->127.0.0.1:3912: read: connection reset by peer

Since that message only appeared a few times amongst hundreds of others, the chances are that one will probably miss it. There is potential room for improvement here then.

Regards

Nathan

—
Nathan John Sowatskey
Full Stack Developer - Programmable Infrastructure, DevOps and SDN
nathan@nathan.to <mailto:nathan@nathan.to>
www.linkedin.com/in/nathandevops
XMPP: nathandotto@im.koderoot.net <mailto:nathandotto@im.koderoot.net>
Google: nathanjohnsowatskey@gmail.com <mailto:nathanjohnsowatskey@gmail.com>
Skype: nathan_sowatskey <skype:nathan_sowatskey>
Twitter: NathanDotTo
GitHub: https://github.com/DevOps4Networks
http://www.kipling.org.uk/poems_if.htm <http://www.kipling.org.uk/poems_if.htm>

**Comment by cbednarski** [comment]
Thanks for the feedback. Unfortunately packer doesn't know whether this connection is temporarily failing because of networking issues or the host not be ready yet, or if the connection will permanently fail. All we can do is retry until the time out happens.

There are a lot of failure modes for the SSH handshake so it's not feasible for us to special case these.
