### ISSUE TITLE
Provisioners: Explicit error when sudo required but not usable

### ISSUE THREAD

**Issue by mafrosis** [mitchellh/packer#2883]
I had a problem (as seen on the mailing list) where I was unable to get the Salt provisioner to complete - it was ending with the message:

```
sudo: no tty present and no askpass program specified
```

This was caused by my configured `ssh_username` user not being able to use sudo without a password. (So sudo asks for one with a TTY).

I think it might make sense to have a mechanism to check for sudo capability early, and then exit with a well defined error message. A quick check shows that sudo is used in the chef and puppet provisioners also, so they could benefit from this. Thoughts?

**Comment by cbednarski** [comment]
Thanks for the suggestion! I agree this would be useful, though I think the error message is fairly helpful already. I'd be happy to review a PR to add this functionality.

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
