### ISSUE TITLE
packer corrupts files on download

### ISSUE THREAD

**Issue by nathwill** [mitchellh/packer#2885]
i've been experimenting with some app packaging pipelines, and [this](https://github.com/nathwill/app-packaging) packer configuration for building minimal rootfs trees, but every time, the resultant archive is corrupted, and as best as i can tell it's the packer file download provisioner corrupting it somehow.

the problem...

```bash
[vagrant@localhost target]$ tar tf build.tar 
./
./lib64
...
./usr/libexec/git-core/git-imap-send
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

so, in [this commit](https://github.com/nathwill/app-packaging/commit/a3377ae9501233e9261b9a0c615d0ad3ecedc0f2) i cut out the compression step to narrow it down, and inserted a sleep so i could inspect the file inside the container (`docker exec -it $container_id tar tf /build.tar`) and fetch the source file for comparison (`docker cp $container_id:/build.tar build.tar`), and sure enough the source file is fine before it passes through the file download provisioner, both inside the container and after being copied out through `docker cp`.

```bash
[vagrant@localhost vagrant]$ docker exec -it b7b41eb1aa5b bash
[root@b7b41eb1aa5b /]# tar tf /build.tar 
./
./lib64
...
/opt/ruby-build/bin/rbenv-uninstall
```

```bash
[vagrant@localhost vagrant]$ docker cp b7b41eb1aa5b:/build.tar build.tar
[vagrant@localhost vagrant]$ du -hs build.tar 
609M	build.tar
[vagrant@localhost vagrant]$ tar tf build.tar 
./
./lib64
...
./opt/ruby-build/bin/rbenv-uninstall
[vagrant@localhost vagrant]$ echo $?
0
```

how reproducible: always
steps to reproduce:
  - clone https://github.com/nathwill/app-packaging
  - vagrant up
  - vagrant ssh
  - packer build my-app-packer.json

**Comment by cbednarski** [comment]
@nathwill Thanks for the report. This was the result of a race condition in the docker downloader and it should be [fixed](https://github.com/mitchellh/packer/pull/2825) in master now. The patched version is also running in Atlas. Can you try building from master and let me know if you're still experiencing this?

**Comment by nathwill** [comment]
oh, that's fantastic, thanks for the quick reply! i'll give it a shot and report back.

**Comment by nathwill** [comment]
no luck

```bash
[vagrant@localhost vagrant]$ du -hs target/my-app-latest.gz 
32M	target/my-app-latest.gz
[vagrant@localhost vagrant]$ du -hs build.tar.gz 
198M	build.tar.gz
[vagrant@localhost vagrant]$ tar tzf target/my-app-latest.gz 1>/dev/null

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
[vagrant@localhost vagrant]$ packer --version
0.8.7
```

**Comment by nathwill** [comment]
mmm i should note, i only got a `packer` binary out of the build, so all the plugins are still from 0.8.6... looking at the patch, i think that should be enough, but if not, can you advise on doing a local build to produce the plugins as well? neither `make` nor `make dev` produced any binaries beyond the `packer` binary that i could see

**Comment by cbednarski** [comment]
@nathwill Ah. Packer plugins are compiled into the binary now, so you will need to delete or backup the old plugins, or run the new version of packer from a different directory.

**Comment by nathwill** [comment]
oho, big change! cool, i'll try running it from the app root and see if that helps. i did notice that the docker builder seems to implement its own communicator using `docker cp $args -` to generate a tar stream, is it possible there's a race there as well?

**Comment by nathwill** [comment]
hmmm, so far so good, i got through several builds without a truncated download, which is definitely progress with the new binary. i'll keep fiddling around and revisit this if i see any other problems, but i think i can confirm the fix for now :+1: thanks again for the help!

**Comment by cbednarski** [comment]
> oho, big change!

Yes! I need to update the changelog. Sorry to be sneaky about that one!

> i did notice that the docker builder seems to implement its own communicator using docker cp $args - to generate a tar stream, is it possible there's a race there as well?

This is heavily tested and I haven't seen a race here. In fact, the unit tests cover this and that's why the bug was not caught sooner.

As you noted there are two downloads: One from docker to the packer plugin (which you just pointed out) using the docker cp command, and then a second between the packer plugin and the packer main binary over the RPC interface. The race that caused this problem was in the RPC interface.

There is now also a test covering the second case and I ran a build exercising this in an acceptance scenario over 50 times and I haven't seen it show up again. There are possibly still some race conditions lurking in other parts of packer, but hopefully this one is fixed!

> hmmm, so far so good, i got through several builds without a truncated download, which is definitely progress with the new binary. i'll keep fiddling around and revisit this if i see any other problems, but i think i can confirm the fix for now :+1: thanks again for the help!

Glad to hear it! Let me know if you have any other issues.
