### ISSUE TITLE
Qemu + Osx

### ISSUE THREAD

**Issue by FRVisser** [mitchellh/packer#2886]
I tried the basic qemu example. But I got the error:

```
2015/10/29 22:02:39 packer-builder-qemu: 2015/10/29 22:02:39 Started Qemu. Pid: 17479
2015/10/29 22:02:39 packer-builder-qemu: 2015/10/29 22:02:39 Qemu stderr:
2015/10/29 22:02:39 packer-builder-qemu: 2015/10/29 22:02:39 Qemu stderr: (process:17479): GLib-WARNING **: gmem.c:482: custom memory allocation vtable not supported
2015/10/29 22:02:39 packer-builder-qemu: 2015/10/29 22:02:39 Qemu stderr: qemu-system-x86_64: -display sdl: SDL support is disabled
```

 I installed qemu via homebrew but I think this is without SDL option. Is there a workaround?

**Comment by cbednarski** [comment]
@FRVisser Maybe you need to use the `--with-sdl` option when installing QEMU? Maybe something like this:

```
brew uninstall qemu
brew install qemu --with-sdl
```

**Comment by FRVisser** [comment]
Thanks for the quick reply. I already tried that but gave up on it eventually. But it actually is the solution. the only problem the uninstall qemu has an error. Executing sudo brew uninstall qemu was the solution.
Thanks! Easy fix!

**Comment by vikas027** [comment]
As on Feb 2018, it is recommended to use 

```
brew install qemu --with-sdl2
```

**Comment by DryFire117** [comment]
> As on Feb 2018, it is recommended to use
> 
> ```
> brew install qemu --with-sdl2
> ```

I now have an issue when running this command:

> ```
> Error: invalid option: --with-sdl2
> ```

When I run 
> ```
> brew info qemu
> ```

The only option I see is --HEAD

**Comment by Chrislevi** [comment]
Any news? the problem seems to consist + the --with-sdl option was removed.. any workaround?
