### ISSUE TITLE
vmware-iso builder "format" errors with "unknown configuration key"

### ISSUE THREAD

**Issue by JoshLitt** [mitchellh/packer#2892]
Seen in 0.8.6 release on Linux 64-bit.

Maybe this is due to the typo in packer/builder/vmware/iso/builder.go on line 43, where "mapstructure" is missing a 'c'. I don't know GO, so that's just a guess.

```go
Format string `mapstruture:"format"`
```

**Comment by cbednarski** [comment]
Ah good catch! Thanks

**Comment by higebu** [comment]
@JoshLitt Thank you for finding the typo. I fixed it and made PR now. But 0.8.6 doesn't support `format` option. It may be available since 0.8.7. See https://github.com/mitchellh/packer/pull/1921.

**Comment by JoshLitt** [comment]
Thanks. I got ahead of the feature, I guess. Can't wait for it to be in a release. Glad the thread on the PR describes a workaround with shell-local in the meantime.

**Comment by markpeek** [comment]
Thanks!
