### ISSUE TITLE
HTTPPort variable is set to value 0

### ISSUE THREAD

**Issue by ervitis** [mitchellh/packer#2896]
Hello.

I am having some problems when I am trying to create a virtualbox machine. When it runs the configuration step and it tries to connect with the ssh protocol the value for the HTTPPort variable is set to 0.

**Comment by rickard-von-essen** [comment]
Enable packer debug logging, PACKER_LOG=1, see the docs. And rerun a build,
gist the log file, your config template and script/http files. Also provide
some info about your packer, VirtualBox, and OS version.

**Comment by ervitis** [comment]
Thank you so much.

My template: https://github.com/beeva-victormartin/packer_example/blob/master/template.json
My config file: https://github.com/beeva-victormartin/packer_example/blob/master/http/ks.cfg
Log: https://gist.github.com/ervitis/6d624b5c0a4e6b7b2789

My Virtualbox version is 5.0.4 Ubuntu version.
My packer version is 0.8.6.
My OS version is Ubuntu 15.10 Mate version for 64 bit.

**Comment by markpeek** [comment]
Please try again after adding ```http_directory``` to the template. From the docs [here](https://packer.io/docs/builders/virtualbox-iso.html#boot_command):

"HTTPIP and HTTPPort - The IP and port, respectively of an HTTP server that is started serving the directory specified by the http_directory configuration parameter. If http_directory isn't specified, these will be blank!"

**Comment by ervitis** [comment]
Oh my... I forgot it. Thank you so much
