### ISSUE TITLE
"uri_template" or similar in variable files for URI to template to use

### ISSUE THREAD

**Issue by khaije1** [mitchellh/packer#2897]
=TLDR=
Setting the template file in the variable file supports this workflow and helps manage complexity by using the variable file a single entry point.

=Background=
The usage pattern I'm gravitating toward is using a small number of highly parameterized template files with a larger number of variable files. 
To organized this - so far - I've been using file naming conventions such that CentOS-vagrant-vmware.vars will match with vagrant-vmware.template . 
I value the way this scheme lends itself to quick groking and fearless experimentation. To try a new configuration a variable is shadowed by providing a higher precedence alternative on the command line, then if the outcome of the change is desirable, it can become it's own variable file.

=Problem=
This is already working well but it seems to me that to manage complexity over time, it would be better to support a 'variable-file'-centric workflow. 

=Proposed Solution=
Packer will allow setting the URI of the template file via a variable in a HCL variable file or as an argument on the command line.
To preserve sanity this should support relative paths from the CWD, and absolute paths*. 

For example:
{  
  "some_other_configs": "boblohblaw",
  "uri_template": "relapath/from/CWD 
}

Will allow the commandline(s) ...
$> packer -var-file=./mycustom.vars
-or-
$> packer -var-file=./mycustom.vars -var='uri_template=./some/partic/file.template'
... to work properly because the location of the template will be picked up with appropriate precedence.

Notably, this does nothing to prevent or degrade current usage patterns.

**Comment by cbednarski** [comment]
> Packer will allow setting the URI of the template file via a variable in a HCL variable file or as an argument on the command line.

Thanks for the suggestion. We've considered migrating to HCL and would like to do this but it is unlikely to make it into packer in the near-to-medium term for backwards-compatibility reasons. It's a significant change, requires rewriting a lot of internals, and can't be done incrementally since everything is in the same file right now. For now I would recommend using a pre-processor or templating tool to generate your configs.
