### ISSUE TITLE
Template function plugins

### ISSUE THREAD

**Issue by thyming** [mitchellh/packer#2899]
Apologies if I missed an existing question about this. 

I'm wondering if there's been any work done or decisions made about incorporating template functions as an interface against which plugins can be written. In Ansible, for example, I've really liked the ability to extend the built-in template functions. I could be mistaken but based on a cursory glance at the code I found no similar way to extend the functions in Packer templates. 
Is there a philosophical reason for having a fixed set of the template functions?
I'd love to be able to write my own.
This is something I'd be willing to work on if there's interest.

**Comment by cbednarski** [comment]
Thanks for opening an issue! Unfortunately this is not feasible for us to support.

> In Ansible, for example, I've really liked the ability to extend the built-in template functions.

Ansible uses python behind the scenes, which means there is a full language interpreter available.

To do this in Packer we would have to embed an interpreter or you would need to recompile packer to add a function (you can use the latter approach now).

Internally, though, scoping in packer is extremely limited. For example, a provisioner knows nothing about the builder it's running in; it's only provided with a connection to the host, and you may have multiple builders running in parallel. As a result, evaluating packer's internal state at any given point in time (e.g. to pass data to a function) is extremely complicated.
