### ISSUE TITLE
Strange build error using salt with packer.

### ISSUE THREAD

**Issue by papiveron** [mitchellh/packer#2902]
Hi,

I'm looking since this weekend where my error could come from.

In fact I'm trying to build and aws ec2 ami with packer and salt provisioner without success, but when I launch an empty instance from aws console with the same ami, instance profile, .... and run the exactly same salt states on the new instance it works.

From packer :

```
 admin@ip-10-4-27-123]~❯❯❯sudo packer build tmp/packer/f2cd1875-9ed8-44a2-a191-423d468d70cb.json
```

Not working the error at the end of my message.

Packer json template

```
admin@ip-10-4-27-123]~❯❯❯cat /tmp/packer/f2cd1875-9ed8-44a2-a191-423d468d70cb.json

{
    "builders": [
        {
            "ami_block_device_mappings": [],
            "ami_name": "ami.prod.us-west-2.search.nixmind-solr5-slave.20151102-092307",
            "associate_public_ip_address": "1",
            "instance_type": "t2.micro",
            "region": "us-west-2",
            "source_ami": "ami-d9183ce9",
            "ssh_username": "admin",
            "subnet_id": "subnet-a8b022f1",
            "type": "amazon-ebs",
            "vpc_id": "vpc-a32e7ac6"
        }
    ],
    "provisioners": [
        {
            "local_pillar_roots": "/tmp/salt/f2cd1875-9ed8-44a2-a191-423d468d70cb/pillar",
            "local_state_tree": "/tmp/salt/f2cd1875-9ed8-44a2-a191-423d468d70cb/salt",
            "skip_bootstrap": true,
            "type": "salt-masterless"
        }
    ]
}
```

And the commands below on a new launched instance works without any error or fail as you can see in the screenshot attached.

```
admin@ip-10-4-27-123]~❯❯❯cd /tmp/salt/f2cd1875-9ed8-44a2-a191-423d468d70cb
admin@ip-10-4-27-123]/tmp/salt/f2cd1875-9ed8-44a2-a191-423d468d70cb❯❯❯ sudo salt-call --local --file-root=salt --pillar-root=pillar state.highstate
```

![state_succeed](https://cloud.githubusercontent.com/assets/8174194/10884809/4faa6e14-817a-11e5-8252-9ffb9f92e792.png)
when I run with packer like above, I have no error in the output, only **[INFO]**, and at the end of the output I have this :

```
2015/10/31 23:05:55 GMT: ==> amazon-ebs: Terminating the source AWS instance...
2015/10/31 23:06:38 GMT: ==> amazon-ebs: No AMIs to cleanup
2015/10/31 23:06:38 GMT: ==> amazon-ebs: Deleting temporary security group...
2015/10/31 23:06:38 GMT: ==> amazon-ebs: Deleting temporary keypair...
2015/10/31 23:06:38 GMT: Build 'amazon-ebs' errored: Error executing highstate: Bad exit status: 2
2015/10/31 23:06:38 GMT: error-count: 1
2015/10/31 23:06:38 GMT: \n==> Some builds didn't complete successfully and had errors:
2015/10/31 23:06:38 GMT: error: Error executing highstate: Bad exit status: 2
2015/10/31 23:06:38 GMT: --> amazon-ebs: Error executing highstate: Bad exit status: 2
2015/10/31 23:06:38 GMT: \n==> Builds finished but no artifacts were created.
2015/10/31 23:06:38 GMT: ERROR: ami_id not found. The packer process had maybe fail.
```

So i would like to know what packer uses to raise errors? The salt return code or anything else?
Where and how can I get what goes wrong with packer or what it thinks it's not good please?

Thank you for your great help.

Regards.

**Comment by donfaruco** [comment]
I started having similar issue this weekend as well.  It almost seems as if it does not recognize salt is installed or salt-call is not in the path.

**Comment by donfaruco** [comment]
This is a salt issue.  The latest bootstrap script does not install salt correctly making unusable.  They have an open issue in the bootstrap project.

**Comment by rickard-von-essen** [comment]
@donfaruco Could you link the issue on the bootstrap project?

**Comment by mwhooker** [comment]
Going to close this for now. Please open a new issue if this is still a problem
