### ISSUE TITLE
Retry failed uploads with Atlas post-processor

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2905]
Sometimes an upload to Atlas fails because of a network hiccup or other transient error. Since the build completed successfully we should try again to upload it.

Packer already has retry wrappers all over the place so I'm surprised that this does not have one already, but we should be able to copy some code over.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but isn't something we're targeting for 1.0, so I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
