### ISSUE TITLE
Rackspace - Error getting SSH config: Error setting up SSH config: asn1: structure error: superfluous leading zeros in length

### ISSUE THREAD

**Issue by brandfocus** [mitchellh/packer#2907]
2015/11/03 14:23:55 packer-builder-openstack: 2015/11/03 14:23:55 Waiting for state to become: [ACTIVE] currently BUILD (80%)
2015/11/03 14:23:57 packer-builder-openstack: 2015/11/03 14:23:57 Waiting for state to become: [ACTIVE] currently BUILD (80%)
2015/11/03 14:23:59 packer-builder-openstack: 2015/11/03 14:23:59 Waiting for state to become: [ACTIVE] currently BUILD (80%)
2015/11/03 14:24:02 packer-builder-openstack: 2015/11/03 14:24:02 Waiting for state to become: [ACTIVE] currently BUILD (80%)
2015/11/03 14:24:04 packer-builder-openstack: 2015/11/03 14:24:04 Waiting for state to become: [ACTIVE] currently BUILD (80%)
2015/11/03 14:24:06 packer-builder-openstack: 2015/11/03 14:24:06 Waiting for state to become: [ACTIVE] currently BUILD (80%)
2015/11/03 14:24:08 packer-builder-openstack: 2015/11/03 14:24:08 Waiting for state to become: [ACTIVE] currently BUILD (100%)
2015/11/03 14:24:10 packer-builder-openstack: 2015/11/03 14:24:10 [INFO] Waiting for SSH, up to timeout: 5m0s
2015/11/03 14:24:10 ui: ==> openstack: Waiting for SSH to become available...
2015/11/03 14:24:10 packer-builder-openstack: 2015/11/03 14:24:10 [DEBUG] Using AccessIPv4 ********* for SSH
==> openstack: Waiting for SSH to become available...
2015/11/03 14:24:10 packer-builder-openstack: 2015/11/03 14:24:10 [DEBUG] Error getting SSH config: Error setting up SSH config: asn1: structure error: superfluous leading zeros in length

**Comment by rickard-von-essen** [comment]
Probably duplicates #2526

**Comment by rickard-von-essen** [comment]
Duplicates #2526
