### ISSUE TITLE
Using STDIN or script to generate variables

### ISSUE THREAD

**Issue by nathanielks** [mitchellh/packer#2914]
Happy Wednesday, all!

There are a few variables I need to use for my packer build that I'd like to populate programatically and am running into a wall. I've got a script that will generate json that I _could_ write to a file and then pass that file as a `-var-file`, but I'd prefer not to persist this file anywhere. I tried using the `-var-file` flag with the script, but it generates a parsing error (as tries to read the json as a file path instead of the content of the file).

I also tried generating multiple `-var` declarations, storing that in a variable, and running it like `packer build $VARS` and it didn't like that either. It yells at me saying `flag provided but not defined: -var 'aws_access_key`. The string of vars looks like this:
```
-var 'aws_access_key=REDACTED' -var 'aws_secret_key=REDACTED'
```

Do y'all have any other ideas of how to achieve this? Would it be possible to pass json into STDIN and let packer process that?

**Comment by markpeek** [comment]
Right now stdin is reserved for being able to pass a template via stdin: ```cat template.json | packer build -```. I would suggest just using environment variables in your script, putting those into the variables portion of the template, and using that as a way to pass between the two.

**Comment by cbednarski** [comment]
You could also pipe the base template through some other program (e.g. a python script, for example) to apply the changes. Something like:

```
cat template.json | python variables.py | packer build -
```

This way it does not land on the filesystem.

> I also tried generating multiple -var declarations, storing that in a variable, and running it like packer build $VARS and it didn't like that either.

I think for this approach you will need to use `xargs` to split the arguments apart.

**Comment by nathanielks** [comment]
Aha! I think `jq` would be of great use here. I can take the json I generate and modify the `variables` section of the template. Great ideas @markpeek @cbednarski!
