### ISSUE TITLE
Check for out-of-date plugins

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2915]
With the switch to integrated plugins there's a high probability we're going to run into weird errors when packer boots up old plugins from the filesystem.

We should check the version of the plugin when we start it up and make a really noisy warning if it doesn't match.

Note that we may want different behavior for built-in plugins vs. third-party plugins. For example we can warn if a third-party plugin doesn't match but error if a built-in plugin doesn't match.

It's likely that a third-party plugin built against an older packer version will continue to work and we should support this use-case since the older plugin may be hard to recompile. On the other hand, we want to force people to upgrade the internal plugins so they get the latest bug fixes and don't run into unexpected failures because of internal changes.

**Comment by mwhooker** [comment]
I think this is probably less of a problem now then it was when this ticket was opened.

It would be great to get a version check in place, but I don't think that's a high priority. Maybe when we move to go-rpc and avro... (or go-plugin!)
