### ISSUE TITLE
Powershell Provisioner: Attempts to upload elevated provision scripts without retry

### ISSUE THREAD

**Issue by chrissimon-au** [mitchellh/packer#2916]
Initially reported here: https://github.com/packer-community/packer-windows-plugins/issues/65

The powershell provisioner has the facility to run a script in an elevated shell on the instance.  It does so by uploading and running a script that creates a scheduled task which is permitted to run elevated.

When running a regular script, the upload&run of the script is wrapped in a retry.  However, for elevated shells, the upload process is not wrapped in a retry, and can fail if the instance has just rebooted and is still booting up.

On [line 454 of powershell/provisioner.go](https://github.com/mitchellh/packer/blob/master/provisioner/powershell/provisioner.go#L454) is the key line.

There are two workarounds:
1. Use a large 'pause_before'
   - Can still have intermittent failures if there are delays or inconsistent timing
   - Makes the process much slower than it needs to be
2. Embed a 'fake' non-elevated script just prior to the elevated script
   - The non-elevated script is wrapped in the retry, so will appropriately wait for the instance to be alive before running
   - The elevated script will only run after the non-elevated script, so we can be sure the instance is alive

Workaround 2 is 'better', but still a bit hacky.  

Would be nice if the elevated upload was wrapped in a retry, for consistent processing and cleanliness of packer files.

I don't have a Go environment, but if I get a chance this weekend I'll see if I can put together a PR.

**Comment by cbednarski** [comment]
@chrissimon-au Thanks for the report! There is a change in master that makes subsequent provisioners wait for a restart to complete https://github.com/mitchellh/packer/pull/2568. This is essentially the correct way to do the "pause_before" you mentioned. So if I understand correctly, I think this is already fixed in master. Can you try building packer from source to see if the fix works for you?

**Comment by chrissimon-au** [comment]
Hi @cbednarski, thanks for the reply - that could well fix the issue for our use case!

Does that mean that the `start_retry_timeout` setting, and the `retryable` implementation for non-elevated scripts is now redundant?

If there is still a reason for the non-elevated scripts to be `retryable`, then I think the elevated scripts should follow the same behaviour, but it's certainly less important for us if packer itself can wait for reboot complete!

Will give the master a try and let you know.

**Comment by cbednarski** [comment]
> Does that mean that the start_retry_timeout setting, and the retryable implementation for non-elevated scripts is now redundant?

Possibly. I'm not sure what the design background is for that. We can extend the retry to both but I'd like to clarify whether this is needed as a bug or is an additional feature so I can test it appropriately.

**Comment by chrissimon-au** [comment]
@cbednarski - it's more for consistent behaviour with the docs: https://www.packer.io/docs/provisioners/powershell.html#start_retry_timeout

The implications of that setting are that it applies for any script, whether or not it is run using an elevated script.

**Comment by cbednarski** [comment]
@chrissimon-au Thanks for the docs link. The design here is to make things work during a reboot. I think there is a different mechanism for doing this now so if that new mechanism is working I think it's safe to omit (and eventually remove from the unelevated version of the provisioner).
