### ISSUE TITLE
VMWare disk_type_id doc is not correct

### ISSUE THREAD

**Issue by dantran** [mitchellh/packer#2917]
this settings is actually is used to configure diskformat ( vmdktool -d param)

**Comment by dantran** [comment]
the correct way is to add diskformat setting and defualt to  'zeroedthick', and then correctlhy implement disk_type_id per current doc

**Comment by mwhooker** [comment]
Not sure I follow, but that's maybe because this has changed since this ticket was opened. Can you please double check that this is right, now? Or, better yet, a PR would be very helpful
