### ISSUE TITLE
vmware-iso builder on ESXi: ks=floppy not found: workaround

### ISSUE THREAD

**Issue by matt-deboer** [mitchellh/packer#2920]
Recently, I was trying to build a centos 7.1 image using the vmware-iso builder through an AnyConnect VPN tunnel, and the HTTP ks option stopped working (no surprise there). 

So, based on the note here https://www.packer.io/docs/builders/vmware-iso.html, I tried the ks=floppy option (with my ks.cfg file listed in the "floppy_files" array). The auto-install failed to locate my ks file, and halted in the text shell.

After I did some investigation (mounted /dev/fd0 and took a look), I found that my ks file (which I had specified in the floppy_files as "ks.cfg" (lowercase), was visible to the system as **"KS.CFG"** (uppercase).

I first tried "ks=floppy:/KS.CFG" to no avail, but found success with  __"ks=hd:fd0:/KS.CFG"__.

__workaround:__
Here's the meaningful parts of the json config:

    ...
    "iso_url": "http://centos.mirrors.hoobly.com/7/isos/x86_64/CentOS-7-x86_64-Minimal-1503-01.iso",
    "boot_command": [
        "<tab> text ks=hd:fd0:/KS.CFG<enter><wait>"
    ],
    "floppy_files": [
        "http/ks.cfg"
    ],
    ...

don't know where the problem lies for the uppercasing of this filename, but hopefully this can help someone else who stumbles on the same issue

context: __packer 0.8.6, ovftool 4.1.0, vmware fusion 8.0.2, OSX 10.10.3__

**Comment by Ancillas** [comment]
I also saw that the filename was capitalized on fd0, but I was able to get the RHEL 7 installer to use KS.CFG using a lowercase filename: `inst.ks=hd:fd0:/kf.cfg`.

**Comment by kikitux** [comment]
@matt-deboer it seems the lowercase/capital can be due floppy is case insensitive?

Per https://github.com/mitchellh/packer/pull/2931 looks like ks=floppy has been deprecated, so not sure what can be fixed on packer other than documentation?

Are you happy that is working for you, so we can close this?

**Comment by matt-deboer** [comment]
Yeah, a doc note is probably the best that could be done.
Yes, you can close-- it's working fine now; btw, packer is awesome; thanks
to the team for sharing it with the community.

**Comment by kikitux** [comment]
closed by https://github.com/mitchellh/packer/pull/2931

**Comment by godenji** [comment]
Sorry to necropost but just argggghhhhh, in rhel 5 and 6 you could mount floppy via esxi with `ks=hd:fd0/ks.cfg`, and now in rhel 7 it's `ks=hd:fd0:/ks.cfg`.

Setting debug loglevel is of no use either as installer just hangs without any output until dracut times out.

Anyway, thanks for the extra colon!
