### ISSUE TITLE
Guest additions upload over WinRM can fail silently and continue (MaxMemoryPerShellMB)

### ISSUE THREAD

**Issue by dusek** [mitchellh/packer#2921]
Based on the powershell's `MaxMemoryPerShellMB` value, when set too low (as is e.g. case with Win 7 x64 Pro without SP1), uploading the `VirtualBoxGuestAdditions.iso` can fail - see packer-community/winrmcp#9 as the issue is reproducible even when using winrmcp directly from command-line (in the issue, if interested, also find more detail about size of the file, workaround, pointer to location in winrmcp source code where the issue happens and what OS I am running on and the guest OS).

The issue with packer (or maybe with winrmcp - can't tell without digging more deep) is that the error is not ultimately detected by packer, nothing suggesting an error is logged at all (at least without `-debug`), and packer continues with provisioning the VM as if no error happened.

Here is packer output with `-debug`:

```
==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
2015/11/08 12:45:39 packer-builder-virtualbox-iso: #< CLIXML
2015/11/08 12:45:40 packer-builder-virtualbox-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">Exception calling "FromBase64String" with "1" argument(s): "Byla vyvol?na vyjim_x000D__x000A_</S><S S="Error">ka typu System.OutOfMemoryException."_x000D__x000A_</S><S S="Error">At line:15 char:47_x000D__x000A_</S><S S="Error">+             $bytes = [System.Convert]::FromBase64String &lt;&lt;&lt;&lt; ($base64_string)_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : DotNetMethodException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">Exception calling "WriteAllBytes" with "2" argument(s): "Hodnota nemuze byt NUL_x000D__x000A_</S><S S="Error">L._x000D__x000A_</S><S S="Error">N?zev parametru: bytes"_x000D__x000A_</S><S S="Error">At line:16 char:35_x000D__x000A_</S><S S="Error">+             [System.IO.File]::WriteAllBytes &lt;&lt;&lt;&lt; ($dest_file_path, $bytes)_x000D__x000A_</S><S S="Error">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : DotNetMethodException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>2015/11/08 12:45:40 Running the provision hook
2015/11/08 12:45:40 ui: ==> virtualbox-iso: Provisioning with windows-shell...
```

(sorry, the error message is in Czech as that is the language of Windows guest OS, see the winrmcp issue linked above for translation if interested)

I am not sure whether this is winrmcp not detecting the error therefore not passing it to packer thus giving packer no chance to know something was wrong, or whether this is winrmcp passing information about the error, but packer ignoring it.

Running packer 0.8.6, VirtualBox 5.0.8

**Comment by kikitux** [comment]
Hello 

Those parameters are usually to be set at the installation configuration. ie UnAttended.xml

[https://technet.microsoft.com/en-us/library/gg550867(v=office.14).aspx](https://technet.microsoft.com/en-us/library/gg550867(v=office.14).aspx)

I can see the default for VirtualBox additions is upload:

```
 Valid options are "upload", "attach", or "disable". If the mode is "attach" the guest additions ISO will be attached as a CD device to the virtual machine
```

You can modify that to `attach` is updating `MaxMemoryPerShellMB` is not an option.

What's what you would like to see here?

**Comment by dusek** [comment]
@kikitux I would suggest:

1. identify whether the failure of winrmcp propagates to packer; if not, make it propagate there

2. in any case, make sure that when winrmcp error propagates to packer, it gets acted on by packer (e.g. the build is stopped and error message is logged why)

To elaborate a bit: the issue I have here with packer is that it does not detect the error condition and continues to provision the machine. I think that no matter whether the error condition is caused by a bug in some other software than packer, packer should be able to detect it and stop continuing with provisioning.

I understand all the suggestions that you are saying, and that related issues should be tackled in different projects (e.g. by [allowing winrmcp to work with low `MaxMemoryPerShellMB` values](https://github.com/packer-community/winrmcp/pull/10), or boxcutter/windows setting enough big value for `MaxMemoryPerShellMB` in its packer templates, or `attach`ing the tools iso instead of `upload`ing it). But packer should detect the `winrmcp` failures nonetheless, that is what I am saying.

Or to emphasize part of my original report:
> The issue with packer (or maybe with winrmcp - can't tell without digging more deep) is that the error is not ultimately detected by packer, nothing suggesting an error happened is logged at all (at least without -debug), and packer continues with provisioning the VM as if no error happened.
