### ISSUE TITLE
desire a template "regex" function

### ISSUE THREAD

**Issue by jhoblitt** [mitchellh/packer#2924]
I'm experimenting with having multiple docker builders in the same template.  In order to disambiguate the different builds, I end up with fairly pedantic build names like `docker-centos-6`.  As there are multiple docker builders operating at the same time, I can't hard code or set a user var for a post-processor tag.  I've resorted to using the `build_name` function but this results in fairly ugly tag names.  Eg.:

```
  "post-processors": [
    {
      "type": "docker-tag",
      "repository": "foo/bar",
      "tag": "{{build_name}}-foo"
    }
  ],
```

Ideally, I'd like to be able to process the string returned by `build_name` into a more succinct tag prefix.  Ie.:

```
"{{regex(s/docker-centos//, {{build_name}})}}-foo"
```

**Comment by cbednarski** [comment]
Thanks for the suggestion! I think this could be supported via a template function.

However, I'm actually curious why the `build_name` parameter doesn't already satisfy this use-case. For instance, why not specify `build_name` as the name you want for tag?

**Comment by jhoblitt** [comment]
@cbednarski I'm building several centos 6 & 7 images that all use the same setup.  Naming a build "6" doesn't really disambiguate it.

**Comment by cbednarski** [comment]
@jhoblitt I guess I don't understand, because it looks like in your example `docker-centos-6` becomes `6` in the tag. How is that more clear?

**Comment by jhoblitt** [comment]
@cbednarski consider running `packer inspect` on a template along the lines of:

{
  "builders":[
    { "name": "6" ... },
    {"name": "7" ... },
    { "name": "aws-centos-6" ... },
    {"name": "aws-centos-7" ... },
    {"name": "openstack-centos-6" ... },
    {"name": "openstack-centos-7" ... },
...
}

**Comment by jhoblitt** [comment]
Inspect isn't a great example, the issue here is that I don't always want to build everything at one go, I need specific names so I can use `--only` to build a few at a time.

**Comment by cbednarski** [comment]
Gotcha. I think I understand now, thanks for clarifying!

In the mean time (while it's a bit repetitive) you can create a different post-processor for each builder with the exact tag name you want, and use `only` to trigger them.

**Comment by jhoblitt** [comment]
Oh, I didn't think of that -- good idea!

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
