### ISSUE TITLE
docker-tag post-processor attempting to run on openstack builder artifacts

### ISSUE THREAD

**Issue by jhoblitt** [mitchellh/packer#2925]
It's my understanding that the docker specific post-processors are supposed to ignore artifacts from other builder.  Is that a correct assumption?

If so, with packer 0.8.6, `docker-tag` is attempting to operate on openstack bulider artifacts, which fails, and causes the openstack image to be deleted.
```
==> openstack-centos-6: Creating the image: centos-6-stack-w_2015_45-1447089586
    openstack-centos-6: Image: f150f6e8-f540-437c-8cf4-85adebb79129
==> openstack-centos-6: Waiting for image to become ready...
==> openstack-centos-6: Deleted temporary floating IP 141.142.209.29
==> openstack-centos-6: Terminating the source server...
==> openstack-centos-6: Deleting temporary keypair...
==> openstack-centos-6: Running post-processor: docker-tag
Build 'openstack-centos-6' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type: mitchellh.openstack
Can only tag from Docker builder artifacts.
```

**Comment by rickard-von-essen** [comment]
You have to use the ```only``` see http://packer.io/docs/templates/post-processors.html

**Comment by jhoblitt** [comment]
Apologies for the noise, for some reason I thought there were magic restrictions on artifact type.

**Comment by cbednarski** [comment]
> Apologies for the noise, for some reason I thought there were magic restrictions on artifact type.

There are restrictions for the docker post-processors. For example, docker tag only works on docker artifacts. That's how you ran into this issue. The post-processors check the type and error if the wrong type is passed in -- they don't silently ignore.
