### ISSUE TITLE
Openstack API v3 Fails, Requires Authentication

### ISSUE THREAD

**Issue by soudaburger** [mitchellh/packer#2927]
Using packer 0.8.6 on OSX, the following curl command works:

```
curl -i \
  -H "Content-Type: application/json" \
  -d '
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "admin",
          "domain": { "id": "default" },
          "password": "adminpassword"
        }
      }
    },
    "scope": {
      "project": {
        "name": "admin",
        "domain": { "id": "default" }
      }
    }
  }
}' \
  https://api.example.com:5000/v3/auth/tokens ; echo
```

However, when using the following JSON file, the build states that it requires authentication.  Is there some abstract way to configure the JSON file to use the same authentication/headers that curl is using ?

```
{
  "variables": {
    "BUILD_DATE"     : "{{isotime}}",
    "BUILD_VERSION"  : "image-{{ isotime \"20060102\"}}"
  },
  "builders": [
    {
      "type"             : "openstack",
      "ssh_username"     : "cloud-user",
      "image_name"       : "{{ user `BUILD_VERSION` }}-test",
      "source_image"     : "b6a7f588-093f-4872-970c-7dd4c0256397",
      "flavor"           : "7af96e60-e418-4952-acf5-4633b56a726e",
      "tenant_name"      : "tenant1",
      "region"           : "regionOne",
      "ssh_pty"          : true,
      "insecure"         : true,
      "username"         : "admin",
      "password"         : "adminpassword",
      "identity_endpoint": "https://api.example.com:5000/v3/"
    }
  ]
}
```

Failure Output:

```
$ packer build simple.json
openstack output will be in this color.

1 error(s) occurred:

* Expected HTTP response code [201 202] when accessing [POST https://api.example.com:5000/v3/auth/tokens], but got 401 instead
{"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}
```

**Comment by soudaburger** [comment]
I should add that we are using self-signed SSL certificates, hence the SSL endpoints and `insecure` setting as well.

**Comment by cbednarski** [comment]
As far as I can tell this auth happens in the gophercloud library. Aside from passing in the username and password packer doesn't do much here.

**Comment by einarf** [comment]
@soudaburger I can't see any reference to domain name, or did you defined that an environment variable?

Looks like the official packer docs don't include anything about specifying domain https://www.packer.io/docs/builders/openstack.html

According to https://github.com/mitchellh/packer/blob/master/builder/openstack/access_config.go you should be able to specify `domain_name`. Optionally it will get all the auth information from environment variables.

**Comment by rickard-von-essen** [comment]
The docs have been updated, see [Docs OpenStack](https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/openstack.html.markdown) until next release when the site will be updated.
