### ISSUE TITLE
openstack builder does not reauthorize expired API tokens

### ISSUE THREAD

**Issue by jhoblitt** [mitchellh/packer#2928]
With packer 0.8.6 and the openstack builder, I've hit keystone API token timeouts due to a really short expiration period (1hour).

```
==> openstack-centos-7: Error terminating server, may still be around: Expected HTTP response code [202 204] when accessing [DELETE http://XXX.XXX:8774/v2/8c1ba1e0b84d486fbe7a665c30030113/servers/aacabacd-e0bc-4a4b-9892-0f2e474727c5], but got 401 instead

==> openstack-centos-7: Authentication required
```

The HTTP 401 is supposed to be a hint to the client to reauthorize and retry.  It sounds like this is already implemented in gophercloud (https://developer.rackspace.com/blog/gophercloud-update/).

**Comment by markpeek** [comment]
I'm thinking we should always default AllowReauth to true. If so this should be an easy 1 line change to set that field in the AuthOptions. Would you be able to build from master and test a patch?

**Comment by jhoblitt** [comment]
Absolutely!

**Comment by markpeek** [comment]
This compiles but is untested if you want to give it a try. I think that line should be all that is needed to fix your issue.
```
diff --git a/builder/openstack/access_config.go b/builder/openstack/access_config.go
index ca33495..9c8c803 100644
--- a/builder/openstack/access_config.go
+++ b/builder/openstack/access_config.go
@@ -61,6 +61,9 @@ func (c *AccessConfig) Prepare(ctx *interpolate.Context) []error {
        // Get as much as possible from the end
        ao, _ := openstack.AuthOptionsFromEnv()

+       // Make sure we reauth as needed
+       ao.AllowReauth = true
+
        // Override values if we have them in our config
        overrides := []struct {
                From, To *string
```

**Comment by jhoblitt** [comment]
@markpeek The project wide token API expatriation value was just pushed up to 4hours.  What I'll do is run a "build" over night with a ~9 hour sleep in it under your patch concurrently with the official 0.8.6 binary as a control.

**Comment by einarf** [comment]
Having `AllowReauth` with default value `true` makes a lot more sense. It should not affect rackspace or other providers using an api key because the auth logic is separate.

**Comment by covo6624** [comment]
Hi all. I was seeing this problem using packer 10.1. I have a packer build that lasts ~2.5 hours, but my OpenStack cloud expires API tokens after 1 hour. As @markpeek suggested, I patched builder/openstack/access_config.go to explicitly set ao.AllowReauth = true. I'm using Keystone v3, but now seeing following error:

`Stopping server: b1d8d516-ea65-461a-89f1-5bccc00c1f4a Error deleting temporary floating IP
Error terminating server, may still be around: No suitable endpoint could be found in the service catalog
Error cleaning up keypair. Please delete the key manually: packer 57ce92d4-b8e0-3524-4a06-9d7b73c4ac55
Build '*' errored: Error stopping server: Successfully re-authenticated, but got error executing request: Expected HTTP response code [201 202] when accessing [POST http://*.*.*.*:8774/v2/9a2a31bc85c949f39184fcb8b64faeba/servers/b1d8d516-ea65-461a-89f1-5bccc00c1f4a/action], but got 400 instead", "{\"badRequest\": {\"message\": \"Malformed request URL: URL's project_id '9a2a31bc85c949f39184fcb8b64faeba' doesn't match Context's project_id 'None'\", \"code\": 400}}`

So I'm guessing when I get reauthed, the token I'm issued doesn't have the appropriate scope? I don't understand why this would be, as it should be the same function issuing the token as always. Anybody able to offer any help on this one?

**Comment by rickard-von-essen** [comment]
@covo6624 you could also try updating to the latest gophercloud.

**Comment by covo6624** [comment]
@rickard-von-essen This does the trick! In version of gophercloud used in upstream packer, options.TenantName and options.TenantID get overwritten before the ReauthFunc() is called, whereas in latest gophercloud a new V3Options var is introduced to get round this :)

https://github.com/rackspace/gophercloud/blob/master/openstack/client.go#L162

I guess latest gophercloud will make it into upstream packer at some point

**Comment by rickard-von-essen** [comment]
@covo6624 please open a PR with your fix and at least a comment with which version of gophercloud you have tested with. It doesn't have to be a perfect solution just a dump of what you have changed to get it working.
