### ISSUE TITLE
Debug Mode unable to access ec2 instance

### ISSUE THREAD

**Issue by shdobxr** [mitchellh/packer#2936]
Gents,

Working with packer and using a standard ami (centos6). I went through the small effort to build a security group for this host to reside in, and during build it assigns it as it should.

However during the phase in which the pem file is stored locally I still cannot ssh into the host. Tried different networks, different machines. I checked my VPC and it appears to be valid.

But still getting:
<pre>
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Timeout waiting for SSH.
</pre>

Any assistance is helpful 

<pre>
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us-east-1",
    "vpc_id": "vpc-d33351b6",
    "security_group_id": "sg-dcde43ba",
    "source_ami": "ami-bc8131d4",
    "instance_type": "t1.micro",
    "ssh_username": "root",
    "ami_name": "packer-example {{timestamp}}"
  }]
}
</pre>

**Comment by markpeek** [comment]
At first glance several things could cause this to occur. Some questions:
- Is the vpc the default or private?
- If private, are you running packer within the same vpc?
- If not, should you be adding "associate_public_ip_address"?
- Does your security group have port 22 open?

I would suggest running packer with the -debug flag to pause after each step. And then verify that you should be able to access the IP and ssh port associated with that instance.

**Comment by shdobxr** [comment]
I tried both default and private. Why? Cause it's getting late :) 
I switched back to the default VPC, but I have a feeling that there is something wrong with routing at that level. 

<pre>
 ssh -i ec2_amazon-ebs.pem root@XXXX -vv
OpenSSH_7.1p1, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: ssh_connect: needpriv 0
debug1: Connecting to XXXX [XXXX] port 22.
debug1: connect to address XXXX port 22: Connection timed out
ssh: connect to host XXXX port 22: Connection timed out
</pre>

**Comment by cbednarski** [comment]
> I tried both default and private. Why? Cause it's getting late :) 

Can you SSH into _any_ vm in that VPC? If no, you will need to setup a VPN, bastion host, or public subnet. If yes, likely you are not specifying the proper subnet or bastion in your packer template.

> I am researching what this issue is by going the 'old' method to start an instance...

That's EC2 classic. Amazon strongly discourages using this nowadays so the docs are probably hidden away now.

**Comment by shdobxr** [comment]
@cbednarski sorry wasn't clear. I was just going through the ropes of building an amazon ami via the console instead of packer. I am on two different networks and I cannot even get the beginning of a handshake. So something is wrong at layer 3. I think the subnet is to blame.... still troubleshooting.

**Comment by shdobxr** [comment]
Ok progress. So something odd..... 
On one machine (not vpn'd into work) I can login just fine into the EC2 AMI. (windows 10)
On the other I am using git bash (windows8) and vpn'd into work. I get
<pre>
ssh_exchange_identification: read: Software caused connection abort
</pre>

**Comment by shdobxr** [comment]
Yep problem was the VPN.... however I think I know that the issue was the VPC and Subnet. Thanks everyone for being that second pair of eyes.

Goodnight! Got this fixed. :+1:

**Comment by cbednarski** [comment]
> Got this fixed. :+1:

Woo! Thanks for following up. :)

**Comment by shdobxr** [comment]
No problem feel like a dunce but hey. Good thing to ask future ppl should
they have the same problem.

On Thursday, November 12, 2015, Chris Bednarski <notifications@github.com>
wrote:

> Got this fixed. [image: :+1:]
>
> Woo! Thanks for following up. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/packer/issues/2936#issuecomment-156287906>.
>


-- 

-DG
