### ISSUE TITLE
Packer exiting early sends incorrect status code

### ISSUE THREAD

**Issue by pearkes** [mitchellh/packer#2943]
Hard to reproduce this, but it looks like when Packer exits during it's RPC setup process, or someone in that stage, it reports a 0 exit code. This is a screenshot from [Atlas](https://atlas.hashicorp.com/learn/packer), which is reporting that status code as "Finished", translating to 0. If it had been != 0 it would have said errored here. 

![](https://dl.dropboxusercontent.com/s/jcjbbgx4q796wv4/2015-11-16%20at%202.07%20PM.png)

**Comment by mwhooker** [comment]
A lot has changed since this issue was reported, so going to close for now. If you continue to run into this, please make sure you try with the latest version of packer, and, if possible, a json file which reproduces this issue.
