### ISSUE TITLE
Shell provisioner remote_path documentation is non-obvious

### ISSUE THREAD

**Issue by dave2** [mitchellh/packer#2944]
At a glance, the shell param remote_path implies only the path would be set for the script to be uploaded (eg, setting to '/run/user/1000' would be a path, and scripts are uploaded/run under it). The documentation then talks about the default being /tmp/script.sh, which is a full filename and path.

Given the param is called remote_path, I think this should be changed to be strictly a path, and packer automatically appends a randomly-generated filename like it does now (default actually isn't /tmp/script.sh, but /tmp/script_%d.sh with %d randomly generated). The documented behavior would be better called "remote_file" or something else that is clearer, or just removed entirely.

**Comment by cbednarski** [comment]
Thanks for the comments. Unfortunately we can't change the semantics because that would result in a backwards compatibility break, and I don't think that type of change is justified here.

The docs should be changed to reflect the randomized path you mentioned.

**Comment by cbednarski** [comment]
Fixed in #2946
