### ISSUE TITLE
Packer  Vmware:-vmware-iso created virtual machine with empty disks

### ISSUE THREAD

**Issue by YamanduTellechea** [mitchellh/packer#2947]
I want create a machine with multiple disks.To do this I use this json:

{
	"builders":[
	{
	  "type": "vmware-iso",
	  "remote_type": "esx5",
	  "remote_host": "xxxxxxxxxxx",
	  "remote_username": "root",
	  "remote_password": "xxxxxxxxx",
	  "remote_datastore": "xxxxxxxxx",
	  "iso_url": "/usr/local/packer/rhel66-minimal.iso",
	  "iso_checksum": "d260e7f236b632b8f773f16794badafc",
	  "iso_checksum_type": "md5",
	  "disk_size" : "20000",
          "disk_type_id": "thin",
	  "vnc_port_min": 5900,
	  "vnc_port_max": 5964,
	  "ssh_username": "root",
	  "ssh_password": "xxxxxxx",
	  "ssh_port": 22,
	  "ssh_wait_timeout": "600s",
	  "ssh_pty" : "true",
	  "shutdown_command": "echo temporal | sudo -S shutdown -P now",
	  "output_directory": "packer-rhel6-vm",
	  "http_directory": ".",	
	  
          "boot_command": [
          "<enter><wait> "
         ],
	"vmx_template_path": "/opt/packer/rhel66-template/rhel66.vmx"
             
    }  
	],

        "provisioners": [
        {
                "type": "shell",
                "execute_command": "echo temporal | sudo -S sh '{{ .Path }}'",
                "inline": [
			"export http_proxy=xxxxxxxxxxxx",
                        "export https_proxy=xxxxxxxxxxxxxx",
                        "rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm",
			"sed -i -e '/^installonly_limit.*/a proxy=xxxxxxxxxxxxxxx' /etc/yum.conf",
			"yum clean expire-cache",
                        "sudo yum -y install puppet"
                        ]
                }
        ]

	
}

This is .vmx template for machine  :

.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "7"
svga.present = "TRUE"
vmci0.present = "TRUE"
displayName = "RHEL66"
floppy0.present = "FALSE"
numvcpus = "2"
memSize = "1024"
sched.cpu.units = "mhz"
sched.cpu.latencySensitivity = "low"
tools.upgrade.policy = "manual"
scsi0.virtualDev = "pvscsi"
scsi0.present = "TRUE"
vmci.filter.enable = "TRUE"
scsi0:0.deviceType = "scsi-hardDisk"
scsi0:0.fileName = "31-RHEL66-template.vmdk"
sched.scsi0:0.shares = "normal"
scsi0:0.present = "TRUE"
scsi0:1.deviceType = "scsi-hardDisk"
scsi0:1.fileName = "31-RHEL66-template_1.vmdk"
sched.scsi0:1.shares = "normal"
scsi0:1.present = "TRUE"
scsi0:2.deviceType = "scsi-hardDisk"
scsi0:2.fileName = "31-RHEL66-template_2.vmdk"
sched.scsi0:2.shares = "normal"
scsi0:2.present = "TRUE"
ide1:0.startConnected = "FALSE"
ide1:0.deviceType = "atapi-cdrom"
ide1:0.fileName = "CD/DVD drive 1"
ide1:0.present = "TRUE"
ethernet0.virtualDev = "vmxnet3"
ethernet0.networkName = "xxxxxxx"
ethernet0.addressType = "vpx"
ethernet0.wakeOnPcktRcv = "FALSE"
ethernet0.present = "TRUE"
ethernet1.virtualDev = "vmxnet3"
ethernet1.networkName = "xxxxxxxx"
ethernet1.addressType = "vpx"
ethernet1.wakeOnPcktRcv = "FALSE"
ethernet1.present = "TRUE"

I save .vmdks and .vmx in the same folder.

Then, I run packer in debug mode and this is the output:

[root@vmlbcatfl04 rhel66template]# packer build -debug /usr/local/packer/packer-vmware-disks.json
Debug mode enabled. Builds will not be parallelized.
vmware-iso output will be in this color.

==> vmware-iso: Pausing after run of step 'StepPrepareTools'. Press enter to continue.
==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: file:///usr/local/packer/rhel66-minimal.iso
==> vmware-iso: Pausing after run of step 'StepDownload'. Press enter to continue.
==> vmware-iso: Pausing after run of step 'StepOutputDir'. Press enter to continue.
==> vmware-iso: Pausing after run of step 'StepCreateFloppy'. Press enter to continue.
==> vmware-iso: Pausing after run of step 'stepRemoteUpload'. Press enter to continue.
==> vmware-iso: Uploading ISO to remote machine...
==> vmware-iso: Pausing after run of step 'stepRemoteUpload'. Press enter to continue.
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Pausing after run of step 'stepCreateDisk'. Press enter to continue.
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Pausing after run of step 'stepCreateVMX'. Press enter to continue.
==> vmware-iso: Pausing after run of step 'StepConfigureVMX'. Press enter to continue.
==> vmware-iso: Pausing after run of step 'StepSuppressMessages'. Press enter to continue.
==> vmware-iso: Starting HTTP server on port 8271
==> vmware-iso: Pausing after run of step 'StepHTTPServer'. Press enter to continue.

==> vmware-iso: Pausing after run of step 'StepConfigureVNC'. Press enter to continue. ==> vmware-iso: Registering remote VM...

==> vmware-iso: Pausing after run of step 'StepRegister'. Press enter to continue. ==> vmware-iso: Starting virtual machine...

==> vmware-iso: Error starting VM: Retry limit exceeded
==> vmware-iso: Pausing before cleanup of step 'StepRegister'. Press enter to continue. ==> vmware-iso: Unregistering virtual machine...
==> vmware-iso: Pausing before cleanup of step 'StepConfigureVNC'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'StepHTTPServer'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'StepSuppressMessages'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'StepConfigureVMX'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'stepCreateVMX'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'stepCreateDisk'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'stepRemoteUpload'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'stepRemoteUpload'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'StepCreateFloppy'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'StepOutputDir'. Press enter to continue.
==> vmware-iso: Deleting output directory...
==> vmware-iso: Pausing before cleanup of step 'StepDownload'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'StepPrepareTools'. Press enter to continue.
Build 'vmware-iso' errored: Error starting VM: Retry limit exceeded

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error starting VM: Retry limit exceeded

Packer create machine with three disks however it doesn't read well ".vmdk". I don't know if it is the path or other error. 

 I hope that is clear.

If you have any doubt, you can ask.

**Comment by dave2** [comment]
That VMX template looks wrong, you shouldn't add the slices of the VMDK to the VMX, it should only refer to the base .VMDK (which in turn points to the slices numbered _1 and _2.). You don't have three disks, you have one with two slices.

If you'd like multiple disks, use the disk_additional_size paramater to create additional empty disks. I'd also suggest not using the template that way, but instead adding specific values you need (like network connections) using vmx_data, like:

    "vmx_data": {
        "ethernet0.virtualDev": "vmxnet3",
        "ethernet0.networkName": "packer_build",
    }

**Comment by YamanduTellechea** [comment]
Thanks a lot dave2. I have created a machine with several disks using disk_additional_size parameter.
