### ISSUE TITLE
virtualbox-iso: interface is nil, not packer.Communicator

### ISSUE THREAD

**Issue by matesito** [mitchellh/packer#2951]
I am trying to build a virtualbox OVA from an installation ISO of routeros to simulate virtual infrastructure. Therefore I do not need ssh access, the problem seems to start here:

> 2015/11/18 20:46:33 packer-builder-virtualbox-iso: panic: interface conversion: interface is nil, not packer.Communicator

This message is similar to the problem in https://github.com/mitchellh/packer/issues/1503 perhaps the cause is similar too?

Update: I have found a workaround. By setting the following in the builders definition packer ssh to localhost with my own user account  and the build finishes succesfully, this points towards a problem with the "none" communicator.

```json
"communicator": "ssh",
"ssh_username": "user",
"ssh_password": "password",
"ssh_host":"127.0.0.1",
"ssh_port" : 22,
"shutdown_command":"pwd",
```

Log: https://gist.github.com/rickard-von-essen/1294d7214796aff879a2

Edit: moved log to gist.

**Comment by mwhooker** [comment]
moving to #3618
