### ISSUE TITLE
amazon-ebs builder: sometimes fails to put a Name tag on the image

### ISSUE THREAD

**Issue by evarga** [mitchellh/packer#2952]
I am using Packer v0.8.6 on Mac OS X (Yosemite). I sometimes get the following error message during the build (copy-pasted a snippet from the output):

```
amazon-ebs: Instance ID: i-55358a8c
amazon-ebs: Waiting for instance (i-55358a8c) to become ready...
amazon-ebs: Failed to tag a Name on the builder instance: InvalidInstanceID.NotFound: The instance ID 'i-55358a8c' does not exist
amazon-ebs:     status code: 400, request id: []
amazon-ebs: Waiting for SSH to become available...
```

I have seen similar reports, but all are closed. But definitely the problem is not yet fully resolved. At any rate, a build sucessfully finishes, nonetheless it is annoying that sometimes this error occures.

**Comment by cbednarski** [comment]
Thanks for the report. The EC2 API is eventually consistent and sometimes takes minutes to converge. I think we need to poll until the resource is available. I was under the impression that we were already doing this but possibly not for the name code path.

**Comment by evarga** [comment]
Thanks for the quick reply! I agree that 400 is a strange response status code, but it is not actually an EC2 error code. The error code is `InvalidInstanceID.NotFound`. Testing against error codes, from my experience in working with EC2 API, is more robust than relying on a status code or an error message.

**Comment by mwhooker** [comment]
I believe this has been fixed
