### ISSUE TITLE
I need reboot the image at least one time

### ISSUE THREAD

**Issue by SydOps** [mitchellh/packer#2953]
Hi guru,

When prepare the image, I need reboot the instance at least one time, after run some commands in part of provisioners, then run other commands. 

Can I do that?

```
  "provisioners": [
    {
      "type": "shell",
      "inline": [
          "sudo yum -y update",
          "sudo growpart -v /dev/xvda 1",
         "sudo reboot",         <= I need reboot the instance here.
         "RUN other commands"
      ]
    }
  ]
```

**Comment by vtolstov** [comment]
Split you scripts on two blocks,first ended with reboot,second with
pause_before.
This is solve you issue.
19 нояб. 2015 г. 8:43 пользователь "Bill W" <notifications@github.com>
написал:

**Comment by SydOps** [comment]
Thanks a lot @vtolstov .

Seems I have the same issue in #1983

**Comment by SydOps** [comment]
@vtolstov 

I went through the issue #1983, but still not sure how to make two sessions in provisioners.

and this:  https://www.packer.io/docs/templates/provisioners.html

all samples are only with one session.

Will the code be 
```
  "provisioners": [
    {
      "type": "shell",
      "inline": [
          "sudo yum -y update",
          "sudo growpart -v /dev/xvda 1",
         "sudo reboot"
    },
    {
      "type": "shell",
      "inline": [
          "RUN other commands"
      ]
       "pause_before": "600s"
    }
  ]
```

**Comment by vtolstov** [comment]
@SydOps yes, something like this.

**Comment by SydOps** [comment]
@vtolstov 
But it doesn't work

I try this and also 

```
  "provisioners": [
    {
      "type": "shell",
      "inline": [
          "sudo yum -y update",
          "sudo growpart -v /dev/xvda 1",
         "sudo reboot",         <= I need reboot the instance here.
      ]
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
         "RUN other commands"
      ],
     "pause_before": "600s"
    }
  ]
```

**Comment by SydOps** [comment]
Ok, I found the sample at here 

https://github.com/packer-community/packer-windows-plugins

Seems I did right.

**Comment by SydOps** [comment]
Thanks, @vtolstov 

It works. 
```
    amazon-ebs:
    amazon-ebs: The system is going down for reboot NOW!
==> amazon-ebs: Pausing 3m0s before the next provisioner...
```
