### ISSUE TITLE
ansible-local + Windows

### ISSUE THREAD

**Issue by josh-padnick** [mitchellh/packer#2957]
Am I correct in understanding that it is not possible to use the `ansible-local` provisioner with Windows?  My understanding is that `ansible-local` is attempting to run ansible on the remote machine, which, [according to the Ansible Docs](http://docs.ansible.com/ansible/intro_windows.html#reminder-you-must-have-a-linux-control-machine) is not permitted.

One idea I have for using Packer + Ansible + Windows is:
- Use Packer to launch a linux EC2 instance
  - Run Remote Shell provisioners (`shell`) whose job is to install ansible.
  - Run `file` provisioners to copy all necessary ansible playbooks, the inventory file, etc.
  - Run a `shell` provisioner that then installs Packer itself and launches a Windows remote machine.
- On that new Packer build, run `local-shell` provisioners which run the `ansible-playbook` command against the new remote Windows machine

This is obviously pretty convoluted and has some issues with it (e.g. the provisioner machine will get an AMI created). Is there a better way to do this beyond writing a custom plugin?

**Comment by josh-padnick** [comment]
I just want to close the loop on this issue.  We ultimately wound up using PowerShell for all our Windows AMIs.  Even if Windows Ansible were supported, my impression was Ansible doesn't support Windows as a first-class citizen anyway, and we probably would have still had to use PowerShell.  So, at least for our team, this is no longer an important feature for us.

**Comment by johnjelinek** [comment]
@josh-padnick: As of Ansible 2.0, Windows is considered a first-class target, just like linux. The controller still needs to be a linux server. Also, the new `ansible` remote provisioner might soon provide support w/ packer. I don't see that it supports winrm yet though.

**Comment by johnjelinek** [comment]
https://github.com/mitchellh/packer/issues/3307

**Comment by rickard-von-essen** [comment]
The ```ansible``` provisioner "should" work with Windows target if it uses SSH.

**Comment by johnjelinek** [comment]
but it should also work with winrm as long as a host_var is set for winrm.
Ansible already speaks winrm.

**Comment by rickard-von-essen** [comment]
@johnjelinek no it won't since we setup a ssh proxy in between. This is because the communicators don't expose any details about how they are connected to the host. So we create a ssh proxy to the connector (the host) and then we run ansible via the proxy. Switching to WinRM will result in a failed connection towards the proxy (which doesn't speak WinRM).

We are thinking about a redesign of the communicators, but haven't started yet.

**Comment by Svieg** [comment]
Is there any evolution on that case ? I would be really interested in this !

**Comment by thebeefcake** [comment]
Has there been any movement on this one? Just wondering if theres a branch i can follow?

**Comment by rickard-von-essen** [comment]
Closing this since Ansible doesn't support Windows as the control machine.

**Comment by johnjelinek** [comment]
@rickard-von-essen: you should reopen because this is about using Linux as a control machine.

**Comment by rickard-von-essen** [comment]
> Am I correct in understanding that it is not possible to use the `ansible-local` provisioner with Windows?
