### ISSUE TITLE
Export artifacts as ENV variable

### ISSUE THREAD

**Issue by nvtkaszpir** [mitchellh/packer#2958]
Enhancement suggestion.

Packe could export artifacts as ENV variable on succesful build.
This way it could be passed later on to other scripts.

Right now you have to parse output log or use other methods (post-processors and other plugins) to find artifact.

**Comment by cbednarski** [comment]
Thanks for the suggestion. Unfortunately the environment variable won't persist in the environment unless packer starts the other process (which is basically a post-processor at that point). We would have to write this to a file.

**Comment by nvtkaszpir** [comment]
Ah yes, you're right.
I totally forgot about that. Indeed it would work only in subprocess spawning and exporting env variable.
