### ISSUE TITLE
Docker configuration doesn't seem to work with discard

### ISSUE THREAD

**Issue by slackpad** [mitchellh/packer#2959]
I was trying out some Docker stuff and started with this basic configuration:

```
{
  "builders":[{
    "type": "docker",
    "image": "ubuntu",
    "discard": true
  }]
}
```

But it fails with this error message:

```
docker output will be in this color.

1 error(s) occurred:

* unknown configuration key: "discard"
```

I used this configuration as a workaround :-)

```
{
  "builders":[{
    "type": "docker",
    "image": "ubuntu",
    "export_path": "/dev/null"
  }]
}
```

This was with a master build of Packer at 25108c8.

**Comment by cbednarski** [comment]
@slackpad This has [test coverage](https://github.com/mitchellh/packer/blob/master/builder/docker/config_test.go#L91-L109) and I tested this _a lot_ when I added the feature and a lot when debugging the docker download issue.

Do you still have old plugins installed? If you built packer from master it will only have one binary (just packer) and if you loaded an old version of the docker plugin it will not have the discard feature. If you have old plugins you will need to remove them manually.

I have an issue open to improve this here https://github.com/mitchellh/packer/issues/2915

**Comment by slackpad** [comment]
Doh it was the old plugins. Sorry for the noise.

**Comment by cbednarski** [comment]
@slackpad No worries. This is definitely going to bite people so we will need to improve the messaging around old plugins.
