### ISSUE TITLE
[Chef Provisioner] Use Validation Key from The Wrong Path

### ISSUE THREAD

**Issue by smalltown** [mitchellh/packer#2961]
I use Chef as the provisioner, I found Packer will prepare Chef validation key in the path **/tmp/packer-chef-client/**, but Packer trigger chef-client command doesn't specify that with **-K KEY_FILE, --validation_key KEY_FILE**([Chef document](https://docs.chef.io/ctl_chef_client.html)). Hence, the chef-client execute fail due to it can't find the validation key.

- Packer Version

  > $ packer version
  Packer v0.8.6

- Error Log

  > docker: Executing Chef: sudo chef-client --no-color -c /tmp/packer-chef-client/client.rb -j /tmp/packer-chef-client/first-boot.json
    docker: [2015-11-22T12:05:25+00:00] INFO: Forking chef instance to converge...
    docker: [2015-11-22T12:05:25+00:00] INFO: *** Chef 12.5.1 ***
    docker: [2015-11-22T12:05:25+00:00] INFO: Chef-client pid: 3162
    docker: [2015-11-22T12:05:25+00:00] INFO: Client key /etc/chef/client.pem is not present - registering
    docker:
    docker: ================================================================================
    docker: Chef encountered an error attempting to create the client "packer-5651aed4-6150-cc18-4fbb-420429024645"
    docker: ================================================================================
    docker:
    docker: [2015-11-22T12:05:25+00:00] ERROR: Running exception handlers
    docker: [2015-11-22T12:05:25+00:00] ERROR: Exception handlers complete
    docker: [2015-11-22T12:05:26+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    docker: [2015-11-22T12:05:26+00:00] ERROR: I cannot write your private key to /etc/chef/client.pem - check permissions?
    docker: [2015-11-22T12:05:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    docker: Creating configuration file 'knife.rb'
==> docker: Cleaning up chef node...
    docker: WARN: Failed to read the private key /tmp/packer-chef-client/client.pem: #2960 \<Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/packer-chef-client/client.pem\>
   docker: ERROR: Your private key could not be loaded from /tmp/packer-chef-client/client.pem
   docker: Check your configuration file and ensure that your private key is readable

**Comment by mlakewood** [comment]
A workaround for this is to use a config_template and specify the path to the validation key in there. for instance 
```log_location     STDOUT
chef_server_url  "https://chef.server.comi/organizations/chef"
validation_client_name "chef-validator"
validation_key "/tmp/packer-chef-client/validation.pem"
ssl_verify_mode :verify_none
node_name {{.NodeName}}
trusted_certs_dir "/etc/chef/trusted_certs"
```
