### ISSUE TITLE
Error Querying AMI : NoCredentialProviders

### ISSUE THREAD

**Issue by jedi132000** [mitchellh/packer#2967]
https://www.dropbox.com/s/4whacpo4z7rbmh7/packer_build.PNG?dl=0

**Comment by jedi132000** [comment]
https://www.dropbox.com/s/8q169yzhgx79bxt/packer_build2.PNG?dl=0

**Comment by mwhooker** [comment]
Please double check your amazon credentials

https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials
