### ISSUE TITLE
Improve authentication when not running on GCE

### ISSUE THREAD

**Issue by Fodoj** [mitchellh/packer#2970]
It seems like it is impossible to use packer for Google Cloud without service account file. I have gcloud configured on my machine and I can perform all API requests etc (including creating infrastructures via Terraform). But Packer always complains that I am not running on GCE if I provide empty account_file. Is that true? There is no way not to use acount file at the moment, right?

**Comment by nyetsche** [comment]
I just checked out from master and despite having a local account file, and it listed with `account_file`, I get:

```Error creating instance: Get https://www.googleapis.com/compute/v1/projects/myproject/zones/us-east1-a?alt=json: oauth2/google: can't get a token from the metadata service; not running on GCE```

I am of course, running outside GCE.

**Comment by javierbq** [comment]
+1

**Comment by cbednarski** [comment]
> There is no way not to use acount file at the moment, right?

The account file is currently required if you are not running on GCE.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
