### ISSUE TITLE
packer push to atlas always fails with "waiting for winrm"

### ISSUE THREAD

**Issue by mihai-satmarean** [mitchellh/packer#2971]
we are trying for months to push any working windows build tu be built on atlas but if fails
Please provide a working example 
The error message we get is Waiting for Winrm
Thank you!

**Comment by cbednarski** [comment]
Hello, sorry about the delayed response. To get support for Atlas please reach out to support@hashicorp.com. There is not enough information here for me to troubleshoot but we can exchange additional info via email.
