### ISSUE TITLE
implement ssh_host option for virtualbox-iso builder

### ISSUE THREAD

**Issue by rasschaert** [mitchellh/packer#2972]
I've got an ISO that is very opinionated about which IP address it sets on the first interface, rendering the NAT port forwarding Packer uses for SSH useless.

I know what IP I _can_ reach the VM at but I can't seem to make the _virtualbox-iso_ builder use anything other than 127.0.0.1 for SSH.

Feature request: implement the `ssh_host` option in the _virtualbox-iso_ (and ovf?) builder so that the following works:

```json
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "ssh_skip_nat_mapping": true,
      "ssh_host": "172.20.0.20",
      "ssh_port": 22
    }
  ]
}
```

**Comment by rasschaert** [comment]
It looks like people are also trying to use ssh_host with the vmware-iso builder: https://github.com/mitchellh/packer/issues/2185

**Comment by ivanilves** [comment]
Yes, implement it. Please... :pray:

**Comment by lamoni** [comment]
Any updates on this?

**Comment by rickard-von-essen** [comment]
> Feature request: implement the `ssh_host` option in the virtualbox-iso

Acctually `ssh_host` option is allready implemented and is a part of the _ssh communicator_ see the [docs](https://www.packer.io/docs/templates/communicator.html#ssh_host).

This looks more like a bug to me or a usage error.

Could you please provide a _full_ code example where this is needed (template, scripts, etc).

**Comment by lamoni** [comment]
Thanks @rickard-von-essen 

I'm trying the following:

```
  "builders": [
    {
      "type": "virtualbox-ovf",
      "communicator": "ssh",
      "source_path": "/Users/user/Downloads/vm.ova",
      "ssh_skip_nat_mapping": true,
      "ssh_username": "admin",
      "ssh_password": "mypassword",
      "ssh_wait_timeout": "20m",
      "ssh_host": "192.168.0.200",
      "ssh_port": 22,
      "ssh_disable_agent": true,
      "ssh_pty": true,
      ...
```

It seems to still attempt to connect to the host machine's port (ssh_port is at least working.  When I don't define ssh_port, it will try to connect to the randomly generated ssh forwarding port), but ssh_host still doesn't dictate which host it attempts to connect to.

I'm assuming it has to do with the following code in packer/builder/virtualbox/common/ssh.go:
```
func CommHost(state multistep.StateBag) (string, error) {
	return "127.0.0.1", nil
}
```

**Comment by lamoni** [comment]
To further check my suspicion, I changed that hardcoded 127.0.0.1 to the desired 192.168.0.200, recompiled, and it is successfully connecting now.  So definitely an issue with how virtualbox-* is getting the host value

**Comment by ivanilves** [comment]
Hey you may use **redir** to redirect SSH connections to a real host. Not the brightest way, but it works:
http://blog.ivanilves.com/2016/redir-to-trick-packer-virtualbox-ovf/

**Comment by lamoni** [comment]
Thanks @ivanilves, I submitted a pull request adding the feature, but no promises on if/when it would be accepted

**Comment by ivanilves** [comment]
Yes. @lamoni thank you! :clap:
