### ISSUE TITLE
Add configuration option to tag volumes of amazon instances/ami's 

### ISSUE THREAD

**Issue by FrontSide** [mitchellh/packer#2973]
When configuring the ami_block_device_mappings and/or launch_block_device_mappings it would be nice if tags for those volumes could be defines as well like you can do with the ami and instance (tags and run_tags respectively)

Proposal:

```
"ami_block_device_mappings": [
    {
         "device_name": "/dev/sda1",
         "volume_size": 30,
         "tags": {
              "project": "project-name"
         } 
    }
]
```

**Comment by dave2** [comment]
As a general rule, all resources (SGs, Volumes, Snaps, etc) created by packer either temporarily or permanently should be tagged along with the "base" of whatever that process is trying to create (AMI or a temp EC2 instance). This can help with cleanup for aborted tasks as noted in #2859 

See amazon-import post processor, which applies tags to snaps as well as the AMI itself on import creation.

**Comment by salimane** [comment]
I would love this feature :)

**Comment by mwhooker** [comment]
You can tag volumes created during instance run with [`run_volume_tags`](https://www.packer.io/docs/builders/amazon-ebs.html#run_volume_tags)

I'm not sure it's possible to tag ami_block_device_mappings

**Comment by lc-nyovchev** [comment]
Any chance to consider reopening this?

Otherwise there is no simple way to:

- create an ami
- and have tags on its volumes

**Comment by sahotay** [comment]
+1

**Comment by rickard-von-essen** [comment]
Already implemented, see https://packer.io/docs/builders/amazon-ebs.html#run_volume_tags
