### ISSUE TITLE
SSH Breaks when provisioning

### ISSUE THREAD

**Issue by bikbajwa** [mitchellh/packer#2977]
I have the following code to build an AMI:

``` json
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },

  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us-east-1",
    "source_ami": "ami-60b6c60a",
    "instance_type": "t2.micro",
    "ssh_pty" : true,
    "ssh_username": "ec2-user",
    "ami_name": "chef-training-ami-4.0"
  }],

  "provisioners": [{
    "type": "shell",
    "inline": [
      "sleep 30",
      "sudo useradd chef",
      "echo -e \"chef\nchef\" | sudo passwd chef",
      "echo -e \"\nchef ALL=(ALL) NOPASSWD:ALL\" | sudo tee --append /etc/sudoers",
      "sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config",
      "echo -e \"\nAllowUsers chef\" | sudo tee --append /etc/ssh/sshd_config",
      "sudo service sshd restart"
    ]
  }]
}
```

However, when I try to login to an AWS instances using this AMI with either:

``` bash
ssh ec2-user@xx.xx.xxx
ssh chef@xx.xx.xxx
```

It complains and returns:

```
Permission denied (publickey)
```

If I create it without the provisioning section, I can successfully SSH into an instance using this AMI, run the provisioning commands, and still successfully SSH in.

Anyone know what's wrong?

**Comment by rickard-von-essen** [comment]
Is that script working? Try using a script file (non-inline) and upload it to a running instance and execute it to verify it (outside packer).

If you do ```ssh -vvv``` you get plenty info about login methods tried etc, and you can also tail ```/var/log/authlog``` on the e2 instance.

**Comment by bikbajwa** [comment]
@rickard-von-essen yeah the script works outside of packer.

I think I've narrowed it down to ```"echo -e \"\nAllowUsers chef\" | sudo tee --append /etc/ssh/sshd_config", ``` being the point where SSH breaks. However, if I manually run this command (outside of packer), it works just fine.

**Comment by rickard-von-essen** [comment]
Ok try
```json
"sudo bash -c 'echo -e \"\nAllowUsers chef\" >> /etc/ssh/sshd_config' "
```
instead.

**Comment by bikbajwa** [comment]
Just tried it with that line instead, still no luck.

**Comment by kwilczynski** [comment]
@bikbajwa try moving the content of the inline script into a file instead.

**Comment by bikbajwa** [comment]
@kwilczynski still does not work. Same problem as before.

**Comment by mbfrahry** [comment]
I'm having similar issues. Did you happen to figure this out?

**Comment by bikbajwa** [comment]
@mbfrahry no luck. It seems that Packer is somehow messing with SSH configuration.

**Comment by Skarlso** [comment]
Do you have an 'n' there before the AllowUsers on purpose?

**Comment by mwhooker** [comment]
Hi all,

there's been a lot changed in packer since this issue was reported, so I'm going to close assuming it's been fixed. Please create a new issue if anyone is still running in to this.
