### ISSUE TITLE
AWS builder spot-price too low

### ISSUE THREAD

**Issue by nwalke** [mitchellh/packer#2979]
Trying out the spot-price option in packer.  I have it set to auto and the spot_price_auto_product set to `Linux/UNIX (Amazon VPC)` for an Ubuntu server inside a VPC.  Packer tries to set the price to 0.0376, but that price is too low.  If I go in to the console and request a spot instance at that price, I also get denied.  But if I set the price to 0.038, my request goes through.

I've seen #1763, but I don't think that will help the particular issue I'm having.  It seems like it might be a math error in calculating the correct current price.

**Comment by gergnz** [comment]
This is affecting me too.

**Comment by mbravorus** [comment]
Happens repeatedly for me as well. Checking in AWS Console, it plainly says that the auto calculated price is less then required minimum price (by over $0.01). Relaunching packer consistently miscalculates the same value.

**Comment by dmourati** [comment]
Hmm, running into this myself now.

> price-too-low	one-time	a minute ago	

I'm also graphing the spot prices per AZ for this instance type. The packer-computed bid is higher than one AZ's spot price, but lower than the other.

**Comment by dmourati** [comment]
I just set my price manually. Turns out you have to specify a subnet if you are using non-default VPC. I forgot that.

**Comment by ryansb** [comment]
I encountered a related issue, and my PR (#3662) will also fix this one.
