### ISSUE TITLE
Validate post-processor chains

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2980]
Add some logic to detect misconfiguration that looks like this, which is a very common and unintuitive mistake:

```
  "post-processors": [
    {
      "type": "docker-tag",
      "repository": "docker-registry-0:5000/addnow_app",
      "tag": "latest"
    },
    "docker-push"
  ] 
```

We'll need some simple heuristics but a post-processor chain that's only includes docker-push or compress are probably good places to start.

We should emit a warning when parsing the config if things look funny. In the docker-push case we can probably fail the build because I don't think this is valid.

Related:
https://github.com/mitchellh/packer/issues/2599
https://github.com/mitchellh/packer/issues/2843

**Comment by mwhooker** [comment]
this sounds good, but not something we can finish for 1.0
