### ISSUE TITLE
Website documentation is months out of date

### ISSUE THREAD

**Issue by ava-miket** [mitchellh/packer#2983]
There are merged PRs dating back to October (or further) that are not reflected in the online documentation.  As a specific example:

[ansible-local.html] (https://www.packer.io/docs/provisioners/ansible-local.html)

Does not reflect these merged PRs: [2804] (https://github.com/mitchellh/packer/pull/2804), [2963] (https://github.com/mitchellh/packer/pull/2963), [2965] (https://github.com/mitchellh/packer/pull/2965)

**Comment by cbednarski** [comment]
Thanks for the heads up, and apologies for the inaccuracy. The website is updated when we make a release. If you need to get the latest version right away you can run a local copy from the [`website` folder](https://github.com/mitchellh/packer/tree/master/website). If you notice any other discrepancies please let me know!

**Comment by SkypLabs** [comment]
The *disable_sudo* option of the salt masterless provisioner is neither referenced on the online documentation for the same reason.

**Comment by cbednarski** [comment]
Hey folks, the website was updated when 0.9.0 was released and will be updated again soon. If you see specific things that are wrong please open an issue or PR. Thanks!
