### ISSUE TITLE
Puppet Masterless doesn't run manifest file

### ISSUE THREAD

**Issue by YamanduTellechea** [mitchellh/packer#2984]
I want to use Puppet Masterless to create users and install different packages. I have realised a test with a simple manifest, however, I can`t  make packer run ".pp".

This is the .json (provisioner part):

  "provisioners": 	       
        
		[
		{
            "type": "shell",
            "execute_command": "echo temporal | sudo -S sh '{{ .Path }}'",
            "inline": [
			"rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm",
			"yum clean expire-cache",
                        "sudo yum -y install puppet"
                        ]
		},
		{
            "type": "puppet-masterless",
            "manifest_file": "/usr/local/packer/puppetmodules/puppetpacker/manifests/init.pp"
		   
                }
					
        ],

And this is init.pp:

class users 
{
      group {'group-atf':
        ensure=>present,
        gid=>502,
      }    
      user{'user1':
        ensure=>present,
        uid=>502,
        gid=>502,
        home =>'/home/user1',           password=>'$6$HH3lWb3E$p9p1KzmiLDO2kFHH6sUld4G.DnRaQ1MEVvQ9wYQ6bxhYp3QVQYdCONAG4vxLt8mivhIMb2nc0BPl6r/kWsJ7J.',
      }
      file{"/home/user1":
        ensure=>"directory",
        owner=>"user1",
        group=>"group1",
      }
   }

When I run packer, It seems that everything is fine,there aren`t any error, but it isn´t create users and group.

**Comment by hasyimibhar** [comment]
This is not related to packer, but puppet. Nothing happens because you are only *defining* the class. You can either remove the class:

```puppet
group { 'group-atf':
  ensure=>present,
  gid=>502,
}

user { 'user1':
  ensure=>present,
  uid=>502,
  gid=>502,
  home =>'/home/user1',
  password=>'$6$HH3lWb3E$p9p1KzmiLDO2kFHH6sUld4G.DnRaQ1MEVvQ9wYQ6bxhYp3QVQYdCONAG4vxLt8mivhIMb2nc0BPl6r/kWsJ7J.',
}

file { "/home/user1":
  ensure=>"directory",
  owner=>"user1",
  group=>"group1",
}
```

Or include the class at the bottom:
```puppet
class users {
  // ...
}

include users
```

**Comment by YamanduTellechea** [comment]
You are certainly right, the problem was that, i have modified puppet module and  working well.

Thanks hasyimibhar
