### ISSUE TITLE
Separate Builders and Provisioners into separate packages  

### ISSUE THREAD

**Issue by neillturner** [mitchellh/packer#2985]
I suggest that the provisioners and builders be broken out into separate packages so they can be developed separately. the would remove the bottleneck from getting issues resolved and alllow the builders and provisioners to be released independently of the the core packer. 

 This is how test-kitchen and fog are managed. 

Also it would be good to add the ability to run test-suites like test-kitchen.

**Comment by Skarlso** [comment]
Could you please provide an example where the builders and the provisioners are tied together? As far as I see, they are pretty separate right now, but maybe I'm missing something!

Cheers!

**Comment by cbednarski** [comment]
Thanks for the suggestion. You can already build and compile any of the plugins independently from the main packer binary, so if you want to update just the AWS builder you can do so today. The most recent packer release ships this way with independently-compiled plugins.

For most users however it is more confusing to match specific plugin versions to specific packer versions so the official releases will release everything together. This also allows us to dramatically reduce complexity of building, testing, and releasing all of the plugins.
