### ISSUE TITLE
Capture screenshot of VM on failed builds

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2990]
For virtual box and vmware builds it's possible to capture a screenshot of the OS state when a build fails. This would help debug early build failures in headless mode during the OS installation process, for example when a kickstart file gets stuck and SSH cannot connect to the VM.

Later in the build (when running script provisioners, for example) the VM state will only show the login prompt so this is not very interesting.

The following commands can do this:

```
VBoxManage controlvm [vm name] screenshotpng [image]
vmrun captureScreen [path to vmx] [image]
```

**Comment by dave2** [comment]
As I mentioned on IRC, it seems most logical to see this in the context of a debug mode, and extend the multistep debug functions to do this, grabbing captures before and/or after a step is performed.

A callback when multistep debug wants to take a screenshot would be all that was required to make this portable across different builders, and provide other types of builder-specific debug capture.

**Comment by cbednarski** [comment]
> As I mentioned on IRC, it seems most logical to see this in the context of a debug mode, and extend the multistep debug functions to do this, grabbing captures before and/or after a step is performed.

@dave2 We could do this at each step. My thinking was that this would be useful for builds that fail in headless mode so we could take a single screenshot when the build is marked "failed" e.g. when SSH can't connect to the guest. You would be able to see something like "oh the installer got stuck on a prompt or waiting for network and can't proceed".

This feature is particularly useful on Jenkins or Atlas where the build runs heedlessly and you can't intervene during the build. In debug mode (which you have to run locally) you can already look at the VM so I don't see added value in that case. It's _nice_ but it doesn't do anything you can't already do by looking at the GUI. Thoughts?

> A callback when multistep debug wants to take a screenshot would be all that was required to make this portable across different builders, and provide other types of builder-specific debug capture.

That's a good point to make this more future-proof. Did you have another builder in mind?

**Comment by StefanScherer** [comment]
+1000 for Atlas!

**Comment by StefanScherer** [comment]
For Atlas maybe something like this would be cool to have a look at the display while packer runs: https://github.com/paimpozhil/docker-novnc

**Comment by rothwerx** [comment]
+1 for this. On ESXi 6 it's possible to screen capture with `vmdumper <world id> screenshot`, which puts a file named 'vmdumper.png' in the the VM's directory.

**Comment by LukeCarrier** [comment]
One technique I've been using to do this (VirtualBox builder only) is to enable video capture on the VM. Whilst it's not pretty, it's a useful last resort when you're just not able to log the activity to a file on the disk. To do this, add the following to the `"vboxmanage"` section of your Packer template:

```json
["modifyvm", "{{.Name}}", "--videocapfile", "../../builds/2008_r2_64_standard/capture.webm"],
["modifyvm", "{{.Name}}", "--videocap",     "on"]
```

Be warned: the resulting VirtualBox VMs will likely have video capture enabled by default! You could probably turn this off with a `"local-shell"` provisioner.

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
