### ISSUE TITLE
Freeze dependencies for release ?

### ISSUE THREAD

**Issue by zimbatm** [mitchellh/packer#2992]
I am currently trying to package packer for NixOS and I don't know how to find all the versions of the dependencies for a specific release. The project doesn't seem to be using `godep` and `make deps` is just a proxy to `go get -v ./...` 

Is there any plan to collect all the revisions of all the dependencies on release ?

**Comment by rickard-von-essen** [comment]
See #1268 and #2234 for previous comments on this topic.

**Comment by zimbatm** [comment]
Thanks. It looks like the issues have been closed but the issue hasn't been resolved yet.

Please don't close this issue, it's a major pain to retroactively find all the working dependencies. I'm counting 34 right now.

**Comment by cbednarski** [comment]
@zimbatm Thanks. We're aware this is a problem and this is something I'd like to fix, but the tooling / workflow here is pretty tedious. I can't promise exactly when but one of our next releases will support the go 1.5 vendor experiment feature so you can build packer deterministically.

**Comment by cbednarski** [comment]
Dependencies are now vendored!
