### ISSUE TITLE
communicator: none breaks QEMU build

### ISSUE THREAD

**Issue by JonnyNomad** [mitchellh/packer#2994]
Using Packer version 0.8.6 on Ubuntu 15.10 with QEMU version 2.3.0 (Debian 1:2.3+dfsg-5ubuntu9.1) my build breaks with "Qemu stderr: qemu-system-x86_64: -netdev user,id=user.0,hostfwd=tcp::3213-:0: invalid host forwarding rule 'tcp::3213-:0'". Taking 'communicator: none' out of my config file allows the build to work but then times out waiting for SSH since I don't have a provisioning step.

Packer output and my config file can be found at this [gist](https://gist.github.com/JonnyNomad/76c11ec0d00e4d169d85)

**Comment by rickard-von-essen** [comment]
Similar to #2736

**Comment by tylert** [comment]
Related to #3304.

**Comment by vtolstov** [comment]
This is already fixed in master
