### ISSUE TITLE
It sure would be nice to have a new release

### ISSUE THREAD

**Issue by smitelli** [mitchellh/packer#2995]
I'm having a problem in my production environment that I'm pretty sure was fixed by [this PR](https://github.com/mitchellh/packer/pull/2818), but Packer hasn't seen a release since August. I don't want to trust my prod environment to a version of Packer that I built myself from an arbitrary commit from master.

Any chance we could get a release with some of the new goodies that have landed in the last four months?

**Comment by cbednarski** [comment]
Thanks for opening an issue. Packer definitely needs a release and there are a slew of bug fixes we are excited to ship. We are working on this, though I don't have dates to share right now.
