### ISSUE TITLE
snapshot support in provisioner

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#2996]
I want to write snapshot provisioner to packer for qemu builder.

My use-case - write multilayered images. So from one qemu qcow2 file i'm able to install base system or something more (like lamp or some other things).

So i think about snapshot provisioner. On each time that i need snapshot i'm run it.
Another thing add to each provisioner snapshot true/false. Like pause_before.

@mitchellh @cbednarski what do you think?

**Comment by cbednarski** [comment]
@vtolstov This sounds good to me. I use this type of build with VMX so I can run one build to produce a VMX with the base operating system, and then a second one to start building from that VMX to make additional changes.

Can you give me a rundown of how this work in QEMU? Can you simply make a QEMU build start from an existing qcow2 file? If so this will be very similar to the VMX builder. If you had something else in mind please let me know!

**Comment by vtolstov** [comment]
qemu have ability to run from snapshot via -loadvm snap_name, but i'm not try to run qemu with disk only snapshot (without memory).
My use-case multilayered images, so i don't need memory state inside image, but for use-case like continue from some point on error vm state is needed.

**Comment by mwhooker** [comment]
Hi @vtolstov ,

This sounds like it would be a good addition, but it's not something we're planning on implementing. Will tag it with post-1.0 and close for now, so we can revisit in the future if anyone would like to submit a PR for it.

**Comment by shleimeleh** [comment]
Hi, 

I've added a Boolean flag called "overlay_image" (has to go with disk_image=true) which basically tells packer to create the new disk image as an overlay image (qemu-img create -b) and use the iso_path as a backing image. 
This addresses the discussion above from a more [poor mans snapshot perspective](https://dustymabe.com/2015/01/11/qemu-img-backing-files-a-poor-mans-snapshotrollback/).
Ultimately, if you'd like to get a multilayered image then you can 'commit' the newly created drives to the backing image and take a snapshot after every commit (qemu-img snapshot -a <name>) giving you a multilayered image with all the jsons.

Thoughts?
