### ISSUE TITLE
Chef client provisioner failing on Windows

### ISSUE THREAD

**Issue by jamestoyer** [mitchellh/packer#2997]
I'm attempting to use the Chef client provisioner to provision a Windows Server 2012 R2 machine. I recently updated to the latest version of Packer (0.8.6) having previously used a version that used the old 3rd party tools for Windows. 

Since I've updated, running the Chef client provisioner fails to run and I get the following issue.

```
 testing: ==> Script exiting with errorlevel 0
 testing: Creating directory: \packer-temp
 testing: 'chmod' is not recognized as an internal or external command,
 testing: operable program or batch file.
```

From what I've gathered, digging around, changing of permissions for the temp directory was introduced in #2255. As it stands Windows, by default, does not have a command called `chmod` and so it fails. As far as I can see there is no way around this, bar creating a mock command called `chmod`, which is undesirable. 

This has become a blocker to using the latest version, and also to my hopes of using Atlas to build my artifacts

**Comment by cbednarski** [comment]
Thanks for the report. I have two thoughts about this:

1. We should try to detect Windows and not call `chmod`.
2. Does this still happen if you use the `winrm` provisioner?

We might be able to use [`icacls`](https://technet.microsoft.com/en-us/library/cc753525(WS.10).aspx) on Windows instead.

**Comment by jamestoyer** [comment]
I am currently only using the `winrm` communicator. 

So I faked a `chmod` command to get around this issue, but I have encountered several other issues with the Chef client provisioner, that I've had to work around. I'm not sure if I should open other issues to deal with them, but I'll outline them here

1. `staging_directory` requires backslashes to work, this means you have to override the default for Windows.
2. Doing the above then breaks the `knife.rb` generation in a subtle way that cause the knife cleanup to fail. Basically, because you've got a backslash in your path, and Chef expects forward slashes always, it can't find the client.pem location. The work around is to manually set the `client_key` property to use forward slashes e.g.
  ```
  "client_key": "/packer-temp/client.pem",
  "staging_directory": "\\packer-temp"
  ```
3. Letting the provisioner install Chef just plain doesn't work. It assumes you're running Linux as far as I can see, so I had to write my Powershell script to install it.
4. It appears, and I could be wrong, that to make it work at all on Windows you also need to set `prevent_sudo` to `true`.

Just let me know if you would like me to open further issues, and I'll be happy to

**Comment by cbednarski** [comment]
> the provisioner ...  assumes you're running Linux as far as I can see

Thanks for following up. This probably needs some general TLC for windows. I don't spend much time with Windows or Chef but I'd be happy to look at some PRs here.

**Comment by mwhooker** [comment]
This should be fixed on master
