### ISSUE TITLE
powershell provisioner or amazon-ebs builder hangs

### ISSUE THREAD

**Issue by JonCubed** [mitchellh/packer#3007]
I'm trying to build an AMI, but on the last powershell script (configure-ec2config-service.ps1) it hangs (has gone more than 30 minutes without doing anything) and I am force to cancel it. The template has worked in the past but now it always fails with this hang. I use this script in other templates so I know it executes fine. 

From the ui it looks like powershell provision is hung but looking at the log it looks like the powershell provisioner has completed and a problem with amazon-ebs builder.
- I've logged onto the image during debug and have confirmed that the script is uploaded into c:\windows\temp
- I've run the upload script to confirm it completes successfully
- I've added a windows-restart provisioner after it in the template to confirm it is hanging

Here is a zip with the log, template and the script for reference
[packer-debug.zip](https://github.com/mitchellh/packer/files/66601/packer-debug.zip)

**Comment by cbednarski** [comment]
Thanks for the report.

> The template has worked in the past but now it always fails with this hang. I use this script in other templates so I know it executes fine.

Can you give me some more information about what has changed since this used to be working? Did you update packer to a new version? Was this working one day and now is not working? Does it work sometimes and fail sometimes?

**Comment by JonCubed** [comment]
@cbednarski  I'm not aware of anything changing between when it worked and didn't, however I did have some problems creating the two new accounts in packer-bootstrap.ps1 and maybe it started hanging after I fix it.

**Comment by JonCubed** [comment]
I have done some more testing, if I comment out the install-packages.ps1 and added a windows-restart provisioner it finished successfully. When I uncomment install-packages.ps1 and leave restart provisioner it fails there. I've added a [gist](https://gist.github.com/JonCubed/64d4eaf4d951761a4f8f) of the debug for review, but I'm thinking it might be an issue with winrm and timing out now. I'll try experimenting there.

**Comment by rajinders** [comment]
I am seeing similar issues while create win 2012 r2 EBS AMI. Powershell provisoner randomly hangs. 

For the past few months I have been erratic behavior while creating windows AWS EBS AMI's.
Sometimes they work and sometimes they fail.
They fail in the a different powershell scripts.

"provisioners": [
{
"type": "powershell",
"scripts": [
"{{user scripts_dir}}/install_web_server.ps1",
"{{user scripts_dir}}/install_windows_updates.ps1"
]
},

install_web_server.ps1
Here is one of the script where it fails often:

Silence progress bars in PowerShell, which can sometimes feed back strange

XML data to the Packer output.

$ProgressPreference = "SilentlyContinue"

Write-Output "Starting IIS Installation"

Import-Module ServerManager

IIS

Only needed for .NET 3, .NET 4/4.5 is already installed.

#Add-WindowsFeature NET-Framework-Core
#Add-WindowsFeature Web-Server -IncludeAllSubFeature
Add-WindowsFeature Web-Server, Web-WebServer, Web-Security, Web-Filtering, Web-Basic-Auth, Web-Static-Content, Web-Http-Redirect, Web-Dyn-Compression, Web-App-Dev, Web-Asp-Net, Web-Asp-Net45, Web-Mgmt-Tools, Web-Mgmt-Console, Web-Mgmt-Service, Web-Common-Http, Web-Default-Doc, Web-Http-Errors, Web-Windows-Auth, Web-WebSockets
Write-Output "Ended IIS Installation"

WebDeploy

Write-Output "Starting WebDeploy Installation"

Install Microsoft Web Deploy to be able to deploy website packages easily

$webDeployURL = "http://download.microsoft.com/download/D/4/4/D446D154-2232-49A1-9D64-F5A9429913A4/WebDeploy_amd64_en-US.msi"
$filePath = "$($env:TEMP)\WebDeploy_amd64_en-US.msi"

(New-Object System.Net.WebClient).DownloadFile($webDeployURL, $filePath)

Start-Process -FilePath msiexec -ArgumentList /i, $filePath, /qn -Wait

Clean up

Remove-Item -Force -Path $filePath

Write-Output "Ended WebDeploy Installation"

I have enabled logging but I don't see any errors.
I have about 20 success rate in successfully getting past IIS installation.

I am on the latest version of packer. It was happening in the previous version as well.

Let me know if you have any suggestions,

**Comment by mwhooker** [comment]
I think this has been fixed. Please do re-open if you see it again. Thanks!
