### ISSUE TITLE
amazon-chroot: Mounting a different partition

### ISSUE THREAD

**Issue by kimor79** [mitchellh/packer#3011]
Investigating the feasibility of using amazon-chroot for our AMI builds but it looks like it is hardcoded to mount the first partition of the drive, ie sda1. Our disks are laid out such that the second partition is the OS partition, e.g., sda2. It would be nice if this were a configuration option one could specify to mount the correct/desired partition.

**Comment by cbednarski** [comment]
Thanks for the PR!
