### ISSUE TITLE
Allow config to specify disk label for virtual floppy

### ISSUE THREAD

**Issue by justindossey** [mitchellh/packer#3015]
From reading the Redhat documentation, it appears that we can avoid doing the insecure VNC connection to launch a kickstart install if we use `floppy_files` AND label the FAT filesystem created `OEMDRV`.  Right now, the disk label is hard-coded to "packer".  

This enhancement request is to allow us to specify `"floppy_label"` in our configuration file to support VNC-free kickstart installs.

**Comment by rickard-von-essen** [comment]
Could you reference these docs and could you elaborate what you mean with _insecure VNC_.

Have you tried this? I didn't have any success testing this on CentOS 6.7, and regarding RHEL 7.0 I found [these docs from Dell](http://en.community.dell.com/techcenter/extras/m/white_papers/20440810/download) stating that _RHEL 7.0 does not support loading the kickstart file from OEMDRV_ (p. 19).

**Comment by justindossey** [comment]
Here's where I got the info:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/sect-kickstart-howto.html
```
Note
To load your Kickstart file automatically without having to specify the inst.ks= boot option, name the file ks.cfg and place it on a storage volume labeled OEMDRV. 
```

If they're wrong, they're wrong, but that's where I got the info.  Note that even when no boot command is specified (with, for example, a custom ISO that doesn't require a boot command), Packer still attempts to connect over VNC (which I consider to be a bug).

**Comment by rickard-von-essen** [comment]
Thanks for the link and explanation. I think some context is missing here, I assume you are using the ```vmware-iso``` builder with ESXi? 

As a side note: a good way to run the VMware builder ESXi is to use nested virtualization and run a specific ESXi instance alongside a build agent with Packer in two VM's inside a private network. This allows you to build without opening up VNC and ESXi ssh to more than the Packer build agent VM.

Also I found that they recently [bug fixed this in Anaconda](https://lists.fedorahosted.org/archives/list/anaconda-patches@lists.fedorahosted.org/thread/A2G6CKICUFLK4WMELOZTSYLAQK7QL4TK/), that might be the reason I didn't get it to work and Dell state that it doesn't work but it is clearly stated in the docs that it should. Haven't hade time to figure out if this bug fix have made it into RHEL 7.2.

**Comment by justindossey** [comment]
I'm going to make a new issue for the VNC-related enhancement, just to keep this one clean.

**Comment by justindossey** [comment]
Oh, your answer: I'm using vmware-iso with ESX; I can work around it by using vmware workstation or ESXi inside a VM.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
