### ISSUE TITLE
HTTPIP/HTTPPort Variables Not Filled In

### ISSUE THREAD

**Issue by bnied** [mitchellh/packer#3016]
Using Packer 0.8.6 on OS X 10.11.2.

I have a snippet with the following:

    "provisioners": [{
        "type": "shell",
        "inline_shebang": "/bin/bash",
        "inline": [
          ...
          "wget http://{{ .HTTPIP }}:{{ .HTTPPort }}/archive.tar.bz2",

However, when Packer renders the script later on, I get the following:

    wget http://<no value>:<no value>/archive.tar.bz2

**Comment by cbednarski** [comment]
Thanks for opening a ticket. This is not currently supported but there is an issue open to add it here: #2869. I'm going to close this one but if you have any additional feedback please add it to #2869.
