### ISSUE TITLE
Support for amazon-iso builder

### ISSUE THREAD

**Issue by rothgar** [mitchellh/packer#3017]
iso builders exist for various other platforms (virtualbox, vmware, qemu, parallels) and it would be nice to have similar support on cloud providers for users who either

 * Have a lot invested in bare metal/automated provisioning and have plans to keep hardware provisioning in the foreseeable future
 * Need to better control ami creation
 * Have custom isos for installation

Providing iso builders for cloud providers would allow users to quickly switch platforms and re-use the same provisioning templates. I would assume other cloud providers could benefit from *-iso builders too but I assume amazon would be the best place to start as most users are probably using it currently.

**Comment by dave2** [comment]
You may want to look at my PR currently outstanding to resolve this:
https://github.com/mitchellh/packer/pull/2962

As a post-processor, you can use any builder you like which can produce an OVA, and the post-processor will import it into an AMI. virtualbox can now, vmware-iso can on master.

**Comment by rothgar** [comment]
That's an interesting option. Thanks for pointing me to it. I'll have to try getting my build working via Virtualbox first but will give it a try.

**Comment by dave2** [comment]
I went with that approach for aligning my on-prem and AWS builds, largely because it does produce a more consistent outcome. As far as I can tell, AWS doesn't have any way to start an instance from an ISO and do any kind of automated install, it's very strictly AMI only as a starting point.

**Comment by rothgar** [comment]
We have custom scripts that boots the aws node via pxe (inside a VPC) and then starts the installer via network with our existing kickstart files. It's not the best option and needs some manual intervention because of our environment. I was hoping to do something similar with packer but the ova -> ami exporter might be good enough. I'll have to give it a try.

**Comment by rickard-von-essen** [comment]
First thank you for contributing you thoughts about which features are needed in Packer.
I'll shot this down a bit, sorry. (Most of this have already been described above)

First of all AWS EC2 doesn't support building an image from scratch. That leaves a few options:
- Import an OVA, see #2962 
- Use for example ```amazon-chroot``` builder and install the OS from scratch into the chroot.
- There are some more more or less hacky ways of creating scratch AMI's.

If you don't object I'll close this as "won't fix"?

**Comment by rothgar** [comment]
I haven't had a chance to try #2962 but I'll give it a shot. It would be nice to have something more native like virtualbox-iso and vmware-iso but I understand (from experience) Amazon doesn't provide a clean way to implement that.

**Comment by rickard-von-essen** [comment]
Building from scratch in a chroot, see #3855
