### ISSUE TITLE
Packer in Atlas crashes when building an AWS AMI

### ISSUE THREAD

**Issue by marceldegraaf** [mitchellh/packer#3020]
When building an AMI with Packer in Atlas, the process panics.

Packer version: `Packer v0.9.0.rc1 (25108c8d13912434d0f32faaf1ea13cdc537b21e+CHANGES)`
Error message:

```
==> aws-ami-development-base: Prevalidating AMI Name...
Build 'aws-ami-development-base' errored: unexpected EOF
```

[Full stack trace and Packer JSON file](https://gist.github.com/marceldegraaf/b513001978a76fb9e13c).

**Comment by kimor79** [comment]
I'm running an amazon-chroot builder on an EC2 instance with an IAM role and get the same error message. I don't have any aws credentials defined in my template nor do I have a credentials file in the `.aws/` directory. However, if I place a valid credentials file in `.aws/`, packer doesn't panic and continues on with the build.

`Packer v0.8.7.dev (d507b18eb4cf00b7d832c8c3fc7bb46b6377b551+CHANGES)`
[Stack trace](https://gist.github.com/kimor79/2cfc14f81f90135fe533)

**Comment by cbednarski** [comment]
Thanks for sharing your config. Since you're both running dev versions I _suspect_ that the upstream API in aws-sdk-go has changed and packer needs to be updated to match.

**Comment by mwhooker** [comment]
A lot has changed since this issue was reported, so going to close for now. If you continue to run into this, please make sure you try with the latest version of packer, and, if possible, a json file which reproduces this issue.
