### ISSUE TITLE
Shell provisioner should show the reason for 'Error removing temporary script'

### ISSUE THREAD

**Issue by discordianfish** [mitchellh/packer#3021]
Note: The problem reported here is that the provisioners changed permissions on the script packer uploaded, and packer no longer has permission to delete the file.

However, the error message "permission denied" seems to have disappeared somewhere. We should add this back in!

-- @cbednarski

---

I have a pretty standard build json with a amazon-ebs builder and a few shell provisioner steps.
For some reason my build now fails between two provisioner step. Here is a excerpt of my json file:

```
    {
      "type": "shell",
      "execute_command": "{{ .Vars }} sudo -E bash -ex '{{ .Path }}'",
      "inline": [ "rsync -av --chown root:root /tmp/rootfs/ /" ]
    },
    {
      "type": "shell",
      "execute_command": "{{ .Vars }} sudo -E bash -ex '{{ .Path }}'",
      "script": "images/{{ user `ami_type` }}/install.sh"
    },
```

It fails between those steps. I still see the output of rsync, then run into the error:

```
    amazon-ebs: sent 33,553 bytes  received 453 bytes  68,012.00 bytes/sec
    amazon-ebs: total size is 31,631  speedup is 0.93
==> amazon-ebs: Pausing before cleanup of step 'StepConnect'. Press enter to continue.      
==> amazon-ebs: Pausing before cleanup of step 'StepGetPassword'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepRunSourceInstance'. Press enter to continue. 
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Pausing before cleanup of step 'stepCleanupVolumes'. Press enter to continue. 
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Pausing before cleanup of step 'StepSecurityGroup'. Press enter to continue. 
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Pausing before cleanup of step 'StepKeyPair'. Press enter to continue. 
==> amazon-ebs: Deleting temporary keypair...
==> amazon-ebs: Pausing before cleanup of step 'StepSourceAMIInfo'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepPreValidate'. Press enter to continue. 
Build 'amazon-ebs' errored: Error removing temporary script at /tmp/script_7943.sh!

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error removing temporary script at /tmp/script_7943.sh!
```

I already tried to come up with a minimal config to reproduce it but haven't had success so far. Will continue so once I find some more time. In the meanwhile every input is welcome!

**Comment by rickard-von-essen** [comment]
Rerun with ```PACKER_LOG=1 packer build template.json``` without ```--debug```

**Comment by discordianfish** [comment]
Will provide more details tomorrow. Unfortunately I can't share the full install.sh (will try to come up with a minimal one to reproduce). But i can already say that it's not doing anything 'special'. IInstalling some packages via apt-get, creates an user and some symlinks and moves some files from /tmp that where put there from rsync (after a prior provisioner step wrote them to /tmp/rootfs).
That the issue is related to the location of those files were my first suspicion, but I tried another direction and ran into the same issue.

**Comment by discordianfish** [comment]
With PACKER_LOG=1 packer I get:

```
==> amazon-ebs: Deleting temporary keypair...
2015/12/26 20:05:49 ui error: Build 'amazon-ebs' errored: Error removing temporary script at /tmp/script_7943.sh!
2015/12/26 20:05:49 Builds completed. Waiting on interrupt barrier...
2015/12/26 20:05:49 machine readable: error-count []string{"1"}
2015/12/26 20:05:49 ui error: 
==> Some builds didn't complete successfully and had errors:
2015/12/26 20:05:49 machine readable: amazon-ebs,error []string{"Error removing temporary script at /tmp/script_7943.sh!"}
2015/12/26 20:05:49 ui error: --> amazon-ebs: Error removing temporary script at /tmp/script_7943.sh!
2015/12/26 20:05:49 ui: 
==> Builds finished but no artifacts were created.
2015/12/26 20:05:49 waiting for all plugin processes to complete...
Build 'amazon-ebs' errored: Error removing temporary script at /tmp/script_7943.sh!

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error removing temporary script at /tmp/script_7943.sh!

==> Builds finished but no artifacts were created.
2015/12/26 20:05:49 /usr/local/bin/packer-provisioner-shell-local: plugin process exited
2015/12/26 20:05:49 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/12/26 20:05:49 /usr/local/bin/packer-provisioner-shell: plugin process exited
2015/12/26 20:05:49 /usr/local/bin/packer-provisioner-shell: plugin process exited
2015/12/26 20:05:49 /usr/local/bin/packer-provisioner-shell: plugin process exited
2015/12/26 20:05:49 /usr/local/bin/packer-provisioner-shell: plugin process exited
2015/12/26 20:05:49 /usr/local/bin/packer-provisioner-shell-local: plugin process exited
2015/12/26 20:05:49 /usr/local/bin/packer-provisioner-file: plugin process exited
2015/12/26 20:05:49 /usr/local/bin/packer-builder-amazon-ebs: plugin process exited
```

**Comment by rickard-von-essen** [comment]
Most likely you are deleting the ```ssh_user``` or revoking it's privileges to remove the temporary script.

**Comment by discordianfish** [comment]
@rickard-von-essen m( You are completely right.. 
The rsync command created (or modified?) /tmp's permissions when syncing /tmp/rootfs/ to /. After that, the ssh user couldn't remove the files anymore. So this is an issue on my side.

Although I would suggest to improve the error: "Error removing temporary script" could be anything. If it would be "Error removing temporary script: Permission denied" or even something like: "Error removing temporary script /tmp/script_7943.sh: Permission denied", I would have looked into this earlier.

(As I said, I tried a different directory - but forgot to delete /tmp/ from the to-be-sync'ed directory and therefor ran into the same issue. That cause most of the confusion)

**Comment by cbednarski** [comment]
> Although I would suggest to improve the error: "Error removing temporary script" could be anything. If it would be "Error removing temporary script: Permission denied" or even something like: "Error removing temporary script /tmp/script_7943.sh: Permission denied", I would have looked into this earlier.

Agreed. I'm going to repurpose your bug report for that purpose.

**Comment by mwhooker** [comment]
This should be fixed now

**Comment by devopssenpai** [comment]
@discordianfish and just for anyone else in the future. This is most likely cause of the `"rsync -av --chown root:root /tmp/rootfs/ /"` he is most likely putting files into `/tmp` or includes the tmp folder in `/tmp/rootfs` the fix is to `chmod 1777 <path-to-files|root-fs>/tmp`

for me i had this:
```
        {
            "type": "file",
            "source": "files",
            "destination": "/tmp/files"
        },
        {
            "execute_command": "{{.Vars}} sudo -E /bin/sh -ex '{{.Path}}'",
            "type": "shell",
            "inline": [
                "rsync -av --chown root:root /tmp/files/ /",
                "rm -rf /tmp/files"
            ]
        },
``` 
so to fix i did `chmod 1777 ./files/tmp` in my packer repo.
