### ISSUE TITLE
Provisioning not being saved

### ISSUE THREAD

**Issue by ikbenerik** [mitchellh/packer#3022]
I'm using Packer (version `0.8.6`) to create a Vagrant box with CentOS 7.1 (I've got the template from [here](https://github.com/shiguredo/packer-templates/tree/develop/centos-7.1)). This all works great. However I run into an issue when I try to install Puppet and provision my installation with it.

In the Packer logs I am seeing that Puppet runs successfully, however when I load my `.box` file into Vagrant none of the changes made by Puppet are present, while the changes made by the CentOS template are in fact present. The only thing that my Puppet does currently is creating a `/var/www` directory, but this is not present on the Vagrant VM. Nor is the `puppet` command.

I've attached all my files and logs [here](https://gist.github.com/ikbenerik/c0490991a47c48b864d1).

**Comment by darkomenx** [comment]
I have the same VERY STRANGE problem with packer and virtualbox-iso. template run correctly to build a vagrant which up correclty but any add package in script template not installed in this vagrant.

**Comment by rickard-von-essen** [comment]
@darkomenx see my previuous comment on https://github.com/mitchellh/packer/issues/3044#issuecomment-170230679 .

**Comment by rickard-von-essen** [comment]
@ikbenerik it is clearly not an issue with Packer, as from you logs it installs and runs puppet as it should. Probably you don't do all the steps in vagrant correctly (e.g destroy, bo add, init, up...).

**Comment by darkomenx** [comment]
perhaps you can help us and tell us what is exactly "all the steps vagrant" for use your packer technology. It seem that help us to more understand step and perhaps one day use packer.

**Comment by rickard-von-essen** [comment]
Check ot #vagrant on IRC, see https://www.vagrantup.com/support#community
