### ISSUE TITLE
rsync provisioner

### ISSUE THREAD

**Issue by ecoulon** [mitchellh/packer#3023]
Hello,
First of all thanks for your nice work, this tool is very useful and well designed.
I want to use rsync as provisioner for syncing a local large directory, with its equivalent on the base ami, at each deployment.
I could use the local shell to call it manually but i miss an host ip variable for the ec2 instance, is there a way to expose this variable ? Or do i need to develop a custom provisioner ?
What could be the easiest way to achieve this ?
Thanks

**Comment by cbednarski** [comment]
Thanks for opening an issue. Can you elaborate on your use-case, specifically why the file provisioner doesn't work right now? [The file provisioner](https://www.packer.io/docs/provisioners/file.html) accepts a directory as an argument.
