### ISSUE TITLE
Error waiting for image: time out while waiting for image to register

### ISSUE THREAD

**Issue by JorritSalverda** [mitchellh/packer#3026]
On GCE I sometimes see the following error:

```
Error waiting for image: time out while waiting for image to register
```

I see it waited 5 minutes for the image to register. Can I configure this value?

**Comment by JorritSalverda** [comment]
Slightly later when I re-ran the build with same image name it failed because it already exists. A configurable or longer timeout would suffice. 

This is the slow windows sysprep we're waiting for, by the way.

**Comment by caiush** [comment]
I havn't tried it but looking at the code it looks like  `state_timeout` already available (at least in master). Configure like so in the builder clause:
```
"state_timeout" : "15m",
...
```

It looks like  its set to 5m by default.

**Comment by mwhooker** [comment]
It looks like this is fixed. please re-open if `state_timeout` doesn't work.
