### ISSUE TITLE
Enable custom keys during boot_command

### ISSUE THREAD

**Issue by aairey** [mitchellh/packer#3028]
I am trying to buld a certain distro, and all that's possible is a GUI wizard.
I am in the need of using the ctrl-tab key combination to exit a text field and jump to a button below the text field.
However this is not available in Packer.

The "make" scancode is: `1d 0f` and the "release" scancode is `9d 8f`.
This works with the `vboxmanage controlvm vm-name keyboardputscancode 1d 0f` and `vboxmanage controlvm vm-name keyboardputscancode 9d 8f` commands.

I've tried adjusting the [Go code](https://github.com/mitchellh/packer/blob/master/builder/virtualbox/common/step_type_boot_command.go)
However Packer seems to send `vboxmanage controlvm vm-name keyboardputscancode '1d 0f'` (notice the quotes), when setting a new specialCode like `special["<ctrlTab>"] = []string{"1d 0f", "9d 8f"}`

Maybe a better aproach would be to use the `append()` function, as with the `shiftKey` variable to use the Shift modifier.
However I'm not a Go coder and I'm not sure how you guys would implement this.

It would be great to be able to use the ctrl and alt modifiers together with any other character like with shiftKey.
Something like `<ctrlPut><tab><ctrlRel>` for example, maybe?

**Comment by rickard-von-essen** [comment]
Could you name the distro?

Currently the syntax of the ```boot_command``` is a bit limited and sending arbitrary sequences of key strokes would require some redesign.

**Comment by aairey** [comment]
[Porteus Kiosk](http://porteus-kiosk.org/download.html#ISO).
It only has a wizard at boot.

Yes, as stated above I tried changing the code but to no succees. I tried sending two keys, but it appears the keystroke is then sent between quotes, which VBoxManage does not expect.

**Comment by aairey** [comment]
Any update on using key modifiers in the `boot_command`?

**Comment by aairey** [comment]
Closing beause PR #3767 was merged.
