### ISSUE TITLE
builder/vmware-iso: do not attempt VNC connection when no boot_command is specified

### ISSUE THREAD

**Issue by justindossey** [mitchellh/packer#3031]
When no boot_command is specified, the vmware builder does two extra steps: configure_vnc and type_boot_command.  It's kind of silly to do all that work when the ultimate result is to send the empty string and `return multistep.ActionContinue`.  Also, in firewalled environments, the VNC connection may fail, causing the build to abort even when it would have succeeded with no VNC connection.

I propose making `StepConfigureVNC` aware of `BootCommand` and no-op if it is empty.  Then, `StepTypeBootCommand` can do the same.  This seems saner than making a whole new builder without those steps.

**Comment by metalmolly** [comment]
Facing the same issue. Our ESXi host is located behind a firewall and most ports are blocked. As I'm creating VMWare machines directly on the host using an unattended Windows ISO, I don't use the `boot_command`.

Unfortunately the vmware-iso builder step fails: `Unable to find available VNC port as VNC is blocked.` Please find the [debug output](https://gist.github.com/metalmolly/0992b51ed3750f456017) and the [configuration file](https://gist.github.com/metalmolly/d8864c5e6c39b89ba1ad).

**Comment by cbednarski** [comment]
Thanks for the report. I think we can add an option to suppress the VNC connection (which may still be useful in other contexts).

**Comment by detailedschematic** [comment]
I would like to see this change as well. Since I do not use `boot_command`, I would rather not have to modify my VMware esxi host's firewall rules for VNC to allow a connection will go unused.

**Comment by donbecker** [comment]
I also need this as enabling VNC is not an option on my ESXi servers. 

Is there a recommendation for how this should be implemented? 

Should there just be IF statements in[https://github.com/mitchellh/packer/blob/98b0f018fa735302f653ab52e48907871ef4b799/builder/vmware/iso/builder.go](url)

Line 257 `&vmwcommon.StepConfigureVNC{`
Line 271 `&vmwcommon.StepTypeBootCommand{`

**Comment by donbecker** [comment]
Perhaps a new bool SkipVNC ?

**Comment by rickard-von-essen** [comment]
A guard statement in:
Line 257 &vmwcommon.StepConfigureVNC{
Line 271 &vmwcommon.StepTypeBootCommand{

No need to add a extra option just check if boot_command is empty.

**Comment by mwhooker** [comment]
Sounds like a good and straight forward change. Will be happy to look at PRs, but we're not planning on implementing this for 1.0, so going to close it for now. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by timsutton** [comment]
This looks easy enough for me to add with my limited knowledge of Go and the Packer codebase.

Do you think it's sensible for us to leave `steps` for the `vmware-iso` builder unchanged, but then simply exit the step runner immediately if the builder's `boot_command` string was empty? Or is there a preferred way to selectively modify `steps` to omit those steps from ever being added in the first place?
