### ISSUE TITLE
VMWare builder not cleaning up VM's properly

### ISSUE THREAD

**Issue by jcsmith** [mitchellh/packer#3036]
When using the VMWare provisioner the "old vm's" are not being properly cleaned up.  See attached screen shot.
![screenshot from 2016-01-05 12-43-44](https://cloud.githubusercontent.com/assets/338959/12122607/25ba9e1e-b3aa-11e5-828a-4ff28e7b62b1.png)

**Comment by dave2** [comment]
I'm not sure this is a bug, the VMware post-processor is expected to just upload the resulting artifact, and has no knowledge of what you consider 'old' images. I don't think we want the post-processor to delete templates based on any assumptions about naming or 'previous' runs.

**Comment by jcsmith** [comment]
@dave2 I would agree with you if it were leaving the "local" VM's in a state where they could be ran on the local machine.  How ever - and I don't think I was clear previously, the definition stays present in VMWare workstation but the files (VMX and VMDK) are deleted leading to the "Invalid" definitions sticking around with in VMWare Workstation.  I believe it should either clean things up or leave VM's that are in a valid runable state in VMWare workstation.

**Comment by dave2** [comment]
Ah that's quite different, if it's deleting but not unregistering the VM. I'm sorry I'm not certain where the call needs to be inserted in the builder. Are you using `vmware-iso` or `vmware-vmx`?

**Comment by rickard-von-essen** [comment]
I can confirm this happens also with VMware Fusion 7 Pro on OS X too.
![screen shot 2016-01-08 at 08 36 41](https://cloud.githubusercontent.com/assets/557699/12192877/10ab8bd8-b5e3-11e5-8f0c-195f8a9befd4.png)
Sometimes, but not always VMs doesn't get deleted.

**Comment by justindossey** [comment]
I've been seeing this too; I think that you have to tell VMWare Workstation/Fusion to power down the VM before deleting it.

**Comment by vikas027** [comment]
I am too encountering this on these versions.
- OS : El Capitan 10.11.2
- Packer: 0.8.6
- VMware Fusion: 8.0.1 Pro

**Comment by jcsmith** [comment]
@dave2 I apologize for missing your note ~1 Month ago.  I am using the vmware-iso builder.

**Comment by michael-crawford** [comment]
Just recovering a bento-inspired packer project, seeing the same behavior with VMware building as noted above. This happened 2 years ago, still happening. I run a thor task which builds about 20 VM templates using VMware builder overnight, wind up with 20 stacked, stopped VM windows in the morning I have to clean up. 

Why can't these be deleted like the Virtualbox variants? I'm saving all the box files, and can use them later in Vagrant.

OS : El Capitan 10.11.3
Packer: 0.8.6
VMware Fusion 8.1.0

**Comment by vikas027** [comment]
All, Blake Garner helped me [here](https://groups.google.com/d/msg/packer-tool/L30dJ2BAnyc/GZJWLHYMIQAJ) with a solution. Just use `"headless": "true",` in your .json file and you will be good. The only caveat is that you will not be able to see the VM in the VMware Fusion library, but that hardly matters since logs are available on the console itself.

Hope this helps.

**Comment by mwhooker** [comment]
This is an issue with vmware. I don't think there's anything we can do. Happy to look at PRs for this if I'm wrong

**Comment by cbednarski** [comment]
Since this came up again today this is GUI metadata that VMware is tracking. On mac it is stored in `~/Library/Application\ Support/VMware\ Fusion/vmInventory`. Packer does not currently manipulate this file.
