### ISSUE TITLE
openstack builder: Change image_type from "snapshot" to "image"

### ISSUE THREAD

**Issue by msabramo** [mitchellh/packer#3038]
It would be nice if the openstack builder did a call to glance to change the `image_type` property from `"snapshot"` to `"image"`.

<img width="1131" alt="screen shot 2016-01-06 at 7 56 04 am" src="https://cloud.githubusercontent.com/assets/305268/12146962/80986cf2-b44b-11e5-81aa-8c8ef2a6a7f1.png">

```
$ glance image-show 9b1c534c-12ec-4dd1-831d-86055726733b | egrep --color=none -- '---|Value|image_type'
+---------------------------------------+--------------------------------------+
| Property                              | Value                                |
+---------------------------------------+--------------------------------------+
| Property 'image_type'                 | snapshot                             |
+---------------------------------------+--------------------------------------+
```

The problem with `"snapshot"` is that snapshots don't show up in the list of available images to boot from when launching a new instance.

<img width="445" alt="screen shot 2016-01-06 at 7 57 17 am" src="https://cloud.githubusercontent.com/assets/305268/12146978/91421b3e-b44b-11e5-80ad-8a161e5a16a9.png">

So I am needing to manually do something like this to fix the images produced by Packer:

```
glance image-update 9b1c534c-12ec-4dd1-831d-86055726733b --property image_type=image
```

**Comment by msabramo** [comment]
I was able to make this happen by setting metadata in my Packer template -- e.g.:

```json
...
  "builders": [
    {
      "type": "openstack",
      ...
      "metadata": {
        "image_type": "image"
      },
      ...
    }
  ],
...
```

so that is a workaround. Now I just wonder if Packer should do this by default?

**Comment by msabramo** [comment]
See https://github.com/mitchellh/packer/pull/3041

This makes the OpenStack builder automatically assume an "image_type" of "image" by default.

**Comment by rickard-von-essen** [comment]
Thank you for bringing this to our attention.

This looks like an oversight or at least the docs fails to inform that the builder produces a snapshot.
