### ISSUE TITLE
openstack builder: Add option to not delete server when done building image

### ISSUE THREAD

**Issue by msabramo** [mitchellh/packer#3039]
The openstack builder always deletes the server that it snapshotted to create the image.

I would like to have an option to tell it to keep the server.

The reason is that after building the image I would like to scan for vulnerabilities with a tool called Nexpose. Nexpose needs a machine to scan. Rather than booting up a new VM with the new image to do this, it would be more efficient to just keep the VM that Packer used, have Nexpose scan that, and then I can clean the VM up later on in my script.

**Comment by rickard-von-essen** [comment]
Is there any particular reason to not use [Local Shell Provisioner](http://packer.io/docs/provisioners/shell-local.html)?
