### ISSUE TITLE
DNS resolution using amazon-ebs ignores local resolv.conf configuration

### ISSUE THREAD

**Issue by bbaja42** [mitchellh/packer#3042]
I've set up packer to create new amazon ami, using amazon-ebs builder, however when packer is trying to SSH to the new instance to configure it; I see that it is using public IP.
Since the host DNS settings ( more of the context at the end of the issue) show local DNS resolver should return private IP address, it looks to me like packer is ignoring local DNS configuration.

Is there a way to tell packer to use local DNS configuration of the host?

```
==> amazon-ebs: Waiting for SSH to become available...
2016/01/07 18:13:38 packer-builder-amazon-ebs: 2016/01/07 18:13:38 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 54.172.1.100:22: i/o timeout
2016/01/07 18:13:58 packer-builder-amazon-ebs: 2016/01/07 18:13:58 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 54.172.1.100:22: i/o timeout
2016/01/07 18:14:18 packer-builder-amazon-ebs: 2016/01/07 18:14:18 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 54.172.1.100:22: i/o timeout
2016/01/07 18:14:38 packer-builder-amazon-ebs: 2016/01/07 18:14:38 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 54.172.1.100:22: i/o timeout
^C2016/01/07 18:14:52 packer-provisioner-ansible-local: 2016/01/07 18:14:52 Received interrupt signal (count: 1). Ignoring.
```

**Context**
DNS resolution of EC2 hostnames can return either public or private IP address, depending on DNS configuration.

Example
```
2016/01/07 18:12:47 ui:     amazon-ebs: Public DNS: ec2-54-172-1-100.compute-1.amazonaws.com
    amazon-ebs: Public DNS: ec2-54-172-1-100.compute-1.amazonaws.com
2016/01/07 18:12:47 ui:     amazon-ebs: Public IP: 54.172.1.100
    amazon-ebs: Public IP: 54.172.1.100
2016/01/07 18:12:47 ui:     amazon-ebs: Private IP: 10.0.8.190
    amazon-ebs: Private IP: 10.0.8.190
```

If the DNS request is sent to 8.8.8.8, a public IP is returned. However, is DNS request is sent to local DNS resolver, which is configured on EC2 instance, it gets private IP address.

```
[ec2-user@ami-builder-production-web-vpc intercom-ami]$ cat /etc/resolv.conf
; generated by /sbin/dhclient-script
search us-east-1b.i.ntr.cm
nameserver 10.0.0.2
```

**Comment by bbaja42** [comment]
I tried following https://golang.org/pkg/net/, and setting 
```
export GODEBUG=netdns=go    # force pure Go resolver
export GODEBUG=netdns=cgo   # force cgo resolver
```

but I didn't notice any difference

**Comment by dave2** [comment]
The logic for which address it picks is here:
https://github.com/mitchellh/packer/blob/master/builder/amazon/common/ssh.go#L20-L28

Perhaps we need an option to force which address to pick?

**Comment by dave2** [comment]
Ignore previous comment, there is an undocumented option to force the private IP to be selected:
https://github.com/mitchellh/packer/blob/master/builder/amazon/common/run_config.go#L38

Untested, but would be interested if it works.

**Comment by bbaja42** [comment]
Thnx, yes; that should work. https://packer.io/docs/builders/amazon-ebs.html#ssh_private_ip

Will make the change tomorrow morning, and update the results here ( I expect it to work).
Thnx for the help.

**Comment by bbaja42** [comment]
Thnx for the help, this cleared out the issue. I was stuck on idea that URL to IP resolution is done using DNS, which led me astray. Packers idea of using AWS API is much more flexible :)
