### ISSUE TITLE
amazon-ebs: Error querying AMI: AuthFailure: AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by lioramilbaum** [mitchellh/packer#3043]
Packer v0.9.0.rc1 (25108c8d13912434d0f32faaf1ea13cdc537b21e+CHANGES)

amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Error querying AMI: AuthFailure: AWS was not able to validate the provided access credentials
==> amazon-ebs: 	status code: 401, request id:
Build 'amazon-ebs' errored: Error querying AMI: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: 

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error querying AMI: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: 

==> Builds finished but no artifacts were created.

It used to work perfectly. The only thing changed that I can recall is the packer version installed in Atlas. Is there something I should change in the packer json file?

**Comment by lioramilbaum** [comment]
The same goes if packer version downgraded to 0.8.5

**Comment by lioramilbaum** [comment]
region is: eu-west-1

**Comment by cbednarski** [comment]
Thanks for the report. Can you tell me how you're specifying your credentials? I think this may be the same issue as #2611.

**Comment by nodesocket** [comment]
Heads up for others. **AMI IDs change** depending on the AWS region.
