### ISSUE TITLE
Add support for subnetworks

### ISSUE THREAD

**Issue by mmoya** [mitchellh/packer#3062]
GCE recently introduced the concept of [subnetworks][1]. The legacy mode of having only _networks_ is deprecated. In fact, creation of [legacy networks][2] is disabled in the web UI, if you want them, you have to use the command line.

When running packer against a project having _subnetworks_, this error happens:

    googlecompute output will be in this color.

    ==> googlecompute: Checking image does not exist... 
    ==> googlecompute: Creating temporary SSH key for instance...
    ==> googlecompute: Creating instance...
        googlecompute: Loading zone: us-east1-b
        googlecompute: Loading image: ubuntu-1404-trusty-v20151113 in project packer-test
        googlecompute: Loading machine type: n1-standard-1
        googlecompute: Loading network: default
        googlecompute: Requesting instance creation...
    ==> googlecompute: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].subnetwork': ''.  Subnetwork was not specified for a custom network., invalid
    Build 'googlecompute' errored: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].subnetwork': ''.  Subnetwork was not specified for a custom network., invalid

 [1]: https://cloud.google.com/compute/docs/subnetworks
 [2]: https://cloud.google.com/compute/docs/subnetworks#legacy_non-subnet_network

**Comment by sl1pm4t** [comment]
In my tests, the above error is only present if the network was created with custom subnetting. If you choose Auto subnetting when creating the network (or are in fact using the default network created by Google when the project was created) then there will not be an error.

In saying that, I'm working on a PR to add support for Subnetworks.

**Comment by sl1pm4t** [comment]
PR submitted.
