### ISSUE TITLE
0.8.6 Not Respecting Command Line User Variables

### ISSUE THREAD

**Issue by kylegoch** [mitchellh/packer#3064]
We just upgraded to 0.8.6 from 0.7.5 and noticed an issue where the variables sent in from the command line were not overriding the variable file itself.

For example:
With parameters.json looking like this:

> {
>   "base_ami": "ami-yyyyyy",
>    `...`
> }

And template.json looking like this:

> {
>   "variables": {
>       "base_ami": ""
>   }
>   "builders: {
>        "type": "amazon-ebs",
>        "source_ami": "{{user `base_ami`}}",
>       `...`
>   }
> }

When I run this:
`packer build -var base_ami=ami-xxxxxx -var-file parameters.json template.json`

I get `ami-yyyyyy` showing up in the packer run. But the documentation says that a command line `-var` will overwrite a variable in a file.

> And as mentioned above, no matter where a -var-file is specified, a -var flag on the command line will always override any variables from a file.
> [User Variables](https://packer.io/docs/templates/user-variables.html)

This overwriting worked fine in 0.7.5.

If I go into the parameters.json and do this:

> {
>   "base_ami": "",
>    `...`
> }

Packer says it needs a base ami to continue.

However if I completely remove `"base_ami": ""` from the parameters file, then i get `ami-xxxxxx` just as I would have expected, and was getting in 0.7.5.

Is this a bug? Or did I do something terribly wrong?

**Comment by cbednarski** [comment]
Thanks for the report! This definitely sounds like a bug. Sorry about that!

**Comment by kylegoch** [comment]
Thanks @cbednarski .

Our workaround for the moment is to remove the variable, but we may roll back to 0.7.5 in the meantime.

**Comment by ptolemy428** [comment]
This Bug made us have to apply some annoying work-arounds when setting up our CI pipeline. 

+1 for fixing this issue soon.

**Comment by cbednarski** [comment]
@ptolemy428 Are you still experiencing this problem with packer 0.10?

**Comment by ptolemy428** [comment]
Hi @cbednarski, we're experiencing this issue with Packer v0.10.1.

**Comment by cbednarski** [comment]
@ptolemy428 Thanks for the info!

**Comment by dragon788** [comment]
Guys, this may be related to https://github.com/mitchellh/packer/issues/2682 so please check and see if the workaround there works.

**Comment by mwhooker** [comment]
This was fixed in #2682. It was a documentation error.

instead of 

`packer build -var-file=3064-params.json -var base_ami=ami-xxxxxx 3064.json`

you would run

`packer build -var base_ami=ami-xxxxxx -var-file=3064-params.json 3064.json`
