### ISSUE TITLE
Longer EC2 and EBS esource IDs

### ISSUE THREAD

**Issue by zWaR** [mitchellh/packer#3072]
Hi!

Probably you all already saw this: https://aws.amazon.com/ec2/faqs/#longer-ids

Is the current version of Packer (v0.8.6) affected by the longer IDs?

In case Packer is affected by the change: I know it's quite early, but is there already a time-frame ready for adding support for longer IDs? What is the anticipated deadline to add support for that to Packer?

Thanks!!

**Comment by jen20** [comment]
Hi @zWaR! I primarily work on Terraform but have done some work in the Amazon builders in Packer too. To the best of my knowledge Packer should need no patches for the new IDs - we don't attempt to parse them, and store them all as strings with no length restriction. If you spot any weirdness related to the change please let us know though, and we will aim to patch it quickly.

**Comment by zWaR** [comment]
Perfect!!

Thank you @jen20!! :)

**Comment by CpuID** [comment]
@jen20 built some AMIs yesterday using 0.9.0 with the longer IDs, no issues here. Probably safe to close.

**Comment by rickard-von-essen** [comment]
This works fine for me. Please reopen if you find any problem with longer aws id's.
