### ISSUE TITLE
Packer qemu builder hangs due instance losing name resolver ability at some point

### ISSUE THREAD

**Issue by mainframe** [mitchellh/packer#3073]
Packer version: 0.8.6
Build host: CentOS 7 VM with nested virtualization support under Parallels Desktop hypervisor
Build host RAM: 4GB
Image base OS: CentOS 7
Qemu builder instance RAM: 2GB

I started to have problems with packer qemu CentOS 7 based image builds - once shell provisioner scripts and number of installed/dowloaded software packages grow in size and numbers. Reducing shell provisioner steps and yum pkg installs reduces the problem occurances it seems (also enlarging qemu instance memory amount seems to have somewhat positive effect).

The problem: at some point during shell provisioner scripts executing yum pkg installs, qemu builder VM instance seems to loose resolver (or network connection completely - not sure) -- which can happen at a bit random point - but mostly during the final shell provisioner phases. This results yum being stuck on package downloads inside the builder instance - due name resolver failing with the timeout. Error messages are like this:

``` bash
qemu: http://ftp.estpak.ee/pub/centos/7.2.1511/os/x86_64/Packages/apr-1.4.8-3.el7.x86_64.rpm: [Errno 12] Timeout on http://ftp.estpak.ee/pub/centos/7.2.1511/os/x86_64/Packages/apr-1.4.8-3.el7.x86_64.rpm: (28, 'Resolving timed out after 30413 milliseconds')
    qemu: Trying other mirror.
```

At the same time build host itself is able to resolve the target mirror and download packages from there just fine - which hints that its not a simple target reachability problem:

``` bash
# wget http://ftp.estpak.ee/pub/centos/7.2.1511/os/x86_64/Packages/apr-1.4.8-3.el7.x86_64.rpm
--2016-01-15 11:11:10--  http://ftp.estpak.ee/pub/centos/7.2.1511/os/x86_64/Packages/apr-1.4.8-3.el7.x86_64.rpm
Resolving ftp.estpak.ee (ftp.estpak.ee)... 62.65.42.236
Connecting to ftp.estpak.ee (ftp.estpak.ee)|62.65.42.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 105572 (103K) [application/x-redhat-package-manager]
Saving to: ‘apr-1.4.8-3.el7.x86_64.rpm’

100%[==========================================================================================================================================>] 105,572     --.-K/s   in 0.06s

2016-01-15 11:11:10 (1.61 MB/s) - ‘apr-1.4.8-3.el7.x86_64.rpm’ saved [105572/105572]

# ping ftp.estpak.ee
PING ftp.estpak.ee (62.65.42.236) 56(84) bytes of data.
64 bytes from ftp.estpak.ee (62.65.42.236): icmp_seq=1 ttl=128 time=9.14 ms
64 bytes from ftp.estpak.ee (62.65.42.236): icmp_seq=2 ttl=128 time=9.14 ms
64 bytes from ftp.estpak.ee (62.65.42.236): icmp_seq=3 ttl=128 time=12.5 ms
64 bytes from ftp.estpak.ee (62.65.42.236): icmp_seq=4 ttl=128 time=11.4 ms
64 bytes from ftp.estpak.ee (62.65.42.236): icmp_seq=5 ttl=128 time=15.6 ms
^C
--- ftp.estpak.ee ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 9.149/11.587/15.679/2.431 ms
```

Tried to disable yum fastestmirror plugin from the provisioning scripts - which didnt seem to have much effect on the problem (perhaps just reducing hostname lookups).

However - if adding 'reboot' command into provisioning scripts - before the final phases where it usually starts fail - this seems to help. BUT this workaround creates another problem - recovering after build instance reboot (ie recovering packer ssh connection to VM perhaps?) and going on with shell provisioner seems to take ages - more than 1h - around 80-90 min to be exact! So this qemu network loss might recover itself after 80 min or so...

Providing more QEMU instance RAM seems to have somewhat positive effect (resolver seems to fail a bit later) - but its definitely not linear and there isnt so big difference between 1GB or 2GB RAM used for the instace. Under normal circumstances 4GB for build host and 2GB for Qemu instance should be more than enought I think.

Sometimes the build might even succeed (and not to loose network afterall) - but this seems to happen on around 1/40 of cases and I havent found any definite factors that could influence this.

**Comment by cbednarski** [comment]
Thanks for opening an issue. From your description it sounds like this is either a QEMU problem or a problem in your build scripts. Am I missing something in your explanation that leads you to believe this is a packer bug?

**Comment by mainframe** [comment]
Provisioning scripts are pretty ordinary - yum, unzip, sed - nothing that should be able to cause networking or resolver loss. Im guessing that problem might be qemu related or how packer runs qemu - and perhaps memory utilization plays its role there as well. I need to setup debug point somehow to get more details - need to figure out how to access the instance if network is gone...

**Comment by mainframe** [comment]
Its very likely qemu issue - this bug seems to have very similar symptoms: https://bugs.launchpad.net/ubuntu/+source/qemu-kvm/+bug/997978

When Im starting to see resolver timeouts from provisioning scripts - also ssh login to VM is impossible or very slow - seems that network connections are hanging.

I found simple workaround to this problem - issuing '/etc/init.d/network restart' as part of shell provisioner inside the qemu instance fixes this network problem and provisioning scripts are able to finish successfully.

**Comment by vtolstov** [comment]
Try to firstly UseDNS no in /etc/ssh/sshd_config

**Comment by mainframe** [comment]
I can still have successful ssh connection to the qemu-builder instance if I initiated it before the hung - ie existing ssh connection to the instance seems to keep working.

**Comment by vtolstov** [comment]
Try to check /etc/resolv.conf when vm is hanging, but before on the first step - add provided ssh option.

**Comment by mainframe** [comment]
It does not seem to be resolver issue as such - all network traffic from VM virtual interface seems to halt.

**Comment by mwhooker** [comment]
Sorry you're having issues with this. If you're still having trouble, I would recommend bringing this to the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk). The mailing list has a lot more eyeballs on it than the github issue tracker, so I think you're more likely to find help there.

If you discover that this is a bug in packer, you should definitely open an issue. However, after a brief glance at this it's not obvious that there's a bug, so I'm going to close this.
