### ISSUE TITLE
Where is the Dockerfile for the Packer image?

### ISSUE THREAD

**Issue by marcosscriven** [mitchellh/packer#3074]
Hi

Sorry if this has already been answered, but it's quite tricky to search for, as docker is itself something Packer can use, as well as be used by.

Re the question here: https://hub.docker.com/r/hashicorp/packer/

Where is the docker file for that please? It's not marked as the 'official' Docker image for Packer either, which would add confidence.

**Comment by marcosscriven** [comment]
I also note it's considerably out of date, unfortunately:

```
root@81fa4c4f3016:/# packer version
Packer v0.7.5

Your version of Packer is out of date! The latest version
is 0.8.6. You can update by downloading from www.packer.io
```

**Comment by cbednarski** [comment]
Thanks for opening an issue. I'm not sure where this comes from so I'll need to look into this for the next release.

**Comment by kikitux** [comment]
@marcosscriven Can you check this project for reference?

https://github.com/hashicorp/docker-consul

**Comment by mwhooker** [comment]
the dockerfiles are here https://github.com/hashicorp/docker-hub-images

and we've been trying to do a better job at updating them!
