### ISSUE TITLE
EBS encryption does not encrypt

### ISSUE THREAD

**Issue by erez-rabih** [mitchellh/packer#3085]
Hi,

I'm using packer v0.8.6
I'm trying to create an AMI with an encrypted root device.
The relevant part of the JSON file i'm building is:
```json
        "ami_block_device_mappings": [{
            "device_name": "/dev/sda1",
            "volume_type": "gp2",
            "volume_size": "100",
            "encrypted": true
        }]
```
The AMI's block device mapping is:
```
/dev/sda1=snap-34863174:100:false:gp2:encrypted
```

But I can't create an instance with encrypted root device from the AMI. On the "Add Storage" step the root device is set to "Not Encrypted" since the original snapshot is not encrypted.

I confirmed that the original snapshot itself is not encrypted which is probably the root cause for this.
I also tried surrounding the true value on the encrypted key with double-quotes but it didn't change the result.

Does the origin AMI have to be encrypted in order to have an encrypted AMI?

Thanks for the help.

**Comment by ertanden** [comment]
I have the same problem.

**Comment by erez-rabih** [comment]
@ertanden I can confirm that if the original snapshot is encrypted and you add the encrypted: true to the packer json file the resulting image will be encrypted as well.
Still don't know about what happens when the original snapshot is not encrypted.

**Comment by cbednarski** [comment]
[According to the docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#EBSEncryption_considerations) you can't create an encrypted snapshot from an unencrypted volume. You also can't change a volume from unencrypted to encrypted (or in reverse). Instead you have to create a new volume and migrate the data (e.g. copy via rsync).

The terminology is easy to confuse here so I'm not sure exactly what scenario you're in but I think what you're trying to do is not supported.

**Comment by erez-rabih** [comment]
@cbednarski Just a small correction. In order to change a volume, or to be more correct a snapshot, from unencrypted to encrypted you can just perform an API copy snapshot operation with the encrypted flag on. See the docs of it here: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CopySnapshot.html
The scenario I had was building a custom AMI out of a public ubuntu vivid base AMI. Public AMIs are never encrypted so I had to copy the AMI's snapshot into an encrypted snapshot and then work on the new AMI as the base AMI to create the custom one I wanted.

**Comment by kamaltherocky** [comment]
+1 . it would be good feature to add in Packer so that we don't need the additional step of pre-creating an encrypted snapshot of the public AMI

**Comment by miked0004** [comment]
The problem on encrypting root volumes is compounded by sharing the image across accounts. When you have an AMI with an encrypted snapshot, you cannot share it across accounts even if the snapshot has a shared custom KMS CMK.

My solution was going to be to share the AMI with unencrypted snapshot to my other account and then do an copy-ami --encrypted. However, packer, as-is, does not yet provide an option enable  "createVolumePermission" for snapshots, even when the AMI has shared launch permissions.

I created an issue here: https://github.com/mitchellh/packer/issues/3761
