### ISSUE TITLE
Better error message when exceeding hardware limits.

### ISSUE THREAD

**Issue by clstokes** [mitchellh/packer#3090]
If I specify more hardware specifications than the host allows, Packer will fail with an ambiguous error message - _The operation was canceled_. Packer should provide a better error message or pre-validate the hardware specs before launching to provide better user feedback.
##### Packer Template Snippet

``` javascript
{
...
    "builders": [
        {
            "type": "vmware-iso",
            "vmx_data": {
              "cpuid.coresPerSocket": "1",
              "memsize": "4096",
              "numvcpus": "64"
            }
            ...
        }
    ]
...
}
```
##### Packer Error log

```
...
==> vmware-iso: Error starting VM: VMware error: 2016-01-19T09:14:21.896| ServiceImpl_Opener: PID 55866
==> vmware-iso: Error: The operation was canceled
==> vmware-iso: Waiting 2.476322553s to give VMware time to clean up...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error starting VM: VMware error: 2016-01-19T09:14:21.896| ServiceImpl_Opener: PID 55866
Error: The operation was canceled
...
```

Full template and error log at https://gist.github.com/clstokes/25c519371fa4f0acd962.

**Comment by dave2** [comment]
Pre-validation of specs would be difficult, as it depends on the license for your hypervisor. Eg, anyone running ESXi as-is is limited to 8 vCPUs per VM, but if ESXi is part of a vSphere cluster that has some other license then it's a much higher limit (64? I forget).

**Comment by cbednarski** [comment]
Thanks for opening an issue. @clstokes can you elaborate on the use-case?

Fingerprinting is pretty tricky and we'd have to do this for different local and remote OSes so I think it's significantly less complicated and easier to just fail for now.

If you need to set the VMX data to a different value you can do so independently of the stats you use for the build. For example if you're building vagrant boxes and don't want to use 4gb of ram on a user's machine you can still use 4gb to do the build but set the final VMX to use 512mb. When sharing templates I tend to be conservative since it's easy to change later (in either direction).

**Comment by clstokes** [comment]
Fingerprinting was just an idea. I definitely understand it's complex and may be more complex than it's worth.

In this case, the error message is unclear that it's related to the excessive `numvcpus` value so I'm left to essentially troubleshoot this by trial and error - removing properties until it passes. If the error message could be elaborated on to say something to the effect of _"The operation was canceled. Requested hardware exceeds the available host hardware."_ that would be sufficient.

**Comment by cbednarski** [comment]
> If the error message could be elaborated on to say something to the effect of "The operation was canceled. Requested hardware exceeds the available host hardware." that would be sufficient.

That makes sense. I think in this case we have to see whether the hypervisor tells us why. I think in most cases VMware is pretty quiet about these things.

**Comment by dave2** [comment]
More general remarks on start/build problems and lack of error reporting noted here:
https://github.com/mitchellh/packer/issues/1543

There seem to be a few other tickets which boil down to reading out the vmware.log.

**Comment by cbednarski** [comment]
To update this, we tried to pre-validate and it has a lot of edge cases that are hard to get right. I think the better approach is to surface more information about why the build failed as mentioned in #1543

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

I agree that perhaps #1543 is a promising way to solve this
