### ISSUE TITLE
Dynamically set builder name using variables

### ISSUE THREAD

**Issue by osvarsha** [mitchellh/packer#3092]
Hi,

I am trying to build foundation images for various OS flavors (Amazon Linux, CentOS, Ubuntu).

I have the following packer file:

[test-bake.packer.txt](https://github.com/mitchellh/packer/files/96796/test-bake.packer.txt)

I am trying to set the builder name dynamically, but it does not seem to work as I get the following error:

Error initializing core: 1 error(s) occurred:

* provisioner 2: override 'amazon-ebs-ubuntu' doesn't exist

Am I doing something wrong?

**Comment by cbednarski** [comment]
Thanks for opening an issue. Template parsing is kinda complicated, but I think what's happening here is that the post-processor is being validated before variable substitution takes place.

In short what you're trying to do won't work. You might be able get away with the variable name as long as you don't reference it anywhere (e.g. if you don't have a post-processor) but in general you're going to have better results if you duplicate the build section or use a pre-processor to generate your variants.
