### ISSUE TITLE
Packer Package 0.8.6_1 in Brew Install Breaks "amazon-ebs" Builder

### ISSUE THREAD

**Issue by bnied** [mitchellh/packer#3094]
OS X 10.11.3, Packer 0.8.6_1

After updating brew this morning, I get the following error whenever I try to use the `amazon-ebs` builder:

    Failed to initialize build 'amazon-ebs': builder type not found: amazon-ebs

**Comment by cbednarski** [comment]
Thanks for the report. I don't maintain the brew binary / installer so I'll need to check how this was built.

**Comment by bnied** [comment]
No problem. To work around the issue, for now:

    [bnied@bnied-mbp /u/local] (master) $ brew remove packer
    [bnied@bnied-mbp /u/local] (master) $ cd /usr/local
    [bnied@bnied-mbp /u/local] (master) $ git reset --hard a08011e4d66b65c5633458288a0f47412464dbc9
    [bnied@bnied-mbp /u/local] (master) $ brew install packer
    [bnied@bnied-mbp /u/local] (master) $ brew pin packer

**Comment by isuftin** [comment]
@bnied Thoughts on the process to revert this pinning when a new, working version of Packer is out?

**Comment by bnied** [comment]
$ brew unpin packer

That'll unpin it in brew, and allow for normal upgrades.

**Comment by jdburton** [comment]
I'm seeing this too. The problem is with packer 0.8.6_1.

```
brew remove packer
brew switch packer 0.8.6
```

**Comment by isuftin** [comment]
@bnied probably also need to `git reset --hard HEAD` and `brew update` as well, no?

**Comment by bnied** [comment]
You shouldn't need to do both. `brew update` should pull the latest commits without needing a hard reset first.

**Comment by bnied** [comment]
@jdburton I'd forgotten about `brew switch`; thanks for the simpler method.

**Comment by isuftin** [comment]
@bnied thanks for the heads up

**Comment by ricardclau** [comment]
Same problem here, thanks for all the solutions! :+1:

**Comment by DomT4** [comment]
Bug report on our side of the fence for reference: https://github.com/Homebrew/homebrew/issues/48293

@cbednarski Is Packer expecting to be built against a specific version of Go at all? That's pretty much the only thing that has changed on our end in terms of the build environment that would be likely to impact this software but seemingly nothing else recently.

**Comment by cbednarski** [comment]
@DomT4 Packer's dependencies are not currently pinned so they may have drifted between the 0.8.6 build and whenever this version was compiled.

The dependencies will be pinned in the upcoming 0.9 release. In the mean time restoring dependencies to their 0.8.6 state is possible but extremely tedious since it has to be done by hand.

I'm not sure what the intended changes were in 0.8.6_1 but it should be sufficient to use the official 0.8.6 binaries from https://releases.hashicorp.com/packer/0.8.6/

**Comment by DomT4** [comment]
@cbednarski Ah, that could well be it. I wonder if we at `brew` could pin them manually in the formula at the point they were when the release was cut initially; we do something similar for many formulae because it kills these edge cases and allows us something closer to reproducibility.

> I'm not sure what the intended changes were in 0.8.6_1 

Go 1.5.3 fixed a [pretty nasty security problem](http://seclists.org/oss-sec/2016/q1/89) in Go 1.5 - 1.5.2 and we did a broad (~50 formulae) rebuild afterwards as a precautionary measure, as rebuilding was the only way to squash the security issue out from packages already compiled.

**Comment by cbednarski** [comment]
> Go 1.5.3 fixed a pretty nasty security problem in Go 1.5 - 1.5.2 and we did a broad (~50 formulae) rebuild afterwards as a precautionary measure, as rebuilding was the only way to squash the security issue out from packages already compiled.

@DomT4 Packer doesn't run a TLS server, except perhaps in testing, and packer is out of the critical path so the risk to packer as a result of this vulnerability is essentially zero. We (HashiCorp) re-released consul and vault as those serve TLS endpoints and run as persistent services, but decided that releasing packer, terraform, and other CLI utilities is not necessary.

> I wonder if we at brew could pin them manually in the formula at the point they were when the release was cut initially; we do something similar for many formulae because it kills these edge cases and allows us something closer to reproducibility.

You may but as I mentioned this is quite tedious, unfortunately. There are quite a few dependencies to track down (including recursive dependencies). In 0.9 we will vendor these so builds will be deterministic.

**Comment by DomT4** [comment]
>  but decided that re-releasing packer, terraform, and other CLI utilities is not necessary.

Nobody on our team has hugely broad Go knowledge to my understanding, and a fair bit of pressure falls on us to "do the right thing" across everything we supply so we decided to play it better safe than sorry and rebuild anything which could be vaguely sensitive. I was happier rebuilding too much than too little, even with this hiccup, to be honest.

> There are quite a few dependencies to track down (including recursive dependencies).

We already vendor a bunch of the dependencies but we missed a few looking at the build logs from `make bin`. I'll try and chase those up today to fix the problem.

> In 0.9 we will vendor these so builds will be deterministic

That's great to hear; thank you in advance!

**Comment by bnied** [comment]
@DomT4 let me know if you need a tester.

**Comment by DomT4** [comment]
@bnied Feel free to play with https://github.com/Homebrew/homebrew/pull/48393. Works locally.

Manually went and found the commit reference for each dependency at the point the release tag for `packer` was cut. Was fun.

**Comment by bnied** [comment]
@DomT4 testing it out now.

**Comment by bnied** [comment]
@DomT4 looks good! Package built successfully, and the `amazon-ebs` builder is present in the 0.8.6_2 package.

**Comment by bnied** [comment]
Build output: https://gist.github.com/bnied/f2192d3b0f703e3deba7

**Comment by DomT4** [comment]
@bnied Yup, same output here. Phew. Once CI has tested it I'll pull the bottles locally to double check but pending that being alright I'll merge it in and this should be safe to mark as resolved.

**Comment by bnied** [comment]
Awesome, thanks for the quick turnaround on this, @DomT4!

**Comment by DomT4** [comment]
Should now be fixed after a `brew update && brew upgrade packer`.

You'll also now get the same build against the same dependency commits via `--build-from-source` as you do the bottle, which is nice in terms of consistency and stability. Thank you for the assistance, discussions & reports and apologies for this hiccup. Feel free to shout if you run into anything else.

**Comment by bnied** [comment]
Looks good here with the new bottle! Thanks again @DomT4!

**Comment by cbednarski** [comment]
@DomT4 @bnied Thanks for working on this! :D
