### ISSUE TITLE
Online docs do not reflect the current released version

### ISSUE THREAD

**Issue by tylert** [mitchellh/packer#3101]
The latest official release of Packer is currently 0.8.6 (released on Aug 22, 2015), however, the https://packer.io website shows documentation options that are more appropriate for the version that is on the "master" branch--what will presumably become 0.9.0 sometime in the near future.  For example, the https://www.packer.io/docs/provisioners/shell.html#skip_clean page shows an optional parameter that will fail in Packer 0.8.6 but should work fine in newer versions.

Since there isn't a set of convenient offline docs or a way to browse docs on the site "by version", new users might, initially, be a tad confused about the fact that the docs don't quite line up with the version of packer that they are currently using.

I'm not certain the most appropriate solution to this issue but it might involve some or all of:
- keeping a separate doc branch
- marking items that are "NEW" or "COMING SOON" in the docs
- sticking a Packer version in URLs somehow
- generating static docs for offline use
- shortening the time between releases
- etc.

I very much enjoy the fact that the website source and the Packer source are kept in the same place;  It might only be a slight tweak to the process for updating the website that is needed.

**Comment by cbednarski** [comment]
Thanks for the report. This happened because of some non-content related website changes, unfortunately unavoidable in this case. It will be back on parity in 0.9.

**Comment by tylert** [comment]
Awesome!  Thanks again!
