### ISSUE TITLE
Delete cached iso 

### ISSUE THREAD

**Issue by alex131290** [mitchellh/packer#3106]
I'm using packer for ova files creation. I'm running it on a nested ESXi (vmware-iso module). I couldn't find a way to delete the cached iso, which is stored by default at: /vmfs/volumes/datastore1/packer_cache/*.iso (assuming that I'm using datastore1 as my datastore).

**Comment by cbednarski** [comment]
Also: http://stackoverflow.com/questions/34995033/packer-delete-cached-iso

**Comment by mwhooker** [comment]
If you're asking how to delete a cached iso, I think there's an answer on that stackoverflow thread. If that doesn't work for you, you might try asking the mailing list.

If you're asking for packer to implement this functionality, I hate saying 'please make a PR', but after we've discussed this has a very very low chance of ever being a priority for us to do so we'd rather close this issue than have it stagnate for years to come.
