### ISSUE TITLE
Cannot have equals sign in values of environment_vars in powershell provisioner

### ISSUE THREAD

**Issue by LHCGreg** [mitchellh/packer#3108]
If you try to pass a string like `a3df=jk;` as an element in `environment_vars` in the `powershell` provisioner, you get an error

`--> amazon-ebs: Error processing command: Shell provisioner environment variables must be in key=value format`

Uses for variables with equals signs in them: Passwords, active directory OUs (`OU=FOO,OU=BAR,DC=BAZ,DC=LOCAL`), base-64 encoded data.

I took a peek at the code and this seems to be the code causing the error in [provisioner/powershell/provisioner.go](https://github.com/mitchellh/packer/blob/cd4a70f846143e0cc860343eb3fe23bdd404aeb5/provisioner/powershell/provisioner.go):

```
    // Split vars into key/value components
    for _, envVar := range p.config.Vars {
        keyValue := strings.Split(envVar, "=")
        if len(keyValue) != 2 {
            err = errors.New("Shell provisioner environment variables must be in key=value format")
            return
        }
        envVars[keyValue[0]] = keyValue[1]
    }
```

Perhaps it should treat everything before the first = as the key and everything after as the value instead of splitting on "=".

Example template:

```
{
    "variables": {
        "aws_access_key": null,
        "aws_secret_key": null,
        "aws_region": "us-east-1",
        "source_ami": "ami-9a0558f0",
        "vpc_id": null,
        "subnet_id": null,
        "some_var": "a3df=jk;"
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "access_key": "{{user `aws_access_key`}}",
            "secret_key": "{{user `aws_secret_key`}}",
            "region": "{{user `aws_region`}}",
            "source_ami": "{{user `source_ami`}}",
            "instance_type": "m3.medium",
            "ami_name": "Greg Test {{timestamp}}",
            "associate_public_ip_address": false,
            "vpc_id": "{{user `vpc_id`}}",
            "subnet_id": "{{user `subnet_id`}}",

            "ssh_private_ip": true,

            "communicator": "winrm",
            "winrm_username": "Administrator",
            "user_data_file": "{{template_dir}}/setup_winrm.txt"
        }
    ],
    "provisioners": [
        {
            "type": "powershell",
            "script": "ami_setup.ps1",
            "environment_vars": [ "some_var={{user `some_var`}}" ]
        }
    ]
}
```

**Comment by kwilczynski** [comment]
Hey, @LHCGreg is this still an issue? /cc @cbednarski 

I am working on a small provisioner on the side, and I had a look at the code inside both the `shell` and `powershell` provisioners, and it seem to be handling the cases like e.g., `name=value1=value2` and `name=(value1=value2)` just fine. The code above was updated since the issue was opened, and I believe this is no longer an issue.

**Comment by LHCGreg** [comment]
Am I looking at the same place you are @kwilczynski ? I still see the code I referenced in https://github.com/mitchellh/packer/blob/master/provisioner/powershell/provisioner.go and packer/provisioner/powershell/provisioner.go was last changed 8 months ago.

```
    // Split vars into key/value components
    for _, envVar := range p.config.Vars {
        keyValue := strings.Split(envVar, "=")
        if len(keyValue) != 2 {
            err = errors.New("Shell provisioner environment variables must be in key=value format")
            return
        }
        envVars[keyValue[0]] = keyValue[1]
    }
```

**Comment by kwilczynski** [comment]
@LHCGreg ah, I just realised. Same file, different place. Apologies. This is what I was looking at:

https://github.com/mitchellh/packer/blob/master/provisioner/powershell/provisioner.go#L189-L196

This seem to be doing the right thing, contrary to this:

https://github.com/mitchellh/packer/blob/master/provisioner/powershell/provisioner.go#L347-L355
