### ISSUE TITLE
Puppet-masterless provisioner does not upload manifests directory and modules directory

### ISSUE THREAD

**Issue by CruzanCaramele** [mitchellh/packer#3112]
I am building an AWS AMI using Packer. I am also using the puppet-masterless provisioner to install and configure services I need and keep them running. 
All this is successful as the AMI gets created and I am able to launch it on AWS. The puppet masterlss provisioner also runs successfully upon **packer build** command and installs and starts services I want.
However after launching the AMI on AWS, when I navigate to **/etc/puppet/manifests** or **/etc/puppet/modules** directories, my manifests file and modules are missing respectively. As such I have an empty puppet directory with none if my manifest file and modules available that were used during provisioning of the AMI by packer.
I want them present when I launch the AMI because i would like to do some tests directly with the modules without having to re-launch another AMI.
Is this the default behavior of Packer ? I could not find an answer in the docs unless i am missing something very fundamental about the puppet-masterless provisioner.
below is my packer template I used to create the AMI 

```
{
	"variables": 
	{
		"PACKER_OS_FLAVOUR": "ubuntu",
		"PACKER_BOX_NAME": "ubuntu-14.04.3-server-amd64",
	    "AWS_ACCESS_KEY_ID": "{{env `AWS_ACCESS_KEY_ID`}}",
        "AWS_SECRET_ACCESS_KEY": "{{env `AWS_SECRET_ACCESS_KEY`}}",
        "ATLAS_TOKEN": "{{env `ATLAS_TOKEN`}}",
        "ATLAS_USERNAME": "{{env `ATLAS_USERNAME`}}",
        "ATLAS_NAME": "{{env `ATLAS_NAME`}}"
    },

    "builders": [



    {
    	"type": "amazon-ebs",
        "access_key": "{{ user `AWS_ACCESS_KEY_ID` }}",
        "secret_key"  : "{{ user `AWS_SECRET_ACCESS_KEY` }}",
        "region"          : "us-east-1",
        "source_ami" : "ami-10b68a78",
        "instance_type" : "t1.micro",
        "ssh_username" : "ubuntu",
        "ami_name": "packer-cultureonweb {{timestamp}}"
    }

    ],

    "provisioners": [


    {
    	"type": "shell",
        "script" : "scripts/cloud.sh"
    },

    {
    	"type": "puppet-masterless",
        "manifest_file": "puppet/manifests/site.pp",
        "module_paths": ["puppet/modules"]

    }

    ],

    "post-processors":[
    {
    	"type": "vagrant",
    	"keep_input_artifact": false
    },

    {
    	"type": "atlas",
        "only": ["virtualbox-iso"],
        "artifact": "{{user `ATLAS_USERNAME`}}/{{user `ATLAS_NAME`}}",
        "artifact_type": "vagrant.box",
        "metadata": {
        	"provider": "virtualbox"
        }

    },

    {
    	"type": "atlas",
        "only": ["amazon-ebs"],
        "artifact": "{{user `ATLAS_USERNAME`}}/{{user `ATLAS_NAME`}}",
        "artifact_type" : "amazon.ami",
        "metadata": {
        	"created_at": "{{timestamp}}"
            }
    }

    ],

    "push":
    {
        "name": "Panda/culture_brands"
    }
}
```

**Comment by rickard-von-essen** [comment]
Check [```staging_directory```](https://www.packer.io/docs/provisioners/puppet-masterless.html#staging_directory)

**Comment by cbednarski** [comment]
@CruzanCaramele As @rickard-von-essen hinted, this is uploaded to `/tmp` by default and run from there -- nothing is ever installed to `/etc`. `/tmp` is typically deleted when a machine restarts so if you want these to persist you'll need to tweak some of those settings in your configs.

**Comment by CruzanCaramele** [comment]
thank you @rickard-von-essen  for the hint
@cbednarski thank you for the information, i will go through the docs to see if it can be improved
