### ISSUE TITLE
Error Authentication running Packer with Openstack template

### ISSUE THREAD

**Issue by YamanduTellechea** [mitchellh/packer#3116]
I have created a simple openstack template to packer:

{"builders":[
{
  "type": "openstack",
  "username": "root",
  "password": "temporal",
  "region": "xxxxx",
  "ssh_username": "root",
  "image_name": "xxx_Packer",
  "source_image": "xxxxxxxxxxxxxxxxxx",
  "flavor": "A1"

}
]}

and I have declared necessary enviroment variables to authentication:

OS_AUTH_URL=http://keystone.xxxxxxx:5000/v2.0
OS_TENANT_ID=xxxxxxx
OS_TENANT_NAME="xxxxxxx"
OS_USERNAME="xxxxxxx"
OS_PASSWORD="xxxxxxx"
OS_REGION_NAME="xxxxx"

However, when i run my .json, terminal shows that error:

Debug mode enabled. Builds will not be parallelized.

    openstack output will be in this color.

    1 error(s) occurred:

    * Expected HTTP response code [200 203] when accessing [POST http://keystone.xxxxxxxx:5000/v2.0/tokens], but got 401 instead
    {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}

**Comment by rickard-von-essen** [comment]
```username``` in your template overrides ```OS_USERNAME``` I guess root is not your OpenStack user.

**Comment by YamanduTellechea** [comment]
Thank you, I must be blind, I have remove username and password and packer running correctly.
