### ISSUE TITLE
Support tilde ("~") as home folder in GCP's account_file property

### ISSUE THREAD

**Issue by phanect** [mitchellh/packer#3119]
I wrote following packer.json5 (and compiled it to JSON) but it doesn't allow me to use `~` in `account_file` property.

``` json5
{
  builders: [{
    type: "googlecompute",
    account_file: "~/.secrets/gcp-{{ user `env` }}.json",
    // …
  }],
  provisioners: [
    // …
  ]
}
```

``` sh
$ packer validate -var "app_name=app" -var "env=staging" packer.json
Template validation failed. Errors are shown below.

Errors validating build 'googlecompute'. 1 error(s) occurred:

* Failed parsing account file: open ~/.credentials/gcp-staging.json: no such file or directory

  error: exit status 1
$ ls ~/.credentials/gcp-staging.json # Check if the file really exists
/home/phanect/.credentials/gcp-staging.json
```

Currently I specify ~/.secrets/gcp-{{ user `env` }}.json as full path (/home/phanect/.secrets/gcp-{{ user `env` }}.json) but I appreciate if Packer allowed us to specify path using `~`.

**Comment by cbednarski** [comment]
Thanks for the suggestion. `~` is handled by bash expansion and since this code path does not call bash the path is not expanded. I think we will need to string-replace this using [go-homdir](https://github.com/mitchellh/go-homedir).

In the mean time, it may be easier to specify `"account_file": ".secrets"`, which you can symlink to `~/.credentials` or wherever you prefer.

**Comment by phanect** [comment]
:+1:

**Comment by rickard-von-essen** [comment]
There is a easy solution to this:
Use a user variable which references env var $HOME
```"home": "{{env `HOME`}}"```
and then
```account_file: "{{ user `home` }}/.secrets/gcp-{{ user `env` }}.json"```
That should work.

**Comment by cbednarski** [comment]
@rickard-von-essen thanks for the suggestion! We should add this example to the documentation. If we handle `~` in packer we can make it work on Windows, too, so I will leave this issue open.

**Comment by phanect** [comment]
@cbednarski @rickard-von-essen Thanks for reply and suggestion.

@rickard-von-essen's workaround looks also nice, but even on Linux (and Mac?) it is so valuable if we could write path much simpler with `~` IMO :)
