### ISSUE TITLE
FYI: A chef-solo issuing an immediate reboot with subsequent shell provisioner to handle reboot may have race conditions.

### ISSUE THREAD

**Issue by grahamc** [mitchellh/packer#3124]
I have a chef solo provisioner which issues a reboot, then a shell provisioner, then a second chef provisioner. As far as I can tell, the chef provisioner can't sleep to make sure the reboot happens within Chef. This can cause confusing behavior where the shell provisioner runs, then the second chef provisioner starts, and then a mysterious stop. Adding a second shell provisioner directly after the chef provisioning with a sleep can help fix this issue.

This took quite some time to debug. I searched the issue tracker, didn't find anything, and so I'm posting this to help the next person who might try.

**Comment by cbednarski** [comment]
Thanks for the report. Did you intend to close this, or should I still track this issue?

**Comment by mconigliaro** [comment]
This might be the answer I'm looking for. So if the chef-client provisioner triggers a reboot, I need to add a second shell provisioner to sleep during the reboot, then copy and paste my original chef-client provisioner to make Chef run again?

**Comment by mconigliaro** [comment]
OK, that worked. I also tried just setting `pause_before` on the second call to the chef provisioner, but that didn't work for some reason. I guess you need that intermediate shell provisioner, but it's not clear to me why.
