### ISSUE TITLE
Add a note about using $HOME environment variable

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#3125]
From: https://github.com/mitchellh/packer/issues/3119#issuecomment-176123898

If you want to reference a file stored under your home directory (`~`) you can use the $HOME environment variable to interpolate it into the packer template. For example:
```
"variables" {
  "home": "{{env `HOME`}}"
}
...
{
  "builders": [{
    "type":"google",
    "account_file": "{{ user `home` }}/.secrets/gcp-{{ user `env` }}.json"
  }]
}
```

**Comment by tylert** [comment]
I also recently came across a need to do the same for PACKER_CACHE_DIR too:

````
...
  "variables": {
...
    "packer_cache_dir": "{{env `PACKER_CACHE_DIR`}}",
...
  },
...
  "builders": [
...
      "iso_target_path": "{{user `packer_cache_dir`}}/{{user `iso_file`}}",
...
  ],
...
````

The stuff above works, however, it didn't seem to work when I tried to do:

````
...
  "variables": {
...
    "iso_destination": "{{env `PACKER_CACHE_DIR`}}/{{user `iso_file`}}",
...
  },
...
````

I shall have to do some more testing later after I finish my template cleanup.

**Comment by tylert** [comment]
Nevermind... PEBKAC.  It works.
