### ISSUE TITLE
packer fails on "Provisioning with shell script" on current master

### ISSUE THREAD

**Issue by arosenhagen** [mitchellh/packer#3138]
While I want to build Parallels 11 boxes, I checked out a current dev build.
There's currently an error preventing me from building any boxes (e.g. https://github.com/ffuenf/vagrant-boxes/blob/master/packer/debian-8.2.0-amd64.json) on any provider.

```
==> virtualbox-iso: Provisioning with shell script: scripts/update.sh
    virtualbox-iso: bash: no: No such file or directory
==> virtualbox-iso: Unregistering and deleting virtual machine...
```
with the corresponding script at https://github.com/ffuenf/vagrant-boxes/blob/master/packer/scripts/update.sh (while this is an error within packer and not within this script)

**Comment by rickard-von-essen** [comment]
This is most certainly not a packer bug. I tried to run this with Debian 8.3.0 but preseed fails. Does Debian have bash installed by default?

**Comment by arosenhagen** [comment]
so for me https://github.com/mitchellh/packer/commit/15f99a4aee781e7558b1ce0beb921b19d258dec7 introduced a breaking chance to the shell provider in [provisioner/shell/provisioner.go](https://github.com/mitchellh/packer/blob/15f99a4aee781e7558b1ce0beb921b19d258dec7/provisioner/shell/provisioner.go).
reversing those lines get me past my error (I have no error in preseed, but that maybe an issue due to my local progress not already present in the repo)

**Comment by rickard-von-essen** [comment]
Sorry, your completely correct. It doesn't work since that commit. Thank you for trouble shoot this.

**Comment by rickard-von-essen** [comment]
Reverting this:

```udiff
diff --git a/provisioner/shell/provisioner.go b/provisioner/shell/provisioner.go
index 78826b6..583f598 100644
--- a/provisioner/shell/provisioner.go
+++ b/provisioner/shell/provisioner.go
@@ -78,11 +78,6 @@ func (p *Provisioner) Prepare(raws ...interface{}) error {
        err := config.Decode(&p.config, &config.DecodeOpts{
                Interpolate:        true,
                InterpolateContext: &p.config.ctx,
-               InterpolateFilter: &interpolate.RenderFilter{
-                       Exclude: []string{
-                               "execute_command",
-                       },
-               },
        }, raws...)
        if err != nil {
                return err
```

Fixes it. @cbednarski will you fix this, I hadn't had time to look into why this broke stuff or why it was done.

**Comment by cbednarski** [comment]
@arosenhagen Thanks for the report!

Good catch on this @rickard-von-essen; I missed this one after merging. Thanks!
