### ISSUE TITLE
File provisioner fails when no non-dotfiles in directory.

### ISSUE THREAD

**Issue by SomeoneWeird** [mitchellh/packer#3142]
The file provisioner fails to copy dotfiles when copying directories. It also makes the build fail when there are only dotfiles in a directory (probably related to first issue).

The tests were run with a folder called `/tmp/somedotfiles/`.
Both tests had a file called `.helloworld`, and the test that succeeds also has a file called `helloworld` in the directory. Noting that even though the build succeeds, only `helloworld` is copied, and not `.helloworld`.

See [gist](https://gist.github.com/SomeoneWeird/680902d0bf487caca615) for related output.

Let me know if you need more info.

**Comment by cbednarski** [comment]
Additional feedback from @mak18ah in #3309

----

For file-provisioner, when local source path to file contains a dotfile at root fails to upload into target machine.
sample packer template to illustrate the issue:
```
{
  "variables": {
    "app_slug": "test-app"
  },
  "builders": [
    {
      "type": "docker",
      "image": "ubuntu:14.04",
      "discard": true
    }
  ],
  "provisioners": [
    {
          "type": "file",
          "source": ".",
          "destination": "/tmp/app"
    },
    {
          "type": "file",
          "source": ".nvmrc",
          "destination": "/tmp/app"
    },
    {
       "type":"shell",
       "inline":[
         "echo `cat /tmp/app/test/.hello`",
         "echo `cat /tmp/app/.nvmrc`"
       ]
    }
  ]
}
```
 Example source dir:
```
├── build.log
├── compile.json
├── .nvmrc    # fails to copy this over to target, even when explicitly specified in packer template
└── test
    ├── .hello
    └──  project
        └── dir
            └── example.txt
```

Does not occur with dotfiles located in subdirectories.

Created project example here: https://github.com/mak18ah/packer-hidden-source-files-fail use `PACKER_LOG=1 packer build compile.json` to run
Here is the debug log: https://gist.github.com/mak18ah/465cd29945371ad09e62#file-file-provisioner-source-dotfile

Packer client version info:
```
$ PACKER_LOG=1 packer -version
2016/03/04 14:57:47 [INFO] Packer version: 0.8.6  f8f7b7a34c1be06058f5aca23a51247db12cdbc5+CHANGES
2016/03/04 14:57:47 Packer Target OS/Arch: darwin amd64
2016/03/04 14:57:47 Built with Go Version: go1.5
```

**Comment by SomeoneWeird** [comment]
Any update on this? Unsure where to even start looking, I've skimmed through the file provisioner code but couldn't see anything obvious excluding dotfiles

**Comment by cbednarski** [comment]
@SomeoneWeird Sorry I have not had a chance to look at this yet.

**Comment by benwtr** [comment]
This works fine for me with the ebs-builder, I'm only seeing this behaviour with the docker builder.

I worked around it by adding an extra file provisioner that explicitly copied the `.path/` I needed.

**Comment by benwtr** [comment]
Could it be this? https://github.com/mitchellh/packer/blob/master/builder/docker/communicator.go#L182

Looks like it copies the files to a temp space on the container, then moves it from there to the destination dir, except that glob here `cp -R %s/* %s` won't match dotfiles in the root of the temp path.

**Comment by benwtr** [comment]
Confirmed the `%s/*` globbing is the problem. 

It looks like it should be extremely simple to fix, but I don't know of a straightforward solution that doesn't involve shell-specific features for changing glob behaviour or `cp` flags that may not exist in every implementation of `cp`.

**Comment by joshenders** [comment]
I think I'm noticing this behavior again on packer `1.2.2`

The following fails to copy `upload/.foo`

```
  "provisioners": [
    {
      "type": "file",
      "source": "upload",
      "destination": "/tmp"
    },```

to `/tmp/upload`
