### ISSUE TITLE
Packer error while validating memory is available for the build

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#3144]
From @tylert https://github.com/mitchellh/packer/pull/3096#issuecomment-178643189

I am also attempting to start actively using some features of 0.9.0 before the official release and ran into a new error while trying to use my existing templates.

The new error I receive is:

```
* Error parsing string: strconv.ParseUint: parsing "{{user `ram_size`}}": invalid syntax
```

My templates work **perfectly** in Packer 0.8.6 and with binaries built from commit id 4aa59e4999ed8ff433299bf4f4645ad062e78db7 (one commit _*before*_ these commits were merged) but fail when trying to run it against binaries built from either master HEAD (commit 114bddfe363257078db2ac2686d0f327394d112f) or commit ffb85f6ea511fa0108a639c879b43e14c799c808.

Was it intentional that this pull-request should also force a template change when using the virtualbox-iso builder?  If the problem is merely "User Too Stupid", I can simply update my templates accordingly;  If not, perhaps my particular use-case may help isolate the problem.

These are the templates I am using:

* with 0.8.7-dev/0.9.0-specific changes https://github.com/tylert/packer-build/blob/bde7340fc461f12fa4ce357aa8822fead4772c79/ubuntu/xenial/base-64.json
* without 0.8.7-dev/0.9.0-specific changes https://github.com/tylert/packer-build/blob/32d9faa191b69b0dad07edf84baab896f8ffafb2/ubuntu/xenial/base-64.json

The offending part of my template above would appear to be:

```
...
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "{{user `ram_size`}}"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "1"
        ]
      ],
...
```

If I try to massage these arrays of strings a bit to get past the error, Packer crashes (I shall capture the crash data *if* the answer to my query above should reveal that the error was not caused by my sloppy templates).

**Comment by tylert** [comment]
@cbednarski Thanks again.  Please let me know if there is anything else you would like me to try.
