### ISSUE TITLE
Packer hangs after reboot

### ISSUE THREAD

**Issue by ferrarimarco** [mitchellh/packer#3148]
Hi everyone.

I am trying to build a Ubuntu Server 15.04 on a Windows 10 x64 host, with Packer 0.86 and Virtualbox 5.0.14.

I have currently one shell provider that installs Ansible from source and reboots the machine. The VM reboots fine but Packer does not do anything after that.

Here is the relevant part of the template ([here](https://github.com/netgroup/Mantoo-VM-conf/blob/development/packer/OSHI-VM.json) is the full one):
```
	  "provisioners": [
		{
		  "type": "shell",
		  "execute_command": "echo '{{ user `ssh_password` }}' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
		  "script": "scripts/ansible.sh"
		},
		{
		  "type": "ansible-local",
		  "inventory_file": "../ansible/inventory",
		  "pause_before": "1m",
		  "playbook_dir": "../ansible",
		  "playbook_file": "../ansible/an_ansible_role.yml"
		}
	  ],
```

Here is the ansible.sh script:
```
#!/bin/bash

# Enable script output
set -x

# Install required packages
apt-get -y install git python-pip python-dev build-essential
pip install paramiko PyYAML Jinja2 httplib2 six

# Install Ansible from source
cd /opt
git clone git://github.com/ansible/ansible.git --recursive
cd ./ansible
source ./hacking/env-setup

# Put Ansible in PATH
echo "export PATH=/opt/ansible/bin:$PATH" >> /etc/profile.d/ansible.sh
chmod +x /etc/profile.d/ansible.sh

# Reboot to refresh PATH changes
# See "Handling Reboots" section in https://www.packer.io/docs/provisioners/shell.html
reboot
sleep 60
```

The last output I get from Packer is:
> virtualbox-iso: +reboot

I see that the machine is rebooting because I disabled the headless mode.

Packer is not frozen because if I CTRL-C, it correctly stops the process and cleans up.

Thanks.

**Comment by jmassara** [comment]
It's probably because Packer has no idea you rebooted.  I do something similar after I patch a system. Here's the relevant bits from my packer config.

```json
{ "type": "shell", "inline": ["sudo reboot", "sleep 300"] },
{ "type": "shell", "start_retry_timeout": "15m", "inline": ["echo $(date) > /tmp/rebooted"] }
```

The second script is basically just waiting for 15 minutes for the system to come back online and write out a file to temp.  The rest of the provisioning continues on after that.

**Comment by cbednarski** [comment]
Also to see more of what's happening during the hang you can run packer with `PACKER_LOG=1 packer build...` which will show debug logs. You should be able to see if there is a timeout or other issue.

**Comment by ferrarimarco** [comment]
Thanks.

I tried to run with PYTHON_LOG=1 but I did not found anything.

The relevant lines of the log (first line is the last one of the Ansible installation script):

> 2016/02/05 09:26:29 ui:     virtualbox-iso: Done!
> 2016/02/05 09:26:29 ui:     virtualbox-iso:
> 2016/02/05 09:26:29 ui:     virtualbox-iso: + reboot

I got nothing more, even after adding a "dummy task" as @jmassara suggests.

Thanks

**Comment by rickard-von-essen** [comment]
This is probably a network issue. To troubleshoot that it's best to use head mode and log into the console after reboot and check that the network is up and running (```ifconfig```, ```ping``` etc).

Furthermore there is no need to reboot Linux, except when updating kernel (and not even that anymore). The ```ansible-local``` provisioner will login again through ssh and thus load all login scripts.

**Comment by ferrarimarco** [comment]
I logged in the machine (in the meantime packer is still waiting) and I have network connectivity. I can ping, wget a curl without problems.

**Comment by rickard-von-essen** [comment]
This actually works for me. Could you you rerun with ```PACKER_LOG=1``` (not ```PYTHON_LOG=1```) i.e. ```PACKER_LOG=1 packer build OSHI-VM.json``` and [gist](https://gits.github.com) the output.

**Comment by ferrarimarco** [comment]
Done, [here ](https://gist.github.com/ferrarimarco/07e9c44b063118c7ee48) it is. Thanks.

**Comment by rickard-von-essen** [comment]
The script in repos is not like the one in the you posted above. The one in the repo work, just stick with that.

Closing as solved, reopen if you still have problems.
