### ISSUE TITLE
Share the images to other accounts

### ISSUE THREAD

**Issue by SydOps** [mitchellh/packer#3150]
Hi 

I am looking for an easy way to share the new ami image to other accounts. 

I can use the template to generate an AWS AMI image, but I have to manually share it to other consolidated accounts every time. 

Is the feature exist in packer?

**Comment by SydOps** [comment]
Seems this will be a new feature for builders of aws. Not sure if there are same requests for other cloud builders.

I did some research and hope to add a new feature after image is generated. Related aws comand is:

    aws ec2 modify-image-attribute --image-id ami-2bb65342 --launch-permission "{\"Add\":[{\"UserId\":\"123456789012\"}]}"

So I need a `post-processors` to share the images
```
  "post-processors": [
    {
      "type": "sharing",
      "account": ["123456789", "987654321"],
    }
  ],
```

I am not golang developer, should be fine to use `Step_register_ami.go` is a nice reference:

https://github.com/mitchellh/packer/blob/master/builder/amazon/instance/step_register_ami.go

**Comment by SydOps** [comment]
find this code, but don't know how to use it to change `LaunchPermission`

https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_modify_ami_attributes.go#L70

**Comment by SydOps** [comment]
looks I am closed to the feature: 

https://github.com/mitchellh/packer/issues/479

**Comment by SydOps** [comment]
ticket can be closed now. I did it with `ami_users`.

**Comment by afaleti** [comment]
Nice!

**Comment by atrakic** [comment]
cannot be used on  encrypt_boot

**Comment by WeekendsBull** [comment]
@atrakic would you be able to use something else rather than ami_users?
