### ISSUE TITLE
Add `skip_clean_staging_dir` option for chef-client provisioner

### ISSUE THREAD

**Issue by icberg7** [mitchellh/packer#3151]
Hi there,
I've recently discovered that packer deletes the [`staging_directory`](https://www.packer.io/docs/provisioners/chef-client.html#staging_directory) after provisioning is complete, even with `skip_clean_client` and `skip_clean_node` set. I found #2738 and understand this is by design, but it would be nice to have an option to prevent the work directory cleanup.

This would be very useful with troubleshooting template issues alongside the null builder. Also, I'm working on a packer template for a workstation virtual machine, and it would be nice if these files were retainable so that the end user could run `chef-client` in local mode at some point later against a newer version of the cookbook (or in case they did something to inadvertently break something).

**Comment by cbednarski** [comment]
> This would be very useful with troubleshooting template issues alongside the null builder. Also, I'm working on a packer template for a workstation virtual machine

Thanks for opening an issue. For troubleshooting you can run packer with the `-debug` flag and it will pause after each step. You can proceed until the provisioner runs and then login to the machine to inspect the files, re-run commands, etc.

> it would be nice if these files were retainable so that the end user could run chef-client in local mode at some point later against a newer version of the cookbook (or in case they did something to inadvertently break something).

For now I would recommend using a provisioner to copy these into a permanent location of your preference. `/tmp` is typically deleted when the box restarts.

**Comment by slbmeh** [comment]
> For now I would recommend using a provisioner to copy these into a permanent location of your preference. /tmp is typically deleted when the box restarts.

I'm trying to have a shell provisioner copy the `client.rb` from the `chef-client` provisioner, however the staging directory is destroyed after the chef provisioner completes preventing another provisioner from accessing it.
