### ISSUE TITLE
knife.rb is copied to the machine even if `skip_clean_node` and `skip_clean_client` are both `true`

### ISSUE THREAD

**Issue by icberg7** [mitchellh/packer#3152]
I'm running into an issue where running chef-client in local mode is changing the current directory that it's run in. I tried adding a `cd /tmp/packer-chef-client` inline with the chef client `execute_command`, which preserves permissions on the home directory and allows subsequent ssh connections, but packer will try to copy a `knife.rb` to this directory, even with `skip_clean_node` and `skip_clean_client` set to `true`, which fails because the permissions and ownership have been changed.

It may be useful to revisit #1520, as this would negate the need to mess with `knife.rb` Otherwise, it would be nice if Packer did not bother copying a `knife.rb` when both the skip cleanup options are `true`.

**Comment by cbednarski** [comment]
I may be missing some nuance to your report but this is how the chef provisioner works. Settings are written into `knife.rb` and then check is invoked using `knife.rb`. `skip_clean_*` happens after the chef run so as far as I understand uploading `knife.rb` is orthogonal to those settings.

**Comment by icberg7** [comment]
The `knife.rb` is only written after the chef run and is used to run `knife client delete <foo>` and `knife node delete <foo>`. If you're not deleting a client and not deleting a node, you don't need `knife.rb` at all.
https://github.com/mitchellh/packer/blob/master/provisioner/chef-client/provisioner.go#L267-L271

The alternative, mentioned in #1520, was to make API calls directly from packer to the chef client to perform these cleanup actions, which would eliminate the need for `knife.rb` entirely.
