### ISSUE TITLE
Improved error handling with Packer failures

### ISSUE THREAD

**Issue by adamstrawson** [mitchellh/packer#3153]
I'm trying to tie Packer into Jenkins to build an OpenStack image in a Private Cloud, but the error reporting isn't proving anything useful to me to debug with. 

Running packer on CLI works fine and does what is expected, but if I run it within Jenkins it fails with the below (The below is all I get with both `-debug` and `PACKER_LOG=1`);

```
2016/02/05 12:24:24 Build 'openstack' prepare failure: 1 error(s) occurred:

* Get /: unsupported protocol scheme ""
2016/02/05 12:24:24 ui error: 1 error(s) occurred:

* Get /: unsupported protocol scheme ""
```

I had this error before which was because the env vars weren't set at the time, but this isn't the case here. If I run `env` before Packer runs all the correct env vars are available and the same as what is being run with CLI. 

I know this isn't directly a packer issue, but the unclear error reporting isn't helping to resolve my issue, so this issue report is more towards improving error handling.

If anyone does know why the above is happening though, I'll owe you a beer as a reward. 

For reference though, here's what I have in Jenkins;

output from build env (unrelated omitted) 

```
OS_PASSWORD=xxxx
OS_AUTH_URL=http://x.x.x.x:5000/v3
OS_USERNAME=packer
OS_TENANT_ID=xxxx
```

And the packer json;

```json
{
  "builders": [
    {
      "flavor": "2",
      "image_name": "packer-test-image",
      "source_image": "e73352d7-9490-47f1-871c-1e4e92a4eeaa",
      "ssh_username": "xxxx",
      "ssh_private_key_file": "/var/lib/jenkins/packer/packer.key",
      "ssh_keypair_name": "packer",
      "type": "openstack",
      "domain_id": "default",
      "networks": ["xxxx"],
      "use_floating_ip": true,
      "floating_ip_pool": "xxxx",
      "security_groups": ["default"]

    }
  ],
  "post-processors": null,
  "provisioners": [
    {
      "inline": [
        "sleep 30",
        "[DO TASK]"
      ],
      "type": "shell"
    }
  ]
}
```

**Comment by adamstrawson** [comment]
I found a work around for the original issue, seems packer isn't acknowledging the env variables even though Jenkins see them.

Adding `identity_endpoint` to the builders, with the addition of username, password, works.

`identity_endpoint` isn't actually in the documentation for Packer OpenStack builders, I found it in an example on a blog post.

Not ideal as I'd rather it used the env variables so that the credentials are not in the file as they'll be stored in GIT, but will have to do for now.

**Comment by cbednarski** [comment]
A few ideas here:

If you have shell access to the Jenkins box, try logging into the box and running the packer build as the jenkins user. For example:

    sudo su jenkins
    cd $workspace
    packer build

If you're using a shell builder in Jenkins you can echo the environment from the build to see whether or not the values are populated with the values you expect. For example:

    echo $OS_AUTH_URL
    echo $OS_USERNAME
    packer build packer.json

If all else fails you can source the environment in your job. For example:

    OS_AUTH_URL=alsdf packer build packer.json

My recollection is that you cannot use `source` or `export` to set environment variables in the inline shell code in Jenkins (maybe each line is invoked in a different shell?) but you can work around this by running e.g. `build.sh` which does everything in one script.

**Comment by adamstrawson** [comment]
Hi @cbednarski 

Thanks for posting so quickly!

Running as the Jenkins user on the server runs fine, it's only within Jenkins itself that it fails with that error.

I'm not using the shell builder, it's the Packer Jenkins plugin, but will have a play using the shell builder and see if I get the same results.

Worth mentioning that I've tried added the OS_* variables as global env vars within Jenkins too so should in theory be available with every build (which they are according to outputing 'env' on a shell build, but Packer still doesn't seem them.

**Comment by cbednarski** [comment]
I see in the docs that packer should fall back on the environment variables, but the more common way is to pass these in via [user variables](https://www.packer.io/docs/templates/user-variables.html). You can try that as well.

Can you also verify you're using the same version of packer in both places? Is the OS different, or anything else that would contribute to the environment having quirks?

**Comment by adamstrawson** [comment]
Thanks, I'll give that a try.

It's the same version (0.8.6), when running it on CLI I was using the same path/install that Jenkins was running it as.

**Comment by rickard-von-essen** [comment]
I have opened a PR addressing the missing info about the OpenStack builder please read the docs at https://github.com/rickard-von-essen/packer/blob/issue-2701/website/source/docs/builders/openstack.html.markdown
and comment in that PR if you have any improvements.

**Comment by rickard-von-essen** [comment]
With v3 you might need ```OS_DOMAIN_NAME```.

Best advice I can give is to download a OpenStack RC file, see [new docs](https://github.com/rickard-von-essen/packer/blob/issue-2701/website/source/docs/builders/openstack.html.markdown#notes-on-openstack-authorization) and adjust the values. Be sure to not unset ```OS_TENANT_ID``` and ```OS_TENANT_NAME``` since they are used by the OpenStack go lib.

**Comment by adamstrawson** [comment]
> I have opened a PR addressing the missing info about the OpenStack builder 

Thanks @rickard-von-essen Useful to see the changes in the docs. 

> With v3 you might need `OS_DOMAIN_NAME`
> Best advice I can give is to download a OpenStack RC file

We're not utilizing domains on our setup so should be defaulting to 'Default', I've not had any issues on CLI with it this way. I have an openrc file in place already which works fine on CLI, but seems that Jenkins doesn't acknowledge that or any env vars for Packer, so had to compromise with having the credentials as part of the builder rather than as env vars. 


_Side note, I'm impressed with the speed of response and helpfulness of this project, kudos!_

**Comment by rickard-von-essen** [comment]
So the solution was to define OpenStack authorisation variables in the template and not through environment variables (```OS_```)?

If it's OK please close.

**Comment by cbednarski** [comment]
@adamstrawson Thanks for following up to close this. If you have any further issues please feel free to open a new issue.
