### ISSUE TITLE
amazon-ebs builder seems to ignore ssh_password

### ISSUE THREAD

**Issue by SanderKnape** [mitchellh/packer#3156]
I've uploaded a test AMI to AWS to which I can connect with both the ssh_username and ssh_password set to "vagrant". Spinning up an instance and connecting with it using these credentials allows me to succesfully connect. Also, during the Packer build phase, I can connect with the machine using these credentials.

However, packer itself seems to ignore the ssh_password, as the error I'm getting is as follows:

`--> amazon-ebs: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

Also, a quick look through [Packer source](https://github.com/mitchellh/packer/blob/024132a698092b0d950d0aaffdb8821616de6a72/builder/amazon/common/ssh.go#L68) tells me that password-based SSH authentication is never configured. Though it's very possible I'm not looking at the correct code.

The following is the setup of my builder:

```
{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "eu-west-1",
    "source_ami": "ami-ebe95898",
    "instance_type": "t2.micro",
    "communicator": "ssh",
    "ssh_username": "vagrant",
    "ssh_password": "vagrant",
    "ami_name": "packer-example {{timestamp}}"
}
```

Am I correct in concluding that my ssh_password is never used? Is this a missing feature? I'm fully aware of the security implications of using password-based SSH authentication and don't plan to use this in any production environment, but was hoping to quickly get something up and running.

**Comment by jjduhamel** [comment]
I'm having a similar issue building from an image with pam_duo installed.  I think keyboard-interactive mode needs to be added to the amazon-ebs builder.

https://github.com/mitchellh/packer/search?utf8=%E2%9C%93&q=PasswordKeyboardInteractive

**Comment by rickard-von-essen** [comment]
Please test if PR #3953 solves your issue.
