### ISSUE TITLE
[driver_esx5] dont check for power_on error to force retry

### ISSUE THREAD

**Issue by dantran** [mitchellh/packer#3157]
Details discussion is here https://groups.google.com/forum/#!topic/packer-tool/OQ8rbQ2x4qw

where after the register of vm, immediate power on can result in failure and prevent any retry

My environment is virtual esxi6 with sles12

here is the code

    func (d *ESX5Driver) Start(vmxPathLocal string, headless bool) error {
	for i := 0; i < 20; i++ {
		err := d.sh("vim-cmd", "vmsvc/power.on", d.vmId)
		if err != nil {
			return err  
		}
		time.Sleep((time.Duration(i) * time.Second) + 1)
		running, err := d.IsRunning(vmxPathLocal)
		if err != nil {
			return err
		}
		if running {
			return nil
		}
	}
	return errors.New("Retry limit exceeded")
    }

**Comment by dantran** [comment]
hmm, looking at the loop again, it is not that simple, unless we also dont check error at IsRunning

**Comment by dantran** [comment]
I can confirm that remove the check after power.on step works for me

**Comment by dantran** [comment]
Please advice if it is the right fix, I can submit the PR with comment why it should be this way

**Comment by dantran** [comment]
func (d *ESX5Driver) Start(vmxPathLocal string, headless bool) error {
        for i := 0; i < 20; i++ {
            d.sh("vim-cmd", "vmsvc/power.on", d.vmId)
            //intentionally not check for error since power on may fail specially after initial VM registration

            time.Sleep((time.Duration(i) * time.Second) + 1)
            running, err := d.IsRunning(vmxPathLocal)
            if err != nil {
                return err
            }
            if running {
                return nil
            }
        }
        return errors.New("Retry limit exceeded")
}

**Comment by cbednarski** [comment]
Thanks for the report. I think a retry loop makes sense but can you explain why we need to retry 20 times? This means waiting up to 3.5 minutes. I'm curious why registration -> poweron needs to wait this long. To clarify, I'm not objecting to the change, I'd just like to understand why it's needed. Please feel free to open a PR for this in the mean time so I can provide feedback on the change. Thanks!

**Comment by dantran** [comment]
20 times was there before. 

My change is very simple.  just ignore error at d.sh("vim-cmd", "vmsvc/power.on", d.vmId)

**Comment by dantran** [comment]
PR #3195

**Comment by peterloron** [comment]
This issue appears to be biting us as well.

**Comment by dantran** [comment]
please merge the PR, sothat @peterloron can continue to see other problem that I see

**Comment by peterloron** [comment]
Any update on the status of this issue?

**Comment by dantran** [comment]
and we stuck with packer 0.8.x

**Comment by dantran** [comment]
@rickard-von-essen have a latest snapshot build i can try out?

**Comment by rickard-von-essen** [comment]
@dantran which os/arch do you want?

**Comment by dantran** [comment]
linux 64bit

**Comment by rickard-von-essen** [comment]
@dantran [Linux amd64 build](https://drive.google.com/file/d/0Bxyf6LmhsEt1bC0xSjBBRWJNY28/view?usp=drivesdk)

**Comment by dantran** [comment]
is it an executable of an archive?. I am not able to unpack using zip and tgz

**Comment by rickard-von-essen** [comment]
It's the packer executable:
```shell
$ file ~/Downloads/packer_linux_amd64_0.10.2.dev
/Users/rickard/Downloads/packer_linux_amd64_0.10.2.dev: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by dantran** [comment]
now i am hitting a blocker similar to https://github.com/mitchellh/packer/issues/3165

2016/08/21 13:32:16 packer: 2016/08/21 13:32:16 starting remote command: rm -rf /vmfs/volumes/EIX_703/ecdm-kickstart
2016/08/21 13:32:16 packer: 2016/08/21 13:32:16 remote command exited with '0': rm -rf /vmfs/volumes/EIX_703/ecdm-kickstart
2016/08/21 13:32:16 ui error: [1;31mBuild 'vmware-iso' errored: open rpm-summaries.txt/rpm-summaries.txt: no such file or directory[0m
2016/08/21 13:32:16 Builds completed. Waiting on interrupt barrier...
2016/08/21 13:32:16 machine readable: error-count []string{"1"}
2016/08/21 13:32:16 ui error: 
==> Some builds didn't complete successfully and had errors:

**Comment by dantran** [comment]
looks  to me the error is producible if I have the following json download

        {
            "type": "file",
            "source": "/root/rpm-summaries.txt",
            "destination": "rpm-summaries.txt",
            "direction": "download"
        }
