### ISSUE TITLE
Digital Ocean build should paginate snapshots when querying for IDs

### ISSUE THREAD

**Issue by slackpad** [mitchellh/packer#3158]
Once a user has more than 200 images, this routine will fail to locate any newly-created ones:

https://github.com/mitchellh/packer/blob/master/builder/digitalocean/step_snapshot.go#L52-L74

It looks like DO sorts them in ascending order by age, so the new ones are always on the last page. We could paginate through them, or depending on the API we could calculate and always fetch the last page. It doesn't look like there's sort control, at least in the Go API.

**Comment by vtolstov** [comment]
I think that do builder needs to use godo client

**Comment by rickard-von-essen** [comment]
@vtolstov it does.

**Comment by andrewsomething** [comment]
As we have the Droplet's ID, we could use `godo.Droplets.Snapshots` which lists snapshots based on a specific Droplet. It's also a paginated resource, but as the Droplet is created just to build the image and then destroyed, it should only have the one list item.

https://github.com/digitalocean/godo/blob/master/droplets.go#L436

**Comment by rickard-von-essen** [comment]
Fixed in #3169

**Comment by slackpad** [comment]
Thanks! Getting the snapshot for the particular droplet ID is a super clean way to do this.
