### ISSUE TITLE
Add an "inline" option for passing Vagrantfile template to Vagrant post-processor

### ISSUE THREAD

**Issue by tylert** [mitchellh/packer#3168]
This outlines a possible enhancement to the vagrant post-processor.

Just like the shell provisioner/post-processor, it would be really nice to have the option to pass an "inline" vagrantfile_template configuration option to the vagrant post-processor instead of an external file.

The use case for this would be to try to create a more self-contained packer template and try to minimize the number of external files needed to build a box.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
