### ISSUE TITLE
Ansible (remote) provisioner inventory file

### ISSUE THREAD

**Issue by Ludachrispeed** [mitchellh/packer#3178]
I'm super excited about the new Ansible (remote) provisioner. One thing that I found confusing, though, was how it deals with the Ansible inventory.

It looks like the provisioner generates an Ansible inventory file. I _think_ that means that any playbook that packer runs needs to have the line `hosts: all`. Is that true? If so, this is very limiting. It would be super cool if we could provide an inventory file, perhaps with an entry like this:

    [packer]
    default ansible_ssh_host=127.0.0.1 ansible_ssh_user='packer-ansible' ansible_ssh_port=2200 ansible_ssh_private_key_file='packer_host_private_key'

**Comment by rickard-von-essen** [comment]
I think a good solution would be to add something like ```groups``` which takes a list of group names to add the host to in the inventory file. And mention in the docs that the ansible inventory host name is **default**.

That solves the two scenarios:

- New playbooks. You just add ```hosts: default``` to them.
- You reuses playbooks that you use somewhere else. You just add the groups you already have in your playbooks to the templates ```groups```.

**Comment by bhcleek** [comment]
@Ludachrispeed the inventory file is generated with `default` as the host alias, so you don't have to put `hosts: all` playbook, you can also use `hosts: default` in the playbook.

Perhaps an option to name the host would be better? Something like 
```
{
    host_alias: "my-preferred-host-name"
}
```

Which would cause the inventory file to be written with `my-preferred-host-name` as the host alias. If not provided, `host_alias` would default to `default`.

**Comment by bhcleek** [comment]
@rickard-von-essen what would you think about combining your suggestion and my suggestion here? If you're in agreement, I'll work up an implementation.

**Comment by rickard-von-essen** [comment]
@bhcleek Sounds great! Add some docs how the inventory is created. Currently I had to read the code to know how to use it. ;-)

**Comment by vinhvu** [comment]
I use packer to provision one ec2 instance, so i can use ansible playbook to install httpd on this ec2?
How can i know the host of ec2 instance?
When i use "hosts: default", the packer will be use 127.0.0.1 to ssh and run playbook.
For more detail as the below:
�[1;32m==> amazon-ebs: Provisioning with Ansible...�[0m
�[0;32m amazon-ebs:�[0m
�[0;32m amazon-ebs: PLAY [default] *****************************************************************�[0m
�[0;32m amazon-ebs:�[0m
�[0;32m amazon-ebs: TASK [Gathering Facts] *********************************************************�[0m
�[0;32m amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: sorry, you must have a tty to run sudo\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}�[0m
�[0;32m amazon-ebs: to retry, use: --limit @/var/lib/jenkins/playbooks/apache-httpd/site.retry�[0m
�[0;32m amazon-ebs:�[0m
�[0;32m amazon-ebs: PLAY RECAP

Can you help me?

**Comment by rickard-von-essen** [comment]
@vinhvu don't spam. See my previous post on how to get help, or try stackoverflow.com
