### ISSUE TITLE
google-builder: populating metadata is broken

### ISSUE THREAD

**Issue by sl1pm4t** [mitchellh/packer#3181]
9cf99289c5729f49674a69a8978594c7a5e79a4b broke how Packer populates instance metadata when creating an Instance. After this change, all metadata entries end up with the last metadata value (the SSH key). 
I'll submit a PR shortly with a fix.

**Comment by cbednarski** [comment]
Thanks for the report! I'll keep an eye open for your PR.

**Comment by sl1pm4t** [comment]
I submitted a PR for this issue together with #3182
