### ISSUE TITLE
Make it explicit that -debug doesn't work with -machine-readable

### ISSUE THREAD

**Issue by zytek** [mitchellh/packer#3186]
Trying to debug packer build showed that `-debug` option is incompatible with `-machine-readable`, meaning that Packer doesn't pause after each step. It could be explicit either via documentation update or in command line parsing.

I could try to make proper PR if you decide how this should be handled. 

Steps to reproduce:
- just take one of your `packer build` command and supply both `-debug` and `-machine-readable`

Tested on packer 0.8.6 with EBS builder.

**Comment by cbednarski** [comment]
Thanks for the report!
