### ISSUE TITLE
convert boot_command to sendkey provisioner

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#3196]
@all @cbednarski @mitchellh @rickard-von-essen and other =)
I think about current boot_command and think, that this is provisioner that can send keys, also sometimes someone may want to send some keys after system is bootup.

Using vnc,spice,qmp we can send keys after vm installed.
What do you think? By default boot_command fills sendkey provisioner data...

**Comment by rickard-von-essen** [comment]
I'm not sure I follow, could you try to explain a use case?

**Comment by cbednarski** [comment]
Yeah that makes sense to me.

@rickard-von-essen Basically "I want to send a key-press event to the VM", but you can do this in a provisioner at any point, not just in during the `boot_command`.

**Comment by rickard-von-essen** [comment]
OK. I haven't seen a use case where this actually is a good solution, usually it is used instead of learning how to properly use a automated install (preseed, kickstart, etc), but there are probably some crapy appliances out there that requires this to install. But the question is if we don't have SSH (or WinRM) why is this different from using a really long ```boot_command```? And if we have SSH it should be possible to do the same provisioning with at least she'll provisioner.

Also this would only support _vmware, virtualbox, paralles,_ and _qemu_ builders. Which would be the first provisioner that is tied to some specific builders.

@vtolstov Sorry, I'm trying to be the devils advocate here, so we don't add stuff that don't add any value.

**Comment by vtolstov** [comment]
@rickard-von-essen very long boot_command can't be mixed with provisioners, also i can run via provisioner some gui command, that want to approve license via gui. So i need to enter some keys, in current case this is very big trouble.
Also i think that boot_command not needs to be independent from provisioners. In all cases we start vm via some builder and provision it via keys, shell, and so.
So i think this is is more right solution. Also i have may linux distros that does not have proper automated installation and i need to wait 10 - 15 minutes in boot_command (i'm already write pr that merged for this long lived waitings). In this waiting i can't run shell_local or something other provisioner to check  status from outside of vm.

**Comment by cbednarski** [comment]
> Also i have may linux distros that does not have proper automated installation and i need to wait 10 - 15 minutes in boot_command (i'm already write pr that merged for this long lived waitings). In this waiting i can't run shell_local or something other provisioner to check status from outside of vm.

Yeah I've run into this with e.g. Alpine linux which has no network by default, so the "preseed" has to be typed in over `boot_command`. The trouble with this is that any commands sent over VNC are blind -- we have no way to see whether they have completed or succeeded. You eventually have to use shell or something else to verify.

I think we can re-use a lot of code here so it is probably not a lot of maintenance burden.

> Also this would only support vmware, virtualbox, paralles, and qemu builders. Which would be the first provisioner that is tied to some specific builders.

@rickard-von-essen raises a good point. Do you have any thoughts about this? `boot_command` is not supported on Amazon, for instance, so the provisioner would not run here.

**Comment by mwhooker** [comment]
I think this needs more thought. I'm not sure it's a great UX to have a provisioner that only works for specific builders, but I also recognize this is a problem. I wonder if this would be better as a 3rd party plugin. That way, we don't have to guarantee that it works for everyone, but people with a need can install it.

This isn't something we're targeting for 1.0, so I'm going to close this.
