### ISSUE TITLE
Build error in builder/googlecompute/driver_gce.go

### ISSUE THREAD

**Issue by mafrosis** [mitchellh/packer#3199]
Since 942aaa7, I have been unable to build `packer` due to the following:

    1 errors occurred:
    --> darwin/amd64 error: exit status 2
    Stderr: # github.com/mitchellh/packer/builder/googlecompute
    builder/googlecompute/driver_gce.go:220: network.AutoCreateSubnetworks undefined (type *compute.Network has no field or method AutoCreateSubnetworks)
    builder/googlecompute/driver_gce.go:220: network.Subnetworks undefined (type *compute.Network has no field or method Subnetworks)
    builder/googlecompute/driver_gce.go:230: d.service.Subnetworks undefined (type *compute.Service has no field or method Subnetworks)
    builder/googlecompute/driver_gce.go:291: unknown compute.NetworkInterface field 'Subnetwork' in struct literal

I can build `packer` on the commit prior to 942aaa7. I've also run `make updatedeps`. What am I doing wrong?

**Comment by rickard-von-essen** [comment]
We just changed to using vendored devs (with godep) be sure to reread https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md#setting-up-go-to-work-on-packer since there are some new stuff there.

**Comment by mafrosis** [comment]
My apologies! I missed the `export GO15VENDOREXPERIMENT=1` option.
