### ISSUE TITLE
HTTPIP is computed incorrectly

### ISSUE THREAD

**Issue by lguminski** [mitchellh/packer#320]
After I have changed network adapter from NAT to bridged 

```json
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--nic1",
          "bridged"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--bridgeadapter1",
          "eth0"
        ]
      ]
```
I have noticed that this didn't affect HTTPIP variable which was still pointing to `10.0.2.2` instead of original IP of the host. As a result preseeding didn't work.

Same happened when I tried to define 2 adapters (bridged + NAT) 

```json
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--nic1",
          "bridged"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--bridgeadapter1",
          "eth0"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--nic2",
          "NAT"
        ]
      ]
```

and use the second one as primary during provisioning (note`netcfg/choose_interface=eth1`)

```json
      "boot_command": [
        "<esc><esc><enter><wait>",
        "/install/vmlinuz noapic preseed/url={{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>",
        "debian-installer=en_US auto locale=en_US kbd-chooser/method=us <wait>",
        "hostname={{ .Name }} <wait>",
        "netcfg/choose_interface=eth1 <wait>",
        "fb=false debconf/frontend=noninteractive <wait>",
        "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA keyboard-configuration/variant=USA console-setup/ask_detect=false <wait>",
        "initrd=/install/initrd.gz -- <enter><wait>"
       ]
```
HTTPIP variable was still pointing to `10.0.2.2` instead of `10.0.3.3`, which was the correct one.

How to solve the problem? Should I use some other variable?

**Comment by paolodina** [comment]
Having the same pre-seeding issue I've been able to solve it using [`vboxmanage_post`](https://packer.io/docs/builders/virtualbox-iso.html#vboxmanage_post) instead of simply `vboxmanage`. Probably this issue was opened before vboxmanage_post was added to packer, so can this issue be closed?

**Comment by paolodina** [comment]
However I see it still doesn't work. The resulting virtualbox vm is again configured to use NAT. I hope in some fix.

**Comment by ashivara77** [comment]
@mitchellh @jasonberanek : I am successful in building a VM with NAT ,  but while trying to create one having Bridged configuration using (as suggested above):  
     "bridged_networking" : true,
     "bridged_host_interface": "eth0"

I get the following error:
* unknown configuration key: "bridged_host_interface"
* unknown configuration key: "bridged_networking"

The boot Script is  :        
 "boot_command" : [
            "<esc><esc><enter><wait>",
            "/install/vmlinuz noapic ",
            "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
            "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
            "hostname={{user `hostname`}} ",
            "fb=false debconf/frontend=noninteractive ",
            "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
            "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
            "initrd=/install/initrd.gz -- <enter>"
        ]
Could you please advice on the changes to be done to get a VM with Bridged configuration ?
Thanks

**Comment by cbednarski** [comment]
@ashivara77 I think your issue is not related to the original issue (HTTPIP not being resolved correctly), and the thread is quite old. Can you open new issue, please?

**Comment by ashivara77** [comment]
Hi Chris,

Thank you for your response.
My doubt is:

1. I have attached the .Json script and the config file I am using to
create a VM (using Virtual Box). I am sucessfully able to create VM.
However, it is created using 'NAT' configuration(default). Could you please
suggest me what changes are to be done in the json or cfg file, if I need
to create the VM with 'Bridged' Configuration. I am not able to find much
resources in this regard and any suggestions will greatly help me.

Thank you very much for the help,

Best Regards,
Arun

**Comment by rickard-von-essen** [comment]
If there is still similar problems like this open a new issue or ask on [IRC: #packer-tool @freenode or the packer-tool Google Group](https://www.packer.io/community/).
