### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by mjperrone** [mitchellh/packer#3202]
I've been waiting a few months now for a [new release](https://github.com/mitchellh/packer/releases) to be issued, there's a fix merged in late November that I'd like our team to use, but I don't want to use a non-standard commit. What's the timeline for getting a new release out?

**Comment by cbednarski** [comment]
Thanks for using packer! A release candidate for 0.9 will be out this week. If there are no major issues 0.9 will be out by the 26th, possibly sooner.
