### ISSUE TITLE
vnc dial timeout for esx5 driver is too short, and not configurable

### ISSUE THREAD

**Issue by zadoryzsolt** [mitchellh/packer#3205]
Hi,

I'm trying to use the vmware builder with a remote machine, and most of the time I get "Timeout connecting to: port". I saw in the code that the timeout is constant 1*time.Second.

It would be nice to configure this value as well, just like ssh_timeout.

**Comment by rickard-von-essen** [comment]
Yes, it probably would. There are instructions in the README.md how to build packer from source. It would be super if you could try to increase the timeout and rebuild and verify that it solved you issue.

**Comment by zadoryzsolt** [comment]
I increased the value to 5 seconds and it works reliably now.

**Comment by JelleHissink** [comment]
I had the same problem in v0.12.2, increasing it to 5 seconds did the trick!
Thanks for providing a solution. Should I make a pull-request for this?

**Comment by rickard-von-essen** [comment]
@JelleHissink yes please do.

**Comment by JelleHissink** [comment]
@rickard-von-essen pull request is in, I have tested this with esxi 6.5 looking at the timestamp from @zadoryzsolt it should also work on an earlier version.

**Comment by mwhooker** [comment]
It looks like this timeout has been increased. We'd be happy to look at PRs to make it configurable, but right now that's not a priority for us.

**Comment by rickard-von-essen** [comment]
This was increased in #4480, which is unreleased but in master.
