### ISSUE TITLE
New Release soon?

### ISSUE THREAD

**Issue by jessechahal** [mitchellh/packer#3218]
Its been about 6month's since the last official release of packer. Are there plans to release a new version of packer anytime soon? From what I can see there is a lot nice stuff just itching to get out into the world. Looking at the previous releases on average it seems to be one larger release every 6months and then a bunch of smaller releases following that.

**Comment by cbednarski** [comment]
Thanks for opening an issue. As mentioned previously, https://github.com/mitchellh/packer/issues/3202 0.9 RC will be out this week. So the official 0.9 release will be out very soon!

**Comment by mjperrone** [comment]
When should we expect it to be updated in homebrew?

**Comment by rickard-von-essen** [comment]
@mjperrone open a issue at https://github.com/homebrew/homebrew asking for an update. There need to be done some work there since we now use Godep.
