### ISSUE TITLE
Unable to create preemptible google machines?

### ISSUE THREAD

**Issue by ldanielw1** [mitchellh/packer#3219]
I tried to include `"preemptible": false` in my json, but I get this error:
`* unknown configuration key: "preemptible"`

Is this a bug in packer, or am I doing something wrong?

**Comment by rickard-von-essen** [comment]
Sorry the docs reflects some configuration keys that isn't in the latest release. ```preemtible``` is not available in v0.8.6, but v0.9.0 will be released any day now and contain support for it.

You can view the correct docs for v0.8.6 at https://github.com/mitchellh/packer/blob/v0.8.6/website/source/docs/builders/googlecompute.html.markdown

**Comment by ldanielw1** [comment]
I'm afraid this issue still isn't fixed in 0.10.0. Is this going to be fixed any time soon?

**Comment by rickard-von-essen** [comment]
Could you include your details.

**Comment by ldanielw1** [comment]
What kind of details do you need? Packer v. 0.10.0.

When I try to run a google build with "preemptible: true" in the json, I get this error:
`unknown configuration key: "preemptible"`

**Comment by rickard-von-essen** [comment]
I'll like a gist of the output when running `PACKER_LOG=1 packer build ...`. This will tell me if your install is sane. Did you notice the note on https://www.packer.io/downloads.html ?

**Comment by ldanielw1** [comment]
aiya. I am so sorry, my path was funky and I was somehow running the wrong packer. Please ignore. 0.10.0 is working fine.

**Comment by cbednarski** [comment]
Thanks for following up @ldanielw1 ! :)
