### ISSUE TITLE
qemu builder's disk_compression and skip_compaction flags not supported. qemu-img convert does not work

### ISSUE THREAD

**Issue by astraverkhau** [mitchellh/packer#3220]
Image compaction doesn't seem to work (4G output qcaw2 vs 1.3G after manual qemu-img convert) + the following documented flags raise errors:

```
2 error(s) occurred:
* unknown configuration key: "disk_compression"
* unknown configuration key: "skip_compaction"
```

**Comment by rickard-von-essen** [comment]
Sorry the docs reflects some configuration keys that isn't in the latest release. ```disk_compression``` and ```skip_compaction``` is not available in v0.8.6, but v0.9.0 will be released any day now and contain support for it.

You can view the correct docs for v0.8.6 at https://github.com/mitchellh/packer/blob/v0.8.6/website/source/docs/builders/qemu.html.markdown

**Comment by astraverkhau** [comment]
Thanks!

**Comment by juaningan** [comment]
Hi, tested in packer 0.10.1 and raise errors:
```

2 error(s) occurred:

* unknown configuration key: "disk_compression"
* unknown configuration key: "skip_compaction"
```

```
➜  packer-qemu-base git:(master) ✗ packer version
Packer v0.10.1

```

**Comment by vtolstov** [comment]
2016-07-08 21:48 GMT+03:00 Juan José Presa <notifications@github.com>:

> Hi, tested in packer 0.10.1 and raise errors:
>
>
> 2 error(s) occurred:
>
> * unknown configuration key: "disk_compression"
> * unknown configuration key: "skip_compaction"
>
> ➜  packer-qemu-base git:(master) ✗ packer version
> Packer v0.10.1
>
>
Please, try master


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@yoctocloud.net

**Comment by juaningan** [comment]
in master:
Packer v0.10.2.dev (2e949bf43ddcacd82cc2eb3d17ec029e1313f45c+CHANGES)

working well
