### ISSUE TITLE
Docker test TestUploadDownload is failing [known issue]

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#3222]
Failing test in packer 0.9.0-rc2 acceptance tests. This will be filed as a known issue and not fixed for 0.9.

```
PACKER_ACC=1 go test -v ./builder/docker/... -run TestUploadDownload -timeout=30s
```

I think this is a rehash of an issue @markpeek looked into earlier. Originally I thought this was fixed in #2846 but appears to still be present. I did a git bisect and this test started failing on a commit that removed the linux OS requirement from the test, so obviously this code path does not (and probably never has) worked on OS X.

I think the fix is to reimplement this entire plugin using go-dockerclient as proposed in #2809

Related / same issue as: #3102 but there's already a repro case in the test suite.

Also this will require minimum docker server version of 1.8 / api version 1.20. Since we will bundle the docker client code in packer the client version requirement will be satisfied automatically.

**Comment by mwhooker** [comment]
I think this will be resolved by #4186. After that gets merged, please open a new issue if you continue to see this
