### ISSUE TITLE
Cannot establish SSH connection in bridged mode

### ISSUE THREAD

**Issue by lguminski** [mitchellh/packer#323]
After changing network adapter from nat to bridged

```json
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--nic1",
          "bridged"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--bridgeadapter1",
          "eth0"
        ]
      ]
```
packer is unable to establish SSH connection, because it attempts to connect  127.0.0.1:4382, instead of public IP assigned to box.

**Comment by catsby** [comment]
https://github.com/mitchellh/packer/pull/1078 was merged, so I'm closing this. 1078 will go out in the next release, which should be soon. Please let us know if you still run into this!

**Comment by chocolatewheelchair** [comment]
Is there a fix or workaround for this issue with vmware machines?
