### ISSUE TITLE
Google builder cannot bring up instances with scopes

### ISSUE THREAD

**Issue by conord33** [mitchellh/packer#3230]
There are no options to bring up an instance with specific scopes using the google builder. This can cause issues if certain provisioning steps require certain scopes to complete. There should be a way, similar to terraform, to add an array of scopes the instance will have in the builder options.

**Comment by kikitux** [comment]
Hello @conord33 could you please provide more information and an example of what you are missing?

**Comment by RobertAtomic** [comment]
I don't see a reply from the original requester, but I was about to open an identical issue myself so I'll answer the question...

In our case we rely on the ability to use the [Google Cloud Logging Service](https://cloud.google.com/logging/docs/).  This requires the scope "https://www.googleapis.com/auth/logging.write" but Packer instances only have "https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/compute", and "https://www.googleapis.com/auth/devstorage.full_control" enabled.  

So far I haven't needed any other scopes available, but I can easily think of scenarios where I would (interaction with BigQuery, or Data Store).

**Comment by ido** [comment]
See issue  #3587 - the google compute engine image builder should be replaced with one that builds the image outside of GCE and imports it as a QEMU, VirtualBox, or AWS AMI into GCS/GCE.

**Comment by rickard-von-essen** [comment]
@ido #3587 doesn't  really change anything for this issue.
