### ISSUE TITLE
Packer crash

### ISSUE THREAD

**Issue by bensojona** [mitchellh/packer#3234]
Got a [Packer crash](https://gist.github.com/bensojona/7aba99c6cd4d5c8ed11d#file-crash-log) on a [build](https://gist.github.com/bensojona/7aba99c6cd4d5c8ed11d#file-deploy-json). Looks to be in the AWS SDK.

Setting the [AWS keys](https://gist.github.com/bensojona/7aba99c6cd4d5c8ed11d#file-deploy-json-L5-L6) fixed it, but we may want to account for this in Packer if they're not set and throw an error.

**Comment by cbednarski** [comment]
Thanks, this is a dupe. Looking into it now. See #3123
