### ISSUE TITLE
Issues with 0.9.0 on Mac OS X El Capitan, VirtualBox 5.0.14, VMware Fusion 8.1.0, both VirtualBox and VMware

### ISSUE THREAD

**Issue by michael-crawford** [mitchellh/packer#3237]
This could be a false alarm - I've been away from dealing with Packer for 18 months, just trying to get my templates working again. 

I first updated packer to 0.8.6 and confirmed my ability to build a CentOS 6.7 x86_64 minimum template using Virtualbox and VMware Fusion builders. This worked with no changes to my prior template. 

I then went to add in the Parallels and QEMU builders, and noticed the `"iso_target_path"` option, which I added to all 4 of the builders. When I ran this, got an error, found on GitHub this appears to be a new option added in 0.9.0 which is on the releases website but was not yet visible on the packer.io downloads section.

I downloaded 0.9.0, removed all `/usr/local/bin/packer-*` files, then unzipped packer, resulting in just the single `/usr/local/bin/packer` file. I didn't clear out any other possible file locations.

When I ran the template again with `-only=virtualbox`, all seemed to work well until the end, when I got these error messages:

```
==> virtualbox: Gracefully halting virtual machine...
==> virtualbox: Error detaching ISO: VBoxManage error: VBoxManage: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
==> virtualbox: VBoxManage: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee nsISupports
==> virtualbox: VBoxManage: error: Context: "LockMachine(a->session, LockType_Shared)" at line 326 of file VBoxManageStorageController.cpp
==> virtualbox: Unregistering and deleting virtual machine...
==> virtualbox: Deleting output directory...
Build 'virtualbox' errored: Error detaching ISO: VBoxManage error: VBoxManage: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
VBoxManage: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Shared)" at line 326 of file VBoxManageStorageController.cpp
```

I then tried again with `-only=vmware`. This time, when the VMware GUI window opened, the host went into PXE boot but could not find a DHCP address. It eventually timed out.

To confirm this was not something caused by other editing changes to the template I was making to add parallels and qemu, I removed the iso_target_path option, removed 0.9.0, reinstalled 0.8.6, and both virtualbox and vmware builders worked perfectly again.

I know this new version just came out, so thought I'd report this behavior. I'll stick on 0.8.6 for now (will really miss iso_target_path, great addition!). 

One more note, not sure if it's relevant, but thought I'd mention it as it may be for the VMware problem - I have VMware DHCP setup to specify a PXE boot server, which is running on another VMware Fusion virtual machine I keep running specifically for this purpose, completely separate from Packer/Vagrant, etc. 

When I create a new VMware VM manually, I specify the MAC address which matches an entry in the `/Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf` file with it's IP, and when I start this host with an empty disk, it does PXE boot correctly to get the OS, kickstart, etc.

That doesn't seem to have a conflict with 0.8.6, but with 0.9.0, the behavior I'm seeing when Packer starts the VM is just like one of my manually created VMs, attempting to PXE boot, but in this case not finding an IP address and then hanging.

You may have changed how booting works in 0.9.0 - if so, it could be incompatible with VMware's build-in ability to implement this feature in OS X. I'm sure I'm an edge case on this technique, but thought I'd mention this in case it helps.

**Comment by markpeek** [comment]
I used this [repo](https://github.com/boxcutter/centos), added ```iso_target_path``` to the vmware-iso builder, and ran ```packer build -only=vmware-iso -var-file=centos67.json centos.json``` without any issue. If you are still having issues you might want to post a gist with some minimal example code.

**Comment by kikitux** [comment]
@michael-crawford Can you share some code to be able to repro this?

**Comment by cheeseplus** [comment]
The vmware issue is most likely related to the issues with 8.1.0 release not properly supporting port forwarding https://communities.vmware.com/thread/526498?tstart=0
