### ISSUE TITLE
Feature Request: Display Source AMI in logs

### ISSUE THREAD

**Issue by vikas027** [mitchellh/packer#3241]
It is not a great need, but would be good to have the name of the Source AMI in packer logs.

Something like this would be useful to refer logs later on.
```sh
$ packer build --only=aws packer.json
aws output will be in this color.

==> aws: Prevalidating AMI Name... 
==> aws: Inspecting the source AMI ami-11032472 ...
```

**Comment by cbednarski** [comment]
Thanks for the suggestion. This is available in the config already so we can probably print it out when we start the build.
