### ISSUE TITLE
Newest release (v0.9.0) not available on website

### ISSUE THREAD

**Issue by Rican7** [mitchellh/packer#3243]
I noticed that you've [bumped the version number][v0.9.0-version-bump] and [tagged a new v0.9.0 release][v0.9.0-tag], yet the website still has the old/previous version listed both in text and in the actual download links:

![screen shot 2016-02-22 at 11 59 13 am](https://cloud.githubusercontent.com/assets/742384/13225645/b27b4af2-d95b-11e5-8017-d178443d0636.png)

![screen shot 2016-02-22 at 11 59 53 am](https://cloud.githubusercontent.com/assets/742384/13225667/cbade0e8-d95b-11e5-84ce-64bd0d379438.png)

I noticed that the [`/website/config.rb` file still has version `v0.8.6` listed in it's configuration][website-config-oldversion], so maybe that's to blame?

[v0.9.0-version-bump]: https://github.com/mitchellh/packer/commit/a643faae672ec8b8424352476d2b91b7a7f7b06e
[v0.9.0-tag]: https://github.com/mitchellh/packer/releases/tag/v0.9.0
[website-config-oldversion]: https://github.com/mitchellh/packer/blob/v0.9.0/website/config.rb#L5

**Comment by rickard-von-essen** [comment]
In the meantime before this is fixed the release is available by replacing the version in the download URL.

**Comment by pearkes** [comment]
0.9.0 is now available on the website – sorry about that! https://github.com/mitchellh/packer/commit/11c1ac45f87c06353433e84d398e7325ad706b3c

Thanks both!

**Comment by Rican7** [comment]
Thanks!
That was quick!

**Comment by cbednarski** [comment]
Sorry about the mixup folks! For future reference you can always find the current and past releases at https://releases.hashicorp.com/packer/

**Comment by smolinari** [comment]
Why is the 0.8.6 120+ MB and 0.9.0 only 8MB?

Scott

**Comment by rickard-von-essen** [comment]
@smolinari Because Packer is now released as one binary and not as a bunch binaries for each plugin, see https://github.com/mitchellh/packer/blob/master/CHANGELOG.md#090-february-19-2016

**Comment by smolinari** [comment]
eww.....thanks! I have to go delete the plugins.....

It might be a good idea to make a big fat red note on the download page. Not many people will know to delete the plugins. :smile: 

(it might also be the problem in the other issue too!)

Scott
