### ISSUE TITLE
Clarification of ansible-local provision `playbook_paths`

### ISSUE THREAD

**Issue by ChrisAubuchon** [mitchellh/packer#3245]
The documentation states:

```
An array of paths to playbook files on your local system. These will be uploaded to the remote machine under staging_directory/playbooks. By default, this is empty.
```

When I supply a path to a playbook, it fails with `must point to a directory`.

Is `playbook_paths` supposed to be a list of directories or a list of playbook files?

**Comment by tamsky** [comment]
Based on the code at:
https://github.com/mitchellh/packer/blob/master/provisioner/ansible-local/provisioner.go#L225-L226
I'm guessing the documentation needs correction.
