### ISSUE TITLE
Using PACKER_LOG=1 packer build -debug  and needing to hit enter multiple times

### ISSUE THREAD

**Issue by smolinari** [mitchellh/packer#3250]
I just updated (properly) to 0.9.0 and now when running debug, I have to hit the Enter key multiple times, before Packer continues. I thought at first Packer just died, because nothing happened after the first press of the Enter key. But, thankfully I got frustrated and hit the Enter key a number of times, then figured out Packer then starts working again. Or does it? It says this too. 

` 2016/02/22 21:44:31 ui: scan err: unexpected newline`

Scott

**Comment by cbednarski** [comment]
Thanks for the report. I've noticed this too.

**Comment by paultyng** [comment]
This is happening to me as well, sometimes when I rerun it, it will get farther without extra enter's.  Debug is pretty much unusable right now though.

**Comment by jlspies1** [comment]
+1 - I just had to downgrade from 0.9.0 to 0.8.6_2 on my Mac and I found that the problem went away, so this was introduced in 0.9.0.

**Comment by Rican7** [comment]
Yea, I've noticed this myself. Using `-debug` mode causes the step pausing to require multiple "enter" key presses.

Strange.

**Comment by jgoldschrafe** [comment]
I'm also seeing this error, regardless of whether I set `PACKER_LOG`. If I hit Ctrl+D (EOF) instead of Enter at any point in the process, Packer complains about stdin being closed but otherwise progresses through the run.

**Comment by Rican7** [comment]
This is becoming quite problematic for debugging builds. Is there any further information that can be provided?

**Comment by Rican7** [comment]
It's great to see this fixed! The analysis and fix were ingenious. Since this is a core bug, will this be part of a patch release, a la `v0.10.1`?

**Comment by smolinari** [comment]
Thank for the fix @theang!

:+1: 

Scott

**Comment by jhg03a** [comment]
A hotfix release would be very useful.  As a new user, the project is unusable until I can properly debug why things might be going wrong.

**Comment by Rican7** [comment]
Boom. Release `v0.10.1` was cut. Thanks @cbednarski!
