### ISSUE TITLE
DigitalOcean: Reference base image by previous snapshot name

### ISSUE THREAD

**Issue by kaelumania** [mitchellh/packer#3252]
I have an existing snapshot created via
`"snapshot_name": "my_base_0.0.1"`

and then reference it in a new resource via
`"image": "my_base_0.0.1"`

but I am getting the error:
https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.

It seems that the logic in order to read images by name (fetching private images and comparing slug, name or id) has been removed recently. At the moment the DigitalOcean API is used directly and it does not support finding images by name. I think it is not a good packer API to allow snapshots with a name and then be unable to reference this name in a following build.

**Comment by cbednarski** [comment]
Thanks for the report. Can you try `region:image`?

**Comment by kaelumania** [comment]
@cbednarski Thanks for the response. Unfortunately no, using `"image": "fra1:my_base_image"` results again in `422 You specified an invalid image for Droplet creation.` when trying to reference my private image. But it's not surprising, because packer uses the do api client directly and searches only for the slug: https://github.com/mitchellh/packer/blob/master/builder/digitalocean/step_create_droplet.go#L28

Version 0.8.0 (June 23, 2015) introduced:
- builder/digitalocean: Private images can be used as a source [GH-1792]

Here was a previous issue https://github.com/mitchellh/packer/issues/1792 that solved it by grabbing all (private) images from DO and then comparing them by name. But that behaviour was removed introducing the DO v2 API (see commit https://github.com/mitchellh/packer/commit/6c6f3c24a561dd64734562e5ae794bad9b1788f6#diff-773223d4ba1a61e81daea8a8dfcdb692L294)

Image names don't have to be unique, maybe therefore they removed the support. But I would rather prefer to return the newest image with a given name.

**Comment by cbednarski** [comment]
Got it. The change that broke this is 6d314707570489e5216d6d69931816eb7f367c4f

The reason for the change is that if you have more than 200 images the image won't necessarily come back from the API, we don't page, and doing so would be really slow. Unfortunately the integration tests didn't catch this case.

So maybe we should do the API calls progressively. I.e. call for snapshot, if it's not found go through the images by name, if we go through 200 and don't find it request the next 200, etc. This is, of course, assuming there is not an appropriate API call on DO's side to do the lookup by name.

**Comment by djmaze** [comment]
Any updates on this?

**Comment by mjtieman** [comment]
Any movement on this issue?

**Comment by kaelumania** [comment]
@cbednarski do you have any plans to fix this soon?

**Comment by rickard-von-essen** [comment]
@kaelumania PR's are welcome.

**Comment by mwhooker** [comment]
This isn't something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
