### ISSUE TITLE
Ansible-local is not looking for the proper role path.

### ISSUE THREAD

**Issue by dsmithfv** [mitchellh/packer#3253]
Packer version: 0.9.0
Ansible version: 1.9.4

Error:     amazon-ebs: ERROR! the role 'common' was not found in /tmp/packer-provisioner-ansible-local/includes/playbooks/roles:/tmp/packer-provisioner-ansible-local/includes/playbooks:/etc/ansible/roles

I am able to push my local role_paths to the remote just fine but, the remote doesn't seem to have a proper roles_path set to find the roles.  It uploads them to /tmp/packer-provisioner-ansible-local/roles.  I would expect ansible-local being used via Packer to look for roles in the same place it is uploading them by default.

I have tried setting roles_path to the directory above (using extra_vars) and it does not seem to honor it.

      "type": "ansible-local",
      "role_paths": [
            "roles/common",
            "roles/webtier",
            "roles/apptier",
            "roles/sumologic",
            "roles/bennojoy.ntp"
        ],
      "playbook_dir": "/Users/dsmith/Documents/gitrepos/api-ansible",
      "playbook_file": "app-servers.yaml",
      "inventory_groups": "autocolor",
      "extra_arguments": [
        "--extra-vars 'roles_path=/tmp/packer-provisioner-ansible-local/roles is_packer=true hosts_tag=autocolor team=api environment=integration application=v2node node_environment=integrationb git_tag=integration'",
        "--vault-password-file ~/.vault_pass.txt"

**Comment by rickard-von-essen** [comment]
Could you rerun with ```PACKER_LOG=1 packer build ...``` and gist the output and your template.

**Comment by cbednarski** [comment]
Thanks for opening an issue. I'm not sure if this is the problem but you have indicated `roles_path` instead of `role_paths` (move the `s`).

```
  "--extra-vars 'roles_path=/tmp/packer-provisioner-ansible-local/roles
```

Also, surprisingly, this code path has not changed since the last release.

**Comment by dsmithfv** [comment]
Here is my original Packer json template which worked at some point prior.  I removed the roles_path variable since it shouldn't be needed. That var normally lives in ansible.cfg and is different from role_paths which I use in my playbook.

api-node-packer-SECRET.json
https://gist.github.com/wfmdevops/307f0aa1713d9facdcda

Packer output with PACKER_LOG=1 added.

packer.debug.log
https://gist.github.com/wfmdevops/72269fd79855f555d36a

Thanks for the quick response!

**Comment by cbednarski** [comment]
> Here is my original Packer json template which worked at some point prior.

Do you know which version of packer this previously worked with? Also, did the version of Ansible change since then?

**Comment by dsmithfv** [comment]
I'm not 100% sure as another Engineer originally wrote this.  I believe his Ansible version was around 1.8.x and the Packer may have been 0.8.6 although I would have thought he would have upgraded to 0.9.0 before leaving.

**Comment by dsmithfv** [comment]
I decided to try and downgrade to 0.8.6 and I got the same error.  Then it occured to me that:
            "sudo apt-add-repository ppa:ansible/ansible",
            "sudo /usr/bin/apt-get -y update",
            "sudo /usr/bin/apt-get -y install ansible"

installs Ansible version 2.0 on the remote server and maybe it handles the roles directory in a different way.

I created a symlink roles -> includes/playbooks/roles and got past this error.  Not sure if others have tried Packer/ansible-local 2.0 but, this seems like a bug.  I'd test by installing 1.9 on the remote if I knew how.

**Comment by rickard-von-essen** [comment]
@dsmithfv I think there is some problem with your playbook / roles configuration. I think the best way to solve this is to step back to the basics and create a smaller setup that works and expand from there. Also running the null builder will allow you to much quicker iterate over your template.

For me the following works:
issue-3253.json
```json
{
   "variables": {
    "ip": ""
  },
 "builders": [
    {
      "type": "null",
      "ssh_host": "{{ user `ip`}}",
      "ssh_username": "vagrant",
      "ssh_private_key_file": "./vagrant_private_key"
    }
   ],

  "provisioners": [
    {
        "type": "shell",
        "inline": [
            "sudo /usr/bin/apt-get -y update",
            "sudo /usr/bin/apt-get -y install software-properties-common",
            "sudo apt-add-repository ppa:ansible/ansible",
            "sudo /usr/bin/apt-get -y update",
            "sudo /usr/bin/apt-get -y install ansible"
        ]
    },
    {
      "type": "ansible-local",
      "playbook_file": "playbook.yml",
      "inventory_groups": [
        "autocolor",
        "default"
      ],
      "role_paths": [
            "roles/common"
      ]
     }
  ]
}
```
playbook.yml
```yml
---
- name: Default playbook
  hosts: default
  roles:
    - common
```
rolse/common/tasks/main.yml
```yml
---
- name: Common Role
  shell: echo "common"
```

And then:
```
vagrant init bento/ubuntu-14.04
cp `vagrant ssh-config | grep private | cut -d\  -f4` vagrant_private_key
packer build -var ip=`vagrant ssh-config | grep HostName | cut -d\  -f4` issue-3253.json
vagrant ssh -c "ansible --version"
```

**Comment by dsmithfv** [comment]
I believe it is in fact my role/playbook configuration.  I think this stopped working because those are incompatible somehow with Ansible 2.0.  I created a simple playbook and common role as suggested and it worked.  Now to slowly add things back and figure out how to migrate to 2.0 or if there is a way to apt-get Ansible 1.9.x for now.

**Comment by rickard-von-essen** [comment]
Closing, please reopen if the problem still exists.

**Comment by e-moshaya** [comment]
why was this issue closed when it hasn't been resolved?

**Comment by rickard-von-essen** [comment]
@e-moshaya this is a old issue. If you have a similar problem I suggest that you open a new issue and supply all the requested information.
