### ISSUE TITLE
AMI discard flag

### ISSUE THREAD

**Issue by bensojona** [mitchellh/packer#3254]
I don't believe this exists, but it would be nice if there was an AMI discard option like there [is with the Docker builder](https://www.packer.io/docs/builders/docker.html#discard) so it doesn't bake an AMI when you're just using the builder for the [artifice post processor](https://www.packer.io/docs/post-processors/artifice.html).

**Comment by paultyng** [comment]
This would be very useful in overcoming Atlas resource limitations for CPU or memory intensive builds.

**Comment by smitelli** [comment]
+1

I'd actually vote for taking it a step further -- adding a flag that can skip the "stop instance, wait for instance to stop, take snapshot, wait for AMI to become ready" and skip right to terminating the instance. In such a workflow, the `ami_name` config key might no longer be required either.

**Comment by mwhooker** [comment]
This should be a really easy fix if anyone wants to submit a PR.

However, this is not something we're targeting for 1.0, so I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
