### ISSUE TITLE
v0.9 preseed issue

### ISSUE THREAD

**Issue by punkrokk** [mitchellh/packer#3257]
I upgraded to v0.9 today with brew and the preseed on vmware fusion is not working. Nothing else has changed to my knowledge. Getting a can't download preseed from http://x.x.x.x:xxxx/preseed.cfg error. 

Any suggestions?

**Comment by cbednarski** [comment]
Thanks for opening an issue. Preseed is downloaded from packer's built-in HTTP server so packer will need to be able to accept inbound network connections. If you're using a firewall you'll need to add an exception for packer. My guess is the old version of packer is already whitelisted.

**Comment by punkrokk** [comment]
Hey - in this case it's a Mac with the firewall turned off...

**Comment by cbednarski** [comment]
`PACKER_LOG=1 packer build ...` will give you debug logging, which might help diagnose.

**Comment by punkrokk** [comment]
fixed user copy error. thanks for the help
