### ISSUE TITLE
unknown configuration key: "ssh_key_path"

### ISSUE THREAD

**Issue by gcshute** [mitchellh/packer#3261]
`% /usr/local/bin/packer-0.9.0 build -var 'linux_ver=7.1.29' packer.json`

```
virtualbox-ovf output will be in this color.

1 error(s) occurred:
* unknown configuration key: "ssh_key_path"
```

When I use Packer v0.7.5 this works fine:
Build 'virtualbox-ovf' finished.

```
  "builders": [
    {
      "type": "virtualbox-ovf",
      "source_path": "vagrant/box.ovf",
      "headless": true,
      "ssh_username": "vagrant",
      "ssh_key_path": "vagrant-files/vagrant",
```

**Comment by cbednarski** [comment]
Thanks for checking out the latest release! The way this is configured has changed. You will want to use [`ssh_private_key_file`](https://www.packer.io/docs/templates/communicator.html#ssh_private_key_file) instead.

To provide background, 0.8 introduced the idea of "communicators" which allows us to (for example) keep SSH configuration and code the same between different builders (VirtualBox, VMWare, etc.) so now all builders have the same options for SSH.

**Comment by cbednarski** [comment]
I'm going to close this but if your issue persists please feel free to reopen. Thanks!
