### ISSUE TITLE
qemu format: converting harddrive, again?

### ISSUE THREAD

**Issue by abbbi** [mitchellh/packer#3270]
building my windows templates with packer 0.8.6 for qemu/kvm resulted in a usable disk image after:

==> windows-2012-R2-standard: Gracefully halting virtual machine...

now i tried to build my images with 0.9.0 and it does one step more:

==> windows-2012-R2-standard: Converting hard drive...

from the processlist i can see:

/usr/bin/qemu-img convert -q -f qcow2 -O qcow2 ...

is this step really necessary? I can see that the created image file in the output folder already has qcow format.

**Comment by rickard-von-essen** [comment]
This is most likely [compaction](https://www.packer.io/docs/builders/qemu.html#skip_compaction).

**Comment by abbbi** [comment]
i see, ill rerun with skip_compaction,thanks!

**Comment by rickard-von-essen** [comment]
Closing this. please reopen if the problem persists.
