### ISSUE TITLE
Fails to provision with ansible remote if path is too long

### ISSUE THREAD

**Issue by LinusU** [mitchellh/packer#3271]
(packer `0.9.0` on OS X 10.11.3)

Ansible, under packer, fails with the following message when trying to provision the remote server.

```text
SSH encountered an unknown error. The output was:
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/linus/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
ControlPath too long
```

Key here is "ControlPath too long", it means that the path to the control file is too long. Ansible usually creates this file under `$HOME/.ansible/cp/ansible-ssh-%h-%p-%r` but something goes wrong, and instead the following path is used: (`/private/tmp/djas.../` is the current directory)

```text
/private/tmp/djaslk/djkslafjkdshfkjsdhfjksdhfkjsdhjfieorjfioejoifwjefojweoifjewiojfosidjtoidfjtoidkjor/$HOME/.ansible/cp/ansible-ssh-%h-%p-%r
```

It indeed also creates a file named `$HOME` in the current directory.

I'm not sure if this is a problem with Ansible or Packer, but I don't have this problem when I run ansible myself so it seems like something in the integration is breaking it...

**Comment by LinusU** [comment]
This is a very simple `template.json` that exhibits this problem:

```json
{
  "builders": [{
    "type": "amazon-ebs",
    "region": "eu-west-1",
    "source_ami": "ami-f95ef58a",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "Delete me please {{timestamp}}"
  }],
  "provisioners": [{
    "type": "ansible",
    "playbook_file": "playbook.yml",
    "extra_arguments": "-vvvv"
  }]
}
```

`"extra_arguments": "-vvvv"` is used to get more verbose output from Ansible.

I'm using the following `playbook.yml` for Ansible, just to test.

```yaml
- hosts: default
  tasks:
    - file: path=test state=touch
```

**Comment by LinusU** [comment]
A temporary workaround is to add the following option to the ansible provisioner:

```json
    "ansible_env_vars": [
      "ANSIBLE_HOST_KEY_CHECKING=False",
      "ANSIBLE_SSH_CONTROL_PATH=/tmp/ansible-ssh-%%h-%%p-%%r"
    ]
```

**Comment by cbednarski** [comment]
Thanks for the detailed report, repro, and workaround! I'm sorry you've run into this bug. Nothing immediately jumps out at me so I'll need to do some investigation to root cause this.

**Comment by LinusU** [comment]
Wow, thanks for the quick fix! I'm currently away but will try the fix on Wednesday:)

**Comment by hunterwyatt** [comment]
FYI, the freebie "Long Path Tool" program has always worked for me. It allows you to delete, rename, or move files and folders.
