### ISSUE TITLE
Ansible Remote ansible_ssh_user is packer-ansible

### ISSUE THREAD

**Issue by thatarchguy** [mitchellh/packer#3273]
When using packer with ansible remote as the provisioner, the builtin ansible variable `ansible_ssh_user` (`ansible_user` for Ansible 2.0) is set to "packer-ansible". 

This means that playbooks that use {{ ansible_ssh_user }} in their playbooks will fail when the "packer-ansible" user is not found and they are expecting something like "ubuntu" in its place. 

```
    amazon-ebs: TASK [deploy : Create virtualenv directory] *******************************
==> amazon-ebs: starting sftp subsystem
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: failed to look up user packer-ansible", "owner": "root", "path": "/opt/app", "size": 4096, "state": "directory", "uid": 0}
```
packer.json provision snippet:
```
  "provisioners" : [
    {
      "type": "ansible",
      "playbook_file": "ansible/site.yml",
      "extra_arguments": [
        "--extra-vars",
        "\"provision_type=pilot revision={{user `revision`}}\""
      ]
    }
  ]
```

Steps to reproduce:  
Create a quick playbook and provision with packer. I used the amazon-ebs in my example. 
```
- name: Create virtualenv directory
  file: path=/opt/app/env state=directory owner={{ansible_user}} group={{ansible_user}} mode=0775 recurse=yes
  sudo: yes
```

I believe this is due to how packer does the ansible remote provision with an ssh proxy.
```
    amazon-ebs: SSH proxy: accepted connection
==> amazon-ebs: authentication attempt from 127.0.0.1:48350 to 127.0.0.1:45959 as packer-ansible using none
==> amazon-ebs: authentication attempt from 127.0.0.1:48350 to 127.0.0.1:45959 as packer-ansible using publickey
```

Packer version: `0.9.0`
Host OS: `Linux Arch-Linux 4.4.1-2-ARCH`

**Comment by thatarchguy** [comment]
Work around:   
Set this variable and replace all instances of `{{ ansible_user }}` with `{{ remote_user }}`
```
remote_user: "ubuntu"
```
You can specify this variable in the packer.json if you want as well.
For when you bring up a dev environment in Vagrant add this to your Vagrantfile:
```
ansible.extra_vars = {remote_user: "vagrant"}
```

**Comment by rickard-von-essen** [comment]
@thatarchguy In the fix I build the _ansible_user_ will be set to you (host) user (`$USER`). That is probably what you should expect when using this var in Ansible (`{{ ansible_user }}`).
