### ISSUE TITLE
Unable to build Images on Atlas

### ISSUE THREAD

**Issue by activatedgeek** [mitchellh/packer#3278]
I am trying to build a simple Ubuntu Vagrant Box (only for starters, I am building another box whose base I am setting up). But the build fails as soon as it starts. Note that I am building on [`Atlas`](https://atlas.hashicorp.com/builds)

- Packer Version: 0.9.0
- Host platform: Pushed from OS X 10.11
- Complete Debug log output from [`Atlas Build UI`](https://atlas.hashicorp.com/builds)
```
Setup failed: open /tmp/build893489859/slug/.packer-template: no such file or directory
```
- The simplest example template and scripts needed to reproduce the bug.
The script that I am using is present at [`ubuntu.json`](https://github.com/activatedgeek/vagrant-mesos/blob/master/ubuntu.json).

Also note that if I see the files available during build, it lists `.packer-template` as one of them along with other files in the repository.

Also, `packer validate ubuntu.json` ran successfully.

**Comment by kikitux** [comment]
Hello @activatedgeek 

I have to say this is not a bug and its expected.

Your template is over the size of the build system in the free tier:

ie:
https://github.com/activatedgeek/vagrant-mesos/blob/master/ubuntu.json#L20

The build environment is defined here:
https://atlas.hashicorp.com/help/packer/builds/build-environment

Those sizes are for the build environment.

As this is not a bug in packer, could you please email us at support at hashicorp.com if you would like to follow this up?

Thanks
Alvaro

**Comment by activatedgeek** [comment]
@kikitux Hi, I have mailed my issue. I have updated my template, but still the exact same error. Not sure where I could be going wrong. I have removed any manual VM hardware configurations that I was doing earlier. It is strange. Similar templates were successfully built earlier. I have made no changes to templates except that the packer version now is 0.9.0.

**Comment by kikitux** [comment]
Hello,

The error `Setup failed: open /tmp/build893489859/slug/.packer-template: no such file or directory` has been taken care on Atlas.

The build should be back to normal.

Thanks
Alvaro.
