### ISSUE TITLE
too strict conditions for build name in v0.9.0

### ISSUE THREAD

**Issue by doka** [mitchellh/packer#3279]
Packer 0.9.0 introduced some rules for build name syntax in https://github.com/mitchellh/packer/blob/master/command/push.go, line 21.

With these new rules, build names like `debian-8.3` are not any more valid when pushing to atlas build service, and `packer push debian-8.3.json` fails with `Your build name can only contain these characters: [a-zA-Z0-9-_]+`

In earlier versions this was working, see https://atlas.hashicorp.com/doka/boxes/debian-8.2

Expected behavior is that at least the dot (.) is allowed in build names.

**Comment by cbednarski** [comment]
Thanks for opening an issue. I dug back in history a bit to see where this change came from and this change was made according to the Atlas spec, which at the indicated that `.` was not allowed. I have reached out to the Atlas team to see if this is still the case.

**Comment by ava-miket** [comment]
This is also causing the docker builder to fail in Packer:

Stderr: Error response from daemon: ~/.packer.d/tmp/packer-docker369748490 includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by mwhooker** [comment]
Just got confirmation from the atlas team that dots _are_ allowed. Since the associated PR needs a rebase, I'll close that out and make a new commit
