### ISSUE TITLE
Looking for vCloud Builder 

### ISSUE THREAD

**Issue by shashanksinha89** [mitchellh/packer#3280]
I am looking for specific use case where I can build images/artifacts vcloud platform directly instead of relying on type-2 hypervisor i.e VirtualBox , vmware desktop products.

Thanks !!!!

**Comment by dave2** [comment]
vmware-iso can talk directly to a ESXi server over ssh, and the vsphere post-processor can punt stuff into anywhere ovftool can talk to.

However, there isn't much support for using the "front door" API for vsphere/vcloud etc on the builder side. Some of the work I'm doing will probably require that, but I have no ETA on any support.

**Comment by rickard-von-essen** [comment]
If you don't want to open up ssh to your ESXi's I can recommend that you run a nested ESXi server in a VM specifically with the purpose of building images.

Closing this as "not implemented yet".
