### ISSUE TITLE
vsphere post-processor unable to connect

### ISSUE THREAD

**Issue by jcsmith** [mitchellh/packer#3283]
After upgrading from packer 0.8.6 to 0.9.0 jobs using the vsphere post-processor fail running on a linux host fails with the following error:

```
* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: output_RHEL7-2016-02-26-jcstest/RHEL7-2016-02-26-jcstest.vmx
Opening OVF target: "vi://USERNAME:*******@vsphere-srv3.wvnet.edu/WVNET/host/Nahalem"
Writing OVF package: "vi://USERNAME:******@vsphere-srv3.wvnet.edu/WVNET/host/Nahalem"/"RHEL7-2016-02-26-jcstest"/"RHEL7-2016-02-26-jcstest".ovf
Transfer Failed                       
Error: System error: (std::exception)
Deleting directory tree below: "vi:
Completed with errors
```

**Comment by rickard-von-essen** [comment]
Can you rerun with Packer log ```PACKER_LOG=1 packer build ...``` and gist the log and relevant parts of your template.

**Comment by grothja** [comment]
Were having the same problem, been meaning to create an issue as well... 

[Log](https://gist.github.com/grothja/e308197082431f9ec44c) (I included the first part, but pulled out the builder and most of the provisioning)
[Post-processor example from template](https://gist.github.com/grothja/8a89c370865b8f399a20)

Maybe I'm wrong, but it looks related to 096b42a.  Without specifying a resource pool, it looks like it's adding double-quotes around the `/` to me...

**Comment by jcsmith** [comment]
Here is a link to a gist containing the log (with password redacted) and the relevant section of the template, again with password redacted):
https://gist.github.com/jcsmith/49d7e53c487ac007f644

**Comment by jalmansor** [comment]
@rickard-von-essen, this seems to be the same issue as #3204

**Comment by rickard-von-essen** [comment]
@jcsmith Could you provide a log whit only one build, and also include the first 100 lines or so which contains info about your setup and startup of packer.

@jalmansor maybe, but I'm not convinced yet.

**Comment by jcsmith** [comment]
@jalmansor, thanks for pointing that out, it definitely seems related.

**Comment by jcsmith** [comment]
@rickard-von-essen coming right up.

**Comment by jcsmith** [comment]
@rickard-von-essen Here you go:
https://gist.github.com/jcsmith/c5a1b26601e9c904e811

Please let me know if you need anything else.

**Comment by iamthemuffinman** [comment]
Hi @jcsmith. This seems to be an issue with passing quotes to ovftool as @grothja has suggested. I recompiled the 0.9.0 release on my machine without the quotes around the parameters and it works just fine. We need to look into why passing quotes to ovftool via exec.Command is causing it to fail.

**Comment by rickard-von-essen** [comment]
@jcsmith Do you have a GPG pub key?

**Comment by jcsmith** [comment]
@rickard-von-essen - I do not, I've never had a use for one.  I can create one though.  I'll ping you again on here once it has been created.

**Comment by iamthemuffinman** [comment]
As a workaround, I modified the vsphere post-processor to just execute ovftool with bash.

**Comment by jcsmith** [comment]
@rickard-von-essen here is a link to my newly created gpg public key:
https://gist.github.com/jcsmith/374dcd737b1c1f5245b0

**Comment by majinjing3** [comment]
+1 Same issue for me.
It seems os/exec passed redundant quotes to ovftool.

**Comment by majinjing3** [comment]
@jcsmith @rickard-von-essen  @grothja  @jalmansor  @iamthemuffinman 
I think that, when use os/exec, we don't need put quotes both ends of parameters, like this ```"\"vi://a:b@c:/d\""```.
os package will auto add quotes both ends of every argument.
so, we just do like this 
``` golang
args := []string{
        ...
        fmt.Sprintf("%s", ovftool_uri)
}
```
While some parameter like this ```--datastore=\"%s\"```, the quotes are necessary.

**Comment by rickard-von-essen** [comment]
Closing as dup of #3204
