### ISSUE TITLE
AWS launch device mappings with delete on termination=false are not cleaned up

### ISSUE THREAD

**Issue by jbachus** [mitchellh/packer#3287]
On version 0.9.0 of packer, if delete_on_termination is set to false in the launch_block_device_mappings, the temporary EBS volume will not be cleaned up.  I don't believe the logic at https://github.com/mitchellh/packer/blob/master/builder/amazon/ebs/step_cleanup_volumes.go#L46 and https://github.com/mitchellh/packer/blob/master/builder/amazon/ebs/step_cleanup_volumes.go#L100 is needed.  I'm not sure when you would ever want to save a temporary packer-created EBS volume, even if the volume in the AMI needs to be preserved on termination.

**Comment by cbednarski** [comment]
Thanks for opening an issue. This behavior is called out in the [documentation](https://www.packer.io/docs/builders/amazon-ebs.html):

> Note: Packer uses pre-built AMIs as the source for building images. These source AMIs may include volumes that are not flagged to be destroyed on termination of the instance building the new image. Packer will attempt to clean up all residual volumes that are not designated by the user to remain after termination. If you need to preserve those source volumes, you can overwrite the termination setting by specifying delete_on_termination=false in the launch_device_mappings block for the device.

I don't think there's a default behavior here that is going to satisfy everyone so unless there is a problem that cannot be solved with configuration, I think it might be better to expand the documentation to cover several common use-cases as opposed to changing the default behavior again.
