### ISSUE TITLE
Broken link in tutorial

### ISSUE THREAD

**Issue by tvlooy** [mitchellh/packer#3288]
Go to https://atlas.hashicorp.com/tutorial/packer-vagrant/1
Click "do you have packer" -> no
The link in "Click here to download the latest version of Packer." is broken.

I didn't know where to report this but didn't want to hold it back.

**Comment by cbednarski** [comment]
Thanks for the report! It appears there is no download link configured for linux.

**Comment by cbednarski** [comment]
I have reported this to the Atlas team who maintain the tutorial. I'm going to close this for now since there is no action item for the packer project. Thanks again!
