### ISSUE TITLE
Google Compute: Add "assign_public_ip" option

### ISSUE THREAD

**Issue by austin127001** [mitchellh/packer#3296]
There are a number of use cases where it would be useful to have packer spawn GCE instance which don't have public IP address (e.g. instance.networkInterfaces[].accessConfigs[] left undefined).

Such use cases are:
- Instance set to use a proxy server
- Instance configuration is performed solely with VPN connected resources
- Organizational compliance

This feature is available in other builders (i.e. amazon-ebs) but not with this one.

Some thoughts:
accessConfig is always defined:
https://github.com/mitchellh/packer/blob/master/builder/googlecompute/driver_gce.go#L238

Instead it might work to have NetworkInterface be more dyanmic:
https://github.com/mitchellh/packer/blob/master/builder/googlecompute/driver_gce.go#L285

Thanks to everyone for making this awesome project by the way!

**Comment by cbednarski** [comment]
Thanks for opening an issue. This makes sense to me! I think to retain backwards-compatibility we will want to name this option to `skip_public_ip` or something similar that can be `false` by default.
