### ISSUE TITLE
SignatureDoesNotMatch amazon-import 

### ISSUE THREAD

**Issue by SephVelut** [mitchellh/packer#3300]
`Packer version: 0.9.0`
`Packer Target OS/Arch: darwin amd64`

I'm getting an error when packer builds and gets to the amazon-import post-processor phase. `SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

template.json
```                
                "type": "amazon-import",
                "access_key": "{{user `aws_access_key`}}",
                "secret_key": "{{user `aws_access_key`}}",
                "region": "us-east-1",
                "s3_bucket_name": "bucketname"
```

The access and secret key are loaded from a json file via the `-var-file=variables.json` option.

variables.json
```
{
    "aws_access_key": "access key",
    "aws_secret_key": "secret"
}
```

Using the same access and secret key for the aws cli, I am able to access s3 and upload files. `aws configure list` shows the same keys. I checked and rechecked the keys permissions and its s3fullaccess. The keys also work fine using other tools like Transmit. The only thing I can think of is that  the secret key contains a forward slash and that's not escaped in the request?

**Comment by dave2** [comment]
Hi there.

Would you be able to run a quick test using the amazon-ebs builder to create an AMI, and see if you get the same error? It'll bisect if it's specific to amazon-import or a general problem with the handling of access/secret keys (since both the builder and the importer use the same code for that).

Thanks!

**Comment by SephVelut** [comment]
For the amazon ebs builder: Having the variables defined in a file works. Hardcoding them in the template json works.

For the amazon importer: Hard coding the variables in the template json works. Defining them in a separate file returns the error. Could this be an issue with the parsing?

**Comment by cbednarski** [comment]
The code paths here look nearly identical. Maybe we can add some debug logging:

	log.Println(common.ScrubConfig(b.config, b.config.AccessKey, b.config.SecretKey))

**Comment by cbednarski** [comment]
I added a log in 0f319fde08cd6ba116925fb13289bab431458bc0; @SephVelut If you can build from master and run with PACKER_LOG=1 this might help see what's going on. There will be a release soon (next few days) so if you like you can wait until that comes out.

**Comment by fredrikslattman** [comment]
Hey,

I'm experiencing the same issue with the amazon-ebs builder. Could this be related to builds that takes longer than the lifetime of a signature? See documentation here: http://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html#signature-v4-troubleshooting-key-signing

Cheers,
Fredrik

**Comment by rickard-von-essen** [comment]
@SephVelut do you still have this problem or did you resolve it?

**Comment by SephVelut** [comment]
I will close this as I was never able to reproduce.
