### ISSUE TITLE
Ansible-Remote Provisioner and WinRM

### ISSUE THREAD

**Issue by johnjelinek** [mitchellh/packer#3307]
Right now, the docs indicate SSH support, but I would like to use winrm. There might be a way to influence the group variables of the dynamic inventory to force winrm, but I'm not sure how to do that yet.

**Comment by rickard-von-essen** [comment]
Currently it is not possible to use WinRM and Ansible due to the design of _Communicators_ in packer.

This is something I have thought about addressing but it will require some work in the core parts of Packer so I have no due date.

**Comment by johnjelinek** [comment]
For ansible-remote, could it rely on the host that runs packer + ansible to handle the winrm communication? It doesn't seem like packer should have to worry about that as long as the windows guest has winrm enabled.

**Comment by bhcleek** [comment]
@johnjelinek The best thing for you to do here is to configure your Packer builder to use WinRM to communicate with and let the ansible provisioner continue to use SSH. That makes the communication look like `Ansible -----(ssh)----> ansible-provisioner ----(winrm)----> node`. You'll need to make sure you specify the correct `sftp_command` value in the ansible provisioner configuration so it can be started on the node by the ansible provisioner when Ansible tries to transfer files to the node.

**Comment by joekhoobyar** [comment]
@bhcleek - So, it looks like the only missing piece here is the fact that we won't have an SFTP server command available on the windows node unless we install OpenSSH?  Or do you have a an easier (more lightweight) option that you could suggest here?

**Comment by bhcleek** [comment]
@joekhoobyar, you're right; you'll have to install SFTP on the node to work with a Windows machine. Instead of installing OpenSSH, I believe you could compile https://github.com/pkg/sftp/blob/master/server_standalone/main.go for Windows and drop that on the node instead.

I plan to implement the SCP protocol in the Ansible provisioner soon to solve this problem; then OpenSSH won't have to be installed on the nodes at all.

**Comment by joekhoobyar** [comment]
Thanks for the tip!  I will try that standalone server and see how it works out for me.

**Comment by joekhoobyar** [comment]
So, I unfortunately cannot report that it is working at this time.  Ansible is unable to detect that this is a windows server via the inventory file that packer is generating:

```
==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Provisioning with shell script: /var/folders/f6/k1p59cs17r5bqq395l42739w0000gn/T/packer-powershell-provisioner275158897
    amazon-ebs:
    amazon-ebs: Mode                LastWriteTime     Length Name
    amazon-ebs: ----                -------------     ------ ----
    amazon-ebs: -a---         5/16/2016   9:24 PM    4595200 sftp-server.exe
==> amazon-ebs: Provisioning with Ansible...
==> amazon-ebs: SSH proxy: serving on 127.0.0.1:53556
==> amazon-ebs: Executing Ansible: ansible-playbook /Users/joe/Documents/ellucian-space/packer-tasks/spec/projects/winrm1/ansible/playbook.yml -i /var/folders/f6/k1p59cs17r5bqq395l42739w0000gn/T/packer-provisioner-ansible244636437 --private-key /var/folders/f6/k1p59cs17r5bqq395l42739w0000gn/T/ansible-key106718478
    amazon-ebs:
    amazon-ebs: PLAY [all] *********************************************************************
    amazon-ebs:
    amazon-ebs: TASK [setup] *******************************************************************
    amazon-ebs: SSH proxy: accepted connection
==> amazon-ebs: authentication attempt from 127.0.0.1:53557 to 127.0.0.1:53556 as Administrator using none
==> amazon-ebs: authentication attempt from 127.0.0.1:53557 to 127.0.0.1:53556 as Administrator using publickey
    amazon-ebs: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 22 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1463433902.51-216220569451453 `\" && echo \"` echo $HOME/.ansible/tmp/ansible-tmp-1463433902.51-216220569451453 `\" ), exited with result 1", "unreachable": true}
    amazon-ebs: 	to retry, use: --limit @/Users/joe/Documents/ellucian-space/packer-tasks/spec/projects/winrm1/ansible/playbook.retry
    amazon-ebs:
    amazon-ebs: PLAY RECAP *********************************************************************
    amazon-ebs: default                    : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by joekhoobyar** [comment]
Looks like the server is determined to be unreachable, too.

**Comment by joekhoobyar** [comment]
@bhcleek - is there anything else that I need to do to get this working?  I literally have the most minimal playbook and build I could come up with.

**Comment by bhcleek** [comment]
@joekhoobyar it looks like Ansible is trying to connect to the provisioner using `Administrator` as the username. Did you configure the provisioner to accept `Administrator` as the ssh user?

**Comment by joekhoobyar** [comment]
I set the `user` attribute to `Administrator`, yes.  Is there something else that I should be doing?

**Comment by fbsdmon** [comment]
@joekhoobyar did you get this setup working?
I would really like to provision my Windows server with Ansible, and Packer is just not complying.

**Comment by rickard-von-essen** [comment]
There have been some ansible improvements merged the last couple of days. It would be interesting to hear if anybody gets ansible + winrm to work on master. 

@bhcleek anything to add?

**Comment by bhcleek** [comment]
I agree that it should work as of `3a709fc`. The key to using ansible + winrm is to make sure that Ansible is communicating over SSH and that the ansible provisioner's `use_sftp` is `false` (`false` is the default).

**Comment by chris-smith-zocdoc** [comment]
I've been unsuccessful so far, see my comment at https://github.com/mitchellh/packer/issues/3911#issuecomment-250354823

**Comment by mwhooker** [comment]
moving to #3911
