### ISSUE TITLE
Shell provisioner exits in the middle of execution

### ISSUE THREAD

**Issue by amontalban** [mitchellh/packer#3310]
Hey guys,

I'm opening a new ticket as requested in #2391

**Packer version:**

```
Andres-MacBook-Pro:packer-test andres$ packer version
Packer v0.9.0
```

I can reproduce this in Linux and OSX however it's hard to reproduce and I can't share my actual Packer config, so I build a test with a bunch of SaltStack formulas on a Debian/Jessie OVF in order to catch it, I put this in each script:

```
echo "--- SALTSTACK HIGHSTATE 1 STARTED ---"
<<< SALT HIGHSTATE COMMAND >>>
echo "--- SALTSTACK HIGHSTATE 1 ENDED ---"
```

I tried to use [rerun](https://github.com/cbednarski/rerun) but I think it won't help because it only mark it as error when the exit code is different than 0, which in this case is 0 but output is not complete.

So I created this repo [packer-test](https://github.com/amontalban/packer-test) to help testing the error case.

This is what I'm seeing:

``` sh
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 remote command exited with '0': chmod +x /tmp/script_614.sh; PACKER_BUILD_NAME='virtualbox-ovf' PACKER_BUILDER_TYPE='virtualbox-ovf' /tmp/script_614.sh
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 [INFO] RPC endpoint: Communicator ended with: 0
2016/03/04 16:59:23 ui: [0;32m    virtualbox-ovf: Result: True[0m
[0;32m    virtualbox-ovf: Result: True[0m
2016/03/04 16:59:23 [INFO] 11322 bytes written for 'stdout'
2016/03/04 16:59:23 [INFO] 37606 bytes written for 'stderr'
2016/03/04 16:59:23 [INFO] RPC client: Communicator ended with: 0
2016/03/04 16:59:23 [INFO] RPC endpoint: Communicator ended with: 0
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 [INFO] RPC client: Communicator ended with: 0
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 [INFO] 37606 bytes written for 'stderr'
2016/03/04 16:59:23 ui: [0;32m    virtualbox-ovf: Comment: Moved "/tmp/consul-template" to "/usr/local/bin/consul-template-0.12.1"[0m
[0;32m    virtualbox-ovf: Comment: Moved "/tmp/consul-template" to "/usr/local/bin/consul-template-0.12.1"[0m
2016/03/04 16:59:23 ui: [0;32m    virtualbox-ovf: Started: 16:59:21.808197[0m
[0;32m    virtualbox-ovf: Started: 16:59:21.808197[0m
2016/03/04 16:59:23 ui: [0;32m    virtualbox-ovf: Duration: 1.361 ms[0m
[0;32m    virtualbox-ovf: Duration: 1.361 ms[0m
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 [INFO] 9032 bytes written for 'stdout'
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 [ERR] 'stdout' copy error: io: read/write on closed pipe
2016/03/04 16:59:23 ui: [0;32m    virtualbox-ovf: Changes:[0m
[0;32m    virtualbox-ovf: Changes:[0m
2016/03/04 16:59:23 ui: [0;32m    virtualbox-ovf: ----------[0m
[0;32m    virtualbox-ovf: ----------[0m
2016/03/04 16:59:23 ui: [0;32m    virtualbox-ovf: /usr/[0m
[0;32m    virtualbox-ovf: /usr/[0m
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 opening new ssh session
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 starting remote command: rm -f /tmp/script_614.sh
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 remote command exited with '0': rm -f /tmp/script_614.sh
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 [INFO] RPC endpoint: Communicator ended with: 0
2016/03/04 16:59:23 [INFO] RPC client: Communicator ended with: 0
2016/03/04 16:59:23 [INFO] RPC endpoint: Communicator ended with: 0
2016/03/04 16:59:23 packer: 2016/03/04 16:59:23 [INFO] RPC client: Communicator ended with: 0
```

I'm not seeing expected message `--- SALTSTACK HIGHSTATE 2 ENDED ---`.

For complete log you can check this [gist](https://gist.github.com/amontalban/fad6eecfe4b87b643233).

Let me know if you need anything else to do the testing.

Thank you very much!

**Comment by cbednarski** [comment]
Thanks for opening an issue and providing the repro case. That will help a lot! I suspect this is a race condition in the salt plugin but will need to do some digging. Usually race conditions are hard to find but easy to fix.

**Comment by amontalban** [comment]
Hey Chris,

Actually I use shell provisioner for Salt in this repro case and real Packer usage.

Thanks for taking a look at this!

**Comment by kev009** [comment]
I see the same thing, took several days to figure out it was packer killing the SSH shell provisioner session.  It appears to be linked to amount of shell output.

in my shell provisioner I switched to minimal output and everything works:
```
sudo salt-call --local -l warning --log-file=/root/salt-build.log --log-file-level=info --out=quiet state.sls singel.build
```

if I run that with console info logging, which is tremendously necessary for the Jenkins console, it bombs.

**Comment by amontalban** [comment]
Yes I'm doing almost the same but redirecting output to file and then
downloading the log file to host machine which runs Jenkins.

However my highstate is HUGE and takes some hours in build machine and
sometimes it fails even if redirecting all output to a file.

**Comment by kikitux** [comment]
@amontalban I did run your script, however I can see lots of changes happening that may cause issues. I think I saw changes in Time Zone?

I was able to run several test without issues. 

Just to be sure is not an guest OS issue, can you try with a different OS ?

**Comment by amontalban** [comment]
Hi @kikitux 

Thanks for looking in to this, I have experienced this issue in Debian and Freebsd (It's totally random).

Actually I just used random [SaltStack Formulas](https://github.com/saltstack-formulas) because I can't share my actual SaltStack configuration. You can replace the formulas with any other.

The script is just to confirm that we see the following text at the start of the shell script:

> --- SALTSTACK HIGHSTATE X STARTED ---

And the following text when the shell script ends:

> --- SALTSTACK HIGHSTATE 1 ENDED ---

Do you happen to have the logs of the run so I can check if it's complete?

Thanks!

**Comment by amontalban** [comment]
Ping @kikitux

**Comment by curiositycasualty** [comment]
I suspect something like this is needed: https://github.com/golang/crypto/commit/1aa39d6262fd81b5cdcfb1ca514bca5e32de756

(But that's a bit over my head to write.)

**Comment by mwhooker** [comment]
I copied the test from the golang/crypto example above, and was unable to reproduce. Going to close for now. Please open a new issue with an example that can reproduce this issue if you're still running into it.
