### ISSUE TITLE
Unable to set environment variables permanently in EC2 linux instance

### ISSUE THREAD

**Issue by javed91777** [mitchellh/packer#3312]
Hi,

I am creating packer image with EC2 linux instance. I am able to create the packer image successfully and setting JAVA_HOME and PATH variables while creating the packer image itself. But when I create an instance with this packer image the environment variables values are no longer available. Could someone let me know how to set environment variables permanently.

Packer version packer_0.9.0
Host: AWS EC2 linux instance

**Comment by rickard-von-essen** [comment]
This is clearly a usage question which should be directed to the [mailing list or #packer-tool @freenode](https://www.packer.io/community/).

If you are using a Debian derived distribution see [the Debian Administrator's Handbook](https://debian-handbook.info/browse/stable/sect.shell-environment.html).
