### ISSUE TITLE
Unable to use command in post-processor 'shell-local'

### ISSUE THREAD

**Issue by vikas027** [mitchellh/packer#3313]
I am unable to use [shell-local](https://www.packer.io/docs/provisioners/shell-local.html) with `command`, `scripts` option work absolutely fine though.

##### ENVIRONMENT

- Host OS: OSX 10.11.2
- Builder: VirtualBox 5.0.14
- Guest OS: CentOS 6.7 x86_64
- packer 0.9.0
- go 1.5.3

##### My Packer JSON
```json
{
"builders": [
    {
      "type": "virtualbox-iso",
      "guest_os_type": "RedHat_64",
      "iso_url": "file:///Users/vikas/Documents/ISOs/UNIX/LINUX/64-Bit/CentOS-6.7-x86_64-bin-DVD1.iso",
      "iso_checksum": "51f90e8ddd2ea199780065eaf75130ad",
      "iso_checksum_type": "md5",
      "http_directory": "http",
      "boot_command": "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks_centos_6.7.cfg<enter><wait>",
      "ssh_port": 22,
      "ssh_username": "vagrant",
      "ssh_password": "vagrant27",
      "shutdown_command": "echo vagrant | sudo -S /sbin/halt -h -p"
    }
  ],
"post-processors": [
    {
      "type": "shell-local",
      "command": "echo foo"
    }
]
}
```
##### ERROR LOGS
```
$ packer validate test.json
Template validation failed. Errors are shown below.

Errors validating build 'virtualbox-iso'. 1 error(s) occurred:

* unknown configuration key: "command"
```

##### DEBUG ERROR LOGS
Here are the [debug](https://gist.github.com/vikas027/0e7098a7a3c7d2fb63e5) logs.

**Comment by vikas027** [comment]
Also, please update the [documentation](https://www.packer.io/docs/provisioners/shell-local.html) that `shell-local` provisioner works with `scripts` too.

**Comment by cheeseplus** [comment]
As responded in IRC, looks like the public facing docs haven't been rebuilt but are fixed in tree : https://github.com/mitchellh/packer/blob/e486eba9cb0409eed70b0c87d8325a89efd200cb/website/source/docs/post-processors/shell-local.html.markdown

**Comment by rickard-von-essen** [comment]
_post-processor: shell-local_ Doesn't support any configuration key named ```command``` see the docs.

The [docs contain info about the configuration key ```scripts```](https://www.packer.io/docs/post-processors/shell-local.html#scripts).

**Comment by rickard-von-essen** [comment]
@cheeseplus I'm positive the site was deployed at the same time as the release of _v0.9.0_. Do you have any concrete examples where it is not reflecting _v0.9.0_?

**Comment by vikas027** [comment]
Thanks, below works fine.

```json
"post-processors": [
    {
      "type": "shell-local",
      "inline": "echo foo"
    }
]
```

**Comment by cheeseplus** [comment]
@rickard-von-essen 

https://www.packer.io/docs/provisioners/shell-local.html

```
{
  "type": "shell-local",
  "command": "echo foo"
}```

That is in docs right now.

**Comment by rickard-von-essen** [comment]
@cheeseplus but the issue was about post-processor `shell-local`.

**Comment by cheeseplus** [comment]
@rickard-von-essen looks like a case of double confusion then - I was looking at the provider. That said this is going to be real confusing for anyone who searches shell-local and maybe making the options line up in both or having a note on either page would be helpful in exactly these instances.

**Comment by rickard-von-essen** [comment]
(s/provider/provisioner/) We might have to do something in the docs.
