### ISSUE TITLE
chef-client validationKeyPath broken in 0.9.0

### ISSUE THREAD

**Issue by jviney** [mitchellh/packer#3314]
The chef-client provisioner ```validationKeyPath``` looks to be broken in 0.9.0. The config value is only processed after the chef config has been created. This works in 0.8.6.

You can see:
1. ```remoteValidationKeyPath``` defined as an [empty string](https://github.com/mitchellh/packer/blob/master/provisioner/chef-client/provisioner.go#L211)
2. The blank value is passed into ```createConfig``` [here](https://github.com/mitchellh/packer/blob/master/provisioner/chef-client/provisioner.go#L245)
3. The config value is finally processed and uploaded (too late) [here](https://github.com/mitchellh/packer/blob/master/provisioner/chef-client/provisioner.go#L253)

It looks like the fix would be to move this block of code above the ```createConfig``` call so it is processed in the same way as ```encryptedDataBagSecretPath ```.

```
if p.config.ValidationKeyPath != "" {
  remoteValidationKeyPath = fmt.Sprintf("%s/validation.pem", p.config.StagingDir)
  if err := p.uploadFile(ui, comm, remoteValidationKeyPath, p.config.ValidationKeyPath); err != nil {
    return fmt.Errorf("Error copying validation key: %s", err)
  }
}
```

This fix is untested.

**Comment by rickard-von-essen** [comment]
Thanks for the report. This seems to duplicate #3263.

**Comment by jviney** [comment]
Yes it's a dup.
