### ISSUE TITLE
Unable to use variable 'Provider' in shell-local post-processor

### ISSUE THREAD

**Issue by vikas027** [mitchellh/packer#3315]
I am unable to use `{{.Provider}}` variable in [shell-local](https://www.packer.io/docs/post-processors/shell-local.html) post-processor.

##### ENVIRONMENT

- Host OS: OSX 10.11.2
- packer 0.9.0
- go 1.5.3

##### My Packer file
This example is just to show the error, I know this does not makes any sense.
```json
{
"variables": {
  "os_to_build": "centos_6.7"
},
"builders": [
    {
      "type": "virtualbox-iso",
      "guest_os_type": "RedHat_64",
      "iso_url": "file:///Users/vikas/Documents/ISOs/UNIX/LINUX/64-Bit/CentOS-6.7-x86_64-bin-DVD1.iso",
      "iso_checksum": "51f90e8ddd2ea199780065eaf75130ad",
      "iso_checksum_type": "md5",
      "http_directory": "http",
      "boot_command": "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks_centos_6.7.cfg<enter><wait>",
      "ssh_port": 22,
      "ssh_username": "vagrant",
      "ssh_password": "vagrant27",
      "shutdown_command": "echo vagrant | sudo -S /sbin/halt -h -p"
    }
  ],
"post-processors": [
    {
      "type": "shell-local",
      "inline": [ "vagrant box add --name {{ user `os_to_build` }} --force /Users/vikas/Vagrant_Lab/Vagrant_Boxes/{{.Provider}}/{{ user `os_to_build` }}_06-Mar-16.box" ]
    }
  ]
}
```

If I replace `{{.Provider}}` with `virtualbox` packer build works fine.

##### DEBUG ERROR LOGS
Here are the [debug](https://gist.github.com/vikas027/0e7098a7a3c7d2fb63e5) logs.

**Comment by rickard-von-essen** [comment]
You should use ```$PACKER_BUILDER_TYPE``` [see the docs](https://www.packer.io/docs/post-processors/shell-local.html).

**Comment by vikas027** [comment]
@rickard-von-essen Can you please give an example of how to use it in my case ? Thanks in advance.

**Comment by rickard-von-essen** [comment]
```json
{
  "type": "shell-local",
  "inline": ["echo $PACKER_BUILDER_TYPE"]
}
```
Common shell knowledge, ask on IRC or read [Advanced Bash-Scripting Guide](http://www.tldp.org/LDP/abs/html/), etc.

**Comment by vikas027** [comment]
Thanks @rickard-von-essen :+1:  
I am pretty good with bash, but here it wasn't quite clear how to use this variable. I mean directly with `inline` or define `environment_vars` separately. Anyways, I am glad my JSON is a little smaller now.
