### ISSUE TITLE
Encoding problem when grabbing file from S3 on Windows for AWS AMI build

### ISSUE THREAD

**Issue by ayan-usgs** [mitchellh/packer#3317]
I've been attempting create a custom Windows Server 2008 R2 AMI in AWS using Packer. Some of the necessary installation and configuration files are stored in S3. However, attempts to retrieve objects from S3 have resulted in AWS CLI errors about unknown encoding along the lines of `LookupError: unknown encoding: cp65001`. The encoding errors then cause subsequent errors as the installation files weren't retrieved. The scripts and templates worked previously with Packer 0.8.6. In addition, the powershell scripts to grab content from an S3 bucket work fine when a human connects to an AWS Windows instances and runs the script manually.

* Packer version: 0.9.0 (64-bit)
* Host OS: Windows 7
* Guest OS: Windows Server 2008 R2
* Log: https://gist.github.com/ayan-usgs/11937bf59e3bee973428
* Simple Template: https://gist.github.com/ayan-usgs/663c6226ec2421df968a
* Scripts: https://gist.github.com/ayan-usgs/d43bf81204b34e9f5092, https://gist.github.com/ayan-usgs/da7bfef723d155dcb095, https://gist.github.com/ayan-usgs/5a4ee3cd2ccc3574da14

I have redacted all content specific to the AWS VPC and subnets  I was working in. The simple template runs a script to pull done an XML file I have been using, but I suspect any bucket and file will suffice to reproduce the error.

**Comment by ayan-usgs** [comment]
I'm not sure this can be reliably reproduced. I'm closing until that's sorted out.

**Comment by jakemig** [comment]
Ran into the same issue and resolved it by adding `chcp 850` to my powershell script before calling the AWS CLI.

TechNet reference: https://technet.microsoft.com/en-us/library/bb490874.aspx

**Comment by Philippe23** [comment]
@jakemig you just saved my life with that.  I'm getting the error 100% of the time from a Win10 cmd.exe prompt when trying to upload a Linux GameLift build via `aws gamelift upload-build`, where the code page is 437.  Just like you said, manually switching to 850 fixes the error.  I bet it has something to do with the upload progress display.
