### ISSUE TITLE
Add option to log debug output to a file with normal output on stdout

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#3319]
`PACKER_LOG` adds debug info to the log output.
`PACKER_LOG_PATH` allows you to save log output to a file.

It would be nice to have a `PACKER_DEBUG_PATH` or similar that will automatically save the debug log to a file and show the regular output on stdout. This is nice when running packer via CLI or CI because you can see the build log without extra noise but also have the debug log available in case the build fails or packer has a problem.

**Comment by mwhooker** [comment]
this sounds good, but not something we can do for 1.0

**Comment by Dombo** [comment]
Out of interest has this been discussed further? From a developer experience perspective this is desirable for our workflow where packer is at the heart of our build system.

**Comment by rickard-von-essen** [comment]
See https://www.packer.io/docs/other/debugging.html#debugging-packer
