### ISSUE TITLE
Making OpenStack builder use an existing server instance (instead of creating a new one)

### ISSUE THREAD

**Issue by ghost** [mitchellh/packer#3325]
I'm wondering if it's possible to make the OpenStack builder use an existing instance instead of creating a new one?

My use case is to improve the build time by having "stand by" servers that can be used immediately.

**Comment by rickard-von-essen** [comment]
Currently it's not possible.

It is probably possible to do something similar as the `amazon-chroot` builder but would require someone to contribute a rather big new feature.

**Comment by imduffy15** [comment]
Dirty hack:
 - Use the ssh builder to login to one of the pool of stand by machines you have available
 - use the shell local post processor to handle the terminate and snapshot taking

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
