### ISSUE TITLE
add custom floppy size in config for all builders

### ISSUE THREAD

**Issue by jim3ma** [mitchellh/packer#3328]
Now, the default floppy size is 1440*1024, it's enough sometime.
But, in some special cases  we want to add some other files bigger than 1440*1024, such as compiled open-vm-tools and so on.
Yes, we can add files in provisions, but I think the size should be customize.

**Comment by majinjing3** [comment]
An other solutions:
**Before create floppy, calculate the size of all files and directories**
If, the size is less than 1.44MB, create a 1.44MB size floppy, or create the size calculated before.

**Comment by kikitux** [comment]
The floppy part is to bootstrap the installation of the OS, pass Kickstart/preseed/unattended file and get the installation running.

So as today to put files into the new VM you can use the http server, or file provisioner.

Perhaps, add a feature create and mount an iso would be better than make a floppy large.
ie: https://github.com/johto/iso9660wrap

**Comment by majinjing3** [comment]
Yes, create and mount an iso is the better solutions. Because **the floppy big than 1.44Mb in vmware esx server is not available** @rickard-von-essen

**Comment by mwhooker** [comment]
happy to look at PRs for this
