### ISSUE TITLE
Support google pd-ssd

### ISSUE THREAD

**Issue by JorritSalverda** [mitchellh/packer#3332]
The google provider should support ability to configure the disk type for the boot disk. Currently the pd-standard disk is used, but I think baking images would hugely benefit from the ability to switch to pd-ssd.

**Comment by cbednarski** [comment]
@JorritSalverda I think https://github.com/mitchellh/packer/pull/2830 may address your concern. I have been focused elsewhere lately so I have not had a chance to review but if you can test it out let me know if this satisfies your use-case. Thanks!

**Comment by JorritSalverda** [comment]
Yes, this will definitely do what's needed. Will it be part of the next release?

**Comment by cbednarski** [comment]
@JorritSalverda Yep! This will go out in 0.10.
