### ISSUE TITLE
Resume interrupted iso download

### ISSUE THREAD

**Issue by adeck** [mitchellh/packer#3334]
# Feature request

If a download is interrupted due to lost network connection, allow for download resumption. While this probably shouldn't be enabled by default, ideally there would be an option in the config file.
# Use case

Most ISOs are large enough that I'm unlikely to be able to download the entire thing on the first try. Usually, network congestion is high enough at some part of the download that latency becomes high enough the connection is assumed to have been lost, and I end up rerunning the command and restarting the download from scratch. Which gets old fast, and wastes a lot of time. Largely because it's usually been downloading for a few minutes before it fails.

While I could simply use `curl` or `wget`, that would undermine the entire point of even having download functionality in packer, and it would mean the time spent writing that part of the config file was entirely wasted.

**Comment by cbednarski** [comment]
Thanks for the suggestion. I can certainly see how this helps if your network is slow and/or unreliable.

> While I could simply use curl or wget, that would undermine the entire point of even having download functionality in packer, and it would mean the time spent writing that part of the config file was entirely wasted.

There are a handful of ways you can use this part of the configuration. For example, you can specify more than one source for your ISO and one of those sources could be a local file (that you downloaded with wget). If that file is not present (for example if you `packer push` to Atlas) then the download will kick in.

So in the mean time, don't feel bad about using `wget`. The resume feature is great!

**Comment by arizvisa** [comment]
PR #2906 contains initial support for resuming ftp and smb transfers, someone will just need to implement the .Cancel() and .Resume() functions in DownloadClient, and then do the seeking in .Resume() for each Downloader. I'd do it, but I'm not quite sure how mitchellh intended .Cancel() in DownloadClient to really be used so that a .Resume() can be implemented.

For the HTTPDownloader interface, I'm also pretty certain that there's an http module in go that should make resuming pretty straightforward.

**Comment by mwhooker** [comment]
this is fixed now

```
~/dev/packertest ᐅ packer build 3896.json
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: http://old-releases.ubuntu.com/releases/precise/ubuntu-12.04.2-server-amd64.iso
    vmware-iso: Download progress: 0%
    vmware-iso: Download progress: 1%
    vmware-iso: Download progress: 1%
    vmware-iso: Download progress: 2%
^C==> vmware-iso: Interrupt received. Cancelling download...
Build 'vmware-iso' errored: Build was cancelled.
Cleanly cancelled builds after being interrupted.
~/dev/packertest ᐅ packer build 3896.json
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: http://old-releases.ubuntu.com/releases/precise/ubuntu-12.04.2-server-amd64.iso
    vmware-iso: Download progress: 3%
^C==> vmware-iso: Interrupt received. Cancelling download...
Build 'vmware-iso' errored: Build was cancelled.
Cleanly cancelled builds after being interrupted.
```
