### ISSUE TITLE
Packer binary release 0.9.0 missing builders, helper executables?

### ISSUE THREAD

**Issue by nyetsche** [mitchellh/packer#3342]
From the page https://www.packer.io/downloads.html, the link for Linux x86_64, https://releases.hashicorp.com/packer/0.9.0/packer_0.9.0_linux_amd64.zip contains:

```
 ~[0] $ ls -hl packer_0.9.0_linux_amd64.zip
-rw-r--r-- 1 leskomw sysadmin 8.0M Feb 19 21:51 packer_0.9.0_linux_amd64.zip
 ~[0] $ md5sum packer_0.9.0_linux_amd64.zip
8a58873c3f212d3db5e7cbc3fe5a0c7e  packer_0.9.0_linux_amd64.zip
 ~[0] $ unzip -l packer_0.9.0_linux_amd64.zip
Archive:  packer_0.9.0_linux_amd64.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 38663840  02-19-2016 21:36   packer
---------                     -------
 38663840                     1 file
```

The previous version, 0.8.6, contains all of the helper files:

```
 ~[0] $ md5sum packer_0.8.6_linux_amd64.zip
4cda1c44cf666fada495dd8e01522e1c  packer_0.8.6_linux_amd64.zip
 ~[0] $ ls -lh packer_0.8.6_linux_amd64.zip
-rw-r--r-- 1 leskomw sysadmin 127M Oct 24 02:51 packer_0.8.6_linux_amd64.zip
 ~[0] $ unzip -l packer_0.8.6_linux_amd64.zip | head
Archive:  packer_0.8.6_linux_amd64.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 11691536  08-22-2015 11:40   packer
 16134240  08-22-2015 11:40   packer-builder-amazon-chroot
 17525280  08-22-2015 11:40   packer-builder-amazon-ebs
 17546720  08-22-2015 11:41   packer-builder-amazon-instance
 13221904  08-22-2015 11:41   packer-builder-digitalocean
 13030992  08-22-2015 11:41   packer-builder-docker
 10547952  08-22-2015 11:41   packer-builder-file
 [...]
```

Were those files all sublimated into `packer`? That seems slightly unlikely based on the filesizes. Plus, from the 0.9.0 release, I'm unable to actually start a build:

```
2016/03/11 17:00:44 Running builder: amazon-ebs
2016/03/11 17:00:44 packer: 2016/03/11 17:00:44 [INFO] Finding AZ for the given subnet 'subnet-fd87e2c7'
2016/03/11 17:00:44 ui error: Build 'amazon-ebs-my--branch' errored: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id:
2016/03/11 17:00:44 Builds completed. Waiting on interrupt barrier...
[...]
```

I believe the `UnauthorizedOperation` is an attempt to execute the non-existent `packer-builder-amazon-ebs` file, not AWS permissions. That same build with 0.8.6 (and associated files) succeeds.

**Comment by cbednarski** [comment]
Thanks for opening an issue. In Packer 0.9.0 all of the plugins are compiled into one binary. This makes packer take up significantly less disk space, smaller download, etc.

If you installed 0.9.0 over your previous 0.8.6 installation you will need to remove the other plugins, since they are old and out of date. You can do this via `rm packer-*` in your install path, which will remove the plugins and leave the main packer binary. Sorry for the inconvenience!
