### ISSUE TITLE
Packer doesn't pause when piping a template with debug enabled

### ISSUE THREAD

**Issue by nathanielks** [mitchellh/packer#3345]
Happy Saturday, team!

I'm taking advantage of the _wonderful_ feature of piping a json template to packer, but I'm running into an issue! When running packer with `-debug`, an already compiled 
template must be provided because otherwise all the enter-to-continue prompts behave as if you'd hit enter every time. Not the end of the world, but it'd be great if it could work by just piping!

Concisely: 
  - `cat template.json | packer build -debug -` skips the enter-to-continue steps.
  - `packer build -debug template.json` works as expected.

Packer Version: 0.9.0
Host platform: OS X 10.10.5
[PACKER_LOG and basic template](https://gist.github.com/nathanielks/43da5ee29f30a44abfa6)

**Comment by rickard-von-essen** [comment]
I'm sorry to say it's impossible. Pipe (`|`) connects standard out of `cat` to standard in of `packer` which is normally where keystrokes come.

**Comment by nathanielks** [comment]
Yup, that totally makes sense. Thanks!
