### ISSUE TITLE
"extra_arguments" behavior of "ansible (remote)" and "ansible-local"

### ISSUE THREAD

**Issue by dmikurube** [mitchellh/packer#3353]
I found a difference of behaviors of "extra_arguments" between "ansible (remote)" and "ansible-local" provisioners.

In elder "ansible-local", the below worked. Many are found about this kind of statements on the web. https://github.com/mitchellh/packer/issues/555#issuecomment-145749614 is an example.

`"extra_arguments": [ "--extra-vars \"deploy_env=dev\"", ... ]
`

In contrast, it doesn't work in the recent "ansible (remote)" provisioner.

`error: no such option: --extra-vars "deploy_env
`

We have to write "--extra-vars" in "extra_arguments" in a split manner as below in "ansible (remote)".

`"extra_arguments": [ "--extra-vars", "deploy_env=dev", ... ]
`

It looks coming from the difference of how "extra-vars" is parsed and executed.
https://github.com/mitchellh/packer/blob/7ac30135fccc2f921177626566d71c8fa8816c53/provisioner/ansible-local/provisioner.go#L249
https://github.com/mitchellh/packer/blob/7ac30135fccc2f921177626566d71c8fa8816c53/provisioner/ansible/provisioner.go#L305

I'm not confident which is the better way, but I believe they should be consistent. I'm fine to write a patch when a decision is made.

Thanks. :)

**Comment by cbednarski** [comment]
@dmikurube Thanks for pointing this out. I agree that it would be good for these to be consistent. We typically encourage copy-pasting because it's easier to get a feature implemented that way but in this case to establish parity it is probably a good idea to refactor and DRY up the code a bit. If you want to take this on I'd be happy to review!

**Comment by InAnimaTe** [comment]
I just ran into this because the docs for `ansible` are incorrect. #3423 should be merged in ASAP so others don't trip over this!
