### ISSUE TITLE
Remove mentions of upload in docs for shell-local post-processor

### ISSUE THREAD

**Issue by rickard-von-essen** [mitchellh/packer#3357]

**Comment by benklop** [comment]
While clarifying the documentation for the shell-local post-processor, it should be made clear whether there is a way to get or create build artifacts, too.

**Comment by mwhooker** [comment]
I don't see any `upload` in the shell-local post processor docs. @rickard-von-essen please re-open if I've misunderstood this issue.

@benklop please open a new issue for that.
