### ISSUE TITLE
Crash with none communicator and vmware-iso - Packer 0.9

### ISSUE THREAD

**Issue by propa52000** [mitchellh/packer#3358]
Hello everyone,

I just try to use Packer in order to create Windows 7 image for vmware. So I don't need any communicator et I don't want to install an openssh server in the OS (like it's usualy do). But after the "stopping virtual machine" step I obtain the packer crash message:

==> vmware-iso: Stopping virtual machine...
Build 'vmware-iso' errored: unexpected EOF

Informations:
Packer 0.9.0
Linux Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29)

template-packer.json that create the crash
https://gist.github.com/propa52000/4da7c41e21db0799f8c7

output from the "PACKER_LOG=1 packer build template.json" command:
https://gist.github.com/propa52000/36e058fdb8423ae8d19e

Data in crash.log:
https://gist.github.com/propa52000/c29d5e58dd6ce6dbdec3

if you need something else, I'm available

**Comment by rickard-von-essen** [comment]
Thanks for reporting, this is the same issue as #3046.
