### ISSUE TITLE
interpolate in provisioner/shell inline command

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#3362]
As i understand, commands that inlined does not interpolated? If i send pr does this accepted by upstream?

**Comment by rickard-von-essen-iz** [comment]
They are interpolated see https://github.com/mitchellh/packer/blob/master/provisioner/shell/provisioner.go#L78

The only exception should be `execute_command`

**Comment by vtolstov** [comment]
Hm, i dont think thats right. Check qemu builder, exlude means - interpolate this structure element.

**Comment by vtolstov** [comment]
check #3368
