### ISSUE TITLE
Feature request: amazon-ebs builder can create AMIs with encrypted root volumes

### ISSUE THREAD

**Issue by gregburek** [mitchellh/packer#3364]
Hello, 
I use the amazon-ebs builder to create EBS backed AMIs and then copy them to other regions. I would like to create AMIs with encrypted EBS volumes with the amazon-ebs builder that then remain encrypted as they are copied between regions.

As of Dec 15, 2015 (https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/) CopySnapshot and CopyImage can accept a `Encrypted` bool parameter so that the snapshot and/or image is encrypted with a customer's default key as it is copied within or between regions. It would be easier if the CreateImage api accepted these encryption options, but that is not yet the case. 

It appears that the amazon-ebs builder could, if a config bool `ami_encryption` were true, return early from the `StepCreateAMI` step and in a new `StepCreateEncryptedAMI` step, take a snapshot of the stopped instance, copy the snapshot with encryption and then register the snapshot as an image. I believe then `StepAMIRegionCopy` would also need to use the `Encrypted` parameter as part of CopyImage, but the docs are not terribly clear about if AMIs with already encrypted root disks need that parameter, or it in inherited from the source AMI.  

Thanks

**Comment by brettcave** [comment]
+1

This was also discussed on #3085 and initially came across the lack of this feature in Packer on http://www.davekonopka.com/2016/ec2-encrypted-boot-volumes.html 

As an alternative to creating an encrypted AMI from an unencrypted one by the builder, a "aws-convert-to-encrypted" sort of post processor would also be a useful implementation. I'm currently trying to implement this with a `shell-local` post processor....

**Comment by ptolemy428** [comment]
+1
This would be a very useful feature to keep our ami baking process (using Packer) nicely automated without compromising security.

**Comment by mlosapio** [comment]
Looks like someone's already written the PR. 
https://github.com/mitchellh/packer/pull/3382

**Comment by gregburek** [comment]
#3382 is from @ahamidi, who I work with at Heroku. Our group is currently using the patch in #3382 in production to build amis with encrypted root disks and ship them to several other regions. It works.

**Comment by kwilczynski** [comment]
Related to #3613.

**Comment by razorsedge** [comment]
@brettcave Do you have that `shell-local` post processor working?
