### ISSUE TITLE
Mistake in the doc "communicator"

### ISSUE THREAD

**Issue by propa52000** [mitchellh/packer#3366]
Hi,

There is a mistake in the doc about the communicator "WinRM" (communicator.html.md file)

In the "WinRM Communicator", about the "winrm_port" parameter:
The SSL port is not "5896" like it's written but the port "5986"

I quote:
"On Windows 7 and higher the default port is 5986."
https://support.microsoft.com/en-us/kb/2019527

**Comment by cbednarski** [comment]
Thanks for opening an issue! It looks like the numbers got swapped. Would you be willing to open a PR for the fix?

**Comment by chasebolt** [comment]
this was fixed in 8bb3541

**Comment by cbednarski** [comment]
Thanks for the tip @chasebolt !

**Comment by propa52000** [comment]
Oh sorry I forgot to do it! Thanks chasebolt!
