### ISSUE TITLE
Packer returns error code 1 for --version. 

### ISSUE THREAD

**Issue by gtmtech** [mitchellh/packer#3370]
Packer 0.8.6
Host platform OSX
Debug log - not required

```
$ packer --version
0.8.6
$ echo $?
1
```

Packer has done exactly what it should have done. It should not be returning error code 1 (for one, this will affect other caller bash scripts with `set -e` or similar)

**Comment by FGtatsuro** [comment]
@gtmtech 
This causes from https://github.com/mitchellh/cli/pull/28 I think.

**Comment by cbednarski** [comment]
@FGtatsuro Yes, thanks for the upstream PR.

@gtmtech I agree we should fix this. It makes checking whether packer is installed / at the right version rather annoying. For now please use `packer version` instead.
