### ISSUE TITLE
pass HTTPPort to provisioners

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#3372]
What is the best way to pass HTTPPort to provisioner for feature interpolation? (i want to use it inside shell inline commands)

**Comment by cbednarski** [comment]
@vtolstov Thanks for reaching out. I'm interested in this too. If there is an existing struct that is passed into the provisioner (perhaps `Config`) that we can use that's probably ideal.

**Comment by mwhooker** [comment]
dupe of #2869, which has been solved
