### ISSUE TITLE
Unable to retrieve ami details after packer sees ami state as available.

### ISSUE THREAD

**Issue by danschaffer** [mitchellh/packer#3377]
Recently seeing intermittent packer failures in both packer 0.9.0 and 0.8.6 in amazon-chroot builder.
Packer creates a snapshot, registers the ami, attempts to tag the ami then fails unable to find the ami.

Seems like the aws api returns the ami state as available but is unable to retrieve the ami.  I reproduced the problem both with packer 0.9.0 and 0.8.6.  I logged a ticket with AWS as well to determine if they are aware of a recent change causing ami state to show available before it can be retrieved.   I was wondering if packer amazon chroot builder could retry when it ami cannot be retrieved.  The packer debug log. from running PACKER_LOG=1 is https://gist.github.com/danschaffer/8372c9118d67f9392d66.

**Comment by danschaffer** [comment]
I have been investigating intermittent packer failures in amazon/chroot builder with AWS support.  Support believes the failures are due to "eventual consistency issues".  Directly after creating the ami, calls to retrieve the ami object (to tag it) intermittently fail.  AWS support suggested retrying retrieving the ami object with an exponential backoff algorithm for up to 2.5 minutes.  I have been experimenting with retries and had some success with simple retries 5s apart and approximately 9/10 attempts succeed without any retry and the 1/10 case succeeds within 2 retries (15s).  For ~9 months we have never had any such issues and in the past 3 weeks we see this problem approx 5-10% of packer runs.

**Comment by danschaffer** [comment]
I have been running with this patched packer version to implement a retry algorithm.
https://github.com/mitchellh/packer/pull/3408

Let me know if you have any feedback.
here's an example of the patch when the tag fails and retries (usually the retry works within 2s, this example took ~6s):
22:32:39 ==> amazon-chroot: Adding tags to AMI (ami-a7666ccd)...
22:32:39     amazon-chroot: Adding tag: "creation_time": "2016-03-31 22:30:48 UTC"
22:32:39     amazon-chroot: Adding tag: "creator": "packer"
22:32:39 ==> amazon-chroot: Tagging snapshot: snap-36d7a129
22:32:39 ==> amazon-chroot: Error adding tags to Resources ([]*string{(*string)(0xc8204d3f40), (*string)(0xc8204b8258)}): InvalidAMIID.NotFound: The image id '[ami-a7666ccd]' does not exist
22:32:39 ==> amazon-chroot:     status code: 400, request id:
22:32:39 ==> amazon-chroot: Will retry adding tags, in 200 ms
22:32:39 ==> amazon-chroot: Error adding tags to Resources ([]*string{(*string)(0xc8204d3f40), (*string)(0xc8204b8258)}): InvalidAMIID.NotFound: The image id '[ami-a7666ccd]' does not exist
22:32:39 ==> amazon-chroot:     status code: 400, request id:
22:32:39 ==> amazon-chroot: Will retry adding tags, in 800 ms
22:32:39 ==> amazon-chroot: Error adding tags to Resources ([]*string{(*string)(0xc8204d3f40), (*string)(0xc8204b8258)}): InvalidAMIID.NotFound: The image id '[ami-a7666ccd]' does not exist
22:32:39 ==> amazon-chroot:     status code: 400, request id:
22:32:39 ==> amazon-chroot: Will retry adding tags, in 1800 ms
22:32:39 ==> amazon-chroot: Error adding tags to Resources ([]*string{(*string)(0xc8204d3f40), (*string)(0xc8204b8258)}): InvalidAMIID.NotFound: The image id '[ami-a7666ccd]' does not exist
22:32:39 ==> amazon-chroot:     status code: 400, request id:
22:32:39 ==> amazon-chroot: Will retry adding tags, in 3200 ms
22:32:39 ==> amazon-chroot: Deleting the created EBS volume...
22:32:39 Build 'amazon-chroot' finished.

**Comment by mwhooker** [comment]
fixed via #3938
