### ISSUE TITLE
Chef Client unable to create Temp directory on Windows

### ISSUE THREAD

**Issue by jamestoyer** [mitchellh/packer#3381]
- Packer Version: 0.10.0
- Host platform: Windows 10
- Destination platform: Windows Server 2012R2
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/jamestoyer/5d78735c4fb51f9380ba

I've been trying to get the Chef Client provision to work on Windows. My current machine is Windows 10 and the server I'm trying to install on to is a vanilla Windows Server 2012R2 instance in AWS. The current AMI is `ami-3d787d57` in `us-east-1`. 

When the provision gets to creating a temporary directory, the provision fails and the build terminates. I've tried doing this with the default path which has not been created (see attached gist) as well as pre-creating the path. Either way it still fails the same way. 

The gist contains the template and sample userdata file we use.

**Comment by cbednarski** [comment]
Thanks for the report. Looks like we're assuming a POSIX OS on the remote side, since the tmp folder is specified as `/tmp` which is obviously not correct.

```
2016/03/23 15:38:26 packer.exe: 2016/03/23 15:38:26 Uploading file to '/tmp/script.bat'
```

**Comment by mwhooker** [comment]
I believe this is the source of the error

```
    {
      "remote_path": "/tmp/script.bat",
      "scripts": [
        "scripts/stop-tasks.bat"
      ],
      "type": "windows-shell"
    },
```

you're trying to upload to a path that doesn't exist. I believe if you change remote_path to a directory that exists, that this should work.
