### ISSUE TITLE
iso_checksum_url does not allow md5 sum without newline at the end

### ISSUE THREAD

**Issue by belonesox** [mitchellh/packer#3383]
«iso_checksum_url (string) - A URL to a GNU or BSD style checksum file containing a checksum for the OS ISO file»

When «iso_checksum_url» contains content with newline at the end, all OK
«0fb3f1fc9bfd1a423518da6305a79f73  some-iso-image.iso\n»

When no newline at the end, just 
«0fb3f1fc9bfd1a423518da6305a79f73  some-iso-image.iso»

packer failed with 
«No checksum for "some-iso-image.iso" found at: … »

- Packer Version: 0.9.0
- Host platform: Linux/Windows/ALL
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/belonesox/92b25b18bca9ae9c53a7
- The _simplest example template and scripts_ needed to reproduce the bug.
   https://gist.github.com/belonesox/bc47abb20bb50b9085f7

**Comment by vtolstov** [comment]
Patches welcome, or i can handle this in next week.

**Comment by vtolstov** [comment]
please, merge pr.
