### ISSUE TITLE
Link to documentation for packer.Cache at extend/builder links to self.

### ISSUE THREAD

**Issue by briangreenery** [mitchellh/packer#3384]
In "Caching Files" section of the "builder" documentation, the link to `documentation for packer.Cache` links to `#`. This is on the website [on this page](https://www.packer.io/docs/extend/builder.html) at the very bottom.

In the repository, this is present [here](https://github.com/mitchellh/packer/blob/fedb0e21f03607060b002fd1467bc617b6a4e812/website/source/docs/extend/builder.html.md#caching-files) in the 0.10.0 release.

**Comment by psifertex** [comment]
The best part about this is the link text says "The documentation for packer.Cache is very detailed in how it works." 

Which is basically the opposite of what it is right now...
