### ISSUE TITLE
Need a handle to set hard drive controller names.

### ISSUE THREAD

**Issue by dtx** [mitchellh/packer#3388]
Today when we provide a `hard_drive_interface` value in builder, the name of the controller is hard coded as per observations and reading the code ([here](https://github.com/mitchellh/packer/blob/master/builder/virtualbox/iso/step_create_disk.go)) for virtualbox-iso step for creating disk.

This could conflict with any assumptions made with other routines expecting a specific controller name. For example, [storageattach in VirtualBox](https://www.virtualbox.org/manual/ch08.html#vboxmanage-storageattach).

It would be nice to have a handle to also provide controller name when creating a `hard_drive_interface`. ([@jc-m](https://github.com/jc-m) who pointed this out)

**Comment by mwhooker** [comment]
This should be an easy fix if anyone wants to submit a PR. It's pretty edge-casey, though, so it's not something I think we want to do for 1.0
