### ISSUE TITLE
r

### ISSUE THREAD

**Issue by benmarcus** [mitchellh/packer#3391]
**DELETE THIS TEMPLATE BEFORE SUBMITTING**

If you are planning to open a pull-request just open the pull-request instead of making an issue first.

FOR FEATURES:

Describe the feature you want and your use case _clearly_.

FOR BUGS:

Describe the problem and include the following information:

- Packer Version
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by rickard-von-essen** [comment]
Closing since the issue lacks information.
