### ISSUE TITLE
invoking ovftool in vsphere post-processor fails

### ISSUE THREAD

**Issue by godfryd** [mitchellh/packer#3394]
In file post-processor/vsphere/post-processor.go, in line 124 the arguments should no be put in quotation marks. Instead of this:
	args := []string{
		fmt.Sprintf("--noSSLVerify=%t", p.config.Insecure),
		"--acceptAllEulas",
		fmt.Sprintf("--name=\"%s\"", p.config.VMName),
		fmt.Sprintf("--datastore=\"%s\"", p.config.Datastore),
		fmt.Sprintf("--diskMode=\"%s\"", p.config.DiskMode),
		fmt.Sprintf("--network=\"%s\"", p.config.VMNetwork),
		fmt.Sprintf("--vmFolder=\"%s\"", p.config.VMFolder),
		fmt.Sprintf("%s", source),
		fmt.Sprintf("\"%s\"", ovftool_uri),
	}
there should be:
	args := []string{
		fmt.Sprintf("--noSSLVerify=%t", p.config.Insecure),
		"--acceptAllEulas",
		fmt.Sprintf("--name=%s", p.config.VMName),
		fmt.Sprintf("--datastore=%s", p.config.Datastore),
		fmt.Sprintf("--diskMode=%s", p.config.DiskMode),
		fmt.Sprintf("--network=%s", p.config.VMNetwork),
		fmt.Sprintf("--vmFolder=%s", p.config.VMFolder),
		fmt.Sprintf("%s", source),
		fmt.Sprintf("%s", ovftool_uri),
	}
Otherwise it just does not work. Quotation marks are only needed if such command is executed in shell. Here the args are directly passed to exec and so the quotation marks are not needed. Worse, they cause failure of this command.

**Comment by rickard-von-essen** [comment]
Duplicates #3204, please reopen if I'm wrong.

**Comment by rickard-von-essen** [comment]
It is really good if you can verify that the linked PR in #3204 solves your problem.

**Comment by godfryd** [comment]
It does not seem the same but I'm not sure.
For sure my case is true and it needs that simple fix.

**Comment by godfryd** [comment]
OK, I found PR commits. It seems that the fix is ok.
