### ISSUE TITLE
Chef knife clean-up command malformed in Windows build

### ISSUE THREAD

**Issue by petewilcock** [mitchellh/packer#3395]
- Packer Version: 0.10.0
- MacOS X El Capitan

Running a Windows 10 VM virtualbox-iso builder from a MacOS host. Build completes successfully but knife node cleanup command is malformed. 

The 'sudo knife' command makes it seem like it's trying to run the cleanup from the host, but it specifies the VM's Windows knife config file and path. Given the error it's running the Linux-style command on the Windows VM which is obviously failing. 

Node clean-up needs a test for VM OS and run the appropriate command?

```
windows-10-enterprise: [2016-03-29T14:59:54+01:00] INFO: Chef Run complete in 1756.8913521 seconds
    windows-10-enterprise: [2016-03-29T14:59:54+01:00] INFO: Running report handlers
    windows-10-enterprise: [2016-03-29T14:59:54+01:00] INFO: Report handlers complete
    windows-10-enterprise: [2016-03-29T14:59:54+01:00] INFO: Sending resource update report (run-id: a536e531-ada6-4f7b-b98e-86f0adc950d0)
    windows-10-enterprise: Creating configuration file 'knife.rb'
==> windows-10-enterprise: Cleaning up chef node...
    windows-10-enterprise: 'sudo' is not recognized as an internal or external command,
    windows-10-enterprise: operable program or batch file.
==> windows-10-enterprise: Unregistering and deleting virtual machine...
==> windows-10-enterprise: Deleting output directory...
Build 'windows-10-enterprise' errored: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.

Command: sudo knife node delete packer-56fa831b-2771-8560-a6d3-c2f9f02e0529 -y -c C:/Windows/Temp/packer-chef-client/knife.rb

==> Some builds didn't complete successfully and had errors:
--> windows-10-enterprise: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.

Command: sudo knife node delete packer-56fa831b-2771-8560-a6d3-c2f9f02e0529 -y -c C:/Windows/Temp/packer-chef-client/knife.rb

==> Builds finished but no artifacts were created.
```

**Comment by cbednarski** [comment]
Thanks for the report. From a glance, definitely looks like we should not be calling `sudo` on Windows. :)

**Comment by petewilcock** [comment]
Wait long enough and maybe the problem will fix itself on windows10 ;)

**Comment by petewilcock** [comment]
@cbednarski Will setting prevent_sudo fix this issue if set? The docs says this has no effect on windows, but it might have the side-effect of running the clean-up command without it, and thereby make it work?

**Comment by petewilcock** [comment]
Update: Can confirm workaround: Setting `prevent_sudo` (even though it's not supposed to do anything on Windows) will prevent the chef-client and chef-node cleanup commands being run with sudo and erroring out.

**Comment by cbednarski** [comment]
@petewilcock Thanks for posting a workaround. I think we recently started tracking the [guest OS in the config](https://www.packer.io/docs/provisioners/chef-solo.html#guest_os_type) so we should be able to do this automatically now.

**Comment by ldooks** [comment]
At risk of being a necromancer and reviving this issue, is there any devlopment on this issue? Getting the same issue

```
==> amazon-ebs: Cleaning up chef node...
    amazon-ebs: 'sudo' is not recognized as an internal or external command,
    amazon-ebs: operable program or batch file.
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.

Command: sudo knife node delete packernode -y -c C:/chef/knife.rb

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.

Command: sudo knife node delete packernode -y -c C:/chef/knife.rb

==> Builds finished but no artifacts were created.
```
