### ISSUE TITLE
Virtualbox builders: add option to disable exporting

### ISSUE THREAD

**Issue by vemv** [mitchellh/packer#3400]
### The problem

Sometimes I want Packer to run scripts over a Virtualbox image. That's all the result I want - without further images being created.
### Proposed solution

Add an option to not export anything. At the very least I need it for the Virtualbox ovf/iso builders, but this also might be a global option as it seems generally useful.
### Workaround

Delete the generated artifacts (maybe as a post-processor script). Note that building undersired artifacts unnecessarily slows down Packer builds .

**Comment by srse** [comment]
+1 . 

I would also like to tell the Virtualbox ovf builder (or again globally) not to shutdown, unregister and delete the VM after I finished provisioning with packer.

**Comment by srse** [comment]
@mitchellh any thoughts on this feature? It would really speed up my workflow of testing provisioning scripts on various target environments.

**Comment by alokhan** [comment]
I agree this would be a great feature :)

**Comment by mwhooker** [comment]
fixed #4339

**Comment by alokhan** [comment]
Great thanks
