### ISSUE TITLE
Option to overwrite existing image

### ISSUE THREAD

**Issue by phanect** [mitchellh/packer#3403]
I want option to overwrite existing image.

I use Google Cloud Platform and currently I run shell script something like:

```shell
gcloud compute images delete IMAGE_NAME
packer build packer.json
```

However, I sometimes run above script when there is already image created from the exact same packer.json and provisioner (Ansible) scripts.
I usually remind that I didn't have to recreate image after existing image is deleted. Even if I canceled the shell script, image is already deleted, and I have to run `packer build` again and wait for several minutes.

If Packer has something like `-overwrite` option and packer delete existing image just before it create image (just after all provisioner scripts finished), I don't have to delete image before running packer.
I can cancel the shell script when I run above script by mistake.

**Comment by cbednarski** [comment]
The [`-force` flag](https://www.packer.io/docs/command-line/build.html#_force) is meant to do this. Is it not working with GCE?

**Comment by phanect** [comment]
No, `-force` doesn't remove existing image. AFAIK it only removes local images for VMs.

```shell
$ packer build -force packer.json
googlecompute output will be in this color.

==> googlecompute: Checking image does not exist...
==> googlecompute: Image IMAGE_NAME already exists
Build 'googlecompute' errored: Image IMAGE_NAME already exists

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Image IMAGE_NAME already exists

==> Builds finished but no artifacts were created.
```

If my memory was correct, this was expected behavior, but I found #2993 and according to it this looks bug. I'm closing this and continue on #2993.
