### ISSUE TITLE
All AppVeyor builds are failing due to vendoring on GO 1.6

### ISSUE THREAD

**Issue by taliesins** [mitchellh/packer#3407]
Builds in AppVeyor are failing.

e.g. [https://ci.appveyor.com/project/hashicorp/packer/build/1248/job/07v0e4bbvlvic967](https://ci.appveyor.com/project/hashicorp/packer/build/1248/job/07v0e4bbvlvic967)

Output error:

> vendor\github.com\ActiveState\tail\cmd\gotail\gotail.go:8:2: cannot find package "github.com/hpcloud/tail" in any of:
>   c:\gopath\src\github.com\mitchellh\packer\vendor\github.com\hpcloud\tail (vendor tree)
>   c:\go\src\github.com\hpcloud\tail (from $GOROOT)
>   c:\gopath\src\github.com\hpcloud\tail (from $GOPATH)
> vendor\github.com\golang\protobuf\proto\proto3_proto\proto3.pb.go:19:8: cannot find package "github.com/golang/protobuf/proto/testdata" in any of:
>   c:\gopath\src\github.com\mitchellh\packer\vendor\github.com\golang\protobuf\proto\testdata (vendor tree)
>   c:\go\src\github.com\golang\protobuf\proto\testdata (from $GOROOT)
>   c:\gopath\src\github.com\golang\protobuf\proto\testdata (from $GOPATH)
> vendor\github.com\rackspace\gophercloud\acceptance\openstack\networking\v2\extensions\lbaas\common.go:7:2: cannot find package "github.com/rackspace/gophercloud/openstack/networking/v2/extensions/lbaas/monitors" in any of:
>   c:\gopath\src\github.com\mitchellh\packer\vendor\github.com\rackspace\gophercloud\openstack\networking\v2\extensions\lbaas\monitors (vendor tree)
>   c:\go\src\github.com\rackspace\gophercloud\openstack\networking\v2\extensions\lbaas\monitors (from $GOROOT)
>   c:\gopath\src\github.com\rackspace\gophercloud\openstack\networking\v2\extensions\lbaas\monitors (from $GOPATH)

I think this is due to vendoring in GO 1.6. We probably don't want to run all the vendors unit tests.

Current build uses:
`go test -v ./...`

Possible cross platform solution for igoring vendoring folder:
`go list ./... | grep -v /vendor/ | xargs -L1 go test -v`

**Comment by mwhooker** [comment]
looks like this is fixed https://ci.appveyor.com/project/hashicorp/packer

reopen if I'm wrong
