### ISSUE TITLE
docker: sudo: knife: command not found

### ISSUE THREAD

**Issue by lioramilbaum** [mitchellh/packer#3409]
Packer 0.10.0
OS - OS-X

Provisioner - chef-client
Builder - docker

The provisioner works fine with amazon-ebs builder. Now I want it work with docker.
But, I hit the next error:

     [exec] [1;32mdocker output will be in this color.[0m
     [exec] [1;32m==> docker: Creating a temporary directory for sharing data...[0m
     [exec] [1;32m==> docker: Pulling Docker image: ubuntu[0m
     [exec] [0;32m    docker: Using default tag: latest[0m
     [exec] [0;32m    docker: latest: Pulling from library/ubuntu[0m
     [exec] [0;32m    docker: 203137e8afd5: Pulling fs layer[0m
     [exec] [0;32m    docker: 2ff1bbbe9310: Pulling fs layer[0m
     [exec] [0;32m    docker: 933ae2486129: Pulling fs layer[0m
     [exec] [0;32m    docker: a3ed95caeb02: Pulling fs layer[0m
     [exec] [0;32m    docker: a3ed95caeb02: Waiting[0m
     [exec] [0;32m    docker: 933ae2486129: Verifying Checksum[0m
     [exec] [0;32m    docker: 933ae2486129: Download complete[0m
     [exec] [0;32m    docker: 2ff1bbbe9310: Verifying Checksum[0m
     [exec] [0;32m    docker: 2ff1bbbe9310: Download complete[0m
     [exec] [0;32m    docker: a3ed95caeb02: Verifying Checksum[0m
     [exec] [0;32m    docker: a3ed95caeb02: Download complete[0m
     [exec] [0;32m    docker: 203137e8afd5: Verifying Checksum[0m
     [exec] [0;32m    docker: 203137e8afd5: Download complete[0m
     [exec] [0;32m    docker: 203137e8afd5: Pull complete[0m
     [exec] [0;32m    docker: 203137e8afd5: Pull complete[0m
     [exec] [0;32m    docker: 2ff1bbbe9310: Pull complete[0m
     [exec] [0;32m    docker: 2ff1bbbe9310: Pull complete[0m
     [exec] [0;32m    docker: 933ae2486129: Pull complete[0m
     [exec] [0;32m    docker: 933ae2486129: Pull complete[0m
     [exec] [0;32m    docker: a3ed95caeb02: Pull complete[0m
     [exec] [0;32m    docker: a3ed95caeb02: Pull complete[0m
     [exec] [0;32m    docker: Digest: sha256:1bea66e185d3464fec1abda32ffaf2a11de69833cfcf81bd2b9a5be147776814[0m
     [exec] [0;32m    docker: Status: Downloaded newer image for ubuntu:latest[0m
     [exec] [1;32m==> docker: Starting docker container...[0m
     [exec] [0;32m    docker: Run command: docker run -v /Users/liora/.packer.d/tmp/packer-docker346571022:/packer-files -d -i -t ubuntu /bin/bash[0m
     [exec] [0;32m    docker: Container ID: 21b359656fe09e10bfb54bc9ed7d1a60c0ae90f61b3e42223845977aa6fba914[0m
     [exec] [1;32m==> docker: Provisioning with shell script: /var/folders/jc/9j09z7nj3zj0f0qtlf0r1klm0000gn/T/packer-shell534321937[0m
     [exec] [1;32m==> docker: Uploading /Users/liora/git/Galaxy/.chef/lmb-validator.pem => /tmp/packer-chef-client/lmb-validator.pem[0m
     [exec] [1;32m==> docker: Provisioning with shell script: /var/folders/jc/9j09z7nj3zj0f0qtlf0r1klm0000gn/T/packer-shell945632681[0m
     [exec] [1;32m==> docker: Uploading /Users/liora/git/Galaxy/.chef/lmb-validator.pem => /etc/chef/validation.pem[0m
     [exec] [1;32m==> docker: Provisioning with shell script: /var/folders/jc/9j09z7nj3zj0f0qtlf0r1klm0000gn/T/packer-shell170417769[0m
     [exec] [0;32m    docker: Installing Chef...[0m
     [exec] [0;32m    docker: curl -L https://www.chef.io/chef/install.sh | sudo bash[0m
     [exec] [0;32m    docker: Creating directory: /tmp/packer-chef-client[0m
     [exec] [0;32m    docker: Creating configuration file 'client.rb'[0m
     [exec] [0;32m    docker: Uploading /Users/liora/git/Galaxy/.chef/lmb-validator.pem...[0m
     [exec] [0;32m    docker: Creating JSON attribute file[0m
     [exec] [0;32m    docker: Executing Chef: sudo chef-client --no-color -c /tmp/packer-chef-client/client.rb -j /tmp/packer-chef-client/first-boot.json[0m
     [exec] [0;32m    docker: Creating configuration file 'knife.rb'[0m
     [exec] [1;32m==> docker: Cleaning up chef node...[0m
     [exec] [0;32m    docker: sudo: knife: command not found[0m
     [exec] [1;32m==> docker: Killing the container: 21b359656fe09e10bfb54bc9ed7d1a60c0ae90f61b3e42223845977aa6fba914[0m
     [exec] [1;31mBuild 'docker' errored: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.
     [exec] Command: sudo knife node delete packer-56fea394-abfb-9e1f-a652-e0bf7c332ecc -y -c /tmp/packer-chef-client/knife.rb[0m
     [exec] ==> Some builds didn't complete successfully and had errors:
     [exec] --> docker: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.
     [exec] Command: sudo knife node delete packer-56fea394-abfb-9e1f-a652-e0bf7c332ecc -y -c /tmp/packer-chef-client/knife.rb
     [exec] ==> Builds finished but no artifacts were created.

**Comment by lioramilbaum** [comment]
sudo was missing. Added the install as a shell provisioner.

Still hitting an error:

     [exec] [1;32mdocker output will be in this color.[0m
     [exec] [1;32m==> docker: Creating a temporary directory for sharing data...[0m
     [exec] [1;32m==> docker: Pulling Docker image: ubuntu:12.04[0m
     [exec] [0;32m    docker: 12.04: Pulling from library/ubuntu[0m
     [exec] [0;32m    docker: 6f8c221e4978: Already exists[0m
     [exec] [0;32m    docker: 2c2b3f3c7d41: Already exists[0m
     [exec] [0;32m    docker: 2bc6bba51fb8: Already exists[0m
     [exec] [0;32m    docker: a3ed95caeb02: Already exists[0m
     [exec] [0;32m    docker: Digest: sha256:b032172750d256ec49fa5113a838504f3ba8c40d63d4d47afce9c755e0d5762a[0m
     [exec] [0;32m    docker: Status: Image is up to date for ubuntu:12.04[0m
     [exec] [1;32m==> docker: Starting docker container...[0m
     [exec] [0;32m    docker: Run command: docker run -v /Users/liora/.packer.d/tmp/packer-docker083060957:/packer-files -d -i -t ubuntu:12.04 /bin/bash[0m
     [exec] [0;32m    docker: Container ID: 0fbb21c3d3956b07ea9b589bae116c25d4b7c6f488c3165715cc191030a6e26d[0m
     [exec] [1;32m==> docker: Provisioning with shell script: /var/folders/jc/9j09z7nj3zj0f0qtlf0r1klm0000gn/T/packer-shell949387571[0m
     [exec] [0;32m    docker: installing sudo[0m
     [exec] [0;32m    docker: Hit http://archive.ubuntu.com precise Release.gpg[0m
     [exec] [0;32m    docker: Get:1 http://archive.ubuntu.com precise-updates Release.gpg [198 B][0m
     [exec] [0;32m    docker: Get:2 http://archive.ubuntu.com precise-security Release.gpg [198 B][0m
     [exec] [0;32m    docker: Hit http://archive.ubuntu.com precise Release[0m
     [exec] [0;32m    docker: Get:3 http://archive.ubuntu.com precise-updates Release [55.4 kB][0m
     [exec] [0;32m    docker: Get:4 http://archive.ubuntu.com precise-security Release [55.5 kB][0m
     [exec] [0;32m    docker: Get:5 http://archive.ubuntu.com precise/main Sources [1175 kB][0m
     [exec] [0;32m    docker: Get:6 http://archive.ubuntu.com precise/restricted Sources [5306 B][0m
     [exec] [0;32m    docker: Get:7 http://archive.ubuntu.com precise/universe Sources [6239 kB][0m
     [exec] [0;32m    docker: Get:8 http://archive.ubuntu.com precise/main amd64 Packages [1640 kB][0m
     [exec] [0;32m    docker: Get:9 http://archive.ubuntu.com precise/restricted amd64 Packages [9098 B][0m
     [exec] [0;32m    docker: Get:10 http://archive.ubuntu.com precise/universe amd64 Packages [6167 kB][0m
     [exec] [0;32m    docker: Get:11 http://archive.ubuntu.com precise/main i386 Packages [1641 kB][0m
     [exec] [0;32m    docker: Get:12 http://archive.ubuntu.com precise/restricted i386 Packages [9108 B][0m
     [exec] [0;32m    docker: Get:13 http://archive.ubuntu.com precise/universe i386 Packages [6180 kB][0m
     [exec] [0;32m    docker: Get:14 http://archive.ubuntu.com precise-updates/main Sources [608 kB][0m
     [exec] [0;32m    docker: Get:15 http://archive.ubuntu.com precise-updates/restricted Sources [8938 B][0m
     [exec] [0;32m    docker: Get:16 http://archive.ubuntu.com precise-updates/universe Sources [153 kB][0m
     [exec] [0;32m    docker: Get:17 http://archive.ubuntu.com precise-updates/main amd64 Packages [1273 kB][0m
     [exec] [0;32m    docker: Get:18 http://archive.ubuntu.com precise-updates/restricted amd64 Packages [24.0 kB][0m
     [exec] [0;32m    docker: Get:19 http://archive.ubuntu.com precise-updates/universe amd64 Packages [351 kB][0m
     [exec] [0;32m    docker: Get:20 http://archive.ubuntu.com precise-updates/main i386 Packages [1351 kB][0m
     [exec] [0;32m    docker: Get:21 http://archive.ubuntu.com precise-updates/restricted i386 Packages [24.0 kB][0m
     [exec] [0;32m    docker: Get:22 http://archive.ubuntu.com precise-updates/universe i386 Packages [362 kB][0m
     [exec] [0;32m    docker: Get:23 http://archive.ubuntu.com precise-security/main Sources [178 kB][0m
     [exec] [0;32m    docker: Get:24 http://archive.ubuntu.com precise-security/restricted Sources [4320 B][0m
     [exec] [0;32m    docker: Get:25 http://archive.ubuntu.com precise-security/universe Sources [53.2 kB][0m
     [exec] [0;32m    docker: Get:26 http://archive.ubuntu.com precise-security/main amd64 Packages [772 kB][0m
     [exec] [0;32m    docker: Get:27 http://archive.ubuntu.com precise-security/restricted amd64 Packages [18.3 kB][0m
     [exec] [0;32m    docker: Get:28 http://archive.ubuntu.com precise-security/universe amd64 Packages [166 kB][0m
     [exec] [0;32m    docker: Get:29 http://archive.ubuntu.com precise-security/main i386 Packages [848 kB][0m
     [exec] [0;32m    docker: Get:30 http://archive.ubuntu.com precise-security/restricted i386 Packages [18.3 kB][0m
     [exec] [0;32m    docker: Get:31 http://archive.ubuntu.com precise-security/universe i386 Packages [175 kB][0m
     [exec] [0;32m    docker: Fetched 29.6 MB in 1min 29s (330 kB/s)[0m
     [exec] [0;32m    docker: Reading package lists...[0m
     [exec] [0;32m    docker: Reading package lists...[0m
     [exec] [0;32m    docker: Building dependency tree...[0m
     [exec] [0;32m    docker: Reading state information...[0m
     [exec] [0;32m    docker: The following NEW packages will be installed:[0m
     [exec] [0;32m    docker: sudo[0m
     [exec] [0;32m    docker: 0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.[0m
     [exec] [0;32m    docker: Need to get 288 kB of archives.[0m
     [exec] [0;32m    docker: After this operation, 1020 kB of additional disk space will be used.[0m
     [exec] [0;32m    docker: Get:1 http://archive.ubuntu.com/ubuntu/ precise-updates/main sudo amd64 1.8.3p1-1ubuntu3.7 [288 kB][0m
     [exec] [0;32m    docker: debconf: delaying package configuration, since apt-utils is not installed[0m
     [exec] [0;32m    docker: Fetched 288 kB in 2s (135 kB/s)[0m
     [exec] [0;32m    docker: Selecting previously unselected package sudo.[0m
     [exec] [0;32m    docker: (Reading database ... 7563 files and directories currently installed.)[0m
     [exec] [0;32m    docker: Unpacking sudo (from .../sudo_1.8.3p1-1ubuntu3.7_amd64.deb) ...[0m
     [exec] [0;32m    docker: Setting up sudo (1.8.3p1-1ubuntu3.7) ...[0m
     [exec] [0;32m    docker: done[0m
     [exec] [1;32m==> docker: Provisioning with shell script: /var/folders/jc/9j09z7nj3zj0f0qtlf0r1klm0000gn/T/packer-shell292136658[0m
     [exec] [0;32m    docker: creating chef/packer directories[0m
     [exec] [0;32m    docker: done[0m
     [exec] [1;32m==> docker: Uploading /Users/liora/git/Galaxy/.chef/lmb-validator.pem => /tmp/packer-chef-client/lmb-validator.pem[0m
     [exec] [1;32m==> docker: Provisioning with shell script: /var/folders/jc/9j09z7nj3zj0f0qtlf0r1klm0000gn/T/packer-shell517668429[0m
     [exec] [1;32m==> docker: Uploading /Users/liora/git/Galaxy/.chef/lmb-validator.pem => /etc/chef/validation.pem[0m
     [exec] [1;32m==> docker: Provisioning with shell script: /var/folders/jc/9j09z7nj3zj0f0qtlf0r1klm0000gn/T/packer-shell012978621[0m
     [exec] [0;32m    docker: Installing Chef...[0m
     [exec] [0;32m    docker: curl -L https://www.chef.io/chef/install.sh | sudo bash[0m
     [exec] [0;32m    docker: Creating directory: /tmp/packer-chef-client[0m
     [exec] [0;32m    docker: Creating configuration file 'client.rb'[0m
     [exec] [0;32m    docker: Uploading /Users/liora/git/Galaxy/.chef/lmb-validator.pem...[0m
     [exec] [0;32m    docker: Creating JSON attribute file[0m
     [exec] [0;32m    docker: Executing Chef: sudo chef-client --no-color -c /tmp/packer-chef-client/client.rb -j /tmp/packer-chef-client/first-boot.json[0m
     [exec] [0;32m    docker: Creating configuration file 'knife.rb'[0m
     [exec] [1;32m==> docker: Cleaning up chef node...[0m
     [exec] [1;32m==> docker: Killing the container: 0fbb21c3d3956b07ea9b589bae116c25d4b7c6f488c3165715cc191030a6e26d[0m
     [exec] [1;31mBuild 'docker' errored: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.
     [exec] Command: sudo knife node delete packer-56feafc4-26b9-0ec0-0833-b2031754b39e -y -c /tmp/packer-chef-client/knife.rb[0m
     [exec] ==> Some builds didn't complete successfully and had errors:
     [exec] --> docker: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.
     [exec] Command: sudo knife node delete packer-56feafc4-26b9-0ec0-0833-b2031754b39e -y -c /tmp/packer-chef-client/knife.rb
     [exec] ==> Builds finished but no artifacts were created.

**Comment by rickard-von-essen** [comment]
Include a minimal packer template to reproduce the error and run that template with debug logging enabled (`PACKER_LOG=1 packer build template.json`) and gist the output.

**Comment by cbednarski** [comment]
Typically you don't need to `sudo` inside of a docker container because you're already root, so you may need to change the `execute_command`.

Also it appears chef is not installed inside your container. I'm not sure how the automatic installer is supposed to work but it seems like something is going sideways there. For now you can substitute a shell provisioner to install chef before calling the chef provisioner. I'm not current on chef but I used to use the omnibus installer for this.

**Comment by lioramilbaum** [comment]
@rickard-von-essen 
Gist output - https://gist.github.com/lioramilbaum/25f984880d3c1b7f60bc0a1e81fe4ea9

@cbednarski - Packer is using the sudo command as part of the chef provisioner code. I am not sure I want it override its code.

**Comment by cbednarski** [comment]
@lioramilbaum That's why the option is there. I noticed there is also an option on the same page to change [install command](https://www.packer.io/docs/provisioners/chef-solo.html), which will probably solve the problem of chef / knife not getting automatically installed (because it also assumes `sudo` is present).

`sudo` is a common but it is not universal. Debian derivatives ship with `sudo` by default because they do not allow you to login as root. On Red Hat derivatives (and Docker) you typically just login as root so sudo is unnecessary. On non-linux systems like FreeBSD or Alpine or SmartOS there are other eccentricities. There's no need to be afraid of changing the settings to fit your platform. That's what the options are for! :)

If chef is actually installed but is missing from the path or is otherwise in a different location than usual (because of docker filesystem idiosyncrasies) you can specify the full path to chef your `execute_command`. If you run packer with `-debug` it should pause so you can `docker exec` your way into the container to see where knife is located.

**Comment by lioramilbaum** [comment]
Chris,
Those are my conclusions which I got them using your tips & tricks. Docker image ubuntu:12.04 was missing two packages: sudo and curl. After adding a shell provisioner which install those, all the reset went well.

Here is the code:
		{
			"type": "shell",
			"inline": [
				"echo 'Installing packages'",
				"apt-get update",
				"apt-get -y install sudo curl",
				"echo 'done'"
			]
		},

**Comment by cbednarski** [comment]
Awesome, glad you got this figured out! Thanks for sharing your solution.
