### ISSUE TITLE
azure-arm fails deploying (any) template

### ISSUE THREAD

**Issue by erinmez** [mitchellh/packer#3413]
Apologies for missing the obvious, but I might have stared too long at it to see the solution :) I have tried with Ubuntu (see below) as well as CoreOS, however, I always get the following error in the azure portal at step Microsoft.Compute/virtualMachines/write :

`statusCode:Conflict statusMessage:{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"ImageNotFound","message":"The platform image 'Canonical:UbuntuServer:14.04.4-LTS:latest' is not available. Verify that all fields in the storage profile are correct."}]}}
`

The image exists, however:
`azure vm image list -l centralus -p canonical -o UbuntuServer -k "14.04.4-LTS"`

Publisher | Offer | Sku | OS | Version | Location | Urn
-------------| ------- | ----- | ----- | --------- | ------------ | -----
canonical | UbuntuServer | 14.04.4-LTS | undefined | 14.04.201602220 | centralus | canonical:UbuntuServer:14.04.4-LTS:14.04.201602220
canonical | UbuntuServer | 14.04.4-LTS | undefined | 14.04.201603140 | centralus | canonical:UbuntuServer:14.04.4-LTS:14.04.201603140`

Versions:
packer version: 0.10.0
azure client version: 0.9.19 (node: 4.1.1)

I have followed the guide at https://www.packer.io/docs/builders/azure-setup.html and used the azure-setup.sh script to get started.

Debug log output (times are CET): 
https://gist.github.com/anonymous/837a89c91a7f0f3936e3809a9f253cec

Simplest template:
https://gist.github.com/anonymous/ea888d97287f0c48f56f448b46b825e5

**Comment by erinmez** [comment]
Found the root cause myself (apologies for any distraction). I was happily referencing Central US in my template, but failed to recognise that azure-setup.sh had created a storage account in the West US.

**Comment by cbednarski** [comment]
Thanks for following up! :)
