### ISSUE TITLE
ansible-local provisioner trying to copy folder that doesn't exist under playbook_dir

### ISSUE THREAD

**Issue by nwalke** [mitchellh/packer#3415]
Packer Version: 0.10.0
Host Platform: AWS
Debug log output: https://gist.github.com/nwalke/21d238e4eb0ba73349f47086b3be5ce3
Packer build template: https://gist.github.com/nwalke/2d37b22835c80672d9734a29832fc489

When I use the `ansible-local` provisioner with the `playbook_dir` option, Packer is looking for a `/vagrant` directory which doesn't exist.  The `playbook_dir` option that I have set in the linked above template follows the Ansible best practices directory layout: http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout

I wanted to just upload the whole thing because it contains everything I need.  I do have a `Vagrantfile` in that directory and I used to have a `.vagrant` directory inside that directory.  The Packer debug output doesn't show that it ever tries to copy a `/vagrant` directory, so I'm not sure where it would get that.

When I run a `grep -r "vagrant"` on my `playbook_dir`, I get the following:
```
./.gitignore:.vagrant
./Vagrantfile:      s.inline = "if [ ! -L /tmp/serverspec ]; then cd /tmp && ln -s /vagrant/serverspec .; fi"
./Vagrantfile:      s.inline = "if [ ! -L /tmp/serverspec ]; then cd /tmp && ln -s /vagrant/serverspec .; fi"
./Vagrantfile:      s.inline = "if [ ! -L /tmp/serverspec ]; then cd /tmp && ln -s /vagrant/serverspec .; fi"
```

Just to make sure I wasn't crazy, I also tried SCP'ing my `playbook_dir` manually to a remote machine and it went through just fine.

Any ideas where it could be getting `/vagrant` from?

**Comment by cbednarski** [comment]
I _suspect_ this is coming from one of the files included in your playbook.

> Build 'amazon-ebs' errored: Error uploading playbook_dir directory: lstat /vagrant: no such file or directory

When you run ansible locally all of the playbooks and paths are resolved on your computer relative to files on the host, not files on the remote VM. The way I read this is Packer is trying to upload `/vagrant` from your host to the remote VM, but can't find that path.

I would try running something like this to see where the errant directory include is coming from:

```
grep -R /vagrant ../../
```

**Comment by nwalke** [comment]
Right, I think I understand all of that.  If I run that grep from the directory that I run packer in, I get...
```
../..//ansible/Vagrantfile:      s.inline = "if [ ! -L /tmp/serverspec ]; then cd /tmp && ln -s /vagrant/serverspec .; fi"
../..//ansible/Vagrantfile:      s.inline = "if [ ! -L /tmp/serverspec ]; then cd /tmp && ln -s /vagrant/serverspec .; fi"
../..//ansible/Vagrantfile:      s.inline = "if [ ! -L /tmp/serverspec ]; then cd /tmp && ln -s /vagrant/serverspec .; fi"
```

Again, this is what I would expect since it's a vagrant file.

**Comment by cbednarski** [comment]
Ah! I have a theory: The Vagrantfile is ruby, so it's probably being hoovered up and evaluated along with your playbook. Try moving the Vagrantfile to a different folder (outside of ../..) and see if the problem goes away.

**Comment by nwalke** [comment]
This was caused by having a symlink in my serverspec directory that I must have set in my vagrant machine to point to `/vagrant`.  Derp.

Thanks for the help.

**Comment by cbednarski** [comment]
Glad you got it figured out!
