### ISSUE TITLE
after ansible-local the AMI done successful but cant access to the AMI 

### ISSUE THREAD

**Issue by noamgr** [mitchellh/packer#3416]
i run the packer and its working fine and finish fine 
i create new EC2 from this AMI and cant access 

```
    {
       "type": "ansible-local",
       "playbook_file": "ansible/presence_all_env_install.yml",
       "role_paths": [
         "ansible/roles/presence"
      ]
    }
  ]
```

any one have idea ? ?? ? 
how can i create generic AMI after i run ansible and use ant key-pair i want ( i have sevral account in AWS ) 

Tnaks

**Comment by cbednarski** [comment]
EC2 instances use cloud-init to install keys on the machine when it is started. Whenever you spin up an instance from an AMI you are required to specify the key you want to use to login to the machine. When the machine boots, cloud-init will pull down the key and install it so you can login.

Typically this process happens automatically and if you start your build from one of the community AMIs (Amazon Linux or Ubuntu, for example) cloud-init should already be setup. Make sure your Ansible provisioners do not remove cloud-init or the AMI will not work when you share it.

You can read more about this process here: [Building Shared AMIs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/building-shared-amis.html)

**Comment by noamgr** [comment]
Hi thanks for the answer just to be clear 
i run the ansible in the packer build so its look like this 

   "provisioners": [
    {
       "type": "ansible-local",
       "playbook_file": "ansible/presence_all_env_install.yml",
       "role_paths": [
         "ansible/roles/presence"
      ]
    }
  ]
}

and in the ansible i am doing a some change in the cloud-init ... 
- name: static hostname to a private Amazon EC2
  sudo: true
  lineinfile: dest=/etc/cloud/cloud.cfg  state=present  line="preserve_hostname:true" insertafter=EOF

so my Q is do you think this can make the issue i get ? 
or i missing something 

Thx

**Comment by cbednarski** [comment]
> in the ansible i am doing a some change in the cloud-init ...

Unfortunately I can't help you troubleshoot cloud-init or your Ansible playbooks. You might try asking for help with cloud-init or ansible through their community resources. Good luck!

**Comment by noamgr** [comment]
after i remove the cloud-init all working ... so i think this was the problem in any case thanks for the help it  :)
