### ISSUE TITLE
Error creating disk

### ISSUE THREAD

**Issue by VsegdaZhivoj** [mitchellh/packer#3420]
Packer version: 0.10.0
Host platform: Ubuntu 14.04.3
Log: https://gist.github.com/VsegdaZhivoj/bd3eef876ea744bb72ca66dba47700ed
Template: https://gist.github.com/VsegdaZhivoj/959de75c76e3d9f584b1d11353bdfcf7

I built vmware-iso (ubuntu) on vmware hypervisor. Packer try to enter "vmkfstools -c 4096M -d 1 -a lsilogic /vmfs/volumes/datastore1/output-hyperhive/disk.vmdk", but get "Incorrect disk option "1""

**Comment by rickard-von-essen** [comment]
Full log please and version info for you VMware software.

**Comment by VsegdaZhivoj** [comment]
I corrected this in my template. Disk type for ESXi is not integer. Key "disk_type_id" must be zeroedthick, eagerzeroedthick, or thin.

**Comment by rickard-von-essen** [comment]
Close?
