### ISSUE TITLE
packer build -debug not responding

### ISSUE THREAD

**Issue by PurrBiscuit** [mitchellh/packer#3426]
- Packer Version: 0.10.0
- Host platform: OS X El Capitan (Version 10.11.3)
- Debug log output from `PACKER_LOG=1 packer build -debug -var-file=vars/app_1 chef-windows-ami.json` and my vars file and packer template example: https://gist.github.com/PurrBiscuit/a49cca93525a3d26271e2c02404c95ae

Since upgrading to packer version 0.9.0 and 0.10.0, the `packer build -debug` flag seems to be unresponsive to pressing Enter to continue.  It just hangs and won't continue.  running `packer build` seems to work fine however.

**Comment by cbednarski** [comment]
Thanks for the report. This is fixed in master. https://github.com/mitchellh/packer/issues/3250

**Comment by PurrBiscuit** [comment]
ah, i didnt see that issue filed already.  thanks for the quick response!
