### ISSUE TITLE
Ignore boot partition when using GPT

### ISSUE THREAD

**Issue by stumyp** [mitchellh/packer#3430]
I'm using amazon-chroot provisioner and if source root volume from source AMI is using GPT table (as oppose to msdos partitions) packer is trying to use first partition anyway, which is usually *boot* partition.
I suggest ignoring boot partition and pick next available partition instead of failing.

(P.S. I'm aware that I can specify partition number in template file, so this is only a suggestion)

**Comment by cbednarski** [comment]
Thanks for the suggestion. It sounds like there's a straightforward way to do this so I do not plan to implement this myself, but if you'd like to take a stab at it I'd be happy to review your PR. Thanks!
