### ISSUE TITLE
qemu: Provisioner changes discarded (unless I SSH during the build process in debug mode)

### ISSUE THREAD

**Issue by hjfreyer** [mitchellh/packer#3432]
I'm trying the simplest possible thing: touching a file in a provisioner. I see the script run as part of the build process, but when I run the machine afterwards with `kvm -m 512 -redir :8090::80 -redir :8022::22 output-qemu/packer-qemu --nographic`, the changes aren't there. Same story with -debug. But if I run with -debug _and_ SSH into the machine after the script runs (but before building is finished), the changes are present. Then once the build has finished, if I start the machine again and SSH the file is still there! The definition of a heisenbug.

At this point I've pretty much given up, but I figured y'all should know. Unfortunately the base image I'm working from is more than I'd like to upload right now, but it was created using a modified version of (this)[https://github.com/shiguredo/packer-templates/blob/develop/ubuntu-14.04/template.json] to run on qemu.
- Packer Version
  $ ../packer --version
  0.10.0
- Host platform
  $ cat /etc/issue
  Ubuntu 14.04.3 LTS \n \l
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/hjfreyer/4d9c1129d4724647e198b6ca3581b5b4
- The _simplest example template and scripts_ needed to reproduce the bug.
  https://gist.github.com/hjfreyer/65b1e5d8422991ba20cb4d945999cadf

**Comment by cbednarski** [comment]
Thanks for the report. It sounds like there is an fsync problem inside your VM. I'm curious if running `fsync` in your final provisioner would solve this problem. Possibly starting a new ssh session has the side-effect of forcing fsync in order to read keys / initialize the bash session.

**Comment by mwhooker** [comment]
going to close since we're still waiting for a response.

If you're still having an issue, please open a new ticket with the result of running `fsync`.

We also can't reproduce with a local `iso_url`, so we can't reproduce
