### ISSUE TITLE
virtualbox-iso builder ignores ssh_private_key_file if ssh_key_path not set

### ISSUE THREAD

**Issue by t2d** [mitchellh/packer#3435]
The virtualbox-iso builder does not use the `ssh_private_key` for authentication, if `ssh_key_path` is not set. However ,`ssh_key_path` is not documented in https://www.packer.io/docs/builders/virtualbox-iso.html
- Packer Version: 0.10.0
- Host platform: Ubuntu 15.10
- Debug log output from `PACKER_LOG=1 packer build template.json`.

```
2016/04/13 13:11:33 ui error: ==> virtualbox-iso: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
==> virtualbox-iso: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

It works with the following config:

```
      "ssh_username": "root",
      "ssh_private_key_file": "packer/id_rsa",
      "ssh_key_path": "packer/id_rsa",
```

I found the `ssh_key_path` option from the connected issue #2428 .

**Comment by rickard-von-essen** [comment]
Please attach a debug log and template to reproduce this.

**Comment by t2d** [comment]
template:
```
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "guest_os_type": "Ubuntu_64",
      "iso_url": "dc01nix4rls.nix4.rls.io.iso",
      "iso_checksum_type": "none",
      "ssh_username": "root",
      "ssh_private_key_file": "packer/id_rsa",
      "ssh_wait_timeout": "500s",
      "boot_command": "<enter>",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
    }
  ]
}
```
PACKER_LOG: https://gist.github.com/t2d/253697ac898efc59eb273645b1c386ca

**Comment by mwhooker** [comment]
This should be fixed, now. please open another issue if you continue to see this
