### ISSUE TITLE
packer validate should give warning for undefined user variables

### ISSUE THREAD

**Issue by johnLate** [mitchellh/packer#3439]
Feature Request

`packer validate foo.json` should issue a warning if the template contains `{{user `bar`}}` but `bar` is not in `variables`. (To avoid a warning, the variable could be defined with empty default.)

I misspelled a variable name in my template (see: https://gist.github.com/johnLate/d9f532b984d7dee5c7956109f11fde44). Validate returned "Template validated successfully.". The build failed. I wasted a lot of time debugging before realizing my error.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but isn't something we're targeting for 1.0, so I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
