### ISSUE TITLE
packer errors if you have 100 provisioners

### ISSUE THREAD

**Issue by trodemaster** [mitchellh/packer#3440]
While doing some testing for a winrm issue I ran into this issue. When trying to build or validate a template with 100 provisioners packer gives this error. If there is a limit of provisioners maybe throw a nice error and report what the limit is. 

packer validate ~/Desktop/tooManyProvisioners.json 
Failed to initialize build 'vmware-vmx': error initializing provisioner 'powershell': fork/exec /files/go/bin/packer: too many open files

Packer v0.10.1.dev (b50036c817a36094cbead945f73159d3c49ccaea)

Example template.json 
https://gist.github.com/trodemaster/91c951ec6cb3e4fbadf2a462b3299049

Debug log
https://gist.github.com/trodemaster/4f52e34eab73c321bbaab685999e9bb9

**Comment by cbednarski** [comment]
That's a lot of provisioners! Thanks for reporting. This seems strangely arbitrary so I'm guessing is not a hard limit and is more a side-effect of something else (e.g. exhausting a port range or similar).

**Comment by cbednarski** [comment]
Found this in the log:
> error initializing provisioner 'powershell': fork/exec /files/go/bin/packer: too many open files

So maybe we need to trigger GC on some file handles.

**Comment by rickard-von-essen** [comment]
What is the output of: `ulimit -n`. A workaround should be to increase this limit.

**Comment by trodemaster** [comment]
Just checked to see if this is still an issue. Packer v0.11.1.dev (3c0e5a10eccf7c3ecbf840fb1062b5d1718e3500)

2016/10/30 16:28:44 ui error: Failed to initialize build 'vmware-vmx': error initializing provisioner 'powershell': fork/exec /files/go/bin/packer: too many open files

https://gist.github.com/trodemaster/22782beee585d1eea3c6ba0803b62349

ulimit is 256 on this system. If I hit this in real world bumping the ulimit is an option.
