### ISSUE TITLE
Second network interface doesn't show up in vagrant (virtualbox-iso)

### ISSUE THREAD

**Issue by t2d** [mitchellh/packer#3442]
I want to build a vagrant box with a second network interface. Therefore, my builder looks like:
```
{
  "variables": {
        "vm_name": "test"
  },
  "builders": [
    {
      "type": "virtualbox-iso",
      "guest_os_type": "Ubuntu_64",
      "headless": true,
      "vm_name": "{{user `vm_name`}}",
      "vboxmanage": [
        ["modifyvm", "{{.Name}}", "--nic2", "nat"],
        ["modifyvm", "{{.Name}}", "--cableconnected2", "on"]
      ],
      "vboxmanage_post": [
        ["modifyvm", "{{.Name}}", "--nic2", "nat"],
        ["modifyvm", "{{.Name}}", "--cableconnected2", "on"]
      ],
      "iso_url": "test.iso",
      "iso_checksum_type": "none",
      "boot_command": "<enter>",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
    }
  ],
  "post-processors": [
    [
      {
        "type": "vagrant",
        "keep_input_artifact": false,
        "output": "{{ user `vm_name` }}.box"
      }
    ]
  ]
}
```
During the building process, the second interface is visible in VirtualBox.
However, when I import the box with vagrant and start it, there is no second network interface.
Is this a feature or a bug? Am I supposed to add the interface again in `Vagrantfile`?

- Packer Version: 0.10.0
- Host platform: Ubuntu 15.10

**Comment by rickard-von-essen** [comment]
Use `vagrantfile_template` to configure your extra NIC, see https://www.packer.io/docs/post-processors/vagrant.html#vagrantfile_template

**Comment by t2d** [comment]
okay, so this is on purpose. thank you very much.

**Comment by tersmitten** [comment]
@t2d Do you have an example?

**Comment by t2d** [comment]
@tersmitten I'm using it like this:
packer file
```
"post-processors": [
  [
    {
      "type": "vagrant",
      "vagrantfile_template": "Vagrantfile",
      "output": "{{ user `vm_name` }}.box"
    }
  ]
```
Vagrantfile
```
config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--cpus", "2"]   
    vb.customize ["modifyvm", :id, "--nic2", "nat"]
```

**Comment by dhpa1982** [comment]
@t2d also may I ask is it required to add the nic twice in the builder template via 'vboxmanage' and 'vboxmanage_post'?

**Comment by t2d** [comment]
@dhpa1982 no, it's not.
