### ISSUE TITLE
Pull Provisioner Console Logs (GUID.out files) Back from Remote

### ISSUE THREAD

**Issue by DarwinJS** [mitchellh/packer#3445]
I am building windows boxes on AWS and have the ebs volume "delete_on_termination" set to false so after a failed build I can [a] attach the volume, [b] boot an instance, [c] look at it's logs, [d] shutdown the instance, [e] detach the volume, [f] manually delete the volume.

I noticed the c:\windows\temp\<guid>.out files contain the console output of powershell provisioners I run.

Getting this output is the only reason I have to take all these extra steps to get this information.

Would be great if Packer supported something like  PACKER_CONSOLE_LOGS_COPY=$env:temp so that those logs could always be brought back (especially the last one that failed) and I could avoid the extra steps.

**Comment by cbednarski** [comment]
Thanks for opening an issue. There is an open request to [support leaving artifacts intact after a failed build](https://github.com/mitchellh/packer/issues/409). We also have [-debug](https://www.packer.io/docs/other/debugging.html) mode which allows you to step through the build process and inspect the VM state at various points. Does either of those satisfy your use case here?

**Comment by DarwinJS** [comment]
Yes - I think especially the suggestion for --pause-on-error.
Thanks!

**Comment by cbednarski** [comment]
Great! I'm going to close this one since we have an issue open already, but I will include your feedback in the other thread.
