### ISSUE TITLE
Allow variable log masking for custom variables

### ISSUE THREAD

**Issue by DarwinJS** [mitchellh/packer#3447]
aws_access_key and aws_secret_key are masked in log files.

I have other credentials I need to use in packer and would like to be able to mask them as well.

**Comment by cbednarski** [comment]
Thanks for opening an issue. The masks are hard-coded so we would need to expose a config or additional heuristic for these. Can you share what types of secrets you want to mask? If there is a particular format (private key, etc.) we can do this automatically.

**Comment by DarwinJS** [comment]
SQL SA Password, passwords to logon to a remote box for large setup files, credentials for elevated packer jobs, credentials for NuGet repo containing main Chocolatey and code deploy NuGet packages

How about any variable name that contains a specific string (or starts or ends with a string if "contains" is too broad)?

e.g secret_SQLSA_Password, elevateduser_password_secret

**Comment by cbednarski** [comment]
Ah that makes sense. I think using the key name as a heuristic is a great idea. I think we can also support some additional configuration syntax to mark certain variables as private. This is not a trivial change but I think we can support this as part of our work to bring HCL into Packer.

**Comment by DarwinJS** [comment]
Cool.  I would probably encourage not too may aliases as it could get confusing.  Would advocate verbose information in the log indicating *exactly why* the variable is being masked.

Maybe in the logs:
Variable "SQLPassword_Secret" is being masked (because the variable name contains the text "secret")

**Comment by DarwinJS** [comment]
Hmmmm - maybe explicit logging is not such a great idea.  I might have a thycotic server setup where even most admins don't know what the password is that is being passed.  They may be able to change the variable name, enable verbose logging and get creds they don't normally have.

**Comment by cbednarski** [comment]
> Hmmmm - maybe explicit logging is not such a great idea.

We already do this for secrets like Atlas credentials and AWS keys. If mentioning the existence of a secret in a log violates your threat model I think the problem lies elsewhere from Packer. For instance in the scenario you describe I have setup isolated build environments which only I have access to.

**Comment by DarwinJS** [comment]
I would like to offer that:

- Complex environments with many levels of admins may not be able to keep the build environment itself that segregated.
- It is a notable and necessary security principle to consider attacks from within.

But having the secrets protected in the logs would be awesome regardless of what you choose to do with this suggested detail - as it would be possible for a potential attacker to google "packer secrets" and discover the method anyway.

**Comment by mwhooker** [comment]
just spit-balling here. What if we introduce a e.g. `-quiet` flag which just blanket filters out any value set in the variables section? There are many issues with trying to be clever about the variable names as described already.

In the future, should packer move to HCL, I could imagine decorating the variable with privacy scope information, but that's not something that'll happen in the near future

**Comment by mwhooker** [comment]
If anyone would like to submit a PR for this, I'd be happy to look at it. In the mean time, this is not something we're going to support in packer core for now. 

I think a viable solution would be to use a program between packer stdout and the destination log file to filter out sensitive information.
