### ISSUE TITLE
Virtualbox: Unable to build without X

### ISSUE THREAD

**Issue by timvisher** [mitchellh/packer#3450]
I'm unable to build images on a box using one user while on the same box with the same template the build succeeds. This only matters because the user than can't build images is the jenkins slave user and thus is the user that needs to be able to build the images.

I'd say this was a problem with VirtualBox except that vagrant can successfully launch boxes under the same account. It's only packer that is presenting this problem.

- Packer Version: `0.10.0`
- Host platform: `Linux 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- Debug log output from `PACKER_LOG=1 packer build template.json`.: https://gist.github.com/765c79656ea13c7f3c851214c12b6c28
- The _simplest example template and scripts_ needed to reproduce the bug.
  See:
    - https://github.com/chef/bento/blob/9b7dcda32c23c9c30e7bc4308c025ead5bf1a733/debian-8.4-amd64.json
    - https://github.com/chef/bento/blob/9b7dcda32c23c9c30e7bc4308c025ead5bf1a733/ubuntu-14.04-amd64.json

**Comment by timvisher** [comment]
I tried to create a simple test VM via the gui and start it and got a similar error:

```
$ VBoxManage startvm test
Waiting for VM "test" to power on...
VBoxManage: error: The virtual machine 'test' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

--------------------------

Ah ha! https://www.virtualbox.org/ticket/7367

This actually might be the problem. There actually is no gui available for this user (it's running a headless session).

How do others run packer via jenkins etc.? in an x session?

**Comment by rickard-von-essen** [comment]
Did you try `"headless": "true"` ? (Your gist runs with `--type gui`) if that doesn't work you can always run with [Xvfb](http://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml), there is a [Jenkins plugin for that](https://wiki.jenkins-ci.org/display/JENKINS/Xvfb+Plugin).

**Comment by timvisher** [comment]
💥 That was it. I'm gong to leave this open unless you think there's no better way that Packer could report this sort of issue.

**Comment by cbednarski** [comment]
Unfortunately, I'm not sure `NS_ERROR_FAILURE (0x80004005)` is specific enough for us to identify the problem, as there are potentially a few other reasons you might get this error. I'm glad you got this sorted, though! Thanks for following up.

**Comment by vladionescu** [comment]
I also encountered this. Perhaps a more prominent note about running in headless mode is warranted in the intro documentation? I did eventually find the headless config variable for virtualbox-iso builder after seeing this issue.
