### ISSUE TITLE
Build 'azure-arm' errored: unexpected EOF

### ISSUE THREAD

**Issue by rarsan** [mitchellh/packer#3456]
- Packer Version: 0.10.0
- Host platform: OS X 10.11.3
- Crash log from `packer build -only=azure-arm template.json`:
https://gist.github.com/rarsan/76fd0c0033844e5067466d26fb07e933

Snippet:
```
2016/04/18 18:21:25 packer: 	/private/tmp/packer20160405-28622-29ix7y/src/github.com/mitchellh/packer/builder/azure/arm/builder.go:90 +0xcb9
2016/04/18 18:21:25 packer: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc820246820, 0x1, 0xc8202d4540, 0x0, 0x0)
2016/04/18 18:21:25 packer: 	/private/tmp/packer20160405-28622-29ix7y/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x3b9
2016/04/18 18:21:25 packer: reflect.Value.call(0xd8d720, 0xefc0b8, 0x13, 0x10d2438, 0x4, 0xc82061fed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:435 +0x120d
2016/04/18 18:21:25 packer: reflect.Value.Call(0xd8d720, 0xefc0b8, 0x13, 0xc82061fed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:303 +0xb1
2016/04/18 18:21:25 packer: net/rpc.(*service).call(0xc820143e00, 0xc820143dc0, 0xc8202415b8, 0xc82014b100, 0xc820246b00, 0xbe44c0, 0xc8202d44ec, 0x18a, 0xbad340, 0xc8202d4540, ...)
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:383 +0x1c2
2016/04/18 18:21:25 packer: created by net/rpc.(*Server).ServeCodec
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:477 +0x49d
2016/04/18 18:21:25 ui error: Build 'azure-arm' errored: unexpected EOF
```

**Comment by boumenot** [comment]
Thank you for reporting, and including all of the details.

@cbednarski, does this stack trace ring a bell for you at all?  It explodes on

**Comment by cbednarski** [comment]
@boumenot I don't think I've seen this one. Error happens here, so I would guess something is not coming back from the API and we are not checking the error:

```
2016/04/18 18:17:59 ui: [1;32m==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-wh5f76j67m'[0m
2016/04/18 18:21:25 packer: panic: runtime error: invalid memory address or nil pointer dereference
2016/04/18 18:21:25 packer: [signal 0xb code=0x1 addr=0x10 pc=0xa23ce1]
```

**Comment by boumenot** [comment]
@cbednarsk I thought that too, but if you follow the gist the panic is when the Azure builder is cleaning up and deleting the resource group.

2016/04/18 18:17:59 ui: [1;32m==> azure-arm: Deleting resource group ...[0m
2016/04/18 18:17:59 ui: [1;32m==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-wh5f76j67m'[0m
2016/04/18 18:21:25 packer: panic: runtime error: invalid memory address or nil pointer dereference
2016/04/18 18:21:25 packer: [signal 0xb code=0x1 addr=0x10 pc=0xa23ce1]
2016/04/18 18:21:25 packer: 
2016/04/18 18:21:25 packer: goroutine 7 [running]:
2016/04/18 18:21:25 packer: panic(0xe60bc0, 0xc820010170)
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2016/04/18 18:21:25 packer: github.com/mitchellh/packer/vendor/github.com/Azure/go-autorest/autorest.ResponseRequiresPolling(0x0, 0x0, 0x0, 0x0, 0xc820324000)
2016/04/18 18:21:25 packer: 	/private/tmp/packer20160405-28622-29ix7y/src/github.com/mitchellh/packer/vendor/github.com/Azure/go-autorest/autorest/autorest.go:82 +0x21

It appears to be an issue in go-autorest/azure-sdk-for-go.  I've pinged the devs with the stack trace to see if they're familiar with the issue.  I know there have been polling issues in the past, but I cannot ascribe this instance to a specific issue.

**Comment by boumenot** [comment]
I checked with the team on this issue, and they asked that I upgrade to the latest release of go-autorest and azure-sdk-for-go.  They have done quite a bit of work on polling, and they would like to see if that fixes the issue first before debugging this further.

I have submitted PR #3461, which pulls in the latest releases of these packages.  (It has many other fixes too, which are generally useful.)  Once the PR is accepted, I am going to close this issue.  Please reopen if you encounter the failure again.

**Comment by boumenot** [comment]
PR has been merged, closing.
