### ISSUE TITLE
packer sets ANSIBLE_FORCE_COLOR=1 even when -color=false

### ISSUE THREAD

**Issue by 72squared** [mitchellh/packer#3484]
Describe the problem and include the following information:
- Packer Version: 0.9.0
- Host platform: tested on mac os X and ubuntu

```
packer build -color=false packer-dev.json
```

In the output I see:

```
amazon-ebs: Executing Ansible: cd /tmp/packer-provisioner-ansible-local && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/packer-dev.yml -e inventory_group=dev -c local -i /tmp/packer-provisioner-ansible-local/packer-provisioner-ansible-local788810739
```

I would expect ANSIBLE_NOCOLOR=1 to be present instead when passing -color=false to packer.

**Comment by bhcleek** [comment]
@cbednarski this has the provisioner/ansible-remote label, but the output indicates it's the ansible-local provisioner.

**Comment by rickard-von-essen** [comment]
@bhcleek fixed labels.

**Comment by mwhooker** [comment]
I think the best way to solve this is through documentation.

I agree that the behavior is inconsistent, but `-color` is more for controlling the packer UI, not the processes packer runs.
