### ISSUE TITLE
Unable to build Ubuntu 16.04 image using AWS EBS provisioner

### ISSUE THREAD

**Issue by mixja** [mitchellh/packer#3489]
- Packer 0.10.0
- OS X El Capitan 10.11.4
- See https://gist.github.com/mixja/2a581e1ad92ffcdb79c830aa2b9dfee1

I have manually created an instance from same source AMI (ami-fa82739a) and I am able to run commands successfully.  I notice that the wrong Ubuntu apt mirrors are being used in the packer setup, whereas the AWS apt mirrors are used from manual instance.

This configuration works fine with Ubuntu 15.10.

**Comment by cbednarski** [comment]
I think `dist-upgrade` rewrites all of the apt URLs. In any case you probably shouldn't use `dist-upgrade` on AWS; just start from a base VM that has the right distro version.

**Comment by mixja** [comment]
I already tried without dist-upgrade and had the same result but I'll try again and advise

**Comment by mixja** [comment]
A new AMI is available (ami-a5416cc6) and it works, even with `apt-get dist-upgrade` so this may have been an Ubuntu AMI issue.

**Comment by mixja** [comment]
Sorry, after running this a few more times, I'm seeing intermittent failures with the new AMI, behaving occasionally as I originally reported.
