### ISSUE TITLE
Packer crash: unexpected EOF, interface conversion panic

### ISSUE THREAD

**Issue by danopia** [mitchellh/packer#3496]
This happened one time so far. Prior and subsequent builds have been fine but any straight-up panic is cause for concern. Haven't been able to find a matching issue, just other "unexpected EOF" tickets from other situations.

Relevant snippet from log:

```
2016/05/03 21:54:11 Waiting on builds to complete...
2016/05/03 21:54:11 Starting build run: amazon-ebs
2016/05/03 21:54:11 Running builder: amazon-ebs
2016/05/03 21:54:11 ui: ==> amazon-ebs: Prevalidating AMI Name...
2016/05/03 21:54:26 ui: ==> amazon-ebs: Inspecting the source AMI...
2016/05/03 21:54:26 ui: ==> amazon-ebs: Creating temporary keypair: packer 67291e03-e838-bc89-57c4-9e02ce671d61
2016/05/03 21:54:26 packer: 2016/05/03 21:54:26 Using specified security groups: [sg-redacted]
2016/05/03 21:54:26 ui: ==> amazon-ebs: Launching a source AWS instance...
2016/05/03 21:54:26 ui:     amazon-ebs: Instance ID: i-d776985d
2016/05/03 21:54:26 ui: ==> amazon-ebs: Waiting for instance (i-d776985d) to become ready...
2016/05/03 21:54:26 packer: 2016/05/03 21:54:26 Waiting for state to become: running
2016/05/03 21:54:26 packer: 2016/05/03 21:54:26 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
2016/05/03 21:55:04 packer: 2016/05/03 21:55:04 [INFO] Not using winrm communicator, skipping get password...
2016/05/03 21:55:04 packer: 2016/05/03 21:55:04 [INFO] Waiting for SSH, up to timeout: 5m0s
2016/05/03 21:55:04 ui: ==> amazon-ebs: Waiting for SSH to become available...
2016/05/03 21:55:06 packer: panic: interface conversion: interface {} is **ec2.Instance, not *ec2.Instance
2016/05/03 21:55:06 packer: 
2016/05/03 21:55:06 packer: goroutine 199 [running]:
2016/05/03 21:55:06 packer: panic(0x11b4100, 0xc8205f86c0)
2016/05/03 21:55:06 packer: 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
2016/05/03 21:55:06 packer: github.com/mitchellh/packer/builder/amazon/common.SSHHost.func1(0x7fb3716402a8, 0xc820452b70, 0x0, 0x0, 0x0, 0x0)
2016/05/03 21:55:06 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/builder/amazon/common/ssh.go:19 +0x70d
2016/05/03 21:55:06 packer: github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).waitForSSH(0xc82033df40, 0x7fb3716402a8, 0xc820452b70, 0xc820011620, 0x0, 0x0, 0x0, 0x0)
2016/05/03 21:55:06 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:119 +0x6e9
2016/05/03 21:55:06 packer: github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).Run.func1(0x7fb37163fd48, 0xc8204acfa0, 0xc8202a3bb0, 0xc8202a3bc0, 0xc82033df40, 0x7fb3716402a8, 0xc820452b70, 0xc820011620, 0xc8201d7dc0)
2016/05/03 21:55:06 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:39 +0x78
2016/05/03 21:55:06 packer: created by github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).Run
2016/05/03 21:55:06 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:41 +0x1c0
2016/05/03 21:55:06 ui error: Build 'amazon-ebs' errored: unexpected EOF
2016/05/03 21:55:06 /usr/bin/packer: plugin process exited
2016/05/03 21:55:06 Builds completed. Waiting on interrupt barrier...
2016/05/03 21:55:06 machine readable: error-count []string{"1"}
2016/05/03 21:55:06 ui error: 
==> Some builds didn't complete successfully and had errors:
2016/05/03 21:55:06 machine readable: amazon-ebs,error []string{"unexpected EOF"}
2016/05/03 21:55:06 ui error: --> amazon-ebs: unexpected EOF
2016/05/03 21:55:06 ui: 
==> Builds finished but no artifacts were created.
2016/05/03 21:55:06 waiting for all plugin processes to complete...
2016/05/03 21:55:06 /usr/bin/packer-post-processor-ami-file: plugin process exited
2016/05/03 21:55:06 /usr/bin/packer: plugin process exited
```

Packer 0.9.0 on Ubuntu 14.04.3

**Comment by cbednarski** [comment]
Thanks for the report. Are you using an official build from releases.hashicorp.com or did you build this yourself / from homebrew?

**Comment by danopia** [comment]
Packer was installed from https://releases.hashicorp.com/packer/0.9.0/packer_0.9.0_linux_amd64.zip

I do have this custom post processor: https://github.com/scopely/packer-post-processor-ami-file  
But it's _extremely_ simple and hasn't caused problems in the 10 months I've had it.

**Comment by cbednarski** [comment]
Thanks for providing the extra info. Since the crash is happening in the `amazon-ebs` builder which should happen before the post-processor stage I think the other piece is unrelated. I just wanted to make sure that you are using the same version of the AWS SDK so I can repro this.

It's likely a programming error on our side but I have also seen this type of error where the AWS SDK has changed their interface, and updating to the latest version causes a problem -- just wanted to pre-emptively rule that out.

**Comment by danopia** [comment]
Yea, I've had problems with the aws-sdk making changes before. This case is just really weird because it's the first time it has happened in 10 months. Perhaps it's bitrotted error handling for a normally-solid API call.

The typeassert that paniced looks pretty innocent, and certainly not finicky: [ssh.go:19](https://github.com/mitchellh/packer/blob/v0.9.0/builder/amazon/common/ssh.go#L19). Especially since [instance is put in the state bag](https://github.com/mitchellh/packer/blob/v0.9.0/builder/amazon/common/step_run_source_instance.go#L290) after being [type-asserted to the proper type](https://github.com/mitchellh/packer/blob/v0.9.0/builder/amazon/common/step_run_source_instance.go#L259).

[This line looks suspicious](https://github.com/mitchellh/packer/blob/v0.9.0/builder/amazon/common/ssh.go#L45). Seems like it hits when the instance didn't have an IP address immediately. `Instances` is a `[]*Instance` so taking a pointer to the first item results in a double-pointer, which is what the panic mentioned.

**Comment by cbednarski** [comment]
Ah you're right, that does look suspect. I wonder if this should be `(&r).Reservations[0].Instances[0]`.
