### ISSUE TITLE
file provisioner fails to upload file to directory

### ISSUE THREAD

**Issue by deitch** [mitchellh/packer#3500]
I am using default ssh to communicate to a virtualbox-iso build. If I try to upload a file to a directory, it fails.

This fails:
````json
{
  "type": "file",
  "source": "somefile",
  "destination": "/tmp",
  "direction": "upload"
}
````

This succeeds:

````json
{
  "type": "file",
  "source": "somefile",
  "destination": "/tmp",
  "direction": "upload"
}
````

Given that `scp` and (when on a host) plain `cp` are able to accept a directory as a destination, i.e. if destination is a directory, then copy to a file in that directory with the same name as the source file, this should work as well.

Error is:

````
Build 'virtualbox-iso' error: scp: /tmp: Is a directory
````

Platform:

* Packer version: 0.10.0
* Host: Ubuntu 16.04 Desktop

Relevant part of packer log output 
https://gist.github.com/anonymous/36ee877ee693d3b6bbd98f35e95aa75b

**Comment by cbednarski** [comment]
The two examples you posted are the same, but this should work:

```
{
  "type": "file",
  "source": "somefile",
  "destination": "/tmp/somefile",
  "direction": "upload"
}
```

If you don't want to specify the file by name you should be able to use a directory instead (and the entire thing will be uploaded) but because this feature has to work in a cross-platform way we don't actually use `scp`.

**Comment by deitch** [comment]
Oops, I messed up on the copy-paste. Editing now. But the issue is that I should *not* have to name the file in the destination. In just about every OS, I can do `cp afile /tmp` and have it recognize that I mean to copt `afile` to `/tmp/afile` (use equivalent paths for Windows). I *don't* need to do `cp afile /tmp/afile`. `scp` works the same way, so does `ftp`, `sftp`, etc. etc.
