### ISSUE TITLE
Add wait_before to shell provisioner

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#3508]
The docs advise using `sleep 60` between reboots and sometimes it's desirable to wait for other reasons (while refreshing all of the network interfaces or upgrading `sshd`, for example). Currently, though, this technique relies on having an SSH connection and may break because of race conditions inside the VM.

To make this more reliable we could add a wait_before (or similar) parameter to the shell provisioner that allows us to insert an arbitrary wait before a provisioner starts.

**Comment by vtolstov** [comment]
Why not use pause_before ?
7 Май 2016 г. 7:14 пользователь "Chris Bednarski" <notifications@github.com>
написал:

**Comment by cbednarski** [comment]
Ah thanks, I thought there was something like this but I couldn't find it in the docs. Derp. :)
