### ISSUE TITLE
Documentation Pages Flow Past The Web Page Footer And Become Invisible

### ISSUE THREAD

**Issue by Zian** [mitchellh/packer#3509]
When I try to view any Packer documentation (e.g. https://www.packer.io/docs/installation.html), most of the text flows past the footer and becomes impossible to read. This happens on both of my monitors.

I will attach a screenshot.

Steps to Reproduce:
1. Go to https://www.packer.io/docs/installation.html
2. Scroll past the footer with the HashiCorp logo in the right-hand corner.
3. Try to read a word (and fail).

System Details:
- Windows 7 SP1 x64 EN-US
- IE11
- ThinkPad TXXXp
- 100% text size (aka 96 PPI)
- Left monitor (primary): 1600x900 
- Right monitor (secondary): 1080x1920 (the orientation is "Portrait (flipped)" according to Windows)

**Comment by Zian** [comment]
![packer screenshot](https://cloud.githubusercontent.com/assets/1581929/15095773/03788b9a-148f-11e6-9bff-b66adcec6419.png)

**Comment by cbednarski** [comment]
Thanks for the report. As far as I know, both Windows 7 and Internet Explorer are end-of-life products and Microsoft is no longer supporting them. To read the documentation please use another browser such as Firefox or Chrome.
