### ISSUE TITLE
Packer Cannot Find VBoxManage After Installing VirtualBox

### ISSUE THREAD

**Issue by Zian** [mitchellh/packer#3510]
packer does not correctly find VBoxManage. It complains that the file is not in the PATH variable even though the computer knows where VirtualBox is installed and VBoxManage is always located in the same folder as VirtualBox.

Steps to Reproduce:
1. Install VirtualBox 5.0.20
2. Install the extra additions from Oracle for VirtualBox
3. Exit VirtualBox
4. Download the ZIP file for Windows 7 x64 from the Packer website.
5. Copy packer.exe to the desktop (e.g. "E:\Zian\Desktop")
6. Go to https://github.com/joefitzgerald/packer-windows 
7. Click "Download ZIP"
8. Open the ZIP file
9. Copy the packer-windows-master folder to the desktop. You should now have something like "E:\Zian\Desktop\packer-windows-master". I will attach the modified version of windows_7.json below.
10. Launch a command prompt (aka "cmd.exe")
11. "cd E:\Zian\Desktop\packer-windows-master"
12. Validate the Windows 7 file by running "..\packer validate E:\Zian\Desktop\packer-windows-master\windows_7.json"
13. Make sure packer says "Template validated successfully."
14. Run "..\packer build E:\Zian\Desktop\packer-windows-master\windows_7.json"

I expected packer to spend the next day or two building a virtual machine. Instead, I got this:

E:\Zian\Desktop\packer-windows-master>..\packer build E:\Zian\Desktop\packer-windows-master\windows_7.json
virtualbox-iso output will be in this color.

Build 'virtualbox-iso' errored: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in %PATH%

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in %PATH%

==> Builds finished but no artifacts were created.

E:\Zian\Desktop\packer-windows-master>

Finally, to attempt & fail at getting a packer log...
1. In the same Windows Command Prompt, run "SET PACKER_LOG=1"
2. Run "SET PACKER_LOG_PATH="packerlog.txt""
3. Run "..\packer build E:\Zian\Desktop\packer-windows-master\windows_7.json" again.
4. You will get the following error:

E:\Zian\Desktop\packer-windows-master>..\packer build E:\Zian\Desktop\packer-windows-master\windows_7.json
Couldn't setup log output: open "packerlog.txt": The filename, directory name, or volume label syntax is incorrect.
E:\Zian\Desktop\packer-windows-master>

- Packer Version 0.10.1
- Host platform Windows 7 SP1 x64 EN-US
- Debug log output from `PACKER_LOG=1 packer build template.json`.
Was not able to get log output
- The _simplest example template and scripts_ needed to reproduce the bug.
  Download it from https://github.com/joefitzgerald/packer-windows. Then overwrite windows_7.json.

**Comment by Zian** [comment]
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "iso_url": "{{user `iso_url`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_checksum": "{{user `iso_checksum`}}",
      "headless": true,
      "boot_wait": "2m",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_wait_timeout": "8h",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "guest_os_type": "Windows7_64",
      "disk_size": 81920,
	  "hard_drive_interface": "sata",
      "floppy_files": [
        "{{user `autounattend`}}",
        "./scripts/dis-updates.ps1",
        "./scripts/hotfix-KB3102810.bat",
        "./scripts/microsoft-updates.bat",
        "./scripts/win-updates.ps1",
        "./scripts/openssh.ps1",
        "./scripts/oracle-cert.cer"
      ],
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "2048"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "2"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--pae",
          "on"
        ]
		,
        [
          "modifyvm",
          "{{.Name}}",
          "--hwvirtex",
          "on"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--nestedpaging",
          "on"
        ]
		,
        [
          "modifyvm",
          "{{.Name}}",
          "--vram",
          "256"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--accelerate3d",
          "on"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--accelerate2dvideo",
          "on"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--audio",
          "dsound"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--audiocontroller",
          "hda"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--usb",
          "on"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--usbehci",
          "on"
        ]
      ]
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "remote_path": "/tmp/script.bat",
      "execute_command": "{{.Vars}} cmd /c C:/Windows/Temp/script.bat",
      "scripts": [
        "./scripts/vm-guest-tools.bat",
        "./scripts/vagrant-ssh.bat",
        "./scripts/disable-auto-logon.bat",
        "./scripts/enable-rdp.bat",
        "./scripts/compile-dotnet-assemblies.bat",
        "./scripts/compact.bat"
      ]
    }
  ],
  "post-processors": [
    {
      "type": "vagrant",
      "keep_input_artifact": false,
      "output": "windows_7_{{.Provider}}.box",
      "vagrantfile_template": "vagrantfile-windows_7.template"
    }
  ],
  "variables": {
    "iso_url": "http://care.dlservice.microsoft.com/dl/download/evalx/win7/x64/EN/7600.16385.090713-1255_x64fre_enterprise_en-us_EVAL_Eval_Enterprise-GRMCENXEVAL_EN_DVD.iso",
    "iso_checksum_type": "md5",
    "iso_checksum": "1d0d239a252cb53e466d39e752b17c28",
    "autounattend": "./answer_files/7/Autounattend.xml"
  }
}

**Comment by Zian** [comment]
Argh! The bug magically went away on its own after recurring 3+ times (I figured I'd give it 1 last shot). Please close this issue.

**Comment by cbednarski** [comment]
@Zian No worries! The PATH is kinda clunky. When you make a change to PATH or any other environment variable you have to restart (close & open) any CMD or powershell windows before the changes will take effect. You can also force an update by logging out or restarting but _usually_ it's fine just to restart the command prompt window. I'm glad you got things working!
