### ISSUE TITLE
Need help using script in provisioner

### ISSUE THREAD

**Issue by Tammys99** [mitchellh/packer#3514]
Hi there.
So I have a script that works when I use the inliine command....but when I change it to use script I get the following error: error,1 error(s) decoding:\n\n* 'Script' expected type 'string'%!(PACKER_COMMA) got unconvertible type '[]interface {}'

I would love to know what I'm doing wrong. here is a chunk of my code:

```
"provisioners": [
	{
		      "type":          "chef-solo",
		      "skip_install":true,
		      "guest_os_type": "windows",
		      "cookbook_paths":["./chef/cookbooks"],
		      "run_list":      [
						"iis::default",
						"iis::mod_aspnet45",
						"iis::mod_compress_static",
						"iis::addspxsite",
						"awscli::download",
						"awscli::default",
						"codedeploy::download",
						"codedeploy::default"
					]
		},
		{
			"type": "powershell",
			"pause_before": "30s",
			"script": [

				"Remove-Item -Recurse -Force c:\\temp",
				"Remove-Item -Recurse -Force c:\\chef"
			]
		},

		{
		"pause_before": "30s",
			"type": "file",
			"pause_before": "30s",
			"source": "./configs",
			"destination": "c:\\temp\\configs"
		},

		{
			"type": "file",
			"pause_before": "30s",
			"source": "./scripts",
			"destination": "c:\\temp\\scripts"
		},
		{
			"type": "powershell",
			"pause_before": "30s",
			"script": 
				"c:\\temp\\scripts\\ec2-instance.ps1"
			
		}
```
If you need more information please let me know.
Thanks!

**Comment by rickard-von-essen** [comment]
`script` dosn't take an array and should be a relative path to a script on the host to execute on the guest.
Change:
```json
"script": [
    "Remove-Item -Recurse -Force c:\\temp",
    "Remove-Item -Recurse -Force c:\\chef"
]
```
To:
```json
"inline": [
    "Remove-Item -Recurse -Force c:\\temp",
    "Remove-Item -Recurse -Force c:\\chef"
]
```
Should do the trick.

**Comment by Tammys99** [comment]
Thanks for the feed back. I made the change like you suggested but I did get another failure the message reads : error(s) occurred:\n\n* Bad script 'c:\temp\scripts\ec2-instance.ps1': stat c:\temp\scripts\ec2-instance.ps1: no such file or directory

Am I using the "script" wrong  here in my code. If I were to change script to inline it works. I'm trying to understand the difference between , scripts, script and inline. The reason I'm trying to use scripts is because I have more than one powershell script to call however my second script keeps failing so I tought I would try to use scripts or script instead of inline:
		"pause_before": "30s",
			"type": "file",
			"pause_before": "30s",
			"source": "./configs",
			"destination": "c:\\temp\\configs"
		},

		{
			"type": "file",
			"pause_before": "30s",
			"source": "./scripts",
			"destination": "c:\\temp\\scripts"
		},
		{
			"type": "powershell",
			"pause_before": "30s",
			"script": 
				"c:\\temp\\scripts\\ec2-instance.ps1"
			
		}

As always thanks for your help.

**Comment by rickard-von-essen** [comment]
See the docs, https://www.packer.io/docs/provisioners/powershell.html#script
You shouldn't upload your script before running them they will be uploaded for you.

```json
    {
        "type": "powershell",
        "pause_before": "30s",
        "script": 
            "scripts/ec2-instance.ps1"
    }
```

Would be a common way to do this. And on the host you would have a directory `scripts` containing the file `ec2-instances.ps1`.

**Comment by Tammys99** [comment]
so I took out the type file and replaced the powershell part with what you suggested but now I'm getting this for an error: 

error,1 error(s) decoding:\n\n* 'Script' expected type 'string'%!(PACKER_COMMA) got unconvertible type '[]interface {}'

I checked that I had valid json 

	"provisioners": [
	{
		      "type":          "chef-solo",
		      "skip_install":true,
		      "guest_os_type": "windows",
		      "cookbook_paths":["./chef/cookbooks"],
		      "run_list":      [
						"iis::default",
						"iis::mod_aspnet45",
						"iis::mod_compress_static",
						"iis::addspxsite",
						"awscli::download",
						"awscli::default",
						"codedeploy::download",
						"codedeploy::default"
					]
		},
		{
			"type": "powershell",
			"pause_before": "30s",
			"script": [

				"Remove-Item -Recurse -Force c:\\temp",
				"Remove-Item -Recurse -Force c:\\chef"
			]
		},

		{
		"pause_before": "30s",
			"type": "file",
			"pause_before": "30s",
			"source": "./configs",
			"destination": "c:\\temp\\configs"
		},

    {
        "type": "powershell",
        "pause_before": "30s",
        "script": 
            "scripts/ec2-instance.ps1"
    }
		


Thanks again for your help.

**Comment by Tammys99** [comment]
Thanks for your help after posting the script above I noticed I still had scripts where you recommened I change it to have inline. Once I fixed that it worked! So I moved on to add my second powershell script and now I get a cookbook error:
errored: Error uploading cookbooks: Error uploading file to $env:TEMP\winrmcp-5731ffc2-c70c-5c57-f8c9-fd0241d63222.tmp: unknown error Post http://54.235.236.118:5985/wsman: write tcp 10.190.198.216:59625->54.235.236.118:5985: write: connection reset by peer

I fixed this  a while ago by putting in pause_before. Also incase you are wondering  the reason I didn't put the two powershell scripts in the same section is because I couldn't get the json to validate...

Here is my code:
	"provisioners": [
	{
		      "type":          "chef-solo",
		      "skip_install":true,
		      "guest_os_type": "windows",
		      "cookbook_paths":["./chef/cookbooks"],
		      "run_list":      [
						"iis::default",
						"iis::mod_aspnet45",
						"iis::mod_compress_static",
						"iis::addspxsite",
						"awscli::download",
						"awscli::default",
						"codedeploy::download",
						"codedeploy::default"
					]
		},
		{
			"type": "powershell",
			"pause_before": "30s",
			"inline": [

				"Remove-Item -Recurse -Force c:\\temp",
				"Remove-Item -Recurse -Force c:\\chef"
			]
		},

		{
		"pause_before": "30s",
			"type": "file",
			"pause_before": "30s",
			"source": "./configs",
			"destination": "c:\\temp\\configs"
		},

    {
        "type": "powershell",
        "pause_before": "30s",
        "script": 
            "scripts/ec2-instance.ps1"
    },

    {
        "type": "powershell",
        "pause_before": "30s",
        "script": 
             "scripts/win-cloudWatchConfig.ps1"
    }
	
Thanks again for your help.

**Comment by michaeltlombardi** [comment]
Recommend this issue be closed since it looks to be resolved.
