### ISSUE TITLE
packer validate crash

### ISSUE THREAD

**Issue by deogracia** [mitchellh/packer#3516]
Hi,
I use [Chakra](https://chakraos.org/)  ( archlinux like) and I compile packer from [source](https://github.com/deogracia/chakraos-ccr-my-contrib/tree/master/packer-io).

* packer version : 0.10.1
* Host platform:
 * LSB Version:	1.4
 * Distributor ID:	Chakra
 * Description:	Chakra
 * Release:	2016.02
 * Codename:	Ian
* gist with files ( log + json) : https://gist.github.com/deogracia/ff3ae2e1fef16eaa3e0c8e980b0cadcd
* scripts isn't needed

I'm trying to create a chakra linux template.

I forgot to complete iso_url before runing packer validate chakra.json and kaboum.

I I put sommething in iso_url, even random char, I have - without a crash :

```
Template validation failed. Errors are shown below.

Errors validating build 'virtualbox-iso'. 1 error(s) occurred:

* No checksum for "lkshjlksqjfmqs" found at: https://mirrors.kernel.org/archlinux/iso/2016.05.01/sha1sums.txt
```

Thanks for your work :D

**Comment by cbednarski** [comment]
Thanks for the report!

> Errors validating build 'virtualbox-iso'. unexpected EOF
> panic: runtime error: index out of range

This looks like a simple programming error; we are not checking the key / length before trying to read the data. It probably needs something like:

```
if val, ok := config['key']; ok {
}
```
