### ISSUE TITLE
ansible remote provisioner cannot be used to build a fresh image (amazon-ebs)

### ISSUE THREAD

**Issue by Daemoen** [mitchellh/packer#3519]
bash-4.3$ packer --version
0.10.0

bash-4.3$ ansible --version
ansible 2.0.2.0
  config file = /opt/ansible/packer/ansible.cfg
  configured module search path = Default w/o overrides

Because of the way that sudo is configured in most distributions (requiretty is *Enabled by default*), and the way that the ansible-provisioner works (Requires using sftp, which is incompatible with set ssh_pty -- See :  #3375 ) you cannot use ansible remote provisioner to build a brand new image from *most* distributions images.

If you were to set ssh_pty, you get stuck when the logins occur and the sftp server is executed due to garbage, but you also cannot provision the machines without it, since you *have* to have a pty initially.  The only way around this is to spin your own copy of an *upstream* image, just so that you can build your image without requiretty, save it, and then use that second stage image.  This defeats the entire purpose and concept of what packer is intended for.

Please provide a workaround or suggestion, as right now, in order to do this, you would have to rebuild your ami every time an ami is updated upstream, until the upstream images change.

**Comment by rickard-von-essen** [comment]
See https://github.com/mitchellh/packer/issues/3375#issuecomment-203738359

Just use the `shell` provisioner to remove `requiretty` before using `ansible`.

**Comment by Daemoen** [comment]
This solution does not work.  In order to use the shell provisioner you still need to use sudo.  In order to use sudo you still need a tty.  Even if I setup a new builder that enables tty for the shell script, I'll never be able to use ansible in that same builder.

**Comment by Daemoen** [comment]
Also worth noting that the change to sudoers is currently Fedora only and has not been accepted into RH at this time.

**Comment by rickard-von-essen** [comment]
Depending on the source of your image, build in two steps or fix it at installation i.e. _preceed/kickstart_. Or just use `root` if that is possible.

**Comment by Daemoen** [comment]
This is tied to Amazon images, none of which use the root user.  Please explain how to do it in multiple build steps, as that appears to be the only option aside from fixing scp/SSH_pty

**Comment by rickard-von-essen** [comment]
Then you can use `user_data` or `user_data_file` to remove requiretty.

**Comment by bhcleek** [comment]
The tty is only a problem because interactive logins (which is what you'll get when a TTY is allocated) cause additional data to be written to be written when the shell is allocated. That additional data doesn't *have* to be written; you should be able to modify the profile such that interactive shells don't write any data to the tty when the shell is initialized. If for some reason you don't want to modify the profile of the user that the builder connects as, you could consider using the shell provisioner to create a new user with permissions necessary to execute your Ansible plays, and then using the `become_user` facility of Ansible to execute tasks as that user.

**Comment by Daemoen** [comment]
For now I am going to close this, I will post some documentation at a later date on how to go about using the user_data method to prepare the image and ensure that amazon-ebs is able to fully utilize ansible for provisioning.  Thanks for feedback @bhcleek and @rickard-von-essen
