### ISSUE TITLE
AWS instance external reboot after provision but before final AMI creation

### ISSUE THREAD

**Issue by poshest** [mitchellh/packer#3522]
We're using Packer 0.8.7 to build a Centos 7 AMI, which involves a Ansible-local provisioner that installs PM2 and node.js to run a node application.  

We're getting this weird issue with PM2 and Node, where we start an instance from the newly Packer-created AMI and the node application has [something like this issue](https://github.com/Unitech/pm2/issues/1521).  

We've tried for a couple of days without success to fix it from the node/PM2 angle, and in doing so, we noticed that when we 

1. Bring up an instance from the newly Packer-created AMI
2. __Manually__ reboot the instance (as in from the AWS console)

... the node app works perfectly and any AMI created from that rebooted instance also works.

We've tried issuing reboot from the shell provisioner after all the other provisioning commands have run (including many variations with `sleep` commands), but that doesn't fix the problem.  External reboot from Amazon seems to be the only flavour of reboot that works.

So I'm wondering if there's any way to reboot an instance by issuing a AWS CLI command from the machine that's hosting Packer (not the AWS instance being built), eg 

[`aws ec2 reboot-instances --instance-ids i-1234567890abcdef5`](http://docs.aws.amazon.com/cli/latest/reference/ec2/reboot-instances.html)

But this has to be done AFTER provisioning, and BEFORE creation of the Packer-created AMI.

Is there currently a feature to run commands from the local machine during a build?   If not, may this server as a feature request to allow for such a functionality?  It seems similar to the "Windows Reboot" provisioner, but specific to AWS instead of operating system.

Obviously we should solve our problem with PM2/node, but given we've exhausted all our options on that front, this route may be a good option for us.  Happy to hear alternative approaches to solve this too!

Or I'd appreciate advice on other approaches.

**Comment by rickard-von-essen** [comment]
First of all v0.8.7 is old, upgrade. Installing software is no reson to reboot a Linux machine. You better spend your time debugging/fixing the real issue (PM2).

**Comment by poshest** [comment]
Good idea.  Upgrading the version was my first thought when I checked it to write this post.  

Yeah, like I said, we've already tried to fix the PM2 issue for days now.  There comes a time when more effort becomes uneconomic.

**Comment by poshest** [comment]
FYI to anyone it helps:  we solved it by creating a parent shell script that calls the packer build, creates an instance from the new AMI, reboots it with the command above, saves a new AMI, deletes the packer AMI.  It's ridiculous, but it works now.
