### ISSUE TITLE
Support for GCE image families

### ISSUE THREAD

**Issue by falzm** [mitchellh/packer#3524]
Hi

Google Cloud Engine has implemented a new feature called [image families](https://cloud.google.com/compute/docs/images#image_families) which allows to sort of *alias* images, could you support this feature in Packer?

**Comment by rickard-von-essen** [comment]
See PR #3503

**Comment by falzm** [comment]
Sorry, I checked in the open issues but not in the pull requests...

**Comment by cbednarski** [comment]
This has been merged into master; please see #3503 for details!
