### ISSUE TITLE
Feature/Doc: qemu builder tweaks to run headless

### ISSUE THREAD

**Issue by candlerb** [mitchellh/packer#3530]
- Packer Version: 0.10.1
- Host platform: ubuntu 14.04

I am running packer on a remote machine which I have ssh'd into.

I am using the [basic example](https://www.packer.io/docs/builders/qemu.html) centos template, minimally tweaked [^1]

The build fails with:

~~~
2016/05/13 15:29:36 packer: 2016/05/13 15:29:36 Qemu stderr: Could not initialize SDL(No available video device) - exiting
~~~

[Full logs](https://gist.github.com/candlerb/4eb63eb375bbcbc336cd19eedd1e1cd4)

Reason: this is because packer runs qemu with `-vnc 0.0.0.0:21 ... -display sdl` which tries to create a local emulated VGA window. If you have text-only access to the system where packer is running, it fails.

Workaround 1: `ssh -X target.host` and then run packer there. You get the VGA screen relayed back to the client which is useful to see what's going on (without having to connect to VNC manually). You have to connect from a client device which has X11 though.

Workaround 2: override using `qemuargs`:

~~~
    ...
      "qemuargs":[
        ["-display", "vnc"]
      ]
~~~

The build runs, and if you want to see progress you can still connect using `vncviewer <targethost>:<display>` (

# Feature request

Either:

1. Default to `-display vnc` if `$DISPLAY` is not set; or

2. Clarify in the documentation that the qemu builder normally runs under a graphical environment, and include the workarounds shown above.

--------
[^1]: Changes required to make the build succeed:

* Change url and checksum for centos 6.7
* Increase ssh timeout from 30s to 600s (actually takes around 5.5 minutes on my setup)
* Change "poweroff" to "reboot" in kickstart file; otherwise packer just waits for ssh to come up, which it never does

**Comment by candlerb** [comment]
Oops, I found there is a "headless" option there already.

It might be helpful to make this the default automatically if `$DISPLAY` is not set.

Otherwise I'm happy for this ticket to be closed.

**Comment by cbednarski** [comment]
By `$DISPLAY` do you mean the environment variable? This is not consistent across OSes such as Windows and OS X so I don't think we can rely on this being set. If I misunderstood please clarify.

**Comment by candlerb** [comment]
Yes, that's what I meant. Maybe then a documentation note is the way to go.

Unfortunately the default output doesn't show you why qemu didn't start, and `./packer --help` doesn't tell you how to turn on verbose output, so I had to go searching to discover `PACKER_LOG=1`. So my out-of-the-box experience of packer was not as smooth as I'd hoped :-(

**Comment by candlerb** [comment]
Note: if you run headless, you can still see the console using `vncviewer -Shared <host>:<display>`

**Comment by cbednarski** [comment]
Thanks for clarifying. If you are willing to make a PR to update the documentation with your notes, I would appreciate it! We can also make the CLI help hint at verbose mode.
