### ISSUE TITLE
Template with keep_registered not validating

### ISSUE THREAD

**Issue by ronlipke** [mitchellh/packer#3532]
I cannot get a template to validate using a vmware-iso builder with the `keep_registered` option.

````
Template validation failed. Errors are shown below.

Errors validating build 'vmware-test'. 1 error(s) occurred:

* unknown configuration key: "keep_registered"
````
Version: 10.0.1
Platform: OS X 10.11.4
Sample template:

````
{
  "builders": [
    {
      "name": "vmware-test",
      "type": "vmware-iso",
      "iso_url": "http://mirror.es.its.nyu.edu/centos/7.2.1511/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso",
      "iso_checksum": "f90e4d28fa377669b2db16cbcb451fcb9a89d2460e3645993e30e137ac37d284",
      "iso_checksum_type": "sha256",
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
      ],
      "http_directory": "http",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_wait_timeout": "600s",
      "headless": true,
      "boot_wait": "10s",
      "disk_size": "16000",
      "disk_type_id": "thin",
      "guest_os_type": "ubuntu-64",
      "remote_type": "esx5",
      "remote_username": "root",
      "remote_password": "password",
      "remote_host": "10.0.0.5",
      "remote_datastore": "datastore-ssd-2",
      "keep_registered": true,
      "tools_upload_flavor": "linux",
      "shutdown_command": "echo 'vagrant' | sudo -S -E shutdown -P now",
      "vnc_port_min": "5988",
      "vnc_port_max": "5988",
      "vmx_data": {
        "memsize": "1024",
        "numvcpus": "1",
        "cpuid.coresPerSocket": "2",
        "ethernet0.networkName": "VM Network"
      }
    }
  ]
}
````

**Comment by rickard-von-essen** [comment]
In the example above you are missing a ','  after the line with
`keep_registered`.

**Comment by ronlipke** [comment]
Whoops, that what I get for copy pasta.  
Even with the correct syntax it fails on validation. Passes with `-synatx-only` though.

**Comment by rickard-von-essen** [comment]
You might be running with old plugins. Could you double check that you followed the _note_ on https://www.packer.io/downloads.html

If that doesn't help please rerun with `PACKER_LOG=1 packer build template.json` and gist the full log.

**Comment by ronlipke** [comment]
Ha, I figured it out.  I didn't realize homebrew updated packer to 10.0.0_1, not 10.0.1, so I checked the release dates and saw that the `keep_registered` change was added on 10/16 - one day after 10.0.0 was released 😂

Weird that it wasn't in the changelog though.

Anyway, thanks for you're help and pointing me in the right direction.
