### ISSUE TITLE
Azure: Where's the Best Error Message

### ISSUE THREAD

**Issue by boumenot** [mitchellh/packer#3536]
A customer experienced an issue when the _capture_name_prefix_ was set to an unacceptable value (#3535).  The method signature for the API call returns an HTTP response and an error. The Azure builder code discards the HTTP response, and checks the error only.  The error's message is not intuitive, and does not return any information to help to debug the issue.  The HTTP response is more helpful, but it is discarded.  

The fix is for the builder code to check and surface both.  (Checking the error only is sufficient to indicate there is an error with the API call.)  I am tracking the [issue](https://github.com/Azure/azure-sdk-for-go/issues/328) with the Azure SDK team too, to see what their recommendations are.

**Comment by boumenot** [comment]
The Azure/go-autorest and Azure/azure-sdk-for-go recently made changes to improve this.

1. See [#339](https://github.com/Azure/azure-sdk-for-go/issues/339)
1. See [#334](https://github.com/Azure/azure-sdk-for-go/issues/334)

There is probably work that needs to be done to expose this in Packer.

**Comment by mwhooker** [comment]
Closing since this looks fixed now https://github.com/Azure/azure-sdk-for-go/issues/334#issuecomment-228890882

the error returned is something like `return fmt.Sprintf("%s#%s: %s: StatusCode=%d", e.PackageType, e.Method, e.Message, e.StatusCode)`
