### ISSUE TITLE
vmware additional_disk fails for 50GB, but works for 25GB

### ISSUE THREAD

**Issue by MansM** [mitchellh/packer#3543]
I am working on a base image for our environment.
I need to create an additional disk. It works as a charm when I use 25000MB and fails with 50000MB.

```
1463484669,,ui,say,==> rhel-7-vmware-oss-oracle: Creating additional hard drives...
2016/05/17 13:31:09 packer: 2016/05/17 13:31:09 Executing: /usr/bin/qemu-img [create -f vmdk -o compat6 packer-rhel-7.2-x86_64-vmware-oss-oracle/packer-rhel-7.2-150-x86_64-oss-oracle-1.vmdk 50000M]
2016/05/17 13:31:09 packer: 2016/05/17 13:31:09 stdout: Formatting 'packer-rhel-7.2-x86_64-vmware-oss-oracle/packer-rhel-7.2-150-x86_64-oss-oracle-1.vmdk', fmt=vmdk size=52428800000 compat6=on zeroed_grain=off
```

lsscsi:
```
1463485315,,ui,message,    rhel-7-vmware-oss-oracle: [0:0:0:0]    disk    VMware%!(PACKER_COMMA)  VMware Virtual S 1.0   /dev/sda
2016/05/17 13:41:55 packer: 2016/05/17 13:41:55 remote command exited with '0': sh '/tmp/script_8678.sh'
2016/05/17 13:41:55 packer: 2016/05/17 13:41:55 [INFO] RPC endpoint: Communicator ended with: 0
2016/05/17 13:41:55 [INFO] 0 bytes written for 'stderr'
2016/05/17 13:41:55 [INFO] 2563 bytes written for 'stdout'
2016/05/17 13:41:55 [INFO] RPC client: Communicator ended with: 0
2016/05/17 13:41:55 [INFO] RPC endpoint: Communicator ended with: 0
2016/05/17 13:41:55 packer: 2016/05/17 13:41:55 [INFO] 2563 bytes written for 'stdout'
2016/05/17 13:41:55 packer: 2016/05/17 13:41:55 [INFO] 0 bytes written for 'stderr'
1463485315,,ui,message,    rhel-7-vmware-oss-oracle: [0:0:1:0]    disk    VMware%!(PACKER_COMMA)  VMware Virtual S 1.0   /dev/sdb
2016/05/17 13:41:55 packer: 2016/05/17 13:41:55 [INFO] RPC client: Communicator ended with: 0
1463485315,,ui,message,    rhel-7-vmware-oss-oracle: [2:0:0:0]    cd/dvd  NECVMWar VMware IDE CDR10 1.00  /dev/sr0
```

 Execution of '/sbin/pvcreate --force /dev/sdb' returned 5: Device /dev/sdb not found (or ignored by filtering)

 /opt/packer/packer  --version
0.10.0

vmware player: 6.0.5

"disk_additional_size": ["50000"], is the only value changed

physical harddisk has 180GB free

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

`/sbin/pvcreate --force /dev/sdb` is quite clear that this is a issue with your installation. Just before that command add a `sleep 3600` access the machine and try your commands by hand and figure out why it fails. If you still have trouble try IRC or the mailing list.

**Comment by MansM** [comment]
it was indeed install issue:
part in kickstart did not selected the correct device.
solved it by adding the following to kickstart config:
%pre
#!/bin/sh
if [ -b /dev/sdb ] ; then
  echo "part /boot    --size 500      --asprimary --ondisk=sda" >> /tmp/partacties
  echo "part pv.01     --size 1        --grow --ondisk=sda" >> /tmp/partacties
elif [ -b /dev/vdb ] ; then
  echo "part /boot    --size 500      --asprimary --ondisk=vda" >> /tmp/partacties
  echo "part pv.01     --size 1        --grow --ondisk=vda" >> /tmp/partacties
else
  echo "part /boot    --size 500      --asprimary" >> /tmp/partacties
  echo "part pv.01     --size 1        --grow" >> /tmp/partacties
fi
%end

# Filesystems
%include /tmp/partacties
