### ISSUE TITLE
Docs probably should mention that ec2:GetPasswordData is required too

### ISSUE THREAD

**Issue by themalkolm** [mitchellh/packer#3546]
- packer 0.10.0
- windows

Here https://www.packer.io/docs/builders/amazon.html we have minimal set of permission for packer to work with Amazon. It is not full as on Windows `ec2:GetPasswordData` is requied as well for packer to be able to retrieve generated password.

Essentially this will allow this request: 
```
		resp, err := ec2conn.GetPasswordData(&ec2.GetPasswordDataInput{
			InstanceId: instance.InstanceId,
		})
```
https://github.com/mitchellh/packer/blob/8040317f7747eaee5b4ec7cad783700a58266fdb/builder/amazon/common/step_get_password.go#L113

Otherwise packer fails do get password data and gracefully dies.

**Comment by cbednarski** [comment]
@themalkolm Thanks for the report! If you could take a stab and updating the docs I'd be happy to merge this. Thanks!

**Comment by themalkolm** [comment]
@cbednarski maybe later, right now I just want to make sure it won't be forgotten
