### ISSUE TITLE
"Bad script... no such file or directory" for scripts that seem to clearly be present

### ISSUE THREAD

**Issue by austinbutler** [mitchellh/packer#3549]
This seems like it should be a simple thing, but I am completely stumped. So I am using [this project](https://github.com/kaorimatz/packer-templates) as a base to start from for my own local development. Unchanged, it works great. But I added my own scripts, and after that when running a validate or build I get the following:

```
packer-io build archlinux-x86_64.json
virtualbox-iso output will be in this color.

1 error(s) occurred:

* Bad script 'scripts/archlinux/pacman.sh': stat scripts/archlinux/pacman.sh: no such file or directory
```

I am pretty certain the file is there, though. And it seems to have the exact same permissions as the other files in the same folder that Packer has no problems with. When I remove the script from the template, everything builds fine.

```
ls -lah scripts/archlinux
total 24K
drwxr-xr-x 1 austin austin  154 May 18 02:41 .
drwxr-xr-x 1 austin austin  188 May 18 02:41 ..
-rw-r--r-- 1 austin austin   51 May 18 04:22 cleanup.sh
-rw-r--r-- 1 austin austin  943 May 18 03:02 packages-gui.sh
-rw-r--r-- 1 austin austin 1.2K May 18 04:24 pacman.sh
-rw-r--r-- 1 austin austin  157 May 18 02:41 virtualbox-cli.sh
-rw-r--r-- 1 austin austin  153 May 18 02:41 virtualbox-gui.sh
```

I even put a test into the template using shell-local, which can stat the same file without issue:
`File: 'scripts/archlinux/pacman.sh' Size: 1193 Blocks: 8 IO Block: 4096 regular file Device: 21h/33d Inode: 5457306 Links: 1 Access: (0644/-rw-r--r--) Uid: ( 1000/ austin) Gid: ( 1000/ austin) Access: 2016-05-18 02:41:06.982259880 -0700 Modify: 2016-05-18 02:41:06.982259880 -0700 Change: 2016-05-18 02:41:06.982259880 -0700 Birth: -`

I can also copy and paste from the error message and do a stat without issue:
```
stat scripts/archlinux/pacman.sh
  File: 'scripts/archlinux/pacman.sh'
  Size: 1193      	Blocks: 8          IO Block: 4096   regular file
Device: 21h/33d	Inode: 5457306     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  austin)   Gid: ( 1000/  austin)
Access: 2016-05-18 02:41:06.982259880 -0700
Modify: 2016-05-18 04:24:26.913507578 -0700
Change: 2016-05-18 04:24:26.913507578 -0700
 Birth: -
```

Thinking it was maybe something with my setup on this computer, I cloned my repo to another computer, installed Packer, then tried a build, but the same error for the same file occurs. I tried adding my own other scripts, too, with different names and I just end up with more of the same errors. What's weird is how all of the scripts I didn't add never are an issue. At this point I am guessing it's a bug, or I am somehow missing something incredibly obvious.

- Packer v0.10.1
- Arch Linux
- Debug log: https://gist.github.com/austinbutler/114854ef567622a7b0e76e22304d0e25
- Template: https://gist.github.com/austinbutler/29cbb85e11798f90a6587a429a808ae2
- Script: https://gist.github.com/austinbutler/70f04c29e9670bbd7e6d1ea6a4f62b87

**Comment by rickard-von-essen** [comment]
Could you publish you git repo where you have this problem.

**Comment by austinbutler** [comment]
Sure: https://gitlab.com/austinbutler/packer-templates

Has some extra stuff in the template that I ripped out later for simplicity and trying to narrow down the problem when reporting this, but otherwise it should exhibit the same problem.

**Comment by rickard-von-essen** [comment]
You should switch editor 😉 
![screen shot 2016-05-18 at 14 49 57](https://cloud.githubusercontent.com/assets/557699/15359078/f7cba5a8-1d07-11e6-8f36-ed894528d42a.png)

**Comment by austinbutler** [comment]
Well... I only feel semi-stupid now. Thanks!

Now I am off to find out how in the world Atom put those there.

**Comment by austinbutler** [comment]
Annnnd here we are: https://github.com/atom/atom/issues/1839

In case anyone else stumbles upon this.
