### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by joshuaspence** [mitchellh/packer#3553]
I would like to output the AWS AMI IDs from Packer to a JSON file, which I can then import into Terraform. The current "machine readable " output is CSV format (gross) and also too verbose (I only care about the output IDs... not the Packer logs themselves).

**Comment by joshuaspence** [comment]
It looks like #1926 would fix my issue.

**Comment by joshuaspence** [comment]
#2050 is also related.

**Comment by cbednarski** [comment]
Thanks for the suggestion. If you feel comfortable building packer from source, I'd encourage you to try applying one of the proposed patches and see whether they work for you.

In the interim, I think you can combine the machine readable format with grep, sed, and [jq](https://stedolan.github.io/jq/) to make a JSON file yourself. I understand shell fu is not ideal but it should open up this use case for you in the mean time.

**Comment by mwhooker** [comment]
This should be solved now through manifests https://www.packer.io/docs/post-processors/manifest.html

Will keep #2050 open for now since it's about tfvars
