### ISSUE TITLE
Openstack builder doesn't remove volume when terminating build instance

### ISSUE THREAD

**Issue by dave2** [mitchellh/packer#3555]
Packer versions tested: 0.9.0, however I've checked the git source and this appears to be still true in head.

It appears the OpenStack builder assumes the default for creating a volume from an image for a new instance is always to delete the volume on termination. However, it doesn't explicitly pass this when creating the instance in builder/openstack/step_run_source_server.go. it also doesn't make any attempt to remove the volume when terminating the instance either.

There are a couple of ways to fix this:
- Raise a PR against Gophercloud to allow passing `delete_on_termination` to nova API from the create server options.
- Explicitly note what volumes were created and destroy them ourselves when terminating the server.

However, in both cases we're be changing the "default" behavior to explicitly delete volumes, rather than leaving it undefined.

**Comment by cbednarski** [comment]
We can also do this in the `step_cleanup` part of the OpenStack builder.

**Comment by dave2** [comment]
The quick fix is extract the volume IDs out of the created instance, then mop them up. The better fix is use the bootfromvolume extension to create the (temp) instance with a block device mapping instead of pure image only, which allows passing delete_on_terminate per volume, and also allows a few other things to be specified (eg, volume size).

However, this would involve rewriting a lot of the openstack builder, starting with refactoring ```source_image``` to accept names or IDs (and not URLs I believe) like flavour does, deprecating ```source_image_name```, and rewiring the step for creating a server to use a block device mapping.

I guess alternatively we could resolve ```source_image_name``` into ```source_image``` early and then pass that to the block device mapping.

Looking for some guidance on what would be accepted before throwing a PR up. :)

**Comment by cbednarski** [comment]
@dave2 OpenStack is essentially supported by the community (I don't run OpenStack and have never used the builder myself), so if you're willing to put in the effort to refactor I will be happy to merge it in.

**Comment by cbednarski** [comment]
@rickard-von-essen I recall that you use OpenStack occasionally; if you have any thoughts here please weigh in!

**Comment by dave2** [comment]
Roger, expect to see quite a few PRs from me then on this, as we're just starting a process of a deploying an OpenStack setup in anger for $EMPLOYER.

**Comment by rickard-von-essen** [comment]
I did a quick run to enhance Packer OpenStack support some months ago, besides that I'm not an active OpenStack user. 

I don't have much advice on which solutions is the way to go without reading up alot on OpenStack.  The only thing I can say is to kept it simple. But I'll hopefully have some time to review any OpenStack PR's.

 > expect to see quite a few PRs from me then on this

Sounds awesome! 🚀

**Comment by mwhooker** [comment]
This isn't something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
