### ISSUE TITLE
packer attempts to sudo ec2-bundle-vol for windows builder

### ISSUE THREAD

**Issue by edsykes** [mitchellh/packer#3560]
- Packer 0.10.1
- Host platform: OSX
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/edsykes/650f8c0a7c2effde97aad20a1713d6fc

- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/edsykes/5d9507cab9365580b9d544f0d5a8f3c2

Problem:
Despite this being a windows ami as the source, packer appears to be running a nix command:

```
==> amazon-instance: Bundling the volume...
2016/05/20 21:11:37 packer: 2016/05/20 21:11:37 [INFO] starting remote command: sudo -i -n ec2-bundle-vol -k /tmp/key.pem -u 970493245035 -c /tmp/cert.pem -r x86_64 -e /tmp/* -d /tmp -p image-1463774867 --batch --no-filter
2016/05/20 21:11:37 packer: 2016/05/20 21:11:37 [INFO] command 'sudo -i -n ec2-bundle-vol -k /tmp/key.pem -u 970493245035 -c /tmp/cert.pem -r x86_64 -e /tmp/* -d /tmp -p image-1463774867 --batch --no-filter' exited with code: 1


```

Which then gives this error:

```
2016/05/20 21:11:37 ui:     amazon-instance: 'sudo' is not recognized as an internal or external command,
    amazon-instance: 'sudo' is not recognized as an internal or external command,
2016/05/20 21:11:37 ui:     amazon-instance: operable program or batch file.
    amazon-instance: operable program or batch file.
2016/05/20 21:11:37 ui error: ==> amazon-instance: Volume bundling failed. Please see the output above for more
==> amazon-instance: details on what went wrong.
==> amazon-instance:
==> amazon-instance: One common cause for this error is ec2-bundle-vol not being
==> amazon-instance: available on the target instance.
==> amazon-instance: Volume bundling failed. Please see the output above for more
2016/05/20 21:11:37 ui: ==> amazon-instance: Terminating the source AWS instance...
==> amazon-instance: details on what went wrong.
```

is there something that I haven't put into the template?

**Comment by cbednarski** [comment]
Thanks for the report! I think this is a feature gap since IIRC ec2-bundle bits were originally implemented before we had support for WinRM connections.

**Comment by edsykes** [comment]
I see, how are Windows users building to amis at the moment? Is there another way? 

I'm up for having a go at implementing this, if this is the way it should be done.

**Comment by edsykes** [comment]
It turns out that using the amazon-ebs builder works, whereas the amazon-instance type doesn't. We've switched to using the ebs storage type. 

Does it make sense to add this to the documentation. Happy to fork and pull request if the amazon-instance page is the right place.

**Comment by rickard-von-essen** [comment]
I think we should just state in the `amazon-instance` builder docs that we only support Linux and you should use `amazon-ebs` if you want to build a Windows AMI.

It is possible to build Windows instance store backed AMI's but only for Windows 2003 according the [AWS docs](http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/Creating_InstanceStoreBacked_WinAMI.html).

**Comment by cbednarski** [comment]
Thanks for clarifying, @rickard-von-essen! I agree that it would be better to advise `amazon-ebs` in the docs for this.

**Comment by cbednarski** [comment]
Added in 97772d0deef. Thanks, all!
