### ISSUE TITLE
Packer fails to authenticate to virtualbox for ansible (remote) provisioner

### ISSUE THREAD

**Issue by Daemoen** [mitchellh/packer#3567]
Using packer 0.10.1 with ansible on osx 10.11

Regardless of supplying sftp_command, proper users, a properly configured kickstart, etc,  ansible fails to handshake with the virtualbox instance.  However, spinning up an instance manually, setting the port to the same one that the proxy communicates on, and passing that as the inventory to ansible manually, I can use the exact same command that ansible is attempting and it works just fine.

Unfortunately, even with debug flag, we get no further data during this phase.

See: https://gist.github.com/Daemoen/026f18f77fa7cbff0350b97b167f750c

**Comment by vankhoa011** [comment]
@Daemoen :   I think the fail to authentication is not root cause of problem. With my output log, I still see the `unauthorized key` , but it is successful. 

I check your log file , it have a error before it run ansible playbook .  But I don't know that is root cause  problem whether or not ? 

```
2016/05/23 00:37:48 packer: 2016/05/23 00:37:48 scp stderr (length 51): Sink: C0644 58157056 VBoxGuestAdditions_5.0.20.iso
```

**Comment by Daemoen** [comment]
So, I have seen that part myself, and thought it was strange for several reasons.
1.) It should be using sftp for transfers
2.) I do not see it starting the sftp server in it, maybe I just overlooked it, but even grepping, I don't find the sftp server
3.) It succeeds regardless of 1, 2

Unfortunately, I cannot find *any* other error, and when I run it with debug, I can ssh in just fine at the beginning of the 'provision' phase.  As soon as the provision phase fails, it destroys the instance, so I can't do further testing unless I ignore the provision step.  I am going to test something a little different.  Instead of using the ansible provisioner, i'll use local shell and have it invoke ansible instead.

**Comment by rickard-von-essen** [comment]
You should just drop the ansible arg with:
```json
"--private-key={{user `key_path`}}/ut_centos_20160425"
```

And add `-e` to your `sftp_command`:
```json
"sftp_command": "{{user `sftp_path`}}/sftp-server -e",
```

And you will be fine.
