### ISSUE TITLE
Local shell post-processor does not support spaces in filenames

### ISSUE THREAD

**Issue by ViaviSolutions** [mitchellh/packer#3571]
Packer Version: 0.10.1
Host platform: OSX

Packer's local-shell post-processor is unable to run scripts that have a space in the path.

Here's an example script: https://gist.github.com/ViaviSolutions/902d08848572fbfc6bdf53d92da45bd8.

If the `templates_dir` has a space in the name, the build will fail. This is because the `execute_command` is expanding the string for the shell without quoting it.

Here's is an example of the relevant output:
https://gist.github.com/ViaviSolutions/647fc5ac7b3ec945a55482745ba9c215

**Comment by vtolstov** [comment]
i think this can be corrected when post-processor has been rewritten

**Comment by mwhooker** [comment]
the ticket for rewriting the post-processor #3571

**Comment by mwhooker** [comment]
@ViaviSolutions any chance you could test the code in https://github.com/mitchellh/packer/pull/4144 ?
