### ISSUE TITLE
packer fails to apply all run_volume_tags

### ISSUE THREAD

**Issue by eedwardsdisco** [mitchellh/packer#3573]
packer 0.10.1

``` json
      "run_volume_tags": {
        "Team": "{{user `tag_team`}}",
        "Category": "{{user `tag_category`}}",
        "Name": "packer-builder-{{user `base_name`}}"
      },
```

only the first tag in the list is applied to the ebs volume during the packer run
i confirmed this by switching the order of 'Team' and 'Category', and only the first one in the list appeared both times

platform: aws
env: os x 10.11.4

**Comment by cbednarski** [comment]
Thanks for the report!

**Comment by kwilczynski** [comment]
I need to get this fixed too, I will have a look.

**Comment by ltrifonov** [comment]
Hm... Just noticed similar behaviour on the very latest 0.12 (linux x64)
It applies only one volume tag. However, not the first one but the 7th in list of 9 ...
