### ISSUE TITLE
Progress ISO from a Network Path

### ISSUE THREAD

**Issue by DriveU** [mitchellh/packer#3578]
Just as Packer shows a Progress in percentage when downloading an ISO using a url request if a similar Progress is shown in percentage when downloading ISO from a Network drive. 
This will help the User a lot as many times due to different reasons a Network drive download fails and everything seems stranded. Should be a minor change but will be way too helpful.

**Comment by cbednarski** [comment]
Thanks for the suggestion! This makes sense to me. This is not high on my todo list but I'd be happy to review a PR for this.

**Comment by vtolstov** [comment]
2016-05-27 2:11 GMT+03:00 Chris Bednarski <notifications@github.com>:

> Thanks for the suggestion! This makes sense to me. This is not high on my
> todo list but I'd be happy to review a PR for this.


What do you think about additional dependency like github.com/cheggaaa/pb ?
Or  (if i want to create pr) i need to use internal packer progress?


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@yoctocloud.net

**Comment by arizvisa** [comment]
My PR, #2906, has preliminary support for doing asynchronous copies for all the different protocols using a goroutine. Inside common/download.go is a `FileDownloader` that does a copy based on the `.buffersize` attribute. One can probably implement the code to update the progressbar for it.

**Comment by cbednarski** [comment]
@vtolstov That looks fine to me.

**Comment by LukB4ULeap** [comment]
Can you also look into network shares that is long path names as this has been a source of problems specifically with reference to the Release build names from Microsoft for Windows 10

**Comment by cbednarski** [comment]
@LukB4ULeap Please create a new issue for that, and provide any relevant details there (what you tried, what didn't work as you expected). It seems to be unrelated to this one.

**Comment by mwhooker** [comment]
I'm +1 to using the `pb` package.

I would want to replace the progress bar in `common/download.go` with it, too. 

However, this is not something we're targeting for 1.0, so I'm going to close this. The best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by mwhooker** [comment]
see also #4364

**Comment by arizvisa** [comment]
Added the progress-bar as desired in the comments for this PR. I'm not sure what you guys want the look of the progress-bar to be, so feel free to update the PR. Or merge it please, the PR has been there for a pretty long time.
