### ISSUE TITLE
'sudo' is not recognized error when creating EC2 Windows AMI

### ISSUE THREAD

**Issue by amsharm** [mitchellh/packer#3580]
I'm trying to create a Windows 2012 R2 AMI with the chef-client provisioner. I've set the guest_os_type parameter to "Windows" and according to the Packer documentation, 'sudo' should not be used to run Chef. However, the Packer run indicates that it fails because it's trying to run 'sudo'. I'm not sure if I've configured something incorrectly. I've attached the Packer json template I'm using and the Packer log. Please let me know if I should provide any other information.

~~<script src="https://gist.github.com/amsharm/fd95aa895e81a4c3c6c2b52294d7fc30.js"></script>
[Packer files.zip](https://github.com/mitchellh/packer/files/286907/Packer.files.zip)~~
See [gist](https://gist.github.com/rickard-von-essen/25cd6a86b7676cccf0b01f9a63965acf) for log, template and bootstrap script.

**Comment by rickard-von-essen** [comment]
Try:
```json
  "prevent_sudo": "true",
```
It shouldn't effect windows according to the docs but reading the code I think it does.

**Comment by amsharm** [comment]
Perfect! Thanks so much

**Comment by cbednarski** [comment]
Thanks for the report, @amsharm! I'm going to re-open this because I think we should do this automatically when `guest_os_type` is windows.
