### ISSUE TITLE
Builder amazon-chroot and ansible provisioner does not work

### ISSUE THREAD

**Issue by wernerb** [mitchellh/packer#3583]
When amazon-chroot method is used with the ansible provisioner, the SSH connection is a success but after the ssh command is executed the session never completes leaving anssible hanging and waiting forever.

I tested some things:
- ansible when using different ssh connection types (paramiko etc) all also hang. ansible seems not to be the problem, but the combination of ssh server and chroot.
- i manually executed the SSH commands and then found it also hangs after returning the correct output. 
  I even made regular ssh connections such as:

```
ssh -vvvv 127.0.0.1 -p 58611  -i /tmp/ansible-key495979498 -o User=root 'ls'
```

which produces the correct output but never returns until I press "enter" during the ssh session which makes packer return some output. Here is the log of that ssh session: https://gist.github.com/wernerb/4d14e6b12eb0ab5bd194e36566f68b67

When I manually "close" the ssh connection (by pressing enter), stuff does happen on packer

```
2016/05/29 21:13:55 ui: ==> amazon-chroot: authentication attempt from 127.0.0.1:48612 to 127.0.0.1:58611 as root using publickey
==> amazon-chroot: authentication attempt from 127.0.0.1:48612 to 127.0.0.1:58611 as root using publickey
2016/05/29 21:13:55 packer: 2016/05/29 21:13:55 Executing: /bin/sh []string{"/bin/sh", "-c", "chroot /opt/builder/chroot/1464548759_574b3d97-5667-64bd-2796-824fbed46bcc/xvdk1 /bin/sh -c \"ls\""}
2016/05/29 21:13:57 packer: 2016/05/29 21:13:57 Chroot execution exited with '0': 'ls'
2016/05/29 21:13:57 packer: 2016/05/29 21:13:57 [INFO] RPC endpoint: Communicator ended with: 0
2016/05/29 21:13:57 [INFO] 120 bytes written for 'stdout'
2016/05/29 21:13:57 [INFO] 0 bytes written for 'stderr'
2016/05/29 21:13:57 [INFO] RPC client: Communicator ended with: 0
2016/05/29 21:13:57 [INFO] RPC endpoint: Communicator ended with: 0
2016/05/29 21:13:57 [INFO] 1 bytes written for 'stdin'
2016/05/29 21:13:57 packer: 2016/05/29 21:13:57 [INFO] 120 bytes written for 'stdout'
2016/05/29 21:13:57 packer: 2016/05/29 21:13:57 [INFO] RPC client: Communicator ended with: 0
2016/05/29 21:13:57 packer: 2016/05/29 21:13:57 [INFO] 0 bytes written for 'stderr'
2016/05/29 21:13:57 packer: 2016/05/29 21:13:57 [INFO] 1 bytes written for 'stdin'
```

In the above log `Chroot execution exited with` appears when I pressed enter during the manual ssh session to test. So I guess the exit status is not properly being detected when doing ssh -> chroot ?

Simple packer template here to reproduce: https://gist.github.com/wernerb/b880c20f30957d70b72417b8ba797f07
Full packer log here: https://gist.github.com/wernerb/6d8350c4dfb646f3f5c8ee3fef7430f4

Host platform: Redhat 7

**Comment by wernerb** [comment]
I changed the title to better reflect the problem. 
Being able to use the ansible provisioner with chroot would allow us to save minutes off our build time.

**Comment by mwhooker** [comment]
There've been a bunch of changes to the ssh communicator. Closing for now. Please open a new issue if you continue to run into this. We'll need to be able to reproduce the issue in order to help, which we can't do from just the json alone. 

Also try using the latest release of whatever OS your AMI is.

**Comment by rickard-von-essen** [comment]
Just a clarification, the `amazon-chroot` builder uses its own communicator (local chroot) and it's highly unlikely that it will work with the `ansible` provisioner (at least without modifications of the ansible communicator setup).
