### ISSUE TITLE
How can use override attributes from packer json file when using chef solo provisioner 

### ISSUE THREAD

**Issue by krishnagade18** [mitchellh/packer#3584]
**Override the attributes which are part of role file in chef**

```json
{
  "type": "chef-solo",
  "cookbook_paths": ["chef/cookbooks/vendor"],
  "run_list": [
    "recipe[cicada-jenkins-cookbook::default]",
    "recipe[cicada-jenkins-cookbook::support_tools]",
    "recipe[cicada-jenkins-cookbook::cft_seed_dsl]",
    "recipe[cicada-jenkins-cookbook::terraform_seed_dsl]"
  ]
}
```
In here i need to override attributes how can i pass them in packer

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

Please also read the documentation.
