### ISSUE TITLE
ansible provisioner doesn't find vault password

### ISSUE THREAD

**Issue by mblakele** [mitchellh/packer#3597]
- Packer Version: 0.10.1
- Host platform: OS X 10.11.5

I saw the request for debug log output and a test case but it'll take me some time to put those together. Sorry. Meanwhile I have a workaround that might help others.

Unexpected behavior: If an ansible playbook refers to variables from ansible-vault, `packer build fubar.json` fails with `Decryption failed` or similar. This means that ansible didn't have access to the vault password. In my case that password is in `~/.ansible/vault-password`.

Expected behavior:  ansible-playbook finds `~/.ansible/vault-password` so I expected packer to do the same.

Workaround: add `"extra_arguments": ["--vault-password-file", "/Users/fubar/.ansible/vault-password"]` to the provisioners json.

**Comment by cbednarski** [comment]
Thanks for the tip. If you'd like you can make a PR directly against the docs to include that.

> I saw the request for debug log output and a test case but it'll take me some time to put those together. 

If you're updating documentation this step is not necessary. If you think a code change is necessary I'd appreciate the test case since this helps write a validation test.
