### ISSUE TITLE
Docker Builder (map of strings to strings)

### ISSUE THREAD

**Issue by emoshaya-cognito** [mitchellh/packer#3600]
I need to use the Docker builder and mount some additional volumes.. Reading the documentation it says:

volumes (map of strings to strings) - A mapping of additional volumes to mount into this container. The key of the object is the host path, the value is the container path.

I tried this in my template but didn't work

"volumes": "/sys/fs/cgroup:/sys/fs/cgroup:ro"

* 'Volumes' expected a map, got 'string'
Finished: FAILURE

Could you please give me an example of a mapping of strings to strings?

**Comment by rickard-von-essen** [comment]
```json
  "volumes": {
    "/sys/fs/cgroup": "/sys/fs/cgroup:ro"
  }
```

I'm unsure about the `ro`.

**Comment by emoshaya-cognito** [comment]
@Rican7
