### ISSUE TITLE
Failed to initialize build 'virtualbox-iso': post-processor type not found: checksum

### ISSUE THREAD

**Issue by rrzaripov** [mitchellh/packer#3603]
- Packer Version: 0.10.1 windows 64-bit
- Host platform: Windows 7 64-bit
- Debug log [output ](https://gist.github.com/rrzaripov/b9450c95e4d2d9008e92eb0ec218309d)
- The example [template ](https://gist.githubusercontent.com/rrzaripov/6d14625dd2595ebb03a48ba65ef022d8/raw/f2b0954c72220b260b94d1d070eb17fd9d96be58/gistfile1.txt)

Plugin is missing in build or something wrong with my template? 
P.S. docs on packer.io have no chapter about checksum.

**Comment by rickard-von-essen** [comment]
The checksum post-processor is not released yet see [CHANGELOG.md](https://github.com/mitchellh/packer/blob/master/CHANGELOG.md).

If you want to use it you have to build from source see [CONTRIBUTING.md](https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md).
