### ISSUE TITLE
packer -v returns nonzero status code

### ISSUE THREAD

**Issue by captaincapsaicin** [mitchellh/packer#3605]
- Packer Version 10.1
- Host platform Mac OS X El Capitan 10.11.5
https://gist.github.com/captaincapsaicin/506ce156201937292b7093d46f30d3fa

```
$ packer -v
0.10.1
$ echo $?
1
```

**Comment by cbednarski** [comment]
Thanks for the report. This is a duplicate of https://github.com/mitchellh/packer/issues/3370.

**Comment by captaincapsaicin** [comment]
Ah thanks! That one eluded my brief search.

**Comment by cbednarski** [comment]
Yeah not easy to search for; I knew it was there already. :)
