### ISSUE TITLE
Azure vagrant post-processor provider

### ISSUE THREAD

**Issue by negul** [mitchellh/packer#3607]
Is there anything in the works for an Azure vagrant post-processor provider?

**Comment by boumenot** [comment]
No, but most of our efforts are directed by community need.  I don't know enough about the Vagrant post-processor to know if any work is needed or if it just works. 

@cbednarski, I do not recall reading post-processor specific code in the other builders. Is there anything the Azure builder needs to do?  Is this just a [doc](https://www.packer.io/docs/post-processors/vagrant.html) bug?

**Comment by cbednarski** [comment]
Azure is not natively supported by Vagrant. There is a [community plugin](https://github.com/Azure/vagrant-azure) but we'd need to see whether it's compatible. Assuming it is, though, we just need [a bit of glue](https://github.com/mitchellh/packer/tree/master/post-processor/vagrant) for the Azure provider.

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
