### ISSUE TITLE
Packer images for Azure are not always useable

### ISSUE THREAD

**Issue by russellseymour** [mitchellh/packer#3620]
I have a need to create a custom Windows image in Azure to assist in the rapid creation of a larger environment.  However I have not been able to create a consistent flow for creating useable machines.

The following table shows the scenarios that work and do not work.

| # | Scenario                                             | Configure | Sysprep | Packer Success? | Azure Success? |
|:--|:-----------------------------------------------------|:----------|:--------|:----------------|:---------------|
| 1 | AMP Windows                                          | false     | true    | true            | true           |
| 2 | AMP Windows with `chef-solo` provisioner             | true      | false   | true            | false          |
| 3 | AMP Windows with `chef-solo` provisioner and sysprep | true      | true    | false           | N/A            |

*Scenario 1*
This scenario works without issue, but is no different from the AMP image

*Scenario 2*
Uses `chef-zero` to create a chef workstation.  This completes and the image is accessible in Azure.  However when it comes to use the image, the Azure deployment times out.  The machine has been provisioned from the custom image, but it does not appear to be in the correct state for Azure to be able to use it properly.

```
"provisioners": [
  {
    "type": "chef-solo",
    "guest_os_type": "windows",
    "cookbook_paths": [
      "../cookbooks/vendored"
    ],
    "run_list": [
      "recipe[cad-workstation::default]"
    ]
  }
]
```

It seems strange that the `chef-solo` provisioner is upsetting things here, but that is the only difference between this an Scenario 1.

The cookbook installs a bunch of applications.  The default recipe can be seen here -  https://gist.github.com/russellseymour/1f68c265acd97e2648d76efef49d941e

*Scenario 3*
The previous scenario led to investigation which suggested that `sysprep` needed to be run on the machine by Packer.  However when this done Packer hangs at the end and does not complete, e.g. the prompt does not return.

```
"provisioners": [
  {
    "type": "chef-solo",
    "guest_os_type": "windows",
    "cookbook_paths": [
      "../cookbooks/vendored"
    ],
    "run_list": [
      "recipe[cad-workstation::default]"
    ]
  },
  {
    "type": "windows-shell",
    "inline": [
      "C:\\Windows\\System32\\sysprep\\sysprep.exe /quiet /generalize /oobe /quit"
    ]
  }
]
```

I will post a Gist for the output of this scenario when I have cleansed it so that I do advertise the secrets I use for Azure.

Is there anything that I am doing that is obviously wrong?

**Comment by boumenot** [comment]
Thank you for the great details, this helps immensely.

What is AMP, and is it relevant to the discussion?  A quick search did not turn up anything relevant to my eyes.

Azure caps VM deployment at 40 minutes, and then walks away and returns a failure.  I have seen issues where customers run out of time while *building* their VM. 

The Azure builder makes no effort beyond the API responses to determine success or not.  Even though Azure stops waiting after 40 minutes, the builder could ignore the error, and attempt to interrogate the VM for success.  This *seems* overly complicated to me, and I would prefer that we not do that.  There are valid scenarios where it takes more than 40 minutes to deploy a VM.

Scenario 2: 
If you connect to the VM, what **state** is it in?  Does the screenshot of the console show anything?  I need more details on the VM to debug this better.

Scenario 3:
I would use the "powershell" provisioner.  This is the one that we test with.  I think windows-shell executes cmd.exe over [WinRM][1].  If you use PowerShell you remove an unnecessary layer.  I do not know if that will solve the problem, but it is worth trying.

/quit exits sysprep.exe, but /shutdown will actually power off the VM when it's done.  This may be worth trying.  Killing the connection (via a shutdown) may be a strong enough force to move packer onto the next step in the build process.

[1]: https://www.packer.io/docs/provisioners/windows-shell.html

**Comment by russellseymour** [comment]
@boumenot AMP means Azure Marketplace - sorry for not expanding that in my original message.

I will try the PowerShell provisioner to see if that makes a difference.

I had tried `/shutdown` on the sysprep command as well as `quit` and both exhibited the same behaviour.  

I will do some testing with your suggestions and report back.

Thanks, Russell

**Comment by boumenot** [comment]
Some many TLAs, so little time.

@russellseymour, there was another issue raised with a [similar issue][1].  I do not know if this is your issue, but he reported that Windows builds were not completing.

> I've just managed to get it working. It was hanging because I wasn't deleting the unattend.xml file before sysprep.

> It's now taking just under 20 mins to build the images, although I'm not really doing anything taxing with the provisioners. Doesn't seem too bad!

I figured I would share in case it helps.

[1]: https://github.com/mitchellh/packer/pull/3575

**Comment by russellseymour** [comment]
@boument Thanks for that.

The given earlier to use the `powershell` provider has worked.  I have also found that there is a problem with the cookbook I am using which is causing other issues :(.

I apologise for raising an issue on this, but I really appreciate the help.

**Comment by boumenot** [comment]
No need to apologize.  I appreciate you raising an issue, self-resolving, and most importantly reporting back.  Too often people do not raise an issue, or do not report back.  We get better with community involvement.  Not to mention, this issue will help future searchers. :smile:
