### ISSUE TITLE
Please publish more information on the naming pattern of "Temporary AWS Security Groups" and the circumstances under which they are created

### ISSUE THREAD

**Issue by DarwinJS** [mitchellh/packer#3621]
This page: https://www.packer.io/docs/builders/amazon-ebs.html mentions the creation of temporary security groups and the advised role policy document allows it: https://www.packer.io/docs/builders/amazon.html

However, I have not seen any temporary security groups created during a packer run.

I have also removed the permissions for creating and deleting security groups and allowing ingresses and packer works fine.

I would like to create a policy that limits the security groups that can be operated on by name (not just limited to a VPC).

Otherwise, as the policy stands, the instance that packer runs on can delete any existing security group as well as create new ones that open up any ingress at all.

OK I found two references to the conditions under which these groups might be created.  On this page: https://www.packer.io/docs/builders/amazon-ebs.html

I found:

security_group_id (string) - The ID (not the name) of the security group to assign to the instance. By default this is not set and Packer will automatically create a new temporary security group to allow SSH access. Note that if this is specified, you must be sure the security group allows access to the ssh_port given below.

And:

vpc_id (string) - If launching into a VPC subnet, Packer needs the VPC ID in order to create a temporary security group within the VPC.

On this second one I am indeed launching into a VPC subnet - but do not see that it creates one.
I do have SSH in one of the security groups automatically assigned to instances - so not sure if this second one is accurate.

I guess I am missing information on what the security group names will look like so I can create AWS policies that only allow group names that follow the pattern to be created / deleted.

**Comment by mwhooker** [comment]
great idea. implemented in #4550. let me know what you thing
