### ISSUE TITLE
AWS Instance-backed provisioning broken due to instanceInitiatedShutdownBehavior

### ISSUE THREAD

**Issue by Yasumoto** [mitchellh/packer#3624]
It looks like the addition of `InstanceInitiatedShutdownBehavior` from PR #3556 should only be for EBS-backed images, as I'm now getting an error when trying to run `packer` with that applied.

- Packer Version: commit ab9621ab7d83a56eea02e11134edf8a941ed294d
- Host platform: ubuntu 14.04
- https://gist.github.com/Yasumoto/d265e9b7f50e0474e3a00aa5b0152a37

**Comment by cbednarski** [comment]
Thanks for the report! @patrobinson Do you think you can take a look at this?

**Comment by patrobinson** [comment]
Indeed Instance Store instances automatically terminate on shutdown so this parameter is invalid. I'll work on a PR to remove it for that provider.
