### ISSUE TITLE
azurerm - feature req - add the ability to specify the whole image name, not a prefix

### ISSUE THREAD

**Issue by tasquith** [mitchellh/packer#3626]
In order to maintain naming parity for our custom images across RS, GCE, AWS and AzureRM it would be handy if we could specify the whole image name, not just a prefix.

I understand the guid after the prefix is for uniqueness, however we'd like the option to control that ourselves - we currently use a timestamp.

**Comment by boumenot** [comment]
Unfortunately, the API is such that it only allows us to specify the prefix.  Everything after the prefix is assigned by *others*.  I think the names are confusing, and I think people would prefer more control over them.  I think a post-processor would be the correct solution in this case.  Are you interested in giving it a Go (pun intended)?

```go
type VirtualMachineCaptureParameters struct {
	VhdPrefix                *string `json:"vhdPrefix,omitempty"`
	DestinationContainerName *string `json:"destinationContainerName,omitempty"`
	OverwriteVhds            *bool   `json:"overwriteVhds,omitempty"`
}```

**Comment by tasquith** [comment]
No problem, cheers @boumenot! I'll take a look, I've not looked into post processors yet! I'll update you with my progress.

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
