### ISSUE TITLE
Community examples

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#3630]
Consul has a community tools page which includes things like python libraries https://www.consul.io/downloads_tools.html

There are actually a lot of Packer community resources too, like well-tested packer templates from joefitzgerald, bento, and others and some wrapper tools like [racker](https://github.com/aspring/racker).

Including these on Packer.io would help people get started using Packer.

Let's collect a few other thoughts / ideas here.

/cc @rickard-von-essen

**Comment by lfarnell** [comment]
I would be wiling to help out with this. I can consolidate some of the Repo's I've found around GitHub and create a page to insert into the docs

**Comment by rickard-von-essen** [comment]
:+1: I think this would help people alot. 
We should also point out in the intro/getting started pages that it's very hard to automate a OS installation from scratch, it's recommend to copy existing work and incrementaly adapt it and references the well-tested templates.

**Comment by mwhooker** [comment]
There's some work in #3860 we could base off of
