### ISSUE TITLE
(Azure builder) Packer Build hangs after adding provisioner 

### ISSUE THREAD

**Issue by deepak-shrivastava** [mitchellh/packer#3634]
Hi,

I am trying to run the packer build (using the builder type as "azure-arm"), but the build hangs and never gets complete. One thing that i am noticing that the temp resource group that the packer creates, it is not deleting the same as well. Is that the reason that the build is never complete??? Is this a known issue??

My template is as follows:-

{
"variables": {
"ssh_user": "centos",
"ssh_pass": null
},
"builders": [{
"type": "azure-arm",
"client_id": "...",
"client_secret": "...",
"resource_group_name": "...",
"storage_account": "...",
"subscription_id": "...",
"tenant_id": "...",
"capture_container_name": "packercentoscontainer",
"capture_name_prefix": "prefixcentos",
"image_publisher": "OpenLogic",
"os_type" : "Linux",
"image_offer": "CentOS",
"image_sku": "7.1",
"image_version": "latest",
"location": "East Asia",
"ssh_pty" : "true",
"ssh_username": "{{user ssh_user}}",
"ssh_password": "{{user ssh_pass}}"
}
],
"provisioners": [{
"execute_command": "echo '{{user ssh_pass}}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'",
"inline": [
"yum update -y",
"/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
],
"inline_shebang": "/bin/sh -x",
"type": "shell",
"skip_clean": true
}]
}

**The logs are as follows:**

_azure-arm output will be in this color.

==> azure-arm: Preparing builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: Creating resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-rwd8qp4pn4'
==> azure-arm:  -> Location          : 'East Asia'
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-rwd8qp4pn4'
==> azure-arm:  -> DeploymentName    : 'pkrdprwd8qp4pn4'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-rwd8qp4pn4'
==> azure-arm:  -> DeploymentName    : 'pkrdprwd8qp4pn4'
==> azure-arm: Getting the public IP address ...
==> azure-arm:  -> ResourceGroupName   : 'packer-Resource-Group-rwd8qp4pn4'
==> azure-arm:  -> PublicIPAddressName : 'packerPublicIP'
==> azure-arm:  -> Public IP           : '13.75.123.156'
==> azure-arm: Waiting for SSH to become available...
==> azure-arm: Connected to SSH!
==> azure-arm: Provisioning with shell script: /tmp/packer-shell431138205
    azure-arm: + yum update -y
    azure-arm: Loaded plugins: fastestmirror, langpacks
    azure-arm: You need to be root to perform this command.
    azure-arm: + sudo /usr/sbin/waagent -force -deprovision+user
    azure-arm:
    azure-arm: We trust you have received the usual lecture from the local System
    azure-arm: Administrator. It usually boils down to these three things:
    azure-arm:
    azure-arm: #1) Respect the privacy of others.
    azure-arm: #2) Think before you type.
    azure-arm: #3) With great power comes great responsibility.
    azure-arm:
    azure-arm: [sudo] password for packer:
==> azure-arm: 
==> azure-arm: Cleanup requested, deleting resource group .._.

I am trying to build using the command

packer build -var ssh_pass=some_secret_password  centos.json

**Comment by paulmey** [comment]
Hmmm, strange. The ssh_pty=true option is known to sometimes yield this kind of result. I'll see if we can repro this behavior or if we need more info... CC: @boumenot

**Comment by boumenot** [comment]
I cannot reproduce this using OpenLogic CentOS 7.2.  I don't see how this is a bug against builder/azure.

**Comment by paulmey** [comment]
@deepak-shrivastava I also can't repro it. I ran with your config above and had no problems [(logs)](https://gist.github.com/paulmey/d67a965e46a542333f56126c608c0524). Can you reproduce this consistently for you or is it something that happens once in a while?

**Comment by paulmey** [comment]
btw, the commands in the output in the initial message in this thread do not seem to align with the builder config:

output: 
```
azure-arm: + yum update -y
azure-arm: + sudo /usr/sbin/waagent -force -deprovision+user
```
v.s.config
``` json
"inline": [
"yum update -y",
"/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
]
```

**Comment by deepak-shrivastava** [comment]
Hi,
@paulmey you are correct. you can see a mismatch in the output logs as when i am giving the inline command as "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync" i am getting the below output. As i thought is a permission issue, i added sudo before it.

Logs if when i used the command "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync " 

azure-arm output will be in this color.

==> azure-arm: Preparing builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: Creating resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-2chk3z993q'
==> azure-arm:  -> Location          : 'East Asia'
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-2chk3z993q'
==> azure-arm:  -> DeploymentName    : 'pkrdp2chk3z993q'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-2chk3z993q'
==> azure-arm:  -> DeploymentName    : 'pkrdp2chk3z993q'
==> azure-arm: Getting the public IP address ...
==> azure-arm:  -> ResourceGroupName   : 'packer-Resource-Group-2chk3z993q'
==> azure-arm:  -> PublicIPAddressName : 'packerPublicIP'
==> azure-arm:  -> Public IP           : '52.175.31.150'
==> azure-arm: Waiting for SSH to become available...
==> azure-arm: Connected to SSH!
==> azure-arm: Provisioning with shell script: /tmp/packer-shell889749655
    azure-arm: + yum update -y
    azure-arm: Loaded plugins: fastestmirror, langpacks
    azure-arm: You need to be root to perform this command.
    azure-arm: + /usr/sbin/waagent -force -deprovision+user
    azure-arm: [Errno 13] Permission denied: '/var/log/waagent.log'
    azure-arm: [Errno 13] Permission denied: '/var/log/waagent.log'
    azure-arm: [Errno 13] Permission denied: '/var/log/waagent.log'
    azure-arm: Traceback (most recent call last):
    azure-arm: File "/usr/sbin/waagent", line 6266, in <module>
    azure-arm: main()
    azure-arm: File "/usr/sbin/waagent", line 6232, in main
    azure-arm: sys.exit(Deprovision(force, True))
    azure-arm: File "/usr/sbin/waagent", line 6117, in Deprovision
    azure-arm: SwitchCwd()
    azure-arm: File "/usr/sbin/waagent", line 6160, in SwitchCwd
    azure-arm: CreateDir(LibDir, "root", 0700)
    azure-arm: File "/usr/sbin/waagent", line 2350, in CreateDir
    azure-arm: ChangeOwner(dirpath, user)
    azure-arm: File "/usr/sbin/waagent", line 2339, in ChangeOwner
    azure-arm: os.chown(filepath, p[2], p[3])
    azure-arm: OSError: [Errno 1] Operation not permitted: '/var/lib/waagent'
==> azure-arm: 
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Script exited with non-zero exit status: 1

**Comment by deepak-shrivastava** [comment]
Hi,
@paulmey . this is with regards to your question "I also can't repro it. I ran with your config above and had no problems (logs). Can you reproduce this consistently for you or is it something that happens once in a while?"

I am getting this error every single time. What are all the things that i should be checking in here?? Can it be related to the face that i am using "Free Trial" as my Subscription???

**Comment by paulmey** [comment]
Hey @deepak-shrivastava, this error is definitely not related to your subscription. The VM is getting created just fine. In your initial log, it looks like the provisioner is hanging at a sudo password prompt (`azure-arm: [sudo] password for packer:`).
Also, you mentioned above you needed to add sudo to the individual commands, which is really not necessary if your provisioner config is as you say it is in your initial message:
```
"provisioners": [{
  "execute_command": "echo '{{user `ssh_pass`}}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'",
  "inline": [
    "yum update -y",
    "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
  ],
  "inline_shebang": "/bin/sh -x",
  "type": "shell",
  "skip_clean": true
}]
```
Note that the `execute_command` here wraps the execution of your `inline` commands with `sudo` (I had to add back-ticks around `ssh_pass` to make that work again). Please check your config to see that it contains the same `execute_command` value for each shell provisioner.

If you still have issues, please share your exact config after removing your subscription id, tenant id, client id and secret. Let us know how it goes.

**Comment by deepak-shrivastava** [comment]
Hi @paulmey ...

It seems to be working now. Although i am not really sure why it was not working in my previous attempts. Let me play around a bit and will come back in case i see the behaviour again.

Thanks a ton again @paulmey 

Closing this issue as it is not reproducible now.

**Comment by paulmey** [comment]
Thanks for reporting back and closing the issue!
