### ISSUE TITLE
Support for "winrm_wait_timeout"

### ISSUE THREAD

**Issue by Wenzel** [mitchellh/packer#3635]
For the moment it is not possible to specify the timeout when using `WinRM` communicator.
The key `winrm_wait_timeout` is not recognized by Packer.

It would be great to be able to set the timeout like we already do with `ssh_wait_timeout`.

- Packer Version : `0.10.1`
- Host platform : `Fedora 23 x64`
- Debug log output : [packer.log](https://gist.github.com/Wenzel/2717b5a15621d3d637905f54741ad347)
- JSON template : [windows_7.json](https://gist.github.com/Wenzel/192497b2ad435d4e39a93474c5b9870e)

**Comment by Wenzel** [comment]
It seems that this feature is already [implemented by Packer](https://github.com/mitchellh/packer/blob/9c9f8cd45160192587a90e95413aaa26fc21b762/helper/communicator/config.go#L40), but no very well documented :)

Therefore I am closing this issue.

**Comment by rickard-von-essen** [comment]
It's actually also in the docs https://www.packer.io/docs/templates/communicator.html#winrm_timeout
