### ISSUE TITLE
Feature request: allow specifying alternative EC2 volume to create AMI from

### ISSUE THREAD

**Issue by amosshapira** [mitchellh/packer#3636]
In order to create AMI's from ISO files, we currently have to jump through hoops like using `amazon-scratch` builder or pivoting between the EC2 root volume and a separate data volume.

This is described nicely in http://blog.sorah.jp/2015/05/11/building-ami-from-scratch-using-packer-amazon-ebs-builder

However, it might be possible to avoid all this complexity if it was possible to just tell the default built-in Packer builder to burn the snapshot from a specific volume instead of always taking the root volume.

I'm thinking of simply being able to specify something like specifying `device_to_ami: "/dev/sdf"` to the AMI builder configuration.

**Comment by lorengordon** [comment]
This might be a dup: https://github.com/mitchellh/packer/issues/3024

**Comment by amosshapira** [comment]
Yes it is, @lorengordon, the last comment also refers to exactly the same URL I give above.
