### ISSUE TITLE
 Support VBoxSDL 

### ISSUE THREAD

**Issue by shibumi** [mitchellh/packer#3645]
It would be neat to have a way to set in the Vagrantfile that vagrant should start the VM with VBoxSDL.
So a lot of people would have less overhead...

**Comment by rickard-von-essen** [comment]
See https://www.packer.io/docs/post-processors/vagrant.html#vagrantfile_template

**Comment by shibumi** [comment]
@rickard-von-essen 
I have no idea how this should help? I can use a vagrant_template for specify something that is valid in all other vagrantfiles but thats not a howto how I can enable VBoxSDL Support.

I Don't want to install all the Qt stuff for GUI for virtualbox. Virtualbox brings VboxSDL for this case..how can I use this with vagrant?

**Comment by rickard-von-essen** [comment]
I'm closing this since this is a Vagrant issue. If you submit a issue on [vagrant](https://github.com/mitchellh/vagrant) please link it here.

**Comment by shibumi** [comment]
Oh Sorry, I thought this is the vagrant bugtracker. Seems like I posted the issue in the wrong tab. 
https://github.com/mitchellh/vagrant/issues/7520
