### ISSUE TITLE
azure setup script: unknown option: --type

### ISSUE THREAD

**Issue by dabdine-r7** [mitchellh/packer#3653]
Storage account creation fails when running the azure-setup.sh script referenced from the [azure setup](https://www.packer.io/docs/builders/azure-setup.html) page: https://github.com/mitchellh/packer/blob/master/contrib/azure-setup.sh

```
Found azure-cli version: 0.10.1
Found jq version: jq-1.5
```

It seems though the azure cli has changed the parameters for `azure storage account create`:

```
help:    Create a storage account
help:    
help:    Usage: storage account create [options] <name>
help:    
help:    Options:
help:      -h, --help                                             output usage information
help:      -v, --verbose                                          use verbose output
help:      -vv                                                    more verbose with debug output
help:      --json                                                 use json output
help:      --sku-name <skuName>                                   the SKU name (LRS/ZRS/GRS/RAGRS/PLRS)
help:      --kind <kind>                                          the account kind
help:      --access-tier <accessTier>                             the access tier (Hot/Cool)
help:      --enable-encryption-service <enableEncryptionService>  specifies the service which needs to enable encryption settings
help:      --custom-domain <customDomain>                         the custom domain
help:      --subdomain                                            whether uses the 'asverify' subdomain to preregister the custom domain
help:      --tags <tags>                                          the account tags. Tags are key=value pairs and separated with semicolon(;)
help:      -l, --location <location>                              the location
help:      -g, --resource-group <resourceGroup>                   the resource group name
help:      -s, --subscription <id>                                the subscription id
help:    
help:    Current Mode: arm (Azure Resource Management)
```

There is no `--type` parameter. Instead, LRU is now specified with `--sku-name`, and there are two new options named `--kind` and `--access-tier`. 

To address this, I updated this line: https://github.com/mitchellh/packer/blob/master/contrib/azure-setup.sh#L129 to:

```
azure storage account create -g $meta_name -l westus --sku-name LRS --kind Storage $meta_name
```

I am new to Azure, so I'm unsure if the SKU, kind and access tier are the most cost effective means to guide people that use the script for initial setup. There is a BlobStorage option, but from what I've experienced, it isn't available in West US (the default location the script uses), and I'm unclear whether you can use BlobStorage to house VM images.

**Comment by boumenot** [comment]
Thank you for logging an issue.  Would you please send a PR with your fixes.

The answer to your question is that it depends.  If you just want to kick the tires how much cost are you going to incur for a **short** period of time.  What types of features are you going to evaluate?

LRS is _likely_ like the right choice for just trying things out ([docs][1]).
Storage is _likely_ the right choice for just trying things out ([FAQ][2]).
Access Tier does not matter if kind is Storage.

[1]: https://azure.microsoft.com/en-us/documentation/articles/storage-redundancy/
[2]: https://azure.microsoft.com/en-us/pricing/details/storage/

**Comment by hectoralicea** [comment]
I came across the exact issue, and I still cannot find the documentation which shows the options for --kind option.  azure help does not list all the kind options.

**Comment by boumenot** [comment]
I logged an [issue][1] against the Azure XPlat-CLI concerning this.  The available options are 'Storage' and 'BlobStorage'.  Storage is the correct value in this case.

The [FAQ][2] has details, but the relevant part is below.


> What is a Blob Storage Account and how is it different from a general purpose Storage Account?
>
> Blob Storage Account is a storage account specialized for storing data as blobs and allows users to specify an access tier based on the frequency of access for the data in that account. General purpose storage accounts can be used to store Blobs as well as Files, Disks, Tables, Queues.

[1]: https://github.com/Azure/azure-xplat-cli/issues/3005
[2]: https://azure.microsoft.com/en-us/pricing/details/storage/
