### ISSUE TITLE
unknown configuration key "encrypted_data_bag_secret_path"

### ISSUE THREAD

**Issue by delta440** [mitchellh/packer#3654]
Perhaps I'm just being dim, but whenever I try to use the "encrypted_data_bag_secret_path" variable with the chef-client provisioner I get the following error:     
     
`docker output will be in this color.

1 error(s) occurred:

* unknown configuration key: "encrypted_data_bag_secret_path"
`

Packer Version: 0.10.1     
Host platform: Ubuntu 14.04.3
Packer Debug Log: https://gist.github.com/delta440/b86cf8238b4e270dfb700c685f971043 
Template:
```json
{
    "builders": [
        {
            "type": "docker",
            "image": "{{user `BIMAGE`}}",
            "commit": true
        }
    ],
    "provisioners": [
        {
            "type": "chef-client",
            "server_url": "{{user `CHEF_URL`}",
            "run_list": ["role[{{user `ROLE`}}]"],
            "chef_environment": "{{user `ENVIRONMENT`}}",
            "validation_client_name": "packer-validator",
            "validation_key_path": "validation.pem",
            "encrypted_data_bag_secret_path": "/tmp/test/",
            "skip_install": true
        }
    ],
    "post-processors": [
        [
            {
                "type": "docker-tag",
                "repository": "{{user `REPO`}}",
                "tag": "latest",
                "force": true
            },
            "docker-push"
        ]
    ]
}
```

Anything with the "encrypted_data_bag_path" variable should work though

**Comment by rickard-von-essen** [comment]
Reinstall and be sure to follow the note on the [download page](https://www.packer.io/downloads.html) 

You are running an old plugin.
