### ISSUE TITLE
overwrite configuration in vsphere post-processor broken

### ISSUE THREAD

**Issue by sunckell** [mitchellh/packer#3657]
Packer Version: 0.10.1
Ovftool Version: 4.1.0 (build-3018522)
Host Platform:  Windows 7 Enterprise

  "post-processors": [
 
    {
      "type": "vsphere",
      "cluster": "{{ user `vsphere_cluster` }}",
      "overwrite": "true",
      "datacenter": "{{ user `vsphere_datacenter` }}",
      "datastore": "{{ user `vsphere_datastore` }}",
      "host": "{{ user `vsphere_host` }}",
      "username": "{{ user `vsphere_user` }}",
      "password": "{{ user `vsphere_pass` }}",
      "vm_network": "{{ user `vsphere_vm_network` }}",
      "vm_folder": "{{ user `vsphere_vm_folder` }}",
      "vm_name": "{{ user `vsphere_vm_name` }}",
      "disk_mode": "thin"
    }
  ],
 
When the overwrite configuration is used, the flag is placed in the wrong location in the underlying ovftool command.
 
It is being placed after the target location instead of before the source location
 
It is producing the following error:
 
https://gist.github.com/sunckell/5ad3d9f30ffd99af75e54e97a6b4d7c6

**Comment by cbednarski** [comment]
Thanks for the report!

**Comment by sunckell** [comment]
I just checked out and built the master (0.10.2).  Everything is resolved there....

Should have checked there first.

**Comment by todd-dsm** [comment]
@sunckell I'm seeing the same overwrite error in the 'vsphere' post-processors. How did you get Packer 0.10.2? I only see tags for Packer </= 0.10.1.

**Comment by sunckell** [comment]
I built it from the master with details from the contrib file:
https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md

**Comment by todd-dsm** [comment]
Thanks man, saw that - moments after I asked; reading is good.
