### ISSUE TITLE
azure: WinRM Certificate Should Use Environment's Cloud App Suffix

### ISSUE THREAD

**Issue by boumenot** [mitchellh/packer#3664]
The method createCeritifcate(), which is used to create a temporary WinRM certificate uses a hostname of the following form.

``` go
    host := fmt.Sprintf("%s.cloudapp.net", c.tmpComputeName)
```

The value **cloudapp.net** should not be hardcoded, and instead should be determined by the user's current environment.

This is a minor issue.  The fix is for aesthetics not functionality.

**Comment by boumenot** [comment]
I opened a [PR][1] against Azure/go-autorest to add support for VM DNS Suffix, which is needed to address this issue.

[1]: https://github.com/Azure/go-autorest/pull/93

**Comment by mwhooker** [comment]
Looks like the upstream PR has been merged.

Would be great to see a PR for this, but going to mark this as post-1.0 and close it since it's not a feature we'll be working on for 1.0
