### ISSUE TITLE
Errors building fork of packer

### ISSUE THREAD

**Issue by ebelew** [mitchellh/packer#3675]
System: OS X 10.11.5
GoLang: (using brew) go version go1.6.2 darwin/amd64

Sample error:
`builder/amazon/chroot/builder.go:140: cannot use config (type *"github.com/mitchellh/packer/vendor/github.com/aws/aws-sdk-go/aws".Config) as type *"github.com/ebelew/packer/vendor/github.com/aws/aws-sdk-go/aws".Config in argument to "github.com/ebelew/packer/vendor/github.com/aws/aws-sdk-go/aws/session".New`

I forked packer to attempt to fix a bug and create a pull request, but when I tried to build locally after doing a `go get github.com/ebelew/packer`, it fails.

My Steps:

First, I made sure it would build successfully using original source:
 1. Forked using button on github
 1. `go get github.com/mitchellh/packer`
 1. `cd $GOPATH/src/github.com/mitchellh/packer`
 1. `make` -> Successful

Next, I tried to build my fork:
 1. Forked using button on github
 1. `go get github.com/ebelew/packer`
 1. `cd $GOPATH/src/github.com/ebelew/packer`
 1. `make` -> Failed (Log: https://gist.github.com/ebelew/26c8788ecc9b20413b016179f19a5189)

**Comment by rickard-von-essen** [comment]
To build your fork do:
```shell
cd $GOPATH/src/github.com/mitchellh/packer 
git remote add ebelew ssh://git@github.com/ebelew/packer
git checkout ebelew/master
make
```

(From the top of my head, typed on my mobile)

**Comment by ebelew** [comment]
These instructions should probably be added to Contributing.MD to avoid confusion.
