### ISSUE TITLE
Packer's command line parsing module doesn't appear to reflect the behavior of the documentation

### ISSUE THREAD

**Issue by dragon788** [mitchellh/packer#3677]
Packer's command line parsing module doesn't appear to reflect the behavior of the documentation. In the documentation it mixes space ``` `and equals`=`as valid separators for the -only -var -var-file and possibly other options. I attempted to validate a template with a var-file and if I used the`-var-file=vars.json`syntax it failed to find the file (seems to drop the extension), but if I used the`-var-file vars.json``` it was correctly found.

This may be a pathing issue in the helpers function, or it is detecting it incorrectly based on the presence or absence of the equals `=`.

Packer's documentation (built in):

```
Usage: packer validate [options] TEMPLATE

...
Options:

  -syntax-only           Only check syntax. Do not verify config of the template.
  -except=foo,bar,baz    Validate all builds other than these
  -only=foo,bar,baz      Validate only these builds
  -var 'key=value'       Variable for templates, can be used multiple times.
  -var-file=path         JSON file containing user variables.
```

Describe the problem and include the following information:
- Packer Version = 0.10.1
- Host platform = Windows 10 (PowerShell used as cmd interpreter)
- Debug log output from `PACKER_LOG=1 packer validate -var-file=vars.json template.json`.
- This includes runs both with and without equals `=`
  https://gist.github.com/dragon788/163aa6b8221ba9108864ca01a8592358
- The _simplest example template and scripts_ needed to reproduce the bug.
  `git clone https://github.com/boxcutter/ubuntu && packer validate -var-file=ubuntu16.04-desktop.json ubuntu.json`

**Comment by rickard-von-essen** [comment]
> -var-file= vars.json

Includes a space in front of the equals sign. Was that intentional? If you remove the space it should work. I.e.
`-var-file=vars.json`

**Comment by rickard-von-essen** [comment]
Closing since no reply from author.

**Comment by dragon788** [comment]
@rickard-von-essen Sorry about that, hadn't seen this update in the deluge of GitHub emails. The space wasn't intentional, but it doesn't work both ways in my experience. I'll give it a try again, but the whole reason  I filed the issue was -var-file 'var-file.json' worked but -var-file=var-file.json didn't. Not sure if the quoting matters either, but I would expect it to assume spaces as the delimiters if it wasn't quoted.

**Comment by mwhooker** [comment]
seems to work fine for me

```
~/dev/packertest/packer-test-boxes/boxcutter-ubuntu (master ✔) ᐅ packer validate -var-file ubuntu1604-desktop.json ubuntu.json
Template validated successfully.
~/dev/packertest/packer-test-boxes/boxcutter-ubuntu (master ✔) ᐅ packer validate -var-file=ubuntu1604-desktop.json ubuntu.json
Template validated successfully.
```

please open a new issue if you continue to encounter this.
