### ISSUE TITLE
Packer validate doesn't test existence of floppy files (though it does scripts and templates)

### ISSUE THREAD

**Issue by dragon788** [mitchellh/packer#3678]
When running ```packer validate``` with a template that requires floppy files, it tests the presence of any scripts referenced in the scripts variable, and it also tests the existance of any Vagrant template files, but it does not verify the existence of the floppy files which results in a failing build run even if the template definitely requires them and the validate returned successfully.

- Packer Version = 0.10.1
- Host platform = Windows 10 (PowerShell as cmd interpreter)
- The _simplest example template and scripts_ needed to reproduce the bug.
```git clone https://github.com/boxcutter/ubuntu && mv http/preseed.cfg http/preseed.cfg.bak && packer validate -var-file ubuntu16.04-desktop.json ubuntu.json && packer build -var-file ubuntu16.04-desktop.json ubuntu.json```

**Comment by ricardclau** [comment]
Hey @rickard-von-essen happy to give this a go, would appreciate some feedback at #3756 before I go change a good number of files using floppies :)
