### ISSUE TITLE
Provide Azure ARM tagging functionality

### ISSUE THREAD

**Issue by maurorappa** [mitchellh/packer#3679]
Hi,

I would like to have a way to create a VM in Azure via ARM with a set of tags.
My config is exactly like the example one, but due to internal policy I have to specify some tags (for billing), the Azure reply is:

```
"\\"error\\\": {\\r\\n    \\\"code\\\": \\\"RequestDisallowedByPolicy\\\",\\r\\n    \\\"message\\\": \\\"The resource action 'Microsoft.Network/virtualNetworks/write' is disallowed by one or more policies. Policy identifier(s): '/subscriptions/4c335e3a-f3dibioboiboib816853a22a/providers/Microsoft.Authorization/policyDefinitions/POLICY-ENFORCE-TAGS-01'.\\\"\\r\\n  }\\r\\n}\"}]}}" "
```

is there an already implemented way to achieve this?
Thanks!

**Comment by boumenot** [comment]
Do you just need tags on the VM, or do you need them on any other resource(s)?  I ask because the error message is flagged for a virtualNetwork.

**Comment by maurorappa** [comment]
I would like to start tagging the VM, but since a tag is useful for any object creation we could tag all subsequent internal calls :)
