### ISSUE TITLE
Refresh github.com/Azure/go-autorest for German Datacenter support

### ISSUE THREAD

**Issue by chgeuer** [mitchellh/packer#3680]
Please update the godeps for github.com/Azure/go-autorest to 0a0ee7d5b9b1b3d980434cbb0afff33e9ca9e907 or later, so that the "AzureGermanCloud" environment becomes visible. 

Currently when I use an AzureEnvironment with value "AzureGermanCloud" it says "unknown environment". 

https://github.com/Azure/go-autorest/commit/0a0ee7d5b9b1b3d980434cbb0afff33e9ca9e907

**Comment by boumenot** [comment]
Will do.

**Comment by chgeuer** [comment]
Christopher, many thanks for taking that over. Before I figured out that the endpoints were in a dependency (I just patched the vendors directory myself), I saw that packer by default tried to use the "regular" Azure AD (at the `login.microsoftonline.com` address), rather than `microsoftonline.de`. I have a subscription in the German data center, so let me know if you need me to test something.

```
POST https://login.microsoftonline.com/...my-subscription..../oauth2/token?api-version=1.0 HTTP/1.1
Host: login.microsoftonline.com
User-Agent: Go-http-client/1.1
Content-Length: 274
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

client_id=...&client_secret=...&grant_type=client_credentials&resource=https%3A%2F%2Fmanagement.microsoftazure.de%2F
```

and

```
GET https://login.microsoftonline.de/...my-subscription..../OAuth2/authorize?client_id=...&resource=https%3a%2f%2fmanagement.microsoftazure.de%2f&response_type=token&api-version=1.0&redirect_uri=https%3a%2f%2flogin.microsoftonline.com%2f.....%2fNationalCloudFederation%3fslice%3dTestSlice%26dc%3dPROD-BY1-001&state=... HTTP/1.1
Host: login.microsoftonline.de
User-Agent: Go-http-client/1.1
Referer: https://login.microsoftonline.com/.../oauth2/token?api-version=1.0
Accept-Encoding: gzip
```
