### ISSUE TITLE
Provide a way to make use of the commit feature "--change" to create docker images 

### ISSUE THREAD

**Issue by chilicat** [mitchellh/packer#3687]
The docker command provides a flag --change which allows to define docker instructions like:
- ENTRYPOINT
- ENV
- EXPOSE

See docker documentation: https://docs.docker.com/engine/reference/commandline/commit/

We could extend the docker build instruction:

```
{
  "type": "docker",
  "image": "ubuntu",
  "commit": true
  "commit-change": [
        "ENTRYPOINT /bin/myapp",
        "ENV debug true",
        "ENV otherEnv someValue",
        "EXPOSE 80"
   ]
}
```

We could also think about a more controlled data model like:

```
  "commit-change":  {
      "entrypoint": "/bin/myapp",
      "env": {
             "debug": true,
            "otherEnv": "someValue"
       },
       expose: [ 80, ... ]
}
```

Use Case:
As a developer I want to be able to define typical docker instruction like ENTRYPOINT and EXPOSE in order to make the resulting docker image easier to use (and conform to our internal docker container guidelines). 

I have seen plugins which allow to achieve a similar result but I would really like to see support for docker instructions in the packer core.

**Comment by cbednarski** [comment]
Thanks for the feedback. I agree this is a gap and I would like to support Dockerfile features better in Packer. I was not aware of the --change flag. Thanks for pointing that out!
