### ISSUE TITLE
Simultaneous amazon-ebs builds lead to authentication failure

### ISSUE THREAD

**Issue by mixmatch** [mitchellh/packer#3689]
Running multiple packer builds simultaneously with amazon-ebs causes slowest builds to fail with:
AuthFailure: AWS was not able to validate the provided access credentials
status code: 401, request id

It does seem that each packer process is using unique temporary key pairs, but it's possible that the clean up of one build is somehow interfering with the AWS authentication for builds that have not completed?
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...

I'm running multiple independent packer builds(seperate templates) with the same AWS credentials used for each.

Packer 0.10.1
Windows 8 host
[Example Build Output](https://gist.github.com/mixmatch/82906408dbec376dd3e76625db71a8da)
[Example Template](https://gist.github.com/mixmatch/45e1e81bd87c9d420c1143259520f3fc)

**Comment by cbednarski** [comment]
Thanks for the report. I suspect the same is happening with [security groups](https://github.com/mitchellh/packer/issues/3627). Unfortunately I don't think the same workaround applies here.

**Comment by mixmatch** [comment]
I'm running 4 separate packer builds for four separate templates in same directory, like:
.\packer.exe build ".\Templates\server1.json"
.\packer.exe build ".\Templates\server2.json"
.\packer.exe build ".\Templates\server3.json"
.\packer.exe build ".\Templates\server4.json"

my AWS_SESSION_TOKEN env variable is actually not set when these are kicked off, so I'm not exactly sure how packer is managing creds during the process.

**Comment by mixmatch** [comment]
The more I test, the more this issue seems intermittent. Not sure if it is a bug in packer or an issue with reliability of the AWS API.

**Comment by mixmatch** [comment]
I resolved this by generating new aws credentials with session token per instance of packer and passing in as -var instead of setting as environmental variables one time and having all packer instances try to use same creds.

**Comment by rickard-von-essen** [comment]
Please reopen if you can repro this with 0.12.2.
