### ISSUE TITLE
Packer.exe 0.10.1 flagged as Trojan.Ebowla.b

### ISSUE THREAD

**Issue by Tiberriver256** [mitchellh/packer#3691]
Packer binary getting flagged as Trojan.Ebowla.b via heuristic scanning.

- Packer Version   0.10.1
- Host platform      Windows

https://www.virustotal.com/en/file/623013056dc662f29817dce6bd31e6fb669883a35ea9311951bbcea4eb9c59f7/analysis/1467922549/

The only scanner showing detection on VirusTotal is JiangMin but Kaspersky in my corporate environment is also picking up this file as Trojan.Win32.Ebowla.jl

**Comment by cbednarski** [comment]
Thanks for the report. This is likely a false positive from your virus scanner for the go runtime. See also [this](http://security.stackexchange.com/questions/129388/does-golang-version-1-6-2-contain-a-trojan) and [this](https://www.virustotal.com/en/file/9c853bbb54734ddc54c1d57f6315724deb1a3878a3c0ad36b6fdc0e14a7be300/analysis/1467834510/). You can verify the [checksums](https://releases.hashicorp.com/packer/0.10.1/) of your release binaries using our [GPG key](https://www.hashicorp.com/security.html) to verify you have an authentic release.

If you believe there is a vulnerability or security problem in packer, please contact us via security@hashicorp.com. There are additional details on our [security page](https://www.hashicorp.com/security.html). For issues pertaining to your virus scanner and resolving any false positives, please reach out to your security vendor.
