### ISSUE TITLE
Feature: Packer aws builder should support kickstart http_server

### ISSUE THREAD

**Issue by elconas** [mitchellh/packer#3695]
We use packer to build unified images for Vagrant/AWS/VMWare and other plattforms. We kickstart on all platforms (including AWS) with a unified ks.cfg file. This allows maximum compatibility and support for LVM Images in AWS. For this we created a kickstart base image, that has all anaconda installer files in local filesystem and a "ks=http://..../ks.cfg" grub boot line in AWS. This base image is used by packer to bootstrap the machine.

However it seems that the AWS builder does not support starting an http server, so we can not run: 

BUILDHOST# packer build --only aws CONFIG

And the installer has ks=https://BUILDHOST/packer configured allowing our reverse proxy to pass through to packer. 

To support out use case, packer should support:
- Starting a HTTP Server for aws builder (as with other builders)
- HTTP Port must specified (http_port_min,http_port_max) as with other builders
- Optionally: The HTTP Server should be a core feature of all cloud provisioners (e.g. azure too)

**Comment by rickard-von-essen** [comment]
PR's are welcome! 

Could provide a working example (files and aws cli commands to run this by hand). That will simplify getting started with implementing this and testing. 

In the meantime you could build on something else and use the aws import post-processor.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by maschinetheist** [comment]
QEMU builder supports that. Possibly you could run the Packer builder on a bare metal AWS instance since those possibly might support QEMU/KVM.
