### ISSUE TITLE
qemu builder new features from 0.9.0 not working in 0.10.1

### ISSUE THREAD

**Issue by juaningan** [mitchellh/packer#3701]
Hi, I've noticed that some changes in changelog for qemu builder are not working in latest releases:

In 0.9.0 changelog you can read:
builder/qemu: qcow2 images are now compacted by default [GH-2748]
builder/qemu: qcow2 images can now be compressed [GH-2748]
builder/qemu: Now specifies virtio-scsi by default [GH-2422]

but if I run Packer 0.10.1 in Ubuntu Xenial I get errors using that options.

```
2 error(s) occurred:

* unknown configuration key: "disk_compression"
* unknown configuration key: "skip_compaction"
```

```
1 error(s) occurred:

* unrecognized disk interface type
```

virtio-scsi: https://gist.github.com/juaningan/e3d8f5e304011ef7a1104fdcb09f0b49
compression: https://gist.github.com/juaningan/c8919b7f1364a541613142b60bed4bc8
packer.json: https://gist.github.com/juaningan/4ddf3d26b049a4a480faa02100aea98f

**Comment by rickard-von-essen** [comment]
Full debug log,  please. (`PACKER_LOG=1 packer build template.json `)

**Comment by juaningan** [comment]
Ok but, in master, 
Packer v0.10.2.dev (2e949bf43ddcacd82cc2eb3d17ec029e1313f45c+CHANGES)

is working well

**Comment by juaningan** [comment]
full debug log updated in same gist

**Comment by rickard-von-essen** [comment]
You have a broken installation of Packer. Please reinstall and be sure to follow the note on: https://www.packer.io/downloads.html

**Comment by rickard-von-essen** [comment]
Reopen if that doesn't helo
