### ISSUE TITLE
Openstack boot from a iso

### ISSUE THREAD

**Issue by marema31** [mitchellh/packer#3705]
Hello,

For windows image generation, we actually use a physical server. It would be great if we could remove it and use directly the in-premise openstack infrastructure. 
For that we would need to boot from a Microsoft ISO and not from a already available image as described in http://docs.openstack.org/user-guide/cli_nova_launch_instance_using_ISO_image.html

Does a such feature is planned on packer ?

**Comment by rickard-von-essen** [comment]
The OpenStack builder relies on community contributions. PR's are welcome!

Currently I would recommend using the qemu builder to build an image and then uploading it to OpenStack.

**Comment by mwhooker** [comment]
This isn't something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
