### ISSUE TITLE
Google compute builder not able to set a disk size

### ISSUE THREAD

**Issue by ehmo** [mitchellh/packer#3707]
Hi,

I'm using packer version 0.10.1.

Seems like the `disk_size` is being ignored and instead a default disk size is used based on the machine type.

**Comment by ehmo** [comment]
I wrote too hastily. The server that is opened during provisioning has a default disk size but the image size is then of the size of the disk size I've set up in the config file. Don't know if that's the desired behavior though.

**Comment by ido** [comment]
See issue  #3587 - the google compute engine image builder should be replaced with one that builds the image outside of GCE and imports it as a QEMU, VirtualBox, or AWS AMI into GCS/GCE.

**Comment by rickard-von-essen** [comment]
@ido #3587 doesn't  really change anything for this issue.

**Comment by mwhooker** [comment]
Going to close this since I think it's fixed. Please open a new issue if you're running into problems with the disk size. Having debug logs will also help us debug this.
