### ISSUE TITLE
VirtualBox: Mount additional iso

### ISSUE THREAD

**Issue by GuillaumeDIDIER** [mitchellh/packer#3708]
Under some circumstances it may be useful to extra additional iso in addition to the installer.

For instance, it would be nice to be able to mount, in addition to the main debian installer, some of the DVDs containing extra packages (if for instance network is slow or unavailable).
### First possibility :
- extra_isos : list of URL each one pointing to an iso
- extra_iso_checksums : the checksums
- extra_isos_urls : list of list of URL (ability to specify several URL for an iso)
### Second possibility :
- extra_iso : list of dictionaries.
  Each specifying url or urls and checksum.

(Also, the guest addition iso for virtual box could be seen as a particular case of this).

**Comment by rickard-von-essen** [comment]
This is can be handled with vboxmanage and vboxmanage_post. (Not as elegantlyl

**Comment by GuillaumeDIDIER** [comment]
Well mounting an extra disk for sure, but downloading and checksumming the ISO from several possible URL ?

**Comment by rickard-von-essen** [comment]
No that would require scripts outside of Packer.
