### ISSUE TITLE
timeout error while creating ami in aws

### ISSUE THREAD

**Issue by deepak-shrivastava** [mitchellh/packer#3713]
Hi,
I am trying to spin up a ami using packer in aws. I do notice that the temp instance that the packer creates is taking a long time to bootup (status check takes a long time to show 2/2 check passed). SO i wanted to know if there is anyway in which we can increase the ssh timeout value in packer (i am using centos image as my base ami)?

thanks
Deepak

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

---
See the [docs](www.packer.io/docs/templates/communicator.html#ssh_timeout)
