### ISSUE TITLE
difference between ansible(remote) and ansible-local

### ISSUE THREAD

**Issue by niravradia** [mitchellh/packer#3717]
I am still confused after reading the documentation about ansible(remote) and ansible-local provisioners. My use-case is to run a playbook which installs Oracle JDK, GIT etc and "synchronize" a folder (say /home/ubuntu/abc) lying on my ansible-controller with ansible-host (at /tmp/abc).

Reading the documentation of [ansible-remote](https://www.packer.io/docs/provisioners/ansible.html), I thought using ansible provisioner would be good. But when I did that, to my surprise, the playbook was synchronizing the folder from /home/ubuntu/abc with /tmp/abc on the SAME MACHINE where I am running packer.

Is it possible that I can use machine running PACKER as ansible controller and use machine provisioned by packer as host?

I am not sure posting this question here is appropriate or not but I can't find anything related to my use case in the documentation.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

---

`ansible` (remote) provisioner should be perfectly fine for that usage but it's very hard to tell what you are doing wrong when you don't include any example code.

Double check you packer template and ansible playbook. If that doesn't help you can either use the `file` provisioner to upload your directory or ask for help on the mail list or on IRC (see above). If you do be sure to provide a minimal example which doesn't work as you expect.
