### ISSUE TITLE
FEATURE REQUEST: transparent http cache for packer

### ISSUE THREAD

**Issue by gdevenyi** [mitchellh/packer#3720]
In the case of using packer to build a VM which makes many downloads from a deb or rpm archive, as once develops the provisioning, there may be many repeat downloads from the internet.

This is particularly painful on slow internet connections.

My idea for a feature is to integrate into packer a "transparent" caching proxy which will cache downloads made by the running builder so that on a repeat build, cached files can be served up.

**Comment by rickard-von-essen** [comment]
I think this is an interesting idea, but complicated to implement and will hardly be effective without adapting the installation/provisioning. I would recommend that you look into setting up your own caching proxy such as [squid](http://www.squid-cache.org).

**Comment by kwilczynski** [comment]
This is a good idea, but not for Packer to solve. I agree with @rickard-von-essen.

A very similar problem people often have with Vagrant and/or Test Kitchen where they want to improve performance by caching binary packages closer to the virtual machine.

A popular way to solve this problem would be to setup something small like the popular [polipo](https://www.irif.univ-paris-diderot.fr/~jch/software/polipo/) and then configure Packer to use it.

I've been using [polipo-box](https://github.com/tmatilai/polipo-box) together with Packer (a Vagrant box removes the need to install anything locally on OS X, which I consider a plus) set against local web caching proxy. It does work well for my use case (e.g. continuously bundling Vagrant boxes and Docker images; as it can be re-used for other tools too). I encourage you to give it a go and see whether it would work for you too.

**Comment by mwhooker** [comment]
I think we can use 3rd party tooling for this.

Thanks for the ticket
