### ISSUE TITLE
Packer should be able to run local builds via ssh

### ISSUE THREAD

**Issue by gtmtech** [mitchellh/packer#3735]
We like running packer from within a docker container - because it becomes a consistent toolset for all devs, CI jobs etc, and we can control the exact packer plugins in use by everyone without people having bespoke versions.

This works fine for AWS provisioning, but for local provisioning via vmware-iso or virtualbox-iso, and equivalent, it presents a problem, because packer would try and run "VBoxManage" or equivalent commands, and I cant think of a way this can work when being done from inside a docker container.

However this could work, if these commands were able to run over SSH. Is there any way to do this, and/or if not, could it be done easily? Having a common dockerized toolset, is a cool thing if it can be made to work.

**Comment by rickard-von-essen** [comment]
My opinion is that it would be very complicated to retrofit this and get everything to work. It's not only that `VBoxManage` need to run on ssh but also you need to setup ssh with correct access, tunnel VNC (VMware) etc, and then setup comm (ssh/winrm) to work from a docker container to the guest vm.

**Comment by dave2** [comment]
You can definitely run qemu inside lxc containers, as that's how Ubuntu's one-machine OpenStack demo environment works. I don't know what permissions would be different between docker and lxc to do that, however. I suspect it's probably just device issues (ie, /dev/kvm) and a few other filesystem things.

**Comment by rickard-von-essen** [comment]
Closing this since this is not something we would like to support.
