### ISSUE TITLE
temporary_key_pair_name is ignored

### ISSUE THREAD

**Issue by TaiSHiNet** [mitchellh/packer#3736]
- Packer Version: 0.10.1
- Host platform: OSX ElCap 10.11.15
- Debug log output: https://gist.github.com/TaiSHiNet/01a79577062ed9ea3cd30672aff43fef
- The _simplest example template and scripts_ needed to reproduce the bug:

```
{
  "builders": [{
    "temporary_key_pair_name": "hello",
    "type": "amazon-ebs",
    "ami_name": "Starmount VyOS",
    "instance_type": "t2.medium",
    "source_ami": "ami-9c9a12f4",
    "region": "us-east-1",
    "ssh_username": "vyos",
    "force_deregister": true,
    "ami_regions": [
      "us-east-1"
    ]
  }],
  "provisioners": [{
    "type": "shell",
    "inline": [
      "echo wololo"
    ],
    "execute_command": "{{ .Vars }} sudo -E sh '{{ .Path }}'"
  }]
}
```

**Comment by TaiSHiNet** [comment]
Most outstanding log line is: 
`==> amazon-ebs: Creating temporary keypair: packer 578fab50-b4f3-90f5-b123-623223a2e45d`

**Comment by kwilczynski** [comment]
Indeed, this is the culprit: [run_config.go#L48-L51](https://github.com/mitchellh/packer/blob/master/builder/amazon/common/run_config.go#L48-L51)

**Comment by kwilczynski** [comment]
Resolved in #3739, over to you @rickard-von-essen 🚀 

Funny enough, I had a custom name in my templates since forever, but never actually noticed that it was broken. Good catch @TaiSHiNet.

**Comment by kwilczynski** [comment]
By the way, should we tackle this one too? https://github.com/mitchellh/packer/issues/2301

**Comment by TaiSHiNet** [comment]
Thanks @kwilczynski, issue presented itself while working with a VyOS AMI, they don't seem to like spaces in key names

**Comment by kwilczynski** [comment]
Actually, this is a fair point. I will add an underscore there, to the auto-generated one. It would not harm anything and/or anyone, but might prevent surprises like the one you've had @TaiSHiNet .

**Comment by kwilczynski** [comment]
@TaiSHiNet so I've made sure that auto-generated SSH key-pair name will have the underscore there between prefix and the UUID.

**Comment by TaiSHiNet** [comment]
Thanks @kwilczynski for going through the trouble!
