### ISSUE TITLE
vmware-iso ISO is not connected and the guest boots looking for PXE

### ISSUE THREAD

**Issue by ybizeul** [mitchellh/packer#3750]
- Packer Version : 0.10.1
- Host platform : Mac OS 10.11.6
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/ybizeul/0893026da3fe274a968013b0391c67ca
- The _simplest example template and scripts_ needed to reproduce the bug.
  https://gist.github.com/ybizeul/ec3a1cbe9a06c9a9a4d93ff663b82527

<img width="721" alt="debian iso" src="https://cloud.githubusercontent.com/assets/182035/17140718/74bb0e7e-5317-11e6-9377-7007b9b45dba.png">

**Comment by ybizeul** [comment]
It looks like it's because I changed the path to the cache file for the ISO. After removing "iso_target_path":"debian.iso" it works. I keep investigating

**Comment by rickard-von-essen** [comment]
As you said, just drop the `"iso_target_path"`.

**Comment by ybizeul** [comment]
I needed to change it so it is out of the paker directory. It seems to be working if I set a full path here
