### ISSUE TITLE
"ssh_private_ip" option does not work in EC2 Classic (only works in VPC)

### ISSUE THREAD

**Issue by tarrall** [mitchellh/packer#3751]
- Packer Version: 0.10.2
- Host platform: OS/X 10.11

For the amazon builders, the "ssh_private_ip" flag is not working outside of VPC.  That is, if you are provisioning on a VPC-based instance, it works; if you are provisioning in Classic, it does not.

Patch coming shortly.

**Comment by rickard-von-essen** [comment]
This is a known limitation. PR's are welcome.

**Comment by tarrall** [comment]
Cool, see PR above!
