### ISSUE TITLE
Windows Azure resource manager VMs fail to launch

### ISSUE THREAD

**Issue by billrich4054** [mitchellh/packer#3754]
- Packer Version
  0.10.2
- Host platform
  Windows VMs on ARM
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/billrich4054/e900dde3c118c265d6a21c1d8455a63b#file-packer-log

- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/billrich4054/e900dde3c118c265d6a21c1d8455a63b#file-windows-json
  

I have seen the same results with any variation of windows builds on ARM (including win 2012 and win 2008). The packer build goes fine, but VMs created from the image fail to launch. Azure lists the new vm in a "creating" state until it times out and then it goes to failed. I've enabled debug features so I could get a screen shot, and the stuck VMs are sitting at the "Press ctrl+alt+del to log on" screen. It seems that Azure is no longer able to connect to the vm to complete the provisioning. I suspect it may have something to do with the winrm configuration performed by packer, but I have been unable to test this.

Manually creating an image of windows vms using the azure cli tools works fine.

**Comment by boumenot** [comment]
Once the build has been created, the image needs to be sysprep'ed.  Have you completed that step?  The symptom that you describe is what I see when a VM has not been sysprep'ed.

Azure times out a deployment after 40 minutes.

**Comment by billrich4054** [comment]
I've tried using the following provisioner:
`
    "provisioners": [
        {
            "type": "powershell",
            "inline": [
                "c:\\windows\\system32\\sysprep\\sysprep.exe /oobe /generalize /shutdown"
            ]
        }
`
And end up with the same result. 

It seems like packer would always end with a sysprep since its a required step to build a functioning windows image.

**Comment by boumenot** [comment]
Agreed.  We've added it to our [TODO][https://github.com/mitchellh/packer/blob/master/builder/azure/TODO.md] list, but have not implemented it.

I believe there are a few platforms that automatically sysprep the VM before deployment, but the majority do not.  Always sysprep'ing adds additional latency, which is costly over the long run, but makes the initial experience much easier.

**Comment by tasquith** [comment]
@billrich4054 I had a similar problem, I used the following lines in an inline PS provisioner just before the destroy which works:

```
"if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
"& $Env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /shutdown /quiet"
```

**Comment by billrich4054** [comment]
Looks like my problem was a bad sysprep script. Switched to using the following and my builds are working now.
`$sysprep = 'C:\Windows\System32\Sysprep\Sysprep.exe'
$arg = '/generalize /oobe /shutdown /quiet'
$sysprep += " $arg"
Invoke-Expression $sysprep`

Thanks for the help!

**Comment by chlsmith** [comment]
Might want to include this sysprep info in the documentation on https://www.packer.io/docs/builders/azure.html.  It's not clear there that you even need to sysprep the image.
