### ISSUE TITLE
packer Openstack provisioner fails due to SSH using IPv6

### ISSUE THREAD

**Issue by eric-lopez** [mitchellh/packer#3759]
Packer Version: 0.10.1
Host platform: darwin amd64

Using Openstack provisioner for DreamCompute. DreamCompute assigns public IPv4 and IPv6 addresses to new instances. IPv4 SSH access to instance is available from my host on a public network, but not from IPv6. 

This is similar to https://github.com/mitchellh/packer/issues/1258

2016/07/28 10:36:52 ui: ==> openstack: Waiting for SSH to become available...
2016/07/28 10:36:52 packer: 2016/07/28 10:36:52 [DEBUG] Detected address: [2607:f298:5:101d:f816:3eff:fe48:5093]
2016/07/28 10:36:52 packer: 2016/07/28 10:36:52 [DEBUG] Using IP address [2607:f298:5:101d:f816:3eff:fe48:5093] to connect
2016/07/28 10:36:52 packer: 2016/07/28 10:36:52 [DEBUG] TCP connection to SSH ip/port failed: dial tcp [2607:f298:5:101d:f816:3eff:fe48:5093]:22: connect: no route to host

$ nova show 5f2570fc-7689-4385-8d38-480219cc7d36
+--------------------------------------+----------------------------------------------------------+
| Property                             | Value                                                    |
+--------------------------------------+----------------------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                                   |
| OS-EXT-AZ:availability_zone          | iad-2                                                    |
| OS-EXT-STS:power_state               | 1                                                        |
| OS-EXT-STS:task_state                | -                                                        |
| OS-EXT-STS:vm_state                  | active                                                   |
| OS-SRV-USG:launched_at               | 2016-07-28T17:34:45.000000                               |
| OS-SRV-USG:terminated_at             | -                                                        |
| accessIPv4                           |                                                          |
| accessIPv6                           |                                                          |
| config_drive                         | True                                                     |
| created                              | 2016-07-28T17:34:36Z                                     |
| flavor                               | gp1.lightspeed (300)                                     |
| hostId                               | 69b8059002eb9517c3d00886cdeb1e215ac60d24ca6909e8fc55a89e |
| id                                   | 5f2570fc-7689-4385-8d38-480219cc7d36                     |
| image                                | Ubuntu-16.04 (12f6a911-00a2-42eb-8712-d930da2da81f)      |
| key_name                             | erilop11-dhc-iad2                                        |
| metadata                             | {}                                                       |
| name                                 | dcos-centos-dreamcompute                                 |
| os-extended-volumes:volumes_attached | []                                                       |
| progress                             | 0                                                        |
| public network                       | 2607:f298:5:101d:f816:3eff:fe48:5093, 64.111.99.126      |
| security_groups                      | default                                                  |
| status                               | ACTIVE                                                   |
| tenant_id                            |                         |
| updated                              | 2016-07-28T17:34:46Z                                     |
| user_id                              |                          |
+--------------------------------------+----------------------------------------------------------+

$ ssh dhc-user@64.111.99.126 -i .ssh/erilop11-dhc-iad2.key
The authenticity of host '64.111.99.126 (64.111.99.126)' can't be established.
ECDSA key fingerprint is SHA256:J7n6zHkmTCxsZvro/74mEltTiAr+POg/YNF/ZCXN128.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '64.111.99.126' (ECDSA) to the list of known hosts.
Welcome to Ubuntu Xenial Xerus (development branch) (GNU/Linux 4.4.0-6-generic x86_64)

....
....

dhc-user@dcos-centos-dreamcompute:~$

**Comment by rickard-von-essen** [comment]
Have you tried to set `"ssh_ip_version": "4"`, see the [docs] (https://www.packer.io/docs/builders/openstack.html#ssh_ip_version)?

**Comment by eric-lopez** [comment]
Thanks. This resolved the issue.  Should this default to IPv4 if this isn't defined?

**Comment by rickard-von-essen** [comment]
I'm not sure, the current behavior might have some benefits over just defaulting to IPv4.
