### ISSUE TITLE
Copy amazon-ebs builder shared AMI in another account

### ISSUE THREAD

**Issue by miked0004** [mitchellh/packer#3761]
## Scenario:

I am using packer to create an AMI in an account called **BUILD** with launch permissions given to another account called **DEPLOY**. In **DEPLOY** account, I want to encrypt the root block device of the AMI before I launch the instance. In order to do this, I need to copy the AMI. Regardless of the encrypt flag, I cannot copy the shared AMI in **DEPLOY** because the launch permissions do not cascade to the associated snapshot(s).
- Packer Version = 0.10.1
- Host platform = OS X 10.11.5 (Capitan)
## Example:

**In BUILD account**
 `packer build` this packer.json, replacing **vpc_id**, **subnet_id** and **DEPLOYACCTNUM**:

```
{
  "builders": [{
    "type": "amazon-ebs",
    "region": "us-east-1",
    "source_ami": "ami-6869aa05",
    "vpc_id": "vpc-00000000",
    "subnet_id": "subnet-00000000",
    "instance_type": "t2.medium",
    "ssh_username": "ec2-user",
    "ami_name": "packer-share-test",
    "ami_users": [
      "DEPLOYACCTNUM"
    ]
  }]
}
```

Result:

```
...build output omitted...
==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

us-east-1: ami-11111111
```

**In DEPLOY account**

```
# check if ami is accessible
$ aws ec2 describe-images --image-ids ami-11111111 --query "Images[].[ImageId,Name]" --output text
ami-11111111    packer-share-test

# attempt to copy the ami
$ aws ec2 copy-image --source-region us-east-1 --source-image-id ami-11111111 --name packer-share-test-copy

An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami
```

This happens because the snapshots of the source ami do not have `createVolumePermission` for **DEPLOY** account.

Any recommendations on a solution? Could this be incorporated into an option for the **amazon-ebs** builder?

Assistance greatly appreciated.

**Comment by sigurdknippenberg** [comment]
Can this be converted to an enhancement request instead of a question? Our workaround for this issue right now is to create a custom post processor plugin that fetches the ```LaunchPermissions``` for the generated AMI and assigns those same permissions to the referenced snapshots's ```CreateVolumePermissions```.

I attached the source files of the plugin. Ideally the amazon-ebs builder performs this logic.

[main.txt](https://github.com/mitchellh/packer/files/394684/main.txt)
[post-procesor.txt](https://github.com/mitchellh/packer/files/394685/post-procesor.txt)

**Comment by anthcourtney** [comment]
I've also hit this problem, following a very similar use-case pattern. (i.e. build in a central account, deploy in a different account, with the desire to copy the image so as to encrypt the root volume of the AMI using the deploy account's KMS key).

+1 for this being a feature which is implemented.

**Comment by eukaryote** [comment]
I also have this problem. For now, I'm manually adding the account ids to the permissions for the two volumes associated with the AMI in the source account.

**Comment by jtopper** [comment]
Similar use case here, except that we create public AMIs. I'd like to be able to set the snapshot to public with packer when creating the AMI.

**Comment by rickard-von-essen** [comment]
See #4243
