### ISSUE TITLE
RFC: Daily Build

### ISSUE THREAD

**Issue by boumenot** [mitchellh/packer#3772]
It would be nice to have a build published either daily or per-checkin to GitHub.  Handing out experimental, but _official_ builds is nicer than me building one offs on my development box.

Thoughts:

cc: @cbednarski

**Comment by rickard-von-essen** [comment]
:+1:
I think it would be great to have Travis push binaries from master en referens them from the download page. This would allow people to easily test out fixes and use the as soon they are merged. It would also decrease the pressure to do bugfix releases.

**Comment by mwhooker** [comment]
Yes, we're definitely working on something like this.

**Comment by boumenot** [comment]
@mwhooker - any update on this?

**Comment by SwampDragons** [comment]
@boumenot No news, unfortunately. (Jumping in because Matt's gonna be mostly AFK until ~July 24)
