### ISSUE TITLE
amazon-ebs builder handshake failure waiting for SSH

### ISSUE THREAD

**Issue by mcforres** [mitchellh/packer#3773]
I'm currently trying to use the aws-ebs builder to deploy an AMI from a packer built Centos minimal AMI (not from the marketplace).  The base AMI is configured to use the ec2-user account for ssh; therefore my builder file looks like the example below.  The temporary instance is created, but packer isn't able to SSH to the new temporary instance.  I've confirmed, using debug methods that the SSH keys are in fact in place and that I can manually connect to the instance.  I've also confirmed from the instance logs, that packer is attempting to connect to the instance, and sshd is able to find the public key on the instance, but then the session is terminated  

```json
{
  "builders": [{
  "type": "amazon-ebs",
  "access_key": "",
  "secret_key": "",
  "region": "us-east-1",
  "vpc_id" : "my_vpc_id",
  "source_ami": "my_ami_id",
  "instance_type": "t2.micro",
  "user_data_file" : "my_user_data_file_path",
  "ssh_keypair_name" : "my_key_name",
  "ssh_private_key_file" : "my_key_path.pem",
  "ssh_username": "ec2-user",
  "associate_public_ip_address" : "1",
  "subnet_id" : "my_subnet_id",
  "ami_name": "test {{timestamp}}"
  }]
}
```

Running Packer 0.10.1

**Comment by rickard-von-essen** [comment]
Please gist a full debug log from `PACKER_LOG=1 packer build template.json`

**Comment by mcforres** [comment]
[debuglog.txt](https://github.com/mitchellh/packer/files/398266/debuglog.txt)

Log attached

**Comment by rickard-von-essen** [comment]
You have a broken installation of Packer. Delete /usr/local/packer and reinstall. See https://www.packer.io/downloads.html especially the note about upgrading from older versions.

**Comment by narendraj9** [comment]
@rickard-von-essen Hi, I am facing a similar issue. How did you figure out that the installation is broken?

**Comment by rickard-von-essen** [comment]
The log contains lines like `Discovered plugin: openstack = /usr/local/packer/packer-builder-openstack` but it should only contains lines like `Using internal plugin for amazon-import`.

**Comment by narendraj9** [comment]
Interesting. Thanks for the explanation.

**Comment by narendraj9** [comment]
How does discovery of a plugin cause this issue?
```
2016/08/02 17:08:11 Using internal plugin for azure-arm
2016/08/02 17:08:11 Using internal plugin for ansible
2016/08/02 17:08:11 Using internal plugin for amazon-import
2016/08/02 17:08:11 Using internal plugin for shell-local
```
These are the plugins that were actually used.

**Comment by rickard-von-essen** [comment]
It uses plugins from a really old version of Packer.

**Comment by rickard-von-essen** [comment]
@narendraj9 if you have the general problem that SSH handshake fails please use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) to get help.


_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
