### ISSUE TITLE
sftp connection error when ssh_pty set to true

### ISSUE THREAD

**Issue by james-s-turner** [mitchellh/packer#3778]
I am seeing the same issue as https://github.com/mitchellh/packer/issues/3406
The resolution to this was to set 'ssh_pty' to false.
However this is not a viable option for me. Is there any way to get 'ssh_pty = true' to work when the script that is run does need to allocate a tty?

I'm running locally on OSX Yosemite
packer: 0.10.1
ansible: 2.1.1.0

**Comment by rickard-von-essen** [comment]
I think your out of luck if you need a pty.

**Comment by james-s-turner** [comment]
Thanks for the prompt reply. Would it not be better to remove the option, rather than to raise peoples hopes, then cruelly dash them ;-)

**Comment by rickard-von-essen** [comment]
If you use `ansible` provisioner and need `pty` you are out of luck.
