### ISSUE TITLE
SSH agent forwarding not working with shell provisioner

### ISSUE THREAD

**Issue by zbjornson** [mitchellh/packer#3779]
SSH agent forwarding doesn't seem to be working when a shell provisioner is running.

```
PACKER_LOG=1 packer build --debug template.json
[...]
2016/08/05 00:35:03 packer: 2016/08/05 00:35:03 opening new ssh session
2016/08/05 00:35:03 packer: 2016/08/05 00:35:03 [INFO] agent forwarding enabled
==> googlecompute: Connected to SSH!
2016/08/05 00:35:03 ui: ==> googlecompute: Connected to SSH!
==> googlecompute: Pausing after run of step 'StepConnect'. Press enter to continue.
```
At this point if I ssh into the instance using the key created by packer, agent forward works.
```
zbjornson@packer-runner$ ssh -i <key.pem> ubuntu@<address>
ubuntu@packer-57a3def2-c38b-138f-5c93-c927959cc4e5:~$ ssh git@github.com
PTY allocation request failed on channel 0
Hi zbjornson! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```
But putting `ssh git@github.com` in a shell script for packer to run fails:
```
2016/08/05 00:48:29 ui: ==> googlecompute: Provisioning with shell script: test_github.sh
[...]
2016/08/05 00:48:29 packer: 2016/08/05 00:48:29 opening new ssh session
2016/08/05 00:48:29 packer: 2016/08/05 00:48:29 starting remote command: chmod +x /tmp/script_8355.sh; PACKER_BUILD_NAME='googlecompute' PACKER_BUILDER_TYPE='googlecompute' PACKER_GIT_BRANCH='master' /tmp/script_8355.sh
2016/08/05 00:48:29 ui:     googlecompute: Pseudo-terminal will not be allocated because stdin is not a terminal.
    googlecompute: Pseudo-terminal will not be allocated because stdin is not a terminal.
2016/08/05 00:48:30 packer: 2016/08/05 00:48:30 remote command exited with '255': chmod +x /tmp/script_8355.sh; PACKER_BUILD_NAME='googlecompute' PACKER_BUILDER_TYPE='googlecompute' PACKER_GIT_BRANCH='master' /tmp/script_8355.sh
2016/08/05 00:48:30 packer: 2016/08/05 00:48:30 [INFO] RPC endpoint: Communicator ended with: 255
    googlecompute: Permission denied (publickey).
```

(That's the same error as if I ssh with `-a` to disable forwarding.)

Early in the logs I see `[INFO] agent forwarding enabled`, but that doesn't appear when it's creating the new connection to run the shell script.

Not positive, but it looks like the forwarding agent is setup in `reconnect` and not in `newSession` [here](https://github.com/mitchellh/packer/blob/4108c7bdbe55f518cc28773d1b5ab69844af7f61/communicator/ssh/communicator.go#L229).

- Packer Version: 0.10.1
- Host platform: Ubuntu 16.04
- Debug log output and template: https://gist.github.com/zbjornson/ec14036e9a5cf8fc1ffbf0a316caeb0f

**Comment by zbjornson** [comment]
Just built packer from source from the master branch and this seems to be fixed! (But I can't find the commit that fixed it.)

**Comment by zbjornson** [comment]
After all that... I didn't know that `ssh-add <mykey>` doesn't persist between sessions. The session where I built from source is the only one I had added my key. :cry:

**Comment by xrage** [comment]
Have you solved it ? Facing same issue 😢

**Comment by rickard-von-essen** [comment]
> The session where I built from source is the only one I had added my key.

Could you clarify this?

SSH agent forwarding should work. If anyone has problems please post on the e-mail list, see [packer.io/community](https://www.packer.io/community/) or open a new issue if you belive there is a issue.

**Comment by zbjornson** [comment]
SSH agent forwarding works -- I had failed to add one of my SSH keys to the SSH agent though. The part you quoted was supposed to say that in the session where I built from source, I had run `ssh-add` explicitly, but that didn't persist to other sessions.

@xrage Github has good docs on this: https://developer.github.com/guides/using-ssh-agent-forwarding/ and if it's useful, I added this to my .profile to deal with the agent automatically.

```sh
[ -z "$SSH_AUTH_SOCK" ] && SSH_AUTH_SOCK=$(ls -l /tmp/ssh-*/agent.* 2> /dev/null | grep $(whoami) | awk '{print $9}')
[ -z "$SSH_AGENT_PID" -a -z `echo $SSH_AUTH_SOCK | cut -d. -f2` ] && SSH_AGENT_PID=$((`echo $SSH_AUTH_SOCK | cut -d. -f2` + 1))
[ -n "$SSH_AUTH_SOCK" ] && export SSH_AUTH_SOCK
[ -n "$SSH_AGENT_PID" ] && export SSH_AGENT_PID

# start agent if necessary
if [ -z $SSH_AGENT_PID ]; then  # if no agent
  eval `ssh-agent -s` > /dev/null
  ssh-add
fi
```

**Comment by rickard-von-essen** [comment]
Thanks for your info. :+1:
