### ISSUE TITLE
packer build -debug not generating an SSH key

### ISSUE THREAD

**Issue by heckj** [mitchellh/packer#3792]
Packer version: 0.10.1
Host: MacOS X

I'm trying to debug an issue where packer hangs after a provisioning script has finished execution (possibly similiar to mitchellh/packer#2447). The underlying issue that surfaced is https://github.com/RackHD/RackHD/issues/372.

When I'm invoking `PACKER_LOG=1 packer build -debug -only=virtualbox-iso template-packages.json`, I was looking for the ephemeral `key.pem` as indicated at https://www.packer.io/docs/other/debugging.html to attempt to log in and see what we running and potentially hanging open the packer SSH communication channel.

However, I was unable to find any generated PEM file in the directory where i invoked the packer command.

The specific process I was using to get here can be reproduced with:

```
git clone https://github.com/rackhd/rackhd
cd rackhd/packer
PACKER_LOG=1 packer build -debug -only=virtualbox-iso template-packages.json
```

Am I looking in the wrong place for the .pem file, or is that something that disappeared from debugging in one of the version updates?

**Comment by rickard-von-essen** [comment]
There are no ephemeral keys for `virtualbox-iso` builder. Only for builders on cloud where there are api's for managing ssh keypairs.

**Comment by heckj** [comment]
@rickard-von-essen ah, thank you. The docs weren't very clear about that - I did log in via my local base image to hunt down my issue. Are the docs also in github? I'd be happy to propose a PR with language that would at least make more sense to me. :-)

**Comment by rickard-von-essen** [comment]
Yes the docs are in the repo. See [debugging](https://github.com/mitchellh/packer/blob/master/website/source/docs/other/debugging.html.md)

Improvements are welcome!
