### ISSUE TITLE
bug: packer build ignore access key and secret access key parameter in json

### ISSUE THREAD

**Issue by fotto1** [mitchellh/packer#3794]
Packer Version: 0.10.1
Host platform: Windows Machine
Target Env: AWS EC2

template.json:

``` json
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "eu-central-1",
    "source_ami": "ami-26c43149",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "packer-ubuntu {{timestamp}}"
  }]
}
```

I try to run the build with following command:

``` cmd
packer.exe build -debug -var 'aws_access_key=my_access_key' -var 'aws_secret_key=my_secret_access_key' template.json
```

The creation is running but in the wrong aws account. Packer don't use the parameters which I set, instead it use my default account from .aws\credentials

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by rickard-von-essen** [comment]
Closing since no response and to little info in description.
