### ISSUE TITLE
Integration with artifactory

### ISSUE THREAD

**Issue by kenny-opennix** [mitchellh/packer#3795]
Hello everyone. 
Anybody try auto upload vagrant image to Artifactory repo after packer build?

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
