### ISSUE TITLE
VirtualBox-iso builder does not follow http redirects when downloading ISO files

### ISSUE THREAD

**Issue by rf1010** [mitchellh/packer#3802]
### Feature enhancement request

Given:

```
  "builders": [
    {
      "type": "virtualbox-iso",
      "iso_urls": [
        "my.iso",
        "{{user `iso_download_url`}}"
      ],
  ...
```

When  `iso_download_url` contains a direct link to the ISO resource, everything works correctly. However, it does not correctly when there are HTTP redirects, as it is often happen with CDNs (content delivery networks). Essentially, packer downloads the http response, which does not match the checksum and aborts.

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by rf1010** [comment]
$ packer version
Packer v0.10.1

$ uname -a
Darwin 6f7032.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

Failed Scenario (Nexus URL is a query API with HTTP redirects, i.e. iso.download.url=http://nexus.dev.[project].com/service/local/artifact/maven/resolve?r=third-party-software&g=org.centos&a=centos-minimal-x86_64&p=iso&v=7&c=1511
): 
https://gist.github.com/rf1010/2bd49bb659e9bafb0324232e1ddc38a8

Successful Scenario (Direct HTTP link, i.e. iso.download.url=http://nexus.dev.[project].com/service/local/repositories/third-party-software/content/org/centos/centos-minimal-x86_64/7/centos-minimal-x86_64-7-1511.iso
): 
https://gist.github.com/rf1010/13cef71959f6037f3096223a5007600d

**Comment by rickard-von-essen** [comment]
Thank you! (A lot of the maintainers time go to reproducing issues. Having cut and past examples reduces that.)

**Comment by mwhooker** [comment]
works for me

```
{
    "builders": [
        {
            "iso_checksum": "af5f788aee1b32c4b2634734309cc9e9",
            "iso_checksum_type": "md5",
            "iso_url": "https://httpbin.org/redirect-to?url=http%3A%2F%2Fold-releases.ubuntu.com%2Freleases%2Fprecise%2Fubuntu-12.04.2-server-amd64.iso",
            "shutdown_command": "shutdown -P now",
            "ssh_username": "packer",
            "type": "vmware-iso"
        }
    ]
}
```

Please open a new issue with a json which reproduces this issue if you continue to encounter it
