### ISSUE TITLE
packer validate - exit status 250 without any message.

### ISSUE THREAD

**Issue by karamazi** [mitchellh/packer#3805]
*\* BUG **
Running `packer validate` results in "Exit status 250" error message, without any reason provided. Packer 0.9.0 validates the same file properly.
- Packer Version: 
  0.10.1
- Host platform: 
  VirtualBox VM with Ubuntu 14 (Running on windows 10)
  Linux ubuntu-14 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- Reproduction gist contains: 
  -- packer template, 
  -- output from 0.10.1 with logs
  -- output from 0.9.0 (succesfull) 
  -- empty playbook.

https://gist.github.com/karamazi/77f400a1f8cf1ffc877b8929d70d4665
- Additional notes:
  This issue occurs on both: shared windows directory and native linux directory.

**Comment by rickard-von-essen** [comment]
This validates fine with my build from master.

**Comment by rickard-von-essen** [comment]
```shell
$ packer_0.10.1 validate aws_image.json
Template validated successfully.
```

Could you double check you env?

**Comment by mwhooker** [comment]
will re-open if we get a reply that shows this still is an error
