### ISSUE TITLE
Azure Authorization setup script fails creating service principal

### ISSUE THREAD

**Issue by chrislea** [mitchellh/packer#3810]
When using the [Azure setup script](https://github.com/mitchellh/packer/blob/master/contrib/azure-setup.sh) to get authorization creds, it will currently reliably fail with this message:
```bash
==> Creating service principal
info:    Executing command ad sp create

  error: missing required argument `name'
```

using the most recent version of the Azure CLI tools running from Linux.

I believe that the error is [here](https://github.com/mitchellh/packer/blob/master/contrib/azure-setup.sh#L149). This line should read

    azure ad sp create -a $azure_client_id

and the script will run successfully. I'm happy to send in a PR with the change if you'd like, I just thought it might be overkill for adding three characters. If I'm wrong and a PR is the way to go just let me know.

Thanks for all your work!

**Comment by ritasker** [comment]
I have a PR for this too, #3812.

**Comment by boumenot** [comment]
Thank you for logging and issue, and making it better!

I merged @ritasker's PR to address the issue.
