### ISSUE TITLE
Provisioner Chef-Client fails to clean node

### ISSUE THREAD

**Issue by jharshman** [mitchellh/packer#3811]
Building an image using the chef-client provisioner fails when attempting to clean the chef node.  
```
    vmware-iso: Creating configuration file 'knife.rb'
==> vmware-iso: Cleaning up chef node...
    vmware-iso: sudo: no tty present and no askpass program specified
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Unregistering virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error cleaning up chef node: Failed to cleanup node: Non-zero exit status. See output above for more info.

Command: sudo knife node delete packer-ubuntu-xenial-tiny -y -c /tmp/packer-chef-client/knife.rb
```

attempting to fix the `sudo: no tty present and no askpass program specified` message I set the "ssh_pty": "true" option which caused the cleanup node operation to hang and not complete.

Packer Version: 0.10.1
Host Platform: Ubuntu 16.04 AMD64
Template: https://gist.github.com/jharshman/138bb773755441f2269f7efae3b1e0ea

I can provide a full log but will have to redact sensitive info out of it.

Any help with this would be much appreciated.  Currently I am manually removing the provisioned image from the chef server which gets super repetitive when iterating on these packer builds.

Thanks in advance!

**Comment by rickard-von-essen** [comment]
Ensure that your kickstart setups `ssh_user` to _not require tty_ for sudo. Then it should be fine with `"ssh_pty": false`.

**Comment by jharshman** [comment]
@rickard-von-essen thanks for the tip.  trying a build now.

**Comment by jharshman** [comment]
excellent.  Another hurdle was the chef recipe was clobbering `/etc/sudoers`.  With that fixed, and the solution you gave above,  it is working perfectly.  Thank you! 👍
