### ISSUE TITLE
Network Interface (eth0) is not created using virtualbox-iso builder

### ISSUE THREAD

**Issue by jrdmcgr** [mitchellh/packer#3814]
I am trying to create an Ubuntu 16.04 VirtualBox image and it consistently times out waiting for ssh. SSH is running, but the only network interface available is the loopback interface (lo0).

I thought that it was related to #3757, so I downgraded to 5.0 and I am still having this issue.

Is there a reason why the interface was not created?

https://gist.github.com/jrdmcgr/3eca10d05f3b02d424d6c9cf684b6b53

**Comment by cbednarski** [comment]
Ubuntu 16 doesn't use `eth0` anymore. It uses something like `ens33` which (I think) corresponds to the PCI slot assignment.

Have you ever run a successful local build with packer? On OSX specifically you should make sure packer is not blocked by the OSX firewall or the build will not work.

I re-ran [my ubuntu build](https://github.com/cbednarski/packer-ubuntu) just now with VirtualBox 5.0.26 and packer from master and it seems to be working (though it did take a long time for the OS install bit to complete. Can you try building packer from master and see if that resolves the issue? I'm not aware of any critical fixes for VirtualBox in master but I might have missed or forgotten something that went in.

**Comment by jrdmcgr** [comment]
Thanks for your quick response! I just tried your template and it worked just fine. After comparing our templates, it looks like there was a problem with my boot command or preseed.cfg. 

I'm just starting out with packer, and maybe I'm being dense, but figuring out the correct boot command has been difficult. The documentation only mentions that this is an important part of the template and [various](https://github.com/boxcutter/ubuntu/blob/master/ubuntu.json) [sources](https://github.com/holser/packer-templates/blob/master/ubuntu.json) around GitHub have different boot commands and preseed files for Ubuntu.

I really appreciate your help! I hope I didn't waste your time here.

**Comment by cbednarski** [comment]
Yeah those are tricky. They are OS-specific so you might be able to find documentation on ubuntu's preseed process. TBH I just copied mine from somewhere.

The boot command can be derived by using the GUI boot and figuring out which key presses are needed to get through the automated installer.
