### ISSUE TITLE
winrm internal error

### ISSUE THREAD

**Issue by alkiskal** [mitchellh/packer#3818]
I'm trying to build an image using the AMI `Microsoft Windows Server 2012 R2 Base`. The problem is that I'm getting 

> 2016/08/21 15:09:12 packer: 2016/08/21 15:09:12 [INFO] Attempting WinRM connection...
2016/08/21 15:09:12 packer: 2016/08/21 15:09:12 [DEBUG] connecting to remote shell using WinRM
2016/08/21 15:09:13 packer: 2016/08/21 15:09:13 [ERROR] connection error: unknown error Post https://xxxxxxxxx:3389/wsman: remote error: internal error
2016/08/21 15:09:13 packer: 2016/08/21 15:09:13 [ERROR] WinRM connection err: unknown error Post https://xxxxxxxxx:3389/wsman: remote error: internal error

when packer tries to connect with the instance. I don't have any provisioners, since I'm experimenting, the provisioners will come later. I just want it to successfully connect with the instance via winrm.

The thing is that I'm able to connect via the Microsoft Remote Desktop app using the same credentials.

- Packer v0.10.1
- OSX El Capitan 10.11.6 (15G31)
- https://gist.github.com/alkiskal/3893b96815735bb42c72a08c01de6526

In order to reproduce, run the template that I provided in the gist. Before that, create a user that will have attached the policy I'm including and use those credentials.

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by alkiskal** [comment]
Ok I updated the existing gist

**Comment by rickard-von-essen** [comment]
You are confusing WinRM and RDP.

**Comment by alkiskal** [comment]
Yes you are correct. I was not familiar with this protocol. Moreover, I tried with the default settings, but I'm getting a timeout. It seems that I must enable winrm either by creating an image which has this enabled by default and using that one as a base, or simply using user data 
https://gist.github.com/jimcroft/3878113
I'm closing this. Sorry for the waste time of time.
