### ISSUE TITLE
object_id required for azurerm build.

### ISSUE THREAD

**Issue by liamjbennett** [mitchellh/packer#3822]
The documentation for the the `os_type` parameter of the azurerm builder states that:

```
"For Windows this configures your Tenant ID, 
Object ID, Key Vault Name, Key Vault Secret, and WinRM certificate URL."
```

This leads me to believe that when specifying `"os_type": "Windows"` that I do not need to provide the `object_id` parameter. 

If not set the build will fail with the following error:

```json
{
  "code":"BadRequest",
  "message": { 
    "error":  { 
      "code": "BadRequest",
        "message": "An invalid value was provided for 'accessPolicies'."
      }
   } 
}
```
Ref: https://gist.github.com/liamjbennett/d7ab6a687f076536d21f75f5e9f82992

Packer Version: 0.10.1
Host OS: ubuntu 16.04

**Comment by boumenot** [comment]
Agreed.  I'll send a PR.
