### ISSUE TITLE
Packer builder [vmware-iso] intermittently ignores ssh_timeout_wait value

### ISSUE THREAD

**Issue by mshate123** [mitchellh/packer#3824]
Packer Version : 
0.8.6
Host : 
RHEL 6.6

Intermittently, when our Jenkins job kicks off a packer vmware-iso build on a remote target, the ssh_wait_timeout flag seems to get ignored and it does not loop through and retry more than a few times (I have it set for 18 minutes). From the logs I can see that it only tries a few times before failing (output attached in gist). This error is intermittent, meaning run job A 1st time = no problems, it waits and retries the ssh connection  as long as expected, run job A 2nd time = it only tries a few times before failing and deleting artifacts, run job A 3rd time = no problems, it waits and retries as expected. About 2 in every 10 jobs fails because of this behavior.

Packer build command (run as Execute Shell task in a Jenkins job) : 
`if [ -f "./${templateName}" ]
then
  PACKER_LOG=1 packer build -var 'templateName='${templateName}''  ${templateName}
else
  exit 1
fi`

Packer Template : 
https://gist.github.com/mshate123/d3b8e8a2d74241aa8c8a43af4bc50e9b

Output from Packer_Log=1 of example when it fails : 
https://gist.github.com/mshate123/5e7c80b50b2ff481846937f4bc1ca86d

**Comment by rickard-von-essen** [comment]
You are using v0.8.6, please retest with the latest release, v0.10.1 and reopen if the error exists there too.

The problem is not connecting to ssh but to type the `boot_command` over VNC. The connection is refused. Probably something else is using the port.
> 2016/08/23 12:43:58 ui error: [1;31mBuild 'vmware-iso' errored: Error connecting to VNC: dial tcp 127.0.0.1:5964: getsockopt: connection refused[0m
2016/08/23 12:43:58 Builds completed. Waiting on interrupt barrier...
[1;31mBuild 'vmware-iso' errored: Error connecting to VNC: dial tcp 127.0.0.1:5964: getsockopt: connection refused[0m

**Comment by mshate123** [comment]
It's my kickstarter script which takes a long time to complete, in the mean time I have set packer to retry-loop for 18 minutes. Sometimes it retries for the entire 18 minutes and other times it does not and just fails without contining to retry. Here is a copy of output of the same exact build where Packer is working.
https://gist.github.com/mshate123/004f448cc95e543bcc34bcc6df72712a

**Comment by rickard-von-essen** [comment]
The log you provided above where it fails doesn't reach doing the kickstart it can't even type the boot command (to start the kickstart install). Nevertheless upgrade and try to check what is interfering with the VNC port.
