### ISSUE TITLE
packer quits on mac os sierra

### ISSUE THREAD

**Issue by nbrys** [mitchellh/packer#3827]
Packer randomly quits on mac os sierra why trying to create an AWS AMI.

Describe the problem and include the following information:

- Packer Version 0.10.1
- Host platform Mac OS Sierra
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/nbrys/fb18ebea7a7bc876b6ac768e9defdfa1

**Comment by nbrys** [comment]
https://gist.github.com/nbrys/99ecbf994bd1bfa29cea7aade0c73478

**Comment by rickard-von-essen** [comment]
v 0.10.1 was built with Go 1.6.2, support for macOS Sierra was added in Go 1.6.3. See https://golang.org/doc/devel/release.html#go1.6

If you rebuild from source with Go 1.6.3 or 1.7 it should work fine.

**Comment by rickard-von-essen** [comment]
Please reopen if the it doesn't work with Go 1.6.3 +

**Comment by andreausu** [comment]
@rickard-von-essen do you have an ETA for a new release based on Go 1.6.3? Thank you.

**Comment by rickard-von-essen** [comment]
@andreausu unfortunately not. Ping @cbednarski

**Comment by cbednarski** [comment]
Hey folks, we'll get an official release based on a newer version of Go out next week to fix this problem. Thanks for your patience!

**Comment by grayaii** [comment]
I know this issue is closed, but we are on 0.8.6 and we got bit by this.  We are trying to rebuild this version with go 1.73
```
$ go version
go version go1.7.3 darwin/amd64

$ make updatedeps
INFO: Currently on  (f8f7b7a34c1be06058f5aca23a51247db12cdbc5)
go get -u github.com/mitchellh/gox
go get -u golang.org/x/tools/cmd/stringer
go list ./... \
		| xargs go list -f '{{join .Deps "\n"}}' \
		| grep -v github.com/mitchellh/packer \
		| grep -v '/internal/' \
		| sort -u \
		| xargs go get -f -u -v -d ; if [ $? -eq 0 ]; then \
		echo "ERROR: go get failed. Your git branch may have changed; you were on  (f8f7b7a34c1be06058f5aca23a51247db12cdbc5)."; \
	fi
can't load package: package _/Users/alexgray/workspace/allrepos/packer: cannot find package "_/Users/alexgray/workspace/allrepos/packer" in any of:
	/usr/local/opt/go/libexec/src/_/Users/alexgray/workspace/allrepos/packer (from $GOROOT)
	/Users/alexgray/golang/src/_/Users/alexgray/workspace/allrepos/packer (from $GOPATH)
...
```

Is there a way to build 0.8.6 with 1.7.3

**Comment by mwhooker** [comment]
@grayaii  Sorry, we can't support a version that old.

**Comment by grayaii** [comment]
No worries! Thanks for the quick reply.
