### ISSUE TITLE
ansible remote ignoring remote_user in tasks?

### ISSUE THREAD

**Issue by giuppo** [mitchellh/packer#3828]
- Packer Version 0.10.1
- Host platform   AWS EC2 ami-ed82e39e (ubuntu 14.04)

It seems that remote_user defined in tasks is ignored when provisioning with ansible remote, i.e. no matter what remote_user is defined in playbooks, packer always SSH connects to the host with the user defined in the json template

```
  "provisioners": [
    {
      "type": "ansible",
      "user": "ubuntu",
...
```

Json and ansible yml templates are [here](https://gist.github.com/giuppo/acff1f070243240b503cb85c0c1096d1)

**\* Stripped logs ***

$ansible-playbook execution gives 

```
16:15 $ egrep "TASK|CONN" log_test_simba_ok.yml
TASK [I should be ubuntu] ******************************************************
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: ubuntu
TASK [I should be root] ********************************************************
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: ubuntu
TASK [Add a user in a group] ***************************************************
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: ubuntu
TASK [Install ssh keys to simba] ***********************************************
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: simba
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: simba
TASK [I should be simba] *******************************************************
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: simba
<52.210.201.189> ESTABLISH SSH CONNECTION FOR USER: simba
```

...everything works as expected 

$PACKER_LOG=1 packer build simple.simba.json gives
16:16 $ egrep "TASK|CONN" log_issue_packer.io
    simba: TASK [I should be ubuntu] ******************************************************
    simba: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    simba: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    simba: TASK [I should be root] ********************************************************
    simba: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    simba: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    simba: TASK [Add a user in a group] ***************************************************
    simba: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    simba: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    simba: TASK [Install ssh keys to simba] ***********************************************
    simba: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu
    simba: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: ubuntu

...it dies as ubuntu does not have permission to copy keys into /home/simba

**Comment by rickard-von-essen** [comment]
I'll say this works as intended, maybe the docs should be a bit more clear on that point.

**Comment by giuppo** [comment]
Yes, I could not understand from the docs that this is done by design, thanks.

However, remote_user is very valuable when using ansible playbooks.  
Are there any plans to support it?

**Comment by rickard-von-essen** [comment]
> Are there any plans to support it?
No I don't think so, it would be hard to implement with the current implementation of the `ansible` provisioner and communicators.

**Comment by giuppo** [comment]
Ok, I will try to reshape things. Thanks
