### ISSUE TITLE
Feature Request: Verification hook/step before rest of builder is applied.

### ISSUE THREAD

**Issue by bkruger99** [mitchellh/packer#3831]
My request is more specific to AWS, but it would be nice if I one could do some verification steps after an AMI is generated, but before it's copied to other regions and tagged.

Specifically, if I'm creating an AMI, I would like to just generate the one AMI, be able to spin it up in a new virtual machine and run some tests against it before the packer job finishes and does some other specific things in my packer script (copy to additional regions, add tags, etc.)

So steps would be:
builder,
provisioners,
_ami generated_
<verify piece to take single ami, run a shell to spin up, run tests, etc.>
then follow rest of how packer runs,  copy to other regions, apply tags, etc.

The end game is to be able to ensure that I have a bootable image in a fresh machine, rather than apply to a running machine, rebooting, installing testing tools, running tests, cleaning up after.

https://groups.google.com/forum/#!searchin/packer-tool/verify%7Csort:relevance/packer-tool/y9LkHSATXQc/md9R8vAWB4kJ

Aaron's last post is kinda the route I've had to go and I can't admit that I'm a fan of the approach.

Even if the hook were just a shell mechanism and run scripts from there, as long as it exported some sort of information of the artifact generated (in my case, ami-id) and then be able to run with it from there would be excellent!   Maybe a "verification-provisioner" hook or something along those lines.

Thanks!

**Comment by rickard-von-essen** [comment]
This is probably a bit out of scope for packer. But it should be easy build a script that takes the resulting ami, create an instance from it and run test there. If they are OK use the cli to copy and tag your ami.

**Comment by mwhooker** [comment]
I'd recommend not copying the AMI in your first build, and have a subsequent step which does verification and copying. Going to close as this is not in scope
