### ISSUE TITLE
Docker: Packer does not preserve base image metadata

### ISSUE THREAD

**Issue by gregorskii** [mitchellh/packer#3832]
Using an image such as the official Tomcat image (https://github.com/docker-library/tomcat/blob/989f50ed5db788921a4954109b90362e2209295e/6/jre8/Dockerfile) as a base image to a builder:

```
  "builders": [
    {
      "type": "docker",
      "image": "tomcat:7.0.69-jre8",
      "export_path": "{{user `IMAGE_NAME`}}.tar"
    }
  ],
```

Results in the final image missing the metadata set by the original image.

Setting new metadata is addressed by https://github.com/mitchellh/packer/issues/2193 and https://github.com/cornfeedhobo/packer-post-processor-docker-dockerfile but does [milestone 14](https://github.com/mitchellh/packer/milestone/14) have any updates that would preserve base image metadata?

Thanks!

**Comment by rickard-von-essen** [comment]
#4202 was just added where you can add metadata for committed images. A export is _not_ a docker image, it's a export of the file system.

**Comment by gregorskii** [comment]
Yep, apologies for the late response. I have since removed the export. The work coming down the pipe to keep/edit metadata will fix my use case, but I have not tested it yet.

Thanks!
