### ISSUE TITLE
Bug: Packer unable to get IP address for Windows2012R2 VM using vmware-iso builder

### ISSUE THREAD

**Issue by dhekimian** [mitchellh/packer#3833]
@rickard-von-essen @rothwerx 
Built Packer from Master on 8/25/2016 (v0.10.2.dev). 

Used a previously working Windows2012R2-packer.json and Packer complained "No interface on the VM has an IP address ready". 

This is a new error message introduced in #3347 **Handle SSH to VM with more than one NIC - vmware ISO builder** 

```
590.158 ERR packer: opening new ssh session
590.158 ERR packer: starting remote command: esxcli --formatter csv network vm list
590.644 ERR packer: remote command exited with '0': esxcli --formatter csv network vm list
590.644 ERR packer: opening new ssh session
590.644 ERR packer: starting remote command: esxcli --formatter csv network vm port list -w 53295
591.152 ERR packer: remote command exited with '0': esxcli --formatter csv network vm port list -w 53295
593.152 ERR packer: Timeout connecting to 10.0.8.31
593.152 ERR packer: [DEBUG] Error getting WinRM host: No interface on the VM has an IP address ready
598.153 ERR packer: opening new ssh session
598.153 ERR packer: starting remote command: esxcli --formatter csv network vm list
598.618 ERR packer: remote command exited with '0': esxcli --formatter csv network vm list
598.618 ERR packer: opening new ssh session
598.619 ERR packer: starting remote command: esxcli --formatter csv network vm port list -w 53295
599.166 ERR packer: remote command exited with '0': esxcli --formatter csv network vm port list -w 53295
599.166 ERR packer: [DEBUG] Error getting WinRM host: No interface on the VM has an IP address ready
```

We tested both Windows 2012R2 and CentOS 7.0. 
Windows 2012R2 **failed**
CentOS 7.0 **worked**

It looks like  'net.DialTimeout' gets an error but its not 'net.OpError'
https://github.com/mitchellh/packer/blob/master/builder/vmware/iso/driver_esx5.go#L289-L291

**Revering #3347 and rebuilding allowed Packer to attempt to connect to WinRM.**

**Comment by rickard-von-essen** [comment]
Could you add some error printout to see which error you get?

I think we need to revert #3347 unless we solve this quickly.

**Comment by mahcsig** [comment]
@dhekimian @rickard-von-essen 
I was able to output the error:
```
668.889 ERR packer: remote command exited with '0': esxcli --formatter csv network vm port list -w 121553
668.889 ERR packer: net.OpError: dial tcp 10.0.8.38:22: getsockopt: connection refused
668.889 ERR packer: DialTimeout: dial tcp 10.0.8.38:22: getsockopt: connection refused
668.889 ERR packer: [DEBUG] Error getting WinRM host: No interface on the VM has an IP address ready
```
Looks like `d.port` returns 22 which is why linux was working and windows was not. Looking to see if I can find the right variable to use now.

**Comment by mahcsig** [comment]
@dhekimian @rickard-von-essen created #3836 to fix the port issue.
