### ISSUE TITLE
Packer hangs waiting for AWS events in Mac OS Sierra 10.x

### ISSUE THREAD

**Issue by mafonso** [mitchellh/packer#3837]
This is most likely not a bug with packer itself but rather the way it (or a go binary) behaves on MacOS Sierra 10.x

```
- Packer version from `v0.10.1` 
- Host platform: Mac OS Sierra 10.12 Beta (Darwin 16.0) 
```
Describe the problem and include the following information:

Packer seems to wait too long (long past AWS_TIMEOUT) or forever for AWS events.  It present a random behaviour. It could hang at either waiting for instance to become ready, before starting the provisioner (I'm using shell and ansible), waiting for the instance to stop or for the AMI to be ready.
The most common hang is at `==> amazon-ebs: Waiting for the instance to stop...`

I tried the exact same [project](https://github.com/mafonso/nomad-cluster)/AWS cred and ATLAS_TOKEN with the same packer version (but for arm) on a RaspberryPi and it worked flawlessly.  I also tried packer v0.9.0 on the darwin setup and the behaviour is the same, hanging up in random places.  
I can reproduce it all the time running `packer build -var image_name=nat aws.json`on mentioned project.

I understand that this is most likely due to using an unsupported Beta version of the OS, but I thought I should raise it up just in case this not due to the fact it is a beta version alone (maybe debug mode) but rather some change in the kernel or libraries that will persist on the final release.

**Comment by rickard-von-essen** [comment]
Duplicates #3827. See the explanation there.
