### ISSUE TITLE
Salt provisioner should let me avoid deleting remote state tree

### ISSUE THREAD

**Issue by kojiromike** [mitchellh/packer#3838]
Building an AMI, I want to put the remote salt material on tmpfs so that it goes away in the stored image. But if I create the directory as a tmpfs, the salt provisioner tries to delete it, and fails:

```
sudo mount -t tmpfs -o size=8M tmpfs /srv/salt
…
amazon-ebs: Removing directory: /srv/salt
amazon-ebs: rm: cannot remove '/srv/salt': Permission denied
```

I would like the salt provisioner to give me some way to avoid clearing the remote state tree.

**Comment by mwhooker** [comment]
This should be a really easy fix if anyone wants to submit a PR.

However, this is not something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
