### ISSUE TITLE
Salt provisioner cannot use `minion_config` with non-default remote state tree

### ISSUE THREAD

**Issue by kojiromike** [mitchellh/packer#3839]
Building an AMI, I have a local minion config I want to use. But it assumes the salt state tree is at /tmp/salt, not /srv/salt. I think I should be able to upload the salt states to wherever I want using the file provisioner, then run the salt provisioner. But the salt provisioner doesn't even validate if you don't include a local_state_tree.

```
* local_state_tree cannot be empty
```

[Here's a test case.](https://gist.github.com/kojiromike/3f4f1ff58a73e093e1f8ba07b7a8cf88) I can't provide `PACKER_LOG=1` output because it doesn't validate, so I never ran `build`.

I'm not sure why this behavior would be by design, since Packer has options that seem to support a custom remote state tree as defined by minion_config.

Using `Packer v0.10.1` on OS X 10.11.6.

_Workaround_: Use an empty directory for your `local_state_tree`. Packer will upload it, replace `/srv/salt` with it, and your custom `minion_config` will not use that directory anyway.

NB, all of this is an attempt to work around #3838

**Comment by cbednarski** [comment]
I think there is a more straightforward way to fix #3838 so I am going to close this. Thanks for providing the extra context here.
