### ISSUE TITLE
Download 64 bit version of chef-client

### ISSUE THREAD

**Issue by spuder** [mitchellh/packer#3847]
Packer can automatically install chef-client, however it is hard coded to a 32 bit download link

http://chef.io/chef/install.msi

powershell
https://github.com/mitchellh/packer/blob/master/provisioner/chef-solo/provisioner.go#L36

bash
https://github.com/mitchellh/packer/blob/master/provisioner/chef-solo/provisioner.go#L31

64 bit builds exist on chef >= 12.7.x.
Change the link to install a 64 bit build by default. 

For those that still want the 32 bit client, it can be overwritten with install_command

```bash
"type": "chef-solo",
      "install_command": "powershell.exe -Command \". { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel {{user `chef_channel`}} -version {{user `chef_ver`}}\"",
      "guest_os_type": "windows",
      "cookbook_paths": [ "{{pwd}}/vendored-cookbooks/workstation" ],
      "run_list": [ "workstation" ],
```

**Comment by rickard-von-essen** [comment]
Please open a PR with a fix.

**Comment by spuder** [comment]
Will be resolved when https://github.com/mitchellh/packer/pull/3848 is merged
