### ISSUE TITLE
DKMS can't find the right kernel-headers version when running under Packer

### ISSUE THREAD

**Issue by dfduarte** [mitchellh/packer#3857]
Hello there,

Recently, I made a little script to update the module driver for the virtual Intel network card used on the AWS instances, to enable the usage of the SRIOV (Enhanced Networking) at a optimum level.

So, when running manually the script in a already packed AMI, it successfully works, compile the module and enables it.

When I run it through Packer, I got the following:

```
1473042182,,ui,message,    amazon-ebs: Creating symlink /var/lib/dkms/ixgbevf/3.2.2/source ->
1473042182,,ui,message,    amazon-ebs: /usr/src/ixgbevf-3.2.2
1473042182,,ui,message,    amazon-ebs:
1473042182,,ui,message,    amazon-ebs: DKMS: add completed.
1473042183,,ui,message,    amazon-ebs: Error! echo
1473042183,,ui,message,    amazon-ebs: Your kernel headers for kernel 3.10.0-229.14.1.el7.x86_64 cannot be found at
1473042183,,ui,message,    amazon-ebs: /lib/modules/3.10.0-229.14.1.el7.x86_64/build or /lib/modules/3.10.0-229.14.1.el7.x86_64/source.
1473042183,,ui,message,    amazon-ebs: Error! echo
1473042183,,ui,message,    amazon-ebs: Your kernel headers for kernel 3.10.0-229.14.1.el7.x86_64 cannot be found at
1473042183,,ui,message,    amazon-ebs: /lib/modules/3.10.0-229.14.1.el7.x86_64/build or /lib/modules/3.10.0-229.14.1.el7.x86_64/source.
```
I tried many ways to compile it, like:  Changing the kernel version on dkms.conf (inside the module source folder), deleting all the headers and reinstalling it, running it on a plain CentOS instance, and I got the same for all and many others.

I exhausted my options, now I'm here asking for help, or for a suggestion to do that. Is there a another way to make it?

- Packer version: 0.10.0

- Host platform: CentOS 7 - Linux ip-10-149-41-137 3.10.0-327.28.3.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- Debug log output from https://gist.github.com/dfduarte/f1a628da4189aa124724506b3a7379a7

- The _simplest example template and scripts_ needed to reproduce the bug: https://gist.github.com/dfduarte/e33999055b7e01d7e254a35881d33380

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

---

Some shell scripting tips:
- Your script doesn't fail on error (commands with exit code != 0) 
- And it doesn't fail on unset variables (spelling mistakes etc.)

1) add `set -x` to the top of your script to enable debugging. All commands executed will be echoed. 

2) add `set -eu` to the top of your script to exit on failing commands or unset variables.
Or
3) add a new script after this which do `sleep 3600` and ssh into the machine and troubleshoot.

Feel free to post on the mailing list, but this is most likely a shell scripting issue and might get a quicker response in a help forum for that.

**Comment by dfduarte** [comment]
@rickard-von-essen Just comming back here quickly to thank you man. Your suggestion of the set -x (-eu) Helped me out to find the problem (it was related to a another script that updated the kernel, and needed a prior reboot before running the DKMS).

Have a good day

**Comment by rickard-von-essen** [comment]
Glad to help, shell scripting is hard.
