### ISSUE TITLE
Issue with virtual_network_subnet_name on azure-arm

### ISSUE THREAD

**Issue by estebangarcia** [mitchellh/packer#3858]
Hi. I'm using Packer v0.10.2.dev (built from master) on OS X 10.11.2. While trying to create a new VHD using azure-arm I get this error:

`--> azure-arm: Found multiple subnets in the resource group "Fury" associated with the  virtual network called "VNET", please use virtual_network_subnet_name to disambiguate`

I'm getting the error with or without 'virtual_network_subnet_name'

Here is the gist with the log and the template
https://gist.github.com/estebangarcia/929dd80938011e36a5efea12307000da

Any help will be much appreciated.

Thanks

**Comment by boumenot** [comment]
Can you share a copy of configuration?

Have you tried specifying all of these values to make it exact?

 * virtual_network_name
 * virtual_network_resource_group_name
 * virtual_network_subnet_name

**Comment by estebangarcia** [comment]
@boumenot thanks for your response. An example of the configuration I'm using is on the gist I posted earlier.

No, I haven't tried using all three values, just virtual_network_subnet_name and virtual_network_name. I'll do it tomorrow.

Thanks

**Comment by estebangarcia** [comment]
@boumenot I can confirm that specifying the three values it works fine.
I hope this helps someone with the same issue.

Thanks for your help.

**Comment by boumenot** [comment]
w00t!  I'm glad this worked for you!  

Apologies for missing that the configuration was in the gist.  I did not realize that gist's could have multiple distinct files pasted in - my bad.
