### ISSUE TITLE
[question] How to output in vbox format, not ovf or ova

### ISSUE THREAD

**Issue by emo3** [mitchellh/packer#3859]
I have a question.
How does one output the results of packer and not have it complete the ovf/ova conversion step.

**Comment by rickard-von-essen** [comment]
Could you explain a bit more?

**Comment by emo3** [comment]
Per documentation:
The VirtualBox Packer builder is able to create VirtualBox virtual machines and export them in the OVA or OVF format.
I want to skip that step, ie do not export the virtual machine.

**Comment by emo3** [comment]
You have a command keep_registered in vmware.  Can we get the same cmd within virtualbox?

**Comment by rickard-von-essen** [comment]
Could you explain the scenario, i e why you want this?

**Comment by rickard-von-essen** [comment]
`keep_registered` is for ESXi and is bit strange fit for the purpose of Packer.

**Comment by tmzt** [comment]
@emo3 Are you asking for vagrant-like functionality? Create a virtualbox vm and leave it registered in the VirtualBox settings? Or are you looking to export the resulting VirtualBox .vbox file without converting to ova/ovf?

**Comment by emo3** [comment]
Yes I am to all your questions.  I want to verify the .vbox before I move on.  IE: iterate development with the kickstart and packer files.

**Comment by emo3** [comment]
Added code via #3954.  This will keep the vbox registered.
I will work on creating code to skip the converting to ova/ovf.

**Comment by synthesizerpatel** [comment]
This use has been available in master for a while if I understand you correctly.

I use virtualbox-iso to generate an OVA, and as a post-processor I also generate a vagrant .box file. In my case I want both (an OVA to import into vSphere or to convert into an AMI), and a .box file for developers to be able to use the same base boxes on their desktops.

The vagrant post-processor seems to run in less than a minute for me, so for iterative development it's been pretty good.

You can disable saving the OVA file by setting keep_input_artifact to false.

```
 "builders": [{
      "type": "virtualbox-iso",
      ....
    }],
 "post-processors": [
    {
      "type": "vagrant",
      "keep_input_artifact": true,
      "output": "{{ "blah.box" }}
    }
  ]
}
    
```

**Comment by emo3** [comment]
I will have to test that and see.  Thanks for the input.

**Comment by mwhooker** [comment]
Going to close this for now

**Comment by sejames** [comment]
OVA exports from Virtualbox are not automatically supported by VMware ESXi due to a variety of configurations necessary in OVF like hardware.
