### ISSUE TITLE
group_vars not recognised when under inventory directory using ansible remote

### ISSUE THREAD

**Issue by klatiss** [mitchellh/packer#3863]
$ packer -version
0.10.1

$ ANSIBLE_CONFIG=/home/karl/ansible/ansible.cfg ansible --version
ansible 2.1.1.0
  config file = /home/karl/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
  {
    "type": "ansible",
    "host_alias": "app-server-template",
    "playbook_file": "/home/karl/ansible/playbooks/app-server.yml",
    "groups": [
      "app-servers"
    ],
    "user": "centos",
    "ansible_env_vars": [
      "ANSIBLE_CONFIG=/home/karl/ansible/ansible.cfg",
      "ANSIBLE_HOST_KEY_CHECKING=False"
    ],
    "sftp_command": "/usr/libexec/openssh/sftp-server -e"
  },
```

The app-server.yml playbook includes a number of existing playbooks (/home/karl/ansible/playbooks) and roles (/home/karl/ansible/roles). group_vars are found under inventory (/home/karl/ansible/inventory/group_vars)

In this configuration the ansible remote provisioner fails as it cannot find the group_vars. I think this may be due to packer specifying an inventory file at runtime (with -i).

Moving/copying/linking the same group_vars to the playbooks directory fixes this issue however according to [the ansible docs](http://docs.ansible.com/ansible/intro_inventory.html) "group_vars/ and host_vars/ directories can exist in the playbook directory OR the inventory directory".

**Comment by bhcleek** [comment]
In the general case, because the directory that holds your other inventory files may be read-only, the inventory file can't be written to that location even if there were a property to specify the inventory directory. However, you can use `ansible_extra_vars` to specify the location of the variables file you want to use using `@file.yml` as documented at http://docs.ansible.com/ansible/playbooks_variables.html.

**Comment by kremers** [comment]
Same issue here! Being able to place the temporary inventory file somewhere would solve the problem.
Temporary solution:
```
ln -s /home/user/ansible_project/env_DEV/host_vars /tmp/host_vars
ln -s /home/user/ansible_project/env_DEV/group_vars /tmp/group_vars
```
works because of the cli command containing "-i /tmp/packer-provisioner-ansible423142001", so the inventory file sits under /tmp

**Comment by mwhooker** [comment]
Sounds like there's a workable fix for this.

Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by DrLongGhost** [comment]
This is what I added to my packer file that ended up working for me:

```
"groups": "db_servers",
"extra_arguments": [ "--extra-vars", "@../ansible/inventory/docker/group_vars/all.yml" ],
```

The "groups" argument helps ansible match the new Docker host against my playbook's host; the "extra-vars" argument lets me pass group_vars into ansible just for my Docker run.
