### ISSUE TITLE
Error 2 when trying to compile

### ISSUE THREAD

**Issue by emo3** [mitchellh/packer#3867]
Here is what I am doing:
$ export GOPATH=`pwd`
$ go get -u github.com/mitchellh/gox 
$ go get github.com/mitchellh/packer
$ cd $GOPATH/src/github.com/mitchellh/packer 
$ make updatedeps 
go get -u github.com/mitchellh/gox
go get -u golang.org/x/tools/cmd/stringer
INFO: Packer deps are managed by godep. See CONTRIBUTING.md
$ make bin 
go get github.com/mitchellh/gox
go get golang.org/x/tools/cmd/stringer
WARN: 'make bin' is for debug / test builds only. Use 'make release' for release builds.
==> Removing old directory...
==> Building...
Number of parallel builds: 11

-->      darwin/386: github.com/mitchellh/packer
-->   openbsd/amd64: github.com/mitchellh/packer
-->      darwin/arm: github.com/mitchellh/packer
-->     linux/amd64: github.com/mitchellh/packer
-->    darwin/amd64: github.com/mitchellh/packer
-->   freebsd/amd64: github.com/mitchellh/packer
-->     freebsd/386: github.com/mitchellh/packer
-->     windows/386: github.com/mitchellh/packer
-->     freebsd/arm: github.com/mitchellh/packer
-->   windows/amd64: github.com/mitchellh/packer
-->       linux/386: github.com/mitchellh/packer
-->     openbsd/386: github.com/mitchellh/packer
-->       linux/arm: github.com/mitchellh/packer

1 errors occurred:
**--> darwin/arm error: exit status 2**
Stderr: # github.com/mitchellh/packer
runtime.load_g: call to external function runtime.read_tls_fallback
runtime._initcgo: call to external function runtime.read_tls_fallback
runtime.save_g: runtime.read_tls_fallback: not defined
runtime.load_g: runtime.read_tls_fallback: not defined
runtime._initcgo: runtime.read_tls_fallback: not defined
runtime.save_g: undefined: runtime.read_tls_fallback
runtime.load_g: undefined: runtime.read_tls_fallback
runtime._initcgo: undefined: runtime.read_tls_fallback

==> Copying binaries for this platform...

==> Results:
total 42M
-rwxr-xr-x 1 emo3 emo3 42M Sep  7 19:16 packer

What do I need to fix to solve this error?

**Comment by cbednarski** [comment]
You should not run `make updatedeps`. Use `make dev` only. What version of go are you using?

**Comment by emo3** [comment]
I did not know that, documentation very limited in the compiling section.
$ go version
go version go1.6.2 linux/amd64
$ make dev
go get github.com/mitchellh/gox
go get golang.org/x/tools/cmd/stringer
==> Removing old directory...
==> Building...
Number of parallel builds: 11

-->     linux/amd64: github.com/mitchellh/packer
==> Copying binaries for this platform...

==> Results:
total 42M
-rwxr-xr-x 1 emo3 emo3 42M Sep  7 20:20 packer

BTW: How would I compile to darwin release?

**Comment by rickard-von-essen** [comment]
To cross compile do:
```
XC_OS=darwin XC_ARCH=amd64 make dev
```
