### ISSUE TITLE
SSH Proxy Support

### ISSUE THREAD

**Issue by defunct73** [mitchellh/packer#387]
Hello, will it be possible to add an enhancement to allow SSH to be proxied?  Similar to how you can achieve it with OpenSSH and the ProxyCommand setting?  Being stuck behind a firewall and unable to ssh 1) to verify the system is up and 2) use the shell provisioner sucks. :(

Thank you for consideration.

**Comment by acourtois** [comment]
This is a real issue for me. I can't use this amazing tool behind my f### corporate proxy... I also use corkscrew (the ProxyCommand entry from my ~/.ssh/config file).
Could you help us?

**Comment by rickard-von-essen** [comment]
Just to clarify how this work. Packer uses "native" go ssh lib, [go.crypto/ssh](https://godoc.org/golang.org/x/crypto/ssh), to ssh.

To be able to define a single proxy command or host might be feasible, but to honor ~/.ssh/config (OpenSSH) would probably be a lot of work.

**Comment by acourtois** [comment]
I understand :) But is there a way to provide a proxy to the packer's ssh connection step? I use packer to build my AWS AMIs all the time and I really like it :)

**Comment by mdthorpe** [comment]
I suggest it might be easiest to emulate override.ssh.proxy_command behaves in Vagrant.
I often use this feature to proxy ssh through a bastion host into instances I've launched in a VPC.
```
override.ssh.proxy_command = "ssh -q 1.2.3.4 nc -q0 %h 22"
```

**Comment by Hefeweizen** [comment]
+1 on desirability of this capability
