### ISSUE TITLE
Custom Commands feature removed? 

### ISSUE THREAD

**Issue by tlopo** [mitchellh/packer#3872]
Hi I was reading the documentation [here](https://www.packer.io/docs/extend/command.html) but It seems that feature was removed on [this commit](https://github.com/mitchellh/packer/commit/779b6d1719ced0828ccc0acb21c62f114284f8dd)

Was that feature removed completely or implemented in a different way?

**Comment by rickard-von-essen** [comment]
Yes it's remove but unfortunately the docs haven't been updated to reflect this. 

@mitchellh @cbednarski do you have any further info about this?

**Comment by cbednarski** [comment]
As far as I'm aware custom commands are no longer supported.
