### ISSUE TITLE
Cannot use vSphere post processor even on an older version

### ISSUE THREAD

**Issue by jfletcher93** [mitchellh/packer#3877]
For some reason when ever I run the vSphere post processor it refuses to work. I have followed several guidelines on how to do this but have had no success.

I get an error from the OVFtool stating that the "locator does not refer to an object" despite the path being 100% correct in my opinion. I can get the path to work using the OVFtool directly but packers seems to be including a random "ha-datacenter" inside the string following vi:\.

Anyone else had this issue or know a fix???

**Comment by rickard-von-essen** [comment]
Could you provide some more info, like a example and a log output?

**Comment by jfletcher93** [comment]
This is my current post processors from my json file (excluding sensitive information) 
 
```
"post-processors": [{

        "type": "vsphere",
        "only": ["vmware-iso"],
        "host": "Physical VCenter Host",
        "cluster": "Cluster",
        "datacenter": "DataCenter",
        "datastore": "Data store",
        "username": "root",
        "password": "Password!",
        "vm_name": "PackerPOC",
        "disk_mode": "thin",
        "vm_folder": "/",
        "vm_network": "DEAD_END",
        "insecure": true,
```
The build completes fine but once I reach the post processor this error comes up:

==> vmware-iso: Running post-processor: vsphere
    vmware-iso (vsphere): Uploading D:\Output-vmware-iso\packer-vmware-iso.vmx to vSphere
Build 'vmware-iso' errored: 1 error(s) occurred:
* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: D:\Output-vmware-iso\packer-vmware-iso.vmx
Error: Locator does not refer to an object: vi://root@host:443ha-datacenter/host/datastore/Re
sources/Datacenter/host/Cluster/Resources/
Completed with errors
==> Some builds didn't complete successfully and had errors:
--> vmware-iso: 1 error(s) occurred:
* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: D:\Output-vmware-iso\packer-vmware-iso.vmx
Error: Locator does not refer to an object: vi://root@host:443ha-datacenter/host/datastore/Re
sources/Datacenter/host/Cluster/Resources/
Completed with errors
==> Builds finished but no artifacts were created.

The bit that doesn't make sense to me is

**Comment by rickard-von-essen** [comment]
There is one fix for vSphere on master. I recommend that you build it and test with that.

There is no `ha-datacenter` in out code. If you fil in the issue template properly there might be enough information to help out.

**Comment by marema31** [comment]
The `ha-datacenter` is the value of datacenter part when you use the API directly on the ip of an ESXi and not on the ip of the Vcenter see [this post on vmware-communities](https://communities.vmware.com/thread/94077?start=0&tstart=0).

The path should be `vi://root@host:443/Datacenter/host/Cluster/` as described [here](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1038709)

**Comment by mwhooker** [comment]
Sorry you're having issues with this. If you're still having trouble, I would recommend bringing this to the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk). The mailing list has a lot more eyeballs on it than the github issue tracker, so I think you're more likely to find help there.

If you discover that this is a bug in packer, you should definitely open an issue. However, after a brief glance at this it's not obvious that there's a bug, so I'm going to close this.
