### ISSUE TITLE
Add ability to specify command in ansible-remote provisioner

### ISSUE THREAD

**Issue by evnm** [mitchellh/packer#3880]
It would be nice if the ansible-remote provisioner included a `command` configuration option akin to [that of the ansible-local provisioner](https://www.packer.io/docs/provisioners/ansible-local.html#command).

My motivating use case is that I have a playbook which does not yet support Ansible 2.0 and I'd like to enforce that the `ansible-playbook` from a specific virtualenv be invoked instead of any system default.

Happy to provide further details if necessary.

**Comment by bhcleek** [comment]
This is already possible; just use `command` to specify the command you want to run instead of `ansible-playbook`.

**Comment by evnm** [comment]
Ah, great. Thank you!
