### ISSUE TITLE
Parallels Desktop 12 Support

### ISSUE THREAD

**Issue by clivecrous** [mitchellh/packer#3881]
Please can we add support for Parallels Desktop 12

> 2016/09/13 08:42:00 packer: 2016/09/13 08:42:00 Parallels Desktop version: 12.0.1
> 2016/09/13 08:42:00 ui error: Build 'parallels-iso' errored: Failed creating Parallels driver: Unable to initialize any driver. Supported Parallels Desktop versions: 11, 10, 9

`packer version`
> Packer v0.10.1

**Comment by rickard-von-essen** [comment]
This have been fixed in master, see #3673. I recommend that you build from master, see [CONTRIBUTING.md](https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md#setting-up-go-to-work-on-packer)

**Comment by clivecrous** [comment]
Hi,

I raised this bug because building from masted does not work:

% make
go get github.com/mitchellh/gox
go get golang.org/x/tools/cmd/stringer
go generate .
2016/09/13 11:48:33 Generated command/plugin.go
go fmt command/plugin.go
command/plugin.go
can't load package: package github.com/mitchellh/packer/vendor/google.golang.org/api/compute/v1: code in directory /Users/clive/go/src/github.com/mitchellh/packer/vendor/google.golang.org/api/compute/v1 expects import "google.golang.org/api/compute/v1"
../../masterzen/winrm/auth.go:8:2: cannot find package "github.com/Azure/azure-sdk-for-go/core/http" in any of:
	/usr/local/Cellar/go/1.5.2/libexec/src/github.com/Azure/azure-sdk-for-go/core/http (from $GOROOT)
	/Users/clive/go/src/github.com/Azure/azure-sdk-for-go/core/http (from $GOPATH)
../../masterzen/winrm/auth.go:9:2: cannot find package "github.com/Azure/azure-sdk-for-go/core/tls" in any of:
	/usr/local/Cellar/go/1.5.2/libexec/src/github.com/Azure/azure-sdk-for-go/core/tls (from $GOROOT)
	/Users/clive/go/src/github.com/Azure/azure-sdk-for-go/core/tls (from $GOPATH)
communicator/winrm/communicator.go:10:2: cannot find package "github.com/masterzen/winrm/winrm" in any of:
	/usr/local/Cellar/go/1.5.2/libexec/src/github.com/masterzen/winrm/winrm (from $GOROOT)
	/Users/clive/go/src/github.com/masterzen/winrm/winrm (from $GOPATH)
make: *** [test] Error 1

**Comment by rickard-von-essen** [comment]
You need go 1.6
