### ISSUE TITLE
Support jsonpatch at build command

### ISSUE THREAD

**Issue by dploeger** [mitchellh/packer#3887]
On creating [Puppetdev](http://dennis.dieploegers.de/easy-puppet-testing-with-vagrant/) (https://github.com/dploeger/packer-puppetdev), I came around [JSONPatch](http://jsonpatch.com), a standardized format for modifying JSON documents.

Puppetdev is based on other Packer templates and modifies them heavily. It would be great, if the packer build-command could include support for JSONPatch files, which are applied (one after the other) to the original Packer template. Packer then would use the modified template.

This would enable a better workflow, if you like to rely on base images for specific features.

And: There's already a Go implementation for JSONPatch. 😉

**Comment by rickard-von-essen** [comment]
Thanks for the suggestion. It looks like a nice workflow and a good way for handling lots of packer configurations. But my general opinion is that Packer should be following a unix tool philosophy, do _one thing_ and be easily _composable_. I think we can improve on the later but we need to be careful to not add to much in.

**Comment by dploeger** [comment]
Yes, @rickard-von-essen. I think, you're right about that. However, adding Jsonpatch-Support wouldn't change that, IMHO. It's just a way of improving the tool, it's not some completely new thing for the tool to do.

**Comment by mwhooker** [comment]
Thanks for the tip, jsonpatch looks neat. I agree with rickard. Rather than making packer do everything, we should allow its behavior to be composible (part of the [tao](https://www.hashicorp.com/blog/tao-of-hashicorp.html)).
