### ISSUE TITLE
Bug: output-virtualbox-iso dir not respecting TMPDIR

### ISSUE THREAD

**Issue by juju4** [mitchellh/packer#3898]
- Packer version from `packer version`: 0.10.1
- Host platform: Ubuntu trusty

When building image, packer creates a directory output-virtualbox-iso inside current directory and deletes it at the end.
There are some past bug entries on TMPDIR like https://github.com/mitchellh/packer/issues/398 and I have the impression this directory should be inside.
Or at least easy to relocate. Currently, you can create a symlink but you have to pass -force flag to proceed build.

Comments?

Thanks

Note: may apply to other provider.

**Comment by mwhooker** [comment]
This is configurable with the `output_directory` setting in the config. This is part of the build output and so it's not a temporary file. I think you might be mistaken about it being deleted at the end.

You can look into `skip_export` if you don't want these files being created.
