### ISSUE TITLE
vagrantfile_template not being added

### ISSUE THREAD

**Issue by DarwinJS** [mitchellh/packer#3900]
I have the following in my packer template:

  "post-processors": [
    {
      "type": "vagrant",
      "vagrantfile_template": "subfolder/VagrantFile"
      "only": ["virtualbox-iso"]
    }
  ]

"subfolder" is directly under the folder where the template is.  I followed the same format for subfolder and directory seperators as calling a "script".

However, when I extract the resultant box file, the embedded vagrant file contents are as follows:
```

# The contents below were provided by the Packer Vagrant post-processor

Vagrant.configure("2") do |config|
  config.vm.base_mac = "08002775BD9E"
end


# The contents below (if any) are custom contents provided by the
# Packer template during image build.
```
That's the exact file - there is nothing after the comment about the packer template.

Does the vagrantfile_template parameter need to be referenced in a different way?  I couldn't find any examples on the net.

Packer 0.10.1
Windows 10

**Comment by rickard-von-essen** [comment]
Could you please gist a debug log. From running `PACKER_LOG=1 packer build template.json`.

**Comment by DarwinJS** [comment]
4th line in what I posted above has no comma - yet I didn't get the expected choking of the JSON processing as packer started.

Apologies for bothering you and will post debug logs on initial report if I find any actualy bugs :s

**Comment by DarwinJS** [comment]
Quick related question if anyone has a moment.

I did the embedded Vagrant file and it seems it was ignored.

1) From the packer docs, my understanding is that a packaged Vagrantfile is not used during "vagrant init", but should be used during "vagrant up" - please confirm if my understanding is correct because the documentation was a little vague (does not explicitly say "used during vagrant up")

If the above is correct, I may be having an end of line issue.

The top portion of the packaged Vagrantfile has no end of line characters, so looks like this in notepad (all one line).  (Fyi viewing in an editor that understands both types of line endings (atom), it looks fine)

The rest of the file from my packager "vagrantfile_template" has end of line characters that display correctly in Windows.

I am both building with packer and using vagrant on WIndows.

This line ends up being one line which I assume means it isn't running due to the comment character.
# The contents below were provided by the Packer Vagrant post-processor Vagrant.configure("2") do |config| config.vm.base_mac = "08002775BD9E" end # The contents below (if any) are custom contents provided by the # Packer template during image build.

But the part that looks correct does not run.

**Comment by DarwinJS** [comment]
FYI 
robocopy /XF ".chocolate*" 

works to exclude the file.  I haven't tested xcopy.
