### ISSUE TITLE
create and launch vm between different platform

### ISSUE THREAD

**Issue by mingjian2049** [mitchellh/packer#3906]
Can packer implement the cross-platform function, and where is the plugin?
I want to create the packer-image from ami then transfer it to digitalocean. Should I implement a new plugin?

**Comment by rickard-von-essen** [comment]
It doesn't move images between builders (clouds). But you can identify similar upstream images i.e. _Ubuntu 14.04_ and run the same _provisioning_ on both images.

If you have usage questions use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.
