### ISSUE TITLE
builder/openstack: 404 when saving an image

### ISSUE THREAD

**Issue by Eleanore** [mitchellh/packer#3907]
I have some problems while cooking my image on OpenStack.
I am creating an image as follows:
- it is based on a CoreOS image
- it contains a Docker image to be launched on startup
  Notice that the Docker image contains **100MB of genomic (textual) data**, plus some software.

When packer is launched, the creation of the OpenStack instance works, the server is correctly turned on, configured, shut down, and the image correctly created (I can see both the OS instance and image from Horizon). But then, OpenStack starts saving the image (you can see a "Saving..." icon aside the image), it remains stuck for a while, and them Packer throws an error:

```
==> openstack: Waiting for image my_os_image (image id: 33eb18c2-ba82-41e2-acd8-0062ac6c9720) to become ready...
==> openstack: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://192.168.100.3:8774/v2.1/images/33eb18c2-ba82-41e2-acd8-0062ac6c9720], but got 404 instead
==> openstack: {"itemNotFound": {"message": "Image not found.", "code": 404}}
==> openstack: Deleted temporary floating IP 192.168.100.165
==> openstack: Terminating the source server: 54747845-3731-4fb1-abc9-aa9b7ced2154 ...
Build 'openstack' errored: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://192.168.100.3:8774/v2.1/images/33eb18c2-ba82-41e2-acd8-0062ac6c9720], but got 404 instead
{"itemNotFound": {"message": "Image not found.", "code": 404}}

==> Some builds didn't complete successfully and had errors:

--> openstack: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://192.168.100.3:8774/v2.1/images/33eb18c2-ba82-41e2-acd8-0062ac6c9720], but got 404 instead
{"itemNotFound": {"message": "Image not found.", "code": 404}}
```

Is there something I am missing? I have tried the same Packer configuration file with another (more light-weighted) project, and it works pretty well. Is there some timeout or something that is preventing Packer to store the image?

Notice that the issue has been raised a while ago, but I still have the same error:
https://github.com/mitchellh/packer/issues/1415#issuecomment-165739549

**Packer versions**
I am using two Packers, on two different OS, which both give problems.
On OSX:

```
$ packer --version
0.10.1
```

On Linux:

```
$ packer --version
0.10.1
```

**Logs**
- Debug log output from `PACKER_LOG=1 packer build template.json`: https://gist.github.com/Eleanore/f5951445f7ea322f4539d38c33a0a155

**Scripts**
- Packer configuration: https://gist.github.com/Eleanore/c8d9c27150fdcb860418a844dff91f8b
- File referenced by Packer configuration: https://gist.github.com/Eleanore/8b2ac35cce207db42dddc21cd00d422b

**Comment by rickard-von-essen** [comment]
Could you gist the _full_ log?

**Comment by Eleanore** [comment]
Sorry, here it is:
https://gist.github.com/Eleanore/03f4e477e5014492aba1639070401904

**Comment by rickard-von-essen** [comment]
You OS does after a while start returning 404 not found on getting the image. The PR #3009 just retries for 20 seconds before giving up. There is probably an error in the OS logs. If you want to build from source it would be nice to see if this persist for ever. If you update https://github.com/mitchellh/packer/blob/8040317f7747eaee5b4ec7cad783700a58266fdb/builder/openstack/step_create_image.go#L65 to 100.

**Comment by mwhooker** [comment]
Hi @Eleanore 

Very happy to help with this issue if you're still running into it. I think the mailing list would be a great place to get some help on this: https://groups.google.com/forum/#!forum/packer-tool

Going to close this for now unless you've got new information
