### ISSUE TITLE
Feature: amazon-ebs: ability to set snapshot name

### ISSUE THREAD

**Issue by koitsu** [mitchellh/packer#3908]
Packer v0.10.1

Naming AMIs is simple: use the ami_name field in the builder config.  An AMI has a snapshot associated with it.  It would be useful if we could also set the name of the snapshot.  For snapshots, this is accomplished using a tag (named "Name").

However, the builders config currently does not have distinction between AMI tags and snapshot tags, which poses a conundrum.  Take for example this:

```
"variables": {
  "label": "test-{{isotime \"20060102T1504\"}}"
},
"builders": [{
  ...
  "ami_name": "{{user `label`}}",
  "tags": { "Name": "{{user `label`}}" }
}],
```

The results:
- An AMI named test-YYYYMMDDThhmm
- That AMI having a tag called Name with the value test-YYYYMMDDThhmm
- The associated snapshot having a tag called Name with the value test-YYYYMMDDThhmm

Any chance of implementing a field called snapshot_name that simply sets the Name tag on the snapshot (and only the snapshot)?

**Comment by rickard-von-essen** [comment]
Could you describe why it's useful to have different names (for you)?

**Comment by koitsu** [comment]
I personally don't want different names: what I want is the ability for packer to set a tag on a snapshot but not an AMI.  To recap: by using the "tags" attribute in builders, the AMI ends up getting a tag called "Name" that serves literally no purpose -- and creation of it will only confuse someone in the EC2 Console when reviewing tags or when configuring columns/fields in the GUI (I can absolutely see my boss saying "What is AMI Name vs. Name?  If they're the same, why does Name even exist?").  If you need screenshots/proof of this, I can provide it.

That said: I have worked at places where AMI names and snapshot names were different.  AMI names were {purpose}-{role}-{serial} while snapshots were snap-{serial}, and this was intentional.  So there's an example of where differentiating the two would be useful.

**Comment by koitsu** [comment]
Thank you for this -- works wonderfully. :)
