### ISSUE TITLE
Same to #2509

### ISSUE THREAD

**Issue by william-graphsql** [mitchellh/packer#3910]
Hi Mitchell/Packer Developer,

I am encountering the same issue as #2509 , I followed the [instruction here](https://www.packer.io/docs/builders/qemu.html), however.

1), The information here seems outdated, on that page, it is 6.8 instead of 6.5, maybe you can update it, after all, you just raise $24M, should have the resources to do some better work.
2), Have you ever tested it, since it seems that it is not working, I tried in both VMWare CentOS 7, VMWare Ubuntu 14.04 LTS, and my physical Ubuntu box, in physical one, it is saying ssh time out.

Would you like to provide any insight? Since I am not golang expert, and some kind of waiting for it.

Thanks,
William

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).
