### ISSUE TITLE
Does packer support RHEL family systems?

### ISSUE THREAD

**Issue by chytreg** [mitchellh/packer#3912]
I'm trying to use packer on centos 7, tried on redhat too, and I stuck. When I run `PACKER_LOG=1 packer` it does nothing, it hangs, not responding, there is no log message anything I could post here. I could help you to debug the issue if somebody gives me instructions how to do this.

**Comment by rickard-von-essen** [comment]
Yes packer should run on basically any Linux. 

Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

**Comment by chytreg** [comment]
> Yes packer should run on basically any Linux.

Have you tested on any RHEL system?  I did, and without checking this personally I wouldn't mark this as a question. How I can properly bug report this issue when there is no log which I can attach?

> When I run PACKER_LOG=1 packer it does nothing, it hangs, not responding, there is no log message anything I could post here. 

I'd like to note that on download/installation page there is no word about additional requirements needed to run packer. When there are any it should be placed there.

**Comment by chytreg** [comment]
@rickard-von-essen here is https://gist.github.com/chytreg/d2f2908b6dd6f2695abf393fff5c5477
what `strace -f packer` shows to me.

**Comment by vtolstov** [comment]
This is know issue,rhel have own packer command.
Place packer downloaded from binaries to somewhere and put into PATH
variable path for binary at the beginning.
Because now you run rhel packer binary and not hasicorp packer.

22 Сен 2016 г. 13:56 пользователь "Dariusz Gertych" <
notifications@github.com> написал:

**Comment by chytreg** [comment]
Thx for explanation, now it works for me.

**Comment by vtolstov** [comment]
@rickard-von-essen i think we need this in FAQ, because rhel/fedora users have this problems...

**Comment by rickard-von-essen** [comment]
It's here https://www.packer.io/intro/getting-started/setup.html
Under troubleshooting.

**Comment by vtolstov** [comment]
@rickard-von-essen thanks =)
