### ISSUE TITLE
Packaged Vagrantfile malformed when using Windows to build

### ISSUE THREAD

**Issue by DarwinJS** [mitchellh/packer#3914]
I am running all of this on Windows - Packer build and Vagrant init/up

When I specify "Vagrantfile_template" in packer, I can open the .BOX file and see that the merge of the standard packaged vagrant file and my specification was done and embedded.

However, the top portion of the packaged Vagrantfile does not have Windows compatible end of line characters, so looks like this in notepad (all one line):

`# The contents below were provided by the Packer Vagrant post-processor Vagrant.configure("2") do |config| config.vm.base_mac = "08002775BD9E" end # The contents below (if any) are custom contents provided by the # Packer template during image build.
`
Since the above oneliner starts with a comment, it ends up commenting that entire block.

However, the first line of my file also ends up being in that block - so it effectively renders my code useless.

I am going to try working around this by inserting some blank lines or comments in the top of my file - which would mean my file runs, but the built-in default will not.

It seems like some end of line logic may need to be used to ensure that this file is usable for Vagrant running on any deployed to OS?

**Comment by rickard-von-essen** [comment]
Ruby files should_not_ have Windows line endings. (Don't use Notepad for development, it's broken)

I think everything works as it should. If you think there is a issue here can you provide some on what doesn't work and what you expect to happen and info on how to reproduce. The issue template is there for a reason. Also feel free to post to the mailing list if you are unsure about the behavior of Packer someone will tell you if it's unexpected behavior.

**Comment by rickard-von-essen** [comment]
I don't believe there is any bug here, if disagree reopen and provide more detailed information.

Please only use _GitHub Issues_ for reporting bugs and feature requests. For asking general questions use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/
