### ISSUE TITLE
apply run_tags to temporary security group

### ISSUE THREAD

**Issue by mrooney** [mitchellh/packer#3915]
It would be awesome if packer applied tags specified via `run_tags` to the temporary `security group`. I understand that it prefixes the name/descriptions with packer so this helps a bit for cleanup. However it doesn't help for security / IAM policies because IAM policy conditions can only be based on tags, not resource names or descriptions.

For example, it would be awesome to be able to specify in my packer json `run_tags` of `{"origin": "packer"}` so that I don't have to provide global `ec2:DeleteSecurityGroup` permission. If these were tagged, we could specify in our AIM policies for those permissions:

``` json
"Condition": {"StringEquals": {"ec2:ResourceTag/origin":"packer"}}
```

and our operations team would actually give us access keys to do this :) Packer should ideally not need permissions to delete any and all security groups. I realize also that I could manually create a SG and specify that, however the automated temporary ones are a really nice feature and greatly ease server/automation provisioning.

**Comment by rickard-von-essen** [comment]
`keypairs`doesn't take tags.

**Comment by mrooney** [comment]
Thanks @rickard-von-essen, I updated the issue :) Would be great for SGs!

**Comment by rickard-von-essen** [comment]
And unfortunately `ec2:DeleteKeyPair` doesn't seems to work with anything except `Resource: *`.

**Comment by rickard-von-essen** [comment]
Agree, adding `run_tags` on security groups make sense since then `ec2:DeleteSecurityGroups` can be limited with:

```json
"Condition": {
   "StringEquals": {
       "ec2:ResourceTag/<tag>": "<value>"
    }
}
```

**Comment by mwhooker** [comment]
Sounds good. I wonder if we could simply add a tag to the group that's something like `"packer_resource": "<run_id>"`, or if it would be desirable to set the tags manually.

We already support something like this for volumes, which adds an entirely new config option, `"run_volume_tags"`. I'd ideally like to keep the footprint as small as possible.

However, this is not something we're targeting for 1.0, so I'm going to close this. The best way to get this added would be to implement one of the ideas above. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by nictrix** [comment]
@mwhooker Is this something the project will still consider implementing? If so I think using the existing run tags for the security group would be good enough.
