### ISSUE TITLE
Implement DownloadDir for docker

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#3916]
Currently when you try to download a directory from a docker container, you're greeted with this error:

`Build 'docker' errored: DownloadDir is not implemented for docker`

This should be feasible to handle, since we can export a tar of a directory, and untar it locally.

I'm curious if this behavior was left out intentionally for some technical reason I'm not aware of.

reproducible with https://gist.github.com/mwhooker/503a9f2b7bfb394ea5566ee31a72f4b6

**Comment by rickard-von-essen** [comment]
Just be careful of what we expect exists inside the container. I would like to allow this to work with the _scratch_ image.

**Comment by mwhooker** [comment]
I believe the docker server is responsible for extracting the files from the container (ie https://docs.docker.com/reference/api/docker_remote_api_v1.20/#get-an-archive-of-a-filesystem-resource-in-a-container), so it shouldn't matter what type of container you're trying to pull files from. I'm fairly certain this is what's actually happening when we run `cp $PATH -` as we do now, but #3917 looks like it uses the API anyway.

**Comment by rickard-von-essen** [comment]
@mwhooker sounds good

**Comment by mwhooker** [comment]
let's revisit as part of #4186

**Comment by ziggythehamster** [comment]
Has this been forgotten? This feature still doesn't exist

**Comment by SwampDragons** [comment]
This isn't very high on the priority list right now so the core maintainers will probably not get to it. PRs are always welcome, though.
