### ISSUE TITLE
ansible-local provisioner: Allow multiple group_vars paths

### ISSUE THREAD

**Issue by stevenscg** [mitchellh/packer#3927]
Feature request to allow multiple `group_vars` and `host_vars` similar to `role_paths` and `playbook_paths`.

My specific use case is a scenario where I have group_vars in two or more different Ansible projects that are all needed to perform a particular build. Think of a main configuration repo and a separate vault configuration repo owned by different teams, etc.

This would also allow the "vars" and "paths" configuration objects to be consistent.

https://www.packer.io/docs/provisioners/ansible-local.html#group_vars

**Comment by mwhooker** [comment]
That's a great idea. One thing we'd want to be careful of, though, is backwards-compatibility. We want to make sure that old configs that only have a single `host_vars` path don't error.

I'm not sure what the best way to do that just yet is, though. Does anyone have any ideas?

**Comment by stevenscg** [comment]
Could `group_vars` and `host_vars` be deprecated in favor of `group_vars_paths` and `host_vars_paths` (or similar)? This would be even more consistent with the other "paths" variables.

Otherwise, possibly checking for a comma in the existing vars and exploding the strings into an array.

**Comment by bhcleek** [comment]
@rickard-von-essen I believe this is incorrectly labeled with `provisioner/ansible-remote`.

**Comment by rickard-von-essen** [comment]
@bhcleek fixed

**Comment by mwhooker** [comment]
This isn't something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
