### ISSUE TITLE
Packer detects script exiting with 0 code when it did not complete

### ISSUE THREAD

**Issue by dfairhurst** [mitchellh/packer#3931]
Running packer with VIO OpenStack (VMWare integrated OpenStack) I have an intermittent issue where packer seems to continue onto the next provisioning script, believing there to be no problem, even though it got disconnected when running one provisioning script and didn't do anything that I needed it to do.
Strangely, it always seems to happen during the same 'yum install' command, but I'm not sure how that could be linked.

The log is here, and shows that it got disconnected, and that the yum install command did not complete (it said 'going to install' but never actually installed anything)
  https://gist.github.com/dfairhurst/859a41426e63534002d30de282e25b1b

The problem isn't so much the disconnection, which is likely not packer's fault, but the fact that packer carries on and can give me an image I expect to work, but which has not had customisation performed that I expect.

packer version is 0.10.1

**Comment by dfairhurst** [comment]
After re-reading the log and looking at the code where the connection reset error comes from, I think I was wrong in my initial assessment.  It doesn't seem to come from a disconnection, but the yum install command never completes, and the remainder of my provisioning script never completes, but packer seems to think there was a 0 return code.

**Comment by dfairhurst** [comment]
Could be the same or similar to https://github.com/mitchellh/packer/issues/3920

**Comment by mwhooker** [comment]
I think we fixed this as part of some work on the ssh communicator.

Please re-open if you continue to see this
