### ISSUE TITLE
Release 0.10.2 unavailable from website or in Atlas

### ISSUE THREAD

**Issue by ajlanghorn** [mitchellh/packer#3942]
Packer 0.10.2 is available as a GitHub release, but it's not available via the Downloads page. I looked in the source, and it seems the latest version is exposed to the Downloads page ERB template as a variable. The `config.rb` file is up to date, but the Downloads page hasn't picked up that a new version is available.

This applies to the version listed at the top of the page, and the binaries listed on the page. Similarly, 0.10.2 isn't available via Atlas just yet; are there plans to make it available soon?

**Comment by cbednarski** [comment]
Thanks for the heads up. You can download the 0.10.2 release from [releases.hashicorp.com](https://releases.hashicorp.com/packer/0.10.2/).

Currently updating the website will also push out all of the documentation updates on master, which are for 0.11, not 0.10. We're looking into getting just the download page updated.

**Comment by cbednarski** [comment]
Also, 0.10.2 fixes a compatibility problem with macOS Sierra but otherwise 0.10.1 and 0.10.2 are functionally identical, so there is no difference between these versions on Atlas.
