### ISSUE TITLE
Azure Provisioner no longer working due to x509 certificate verification failure

### ISSUE THREAD

**Issue by samirageb** [mitchellh/packer#3946]
As of 10 hours ago, I can no longer use the Packer ARM builder due to an error 'x509: certificate signed by unknown authority'. Previously (for weeks) no problems.

I *believe* it has to do with the fact that I can't verify the SSL chain at https://management.azure.com 

Using 'curl -vvv https://management.azure.com' on Ubuntu gives me an output of: 
**server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none**
with 'curl -V' producing
**curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3**

Curl on Windows verifies the cert chain fine, as does Chrome on Windows. (I realize different behaviors is common)

I have verified the root CA certificate exists on my Ubuntu instance in /etc/ssl/certs/ and that it's still valid through 2025.  Just for the heck of it, I even added the file being served at that URL via this SO post [server certificate verification failed](http://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c) which solved my curl verification problem, however Packer still outputs the same behavior.

At this point, I don't believe this is a Packer bug per se, but something that Packer Azure users will experience. Any assistance you can provide in allowing me to disable SSL checking for Packer (not a great idea I know) or somehow get me to add this chain so that golang considers it trusted, is greatly appreciated.

- Build machine: Jenkins (latest)
- Packer version 10.2
- Ubuntu 16.04 (64-bit) w/ kernel 4.6.3-040603-generic
- Golang version 1.7
- Debug output: [click here](https://gist.github.com/samirageb/80ea0989488430762b9ab7b17f5f54ed)

**Comment by rickard-von-essen** [comment]
This works for me

```bash
root@f3083d42e215:/#  uname -a
Linux f3083d42e215 4.4.20-moby #1 SMP Thu Sep 8 21:27:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@f3083d42e215:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
root@f3083d42e215:/# curl https://management.azure.com
{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}
```

Could you launch fresh Ubuntu 16.04 and test in. My guess is that you cert-bundle is somehow broken.

**Comment by samirageb** [comment]
Ok, I've tried this command on 7 different VMs, with some on 4.7 kernel, all same result.
`curl https://management.azure.com
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
ubuntu@Ingest:~$ uname -a
Linux Ingest 4.6.3-040603-generic #201606241434 SMP Fri Jun 24 18:36:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

The only thing these VMs have in common is that they're all hosted inside of Azure... Does this make any sense?

**Comment by rickard-von-essen** [comment]
Can you gist the output of:
```bash
openssl s_client -connect management.azure.com:443
```

**Comment by samirageb** [comment]
Results from cmd on 2 different Ubuntu VMs

[System 1](https://gist.github.com/samirageb/e55bdf9a39f9d54569a8c4202bb4bc53)
[System 2](https://gist.github.com/samirageb/d2e43d46203df65963d108463b9444e6)

**Comment by samirageb** [comment]
Also my OpenSSL version is: **OpenSSL 1.0.2g  1 Mar 2016**

**Comment by samirageb** [comment]
So the Root CA is 'Baltimore CyberTrust Root' with a cert expiration of 2025. I have a ```Baltimore_CyberTrust_Root.pem``` in my ```/etc/ssl/certs/``` directory.

As this is a DigiCert issued certificate, I've gone to their page to check out their bundles: [DigiCert Root Certs](https://www.digicert.com/digicert-root-certificates.htm)

If I run this command:
```console
openssl s_client -connect baltimore-cybertrust-root.digicert.com:443
```
I get the entire chain verified.

**Comment by samirageb** [comment]
I've opened a ticket with Microsoft but won't hear back until Monday.  I've run out of ideas.  Thanks for the assistance and I'll post back the outcome here.  If you think of anything else let me know.

**Comment by rickard-von-essen** [comment]
The responses looks wrong in _System 1_ and _System 2_. It should start with:
```bash
root@f3083d42e215:/# openssl s_client -connect management.azure.com:443
CONNECTED(00000003)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT SSL SHA2
verify return:1
depth=0 CN = management.azure.com
verify return:1
---
Certificate chain
 0 s:/CN=management.azure.com
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
```

Which shows a proper certificate chain.

**Comment by samirageb** [comment]
Been trying every hour or so, and now everything works.... No changes on my end, just self-resolved.

Thanks for the assistance and patience. Now I got a few more things I can look at in the future. Cheers.
