### ISSUE TITLE
Migrate to govendor

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#3955]
The rest of the hashicorp tools have already made the move.

Currently we have problems identifying deltas between the godep.json file and the vendor/ directory. govendor will make this simpler.

see #3949

**Comment by mwhooker** [comment]
Here's some context from when this was tried before: https://github.com/mitchellh/packer/pull/3852

I noticed @rickard-von-essen had some reservations. I wonder if they still apply?

**Comment by rickard-von-essen** [comment]
I don't have any thing against govendor per se. Just that PR contained stuff that didn't match what godep would add.
