### ISSUE TITLE
[FEATURE] qemu builder using existing qcow2 image file

### ISSUE THREAD

**Issue by candlerb** [mitchellh/packer#3959]
I would like a variant of the qemu builder which instead of installing from an ISO image, starts from an existing qcow2 image<sup>1</sup>

Use case: you are building lots of VM variations from the same base ISO image, with different provisioners.

The ISO install process is by far the slowest part of the build; hence it would be *much* faster to run the ISO install once and then run multiple provisioner installs using the same qcow2 base.

This could also be thought of as an analog to the EC2 builder working from an existing AMI.

This builder would still have to create the qcow2 file and start qemu with the right options. Making it a mode of the existing qemu provisioner might be the simplest approach?

-----

<sup>1</sup> you could simply `cp` the existing qcow2 file, but a better solution is to make a new qcow2 file with the original one as copy-on-write base:

~~~
qemu-img create -f qcow2 -b path/to/old.qcow2 path/to/new.qcow2
~~~

This is fast and cheap. The user can later flatten out the base+clone to a single file using `qemu-img convert` if required.

**Comment by rickard-von-essen** [comment]
This is already supported see https://www.packer.io/docs/builders/qemu.html#disk_image.

**Comment by candlerb** [comment]
Thank you. It didn't occur to me that there's a flag to say the ISO file is not an ISO file 👍 

However I'm having a problem. In my new builder I have:

~~~
      "disk_image": true,
      "iso_url": "output-qemu-base/vtp-base.qcow2",
      "iso_checksum_url": "output-qemu-base/vtp-base.qcow2.sha256",
      "iso_checksum_type": "sha256",
~~~

Those two files do exist. But I get this error:

~~~
==> qemu: Downloading or copying ISO
    qemu: Downloading or copying: file:///data/vtp/output-qemu-base/vtp-base.qcow2
    qemu: Error downloading: Checksum or Hash isn't set on download.
==> qemu: ISO download failed.
Build 'qemu' errored: ISO download failed.
~~~

(This is with packer 0.10.2, which I believe is the latest released version)

**Comment by vtolstov** [comment]
iso_checksum_url need to special syntax. via file:/./.. but why you need it? you use local file  - disable checksum checking

**Comment by candlerb** [comment]
It's hapy with `iso_checksum` but not `iso_checksum_url`. I think this is a bug, but the workaround isn't too bad:

~~~
    "variables": {
      "iso_checksum": null
    },

...
      "disk_image": true,
      "iso_url": "output-qemu-base/vtp-base.qcow2",
      "iso_checksum": "{{ user `iso_checksum` }},
      "iso_checksum_type": "sha256",

..
packer -var iso_checksum=$(cat output-qemu-base/vtp-base.qcow2.sha256)
~~~

**Comment by candlerb** [comment]
If I use local file like this:

~~~
~~~

If I only specify `"iso_url"` and `"disk_image": true`, it fails:

~~~
1 error(s) occurred:

* The iso_checksum_type must be specified.
~~~

**Comment by candlerb** [comment]
And if I add `"iso_checksum_type": "sha256"` without an actual checksum, I get this:

~~~
1 error(s) occurred:

* Due to large file sizes, an iso_checksum is required
~~~

**Comment by candlerb** [comment]
The workaround `file:/./foo` doesn't seem to work with relative files.

~~~
      "iso_checksum_url": "file:/./output-qemu-base/vtp-base.qcow2.sha256",
~~~

gives:

~~~
* open /./output-qemu-base/vtp-base.qcow2.sha256: no such file or directory
~~~

I have also tried `file://./foo`, `file:///./foo` and they both convert to absolute paths starting `/./`. `file:./foo` is just treated as a non-existent filename.

**Comment by candlerb** [comment]
OK stupid me: `"iso_checksum_type": "none"` !

**Comment by candlerb** [comment]
I'm going to keep the sha256 checksum for my qcow2 image. It's a useful flag that the build was successful and the image hasn't been corrupted in the mean time.

So this just leaves a bug report that `iso_checksum_url` doesn't seem to work with relative filenames. Would you like me to open a separate issue?

**Comment by rickard-von-essen** [comment]
The solution is simple just:
```json
{
  "variables": {
    "pwd": "{{ env `PWD` }}"
  },
  "builders": [
    {
      "type": "qemu",
      "iso_checksum_url": "{{ user `pwd` }}/output-qemu-base/vtp-base.qcow2.sha256"
    }
  ]
}
```

**Comment by rickard-von-essen** [comment]
I'm closing this since the original feature request is already implemented. If you find any issues or have feature requests please open a new issue. 

For general help on Packer use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

**Comment by candlerb** [comment]
OK. Many thanks.
