### ISSUE TITLE
[FEATURE] qemu kernel/initrd from ISO

### ISSUE THREAD

**Issue by candlerb** [mitchellh/packer#3960]
One reason the qemu installer is so slow to install from an Ubuntu ISO is that it has a large amount of "blind typing" sent to the installer at about 1 character per second. See [this example](https://github.com/puppetlabs/puppetlabs-packer/blob/master/templates/ubuntu-16.04/x86_64.virtualbox.base.json#L25) which is what I have based my own configs on.

It works but is very slow, and seems like it could be fragile.

I think it would be better if it were possible to kick off qemu with `-kernel`, `-initrd` and `-append` flags so that the installer can start straight away.

This is already possible in principle using `qemuargs`, but I would like to use the kernel and initrd from the ISO image.

Perhaps have an option for packer to loopback-mount the ISO image after downloading it? Or use a tool like 7z to extract just the files of interest?

**Comment by rickard-von-essen** [comment]
That seams like very host and guest OS dependent.

**Comment by candlerb** [comment]
Fair enough.

I initially thought `floppy_files` would be just as host-dependent, but now I see this is coded in native go: <https://github.com/mitchellh/go-fs>

I also wondered about copying the kernel from ISO into the floppy, and setting qemuargs to boot from that. Except that the kernel is now 7MB and wouldn't even fit on a 2.88MB floppy :-(

**Comment by rickard-von-essen** [comment]
I'm not sure disk size limits are imposed.

**Comment by candlerb** [comment]
(Was going to look into floppies greater than 2.88MB, but then...)

I realise this won't work. The `-kernel` option to qemu needs to point to a local file.

So it *is* necessary to extract the file from the ISO onto the host filesystem. In the absence of go code for iso9660, it can be done by shelling out to 7z:

~~~
# 7z x packer_cache/96301dfe00958ccc15c4b15a016138d336240888efbdec8159e2c36dfc4bdbed.iso install/vmlinuz

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_GB.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: packer_cache/96301dfe00958ccc15c4b15a016138d336240888efbdec8159e2c36dfc4bdbed.iso

Extracting  install/vmlinuz

Everything is Ok

Size:       7015896
Compressed: 686817280
# ls -l install/vmlinuz
-rw-r--r-- 1 root root 7015896 Apr 20 14:00 install/vmlinuz
~~~

This would require a hook to run a script in the builder, *after* the ISO image has been downloaded and verified, but *before* qemu is started.

I guess I could set the "qemu_binary" option to point at a script which does the extraction and then exec's the real qemu?

**Comment by candlerb** [comment]
Actually I'm less worried about this now that I am using qcow2 disk images for packer. The need to build from ISO will be much less frequent.
