### ISSUE TITLE
[FEATURE] templating for floppy files

### ISSUE THREAD

**Issue by candlerb** [mitchellh/packer#3961]
```
      "floppy_files": [ "packer_files/preseed.cfg" ],
```

It would be nice if such files could be subject to template expansion, so you could have e.g.

```
d-i passwd/root-password password {{ user `ssh_password` }}
d-i passwd/root-password-again password {{ user `ssh_password` }}
```

**Comment by mwhooker** [comment]
This sounds like a reasonable idea. However, we're focused on 1.0 right now, and this has very low chance of ever being a priority for us,  do so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
