### ISSUE TITLE
Feature: Make .HTTPIP / .HTTPPort available outside of boot_command

### ISSUE THREAD

**Issue by candlerb** [mitchellh/packer#3973]
(Using packer 0.10.2)

The documentation says that `.HTTPPort` is only available during the expansion of `boot_command`, and indeed this seems to be the case. It expands to the literal string `<no value>` when used in a provisioner.

However the HTTP server remains running after the boot phase phase, and I would like to be able to access files on the HTTP server during later provisioning steps, e.g.

~~~
      "inline": [
        "curl http://10.0.2.2:{{.HTTPPort}}/foo | ....",
        ...
~~~

Workaround 1: set http_min_port and http_max_port to be the same (but then concurrent builds will fail)

Workaround 2: use a different mechanism where possible, e.g. the file upload provisioner

**Comment by rickard-von-essen** [comment]
The only scenario where this wouldn't be achievable (and prefered) with the `file` provisioner is if you use communicator `none`, and in that case you can't run any provisioner any way. 

And there is nothing stopping you from writing the `.HTTPPort` in a temp file in the `boot_command` and sourcing that file in your provisioner. 

If you have a use case not covered the above please describe it in more detail.

**Comment by candlerb** [comment]
> there is nothing stopping you from writing the .HTTPPort in a temp file in the boot_command and sourcing that file in your provisioner.

I'm using the qemu builder, and boot_command is just stuff typed blind to the target. I can't see a way to capture it on the host.

My specific case right now is building pfSense, a firewall appliance. The boot phase does a vanilla install from ISO to filesystem, with a handful of keystrokes. After it reboots you can connect using ssh.

I was actually hoping pfSense would have a command to restore its config from a provided URL, but actually it doesn't. So I've changed to using the `file` provisioner, and uploading a script to restore the config from the local file, which means I don't need this right now.

But is there a particular reason not to allow `.HTTPPort` to be used in later expansions?

**Comment by rickard-von-essen** [comment]
> `boot_command` is just stuff typed blind to the target. I can't see a way to capture it on the host.

During the install there is usually a way of getting a shell, get that and the in your `boot_command` do something like `echo "{{ .HTTPIP }}" > /tmp/host_ip`.

> But is there a particular reason not to allow `.HTTPPort` to be used in later expansions?

Because `.HTTPIP` (etc) is tied to that particular _builder_. Provisioning is agnostic of which type of _builder_ it is running on.

**Comment by candlerb** [comment]
> Because `.HTTPIP` (etc) is tied to that particular *builder*. Provisioning is agnostic of which type of *builder* it is running on.

Ah I see. And I don't suppose it's realistic to terminate the HTTP server when the builder has completed, because in the first provisioner may still be waiting for the VM's building phase to terminate.

Thanks for the explanation.
