### ISSUE TITLE
Should an "inline" shell provisioner be run as a script?

### ISSUE THREAD

**Issue by hvindin** [mitchellh/packer#3978]
I'm not sure if this is a bug or not but have recently noticed the behaviour that, when using an inline script as part of a provisioning process the script is actually copied to the /tmp directory on the box and then executed.

eg. 

```
provisioners": [
    {
      "type": "shell",
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -S -E '{{.Path}}'",
      "inline": [ "env echo -e \"[INFO] Starting subscribe-to-redhat-network script\"", "subscription-manager register --username=\"${REDHAT_USERNAME}\" --password=\"${REDHAT_PASSWORD}\" --servicelevel=Self-Support --release=7.1 --auto-attach --name=hpaas-basebox", "subscription-manager repo-override --remove-all",, "subscription-manager repos --disable=\"*beta*\" --disable=\"*atomic*\" --disable=\"*source*\" --disable=\"*debug*\" --disable=\"*eus*\" --disable=\"*openstack*\" --disable=\"*dotnet*\" --disable=\"*rt*\" --disable=\"*rhscl*\" --disable=\"*sjis*\" --disable=\"*rhel-ha*\" --disable=\"*rh-gluster*\" --disable=\"*rhel-rs*\" --disable=\"*v2vwin*\" --disable=\"*rh-common*\" --disable=\"*satellite-tools*\" --disable=\"*rhceph*\" --disable=\"*rhceph*\" --disable=\"*rhn-tools*\" --disable=\"*supplementary*\" --disable=\"*fastrack*\" --enable=\"rhel-7-server-rpms\" --disable=\"*extras*\" --enable=\"rhel-7-server-optional-rpms\"" ],
      "environment_vars": [
        "REDHAT_USERNAME={{ user `redhat_username` }}",
        "REDHAT_PASSWORD={{ user `redhat_password` }}"
      ]
    }
  ],
```

being run against a  base image which has noexec set on a mount that /tmp occupies results in the following:  

```
==> virtualbox-iso: Connected to SSH!  
==> virtualbox-iso: Uploading VirtualBox version info (5.1.6)  
==> virtualbox-iso: Provisioning with shell script: /tmp/packer-shell174734822  
    virtualbox-iso: sudo: unable to execute /tmp/script_362.sh: Permission denied  
==> virtualbox-iso: Unregistering and deleting virtual machine...  
==> virtualbox-iso: Deleting output directory...  
```

If this is the intended behavior  then perhaps there's some documentation that should indicate what the purpose of an "inline" shell provisioner is vs just a regular script.

If required I'm more than happy to post more detailed logs/build json but I suspect that this either is or is not the intended behavior and probably isn't particularly ambiguous.

**Comment by rickard-von-essen** [comment]
This is intended behavior. See [shell provisioner - inline](https://www.packer.io/docs/provisioners/shell.html#inline), to adjust where the file gets uploaded use [remote_path](https://www.packer.io/docs/provisioners/shell.html#remote_path).

**Comment by hvindin** [comment]
I actually noticed that in the documentation not so long after posting this question. The inability to execute scripts from tmp didn't actually end up being a problem as I  just ended up adding an ansible task to my existing playbooks and included a command to run the repos stuff. It just seems counter intuitive to me that the facility exists to upload a script end execute it (logically by having a script locally that is referenced in the build file) and the exact same functionality is duplicated identically (except with minor syntax differences) for an inline script.

It just seemed more logical based on the language used in the build file (admittedly not the actual documentation) that when one specifies something to run "inline" that it would simply be executed over the ssh channel rather than uploaded the same as a regular script then executed.
