### ISSUE TITLE
Disable network card in QEMU builder

### ISSUE THREAD

**Issue by Wenzel** [mitchellh/packer#3987]
Hi !

The [QEMU builder](https://www.packer.io/docs/builders/qemu.html) allows to specify the network card device to be used during the build with the `net_device` key.

```
 The driver to use for the network interface. Allowed values "ne2k_pci", "i82551", "i82557b", "i82559er", "rtl8139", "e1000", "pcnet", "virtio", "virtio-net", "virtio-net-pci", "usb-net", "i82559a", "i82559b", "i82559c", "i82550", "i82562", "i82557a", "i82557c", "i82801", "vmxnet3", "i82558a" or "i82558b". The Qemu builder uses "virtio-net" by default.
```

I would like to disable the network interface on my build.
Would it be possible to set the `net_device` to `none` to disable the network card ?

Thanks !

**Comment by mwhooker** [comment]
This isn't something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
