### ISSUE TITLE
[Feature Request] Include Non-Cloud Packer Configuration Example

### ISSUE THREAD

**Issue by kkirsche** [mitchellh/packer#3991]
I would like to request a feature / inclusion in the git repository. Specifically, I would like to request that the repository include a single (at a minimum) or multiple non-cloud examples for how to use Packer. Sadly, the website example only includes an AWS configuration example and the repository an Azure configuration. Following both of these, it hasn't actually shown me or gotten me any closer to successfully building a VirtualBox, VMWare Fusion or Parallels machine.

Due to the differences that (appear to) exist between the cloud and local uses of Packer, I would like to ask if it would be possible to add a virtual machine configuration example to either the website or the repository to assist users like me who haven't been able to get anything working via the available documentation.

Thanks for your consideration of this feature

**Comment by mwhooker** [comment]
Would the basic example on the virtualbox documentation help? https://www.packer.io/docs/builders/virtualbox-iso.html

or do you more want a complete file with different provisioners?

**Comment by kkirsche** [comment]
Sadly I wasn't able to get much farther with that documentation which I had read through. For me, I struggled with putting it in the context of a larger configuration document. As such, I would prefer a more complete file if that was possible, as that would help me better see how it fits in the configuration file as a whole.

**Comment by rickard-von-essen** [comment]
@kkirsche For some great example see https://github.com/chef/bento

**Comment by kkirsche** [comment]
Thanks, @rickard-von-essen — those are certainly a lot of great examples to start building upon. Thank you!

**Comment by mwhooker** [comment]
see #4550
