### ISSUE TITLE
Problem executing reboot in shell provisioner

### ISSUE THREAD

**Issue by mawatech** [mitchellh/packer#4006]
- Packer v0.11.0.dev
- Ubuntu 16.10
- [log for the master version](https://gist.github.com/mawatech/40b25d5a53dc32ea2d73070a72c1132c)
- [log with commit 5ab19ea469d390da85ed328889cc2e708072f24c reverted](https://gist.github.com/mawatech/837df364828a8b761aa78b85507cb095)
- [tar.gz with all scripts needed](https://github.com/mitchellh/packer/files/529044/packer_ssh.tar.gz)

With the latest master version of packer, the build fails if I trigger a reboot in the shell provisioner. This happens since the merge of #3966 

The reboot script is very simple

```
#!/bin/sh -eux

/sbin/shutdown -r now

sleep 60
```

Running the command

`packer build -only=virtualbox-iso centos68.json`

with the latest master versions results into the following error after executing the reboot script:
```
2016/10/14 10:28:17 packer: 2016/10/14 10:28:17 Remote command exited without exit status or exit signal.
2016/10/14 10:28:17 packer: 2016/10/14 10:28:17 [INFO] RPC endpoint: Communicator ended with: -1
```

It's working if i revert commit 5ab19ea469d390da85ed328889cc2e708072f24c
```
2016/10/14 10:43:28 packer: 2016/10/14 10:43:28 [INFO] RPC endpoint: Communicator ended with: 0
```

**Comment by rickard-von-essen** [comment]
Oh! Thanks for reporting this. This is hairy. In 5ab19ea we fixed that getting disconnected was treated as success, which it should in your case. 

@mwhooker I guess that we have to either introduce a option to regard -1 as OK in `shelll` provisioner or create a unix-reboot / shutdown provisioner.

**Comment by rickard-von-essen** [comment]
@mawatech what happens if you drop the `sleep 60`?

**Comment by mawatech** [comment]
It also fails, but at the next script. So the reboot script has exit 0, but then the next script immediately runs but is killed as soon as the ssh daemon terminates.

[new logs without sleep](https://gist.github.com/mawatech/866f3a5adebdce1d0976cf7f9ae07675)

**Comment by rickard-von-essen** [comment]
You can add `"pause_before": "10s"` to the next script.
See https://www.packer.io/docs/templates/provisioners.html

**Comment by mawatech** [comment]
OK, if I add the pause it works. However, I'm using the bento templates, so to fix it i need to split the script arrays :(

Before:

```
    {
      "destination": "/tmp/bento-metadata.json",
      "source": "{{user `metadata`}}",
      "type": "file"
    },
    {
      "environment_vars": [
        "HOME_DIR=/home/vagrant",
        "http_proxy={{user `http_proxy`}}",
        "https_proxy={{user `https_proxy`}}",
        "no_proxy={{user `no_proxy`}}"
      ],
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -S -E sh -eux '{{.Path}}'",
      "scripts": [
        "scripts/common/metadata.sh",
        "scripts/common/sshd.sh",
        "scripts/centos/networking.sh",
        "scripts/common/vagrant.sh",
        "scripts/common/reboot.sh",
        "scripts/common/virtualbox.sh",
        "scripts/centos/cleanup.sh",
        "scripts/common/minimize.sh"
      ],
      "type": "shell"
    }
  
```
After:
```
{
      "destination": "/tmp/bento-metadata.json",
      "source": "{{user `metadata`}}",
      "type": "file"
    },
    {
      "environment_vars": [
        "HOME_DIR=/home/vagrant",
        "http_proxy={{user `http_proxy`}}",
        "https_proxy={{user `https_proxy`}}",
        "no_proxy={{user `no_proxy`}}"
      ],
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -S -E sh -eux '{{.Path}}'",
      "scripts": [
        "scripts/common/metadata.sh",
        "scripts/common/sshd.sh",
        "scripts/centos/networking.sh",
        "scripts/common/vagrant.sh",
        "scripts/common/reboot.sh"
      ],
      "type": "shell"
    },
    {
       "environment_vars": [
        "HOME_DIR=/home/vagrant",
        "http_proxy={{user `http_proxy`}}",
        "https_proxy={{user `https_proxy`}}",
        "no_proxy={{user `no_proxy`}}"
      ],
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -S -E sh -eux '{{.Path}}'",
      "scripts": [
        "scripts/common/virtualbox.sh",
        "scripts/centos/cleanup.sh",
        "scripts/common/minimize.sh"
      ],
      "type": "shell",
      "pause_before": "10s"
    }

```
Isn't it possible to set the "pause_before" and packer waits before every script in the array?

**Comment by mwhooker** [comment]
I'm taking another look at https://github.com/mitchellh/packer/issues/3920

maybe this behavior was intended, and it wasn't a bug to begin with?

It looks like in the above bug, the ssh connection was dropping when he ran yum update. That disconnected the communicator, which continued right along to the next one instead of failing the whole build.

I wonder if the correct solution would have been to not upgrade sshd.

**Comment by cbednarski** [comment]
> I wonder if the correct solution would have been to not upgrade sshd.
This is likely to happen any time you update system packages, or especially with every flavor-of-the-month openssl vulnerability. However, it sounds like this problem will occur whenever you invoke a system shutdown or restart. This will be annoying to work around in every packer template.

IMO we should try to avoid making a change that will cause previously working templates to break in mysterious ways. For instance, maybe we can make an explicit option `fail_on_disconnect`.

**Comment by cbednarski** [comment]
We could also model this as `expect_disconnect`, which I think is probably more semantically correct, but the BC path with `packer fix` is not quite a smooth.

**Comment by mwhooker** [comment]
I was thinking `expect_disconnect` would best go in `shell.Config`, since you might want to control the behavior per step, but I don't immediately see an easy way to communicate that to the ssh communicator. It might need to be a part of `ssh.Config`

**Comment by rickard-von-essen** [comment]
> This is likely to happen any time you update system packages

`service sshd restart` _should_ not drop connections.

> IMO we should try to avoid making a change that will cause previously working templates to break in mysterious ways. 

This doesn't have to break in _"mysterious ways"_ we could print a very detailed message telling the user exactly what to do if this disconnect was expected, but sure it would break some, maybe a lot currently working templates.

**Comment by trodemaster** [comment]
I'm seeing some strange errors on shutdown of linux builds with the master branch. Seems like this issue may be affecting shutdown command with the ssh communicator also. 

https://gist.github.com/trodemaster/5bc3db680622b32fb38cba3eeba6a7dd

**Comment by rickard-von-essen** [comment]
@trodemaster yes definitely impacts `shutdown_command` if you use ssh.

**Comment by mawatech** [comment]
thx, it works!

**Comment by confiq** [comment]
amm... what works? 
I'm having same error

**Comment by rickard-von-essen** [comment]
@confiq use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) to get help with usage and troubleshooting. 

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
