### ISSUE TITLE
azure-setup.sh no longer works

### ISSUE THREAD

**Issue by nneul** [mitchellh/packer#4007]
The azure setup script for authorizing has multiple issues. 

The attempt to set up service princpal fails due to command line arguments that don't exist (the two URL arguments). 

If you remove those in the script, it fails later on:

info:    Executing command storage account create
- Checking availability of the storage account name  
- Creating storage account  
  info:    storage account create command OK
  ==> Creating service principal
  ==> Creating permissions
  info:    Executing command role assignment create
- Finding role with specified name  
- Creating role assignment  
  error:   Principal xxxxxxxxxxxxxxxxxxxxxx does not exist in the directory xxxxxxxxxxxxxxxx.
  error:   Error information has been recorded to /users/nneul/.azure/azure.err
  error:   role assignment create command failed

I haven't dug in further at this point - going through the manual setup now.

**Comment by nneul** [comment]
From looking at the manual steps - looks like this:

    azure_object_id=$(azure ad sp create -n $meta_name --home-page http://$meta_name --identifier-uris http://$meta_name/example -p $azure_client_secret --json | jq -r .objectId)

Should be a call to "azure ad app create" with those same args, and then a followup call to "azure ad sp create" with the applicationid

**Comment by boumenot** [comment]
I'll take a look.  Support for this script has bee driven by contributions from the community, and we had a recent round of cleanups to address some issues.  The last changes dealt with _interface_ changes to the CLI.

What version of the CLI are you using?

**Comment by nneul** [comment]
nneul@skyhawk:~$ azure --version
0.10.5 (node: 4.2.6)

**Comment by nneul** [comment]
Also with 0.10.6:

```
nneul@skyhawk:~$ azure ad sp create --help
help:    Create Active Directory service principal.
help:    
help:    Usage: ad sp create [options]
help:    
help:    Options:
help:      -h, --help                          output usage information
help:      -v, --verbose                       use verbose output
help:      -vv                                 more verbose with debug output
help:      --json                              use json output
help:      -a --applicationId <applicationId>  The application Id for which service principal needs to be created. If this is provided then everything else will be ignored. 
help:      When the applicationId is provided it means that the application was already created and it needs to be used to create the service principal.
help:      -n --name <name>                    the display name for the application
help:      -p --password <password>            the value for the password credential associated with the application that will be valid for one year by default
help:      --cert-value <cert-value>           the value of the "asymmetric" credential type. It represents the base 64 encoded certificate
help:      --start-date <start-date>           the start date after which password or key would be valid. Default value is current time
help:      --end-date <end-date>               the end date till which password or key is valid. Default value is one year after current time
help:    
help:    Current Mode: arm (Azure Resource Management)


nneul@skyhawk:~$ azure ad app create --help
help:    Creates a new Active Directory application
help:    
help:    Usage: ad app create [options] <name> <home-page> <identifier-uris>
help:    
help:    Options:
help:      -h, --help                              output usage information
help:      -v, --verbose                           use verbose output
help:      -vv                                     more verbose with debug output
help:      --json                                  use json output
help:      -n --name <name>                        the display name for the application
help:      -m --home-page <home-page>              the URL to the application homepage
help:      -i --identifier-uris <identifier-uris>  the comma-delimitied URIs that identify the application
help:      -l --available <available>              the value specifying whether the application is a single tenant or a multi-tenant. "true" if the application will be available to other tenants, "false" if its a single tenant application. Default is false.
help:      -r --reply-urls <reply-urls>            the comma-delimitied application reply urls
help:      -p --password <password>                the value for the password credential associated with the application that will be valid for one year by default
help:      --cert-value <cert-value>               the value of the "asymmetric" credential type. It represents the base 64 encoded certificate.
help:      --start-date <start-date>               the start date after which password or key would be valid. Default value is current time
help:      --end-date <end-date>                   the end date till which password or key is valid. Default value is one year after current time
help:    
help:    Current Mode: arm (Azure Resource Management)

```

**Comment by tamsky** [comment]
> The attempt to set up service princpal fails due to command line arguments that don't exist (the two URL arguments).
> If you remove those in the script, it fails later on:

I was able to remove them from the script and subsequently have it succeed to completion.

```
diff -r e8dc6ccc9835 contrib/azure-setup.sh
--- a/contrib/azure-setup.sh    Sun Oct 23 15:39:47 2016 +0200
+++ b/contrib/azure-setup.sh    Sun Oct 23 20:53:51 2016 -0700
@@ -147,7 +147,7 @@
 
 createServicePrinciple() {
        echo "==> Creating service principal"
-       azure_object_id=$(azure ad sp create -n $meta_name --home-page http://$meta_name --identifier-uris http://$meta_name/example -p $azure_client_secret --json | jq -r .objectId)
+       azure_object_id=$(azure ad sp create -n $meta_name -p $azure_client_secret --json | jq -r .objectId)
        azure_client_id=$(azure ad app show -c $meta_name --json | jq -r .[0].appId)
        if [ $? -ne 0 ]; then
                echo "Error creating service principal: $azure_client_id"
```

I did figure out that I needed to `azure provider register Microsoft.Storage` at some earlier error-point reached while running the unmodified script.

**Comment by mwhooker** [comment]
there have been a number of issues about this script (most relevantly #4122)

It seems as if azure keeps changing their API.

We'll try to get this sorted soon.

**Comment by bosconi** [comment]
WORKAROUND BELOW...

As of the latest tool versions today:

```
Terraform v0.8.5
Azure Tool version 0.10.8
```

I consistently get this error:

```
...
==> Creating application
==> Creating service principal
==> Creating permissions
info:    Executing command role assignment create
+ Finding role with specified name
+ Creating role assignment
error:   Principal **************** does not exist in the directory *****************.
error:   Error information has been recorded to /Users/jon/.azure/azure.err
error:   role assignment create command failed
```

But if I've inserted an echo of the failing command:

https://github.com/mitchellh/packer/blob/master/contrib/azure-setup.sh#L182

right before it in the script, and wait some time after the error occurs (I waited a few hours, so I don't know the lower bound on the time to wait) then re-run the echo'd command, it completes successfully.

So this is a workaround for now, and points to this most likely being a timing issue. Perhaps a short sleep before this command would be sufficient to make it succeed? Or better, another command should be inserted in a polling loop, to ensure that the previous step has completed before proceeding?

**Comment by bosconi** [comment]
I came to this issue from here: https://blogs.msdn.microsoft.com/eugene/2016/11/03/creating-azure-resources-with-terraform/ ,preparing to bring up an Ubuntu instance on Azure via Terraform. Client environment is:

```
Mac OS 10.11.6
Terraform v0.8.5
Azure Tool version 0.10.8
jq 1.5.2
```

Steps performed, as per the blog post:

```
brew install jq
brew install node
npm install -g azure-cli
<get script from https://github.com/mitchellh/packer/blob/master/contrib/azure-setup.sh>
<edit script to add echo as described above - not in blog post>
<run script, authenticate with an existing Azure account and subscription>
```

Packer not involved.

**Comment by bosconi** [comment]
Just came across someone apparently solving the same problem (but in PowerShell). Line 31 of:

https://gist.github.com/bobalob/1caea3870beb387bdc4e842074f827e7

waits 15 seconds between creating the service principal and performing the role assignment.

Found from: https://superautomation.blogspot.co.uk/2016/11/terraform-with-azure-resource-manager.html

**Comment by cbednarski** [comment]
Hey folks, a few thoughts here:

1. `sleep`s do help because Azure sometimes takes a few seconds to do something. We may need to sprinkle a few more in.
2. Since this is node.js we can do a local npm install of a specific version of the Azure CLI to guard against CLI changes, but this may eventually fall behind and become incompatible with the API.

@boumenot Do you have any ideas how we can stabilize this? E.g. would it help if we targeted the API instead of the CLI, or are these things in a move-fast-and-break-things type of dev cycle?

**Comment by boumenot** [comment]
This feedback has been delivered to the XPlat CLI team before.  Users consume the XPlat CLI in their scripts, and changing the command set, options, or arguments will potentially break users.

IMHO this script needs to be re-written to target the API.

**Comment by chrrrles** [comment]
This script works for me when I increase the sleep timeouts between the create* functions:
```
223     createResourceGroup
224     sleep 20
225     createStorageAccount
226     sleep 20
227     createApplication
228     sleep 20
229     createServicePrincipal
230     sleep  20
231     createPermissions
```

Saw this alluded to in other azure/powershell issues with error messsages similar to those reported by @nneul
