### ISSUE TITLE
OutOfMemoryException with WinRM on 2008R2

### ISSUE THREAD

**Issue by matt-richardson** [mitchellh/packer#4016]
I am facing an issue using WinRM against 2008R2 on AWS.

It manifests in slightly different ways, but it nearly always shows a `System.OutOfMemoryException`. I have not been able to get a successful build.

Nearly everything I read says that I should set `MaxMemoryPerShellMB` to a higher number, but I am already setting this to 3GB.

I am using identical scripts for Win2012 and Win2012R2 and they work fine.

- Packer version from `packer version`
`0.10.2.dev (42144640658ded0e55be62984642750ffc4978db+CHANGES)`. (This is a custom version, as I need the fix from https://github.com/mitchellh/packer/issues/3866, and its not in a released version as yet).

- Host platform
macOS Sierra 10.12

- Debug log output from `PACKER_LOG=1 packer build template.json`:
https://gist.github.com/matt-richardson/3c15465952ec67972c4ae655c9d71766

- The _simplest example template and scripts_ needed to reproduce the bug:
https://gist.github.com/matt-richardson/6bdba1dd172117500c0a275548579499

I doubt its relevant, but the machine is being launched inside a VPC.

Powershell version, in case its relevant:
```
PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.2.9200.16481
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

Let me know if i can provide any more information.

Thanks in advance.

**Comment by mwhooker** [comment]
hmm, the only thing I can think of is that the `c3.large` instance type is a bit odd. Those types have more cpu but often less memory. What if you tried this with an m3.large?

**Comment by cbednarski** [comment]
Some ideas:

1. There is a bug in WinRM / Packer's use of WinRM that causes a memory leak. Are Windows updates installed on the base AMI already? It looks like 2008 is EOL so maybe there is a latent bug there that has been fixed in 2012.
2. PowerShell is buffering a lot of data into memory for some reason. E.g. output logs, downloaded binaries for your install process, etc. You can test this by running the provisioner over RDP and see if you get the same failure.
3. You're running a 32-bit version of 2008 and running out of virtual memory.

If this works on 2012, though, I'm inclined to think this is an OS / provisioning problem and not really a packer issue.

**Comment by matt-richardson** [comment]
Thanks for the input, @mwhooker & @cbednarski.

Turns out I was hitting `"Out of memory" error on a computer that has a customized MaxMemoryPerShellMB quota set and has WMF 3.0 installed` and needed to install the [KB2842230 hotfix](https://support.microsoft.com/en-us/kb/2842230).

From the KB article (copying here so that its searchable):

```
Consider the following scenario:
You increase the MaxMemoryPerShellMB quota (for example, you increase the quota to 1 gigabyte (GB)) on a computer that has one of the following configurations:
Windows Server 2008 Service Pack 2 (SP2) and Windows Management Framework (WMF) 3.0 are installed.
Windows 7 Service Pack 1 (SP1) and WMF 3.0 are installed.
Windows Server 2008 R2 SP1 and WMF 3.0 are installed.
Windows 8 is installed.
Windows Server 2012 is installed.
You execute a Windows Remote Shell (WinRS) command that requires lots of memory, such as 500 megabytes (MB) of memory.
In this scenario, the command fails, and you receive an "out of memory" error.
```

**Comment by mwhooker** [comment]
Thanks for following up @matt-richardson!
