### ISSUE TITLE
packer ipv6 qemu-kvm problem

### ISSUE THREAD

**Issue by zetan503** [mitchellh/packer#4020]
Packer v0.10.2
Platform: Oracle Linux 7.1 qemu-kvm
https://gist.github.com/zetan503/b6d700f05d1438e8e90bfe2cde1ad221

My hypervisor is ipv6 only.
When packer starts qemu it gives -vnc 0.0.0.0:36

2016/10/17 21:52:36 packer: 2016/10/17 21:52:36 Executing /usr/libexec/qemu-kvm: []string{"-m", "512M", "-drive", "file=/vm/packer-01/packer-01,if=virtio,cache=none", "-device", "virtio-net,netdev=user.0", "-cdrom", "/home/XXXX/builder/packer_cache/3d5ddd87ab684a4105f857aa1f068f8cd276975a0c4dfdccb7cc5f454d15ea9f.iso", "-boot", "once=d", "-netdev", "user,id=user.0,hostfwd=tcp::2460-:22", **"-vnc", "0.0.0.0:36"**, "-name", "packer-01", "-machine", "type=pc,accel=kvm"}
2016/10/17 21:52:36 packer: 2016/10/17 21:52:36 Started Qemu. Pid: 35678
2016/10/17 21:52:36 packer: 2016/10/17 21:52:36 Qemu stderr: qemu-kvm: Failed to start VNC server on `0.0.0.0:36': address resolution failed for 0.0.0.0:5936: Address family for hostname not supported
2016/10/17 21:52:36 ui error: ==> qemu: Error launching VM: Qemu failed to start. Please run with logs to get more info.

Please help me figure out how to make packer start VM on ipv6 localhost ::1

{
  "builders": [{
    "type": "qemu",
    "accelerator": "kvm",
    "machine_type": "pc",
    "qemu_binary": "/usr/libexec/qemu-kvm",
    "iso_checksum_type": "md5",
    "iso_checksum": "5728ef4b431d28a2d4ad62dbdf5bf36d",
    "iso_url": "http:/XXXX/sysrepo/OL_7_1_V74844-01.iso",
    "output_directory": "/vm/packer-01",
    "ssh_username": "vagrant",
    "ssh_password": "vagrant",
    "vm_name": "packer-01",
    "disk_size": "102400",
    "format": "qcow2",
    "disk_interface": "virtio",
    "disk_cache": "none",
    "http_directory": "httpdir",
    "net_device": "virtio-net",
    "disk_interface": "virtio",
    "shutdown_command": "echo 'vagrant' | sudo -S shutdown -P now",
    "http_directory": "httpdir",
    "boot_wait": "3s",
    "qemuargs": [ 
    ],
    "boot_command": [
      "<wait><esc><esc>",
      "linux ks=http://{{.HTTPIP}}:{{.HTTPPort}}/kickstart.cfg<enter><wait>"
    ]
  }],
  "post-processors": [{
    "type": "vagrant",
    "output": "./oraclelinux-7.1-x86_64.box",
    "vagrantfile_template": "./Vagrantfile"
  
  }]

}

**Comment by mwhooker** [comment]
It looks like you can override the vnc IP by setting `vnc_bind_address` https://github.com/mitchellh/packer/blob/6b167c508f8a5210a72ddfcb0c89e867c2a71f08/builder/qemu/builder.go#L107

is this helpful?

**Comment by zetan503** [comment]
Thank you. Where would I set it?

**Comment by zetan503** [comment]
2016/10/17 22:56:19 Build 'qemu' prepare failure: 1 error(s) occurred:

* unknown configuration key: "vnc_bind_address"
2016/10/17 22:56:19 ui error: 1 error(s) occurred:

**Comment by mwhooker** [comment]
hmm, this needs to be better documented. It looks like you set it in the qemu builder

```json
{
    "builders": [
        {
            "accelerator": "kvm",
            "boot_command": [
                "",
                "linux ks=http://{{.HTTPIP}}:{{.HTTPPort}}/kickstart.cfg"
            ],
            "boot_wait": "3s",
            "disk_cache": "none",
            "disk_interface": "virtio",
            "disk_size": "102400",
            "format": "qcow2",
            "http_directory": "httpdir",
            "iso_checksum": "5728ef4b431d28a2d4ad62dbdf5bf36d",
            "iso_checksum_type": "md5",
            "iso_url": "http:/XXXX/sysrepo/OL_7_1_V74844-01.iso",
            "machine_type": "pc",
            "net_device": "virtio-net",
            "output_directory": "/vm/packer-01",
            "qemu_binary": "/usr/libexec/qemu-kvm",
            "qemuargs": [],
            "shutdown_command": "echo 'vagrant' | sudo -S shutdown -P now",
            "ssh_password": "vagrant",
            "ssh_username": "vagrant",
            "type": "qemu",
            "vm_name": "packer-01",
            "vnc_bind_address": "VNC_BIND_ADDRESS"
        }
    ],
    "post-processors": [
        {
            "output": "./oraclelinux-7.1-x86_64.box",
            "type": "vagrant",
            "vagrantfile_template": "./Vagrantfile"
        }
    ]
}
```

Does that cause an error?

**Comment by mwhooker** [comment]
Oh, you know what, I don't think this is in the latest packer release. If you feel comfortable building from source, that should work. Otherwise, wait for 0.11 which should be released this week.
