### ISSUE TITLE
No more logs after deleting log file while packer runs

### ISSUE THREAD

**Issue by sleighsoft** [mitchellh/packer#4025]
Packer logs a lot of information, sometimes I want to clear the log file and therefore I just delete it under the assumption that the running logger will recreate the file again which it does not do.

- Packer version 0.10.2
- Host platform CentOS

**Comment by mwhooker** [comment]
Can you show us how you run packer and where the log file is that you delete?

It looks like if you specify a `PACKER_LOG_PATH`, it recreates the log file every time: https://github.com/mitchellh/packer/blob/v0.10.2/log.go#L21

and if you don't specify that env var, it writes to a temp file which it deletes after every run: https://github.com/mitchellh/packer/blob/v0.10.2/main.go#L40-L57

**Comment by mwhooker** [comment]
Oh, do you mean you delete it while packer is still running?

**Comment by sleighsoft** [comment]
Yes

**Comment by rickard-von-essen** [comment]
Ok, that is how Unix filsystems work. 

Try truncating the logs with:
`echo "" > packer.log`

**Comment by sleighsoft** [comment]
Works for me
