### ISSUE TITLE
ui: scan err: unexpected newline

### ISSUE THREAD

**Issue by veetow** [mitchellh/packer#4029]
This is very minor, but when running with `-debug`, packer prints this error after every pause and subsequent press of the enter key.  Here's an exmample:

```
2016/10/19 13:04:19 ui: ask: ==> vmware-iso: Pausing after run of step 'stepCreateVMX'. Press enter to continue.
==> vmware-iso: Pausing after run of step 'stepCreateVMX'. Press enter to continue.
2016/10/19 13:04:21 ui: scan err: unexpected newline
```
- Packer version: 0.10.2
- Host platform: macOS 10.12

**Comment by dacamp** [comment]
I think the fix is two fold, land mitchellh/multistep/pull/8 and then update vendor.

**Comment by mwhooker** [comment]
Since this is an upstream bug, I'm going to close this since there's nothing we can do about for now. Will be happy to look at a PR once upstream gets merged

**Comment by dacamp** [comment]
Does @mitchellh still maintain the [mitchellh/multistep](/mitchellh/multistep) package? There's been little movement.

**Comment by mwhooker** [comment]
I'd say it's still maintained, but he's very focused on other stuff. I can ping him but can't guarantee any movement.
