### ISSUE TITLE
How to use variable in {{}}

### ISSUE THREAD

**Issue by hanks** [mitchellh/packer#4031]
packer version: 0.10.2

How to use user variable in a function like below:

```
"variables": {
  "magic_reference_date": "2006-01-02 15-04-05+0900"
},
...
"ami_name": "base-ami {{ isotime .magic_reference_date | clean_ami_name }}",
```

And how to format isotime to the local time, for example, {{ isotime }} will be `2016-10-20T05-27-16Z`, but I want to it to be `2016-10-20T14-27-16Z`, plus 9 hours to Japan Time.

Thank you for your time.

**Comment by rickard-von-essen** [comment]
I'm not in front of a computer right now. Did you try:

```json
"ami_name": "base-ami {{ isotime user `magic_reference_date` }} | clean_ami_name }}"
```

ISO time is always UTC, see note in the docs about templates.

**Comment by hanks** [comment]
Thank you for your reply.

yeah, I tried, it does not work, result is `Creating the AMI: base-ami magic_reference_date`, just parse the string itself.

And is there some way, like a function to get current local time format?

**Comment by patrickdappollonio** [comment]
Since those are Go template functions, it should be...

```json
"variables": {
  "magic_reference_date": "2006-01-02 15-04-05+0900"
},
...
"ami_name": "base-ami {{ isotime }} {{ user `magic_reference_date` }}",
```

**Comment by hanks** [comment]
@patrickdappollonio thank you for your reply, but it did not work, the output is below:

```
==> amazon-ebs: Creating the AMI: base-ami.2016-11-18T01-03-16Z.2006-01-02 15-04-05 +0900
==> amazon-ebs: Error creating AMI: InvalidAMIName.Malformed: AMI names must be between 3 and 128 characters long, and may contain letters, numbers, '(', ')', '.', '-', '/' and '_'
==> amazon-ebs: 	status code: 400, request id: 3ba96e67-7e50-4bbb-8488-680231acfd90
```

the `magic_reference_date ` is not used by `isotime` function

**Comment by patrickdappollonio** [comment]
The problem is the value at `magic_reference_date`... You also need to do...

```json
"ami_name": "base-ami.{{ isotime | clean_ami_name }}.{{ user `magic_reference_date` | clean_ami_name }}",

```

**Comment by hanks** [comment]
@patrickdappollonio  yeah, it works, but the result is not what I want, actually I want to use the `magic_reference_date` to format `isotime` result, the sample from document is like:

[https://www.packer.io/docs/templates/configuration-templates.html](https://www.packer.io/docs/templates/configuration-templates.html)

```
isotime = June 7, 7:22:43pm 2014

{{isotime "2006-01-02"}} = 2014-06-07
{{isotime "Mon 1504"}} = Sat 1922
{{isotime "02-Jan-06 03\_04\_05"}} = 07-Jun-2014 07\_22\_43
{{isotime "Hour15Year200603"}} = Hour19Year201407
```

the result of your solution is 

```
==> amazon-ebs: Creating the AMI: base-ami.2016-11-18T01-29-28Z.2006-01-02 15-04-05 -0900
```

the result expected is , with the timezone of Japan time (+0900),

```
==> amazon-ebs: Creating the AMI: base-ami.2016-11-18 10-29-28 
```

**Comment by patrickdappollonio** [comment]
Can you try this?

```json
"ami_name": "base-ami.{{ (isotime | (user `magic_reference_date`)) | clean_ami_name }}",
```

Technically, you can group elements, take the result, and apply it to something else.

**Comment by hanks** [comment]
@patrickdappollonio It works! Thank you for your patient, I also tried `"ami_name": "base-ami.{{ (isotime (user `magic_reference_date`)) | clean_ami_name }}"`, it is ok too.

**Comment by patrickdappollonio** [comment]
Hah, even better. Glad you make it!
