### ISSUE TITLE
$env:PACKER_BUILDER_TYPE error while executing PowerShell provisioners

### ISSUE THREAD

**Issue by kagarlickijd** [mitchellh/packer#4053]
Hi there, 
I use:
Packer 0.11.0
macOS 10.12.1 Beta (16B2553a)
VirtualBox 5.1.8 r111374
Parallels 12.0.2 (41353)

After I'd updated packer from 0.10.2 to 0.11.0 I started to get **$env:PACKER_BUILDER_TYPE** error for all PowerShell scripts, for all builders. 
If I downgrade packer form 0.11.0 to 0.10.2 problem drops out - I've tested it on both my machines.

Here's screenshot with error: [http://prntscr.com/cyeifk](http://prntscr.com/cyeifk)

It's not a blocker, I still can build stuff, but it makes output less readable..

**Comment by rickard-von-essen** [comment]
Thanks for reporting this. This duplicates #4044.
