### ISSUE TITLE
Bug: Build 'vmware-iso' errored: Shutdown command has non-zero exit status.

### ISSUE THREAD

**Issue by cjbirk** [mitchellh/packer#4054]
- Operating system: OS X 10.12
- Packer version: 0.11.0 (from brew)
- Host platform: VMware
- Debug log output: Build 'vmware-iso' errored: Shutdown command has non-zero exit status.
- Packer template used: https://gist.github.com/cjbirk/db1ca4634e22e5acf023948925cf5452
- Steps to replicate: packer build -only vmware-iso rhel7.json
- Expected results: It works
- Actual results: It doesn't
- Error given: Build 'vmware-iso' errored: Shutdown command has non-zero exit status. More info in this gist: https://gist.github.com/cjbirk/6fba8b0899108279204c4462b53ae03c
- Temporary solution: Installed 0.10.2 binary which resolved the issue.

In packer 0.11.0, I tried building a vmware-iso only image for CentOS 7 and RHEL 7 (confirmed not working for both) - this non-zero exit status is all that I got despite the entire run being fine.

When I downgraded to 0.10.2, the run was perfectly fine (besides having to manually kill VMware Fusion): https://gist.github.com/cjbirk/83de0a50d811fbabb689f14876fe77b5

**Comment by trodemaster** [comment]
This showed up right after the 0.11.0 in my testing. It's now fixed in the master branch per https://github.com/mitchellh/packer/pull/4041 I validated that the fix works as expected.

**Comment by cjbirk** [comment]
Thanks @trodemaster

**Comment by rickard-von-essen** [comment]
Duplicates #4034

**Comment by rickard-von-essen** [comment]
It duplicates the issue reported in the https://github.com/mitchellh/packer/pull/4034#issuecomment-255485956 on the PR which introduce this error. And is fixed by #4041

**Comment by geerlingguy** [comment]
Confirmed I'm hitting this too. What's the quickest way to test PR https://github.com/mitchellh/packer/pull/4041 if I have packer installed via `brew`?
