### ISSUE TITLE
[vmware] builder removes esxi vm directory at shutdown

### ISSUE THREAD

**Issue by dantran** [mitchellh/packer#4055]
At shutdown vmware build unregister the VM and also remove its director on ESX

Packer: 0.11.0
Host: SLES12Sp1
ESX:6, but produce esx5.5 compatible image

here is the log

2016/10/24 15:52:55 packer: 2016/10/24 15:52:55 starting remote command: /sbin/shutdown -h -P now
2016/10/24 15:53:45 packer: 2016/10/24 15:53:45 Remote command exited without exit status or exit signal.
2016/10/24 15:53:45 packer: 2016/10/24 15:53:45 opening new ssh session
2016/10/24 15:53:45 packer: 2016/10/24 15:53:45 starting remote command: vim-cmd vmsvc/power.getstate 539
2016/10/24 15:53:45 ui: [1;32m==> vmware-iso: Unregistering virtual machine...[0m
[1;32m==> vmware-iso: Unregistering virtual machine...[0m
2016/10/24 15:53:45 packer: 2016/10/24 15:53:45 opening new ssh session
2016/10/24 15:53:45 packer: 2016/10/24 15:53:45 starting remote command: vim-cmd vmsvc/unregister 539
2016/10/24 15:53:46 packer: 2016/10/24 15:53:46 opening new ssh session
2016/10/24 15:53:46 packer: 2016/10/24 15:53:46 starting remote command: test -e /vmfs/volumes/EIX_703/msm-kickstart
2016/10/24 15:53:46 ui: [1;32m==> vmware-iso: Deleting output directory...[0m
[1;32m==> vmware-iso: Deleting output directory...[0m
2016/10/24 15:53:46 packer: 2016/10/24 15:53:46 opening new ssh session
2016/10/24 15:53:46 packer: 2016/10/24 15:53:46 starting remote command: rm -rf /vmfs/volumes/EIX_703/msm-kickstart
2016/10/24 15:53:46 ui error: [1;31mBuild 'vmware-iso' errored: Shutdown command has non-zero exit status.

Will update the debug log later

**Comment by berney** [comment]
@dantran  I think this is #4006 fixed by #4034, the shutdown command is causing the SSH session to disconnect, which packer used to treat as success but now as failure. Then after if fails it deletes cleans up removing the directory.

**Comment by dantran** [comment]
@berney, I dont see any related fix after 0.11.0

**Comment by berney** [comment]
Good point, IIUC that fix is in v0.11.0.

**Comment by dantran** [comment]
this is a dup of #4054

Note,  I am still stuck at packer 0.8.6 for my vmware-iso OVA build

**Comment by rickard-von-essen** [comment]
@dantran 0.12.0 will be out probably next week or the week after. It would be great if you could build from master and verify that it works in your setting a couple of times the coming weeks to ensure that 0.12.0 will be working for you.

**Comment by dantran** [comment]
I have no luck building packer :-)  wish packer can just deploy snapshots

**Comment by rickard-von-essen** [comment]
Yes we should publish snapshots.
