### ISSUE TITLE
Amazon key pair no longer cleaned up at end of build

### ISSUE THREAD

**Issue by richardowen** [mitchellh/packer#4057]
After upgrading to Packer 0.11.0, the temporary key pair created during an Amazon EBS build is no longer cleaned up at the end of the build. See gist with template and log outputs from v0.10.2 and v0.11.0:

https://gist.github.com/richardowen/74394a8b8dfa6f75d4edfe623c0574b6

In the v0.10.2 log it shows "Deleting temporary keypair..." whereas it doesn't show this (and doesn't do it) in the v0.11.0 log.

Host platform is macOS 10.12.1 but the behaviour is also the same on Ubuntu 16.04.

**Comment by rickard-von-essen** [comment]
Confirmed

**Comment by rickard-von-essen** [comment]
This guard here is wrong
https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_key_pair.go#L98

**Comment by Constantin07** [comment]
On CentOS 7.2 with Packer v0.11.0 - the keys are not cleaned up as well.

**Comment by rickard-von-essen** [comment]
I have a fix for this. Just needs to verify that it doesn't break anything.

**Comment by dacamp** [comment]
Is the user expected to cp/mv the key if the intention is to preserve it?
