### ISSUE TITLE
Shutdown commands sometimes fail on packer 0.11.0

### ISSUE THREAD

**Issue by eschrock** [mitchellh/packer#4066]
I had a nicely working packer configuration and attempted to upgrade from 0.10.1 to 0.11.0. At this point my VMWare builds started failing. I have seen this multiple times and have not yet had a successful build, though I am still testing other builders. I am building CentOS images, and have the following as my shutdown_command:

`      "shutdown_command": "echo '***' | sudo -S shutdown -P now",`

Now, on a working 0.10.1 build, I see this with PACKER_LOG:

```
==> vmware: Gracefully halting virtual machine...
2016/10/26 12:46:21 packer: 2016/10/26 12:46:21 starting remote command: echo '***' | sudo -S shutdown -P now
2016/10/26 12:46:22 packer: 2016/10/26 12:46:22 remote command exited with '0': echo '***' | sudo -S shutdown -P now
```

On a failing 0.11.0 build, I now see this:

```
==> vmware: Gracefully halting virtual machine...
2016/10/26 11:00:13 packer: 2016/10/26 11:00:13 starting remote command: echo '***' | sudo -S shutdown -P now
2016/10/26 11:00:14 packer: 2016/10/26 11:00:14 Remote command exited without exit status or exit signal.
...
2016/10/26 11:00:21 ui error: Build 'vmware' errored: Shutdown command has non-zero exit status.

Stdout: 

Stderr: 
```

Nothing else has changed - switching back and forth between packer binaries fixes the problem. I believe this could be related to the new [expect_disconnect](https://github.com/mitchellh/packer/commit/892d5e82c97a270b2ab3dd7b5e7906c85176f281) option, but I would have expected to still see the same "exited without exit status or exit signal" message even on 0.10.1. Perhaps something changed timing-wise, but it's oddly consistent.

Shutdown commands should be expected to disconnect SSH, since they are bringing down all processes on the system. The new expect_disconnect option appears to only be valid in "shell" context, so I don't know how that can be specified specifically for the shutdown command. Shouldn't it always be expected (or at least possible) to get disconnected while executing a shutdown command?

**Comment by eschrock** [comment]
I have confirmed that the virtualbox build works and the vmware (remote ESX) build fails, so it is not universal. This could be because the ESX server is just a much more powerful machine than my laptop, and is therefore able to hit this race more easily. That being said, it's 100% reproducible that it fails with vmware remote ESX + 0.11.0 and succeeds with any other combination.

**Comment by eschrock** [comment]
I can also confirm that this works properly with 0.10.2 (my previous testing had been with 0.10.1).

**Comment by rickard-von-essen** [comment]
Duplicates #4054
