### ISSUE TITLE
Feature: Allow builders to respond to --on-error=ask responses

### ISSUE THREAD

**Issue by nwalke** [mitchellh/packer#4071]
Feature:
I think it would be interesting to allow builders to have a debug option in the `on-error=ask` confirmation.  Each builder could do various things that make sense for them when the debug option is chosen. 

Use case:
AWS builder errors on some step, not running with debug.  It would be nice if I could respond that I want Packer to save the temporary key-pair so that I can log in and find out what's going on.

**Comment by rickard-von-essen** [comment]
It's a very nice idea. It will require some additional core parts of Packer so it won't be add in the near future.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but isn't something we're targeting for 1.0, so I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
