### ISSUE TITLE
use `clean_ami_name` in variable error

### ISSUE THREAD

**Issue by hanks** [mitchellh/packer#4073]
version: 0.10.2

I want to use `clean_ami_name` name in variable, like:

```
"variables": {
...
"ami_name": "ami-{{ isotime | clean_ami_name }}",
...
}
```

but error below occurs:

`Error initializing core: error interpolating default value for 'ami_name': template: root:1: function "clean_ami_name" not defined`

**Comment by rickard-von-essen** [comment]
Could you provide a minimal template for this.

**Comment by hanks** [comment]
ok, how about this one

```json
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": "",
    "source_ami": "ami-a21529cc",
    "ami_name": "ami-{{ isotime | clean_ami_name }}"
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{ user `aws_access_key` }}",
    "secret_key": "{{ user `aws_secret_key` }}",
    "region": "ap-northeast-1",
    "source_ami": "{{ user `source_ami` }}",
    "instance_type": "m3.medium",
    "ssh_username": "ubuntu",
    "ami_name": "{{ user `ami_name` }}"
  }]
}
```

**Comment by rickard-von-essen** [comment]
Ok then it makes sense. `clean_ami_name` is local function only available in a Amazon builder. If you just move in to the `amazon-ebs` builder block it will work.

**Comment by hanks** [comment]
oh, the function is searched in the builder scope. thanks
