### ISSUE TITLE
AWS AMI Ubuntu Xenial (16.04) HVM instance-store image - grub issue

### ISSUE THREAD

**Issue by Galitskiy** [mitchellh/packer#4077]
Trying create HVM instance-store image on Ubuntu Xenial (16.04) but have issue with grub:
![screen shot 2016-10-27 at 16 11 54](https://cloud.githubusercontent.com/assets/4974260/19768498/5d86af50-9c60-11e6-89f9-e296417215fa.png)

I see that used legacy grub:
https://gist.github.com/Galitskiy/cad6191117c63a5c241186e5faa50d7d

but should be used grub2 for Ubuntu 16.

Not sure that this is packer issue, but please check.

P.S. with instance-ebs there're issues.

packer version: 0.11.0
host: MacOS 10.11.6 64bit

Thanks.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
