### ISSUE TITLE
Tag the latest docker release as 0.11.0 on docker hub

### ISSUE THREAD

**Issue by dustyburwell** [mitchellh/packer#4079]
I'm presently using the `latest` tag version of packer, but I'm not a fan of using latest as it tends to move. Would it be possible to tag the 0.11.0 version of the packer docker image and push the tag to docker hub?

Thanks.

**Comment by mwhooker** [comment]
I agree we need to revisit the way we do docker. fwiw our dockerfile repo is https://github.com/hashicorp/docker-hub-images

**Comment by mwhooker** [comment]
dne

**Comment by mwhooker** [comment]
done. will be sure to push specific versions going forward
