### ISSUE TITLE
shutdown commands fails on vmware/redhat 7.2 when using packer 0.11

### ISSUE THREAD

**Issue by eelcomaljaars** [mitchellh/packer#4087]
- packer version 0.11
- MacOS 10.12
- VMWare 8.5.x
- https://gist.github.com/eelcomaljaars/b411e760e81feff1b994501889cb0b36

-problem does not occur when using packer 0.10
- problem does not occur with packer 0.11 combined with RHEL6 as target OS for the build 

- problem also seen with a another setup using packer 0.11 and Ubuntu 16.04 (but no problem with 14.04 / 12.04 in same setup). So _maybe_ linked to systemctl? 

- also, I tried nummerou 'shutdown' commands, using systemctl directly, using init, using the shutdown command, appending  '; exit 0' to the shutdown command, but all to no avail.

**Comment by eelcomaljaars** [comment]
This probably is a duplicate of Bug: Build 'vmware-iso' errored: Shutdown command has non-zero exit status. #4054, I took a couple of days to report it :-/

**Comment by rickard-von-essen** [comment]
Closing this as a dup of #4054. v0.12.0 is planned for 15 Nov with a fix for this.
