### ISSUE TITLE
[Bug] Packer VMWare Build doesn't support DHCP in "bridge" Mode

### ISSUE THREAD

**Issue by panpan0000** [mitchellh/packer#4091]
- Packer version :0.10.0
- Host platform:  Ubuntu 14.04.2 
- VMWare WorkStation: VMware Workstation 12.1.1 build-3770994

- Summary:  

  in "vmx_data", if I specific "ethernet0.networkName". then the NIC will always be "bridged" mode in the .vmx file created by packer in output folder, regardless if I specific  "ethernet0.connectiontype": "nat" as below example template. (this is problem 1)
 moreover, if .vmx is "bridged" mode, then the Ubuntu 14.04.4 ISO installation will fail, due to unable to DHCP for the NIC  ( I don't have standalone DHCP service, but VMWare Workstation will provide DHCP)
  I looked at the packer.log, find packer always search VM IP from /etc/vmware/**vmnet8**/dhcpd/dhcpd.leases ( hardcoded in code) , but vmnet8 is only used for "NAT" mode, VMWare's vmnet0 is for "bridged" mode. (this is problem 2)

-Example Template.json:
```
"vmx_data": {
   "memsize": "1024",
   "numvcpus": "2",
   "cpuid.coresPerSocket": "1",

   "ethernet0.virtualDev": "e1000",
   "ethernet0.networkName": "ADMIN",
   "ethernet0.present": "TRUE",
   "ethernet0.connectiontype": "nat",
   "ethernet0.pcislotnumber": "32",

   "ethernet1.virtualDev": "e1000",
   "ethernet1.networkName": "CONTROL",
   "ethernet1.connectiontype": "nat",
   "ethernet1.present": "TRUE",
   "ethernet1.pcislotnumber": "33"
   },
```

- Packer Log:
```
packer: 2016/10/31 21:21:29 Special code '<enter>' found, replacing with: 65293
packer: 2016/10/31 21:21:29 Special code '<wait>' found, sleeping one second
packer: 2016/10/31 21:21:30 [INFO] Waiting for SSH, up to timeout: 2h46m40s
ui: ==> vmware-iso: Waiting for SSH to become available...
packer: 2016/10/31 21:21:30 Lookup up IP information...
packer: 2016/10/31 21:21:30 DHCP leases path: /etc/vmware/vmnet8/dhcpd/dhcpd.leases
packer: 2016/10/31 21:21:30 Detected IP: 192.168.90.139
packer: 2016/10/31 21:21:33 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 192.168.90.139:22: getsockopt: no route to host
packer: 2016/10/31 21:21:38 Lookup up IP information...
packer: 2016/10/31 21:21:38 DHCP leases path: /etc/vmware/vmnet8/dhcpd/dhcpd.leases
```

- My VMWare DHCP services (seems vmnet0 is not there, but packer code will not look for it anyway)
```
# ps -lef|grep vmnet|grep dhcp
/usr/bin/vmnet-dhcpd -s 6 -cf /etc/vmware/vmnet1/dhcpd/dhcpd.conf -lf /etc/vmware/vmnet1/dhcpd/dhcpd.leases -pf /var/run/vmnet-dhcpd-vmnet1.pid vmnet1
/usr/bin/vmnet-dhcpd -s 6 -cf /etc/vmware/vmnet8/dhcpd/dhcpd.conf -lf /etc/vmware/vmnet8/dhcpd/dhcpd.leases -pf /var/run/vmnet-dhcpd-vmnet8.pid vmnet8
```

**Comment by rickard-von-essen** [comment]
If you run a VM's nic in bridged mode you will get a lease from the dhcp server on your lan and Packer won't know which IP it has. 

I suggest you use the default network setup when building the image and then change it in `vmx_data_post` to whatever you want it to be when the image is used.

If you still think this is a bug please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by panpan0000** [comment]
Hi, @rickard-von-essen , thanks for pay attention.
I'm fine if Packer can't know IP if VM in bridge mode.

But for my problem 1:
in "vmx_data", if I specific ```"ethernet0.networkName"```. then the NIC will always be "bridged" mode in the .vmx file created by packer in output folder, regardless even if I specific ```"ethernet0.connectiontype": "nat"``` as my example template. 

Do you think this is a problem ?

last , why I specificed two NICs in ```vmx_data``` instead of ```vmx_data_post``` , because my provisioner scripts requires two NICs.

**Comment by rickard-von-essen** [comment]
I think it's best if you send ask for help on the [mailing list](https://groups.google.com/group/packer-tool) for that.

And supply:
- Debug log output from PACKER_LOG=1 `packer build template.json`. 
- The simplest example template and scripts that you want help with.

See https://www.packer.io/community/
