### ISSUE TITLE
FreeBSD on GCP hangs on "Startup script not finished yet. Waiting..."

### ISSUE THREAD

**Issue by jevonearth** [mitchellh/packer#4095]
Packer: `Packer v0.11.0`
Host platform: arch linux 
provider: googlecompute
OS on provider: FreeBSD 11.0

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/jevonearth/af20f0fd048c7aaa503d9017d69c236d
- Example template
  https://gist.github.com/jevonearth/77b31bdeee0285c8a6d6c120d2f2e9ab

The example template does not use a "startup_script_file" or "metadata"."startup-script", as suggested to in #3829  but I did try that, and got the same result.

Thank you,

Possibly related to #3829 
CC: @rickard-von-essen and @crunk1

**Comment by crunk1** [comment]
FreeBSD isn't officially supported by GCE at this time: https://cloud.google.com/compute/docs/images. So that is probably part of the issue. 

The way I have the googlecompute builder, for now, is that it starts up a VM with a wrapper for user-provided startup scripts (see https://github.com/mitchellh/packer/blob/master/builder/googlecompute/startup.go and https://cloud.google.com/compute/docs/startupscript) which will inform Packer when the user-provided script (or lack thereof) finishes. It informs Packer via a metadata variable (https://github.com/mitchellh/packer/blob/master/builder/googlecompute/startup.go#L55). So Packer waits for this variable, but if an unofficial image such as BSD doesn't have startup script support, that variable will never be set...

**Comment by crunk1** [comment]
That being said, it is possible to skip the wait-for-instance-startup step entirely.

**Comment by jevonearth** [comment]
@crunk1 thank you for looking into this!

I have heard rumor that FreeBSD is working with GCP to get the official images (made by FreeBSD) promoted to official GCE builds. I think that FreeBSD images has implemented everything that is needed. FWIW. :)

Anyway, I think I may see the problem, your script uses `#!/bin/bash`. FreeBSD does not include bash in the base system, but it _is_ installed on the FreeBSD images. But it lives in `/usr/local/bin/bash`.

You could consider to use `#!/usr/bin/env bash` or use `/bin/sh` which I think is a lower common denominator, as AFAIK all Linux and BSD distributions ship with `/bin/sh`

**Comment by crunk1** [comment]
Still, to be more compatible with other image flavors, which may not have startup-script support, I think I will conditionally exclude the wait step.

**Comment by crunk1** [comment]
The startup script wrapper also requires that gcloud and gsutil be installed on the VM.

**Comment by jevonearth** [comment]
Yep, all gcloud, gsutil, and curl are installed. The FreeBSD people who built the images understood that these are needed. bash is there also, just not where you are expecting it. :)

If you want me to test a build, just tell me what branch, commit, and I'll be delighted to test for you.

-Jev

**Comment by crunk1** [comment]
That would be great! https://github.com/crunk1/packer, master, HEAD.

**Comment by jevonearth** [comment]
Looks better! I have to leave office now, will test more later this evening, or tomorrow morning. Thank you.

**Comment by jevonearth** [comment]
Upon testing further, I find that my simple test case now works, but my bigger test case, that uses some ansible playbooks for provisioning still hits the "Waiting..." condition.

I can trim down my packer config with the ansible configuration if you like. Below is a snippet of logs with `PACKER_LOG=1 ` set. Let me know what I can do to best assist further.

```
2016/11/03 06:29:50 ui:     foo-base-gcp-freebsd11: 127.0.0.1                  : ok=24   changed=21   unreachable=0  failed=0
    foo-base-gcp-freebsd11: 127.0.0.1                  : ok=24   changed=21   unreachable=0    failed=0
2016/11/03 06:29:50 ui:     foo-base-gcp-freebsd11:
    foo-base-gcp-freebsd11:
2016/11/03 06:29:50 packer: 2016/11/03 06:29:50 [INFO] RPC endpoint: Communicator ended with: 0
2016/11/03 06:29:50 [INFO] RPC client: Communicator ended with: 0
2016/11/03 06:29:50 [INFO] 0 bytes written for 'stderr'
2016/11/03 06:29:50 [INFO] RPC endpoint: Communicator ended with: 0
2016/11/03 06:29:50 [INFO] 22923 bytes written for 'stdout'
2016/11/03 06:29:50 packer: 2016/11/03 06:29:50 [INFO] 22923 bytes written for 'stdout'
2016/11/03 06:29:50 packer: 2016/11/03 06:29:50 [INFO] 0 bytes written for 'stderr'
2016/11/03 06:29:50 packer: 2016/11/03 06:29:50 [INFO] RPC client: Communicator ended with: 0
2016/11/03 06:29:50 ui: ==> foo-base-gcp-freebsd11: Waiting for any running startup script to finish...
==> foo-base-gcp-freebsd11: Waiting for any running startup script to finish...
2016/11/03 06:29:50 ui: ==> foo-base-gcp-freebsd11: Startup script not finished yet. Waiting...
==> foo-base-gcp-freebsd11: Startup script not finished yet. Waiting...
2016/11/03 06:30:00 ui: ==> foo-base-gcp-freebsd11: Startup script not finished yet. Waiting...
==> foo-base-gcp-freebsd11: Startup script not finished yet. Waiting...
```

**Comment by jevonearth** [comment]
I still had "startup_script_file" or "metadata"."startup-script" in my packer config.

After removing those settings, and using your latest build, my image seems to complete correctly. Appears to be good now, but I'm curious if this will bite someone using `startup_script_file` in the future.

**Comment by mwhooker** [comment]
hmm, could you clarify? Do you mean if someone has those settings but they point to a non-existant script?

**Comment by jevonearth** [comment]
I'll re-test and confirm. Thanks.

**Comment by jevonearth** [comment]
The below packer config, and referenced shell file should trigger the "Startup script not finished yet. Waiting..." condition. Using @crunk1 master build.

Log:
https://gist.github.com/jevonearth/d57705252c2e60de4dfc1e7d5ad9be35

```
{
  "builders": [
    {
      "image_name": "foo-base-gcp-11-0-{{timestamp}}",
      "account_file": "../gcp_account.json",
      "name": "foo-base-gcp-freebsd11",
      "zone": "us-west1-a",
      "startup_script_file": "startup_script.sh",
      "disk_size": "30",
      "source_image": "freebsd-11-0-release-p1-amd64",
      "source_image_project_id": "freebsd-org-cloud-dev",
      "ssh_username": "packer",
      "project_id": "sippy-infrastructure",
      "type": "googlecompute"
    }  ]
}
```

```
cat startup_script.sh
#!/bin/sh
echo "Hi, my name is Scott. I'm waiting 60 seconds!" >> /scott
sleep 60
echo "I'm done waiting!" >> /scott
```

**Comment by crunk1** [comment]
So, are you confirming that it works? Or is there an issue? I see that the "waiting" prompt occurred over a period of ~30 secs before you killed the build. My test startup script was made to run for 60 secs.

**Comment by jevonearth** [comment]
I think there is still an issue, but you are right, I was too quick with my log. I made a new test, and added a sprinkle of patience. :)

Please see: https://gist.github.com/jevonearth/1676bdfd519b431981e3e7cd34af77db

**Comment by crunk1** [comment]
I haven't done anything with FreeBSD on GCE. Can you get a copy of /var/log/messages (or whatever syslogs go to in FreeBSD) of the instance created by the builder? I want to see if startup scripts are running properly on the instance.

**Comment by mwhooker** [comment]
reopening as this seems to still be an issue

**Comment by crunk1** [comment]
@jevonearth are you still having troubles with this?

**Comment by jevonearth** [comment]
Been busy here, but I will make some time early next week to re-test and got you useful info from /var/logs etc.

**Comment by mwhooker** [comment]
Going to close until we can get confirmation that it's still an issue
