### ISSUE TITLE
builder/amazon: make prevalidation optional

### ISSUE THREAD

**Issue by danp** [mitchellh/packer#4105]
Short:

It would be nice if there was an option to skip AMI name prevalidation, separate from the existing force_deregister option.

Long:

When using a template that guarantees unique names, such as by incorporating a uuid, there is minimal need to prevalidate AMI names. In some cases, when many AMIs exist, the prevalidation step can take a while and put strain on the EC2 api.

The [force_deregister](https://www.packer.io/docs/builders/amazon-ebs.html#force_deregister) option exists and [skips prevalidation](https://github.com/mitchellh/packer/blob/d920b3fbf424e1c1da98682b9868b76d61467eea/builder/amazon/common/step_pre_validate.go#L23), however this adds more danger than necessary when it would be preferable (for safety) to fail should an AMI name somehow happen to be duplicated.

Using force_deregister along with not granting the user running packer permission to call DeregisterImage is an option, though I think an explicit skip_prevalidation or similar option would be more explicit and preferable.

I could probably put a PR together if this sounds good.

**Comment by mwhooker** [comment]
I think if you wanted to submit a PR this would be fine. It seems like a really niche case, though.

I'm going to close this since we won't be working on this for 1.0, but if you do submit a PR I will happily look at it.
