### ISSUE TITLE
builder/amazon: prevent metadata service timeouts

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#4111]
In a hosted environment we've seen `Get http://169.254.169.254/latest/meta-data/placement/availability-zone: dial tcp 169.254.169.254:80: i/o timeout` errors

terraform has some code that might help us https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/auth_helpers.go#L112-L140

**Comment by mwhooker** [comment]
@jen20 can you help me reproduce this issue? I'm not sure if it's a transient thing or repeatable deterministically

**Comment by jen20** [comment]
I discussed offline with @mwhooker, we think we have a solution.

**Comment by mwhooker** [comment]
a little more clarity: this happens on providers who try to impersonate the aws meta-data service, but which actually can't respond correctly. I'm closing this as I think it's out of scope of packer
