### ISSUE TITLE
AWS IAM Role missing rule for attaching existing Security Group

### ISSUE THREAD

**Issue by rwildgrube** [mitchellh/packer#4112]
If you are attaching an existing security group using:
 "security_group_ids": "sg-xxxxxxxx",

In your json file  with the policy example in https://www.packer.io/docs/builders/amazon.html it fails and attached the default Security Group.
To fix the issues you need to add:
ec2:DescribeSecurityGroups 
to the policy.
I would suggest adding this to the documentation.

**Comment by mwhooker** [comment]
The docs aren't updated on the website yet, but this was fixed in #4059
