### ISSUE TITLE
Allow specifying additional tenants for sharing OpenStack images.

### ISSUE THREAD

**Issue by clstokes** [mitchellh/packer#4113]
When building an OpenStack image using Packer, the resulting image is available only to the tenant (or project) that was specified in the builder. Additional tenant ids should be able to be set (optionally) to share the resulting image with multiple tenants. This is functionally equivalent to the [ami_users](https://www.packer.io/docs/builders/amazon-ebs.html#ami_users) option for the `amazon-ebs` builder.

**Comment by rickard-von-essen** [comment]
@varikin Do you know if this requires Glance?

**Comment by varikin** [comment]
@rickard-von-essen I would assume so, but I am haven't looked at that functionality. We are happy with just making images public to all projects (tenants).

**Comment by mwhooker** [comment]
looks like the API is here https://github.com/rackspace/gophercloud/blob/HEAD/openstack/imageservice/v2/members/requests.go

**Comment by mwhooker** [comment]
@clstokes 0.12.0 will come out next week and we'll get this in immediately after in 0.12.1 before 1.0

**Comment by clstokes** [comment]
Thanks Matt!

**Comment by rickard-von-essen** [comment]
@mwhooker Could you also look into throwing in a option for visibility, private or public. See
https://github.com/rackspace/gophercloud/blob/master/openstack/imageservice/v2/images/requests.go

**Comment by mwhooker** [comment]
There's a PR for upgrading the library here, but it looks like some functionality will be lost #4211
