### ISSUE TITLE
Docs website not updated

### ISSUE THREAD

**Issue by eredi93** [mitchellh/packer#4126]
the docs on the website are not matching the one in the repo.
The AWS policy here:
https://www.packer.io/docs/builders/amazon.html
do not match this one:
https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/amazon.html.md

I discovered it after wasting 1h with permission problems. The Policy on the website is missing permission eg `ec2:DescribeSecurityGroups`

**Comment by rickard-von-essen** [comment]
The site is deployed when a release is made. 0.12.0 will be released in about a week.
