### ISSUE TITLE
builder/azure hangs with 'waagent -deprovision+user'

### ISSUE THREAD

**Issue by maxim-nazarenko** [mitchellh/packer#4129]
Packer version: 0.11.0

I used https://github.com/mitchellh/packer/blob/master/examples/azure/debian.json as start point for Azure image building.
The build process hangs for a while after running `/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync` at the same time deprovision without '+user' works just fine.

The error itself:
```shell
Build 'azure-arm' errored: Retryable error: Error removing temporary script at /tmp/script_9899.sh: ssh: handshake failed: EOF
```

**Comment by rickard-von-essen** [comment]
I guess that if you add `"skip_clean": true` to your `shell` provisioner it will be fine.

**Comment by maxim-nazarenko** [comment]
Thank you @rickard-von-essen `skip_clean` solved the problem.
I was sure that packer kept SSH connection opened after shell provision and used it for script cleanup process. 
But it looks like packer tries to establish new connection and after `-deprovision+user` credentials for SSH become invalid
