### ISSUE TITLE
VirtualBox Builder - omit export

### ISSUE THREAD

**Issue by wellenvogel** [mitchellh/packer#4131]
It would be helpfull to be able to completely omit the export of the VM during a VirtualBox build.
The usecase:
Using a custom provisioner script the necessary data will already be fetched from within the machine after the installation is finished. There is no need for an ova/ovf afterwards.
Basically the export is no real problem - but it consumes time (and resources).

**Comment by mwhooker** [comment]
should be pretty straight-forward if anyone wants to submit a PR.

Would just conditionally add the `vboxcommon.StepExport` step in the virtualbox builders. Probably want to add a config option like `skip_export`.

**Comment by wellenvogel** [comment]
Maybe we could reuse the format <code>format</code> option with a value of <code>none</code>.

**Comment by rickard-von-essen** [comment]
I think it's cleaner to check for skip_export in step_export and just log a
message and return step.Continue

**Comment by rickard-von-essen** [comment]
@mwhooker Yes I agree.

**Comment by marema31** [comment]
I'd love to have a such option for vmware-iso builder too.

If the referenced PR is OK, why not duplicate it for other builders ?

**Comment by DanHam** [comment]
@marema31 Probably best if you open a new issue requesting a `skip_export` option for the VMware ISO builder. A new PR can then be raised against that request rather than referencing this one... 

That said, so long as the PR for Virtualbox is accepted (i.e. I haven't messed things up!!), doing the same for VMware shouldn't be too difficult...

**Comment by wellenvogel** [comment]
Tested with 0.12.2. Works perfectly. Many Thanks.

**Comment by santhoshm153** [comment]
can we extend this to hyperv-vmcx  builder too?

**Comment by DanHam** [comment]
Hi @santhoshm153. 

I've just taken a look at the code for the hyperv-vmcx builder and it looks as though the option to skip the export of the VM is already in place - it just hasn't been added to the documentation.

The option you would need to set in your build template is:

 `skip_export: true` 

Unfortunately, I don't have a working Hyper-V environment to test that with at the moment, but from what I can see this should work for you.

Would you be able to test this and report back? If this works for you we can then fix the omission in the docs.

**Comment by DanHam** [comment]
Note to myself: The option is also there for the ISO builder as well, but again is missing from the docs!

@santhoshm153 Would you be able to test this with the ISO builder as well?

**Comment by santhoshm153** [comment]
HI @DanHam ,

I tested with hyperv-vmcx. It works only when it is combined with `"skip_compaction": true` else Packer throws error complaining the disks are unavailable.

Compacting disks is set to true by default. 

Thanks for helping out.

**Comment by DanHam** [comment]
@santhoshm153 Thanks for reporting. I've opened #6392 to track the bug you've discovered.

If you don't mind, it would be good to get your thoughts on the discussion started there. Once ready, testing and feedback on the fix would also be much appreciated.
