### ISSUE TITLE
packer build: don't open stdin if a file is provided

### ISSUE THREAD

**Issue by keiranmraine** [mitchellh/packer#4132]
At present you can read the json template from stdin, but it seems counter intuitive that the process opens stdin even when a file is provided.

As the args expect `-` when reading from stdin why is the handle held open?  This can cause mild confusion as to why a process can't be run in the background, especially when `-machine-readable` is in effect.  Clearly the work around is possible but it makes for noisy ancillary code:

```
nohup packer build -machine-readable .... template.json < /dev/null >& build.log &
```

Other wise I'm really enjoying working with packer (OpenStack post-processor +1)

**Comment by mwhooker** [comment]
yeah this seems like a reasonable thing to do, but after a quick glance at the code, it's not obvious where we're opening stdin. This seems like a real bug, but it is sufficiently rare that we're focused on 1.0 and won't be fixing this without a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
