### ISSUE TITLE
Feature Request: Better use of EC2 spot instances with on-demand fallback

### ISSUE THREAD

**Issue by CpuID** [mitchellh/packer#4145]
It is common when using `spot_price` on the amazon-* builders, to end up with `price-too-low` requiring a manual change of either a) `availability_zone` or b) `spot_price`. A good example:

- c4.large in us-east-1 has an on-demand price of 0.105/hr
- spot prices in 2 AZ's are well below the on-demand price
- the other 2 AZ's are easily 5-10x the on-demand price

![capture](https://cloud.githubusercontent.com/assets/916201/20162535/79f75f5e-a741-11e6-8bed-595b57ab05d0.PNG)

The logic [here](https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_run_source_instance.go) currently allows the following options:

- `spot_price` of "0" or unset to use on-demand
- `spot_price` of any decimal value (as a string in JSON) to specify a max bid
- `spot_price` of "auto" to check the current spot price (regardless of the maximum), add 0.005 and apply it as the maximum accepted price at the time

I think a better approach would be a flag to check the on-demand prices using [this JS file](https://a0.awsstatic.com/pricing/1/ec2/linux-od.min.js?callback=callback&_=1478745282582) and compare against the spot price (needs a little mangling as it's not just JSON, mostly just stripping the header and footer callback wrapper. I have done it before in Ruby a couple of years ago and the code still works so the logic doesn't change often). You would then submit a spot request at the current on-demand price, and if you get a price-too-low response, cancel it and submit an on-demand instance request as a fallback.

This would allow getting the savings of spot instances, without the risk of paying above the on-demand rate when they spike substantially higher.

Thoughts...?

**Comment by CpuID** [comment]
An alternate workaround is described in https://github.com/mitchellh/packer/issues/4146 - different solution to a similar underlying problem.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
