### ISSUE TITLE
override packer template file

### ISSUE THREAD

**Issue by RajatGoyal** [mitchellh/packer#4157]
I have a packer configuration file which uses remote shell provisioning on aws ebs builder, most of the things in the packer file are common to our many microservices. I want to keep this packer file as a git submodule for each of our microservices. Ideally, I would want to create a new JSON for each of my microservices which will inherit provisioner and builders from my existing JSON and the new json should be able to add new additional provisioners if required.

Essentially a functionality to import provisioner and builder configs defined in another template file.

Is there any such existing capability, or a workaround?

**Comment by rickard-von-essen** [comment]
Your best option is to use a wrapper that joins json or yaml files together or use something like https://github.com/aspring/racker .

Or you can also use file provisioner to upload a directory of provision script and invoke a generic shell provisioner which only runs all those files.

**Comment by RajatGoyal** [comment]
Thanks @rickard-von-essen racker feels exactly like the functionality that I needed. I had the second suggestion in mind, but really limits packer flexibility when i want to use multiple type of provisioner.
