### ISSUE TITLE
Packer v0.11.0 does not work with MacOS Sierra v10.12.1 

### ISSUE THREAD

**Issue by dashfwd** [mitchellh/packer#4160]
Packer fails in numerous ways. 
-> It often launches an Amazon instance, and then waits forever to connect to it.
-> If it gets far enough to start provisioning, it often dies with an EOF error.
-> Other indeterminate hangs

I've not been reliably able to get my packer script to run using MacOS Sierra.  The exact same script works fine if I'm using Ubuntu, using the same version of Packer.  

I'm guessing this is another issue with the "Go" library, which seems to have no end of problems working with MacOS Sierra, but that's just a guess because I know 0.10.0 had issues.

Packer version: 0.11.0
Host platform: MacOS Sierra v10.12.1
Using builder: amazon-ebs
Debug log output: https://gist.github.com/dashfwd/e218de77bba4550a7586f47caa8de750 (Note: it got to the point where it couldn't connect and I did a CTRL+C at this point)
Simplest example templates and scripts:
```
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": "",
    "jdk_version": "jdk-8u65-linux-x64",
    "jdk_home": "/usr/java/jdk1.8.0_65",
    "region" : "us-west-2"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "communicator": "ssh",
      "ssh_keypair_name" : "keypair",
      "ssh_private_key_file": "somekeypair.pem",
      "iam_instance_profile" : "instance",
      "ssh_pty": true,
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "region": "us-west-2",
      "source_ami": "ami-5ec1673e",
      "instance_type": "m3.medium",
      "ssh_username": "ec2-user",
      "ami_name": "my_ami_{{user `build_timestamp`}}",
      "tags": {
        "Name": "my_ami_{{user `build_timestamp`}}"
      }
    }
  ],
  "provisioners": [
    # NOTE: Removed, it rarely seems to even get to doing the actual provisioning.
  ]
}
```

**Comment by rickard-von-essen** [comment]
Your install is broken. Remove your current install directory and reinstall from [packer.io/downloads](https://www.packer.io/downloads.html). _Be sure to read the **note** about upgrading from < 0.9.0._
