### ISSUE TITLE
Builder virtualbox-iso behaves differently than vmware-iso

### ISSUE THREAD

**Issue by dhoppe** [mitchellh/packer#4161]
* Operating System macOS 10.12.1
* Packer 0.11.0
* VirtualBox 5.1.8
* VMware Fusion 8.5.1

I use the following Packer [template](https://github.com/dhoppe/packer-templates/blob/master/debian-8.6.0-amd64/template.json) to create a Vagrant box for VirtualBox and VMware Fusion.

For some reason the builder `virtualbox-iso` behaves differently than `vmware-iso`. While the build for VMware Fusion is terminated without problems (except #4054), the build for VirtualBox asks during the installation of Debian for the root password.

I do not know why this happens, since I use the same `boot_command` and `preseed.cfg` for both environments. So this should not be an issue of the Operating System.

Build [logs](https://gist.github.com/dhoppe/8c32e458c85ae04b0f19854a507146ee) for `virtualbox-iso` and `vmware-iso`.

**Comment by rickard-von-essen** [comment]
I can't repro this with a build from master. Can you explain what you mean with:

> the build for VirtualBox asks during the installation of Debian for the root password.

**Comment by dhoppe** [comment]
The installation via VirtualBox does not honor the settings from Persers.cfg,

**Comment by rickard-von-essen** [comment]
This is most likely not a bug in Packer. Since both builders works fine for me, I think you should try rerunning and verify that the load of the machine during the typing of the `boot_command` is low since otherwise it can interfere with it. Also try to verify that everything is typed as is should on the console. If you still have the problem attach the installation logs here and some screenshots of where it get stuck (asks for root).

**Comment by dhoppe** [comment]
I followed your recommendations and this is the boot command.
![boot](https://cloud.githubusercontent.com/assets/1111056/20242400/e47f88a0-a92c-11e6-84b8-7b8789435f63.png)

As you can see at the log file, the newline from the previous screenshot is caused by the resolution of the VirtualBox window.
![boot_log](https://cloud.githubusercontent.com/assets/1111056/20242404/f8f24fd4-a92c-11e6-9f7e-487ab3f8dac1.png)

This is where the Debian installer stops and asks for the root password, even if `d-i passwd/root-login boolean false` is configured at `preseed.cfg`. 
![installer](https://cloud.githubusercontent.com/assets/1111056/20242410/4f1afe1a-a92d-11e6-9ef2-261c95314e1d.png)

According to the console the `preseed.cfg` was loaded successfully. 
![console](https://cloud.githubusercontent.com/assets/1111056/20242408/43b95abc-a92d-11e6-94a1-130c7bb48830.png)

Maybe it is not a problem of the builder, because I am able to build Vagrant boxes (virtualbox-iso) for Ubuntu 12.04, 14.04 and 16.04. But what drives me crazy is that I am able to build Vagrant boxes (vmware-iso) with the same `boot_command` and `preseed.cfg`, but it fails for Vagrant boxes (virtualbox-iso).
![vmware](https://cloud.githubusercontent.com/assets/1111056/20242413/7a7d00bc-a92d-11e6-9d59-85081e515241.png)

**Comment by rickard-von-essen** [comment]
I tried again with Packer 0.11.0 on macOS Sierra, VirtualBox 5.1.6 and everything builds fine. I don't think there is anything more I try. I suggest you try on another machine or reinstall VirtualBox. If you find any more details about what is going wrong or find a solution feel free to post it here.

**Comment by dhoppe** [comment]
The problem no longer occurs since I have updated to VirtualBox 5.1.10.

**Comment by rickard-von-essen** [comment]
Great to hear, and thanks for reporting back.
