### ISSUE TITLE
builder/profitbicks: Fix (ssh) comm and some other options

### ISSUE THREAD

**Issue by rickard-von-essen** [mitchellh/packer#4169]
Comm related:
- [ ] Port 22 [shouldn't be hard coded](https://github.com/mitchellh/packer/blob/master/builder/profitbricks/config.go#L60). (If the builder requires port 22, validate that the template only contains 22 or "", don't silently ignore the option)
- [ ] Remove `ssh_key_path`
- [x] ~~Create a `fixer`which migrates `ssh_key_path` -> `ssh_private_key_file`~~ N/A
- [ ] `ssh.go` must handle a three different ssh auth methods that Packer supports; password, keyboard interactive, and ssh key, see [VirtualBox - ssh.go](https://github.com/mitchellh/packer/blob/master/builder/virtualbox/common/ssh.go#L21)

Not Comm related:
- [ ] Remove the default `image`.  Adjust the example accordingly.
- [ ] `timeout` should take a `time.Duration`, see [VirtualBox - shutdown_config.go](https://github.com/mitchellh/packer/blob/master/builder/virtualbox/common/shutdown_config.go#L12). Adjust the example accordingly.

Q: Does Profitbricks work with WinRM?

https://github.com/mitchellh/packer/blob/master/builder/profitbricks/config.go#L25

**Comment by jasminSPC** [comment]
Would it be ok if I handle this together with 1&1 PR?

**Comment by jasminSPC** [comment]
Can you be a little more specific when you say this:

` Create a fixer which migrates ssh_key_path -> ssh_private_key_file` Do you want me to change how i call ssh_key_path, or did you have something else in mind?

**Comment by rickard-von-essen** [comment]
> Would it be ok if I handle this together with 1&1 PR?

I guess not, even though it might be easier to pinpoint a change if they are separate. You choose.

> Can you be a little more specific when you say...

Sorry just realized this wasn't in the latest release so we can just skip it. 

FYI: Fixers are used to migrate users templates with the `packer fix <template>` command. And there was already a fixer for `ssh_key_path`, see https://github.com/mitchellh/packer/blob/master/fix/fixer_sshkeypath.go

**Comment by jasminSPC** [comment]
Alright.

Just to be clear it doesn't matter to you if I handle this in one PR?

And also about timeout, in both providers the value `timeout` doesn't indicate time period but number of iterations that will happen every second.  So 60 doesn't directly mean 60 seconds but rather 60 iterations where each iteration lasts `GetRequestStatus` + 1 second sleep. What do you suggest we do?

**Comment by jasminSPC** [comment]
As for WinRm it is not supported.

**Comment by rickard-von-essen** [comment]
> Just to be clear it doesn't matter to you if I handle this in one PR?

One PR is fine.

> And also about timeout[...]

Ok, then I see there is 3 alternatives:
1) Rename `timeout` to `retries` and explain in the docs that it will retry after on sec.
2) Take a `time.Duration` and convert to second and use it as the number of iterations to do, even though it's inaccurate.
3) Or you can use a timer, see [step_shutdown.go](https://github.com/mitchellh/packer/blob/master/builder/parallels/common/step_shutdown.go#L47)

I guess number 3 is the best but requires most changes. You chose which you do, or if you have another alternative.

**Comment by jasminSPC** [comment]
I'm going to go for retries,  as it requires the least work on both providers.

**Comment by jasminSPC** [comment]
Also about keyboard interaction. To provision a server either ssh key or password are required so keyboard interaction doesn't play any role.

**Comment by rickard-von-essen** [comment]
Keyboard interactive is a variation of password so it's needed.

**Comment by jasminSPC** [comment]
There you go

**Comment by rickard-von-essen** [comment]
Looks good. Could you also drop the default `ssh_username` = `root` in both builders. Related to #4172.

**Comment by jasminSPC** [comment]
I just did here https://github.com/mitchellh/packer/pull/4163/commits/68ca7490bbb465964ce2d4e5070d4dcecbbe42d4

**Comment by mwhooker** [comment]
What's the status of this? If there's work to be done I think this will have to wait until after 1.0

**Comment by jasminSPC** [comment]
All the remarks have been addressed couple of weeks ago.

**Comment by mwhooker** [comment]
noticed `ssh_key_path` was in docs. will fix
