### ISSUE TITLE
Get machine ip in provisioner

### ISSUE THREAD

**Issue by RajatGoyal** [mitchellh/packer#4177]
I want to know the public IP of the machine which packer has provisioned to create the AMI. I am using Capistrano to deploy sidekiq in my machine(by running local-shell provisioner) after packer has installed other dependencies, but Capistrano will need the IP and ssh-agent should have the private key that packer has used to create the machine.

can someone guide me on how should i do that or if there is already and example, that would be great?

**Comment by kronos** [comment]
I think this ticket duplicates #4173

**Comment by RajatGoyal** [comment]
Agreed, I am wondering if there is a workaround? because people must be using Capistrano with packer already?

**Comment by kronos** [comment]
I failed to find the solution and postponed packer for a time being.

**Comment by mwhooker** [comment]
let's keep discussion in #4173
