### ISSUE TITLE
"floppy_files" with wildcard characters are not working properly in qemu builder 

### ISSUE THREAD

**Issue by ruzickap** [mitchellh/packer#4178]
Hello.

It looks like there is a bug in Packer 0.11 and 0.12 when using the floppy_files with wildcards.
It's not happening in version 0.10 - with this version it's working fine like it's in the documentation: https://www.packer.io/docs/builders/qemu.html#floppy_files

When I'm using "floppy_files" like this:

```
      "floppy_files": [
        "/var/tmp/del/NetKVM/w10/amd64/netkvm*.cat"
      ]
```

I'm getting this error:

```
* Bad Floppy disk file '/var/tmp/del/NetKVM/w10/amd64/netkvm*.cat': stat /var/tmp/del/NetKVM/w10/amd64/netkvm*.cat: no such file or directory
```

FOR BUGS:
- Packer version: Packer v0.11.0 and Packer v0.12.0
- Host platform: Fedora 23
- Debug log output from `PACKER_LOG=1 packer build template.json`: https://gist.github.com/ruzickap/9dddefef90bf28b927916dd1f31efa93
- The _simplest example template and scripts_ needed to reproduce the bug.
```
  "builders":
  [
    {
......
      "type": "qemu",
......
      "floppy_files": [
        "/var/tmp/del/NetKVM/w10/amd64/netkvm*.cat"
      ]
    }
  ],
```

Thank you for looking at it...

**Comment by skeenan947** [comment]
I'm getting the same thing with the VirtualBox builder (FWIW, I have the qemu builder in the template as well, but using -only=virtualbox-iso)

**Comment by jbarnett1981** [comment]
Same here trying to use qemu builder on CentOS 7.2.1511 using Packer 0.11.1 compiled from source.

**Comment by vtolstov** [comment]
I have pr for this,but it fails to test, so please waiting..

18 Ноя 2016 г. 4:54 пользователь "jbarnett1981" <notifications@github.com>
написал:

**Comment by vtolstov** [comment]
2016-11-20 16:14 GMT+03:00 Vasiliy Tolstov <v.tolstov@selfip.ru>:

> I have pr for this,but it fails to test, so please waiting..


I'm fix pr


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru
