### ISSUE TITLE
post-processor/manifest variables in filename

### ISSUE THREAD

**Issue by arosenhagen** [mitchellh/packer#4180]
unfortunately the variable ```{{.Provider}}``` in this doesn't work:
```
"filename": "../builds/{{.Provider}}/{{ user `PACKER_BOX_NAME` }}_{{.Provider}}.manifest.json",
```
output is:
```
Unable to write ../builds/<no value>/debian-8.6.0-amd64_<no value>.manifest.json
```
And it would be nice to stick to the naming of other post-processors and name it "output" instead of "filename".

**Comment by rickard-von-essen** [comment]
@vtolstov do you mind creating a PR for this?

**Comment by vtolstov** [comment]
I'm try to fix this today.

18 Ноя 2016 г. 19:35 пользователь "Rickard von Essen" <
notifications@github.com> написал:
