### ISSUE TITLE
Amazon-ebs builder; ssh_keypair_name not working.

### ISSUE THREAD

**Issue by MaarthenKastanja** [mitchellh/packer#4181]
Amazon-ebs builder; option "ssh_keypair_name" not used correctly.

- Packer version from `packer version`: **0.12.0**
- Host platform: **Mac OSX 10.11.6**
- Debug log output from `PACKER_LOG=1 packer build template.json`.
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com
**https://gist.github.com/MaarthenKastanja/7392a89008555b717eefb10fa6ca16ce**

Hello, the "ssh_keypair_name" option does not seem to implement the key correctly. Manual deployment does work; connecting with keypair authentication works without issues. Am I missing something?

Tried different source AMIs;
Centos7 AMI    -     ami-9bf712f4
Amazon Linux AMI 2015.03    -    ami-7089b46d

Details added in the gist. 

Thanks.

**Comment by MaarthenKastanja** [comment]
Sorry, it regarded a blocking sg that was being used. My bad.

**Comment by rickard-von-essen** [comment]
Thanks for reporting back!
