### ISSUE TITLE
Consistent SSH handshake error

### ISSUE THREAD

**Issue by vanjohnson** [mitchellh/packer#4194]
Constantly getting a "Build 'ubuntu-1404-server' errored: Timeout waiting for SSH" .  sshd is running and there are no specific hints that tell me what the issue is.  The interesting part is that each machine that I run this on (packer build ubuntu-14.04-server-amd64-v012.json) it will run once and build successfully and then never again.  That's where I am at.

- Packer v0.12.0
- Running packer on a Red Hat 7.2 vm with virtualization hardware exposed on the client hypervisor  

Debug output. 
https://gist.github.com/vanjohnson/538e7aa420cd1fbef9106dd937ddbb28

Packer Template.
https://gist.github.com/vanjohnson/918accf08e312a5e386c3e79a9283eac

Preseed file.
https://gist.github.com/vanjohnson/69416b613306ec549e9025c7145018c4

**Comment by rickard-von-essen** [comment]
Could you fix your links.

**Comment by vanjohnson** [comment]
Fixed thanks.

**Comment by rickard-von-essen** [comment]
I believe rhel doesn't allow root login on ssh by default.

**Comment by vanjohnson** [comment]
Yeah I set the username to something other than root and it threw the same errors.
```
"variables": {
    "disk_size": "100000",
    "password": "iDirect",
    "user": "vjohnson"
  }
```

**Comment by rickard-von-essen** [comment]
But you don't add any user in your preseed.

**Comment by vanjohnson** [comment]
Setting `PermitRootLogin yes` in sshd_config, didn't work for me wither.

**Comment by vanjohnson** [comment]
I found a good enough solution in the following link.  I just didn't expect reverse lookup to take so long.  I increased my  `"ssh_wait_timeout": "10m"` instead of 2m.  
https://github.com/mitchellh/packer/issues/78
