### ISSUE TITLE
Docker build hangs on provisioning with 0.12.0

### ISSUE THREAD

**Issue by munjeli** [mitchellh/packer#4196]
I just upgraded to Packer 0.12.0 from 0.10.1 so I could use the ecr push feature, but the docker build now hangs on the first provisioner (even when I've switched the provisioners around). I logged into the container while it was up and could manually run the provisioning commands with no problem, and the same template worked in 0.10.1. I'll roll back and see if it works with 11, but let me know if there's more information I can provide. 

- 0.12.0
- Ubuntu 14.04 (in VMware)
Here's the gist: https://gist.github.com/munjeli/bb4fd9181e6afb3d63878ee90d88b0d4

**Comment by mwhooker** [comment]
interesting. what version of docker? How long would you say you wait before cancelling the build?

it'd be very helpful if you could come up with a minimal packer.json that can reproduce this. I tried with the following, but the build worked fine for me.


```
{
  "variables": {
    "cookbook_path": "{{env `WORKSPACE`}}/ops/base/cookbooks"
  },
  "builders": [
   {
     "type": "docker",
     "image": "ubuntu:xenial",
     "commit": true
   }
   ],
 "provisioners": [
 {
  "type": "shell",
  "inline": [
    "mkdir -p /etc/chef &&  chmod 777 /etc/chef",
    "mkdir -p /tmp/packer-chef-client &&  chmod 777 /tmp/packer-chef-client"
  ]
  }
 ]
}
```

**Comment by james-powis** [comment]
I too have seen issues with packer hanging since upgrading to the 0.12.0 as pulled last week from github. It hangs at "waiting for SSH" stage and if you connect to VNC it immediately connects via SSH and progresses to completion. Additionally the SSH timeout never times out, so this can be hours after the build started.

**Comment by james-powis** [comment]
Forgot to mention I am using Virtualbox provisioner

**Comment by munjeli** [comment]
I am on an older docker... 1.6.2 I'll upgrade that and see if it flies. It did hang for more than a half hour at one point. I just installed 0.11.0 and am seeing the same behavior though, which makes me suspect docker. I'll check in after I upgrade that.

**Comment by mwhooker** [comment]
@james-powis where is packer trying to connect over ssh? We don't use the ssh communicator for docker builds

**Comment by munjeli** [comment]
I'm gonna close this. It worked when I updated Docker.. I'm on the newest version now. Good to know, and thanks for your help :D

**Comment by mwhooker** [comment]
@munjeli of course! glad we got it fixed
