### ISSUE TITLE
Azure ARM Available Image not working

### ISSUE THREAD

**Issue by frostarun** [mitchellh/packer#4199]
Hi, 

    While working with Azure ARM builders , its failing to lauch a VM on West US. 
**statusMessage** :The platform image 'Canonical:UbuntuServer:16.04.0-LTS:latest' is not available. Verify that all fields in the storage profile are correct.

I have seen in my console and the variant of that machine is available , But Still its saying unavailable.I have template reference : 
`"storageProfile": {
                    "imageReference": {
                        "publisher": "Canonical",
                        "offer": "UbuntuServer",
                        "sku": "16.04.0-LTS",
                        "version": "latest"
                    }`

my json template for Packer : 
`{ "builders": [{
    "type": "azure-arm",
    "ssh_username": "chnadmin",
    "ssh_password": "XXX",
    "client_id": "XXXX",
    "client_secret": "XXXXX",
    "resource_group_name": "arunpackertest",
    "storage_account": "packersc",
    "subscription_id": "XXXXX",
    "tenant_id": "XXXXX",
    "capture_container_name": "packercontainer",
    "capture_name_prefix": "packertest",
    "os_type": "Linux",
    "image_publisher": "Canonical",
    "image_offer": "UbuntuServer",
    "image_sku": "16.04.0-LTS",
    "image_version":"latest",
    "location": "West US",
    "vm_size": "Standard_DS1_v2"
  }]}`

Sorry if I had raised a false issue.

Regards ,
Arun Kumar GR.

**Comment by boumenot** [comment]
I would not worry about raising a false issues.  I would rather to reach out to us than not.  👍 

I verified the issue for West US.  I retried in a different region, South Central US, without issue, so I need to follow up internally on this.

**Comment by frostarun** [comment]
Thanks for the reply. And your site Azure ARM documentation templates are with **West US** location , people following that template might face same issue .

**Comment by boumenot** [comment]
Agreed.  West US needs to work.  If it does not than it is unacceptable, and needs to be fixed.

**Comment by frostarun** [comment]
Hi , As you said its working with 'Central US' . Its creating two container called 'Image and System'. Its using 'Image' as temp storage for vhd and its deleting the vhd and leaves the container empty behind . Is that the process ? . It doesn't delete the Container(Image) which it created for storing temp vhd.

**Comment by boumenot** [comment]
The System container is auto-created when the image is _captured_.  This is the VHD you use to deploy.  The temporary image should be deleted after the build has completed.

**Comment by frostarun** [comment]
The image is getting deleted but the temp container where the temp image resisted remains empty and doesn't get deleted. That container is named as 'Image' by default.

**Comment by boumenot** [comment]
Correct, the container is not deleted.

The name of the container is controlled via a configuration value.

> "capture_container_name": "images",

**Comment by boumenot** [comment]
I believe you are unblocked.  If you have any other issues let me know.
