### ISSUE TITLE
allow templates to be defined using yaml

### ISSUE THREAD

**Issue by kidbrax** [mitchellh/packer#4200]
Please allow templates to be defined in YAML. It is easier to read and, more importantly, allows comments.

It is a common use case, even Amazon now allows CloudFormation to be defined with YAML.

**Comment by rickard-von-essen** [comment]
You can just do:

```bash
cat template.yaml | ruby -r json -r yaml -e "yaml = YAML.load(ARGF.read); print yaml.to_json"
```

**Comment by rickard-von-essen** [comment]
Duplicates #1047

**Comment by mwhooker** [comment]
If you'd like to submit a pull request that handles both yaml and json, please feel free to, but this isn't a priority for us.

I noticed this library which may be helpful for you https://github.com/ghodss/yaml

We may in the future however support [hcl](https://github.com/hashicorp/hcl) which supports comments.

**Comment by quixand** [comment]
I would really like to put comments in my config files without having to process my config files
