### ISSUE TITLE
AMI persistence in Vagrant Boxes info is unclear

### ISSUE THREAD

**Issue by iainelder** [mitchellh/packer#4208]
The current [Vagrant Boxes](https://www.packer.io/intro/getting-started/vagrant.html) section of the intro has two apparently contradictory paragraphs.

> **But where did the AMI go? When using post-processors, Vagrant removes intermediary artifacts since they're usually not wanted. Only the final artifact is preserved.** This behavior can be changed, of course. Changing this behavior is covered in the documentation.

> Typically when removing intermediary artifacts, the actual underlying files or resources of the artifact are also removed. For example, when building a VMware image, if you turn it into a Vagrant box, the files of the VMware image will be deleted since they were compressed into the Vagrant box. **With creating AWS images, however, the AMI is kept around, since Vagrant needs it to function.**

It's unclear whether the AMI is supposed to persist after creating the Vagrant box.

Following the tutorial with packer 0.11.0, the AMI is still available after building example.json ([gist](https://gist.github.com/iainelder/f38bbbd6deeca0aafcf9e0bd7d3784cf)).

```
$ AWS_PROFILE=staging packer build -only=amazon-ebs example.json
[...]
==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

us-east-1: ami-c02e13d7
--> amazon-ebs: 'aws' provider box: packer_amazon-ebs_aws.box
```

```
$ ls -1
example.json
packer_amazon-ebs_aws.box
```

```
$ aws ec2 describe-images \
> --image-ids ami-c02e13d7 \
> --region us-east-1 \
> --profile staging \
> --query "Images[].[Name,ImageId,State]" \
> --output text
packer-example 1480168550	ami-c02e13d7	available
```

**Comment by rickard-von-essen** [comment]
The second paragraph is correct, the first is a bit vague. 

> But where did the AMI go? When using post-processors, Vagrant removes intermediary artifacts since they're usually not wanted. Only the final artifact is preserved. This behavior can be changed, of course. Changing this behavior is covered in the documentation.

A better phrasing could be something like:

> But where did the Amazon EBS builder artifact go?

**Comment by iainelder** [comment]
By "Amazon EBS builder", do you mean the EC2 instance (with attached EBS volume)?

I thought that the EC2 instance was always removed after creating the AMI from it, even without post-processors.

**Comment by rickard-von-essen** [comment]
No the artifact is the result. It's a data structure that stores the result and references the ami. 

What the text tries to explain is that:

1) If you have a virtualbox-iso the artifact contains the directory of the export, when this is processed by the vagrant post-processor the content of that directory is put in a tar along with some metadata. This is the vagrant box and the original virtualbox-iso artifact is removed.

2) If you have a amazon-ebs the artifact contains just a reference to the ami. When this is processed  by the vagrant post-processor the artifact is deleted and a tar just containing some metadata is created as the vagrant box. This metadata is referencing the ami, and thus it is kept.

@mwhooker I won't try to clarify this.

**Comment by mwhooker** [comment]
agreed, this is quite vague. Took @rickard-von-essen's advice
