### ISSUE TITLE
Unknown configuration key

### ISSUE THREAD

**Issue by riponbanik** [mitchellh/packer#4212]
packer: 0.12
builder - amazon-ebs

using the following show unknown configuration key
"disable_stop_instance": "true",
"shutdown_behavior": "stop",

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by riponbanik** [comment]
Here you are -
packer version - Packer v0.11.0
uname -a - Linux xxxxx 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Debug log - https://gist.github.com/riponbanik/7927cff6e38b341ddedc96d1b70f1b05
Sample template - https://gist.github.com/riponbanik/5646945249daca6d342d517b27c930ab

**Comment by rickard-von-essen** [comment]
A debug log should be setting env var PACKER_LOG. `PACKER_LOG=1 packer
validate template.json`

**Comment by donnoman** [comment]
I'm getting the same thing

› packer --version
0.12.0
› uname -a
Darwin Donovans-MBP.attlocal.net 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64

Gist: https://gist.github.com/donnoman/47eb1565a821b1983a820d084ace4fd8

**Comment by rickard-von-essen** [comment]
Spelling 
https://www.packer.io/docs/builders/amazon-ebs.html#shutdown_behaviour

**Comment by donnoman** [comment]
awww bloody brits, LOL

after updating spelling: Template validated successfully.

**Comment by donnoman** [comment]
can we ask for an alias spelled the way websters spells it? 

Even google thinks its wrong:

Showing results for behaviour
Search instead for behviour

**Comment by donnoman** [comment]
can we ask for an EN-US alias, this won't be the last time it's reported.

**Comment by rickard-von-essen** [comment]
Actually this should be spelled as the [AWS API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html) spells it, which is _"InstanceInitiatedShutdownBehavior"_. Which is actually how it's [internally is spelled](https://github.com/mitchellh/packer/blob/master/builder/amazon/common/run_config.go#L49).

**Comment by donnoman** [comment]
Awesome thank you. 👍

**Comment by riponbanik** [comment]
is it available in 0.12.2? I have updated to 0.12.2 but still complains - * unknown configuration key: "shutdown_behavior"
