### ISSUE TITLE
OVF Tool update changes default hashing algorithm 

### ISSUE THREAD

**Issue by LEALCorentin** [mitchellh/packer#4217]
Hello,

This issue is about the latest version of OVF Tool used in the VMware ESX builder. It is now in version 4.2 and the default algorithm changed from SHA1 to SHA256. It is currently not possible to change Packer args used with OVF Tool as far as I know.
The SHA256 is not supported by the vSphere Client thus, it is not possible to had an OVF VM to an ESX with this method. (It is still possible to add them using vSphere web client as I've read but I didn't tested it).

I think it would be a good idea to let users change the parameters they used.

For more details : http://www.virtuallyghetto.com/2016/11/default-hashing-algorithm-changed-in-ovftool-4-2-preventing-ovfova-import-using-vsphere-c-client.html

**Comment by mwhooker** [comment]
I believe this has been fixed in #4536

please let me know if I'm wrong and I'll re-open
