### ISSUE TITLE
Document 'login_server' for ECR-based docker builds

### ISSUE THREAD

**Issue by ankon** [mitchellh/packer#4218]
The documentation for the docker builder currently has this:

~~~~
ecr_login (boolean) - Defaults to false. If true, the builder will login in order to pull the image from Amazon EC2 Container Registry (ECR). The builder only logs in for the duration of the pull. If true login_server is required and login, login_username, and login_password will be ignored.
...
login_server (string) - The server address to login to.
~~~~

There is no concept of "login server" when talking about AWS ECR, so this is a term that packer "made up". It should therefore be documented what the login server is, maybe like this:

~~~~
ecr_login (boolean) - Defaults to false. If true, the builder will login in order to pull the image from Amazon EC2 Container Registry (ECR). The builder only logs in for the duration of the pull. If true then login_server must be set to "https://AWS-ACCOUNT-ID.dkr.ecr.REGION.amazonaws.com" and login, login_username, and login_password will be ignored.
~~~~
(I'm not sure whether login_server is ECR-specific, if it is it should maybe be renamed to that and the explanation of the format could move there)

I figured this one by actually going through the code in packer added with #3856  (https://github.com/mitchellh/packer/commit/b2d9782a9e23745059bbb8c2f420f05ae6e4e73f#diff-a714bcc592975b54a89c5cae7a01f24cR50).

**Comment by rickard-von-essen** [comment]
https://docs.docker.com/engine/reference/commandline/login/

**Comment by rickard-von-essen** [comment]
If you want to PR a clarification we can have a look. Otherwise I'm for closing this.

**Comment by ankon** [comment]
Fair enough. I tried improving the documentation by just adding a reference to the later section on ECR - when I opened the ticket I didn't even notice that there is section on that topic, and it would have helped me to read until there :)
