### ISSUE TITLE
vSphere 6.5 Error handshaking with VNC

### ISSUE THREAD

**Issue by eegilbert** [mitchellh/packer#4219]
Hello,

Just upgraded my lab to vSphere 6.5 and see this issue now with the VNC connection portion of packer build:

Error handshaking with VNC: no suitable auth schemes found. server supported: []byte{0x1}

The [GIST](https://gist.github.com/eegilbert/70e6940a87455ae2766d68799319213e) containing the debug log and JSON/shell scripts. Prior to the upgrade this was working so I suspect it's a change that vmware made in 6.5.

Thank you,

**Comment by rickard-von-essen** [comment]
Use vnc_password_disable:true

**Comment by eegilbert** [comment]
Hi Rickard, thank you. My turn to miss something obvious in the docs! :)

Working with:
"vnc_disable_password": true

Just waiting for things to progress and I will chime in when it completes

**Comment by eegilbert** [comment]
Yes, that was it thank you very much! Definitely changed between 6 and 6.5 though since I'd never needed to use it prior.
