### ISSUE TITLE
ssh_keypair_name launches source instance without assigning the key

### ISSUE THREAD

**Issue by rvandegrift** [mitchellh/packer#4220]
I'd like to use ``ssh_keypair_name`` and ``ssh_agent_auth``, but the source instance is launched without a keypair assigned.

Key is already created:
```sh
$ aws ec2 describe-key-pairs --key-names user-ross --output text
KEYPAIRS	db:da:da:3a:b4:b2:0c:20:89:7e:bf:af:27:a6:ed:33	user-ross
```

Run packer with config from: https://gist.github.com/rvandegrift/c61bc0804d78ffabf07e0a0e4fe13425
```sh
$ PACKER_LOG=1 packer build -machine-readable minimal.json
...
1480439916,,ui,say,==> amazon-ebs: Launching a source AWS instance...
1480439917,,ui,message,    amazon-ebs: Instance ID: i-02e99509503a13884
```

The instance launched without an ssh key:
```sh
$ aws ec2 describe-instances --instance-ids i-02e99509503a13884 --query 'Reservations[].Instances[].KeyName'
[]
```

Debug log: https://gist.github.com/rvandegrift/fd792ba5f32eef17f019cd7b020c1317

This is packer 0.12.0 on Linux amd64.

Thanks!

**Comment by rickard-von-essen** [comment]
I can confirm this and found the issue. I'll try to provide a patch later today.

**Comment by rickard-von-essen** [comment]
@jen20 Looping you in #4050 there seems to be some code missing. At least when setting up [`StepKeyPair`](https://github.com/jen20/packer/blob/395d88941c2a0d3ec4a9aa2905c745f20f46617b/builder/amazon/ebs/builder.go#L104) is missing `b.config.Comm.SSHAgentAuth` so you code can never be used. Is there some code left missing in #4050?
