### ISSUE TITLE
Cannot create VM from packer Azure image

### ISSUE THREAD

**Issue by hdatteln** [mitchellh/packer#4221]
packer version: 0.12.0

Steps to reproduce:

- Build a simple Azure VM image using packer, using this packer .json file: 
https://gist.github.com/hdatteln/14f209777625f836b9952efc8fab979e
- Use the template .json file that is created from the image build process to create a new Azure VM:
         azure group deployment create [resource group] --template-file mypackerazuretemplate.json

Expected result: the deployment of the new VM in Azure completes successfully
Actual result: 
Deployment gets stuck in a loop of "info:    Resource 'packerubuntu' of type 'Microsoft.Compute/virtualMachines' provisioning status is Running"

Finally, it times out with the error:

" Provisioning failed. OS Provisioning for VM 'packerubuntu' did not finish in the allotted time. However, the VM guest agent was detected running. This suggests the guest OS has not been properly prepared to be used as a VM image (with CreateOption=FromImage). To resolve this issue, either use the VHD as is with CreateOption=Attach or prepare it properly for use as an image: * Instructions for Windows: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-upload-image/ * Instructions for Linux: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-capture-image/. OSProvisioningTimedOut"

Is packer "not preparing the guest OS properly  to be used as a VM image" in Azure? Or am I missing a config option or step?

Best Regards,
Heidi

**Comment by boumenot** [comment]
We build many Linux distros and Windows against Packer's master every time there is a commit, so I am fairly confident Packer is preparing the image correctly.  In the case of Ubuntu, we build the LTS flavors, but I am not aware of an issue with 16.10.

Would you please follow the [debugging](https://www.packer.io/docs/other/debugging.html) steps, and create a gist of the log output.  I will review, and try to diagnose the issue.

There are example templates checked into the repo for [Ubuntu](https://github.com/mitchellh/packer/blob/master/examples/azure/ubuntu.json) that may be useful.

**Comment by hdatteln** [comment]
Thank you for helping with this so quickly.
Your example link pointed me in the right direction; 
i hadn't included the waagent command in the provisioner, to generalize the system.

After following the examples more closely and adding this line in the provisioner section, it works fine:
"/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"

This document actually also mentions that this is a neccessary step: https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-capture-image
I had missed that in my very simple packer .json.
