### ISSUE TITLE
source_ami_filter ignoring owners property

### ISSUE THREAD

**Issue by richardowen** [mitchellh/packer#4232]
It appears that the "owners" property on "source_ami_filter" is not being used when looking for an AMI. I have found this morning that when using "self" in the owners property, it was selecting a public ubuntu AMI. You can see an example in this gist:

https://gist.github.com/richardowen/0e9b1fc89c6234b563e6a9f6a3e137fd

I have "owners": [ "self" ] in the template but the AMI it selects is ami-d1762fa2 which is an official Ubuntu AMI.

I'm not very familiar with the packer code base but it looks like it should be including owner in the DescribeImages params here:

https://github.com/mitchellh/packer/blob/4e1e2c18d5d925ade21b668f565f4228127cdba5/builder/amazon/common/step_source_ami_info.go#L70

Packer version: 0.12.0
Host Platform: macOS 10.12.1 (same behaviour on Ubuntu 16.04)

**Comment by rickard-von-essen** [comment]
Thanks! Looks like there might be something missing here.
