### ISSUE TITLE
Error Building Amazon AMI with Amazon-EBS Builder in Atlas

### ISSUE THREAD

**Issue by brianknight10** [mitchellh/packer#4240]
I have been encountering a consistent error when building Amazon AMIs with the `amazon-ebs` builder using Packer in Atlas using any Packer version greater than or equal to 11.0.

The error occurs when creating the initial security group in AWS to place the EC2 instance in. The process appears to hang on:

`==> amazon-ebs: Authorizing access to port 22 the temporary security group...`

and remains there until the process times out. Note this is before any provisioners even run - it's just at EC2 instance creation by the builder.

If I run the same Packer template in 10.2, the issue does not occur.

- Packer version - 11.0, 11.1, 12.0
- Host platform - Atlas
- Template producing issue - https://gist.github.com/brianknight10/8d7f0cb354b439b0f7633c7c7ebf9e7d

**Comment by rickard-von-essen** [comment]
See #4059 you need to allow `ec2:DescribeSecurityGroup`.

**Comment by brianknight10** [comment]
Thanks @rickard-von-essen - it's `ec2:DescribeSecurityGroups` (with the "s" on the end) based on #4059. That certainly solves the issue.
