### ISSUE TITLE
Dockerfile Provisioner

### ISSUE THREAD

**Issue by caiofbpa** [mitchellh/packer#4250]
We use Docker for development and CI, but we aren't ready to put it in production just yet. We want to use Packer to create AMIs to deploy on AWS.

We already have all steps necessary to provision a machine in our Dockerfile. It would be really nice if Packer could read supported steps (mostly RUN and ADD/COPY) from the Dockerfile and execute them in the provisioning step.

This way we could use Packer to create an AMI based off a Dockerfile.

What do you guys think?

**Comment by mwhooker** [comment]
Thanks for the idea, it's kind of a neat thought.

As for the packer road map, I don't see this as getting added any time soon. We want to move away from very specific provisioners, and focus more on the broader, more general purpose ones like the shell and file provisioners. 

I think a better solution might be a 3rd party tool that could parse the file and execute the changes locally. That way you could call it from the shell provisioner and have it work how you expect.
