### ISSUE TITLE
Packer can't pack AMI with sshd setting MACs hmac-sha2-512,hmac-sha2-256

### ISSUE THREAD

**Issue by 419385600** [mitchellh/packer#4257]
I have been attempting to use Packer to create an AMI based off ami-972f72e4.  When Packer attempts to SSH to the Instance it times out.  If I run the OpenSSH client I can connect to the Instance but Packer cannot.  Looking in the /var/log/secure log, I can see that Packer has opened a number of SSH connections to the Instance and ps -ef shows a number of running sshd processes but Packer itself thinks that the connection has failed.  After lots and lots of testing by manually creating AMIs based off ami-972f72e4, I find that the issue only occures when the base AMI has the following line in /etc/ssh/sshd_config:

MACs hmac-sha2-512,hmac-sha2-256

This was occuring with Packer version 0.10.0.  I have downloaded version 0.12.0 and I get the same result.  I am running the MacOSX 64bit Packer on OSX 15.4.0.

https://gist.github.com/419385600/1214c629eb2bd16204892b485fea49b0

**Comment by rickard-von-essen** [comment]
Duplicates #4076
