### ISSUE TITLE
Unknown configuration key subnetwork - googlecompute

### ISSUE THREAD

**Issue by jrbury** [mitchellh/packer#4259]
Packer Version:
 `Packer v0.12.0`

Host:
`Linux prod-spinnaker-dyvx 4.4.0-51-generic #72~14.04.1-Ubuntu SMP Thu Nov 24 19:22:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Debug logs:
https://gist.github.com/jrbury/33fbc8fb31b62a60901e25efb19ef631

Template:
https://gist.github.com/jrbury/e88dd94a35aa7e25580db18afcd47076

Based on the packer documentation and the code at https://github.com/mitchellh/packer/blob/master/builder/googlecompute/config.go I'm not sure why it's complaining about `subnetwork` being an unknown key. Any help would be greatly appreciated. Let me know if you need more information.

**Comment by mwhooker** [comment]
I think you've got an old version of packer 

`2016/12/06 23:18:32 Starting plugin: /usr/bin/packer-builder-googlecompute []string{"/usr/bin/packer-builder-googlecompute"}`

that's how we used to do things before we compiled the builders into the main packer binary. Let me search around for some instructions but you should be able to delete all the packer- binaries and have it work as expected

**Comment by mwhooker** [comment]
it's on the download page here

`Note: Packer now ships as a single binary. When upgrading from Packer < 0.9.0, you will need to remove the old packer-* plugins from your installation path.`

https://www.packer.io/downloads.html

after doing that it should work

**Comment by jrbury** [comment]
Thanks for the quick response. Once I cleaned my usr/bin directory the template validates and builds correctly.
