### ISSUE TITLE
azure-arm builder and ansible remote provisioner does not work

### ISSUE THREAD

**Issue by rbrutas** [mitchellh/packer#4265]
- Packer version from `packer version` - 0.12.0
- Host platform - centos 7.2 in azure
- Debug log output from `PACKER_LOG=1 packer build template.json` and packer config - 
https://gist.github.com/rbrutas/9d9c38ed9bfeaeb5cb87b546d5c3d023

**Comment by boumenot** [comment]
Is this a dupe of #4263?

**Comment by rbrutas** [comment]
I don't think so, my issue is that packer ansible remote provisioner does't re-use the ssh keypair that asure-arm created when it provisioned the azure vm. I created a new one but it did not update the azure vm.

**Comment by boumenot** [comment]
I do not know how the Ansible provider works, so this is mostly a guess.  The Azure builder generates a key pair at run time if one is not defined by the user.  The builder does not make that key available, but there is nothing that prevents the user for defining an ssh key explicitly.  If the user does, the builder will not auto-create one.  Ansible may respect this too, and use the user supplied key.

See [ssh_private_key_file](https://www.packer.io/docs/templates/communicator.html#ssh_private_key_file) for details.

**Comment by rbrutas** [comment]
that resolves it.. thanks @boumenot
