### ISSUE TITLE
qemu builder: `<wait30s>` trips up the `boot_command` parser/runner

### ISSUE THREAD

**Issue by Coaxial** [mitchellh/packer#4268]
Packer v0.12.0
OS X 10.11.6
Template + log: https://gist.github.com/Coaxial/8acb830fa49edd57f0427148647df8cc

When I run `packer build`, packer misses part of the `boot_command`. Compare [this](https://gist.github.com/Coaxial/8acb830fa49edd57f0427148647df8cc#file-xenial64-json-L25) with [that](https://gist.github.com/Coaxial/8acb830fa49edd57f0427148647df8cc#file-log-log-L182-L185): it's missing several `<waitxxx>` and a few keystrokes.

If I concat the `boot_command` to a single string, then it's even worse: it types the first two `<enter>` and jumps straight to the last `<wait 1200m>`, ignoring anything inbetween.

It seems the `<wait30s>` is problematic, but it is valid according to the doc and it works as expected (most of the time) with the array of strings from the gist. I also tried `<wait0m30s>` and `<wait30>` in the one long string version, but it always trips on it. Replacing it with `<wait10><wait10><wait10>`, although it's tedious, works.

Probably related, once it has skipped a `<wait30s>` instruction, I can't kill packer with <kbd>Ctrl</kbd>+<kbd>c</kbd>:

```
2016/12/08 15:21:33 packer: 2016/12/08 15:21:33 Special code '<enter>' found, replacing with: 65293
2016/12/08 15:21:34 packer: 2016/12/08 15:21:34 Special code '<enter>' found, replacing with: 65293
2016/12/08 15:21:34 packer: 2016/12/08 15:21:34 Special code <wait1200m> found, sleeping
^C2016/12/08 15:26:10 Stopping build: qemu
2016/12/08 15:26:10 Closing stdin because interrupt received.
2016/12/08 15:26:10 packer: 2016/12/08 15:26:10 Received interrupt signal (count: 1). Ignoring.
2016/12/08 15:26:10 packer: 2016/12/08 15:26:10 Qemu stderr: qemu-system-x86_64: terminating on signal 2 from pid 409
2016/12/08 15:26:10 packer: 2016/12/08 15:26:10 Cancelling the step runner...
^C2016/12/08 15:26:10 packer: 2016/12/08 15:26:10 Received interrupt signal (count: 2). Ignoring.
^C2016/12/08 15:26:10 packer: 2016/12/08 15:26:10 Received interrupt signal (count: 3). Ignoring.
^C2016/12/08 15:26:10 packer: 2016/12/08 15:26:10 Received interrupt signal (count: 4). Ignoring.
^C2016/12/08 15:26:10 packer: 2016/12/08 15:26:10 Received interrupt signal (count: 5). Ignoring.
^C2016/12/08 15:26:11 packer: 2016/12/08 15:26:11 Received interrupt signal (count: 6). Ignoring.
^C2016/12/08 15:26:11 packer: 2016/12/08 15:26:11 Received interrupt signal (count: 7). Ignoring.
```

For those stumbling on this issue, the only way to "reset" packer is with this one liner after stopping packer (<kbd>Ctrl</kbd>+<kbd>z</kbd>): `ps x | grep packer | cut -f 1 -d ' ' | head -n 1 | xargs sudo kill -9 && rm -rf output-qemu/`

**Comment by mwhooker** [comment]
definitely something wrong with the regex. see https://play.golang.org/p/WEv5PRR_I0

**Comment by mwhooker** [comment]
the wait regex forces it to match against the end of the line. I'll see if it's just as easy as removing the `$`, but in the mean time you should be able to get away with having one command per line

**Comment by mwhooker** [comment]
@Coaxial would you mind testing the PR I just sent up? Will merge if it works okay for you.
