### ISSUE TITLE
Packer can give misleading errors if IAM permissions are missing

### ISSUE THREAD

**Issue by smitelli** [mitchellh/packer#4277]
* Packer 0.12.0
* Linux (Debian Jessie, amd64)
* `amazon-ebs` builder

I upgraded a packer 0.10.0 installation to 0.12.0, and builds immediately started failing in the following manner:

    12:07:36 amazon-ebs output will be in this color.
    12:07:36 
    12:07:36 ==> amazon-ebs: Prevalidating AMI Name...
    12:07:38     amazon-ebs: Found Image ID: ami-dcb57ebc
    12:07:38 ==> amazon-ebs: Creating temporary keypair: packer_584e9308-d1ec-caf0-15fb-bdf54c66f2ba
    12:07:38 ==> amazon-ebs: Creating temporary security group for this instance...
    12:07:38 ==> amazon-ebs: Authorizing access to port 22 the temporary security group...
    [... hangs for 10 minutes ...]
    12:17:53 ==> amazon-ebs: No volumes to clean up, skipping
    12:17:53 ==> amazon-ebs: Deleting temporary security group...
    12:17:53 ==> amazon-ebs: Deleting temporary keypair...
    12:17:54 Build 'amazon-ebs' errored: Timed out waiting for security group sg-b8e6f2c1
    12:17:54 
    12:17:54 ==> Some builds didn't complete successfully and had errors:
    12:17:54 --> amazon-ebs: Timed out waiting for security group sg-b8e6f2c1
    12:17:54 
    12:17:54 ==> Builds finished but no artifacts were created.

After running around in circles trying to figure out why things broke, it occurred to me that I should check [the docs](https://www.packer.io/docs/builders/amazon.html#using-an-iam-instance-profile) to see if any new IAM permissions needed to be added in my instance profile. Sure enough, I was missing the following:

* `ec2:DeregisterImage`
* `ec2:DescribeImageAttribute`
* `ec2:DescribeRegions`
* `ec2:DescribeSecurityGroups`
* `ec2:DescribeTags`
* `ec2:GetPasswordData`
* `ec2:ModifyInstanceAttribute`

After adding them, the problem went away and my builds succeeded like normal.

I am opening this issue because I believe there is a defect in the error reporting in this scenario. Packer almost certainly receives a permissions error from the AWS API when trying to perform one of its operations, but instead of reporting the error in a way that the user can diagnose, it hangs for ten minutes then aborts with a somewhat misleading error message. Without some hint that the error is caused by missing IAM permissions, it seems quite difficult for a user to find the cause of the problem.

**Comment by mwhooker** [comment]
definitely agree we could do a better job surfacing this error. thanks!

**Comment by dave2** [comment]
https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_run_source_instance.go#L369

I've checked all the other attributes given on the missing list on this issue, and they all handle errors correctly, but the waiter above doesn't. I'll flick a PR to fix it shortly.

**Comment by mwhooker** [comment]
I wonder if there's a way to check what permissions you have so we can check before we run

**Comment by dave2** [comment]
I did consider if we could preflight check the permissions, but quickly found myself in an IAM policy sim rabbit hole. Resource level permissions could give false negatives on access is the main issue I see, it's not immediately clear how the policy sim default resource of "*" would be interpreted given a resource-level permission.

**Comment by codesurf42** [comment]
I am using packer 1.2.4 and still got similar errors about missing IAM permissions (that way I have found this issue), e.g.
```
==> amazon-ebs: Modifying attributes on AMI (ami-67e80000)...
    amazon-ebs: Modifying: users
==> amazon-ebs: Error modify AMI attributes: UnauthorizedOperation: You are not authorized to perform this operation.
==> amazon-ebs: 	status code: 403, request id: 032c86ae-2f73-4140-8fca-9207eb96f0d6
==> amazon-ebs: Deregistering the AMI because cancellation or error...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Error describing volumes: UnauthorizedOperation: You are not authorized to perform this operation.
==> amazon-ebs: 	status code: 403, request id: 56f87547-f8fd-49e6-8d2e-c7c57f5ce05f
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error modify AMI attributes: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id
```
It would easier if packer could just say which AWS IAM permission is missing.

**Comment by elliottb303** [comment]
@codesurf42 did you ever validate this was from missing IAM credentials in an AWS role/policy? From what I can tell, my policy includes all the required permissions, and I still see similar error ( Error ValidatingRegions "

Perhaps related to overall miss on using AWS credentials from env variables?
https://github.com/hashicorp/packer/issues/8036
