### ISSUE TITLE
Run an executable such as script on remote builder types.

### ISSUE THREAD

**Issue by odg0318** [mitchellh/packer#4280]
Hello.
I should create autoscaling group, a feature of AWS, after packer is done.
AMI id is required to do that but there is no way to get it.
I made a plugin that gets image id from artifact and run script with parameters, `builder_type`, `image_id`.
The plugin works fine only when `amazon` or `googlecompute` is used as a builder.
I want this feature is added to packer's default post-processor.

https://github.com/odg0318/packer-post-processor-shell-with-imageid

**Comment by rickard-von-essen** [comment]
You can already use the `manifest` post-processor in combination with `shell-local` post-processor.

**Comment by rickard-von-essen** [comment]
Also the `shell-local` post-processor have been rewritten on master, see #4189.

**Comment by odg0318** [comment]
Yes, I see. I will wait for releasing master version to stable.
Thank you
