### ISSUE TITLE
specify AWS_CONFIG_FILE path

### ISSUE THREAD

**Issue by odg0318** [mitchellh/packer#4281]
Hello.

I think it is better that a path of `AWS_CONFIG_FILE` is specified in template.
Now, the path can be set only via environment variables.
I don't know why this configuration is missing in template and hope that it is added.
This link https://github.com/odg0318/packer/commit/d1207979b75e764300b259f1283b5da7342f707c is sample codes that I did. 

As a diffrent solution, can you provide another way to set environment variable such as in variables of template? I think it is also very good.
```json
{
  "environments": {
     "AWS_CONFIG_FILE": "path/to/aws_config"
  }
}
```

Thank you

**Comment by rickard-von-essen** [comment]
I expect that you can use env var `AWS_CONFIG_FILE`. When #4124 is completed this should mostly work as the [awscli](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html). But we don't plan to add a new option for `AWS_CONFIG_FILE` it's better suited as a env var.

**Comment by odg0318** [comment]
Thank you for your reply.

It is uncomfortable that I should always set env vars every time I build.
`docker-compose` also has a way to write env vars in a template file.
https://docs.docker.com/compose/compose-file/#/environment

What do you think of new section to set env variables in template?
Priority would process it in the following overriding order.
1. env vars on system.
2. en vars on template

**Comment by rickard-von-essen** [comment]
I don't see how that adds value over defining the env var before starting packer. Also it ties the template unnecessarily to the build environment. If it's cumbersome to specify the env var each time put it in `~/.bashrc`, a bash function, a `Makefile`, or switch to a modern shell (like [fish](https://fishshell.com/) 🐟).

**Comment by odg0318** [comment]
Thank you
