### ISSUE TITLE
Cloudstack security groups

### ISSUE THREAD

**Issue by wingZero21** [mitchellh/packer#4287]
Hi,

Can you advise if its currently possible to add security groups to the cloudstack packer builder templates?

Currently I cant see any option on the documentation page that allows for this.

**Comment by mwhooker** [comment]
You can add security groups to the source instance

https://www.packer.io/docs/builders/openstack.html#security_groups

**Comment by rickard-von-essen** [comment]
From reading the docs I believe it's not supported. PR's are welcome.

Ping @svanharmelen

**Comment by svanharmelen** [comment]
@wingZero21 security groups are indeed (currently) not supported. VPC networks using a ACL and Guest networks are supported, but if those aren't options you can use, you could also try this option:

```
use_local_ip_address (boolean) - Set to true to indicate that the provisioners should connect to the local IP address of the instance.
```

So in this case the machine running Packer should be in the same network/security group as where you create the VM to build the template from.

If thing works out, PR's are indeed welcome :wink:

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
