### ISSUE TITLE
qemu builder: boot_command failed to enter text

### ISSUE THREAD

**Issue by skvl** [mitchellh/packer#4291]
#### Description
After `boot_wait` (10s) no input appear in *grub* menu. If I press *<tab>*, then I could see this input:
```
=;//...;/.
```

#### Packer version
Packer v0.12.0

#### Host platform
Linux

#### Log
[Log](https://gist.github.com/skvl/b5d978c1599eec9b915206cb094a9a5b)

#### Build command
```
PACKER_LOG=1 packer build -on-error=ask -parallel=false --only=qemu template.json
```

**Comment by skvl** [comment]
I have tried [this](https://github.com/stardata/packer-centos7-kvm-example) example and it works! I think something bad with my `json` file.

**Comment by rickard-von-essen** [comment]
If you solved it please close, if not could you try with 0.12.1, there where at least one fix for qemu `boot_command`.

**Comment by skvl** [comment]
I really don't understand: I have copied files from example into my project and this doesn't work!

**Comment by skvl** [comment]
It's the same with 0.12.1

**Comment by skvl** [comment]
I think there is some stupid error but I miss it.

**Comment by skvl** [comment]
I have some clue about this! It is something about `"http_directory"` argument.

**Comment by skvl** [comment]
First of all if I have directory named **common** then this appears.

**Comment by mwhooker** [comment]
probably has something to do with these warnings
`Qemu stderr: Warning: no scancode found for keysym 32`

found some information about it here https://bugs.launchpad.net/qemu/+bug/1267520 which mentions the `common` directory issue.

see if you can run it from a directory without a `common` subdirectory

**Comment by skvl** [comment]
Yes, it is working without `common` folder.
