### ISSUE TITLE
Packer 1.12.1 fails to launch openstack instance, but 1.12.0 works

### ISSUE THREAD

**Issue by noroutine** [mitchellh/packer#4299]
Looks like has troubles resolving names to uuids.

- Packer version 1.12.1 (1.12.0 works!)
- Host platform Ubuntu Xenial 16.04
- Error, build.json and debug log output from `PACKER_LOG=1 packer build template.json` are here https://gist.github.com/noroutine/619497f6429e1cc9748cb43fdd269d8d

**Comment by mwhooker** [comment]
Thanks for the report. we updated to a new openstack library which may have impacted this

**Comment by mwhooker** [comment]
@noroutine are you able to test the patch in #4301? Let me know if you have trouble building it and I can send you a binary.

**Comment by noroutine** [comment]
Yip, confirmed - works now perfectly
