### ISSUE TITLE
amazon: Packer don't reconnect to when IP changes

### ISSUE THREAD

**Issue by alter** [mitchellh/packer#4307]
Packer lost connection and doesn't detect new ip after changing instance ip.

```
2016/12/21 11:48:14 machine readable: amazon-ebs,error []string{"Error creating staging directory: dial tcp 54.144.59.1:22: getsockopt: connection refused"}
2016/12/21 11:48:14 ui error: --> amazon-ebs: Error creating staging directory: dial tcp 54.144.59.1:22: getsockopt: connection refused
```

I think Packer should not cache ip for ssh, it have to get ip from instance every time when it needs to reconnect. 
                                                                                                                                                                   
Packer v0.12.1

```
lsb_release -a                                                                                                                                                                      
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

uname -a                                                                                                                                                                            
Linux awork 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

https://gist.github.com/alter/20cd6f16ac4fd4a3b26726aa700de8d3

sample image.json:       
```json                                                                                                                                                               
{
  "builders": [
    {
      "type": "amazon-ebs",
      "associate_public_ip_address": true,
      "source_ami": "ami-5ac2cd4d",
      "ami_name": "packer-test {{timestamp}}"
    }
  ],
  "provisioners": [
    {
        "type": "shell",
        "script": "scripts/awscli_install.sh"
    },
    {
      "type": "file",
      "source": "aws_credentials",
      "destination": "~/.aws/credentials"
    },
    {
        "type": "shell",
        "script": "scripts/aws_setip.sh"
    },
    {
        "type": "puppet-server",
        "options": "--test",
        "puppet_server": "admin-some.host.net",
        "puppet_bin_dir": "/opt/puppetlabs/bin",
        "pause_before": "10s"
    }
  ]
}
```

awscli_install.sh:
```sh
#!/bin/bash
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python-pip
sudo pip install awscli
```

aws_credentials file - file with your aws credentials

scripts/aws_setip.sh:
```bash
#!/bin/bash
aws --region us-east-1 ec2 associate-address --instance-id $(wget -q -O - http://instance-data/latest/meta-data/instance-id) --allocation-id eipalloc-$ID
```

**Comment by alter** [comment]
Also I could describe current situation:
I can't connect to my puppet-server from all IPs, it's  too unsecure.
I've created Elastic IP in AWS, added it to firewall and now I need to assign it to instance, but after IP assignation Packer lost connection.

**Comment by rickard-von-essen** [comment]
Just double checking.. Your Puppet server isn't running in AWS?

**Comment by alter** [comment]
it depends on many factors, it maybe aws, gce, if it aws it maybe another project/region/etc
So, generally I can't connect to it using internal ip, and I can't use only public, but not static IP, b/c it won't be in firewall.

PS: The main idea that if pulic ip of instance has been changed, Packer can't reconnect to it, but Packer has AWS credentials and I think could get current ip of instance.
I think there will be same issue when I'll check Packer with GCE.

**Comment by mwhooker** [comment]
I can see this being an issue, but it's an odd case. I would be willing to look at patches, but I don't think this is something we're going to support at the moment.

I would recommend perhaps creating a NAT gateway so that outgoing internet traffic always comes from the same IP. That should be simpler than the other option with is creating a VPN to your puppet server so you can connect to it using the private IP.
