### ISSUE TITLE
Custom KMS key encrypted root volume + AMI share is not supported, why?

### ISSUE THREAD

**Issue by gupta-abhishek** [mitchellh/packer#4313]
Hey,

I was trying to share an encrypted AMI. But packer fails in pre-validate step. The encrypted AMI is encrypted using custom key, but not default KMS key. So, it should be allowed.

It could be because of https://github.com/mitchellh/packer/commit/d7a7d8c85222b22ba8d140c31d2ded056d14d5cf#diff-5dba49c9dc76437bfbfbd2e93dade275

Repro step:
```
{
"builders": [
"ami_users": "['xxx']",
"encrypt_boot": true,
"kms_key_id": "xxx",
]
}
```

Simply re-adding `len(c.AMIKmsKeyId) == 0`, might solve the issue. 

Can you please fix this?

**Comment by rickard-von-essen** [comment]
It's not possible to share an AMI with a encrypted vol.

**Comment by gupta-abhishek** [comment]
It is possible to share AMI with encrypted volume, as per [AWS docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html) & [blog](https://aws.amazon.com/blogs/security/how-to-create-a-custom-ami-with-encrypted-amazon-ebs-snapshots-and-share-it-with-other-accounts-and-regions/). We just need custom KMS key for that. 

So, can this feature be integrated with packer?

**Comment by rickard-von-essen** [comment]
> It is possible to share AMI with encrypted volume, as per AWS docs & blog

No actually they don't, they talk about sharing encrypted EBS snapshots. For this feature I added `snapshot_users` so you can share snapshots with another account and that in turn can copy the AMI.

**Comment by gupta-abhishek** [comment]
Oh! I wasn't aware of `snapshot_users`. Thanks for pointing me to it.
