### ISSUE TITLE
Hyper-V builder should have ssh_wait_timeout parameter

### ISSUE THREAD

**Issue by dmlb2000** [mitchellh/packer#4314]
- Packer version from 0.12.1
- Host platform: Windows 10
```
PS C:\Users\dmlb2\bento> packer build -only=hyperv-iso centos-7.3-x86_64.json
hyperv-iso output will be in this color.

==> hyperv-iso: Creating temporary directory...
==> hyperv-iso: Downloading or copying ISO
    hyperv-iso: Downloading or copying: http://mirrors.kernel.org/centos/7.3.1611/isos/x86_64/CentOS-7-x86_64-D
so
==> hyperv-iso: Starting HTTP server on port 8540
==> hyperv-iso: Creating switch 'Vagrant Virtual Switch' if required...
==> hyperv-iso:     switch 'Vagrant Virtual Switch' already exists. Will not delete on cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...
==> hyperv-iso: Setting boot drive to os dvd drive C:\Users\dmlb2\bento\packer_cache\72bceadf1983aee393b56af2c5
b470caa03d5109c9ab90dc6f2fe13.iso ...
==> hyperv-iso: Mounting os dvd drive C:\Users\dmlb2\bento\packer_cache\72bceadf1983aee393b56af2c509d174c99b470
9c9ab90dc6f2fe13.iso ...
==> hyperv-iso: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso: Mounting secondary DVD images...
==> hyperv-iso: Configuring vlan...
==> hyperv-iso: Starting the virtual machine...
==> hyperv-iso: Waiting 10s for boot...
==> hyperv-iso: Host IP for the HyperV machine: 192.168.1.10
==> hyperv-iso: Typing the boot command...
==> hyperv-iso: Waiting for SSH to become available...
==> hyperv-iso: Timeout waiting for SSH.
==> hyperv-iso: Clean up os dvd drive...
==> hyperv-iso: Unregistering and deleting virtual machine...
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting temporary directory...
Build 'hyperv-iso' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> hyperv-iso: Timeout waiting for SSH.
```
- The _simplest example template and scripts_ needed to reproduce the bug.
This is using the bento project json templates... seems like there's some more stuff missing there as well since the template doesn't render quite right.
```
{
  "builders": [
    {
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-7.3/ks.cfg<enter><wait>"
      ],
      "boot_wait": "10s",
      "cpu": 2,
      "ram_size": 4096,
      "disk_size": "{{user `disk_size`}}",
      "http_directory": "http",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `mirror`}}/{{user `mirror_directory`}}/{{user `iso_name`}}",
      "output_directory": "packer-{{user `template`}}-hyperv",
      "shutdown_command": "echo 'vagrant' | sudo -S /sbin/halt -h -p",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_username": "vagrant",
      "type": "hyperv-iso",
      "vm_name": "{{ user `template` }}"
    },
```

The original template had the `{{user 'ks_path'}}` template directive which also doesn't seem to work with hyperv.

**Comment by dmlb2000** [comment]
Seems like there's some hard coded values that might need to be parameterized in `builder/hyperv/common/step_polling_installation.go` around line 35.

**Comment by bla-kw** [comment]
Have you checked that the switch is configured properly? I had the same problem with the auto generated switch, when I remember right it was not connected to the host, so ssh could not reach the desired IP. After changing the switch this was no problem any more.

**Comment by dmlb2000** [comment]
I should reference the #4402 pull request here, this took too long so I started making the adjustments.

**Comment by dmlb2000** [comment]
Specifically, this is an issue trying to use the chef/bento packer json files... They currently don't support hyper-v by default but copying the virtualbox-iso profile and ripping out the virtualbox specifics does get you close.

**Comment by mwhooker** [comment]
try
```
{
  "builders": [
    {
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-7.3/ks.cfg<enter><wait>"
      ],
      "boot_wait": "10s",
      "cpu": 2,
      "ram_size": 4096,
      "disk_size": "{{user `disk_size`}}",
      "http_directory": "http",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `mirror`}}/{{user `mirror_directory`}}/{{user `iso_name`}}",
      "output_directory": "packer-{{user `template`}}-hyperv",
      "shutdown_command": "echo 'vagrant' | sudo -S /sbin/halt -h -p",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_username": "vagrant",
      "type": "hyperv-iso",
      "vm_name": "{{ user `template` }}"

      "communicator": "ssh",
      "ssh_timeout": "1h"
    },
```


https://www.packer.io/docs/templates/communicator.html#ssh_timeout

**Comment by ilamurugu** [comment]
Tried with the following and got the error message as 

{
  "builders": [
    {
      "boot_command": [
       "<tab> text inst.ks=hd:fd0:/ks.cfg <enter><wait>"
      ],
      "boot_wait": "10s",
      "cpu": 2,
      "ram_size": 1024,
      "disk_size": 8000,
      "http_directory": "http",
      "iso_url": "c:\\packer_isos\\CentOS-7-x86_64-Minimal-1708.iso",
      "iso_checksum_type": "****************",
      "iso_checksum": "*********************",
      "output_directory": "packer-test-hyperv",
      "shutdown_command": "echo 'vagrant' | sudo -S /sbin/halt -h -p",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_username": "vagrant",
      "type": "hyperv-iso",
      "vm_name": "packer123",
      "communicator": "ssh",
      "ssh_timeout": "1h"
    } ]
	}

Error Message:
C:\>C:\packer21\packer.exe build C:\packer21\hyper-cent.json
hyperv-iso output will be in this color.

==> hyperv-iso: Creating temporary directory...
==> hyperv-iso: Downloading or copying ISO
    hyperv-iso: Downloading or copying: file:///C:/packer_isos/CentOS-7-x86_64-
inimal-1708.iso
==> hyperv-iso: Creating floppy disk...
    hyperv-iso: Copying files flatly from floppy_files
    hyperv-iso: Copying file: c:\packer21\ks.cfg
    hyperv-iso: Done copying files from floppy_files
    hyperv-iso: Collecting paths from floppy_dirs
    hyperv-iso: Resulting paths from floppy_dirs : []
    hyperv-iso: Done copying paths from floppy_dirs
==> hyperv-iso: Creating switch 'internal_vSwitch' if required...
==> hyperv-iso:     switch 'internal_vSwitch' already exists. Will not delete o
 cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...
==> hyperv-iso: Setting boot drive to os dvd drive C:/packer_isos/CentOS-7-x86_
4-Minimal-1708.iso ...
==> hyperv-iso: Mounting os dvd drive C:/packer_isos/CentOS-7-x86_64-Minimal-17
8.iso ...
==> hyperv-iso: Mounting floppy drive...
==> hyperv-iso: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso: Mounting secondary DVD images...
==> hyperv-iso: Configuring vlan...
==> hyperv-iso: Starting the virtual machine...
==> hyperv-iso: Waiting 10s for boot...
==> hyperv-iso: Host IP for the HyperV machine: 169.254.117.27
==> hyperv-iso: Typing the boot command...
==> hyperv-iso: Waiting for SSH to become available...
==> hyperv-iso: Timeout waiting for SSH.
==> hyperv-iso: Cleanup floppy drive...
==> hyperv-iso: Clean up os dvd drive...
==> hyperv-iso: Unregistering and deleting virtual machine...
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting temporary directory...
Build 'hyperv-iso' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> hyperv-iso: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.

Any luck on this?

**Comment by dmlb2000** [comment]
I've not had this issue in a while, I've been able to use the chef/bento repository for a starting point getting packer to build hyperv images.

**Comment by ilamurugu** [comment]
I am trying with Windows image now. let me see if i get the same error message
