### ISSUE TITLE
replace own scp with go package

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#4316]
What do you think about replacing own scp logic to https://github.com/hnakamur/go-scp ?

**Comment by mwhooker** [comment]
would be nice to remove a bunch of code, but not sure it's worth it in this particular case, since our communicator code is relatively stable, and that library says its apis are not frozen yet. Is there any good reason to switch that I'm missing?

**Comment by vtolstov** [comment]
You right, i'm wait for api stabilization.
I think that lib can be more tested and have less bugs then our own implementation that used only with single files (and rare with dirs)

**Comment by mwhooker** [comment]
gonna close this for now. Would be excellent to revisit after 1.0
