### ISSUE TITLE
 virtualbox-windows-iso builder - can't specify same value for http_port_max / http_port_min

### ISSUE THREAD

**Issue by avishnyakov** [mitchellh/packer#4319]
As packer suggests, we can specify same port for both  http_port_max / http_port_min so that we would know the right number while running provisioners. 

>> http_port_min and http_port_max (integer) - These are the minimum and maximum port to use for the HTTP server started to serve the http_directory. Because Packer often runs in parallel, Packer will choose a randomly available port in this range to run the HTTP server. If you want to force the HTTP server to be on one port, make this minimum and maximum port the same. By default the values are 8000 and 9000, respectively.

https://www.packer.io/docs/builders/virtualbox-iso.html

However, the following setup for virtualbox-windows-iso builder gives "* http_port_max must be greater than http_port_min":

```
"http_directory": "./_install/",
"http_port_min" : 8013,
"http_port_max" : 8013
```

The aim is to transfer a huge ISO file into VM. WinRM transfer fails, so trying to expose ISO file via HTTP server - hence need to know the port. As port is dynamic and isn't available via interpolations, trying to get predefined port with the same number for min/max values.
 
- packer version 0.12.0
- win10

**Comment by avishnyakov** [comment]
A workaround if anyone needs it.

Setup ports:
```
"http_port_min" : 8013,
"http_port_max" : 8014
```

That should give random one either 8013/8014, later use the following PS and temporary file '_ping.txt' as following within powershell provisioner. Basically, checking availability on two predefined ports and then downloading required files.
```
cls

$urls = @(
    'http://10.0.2.2:8013',
    'http://10.0.2.2:8014'
)

$targetFolder = "c:/_install"

Write-Host "Creating target folder:[$targetFolder]"
[System.IO.Directory]::CreateDirectory($targetFolder) | out-null

foreach($baseUrl in $urls) {

    $avialableUrl = $false
    $probeUrl = $baseUrl + "/" + "_ping.txt"
       

    Write-Host "Testing URL:[$baseUrl] with probe:[$probeUrl]"

    try{
        $probe = Invoke-WebRequest -Uri  $probeUrl -TimeoutSec 10 -UseBasicParsing
        $avialableUrl = $true
    }
    catch {
        $ErrorMessage = $_.Exception.Message

        Write-Host "Error: [$ErrorMessage]"
        Write-Host $_.Exception

        $avialableUrl = $false
    }

    if($avialableUrl -eq $false) {
         Write-Host "`tIncorrect URL:[$baseUrl]"
         continue
    }

    Write-Host "`tFound correct base URL:[$baseUrl]"

    $files = @(
        'en_sharepoint_server_2013_with_sp1_x64_dvd_3823428.iso'
    )

    Write-Host "Downloading files:[$($files.Count)]"

    foreach($file in $files) {
        $fileUrl = $baseUrl + "/" + $file
        $targetFilePath = [System.IO.Path]::Combine($targetFolder, $file)

        Write-Host "`tDownloading file:[$fileUrl] to [$targetFilePath]"

        # gives out of memory exception on 2G+ files
        #Invoke-WebRequest -Uri $fileUrl -OutFile $targetFilePath

        # remote BITS is not supported
        #Start-BitsTransfer -Source $fileUrl -Destination $targetFilePath
        
        $wc = New-Object System.Net.WebClient
        $wc.DownloadFile($fileUrl,  $targetFilePath)

        Write-Host "`tDownloaded!"
    }

    break
}       
Write-Host "Completed!"
```

Wish there were another way around to transfer huge ISOs into packer VM.

**Comment by rickard-von-essen** [comment]
I think it's actually the docs that are wrong. The port is selected from the range [min_port, max_port).

**Comment by DanHam** [comment]
Due to the problems with the upstream WinRM library, I've been using a similar workaround to upload the VMware tools iso. However, I'm not encountering any issues with setting the min and max http port to the same value; For me this is working exactly as the documentation says it should.

```
      ...
      "http_directory": "http",
      "http_port_min": 8013,
      "http_port_max": 8013,
      ...
```

From the log output (PACKER_LOG=1 packer build windows.json):

```
016/12/26 12:19:58 packer: 2016/12/26 12:19:58 [INFO] Packer version: 0.12.0
2016/12/26 12:19:58 packer: 2016/12/26 12:19:58 Packer Target OS/Arch: darwin amd64
2016/12/26 12:19:58 packer: 2016/12/26 12:19:58 Built with Go Version: go1.7.3
...
2016/12/26 12:20:13 packer: 2016/12/26 12:20:13 Trying port: 8013
2016/12/26 12:20:13 ui: ==> virtualbox-iso: Starting HTTP server on port 8013
...
```

As Rickard points out, the port is (pseudo-randomly) selected from the range [min_port, max_port]. This is done [here](https://github.com/mitchellh/packer/blob/master/common/step_http_server.go#L39) in common/step_http_server.go. 

Long and short, if ```http_port_min``` is the same as ```http_port_max``` then the HTTP server will use that port as the documentation says it should.

> However, the following setup for virtualbox-windows-iso builder gives "* http_port_max must be greater than http_port_min"

@avishnyakov The only error message I could find that was *close* to this was [here](https://github.com/mitchellh/packer/blob/master/common/http_config.go#L30) in common/http_config.go. Could you provide a gist with the Packer log output?

Once implemented #2869 should make hard coding the HTTP port like this unnecessary and we will be able to use the Packer provided HTTP Address and HTTP Port environment variables within our scripts instead... Of course a fix in the upstream WinRM code would be welcome as well!

**Comment by avishnyakov** [comment]
#2869 would be just crazy awesome, indeed. @DanHam, I'll get back early Jan and post more info and logs. Thanks for looking into that.

**Comment by DanHam** [comment]
@avishnyakov Have you been able to reproduce the issue you were having? If so logs would be very welcome.

**Comment by mwhooker** [comment]
hmm, I don't see the words "must be greater than" anywhere in the code. 

I do see this logic, though, which seems correct.

```
	if c.HTTPPortMin > c.HTTPPortMax {
		errs = append(errs,
			errors.New("http_port_min must be less than http_port_max"))
	}
```

Will need more info to reproduce.

**Comment by rickard-von-essen** [comment]
From reading the code every thing looks fine except that the docs are wrong since the options define a range [http_port_min, http_port_max). So to specify exactly port 8000 you need to have http_port_min=8000 and http_port_max=8001.

**Comment by mwhooker** [comment]
I think docs are correct, since if you give, say, 8000/8000, then `if c.HTTPPortMin > c.HTTPPortMax ` in http_config will evaluate to false and no error will be raised. In `common/step_http_server.go:41`, `port_range` will be 0, and so the offset will be 0.

```
httpPort = offset + s.HTTPPortMin
httpAddr = fmt.Sprintf("0.0.0.0:%d", httpPort)
```

httpAddr will be `0.0.0.0:HTTPPortMin`

**Comment by rickard-von-essen** [comment]
Sorry missed that but then having 8000/8000 is the same as 8000/8001 since:
```golang
if portRange > 0 {
	// Intn will panic if portRange == 0, so we do a check.
	offset = uint(rand.Intn(portRange))
}
```
[step_http_server.go#L46-L49](https://github.com/mitchellh/packer/blob/master/common/step_http_server.go#L46-L49)

**Comment by rickard-von-essen** [comment]
I think this should be implemented such that either we do `[http_port_min, http_port_max]` and allow `http_port_min == http_port_max` OR we do `[http_port_min, http_port_max)` and require `http_port_min < http_port_max`.

**Comment by mwhooker** [comment]
IntN(1) will give 0 or 1, so I think 8000/8001 will be either of those two, ie [min, max]. so setting them both to the same value forces it. I think the logic is working as intended.

**Comment by mwhooker** [comment]
an obvious solution would be to change the line to

```
offset = uint(rand.Intn(portRange + 1))
```

**Comment by DanHam** [comment]
>  IntN gives [0, N) so 8000/8001 will be 8000 always.

Good spot! The proposed fix looks good... As an aside, it's slightly weird that they've chosen to use that open interval for IntN - that seems rather counter intuitive to me. Still, there it is in the docs...

>  I think the logic is working as intended.

Aside from that one small bug you've spotted, agreed - the logic matches up with the behaviour promised by the docs. I could never reproduce the reported error here...

**Comment by mwhooker** [comment]
Going to close until we get more info. I think probably the user was using an older version of packer
