### ISSUE TITLE
[amazon-ebs] Reproducable crash during build

### ISSUE THREAD

**Issue by igmar** [mitchellh/packer#4320]
- Packer version from `packer version`

0.12.1

- Host platform

12:05 $ uname -a
Darwin igmar-macb.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

OSX Sierra 10.12.2

- Debug log output from `PACKER_LOG=1 packer build template.json`.

https://gist.github.com/igmar/cd5c0acb8e452f3d488ecac73386dc2a

- The _simplest example template and scripts_ needed to reproduce the bug.

See the above gist. The crash lies in the second value of ami_block_device_mappings : If I leave out the mapping for /dev/sdf, all is fine.

**Comment by rickard-von-essen** [comment]
Duplicates #4303 which has been fixed on master.

**Comment by igmar** [comment]
The same issue indeed.
