### ISSUE TITLE
unknown configuration key: "encrypt_boot" with amazon ebs builder

### ISSUE THREAD

**Issue by jisantuc** [mitchellh/packer#4327]
**Problem**

We have a working packer build template that we'd like to add encrypted boot volumes to. This [looks pretty possible](https://www.packer.io/docs/builders/amazon-ebs.html#encrypt_boot), but it isn't obvious where the `encrypt_boot` configuration key is supposed to go. When I put it in the top level (i.e. at the same level as `name` and `source_ami`) of the json object for a builder, I get `unknown configuration key: "encrypt_boot"`. When I put it in `ami_block_device_mappings` as in this [Medium post](https://medium.com/@scottpgallagher/packer-aws-3e3ec5aecf76#.4wjc6ncpe) packer complains `unknown configuration key: "ami_block_device_mappings[0].encrypt_boot"`

**Question**

Is either of those places supposed to be right? If neither place is right, what is the right place, and why does it look in the docs like `encrypt_boot` is a top-level configuration key for builders?

**Template data**

- Packer version from `packer version`: tested with `Packer v0.12.1` and `Packer v0.12.2.dev (77f878b89cbae1a82b4cd04180c3544ea9234af2+CHANGES)`
- Host platform: Ubuntu 14.04 in a VM
- Debug output / minimal template: I'll fill in if this smells more like bug than user error

**Comment by rickard-von-essen** [comment]
It's a "top level" option. Most likely your install is broken. If you gist a log I can tell.

**Comment by rickard-von-essen** [comment]
Your install is broken. Remove your current install directory and reinstall from [packer.io/downloads](https://www.packer.io/downloads.html). _Be sure to read the **note** about upgrading from < 0.9.0._

**Comment by jisantuc** [comment]
I didn't read down to 0.9.0 or see that note. :man_facepalming:
