### ISSUE TITLE
XML output on screen

### ISSUE THREAD

**Issue by kagarlickijd** [mitchellh/packer#4331]
Hi there, I use
- Packer version: 0.12.1
- Host platform: macOS 10.12.2
- Debug log output: https://gist.github.com/kagarlickijd/de98460697bb4ffd7bcd0f92fc4cc812
- The simplest example template and scripts needed to reproduce the bug: https://github.com/kagarlickijd/packer-demo/tree/win-shutdown

During Windows template build XML output on screen appears - http://prntscr.com/dou48b

**Comment by kagarlickijd** [comment]
@rickard-von-essen bug report has been provided, all details are in first message

**Comment by rickard-von-essen** [comment]
Thank you for providing more information.

**Comment by rickard-von-essen** [comment]
Maybe a duplicate of #4322?

**Comment by kagarlickijd** [comment]
@rickard-von-essen it looks rather similar, but I'm not sure for 100%..
Anyway, I've switched to packer 0.12.0 and it works fine

**Comment by mwhooker** [comment]
dupe
