### ISSUE TITLE
virtualbox in Packer 0.12.1 debug mode on boot_command

### ISSUE THREAD

**Issue by roumano** [mitchellh/packer#4332]
BUGS:

- Packer v0.12.1

In "old" version, in the debug command , it's was asking only once the " Press enter to continue " on StepTypeBootCommand

Like this :  
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'StepRun'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Typing the boot command...
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'StepTypeBootCommand'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Waiting for SSH to become available...

On the last version, we need to press enter for each character on the boot_command :  

==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'StepRun'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Typing the boot command...
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'boot_command[0]: <tab> text ks=http://10.0.2.2:8771/ks-OL7.cfg<enter><wait>'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Pausing after run of step 'StepTypeBootCommand'. Press enter to continue. 
==> ami-OEL-7.2-x86_64-hvm-V2016.12a-edfx: Waiting for SSH to become available...

it's boring 
And (more important) if we type the enter too fast, the previous caractere is used 
so the text "text ks=http..." can be replaced by "tteexxttt ks=htttp..." if we type too fast the enter many time so it's failed to install ...

**Comment by rickard-von-essen** [comment]
Is this per character or line?

**Comment by rickard-von-essen** [comment]
I recommend that you use `-on-error=ask` instead of `-debug` when troubleshooting.

**Comment by roumano** [comment]
it's per character ...
( i note the -on-error=ask )

**Comment by DanHam** [comment]
Pausing between sending of each character with `-debug` was introduced by #3542.

@roumano There are known issues with the Virtualbox code responsible for sending the required characters to the VM console. This is the reason for the repeating characters when pressing enter too quickly - this has nothing to do with Packer per se.

> it's boring

Agreed... and given the repeating characters pretty frustrating too!

Is pausing between each character of the boot command really necessary? Packer outputs a bunch of info about what it's doing here to the log. I could be missing something, but I can't really see the benefit here. Note that this behaviour seems to have been introduced for all relevant builders.

**Comment by DanHam** [comment]
Whoops... Just taken a look at the behaviour of that `-debug` code with the VMware builder and seen how that should actually work - namely pausing between each separate element of the boot command rather than between individual characters...

Clearly Virtualbox is not liking that too much though...

**Comment by roumano** [comment]
Hi  rickard-von-essen ,
i can use the -on-error=ask on virtualbox provisionner, it's better than -debug for my usage.
but it's useless (for me) on amazon as (without -debug) i don't have the ssh key file used (and also don't known the Public IP (or private Ip)

**Comment by rickard-von-essen** [comment]
On Amazon you can use a provided keypair where you have the private key and it's trivial to run a aws cli command to get the IP of instance.

**Comment by DanHam** [comment]
OK. So having seen how `-debug` should have *actually* worked with the VMware builder, implementing the fix for Virtualbox was straight forward - it simply needed the debug conditional moved out of the loop that sends each character, and into the outer loop that sends each complete element of the users boot command.

Dan
