### ISSUE TITLE
Support ignoring a configured builder

### ISSUE THREAD

**Issue by synhershko** [mitchellh/packer#4347]
Heya,

In a case where there are multiple builders defined in a packer.json file, it would be great to allow to execute the packer build with whichever is properly configured. Right now, if I would specify an amazon-eps and an azure builder both in the same file, and one isn't configured (e.g. Azure credentials are missing) the entire run will prematurely stop.

What I'm proposing is a way to either disable a builder on run, prompt the user to continue if one builder fails to initialize but there's at least another one that is ready to run, or automatically do just that (run the configured builders, skip other ones).

This is mostly useful for template case - e.g. one packer.json file that can create an image for a service (say, Elasticsearch on Ubuntu) and then providing ootb support for building it on many environments without requiring the user to setup them all, or to edit the packer.json file before running it.

WDYT?

**Comment by rickard-von-essen** [comment]
See [-only](https://www.packer.io/docs/command-line/build.html#_only_foo_bar_baz).

**Comment by synhershko** [comment]
Oh cool, thanks!
