### ISSUE TITLE
Error getting SSH address: No ip address from HyperV builder

### ISSUE THREAD

**Issue by w9n** [mitchellh/packer#4352]
Hello,

im running the following config on a windows host(MINGW32_NT-6.2 1.0.17(0.48/3/2) 2011-04-24 23:39 i686 Msys) with Packer (version: 0.12.2.dev) and receive `"[DEBUG] Error getting SSH address: No ip address."` in my debug log while the builder dies after 20m waiting for ssh. The VM is manually available via ssh from the host.

Log -> https://gist.github.com/w9n/52d922049682760927f63ecc758fd93a

The Driver gets a valid mac but fails to receive the ip from the vm. Its probably a bug in [hyperv.go](https://github.com/mitchellh/packer/blob/45d4cf8b36b8eb5f57e6eea06f14946d3aa2c56e/common/powershell/hyperv/hyperv.go#L750) but i wasn't able to figure it out yet.

after figuring out the ps script, i guess its arch specific, because the vm does not expose its ip to hyper-v manager.

final thought: Script is fine, but its necessary to have Linux Integration Services (rpm only) running in vm to receive ip-address from Get-Vm. Ill stop my arch experiments on hyperv here :/
 
```json
{
 "variables": {
        "iso_url": "https://mirrors.kernel.org/archlinux/iso/2016.11.01/archlinux-2016.11.01-dual.iso",
        "iso_checksum_url": "https://mirrors.kernel.org/archlinux/iso/2016.11.01/sha1sums.txt",
        "iso_checksum_type": "sha1",
        "ssh_timeout": "20m",
        "country": "US"
    },
   "builders": [
   {
            "type": "hyperv-iso",
            "iso_url": "{{ user `iso_url` }}",
            "iso_checksum_url": "{{ user `iso_checksum_url` }}",
            "iso_checksum_type": "{{ user `iso_checksum_type` }}",
            "http_directory": "srv",
            "boot_wait": "5s",
            "boot_command": [
                "<enter><wait10><wait10><wait10>",
                "/usr/bin/curl -s http://{{ .HTTPIP }}:{{ .HTTPPort }}/enable-ssh.sh | tr -d '\\r' | cat > enable-ssh.sh<enter><wait5>",
                "/usr/bin/bash ./enable-ssh.sh<enter>"
            ],
            "disk_size": 10480,
            "ssh_username": "vagrant",
            "ssh_password": "vagrant",
            "ssh_port": 22,
            "ssh_timeout": "{{ user `ssh_timeout` }}",
        }
   ]
}
```
enable-ssh.sh 
```
#!/usr/bin/env bash

PASSWORD=$(/usr/bin/openssl passwd -crypt 'vagrant')

echo "==> Enabling SSH"
# Vagrant-specific configuration
/usr/bin/useradd --password ${PASSWORD} --comment 'Vagrant User' --create-home --user-group vagrant
echo 'Defaults env_keep += "SSH_AUTH_SOCK"' > /etc/sudoers.d/10_vagrant
echo 'vagrant ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/10_vagrant
/usr/bin/chmod 0440 /etc/sudoers.d/10_vagrant
/usr/bin/systemctl start sshd.service

```

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).

**Comment by w9n** [comment]
updated, sorry for inconvenience

**Comment by rmustard** [comment]
I see the same problem with Windows7 Guest on Hyper-V. (Windows 8 and above work fine).
In Hyper-V Manager there is no IP listed and the process timed out (although it tries to use 127.0.0.1).
Also, using Powershell to query the Network Information of the Hyper-V VMs showed the same thing.  No IP.

FYI: After manually doing windows update for Windows7, the guest OS reported it's IP in Windows Manager.

**Comment by w9n** [comment]
yes, i guess the windows update installs the guest tools which enable hyperv manager to determine the vms ip, do memory ballooning and all the other good stuff. It would be nice if packer does not depend on these "Integration Services" or at least notices the user of the necessity of them.

**Comment by w9n** [comment]
@taliesins An optional functionality for static ip and mac for provisioners would be great! I might dig deeper into vagrant soon, but i didnt see any option in hyperv yet that enables this. 

Maybe some switch magic with build in dhcp and routing or a little proxy vm with guest tools and a private network to the actual vm could solve that, but i dont know if that is out of scoop :)

**Comment by taliesins** [comment]
@w9n I use a PfSense VM for my dhcp, dns, gateway, firewall etc

Great UI. I even run my home router in modem mode and use a PfSense VM as my router.

**Comment by w9n** [comment]
@taliesins PfSense is good, but i think if its only purpose would be to dhcp a static ip to the guest vm and ssh proxy for packer, something like alpine or even smaller would be enough. Compatibility with all guest tools is probably the biggest concern.

**Comment by rmustard** [comment]
If anyone is looking for a workaround for windows 7, I was able to get a fully automated hyper-v build working by SlipStreaming a Windows 7 ISO with the guest integration update.
https://support.microsoft.com/en-us/kb/3071740
I'm assuming you could run windows updating during OS install, but that seems to take forever or never complete.

**Comment by taliesins** [comment]
@w9n can we close this issue and perhaps add a feature request? Maybe one along the lines of specifying mac address and ip address. We would want to do this in multiple builders.

**Comment by JoelBCarter** [comment]
@rmustard  That's an excellent workaround.  Sadly, 6 days later, every one of those links to the Integration Tools that MS supplies is currently broken for me.

**Comment by rmustard** [comment]
@JoelBCarter I had similar problems when working on this before.  Just now, using chrome, I clicked on the link for "All supported x64-based versions of Windows 7" and in the same browser tab it gave me a broken link page.  If I right click and open in a new tab, it sent me to the download page.
