### ISSUE TITLE
chef-solo provisioner 404 on chef_server_url

### ISSUE THREAD

**Issue by Syffs** [mitchellh/packer#4356]
As in title,
```
2017/01/04 20:40:34 ui:     docker: The server returned a HTTP 404. This usually indicates that your chef_server_url is incorrect.
    docker: The server returned a HTTP 404. This usually indicates that your chef_server_url is incorrect.
```

Here are the details
- Packer version
```
[root@server ~]# packer.io -version
0.12.1
```
- Host platform
```
[root@server ~]# cat /etc/*-release
CentOS Linux release 7.3.1611 (Core)
```
- [Debug log output](https://gist.github.com/Syffs/c7093812d474e1b5f3ff3fc5460cae82)

- Reproduce
```
{
	"variables": {
		"chef_recipe": "def::def",
		"docker_tag": "def/def"
	},
	"builders": [{
			"type": "docker",
			"image": "ubuntu",
			"commit": "true"
		}
	],
	"provisioners": [{
			"inline": [
				"apt-get update",
				"apt-get -y install curl"
			],
			"type": "shell"
		}, {
			"type": "chef-solo",
			"prevent_sudo": "true",
			"run_list": [
				"recipe[{{user `chef_recipe`}}]"
			]
		}
	],
	"post-processors": [{
			"type": "docker-tag",
			"repository": "{{user `docker_tag`}}",
			"tag": "0.1"
		}
	]
}
```

**Comment by mwhooker** [comment]
I was able to reproduce. It looks like chef-solo uses an in-memory server called chef-zero, which is why this looks like a chef-server error when it's not. I'm not very familiar with chef any more, so not able to debug this atm. I wonder if forcing an earlier version of chef-solo would fix.

**Comment by Syffs** [comment]
@mwhooker Thanks for looking into this, I'm not familiar enough with chef to debug either... How would you force the version of chef through packer? I can do some testing, but I haven't found anything related in the [doc](https://www.packer.io/docs/provisioners/chef-solo.html)

**Comment by mwhooker** [comment]
alright, I think the issue has something to do with the cookbooks. I was able to build it just fine with

```
{
    "builders": [
        {
            "commit": "true",
            "image": "ubuntu",
            "type": "docker"
        }
    ],
    "post-processors": [
        {
            "repository": "{{user `docker_tag`}}",
            "tag": "0.1",
            "type": "docker-tag"
        }
    ],
    "provisioners": [
        {
            "inline": [
                "apt-get update",
                "apt-get -y install curl"
            ],
            "type": "shell"
        },
        {
            "prevent_sudo": "true",
            "run_list": [
                "recipe[{{user `chef_recipe`}}]"
            ],
            "cookbook_paths": ["./4356/cookbooks"],
            "type": "chef-solo"
        }
    ],
    "variables": {
        "chef_recipe": "ckbk",
        "docker_tag": "def/def"
    }
}
```

where the cookbooks is just https://github.com/fnichol/chef-ckbk installed with librarian-chef. 

check that your recipe exists and that you're installing it correctly and specifying your cookbook_paths correctly.
