### ISSUE TITLE
Google Compute Builder error: ssh_username must be specified

### ISSUE THREAD

**Issue by racingyacht** [mitchellh/packer#4359]
During testing the creation of images on Google Cloud Compute using Packer the following error occurred when running $ packer build packer.json 
Error:
      An ssh_username must be specified
      Note: some builders used to default ssh_username to "root".

**To resolve the issue add the following line to "builder":**

                "ssh_username": "root"

**packer.json file** 
```json
{
  "variables": {
    "git_commit": "",
    "git_branch": "",
    "account_file": "/test/test-xxxxxxx-.json",
    "project_id": "test-container1"
  },
  "builders": [
    {
      "type": "googlecompute",
      "account_file": "{{user `account_file`}}",
      "project_id": "{{user `project_id`}}",
      "source_image": "ubuntu-1404-trusty-v20161213",
      "zone": "us-central1-a",
      "image_name": "redmine-{{timestamp}}-{{user `git_branch`}}-{{user `git_commit`}}",
    }
  ],
  "provisioners": [
    {
      "type": "chef-solo",
      "install_command": "apt-get update && apt-get install -y curl && curl -L https://www.opscode.com/chef/install.sh | {{if .Sudo}}sudo{{end}} bash",
      "cookbook_paths": ["chef/site-cookbooks"],
      "run_list": [
        "recipe[rails-sample]",
        "recipe[rails-sample::user]",
        "recipe[rails-sample::ruby]",
        "recipe[rails-sample::app]"
      ]
    }
  ]
}
```

FOR FEATURES:

Describe the feature you want and your use case _clearly_.

FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version` = 0.12.1
- Host platform - Google Cloud Platform

**Comment by mwhooker** [comment]
can you try adding the `ssh_username` to the builder and see if you get the same error? Please re-open if you do that and it doesn't work.

thanks!
