### ISSUE TITLE
SSH agent forwarding not working

### ISSUE THREAD

**Issue by xrage** [mitchellh/packer#4371]
SSH forwarding enabled according to logs but doesn't seems to be working.

Packer version 0.12.1
Host platform Ubuntu 16.04
Debug log output from PACKER_LOG=1 packer build template.json.
https://gist.github.com/xrage/2468bfde4b2addcb27a1ad5739582279

==> amazon-ebs: Waiting for SSH to become available...
2017/01/06 06:21:30 ui: ==> amazon-ebs: Waiting for SSH to become available...
2017/01/06 06:21:45 packer: 2017/01/06 06:21:45 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 54.162.177.181:22: i/o timeout
2017/01/06 06:21:50 packer: 2017/01/06 06:21:50 [INFO] Attempting SSH connection...
2017/01/06 06:21:50 packer: 2017/01/06 06:21:50 reconnecting to TCP connection for SSH
2017/01/06 06:21:50 packer: 2017/01/06 06:21:50 handshaking with SSH
2017/01/06 06:21:50 packer: 2017/01/06 06:21:50 handshake complete!
2017/01/06 06:21:50 packer: 2017/01/06 06:21:50 opening new ssh session
2017/01/06 06:21:50 packer: 2017/01/06 06:21:50 [INFO] agent forwarding enabled
2017/01/06 06:21:50 ui: ==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Connected to SSH!

ssh-agent running on local machine.

ssh-add -l
2048 SHA256:3dqfwes0X6XW6OuVFhooKfNySWvnUECiUgwIODCAkAM /home/ubuntu/.ssh/xrage_local (RSA)

when i do ssh to remote instance with -A option, this allowed me to pull that private git repo but from packer its giving me permission error.

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by rickard-von-essen** [comment]
This works for me: 

```
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Provisioning with shell script: /var/folders/_t/lsk64yf93xs3slvvtc6b_6mr0000gn/T/packer-shell416182220
    amazon-ebs: SSH_AUTH_SOCK=/tmp/ssh-xDeLRteZ18/agent.3274
    amazon-ebs: SSH_CLIENT='85.224.209.95 60119 22'
    amazon-ebs: SSH_CONNECTION='85.224.209.95 60119 172.31.37.45 22'
    amazon-ebs: SSH_TTY=/dev/pts/0
    amazon-ebs: 2048 d1:42:a8:94:d3:62:12:ff:53:25:8c:77:09:e3:5b:6e /Users/rickard/.ssh/id_rsa-home (RSA)
```

Use the following provisioner to verify your setup:

```json
     {
       "type": "shell",
       "inline": [
         "set | grep -i ssh",
         "ssh-add -l"
       ]
     },
```

Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) to get further help.

See https://www.packer.io/community/

_If you still thinks this is a bug or a feature request please reopen and try to add some more details to make it clearer._
