### ISSUE TITLE
Packer 0.12.1 doesn't work with VirtualBox 5.1.12 (WinRM issue)

### ISSUE THREAD

**Issue by kagarlickijd** [mitchellh/packer#4374]
- Packer version: 0.12.1
- Host platform: macOS 10.12.2 
- Debug log output: https://gist.github.com/kagarlickijd/a24cd51e49fa5471c742240861118b1d
- The _simplest example template and scripts_ needed to reproduce the bug: https://github.com/kagarlickijd/packer-demo/tree/win-shutdown

**Comment by rickard-von-essen** [comment]
Thanks for reporting this. This duplicates #4321 and has been fixed on master and will be in the next release.
