### ISSUE TITLE
openstack: Strange behavior on VMware Integrated OpenStack 

### ISSUE THREAD

**Issue by MethyleneBlu** [mitchellh/packer#4377]
Hello, 

I'm currently working with packer v0.12.1 with the openstack builder but I have a very strange behaviour. I use Openstack Mitaka with VSphere 6 and  build my image using this simple json.

[https://gist.github.com/MethyleneBlu/12fb40b286a1eb400b8e87ea1c372050](https://gist.github.com/MethyleneBlu/12fb40b286a1eb400b8e87ea1c372050)

when I build it, all seems to be good, On the VSphere side, a tempo instance is created, the modifications are done, the OVF snapshot is created, the exportation begins and an image is in "saving" status on the openstack side. BUT when the tempo instance is removed in VSphere, the OVF is removed too and the image in openstack disappears as if the creation was cancelled.

[https://gist.github.com/MethyleneBlu/755de9624d47ac524d0748cda2521044](https://gist.github.com/MethyleneBlu/755de9624d47ac524d0748cda2521044)

Do you know this problem ?

**Comment by rickard-von-essen** [comment]
Never used OpenStack on vSphere but from the logs everything does look fine. Does the image with ID: `f373c842-cd05-4e45-8d06-ae7cfe42041d` exist? Can you launch it? If not it seems to be a bug in _VMware Integrated OpenStack_ since it reports that the image is successfully created.

**Comment by MethyleneBlu** [comment]
Hello,

This ID is the image in "saving" mode which apppears while the OVF is exported from VSphere to Openstack, so technically yes it exists during the process, but it's never become available and is removed when the build ends.

**Comment by rickard-von-essen** [comment]
As I see it there is two alternatives:

1. You can create an instance from the image created by Packer ->  there is no error. 
2. The image is not created even though VMware reports that -> this is an issue with VMware Integrated OpenStack. 

Or should I misunderstand your problem? Then try to add more details and clarify.

**Comment by MethyleneBlu** [comment]
It's a little different, but maybe it's a grammar problem:
I cannot create an instance in openstack. A VM is created in VMWare during the process of building, this VM is modified and an OVF is created, and after that, the VM is deleted.

On the openstack side, an image (not an instance) is defined as "saving" (corresponding to the importation period of the OVF) but it looks like the importation of the OVF never ends with success. However for Packer the importation finishes with success.

I don't really know the exact behaviour of Packer but if I've understood right, the VM and the OVF created by the building process are deleted **after** the success of the importation, right ? in my case it looks like the OVF and the VM are removed before the end of the effective importation.

**Comment by dave2** [comment]
Image creation from an instance is done using Nova's create image API, which is what Packer uses to create the image of the instance. After the image exists, Packer deletes the source instance, which should not destroy the image created from it. OpenStack w/KVM definitely does not, and it's the reference implementation. 

It sounds like VIO does, which is rather unfortunate. This is not something Packer can control, as all it's doing is asking Nova to create an image, and then Nova to delete the instance. It doesn't know about any intermediate copies made in that process of creating an image, that's all hidden under the Nova create image API. So no, packer is not deleting any OVFs created as part of the image creation process.

A quick test would be to see if the same steps as packer is performing keeps the image or destroys it. I would try creating a new instance from a normal openstack CLI, stopping it, creating an image from it, and then deleting the source instance. Note: I don't know if VIO ships with a modified openstack CLI tool, if it does I would test it without using their modified version.

**Comment by MethyleneBlu** [comment]
Aaaah ok, so it's how it works, it explains many things considering the snapshot management has several problems with snapshots. I tried to create an image from an instance manually : the problem occures when I do a snapshot on the VM :

# openstack server create --image 39387358-1455-46a5-8bf4-efe3b0c54ac2 --flavor Tiny_Linux --nic net-id=FO-NIC myinstance
# openstack server list
# nova stop d39c4c42-38f0-4036-a28a-2665b982d7d0
# nova image-create --poll myinstance mysnapshot

result : A snapshot is created, then the snapshot is deleted and the associated instance too.

Great. So it's a problem with Openstack Mitaka !

Ok, I'll see it with Openstack so. Thank you very much for your help and your explanations. :)
