### ISSUE TITLE
vmware-iso giving ssh timeout error

### ISSUE THREAD

**Issue by shyam2j** [mitchellh/packer#4392]
Hi,

When using vmware-iso option to build template in ESX machine machine I am getting SSH timeout error. When put on debug mode this is the error I am getting 

2017/01/03 07:02:51 packer.exe: 2017/01/03 07:02:51 [DEBUG] Error getting SSH address: EOF
2017/01/03 07:02:56 packer.exe: 2017/01/03 07:02:56 opening new ssh session
2017/01/03 07:02:56 packer.exe: 2017/01/03 07:02:56 starting remote command: esxcli --formatter csv network vm list

I see VM getting created and its stuck at the language prompt after the boot keystrokes went in. 
I tried to run the "esxcli --formatter csv network vm list" manually and no output is produced.

Below is the JSON file

```json
{
    "variables": {
        "username": "packer",
        "password": "packer",
        "hostname": "packertest",
        "vm_name": "packertest",
        "ssh_wait_timeout": "30s"
    },
    "builders": [
        {
            "type": "vmware-iso",
	    "http_directory" : "preseeds",
            "http_port_min" : 9001,
            "http_port_max" : 9001,
            "boot_command": [
                "<esc><esc><enter><wait>",
                "/install/vmlinuz noapic ",
                "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
                "debian-installer=en_GB auto locale=en_GB kbd-chooser/method=gb ",
                "hostname={{ user `hostname` }} ",
                "fb=false debconf/frontend=noninteractive ",
                "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=GB ",
                "keyboard-configuration/variant=GB console-setup/ask_detect=false ",
                "initrd=/install/initrd.gz -- <enter>"
            ],
            "http_directory": "preseed",
            "headless": "false",
            "guest_os_type": "ubuntu-64",
            "iso_checksum": "17643C29E3C4609818F26BECF76D29A3",
            "iso_checksum_type": "md5",
            "iso_url": "ubuntu-16.04.1-desktop-amd64.iso",
            "name": "{{ user `vm_name` }}",
            "ssh_username": "{{ user `username` }}",
            "ssh_password": "{{ user `password` }}",
            "ssh_wait_timeout": "{{user `ssh_wait_timeout`}}",
            "shutdown_command": "echo '{{ user `username` }}' | sudo -S shutdown -P now",
            "vm_name": "{{ user `vm_name` }}",
            "tools_upload_flavor": "linux",
            "remote_datastore": "xxxxx",
            "remote_host": "10.xxxxx",
            "remote_password": "xxxxx",
            "remote_type": "esx5",
            "remote_username": "root"
        }
    ]
}   
```

- Packer version 0.11.0
- Host RHEL 6
 
Please advise 
Thanks in advance

Shyam

**Comment by rickard-von-essen** [comment]
Please upgrade to latest version 0.12.1 and reopen if you can reproduce with that and supply:

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template *AND SCRIPTS*_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

Hint: you need a longer `ssh_wait_timeout`, stick with the default `10m`.

**Comment by shyam2j** [comment]
Hi Rickard,

Upgraded to latest 0.12.1 and still getting same error repeating. Sorry dont have access to gist to upload. 

2017/01/16 23:42:01 packer.exe: 2017/01/16 23:42:01 [DEBUG] Error getting SSH address: EOF
2017/01/16 23:42:06 packer.exe: 2017/01/16 23:42:06 opening new ssh session
2017/01/16 23:42:06 packer.exe: 2017/01/16 23:42:06 starting remote command: esxcli --formatter csv
network vm list
2017/01/16 23:42:06 packer.exe: 2017/01/16 23:42:06 [DEBUG] Error getting SSH address: EOF
2017/01/16 23:42:11 packer.exe: 2017/01/16 23:42:11 opening new ssh session
2017/01/16 23:42:11 packer.exe: 2017/01/16 23:42:11 starting remote command: esxcli --formatter csv
network vm list


Thanks in advance
Shyam

**Comment by rickard-von-essen** [comment]
Did you follow my advice about `ssh_wait_timeout`?

> Sorry dont have access to gist to upload.

Since you have a GitHub account you have access to gist. 

Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
