### ISSUE TITLE
vmware-vmx gives no file found error

### ISSUE THREAD

**Issue by shyam2j** [mitchellh/packer#4393]
Hi,

I am using a simple vmware-vmx JSON file used for build. But getting the below error in debug mode. Do I need to add more parameters for the template to work?

2017/01/13 14:45:51 ui: scan err: unexpected newline
Build 'vmware-vmx' errored: VMware error: Error: A file was not found
2017/01/13 14:45:51 ui error: Build 'vmware-vmx' errored: VMware error: Error: A file was not found

2017/01/13 14:45:51 Waiting on builds to complete...
2017/01/13 14:45:51 Builds completed. Waiting on interrupt barrier...
2017/01/13 14:45:51 machine readable: error-count []string{"1"}
2017/01/13 14:45:51 ui error:
==> Some builds didn't complete successfully and had errors:
2017/01/13 14:45:51 machine readable: vmware-vmx,error []string{"VMware error: Error: A file was not
 found"}
2017/01/13 14:45:51 ui error: --> vmware-vmx: VMware error: Error: A file was not found
2017/01/13 14:45:51 ui:
==> Builds finished but no artifacts were created.

This is the JSON used
```json
{
"builders": [{
  "type": "vmware-vmx",
  "source_path": "RHEL6_X64_BASEOS.vmx",
  "ssh_username": "root",
  "ssh_password": "packer",
  "shutdown_command": "shutdown -P now"
}]
}
```

- Packer version 0.12.0
- Host platform: Windows 7 desktop

Please advise
Thanks in advance

Shyam

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by shyam2j** [comment]
Hi Rickard,

Im using the same template which is mentioned as a working template in the Packer vmware-vmx build page. Do I need a licensed version of vmware workstation for this to work? I am using a eval copy.

Thanks
Shyam

**Comment by rickard-von-essen** [comment]
I think it should work since the evaluations are full versions. But I might be wrong. Check VMwares docs about any limitations on evaluation copies.

**Comment by rubin55** [comment]
I'm actually running into exactly the same issue, but with the vmware-iso builder: example.json (taken almost litterally from the packer examples on the VMware builder section):

```
{
  "builders": [{
  "type": "vmware-iso",
  "iso_url": "https://files.devuan.org/devuan_jessie_beta/devuan_jessie_1.0.0-beta2_amd64_NETINST.iso",
  "iso_checksum": "ecb8057317bf8131885c6bc5c8981fd1fb259fd002fb5f145c8be15ac96d0983",
  "iso_checksum_type": "sha256",
  "ssh_username": "packer",
  "shutdown_command": "shutdown -P now"
  }]
}
```

packer validate example.json returns OK. I then run `packer build`:

```
==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: https://files.devuan.org/devuan_jessie_beta/devuan_jessie_1.0.0-beta2_amd64_NETINST.iso
    vmware-iso: Download progress: 100%
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Error starting VM: VMware error: Error: Cannot open VM: C:\Users\rubin\Dropbox\Source\Rubin\packer-zone\output-vmware-iso\packer-vmware-iso.vmx, Cannot read the virtual machine configuration file
==> vmware-iso: Waiting 4.5156999s to give VMware time to clean up...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error starting VM: VMware error: Error: Cannot open VM: C:\Users\rubin\Dropbox\Source\Rubin\packer-zone\output-vmware-iso\packer-vmware-iso.vmx, Cannot read the virtual machine configuration file

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error starting VM: VMware error: Error: Cannot open VM: C:\Users\rubin\Dropbox\Source\Rubin\packer-zone\output-vmware-iso\packer-vmware-iso.vmx, Cannot read the virtual machine configuration file
```

It seems packer really does not create the VMX file: how can one debug this?

**Comment by rubin55** [comment]
Note: After running the exact same string of commands with exactly the same json template, I am unable to reproduce.. It feels like a race condition having to do with VMX file creation and locking on the resulting file, but I can't prove that!

**Comment by steakknife** [comment]
>>>> For future reference, it can indicate VMware had a parse problem with the .vmx. Check your configs carefully.
