### ISSUE TITLE
Issues with WINRM on Windows Server 2016

### ISSUE THREAD

**Issue by beaudryj** [mitchellh/packer#4396]
I have been banging my head at the wall trying to spin up a box using  Packer 0.12.1 on Windows Server 2016 trying to spin up a VBOX image and it seems to keep getting stuck on WINRM connection. 

### Steps taken 
Modified my json with winrm_port and set to 5985 

changed up my winrm script to be inline with the on defined in here https://github.com/mitchellh/packer/issues/3820

I changed all of my shutdown script calls from `"shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"` to `"shutdown_command": "C:/Windows/packer/PackerShutdown.bat",` 

I ran my build in GUI mode and the machine does come up and the scripts run but it just seems like packer can't see it.

**Comment by rickard-von-essen** [comment]
Thank you for reporting this. This duplicates #4321 which is fixed on master.
