### ISSUE TITLE
Amazon-ebs not using iam instance profile

### ISSUE THREAD

**Issue by JChrist** [mitchellh/packer#4405]
Hello.
I am using packer 0.12.0, running inside an Ubuntu 14.04 docker container, with an amazon-ebs builder.
I need packer builder to start an ec2 instance with a specific IAM instance profile, containing an IAM role that I need to be present for the build process.
However, the ec2 instance that is started does not have that IAM profile (or its associated role) assigned.
The sample template I am using is.

    {
      "variables": {
        "aws_access_key_id": "{{env `AWS_ACCESS_KEY`}}",
        "aws_secret_key": "{{env `AWS_SECRET_KEY`}}",
        "aws_region": "{{env `AWS_REGION`}}",
        "ssh_username": "{{env `SSH_USER`}}",
        "ssh_password": "{{env `SSH_PASS`}}",
        "ssh_host": "{{env `SSH_HOST`}}",
        "ssh_port": "{{env `SSH_PORT`}}",
        "iam_instance_profile_name": "{{env `IAM_INSTANCE_PROFILE`}}",
        "user_home": "{{env `HOME`}}",
        "environment": "{{env `ENV`}}"
      },
      "builders": [
        {
          "name": "my_app_aws",
          "type": "amazon-ebs",
          "access_key": "{{user `aws_access_key_id`}}",
          "secret_key": "{{user `aws_secret_key`}}",
          "region": "{{user `aws_region`}}",
          "iam_instance_profile": "{{user `iam_instance_profile_name`}}",
          "instance_type": "t2.small",
          "source_ami_filter": {
            "filters": {
              "virtualization-type": "hvm",
              "name": "*ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server*",
              "root-device-type": "ebs"
            },
            "owners": [
              "099720109477"
            ],
            "most_recent": true
          },
          "ssh_username": "ubuntu",
          "ami_name": "my-app-{{user `environment`}} {{timestamp}}"
        }
      ]
    }

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by JChrist** [comment]
Hi @rickard-von-essen! Thanks for your response.
You can find the requested gist [here](https://gist.github.com/JChrist/297d906e271c2b5e38874a0b092615fe)

**Comment by rickard-von-essen** [comment]
Is this really the name of the instance profile you want to use `ubuntu-packer-packerBuilderIamInstanceProfile-1EEJ4BZ3CR90W`?

**Comment by JChrist** [comment]
Yes, this gets created from aws cloudformation cli (from json template).
If I launch an ec2 instance manually and attach this profile (role as console puts it), it is correctly attached.

**Comment by mwhooker** [comment]
could you paste the output of `aws iam get-instance-profile --instance-profile-name ubuntu-packer-packerBuilderIamInstanceProfile-1EEJ4BZ3CR90W` ?

**Comment by JChrist** [comment]
Hi again and thank you very much for looking into this. I finally found a series of issues related to my problem, none of which is related to packer, which does its job perfectly. More specifically, the error was related to the service version (s3fs 1.79 had issues on start, fixed by 1.80). I haven't found why the the role did not appear in the console, which led me to falsely believe it was not assigned, i suspect iam permission issue. All in all, we can close this as invalid. Thank you very much for your help!

**Comment by mwhooker** [comment]
👍
