### ISSUE TITLE
builder/vmware: Add support for ip command

### ISSUE THREAD

**Issue by externl** [mitchellh/packer#4406]
Currently, packer only supports the `ipconfig` command to determine the ip. Several newer Linux distros do not ship with this, but instead use `ip`. 

It would be great it packer also supported the `ip` command.

**Comment by rickard-von-essen** [comment]
A little bit more context would be nice. 

But I'll guess this request is about VMware builder on Linux where `ifconfig` could be replaced with `ip a`. 

(Similar code is used in the Parallels builder but to my knowledge macOS always ships with ifconfig.)

**Comment by externl** [comment]
Sorry, I was definitely a little vague. You guessed right. I use a VMware builder on Linux platform which doesn't have `ipconfig` and instead you typically use `ip a`.

**Comment by rickard-von-essen** [comment]
@externl please test #4411

**Comment by externl** [comment]
All good! Thanks!
