### ISSUE TITLE
Mac OSX Sierra Runtime Issues

### ISSUE THREAD

**Issue by jbornemann** [mitchellh/packer#4413]
Downloading, and installing a fresh install of v0.12.1 from the Packer website yields several variations failure on Mac OSX Sierra. An example debug output is below.   

Example: https://gist.github.com/jbornemann/22edf1259a045136828c1a03e4855c5e

I've also seen it fail on machine image copy. 

I noticed that it seems the binary is compiled against some very old Go runtime libraries. (v1.4.2) When I build from source against Go 1.7.3 the issues go away. Could there be something wrong with this provided build?

**Comment by rickard-von-essen** [comment]
Your install is broken. Remove your current install directory and reinstall from [packer.io/downloads](https://www.packer.io/downloads.html). _Be sure to read the **note** about upgrading from < 0.9.0._
