### ISSUE TITLE
builder/hyperv: shutdown command shouldn't hang

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#4435]
There was an issue open against parallels/vmware that showed the build hanging when using sysprep to shut down. See #4134 and #4433 for context.

The same behavior might exist in hyper-v, and we need to fix it if it does. cc @taliesins

**Comment by ebjornset** [comment]
@mwhooker I ran into this issue when testing #4664 on Windows 10, using an .iso that I downloaded from MSDN, so the issue i\exists int he hyperv-builder as well. 

Commenting out the cmd.Wait() ...\go\src\github.com\mitchellh\packer\builder\hyperv\common\step_shutdown.go fixed the problem on my machine.

**Comment by mwhooker** [comment]
@ebjornset thanks for following up!
