### ISSUE TITLE
environment variable assignment inside shell script not working

### ISSUE THREAD

**Issue by techytech007** [mitchellh/packer#4437]
I am setting environment variable inside provisioners to access the variables inside shell script for virtual box image.
"provisioners": [
"type": "shell", 
"execute_command": "echo '{{user ssh_pass}}' | {{.Vars}} sudo -S -E bash '{{.Path}}'", 
"environment_vars":[
   "USER_A={{user m_u}}", 
    "PASSWD_A={{user m_p}}"
 ], 
"script":  
    "scripts/myscript.sh"

My problem is that, what is correct notation to assign USER_A inside myscript.sh ? I need these variables to be assigned at some place. Somehow I am not able to obtain the USER_A and PASSWD_A value inside myscript.sh.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
I'll try to give you an answer on SO soon.

**Comment by DanHam** [comment]
Set up the variables you want to use:

```
  "variables": {
    "my_user": "foouser",
    "my_pass": "password"
  },
```

I always put my `variables` section at the top of my template for convenience. Once done you should be able to reference your variables in the provisioner section as below.

```
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "...",
      "environment_vars": [
        "MYUSER={{user `my_user`}}",
        "MYPASS={{user `my_pass`}}",
      ],
      "scripts": [
          ...
      ]
    }
  ]
```

Note the use of backticks (not single quotes) in ```{{user `my_user`}}```. You should now be able to access the variables as ${MYUSER} and ${MYPASS} from within your shell script (assuming Bash).

**Comment by DanHam** [comment]
@rickard-von-essen Oops - sorry. Busy typing and missed your comment!
