### ISSUE TITLE
Failed to parse template:: no such file or directory

### ISSUE THREAD

**Issue by smithah-c** [mitchellh/packer#4442]
Command issued: packer build -only=virtualbox-iso application-server.json

error: Failed to parse template: open application-server.json: no such file or directory

**Comment by smithah-c** [comment]
git clone http://github.com/<account-name>/devops-intro-project devops, replacing <account-name> with your GitHub username

**Comment by mwhooker** [comment]
can you type `file application-server.json`? If you get `f: cannot open \`application-server.json\' (No such file or directory)`, then you're in the wrong directory.

You need to pass the path to the `application-server.json` file, which should be relative to your current working directory.
