### ISSUE TITLE
[RFC] template functions that are guaranteed unique and equals during same run

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#4446]
There are two issues that describe similar but separate issues around using the `{{timestamp}}` template function

* #3958
* #4136

The first one is about the timestamp not having small enough resolution to produce unique ami names during sequential provisioner runs.

The second one is about wanting to have an ID that is the same between builders and provisioners.

### clarify docs instructing users not to use timestamp for uniqueness, and instead use UUIDs

A possible problem with that approach is a uuid is 36 characters long, compared to a timestamp's 10. aws tag value limits are 255 characters.

### increase `timestamp` resolution to milliseconds or more

will probably break existing behavior

### introduce a `run_id` template function which returns the `PACKER_RUN_UUID` value

seems useful but I'm lacking concrete use cases.

## summary

I'm leaning more towards clarifying the docs and possibly creating a `run_id` function.

**Comment by rickard-von-essen** [comment]
You could also create a `timstampmillis` templating function not to break BC.

**Comment by mwhooker** [comment]
I think my solution will be to document using `{{uuid}}` for unique IDs, and using `{{env "PACKER_RUN_ID"}}` for consistent-across-builders IDs

**Comment by mwhooker** [comment]
Not going to document using `PACKER_RUN_UUID` just yet, since it's kind of a power user thing. Will open a ticket and close it for post-1.0
