### ISSUE TITLE
[feature request] builder/file interpolation of user variables

### ISSUE THREAD

**Issue by shantanugadgil** [mitchellh/packer#4451]
What I want to do is generate a json from a template and then upload the generated json to a remote server (using file upload).

This is what I have tried so far:

I have a variable block which initializes a variable named "myvar"

```
"variables": {
  "myvar": "foo"
},
```

... and in the builders' block:

```
{
  "type": "file",
  "content": "{{ user `myvar`}}",
  "target": "cooked.json"
}
```
* This turns out fine, my "cooked.json" contains only "foo".
```
# cat cooked.json
foo
```

What I want to do is, use a "cooked.json.tmpl" as source, interpolate the user variable "myvar" within the template, and then generate the "cooked.json"

Like this:
```
{
  "type": "file",
  "source": "cooked.json.tmpl",
  "target": "cooked.json"
}
```

The cooked.json.tmpl would look something like:
```
{
        "node_name": "{{user `myvar`}}"
}
```

- Packer version from `packer version`: 0.12.2
- Host platform: CentOS 7.3

Is this possible?
_I have pored over the file builder section but have not found any mention of interpolation._

Thanks and Regards,
Shantanu

**Comment by mwhooker** [comment]
to summarize, using file builder with `source` doesn't parse template variables/functions, whereas it does if you use `content` it does.

it seems like this behavior should be consistent, but then again the file builder is more of a debug utility than a template compiler. Leaving this open for now in case anyone wants to work on it, but I'm not sure it'll make it in by 1.0

**Comment by mwhooker** [comment]
In the meantime, I suggest using an existing templating tool.

**Comment by tb3088** [comment]
it would probably help clarify if the OP would replace the incorrect reference to "foo" with "myvar" as the latter is the variable, not "foo" which is the value.

**Comment by shantanugadgil** [comment]
thanks @tb3088 fixed the description errors.

**Comment by shantanugadgil** [comment]
@mwhooker just wondering what would be the probable release date of 1.0 considering it is only 0.12.2 now.

Also was wondering if the template rendering similar to Terraform could be integrated into Packer?

Thanks and Reagrds,
Shantanu

**Comment by mwhooker** [comment]
@shantanugadgil Within a couple of months. We're definitely considering stuff like that for after 1.0, but no firm plans

**Comment by shantanugadgil** [comment]
@mwhooker  Thanks!

**Comment by mwhooker** [comment]
tracking in meta issue
