### ISSUE TITLE
* unknown configuration key: "image_password" in 1&1 builder

### ISSUE THREAD

**Issue by jorgelon** [mitchellh/packer#4454]
Seems the image_password setting doesn't work

- Packer version 0.12.2
- Host platform: 1&1 builder
- ERROR
packer validate 1and1.json
* unknown configuration key: "image_password"

The settings

```json 
{
 " builders": [
    {
         "type":"oneandone",
         "token": "ommitted",
         "disk_size":"30",
         "image_name":"testpacker",
         "data_center_name": "ES",
         "source_image_name":"ubuntu1604-64min",
         "ssh_username" :"root",
         "communicator": "none",
         "image_password": "whatever"
   } 
 ]
} 
```

**Comment by jasminSPC** [comment]
@jorgelon Sorry for the inconvenience the documentation seems to be off. "image_password" is no longer used but builtin "ssh_password"

**Comment by rickard-von-essen** [comment]
Actually the change looks like it's removing the wrong key from the docs?

**Comment by jorgelon** [comment]
the images deployed in 1and1 give you a random password if you doesn't set one. I can't see a way to give a password to the image via packer or to get the randomly generated one, so i think there is no way to ssh it.

**Comment by jasminSPC** [comment]
You can use "ssh_password" for that purpose. Its value will be set as image password on 1and1 server.
