### ISSUE TITLE
Is it possible to run the virtualbox-ovf builder remotely, let's say, on an AWS EC2 instance?

### ISSUE THREAD

**Issue by djvdorp** [mitchellh/packer#4469]
This might be a stupid question but I couldn't directly find the answer in the Docs, hence I am trying my luck here. I am using both the `virtualbox-ovf` and `amazon-ebs` builders for a while. However, running the `virtualbox-ovf` on my local machine uses a lot of CPU and Disk I/O, so that is not really ideal. So I recently wondered if it would be possible to use the same `packer build` command with the `packer.json` I use for my local `virtualbox-ovf` build (that has a `vagrant` post-processor) on a remote server, let's say, an AWS EC2 instance, and if so, how would one achieve that? Use `packer` to run `packer` remotely sounds like a bit of inception and overkill at the same time, and maybe I am just overthinking this? Any tips/advise or similar use cases from other? Any help will be greatly appreciated, thanks in advance!

**Comment by rickard-von-essen** [comment]
In general cloud providers don't support nested virtualisation. 

You could just remote exec (`ssh`) run packer on a bare metal server or a VM with nested virtualisation enabled. There is nothing special in packer for this.

**Comment by rickard-von-essen** [comment]
And of course you can build your VirtualBox Vagrant boxes on [HashiCorps Atlas](https://www.hashicorp.com/atlas.html).
