### ISSUE TITLE
ui.Ask only allows for single words, not whole line

### ISSUE THREAD

**Issue by ashb** [mitchellh/packer#4474]
This was slightly counter to my expectation when writing a custom packer plugin: `ui.Ask(prompt)` will return an error if the line has spaces in it -- this is because `fmt.Fsanln` doesn't scan for whole lines, but for line separated tokens.

Here's an example of the underlying problem with using fmt.Fscanln ([run it in go playground](https://play.golang.org/p/1RYXdtPSbk)):

```
package main

import (
	"fmt"
	"strings"
)

func main() {
	r := strings.NewReader("line with spaces\n")
	var line string
	n, err := fmt.Fscanln(r, &line)
	fmt.Printf("%+v %q %q\n", n, err, line)
}
```

The output is `n=1 err="expected newline" line="line"`

Using something like [`bufio.Scanner`](https://godoc.org/bufio#Scanner) would fix this, and I think could be made backwards in compatible fashion if BasicUI.Ask created a buffered reader on demand -- as nothing else in packer itself accesses this directly (and external plugins are limited via RPC so can't).

If this fix seems sensible I'll happily open a PR for it.

**Comment by mwhooker** [comment]
yeah, seems like that change would make sense. Will happily look at any PRs
