### ISSUE TITLE
Inconsistent handling of quoted command line var parameters for Powershell provisioner

### ISSUE THREAD

**Issue by robumberger** [mitchellh/packer#4478]
I'm not sure if this is an issue with Spinnaker shell configuration when running Packer or with Packer itself. I've added support in Spinnaker to bake Windows images and am capturing the debug output from Packer as part of the bake log.

When Spinnaker generates the Packer command line and adds env parameters where the value has multiple words in them,  the command line parameter is added like this:
    -var packages="googlechrome javaruntime"

The issue arises when the Powershell provisioner generates the encodedCommand. Instead of generating the powershell command line with a single set of quotes, it wraps the existing quoted string in additional quotes. For example, instead of this:
    $env:packages="googlechrome javaruntime";

it generating this:
    $env:packages=""googlechrome javaruntime"";

This is incorrect and causes powershell to fail while parsing it's command line.

In the gist below, I've added the full debug output from Packer when running both from the command line and from when invoked by Spinnaker.

Gist with inputs and outputs: https://gist.github.com/robumberger/43c7ca5c62a1d2a5283106682bbb5c13

Packer version: Packer v0.12.1

Host platform:
    ubuntu@spinnaker:~/transfer$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.5 LTS
    Release:        14.04
    Codename:       trusty

**Comment by rickard-von-essen** [comment]
Seems like a Spinnaker issue to me.

**Comment by DanHam** [comment]
I've had a quick look at this and agree with Rickard. As you yourself have shown, invoking Packer directly with the given arguments/variables seems to give the desired behaviour.

I'm not at all familiar with Spinnaker so this may not be possible, but it seems the simplest work around for this would be to delimit your package list with something other than spaces and adjust your package install script accordingly e.g.

Within your Spinnaker config somewhere:
```
packages=googlechrome,javaruntime
```

... and change [this line](https://gist.github.com/robumberger/43c7ca5c62a1d2a5283106682bbb5c13#file-windows-install-packages-ps1-L5) of your install script to something like:

```
$packages = $env:packages.split(',')
```

**Comment by robumberger** [comment]
Agree this could be a Spinnaker issue and work arounds can be done, but the issue seems to be the way packer is handling it's command line. The  command line I tested is 100% the same (minus the PACKER_LOG=1) as what Spinnaker uses when running Packer (I grabbed it using `ps -ef | grep packer`). From everything I can tell, the only difference is that Spinnaker is running Packer in a non-interactive shell. So the question here is why would Packer handle `-var packages="googlechrome javaruntime"` differently?

**Comment by DanHam** [comment]
> ...the issue seems to be the way packer is handling it's command line

Tut... Packer works perfectly!! This issue is clearly down to the way Spinnaker invokes it! 😄

Joking aside, the fact that there is seemingly **zero** difference between the command that Spinnaker creates and the command that you would type if invoking Packer directly is puzzling. I don't get the different results and that bugs me.

> From everything I can tell, the only difference is that Spinnaker is running Packer in a non-interactive shell.

Interesting... I wonder if that has something to do with it. Maybe this is not so much the way Packer is handling its command line, but something to do with the way in which those args are treated in a non-interactive shell. It's like the interactive shell treats the packages value as the string `googlechrome javaruntime`, while within a non-interactive shell the value is **literally** interpreted as the quoted string `"googlechrome javaruntime"`. 

Like I said, this type of thing bugs me until I know *why* it is happening - regardless of whether we have a valid workaround or not. Some further investigation is needed to understand this. I'll keep taking a look and see if I can figure out anything further. Could you provide a pointer/reference to the Spinnaker code that issues the packer command?

**Comment by robumberger** [comment]
Spinnaker creates the packer command line in CloudProviderBakeHandler.groovy and LocalJobFriendlyPackerCommandFactory.groovy. The primary method is "producePackerCommand" which collects all the variables to pass over to the method "buildPackerCommand" which actually creates the command line.

If we assume that the packer command line is correct and it's the runtime environment that's impacting how packer parses the command line, reviewing the launch code is probably more interesting. Spinnaker launches the packer job in JobExecutorLocal.groovy in the "startJob" method. I'll dig into this code and see if anything stands out.

I looked at the contents of `/proc/<process_id>/environ` when packer is running under Spinnaker and command line to see if there are any differences and there are. I still need to step through the data, but here it is from each way of invoking packer.

From command line:

> PCKER_LOG=1XDG_SESSION_ID=4TERM=xtermSHELL=/bin/bashSSH_CLIENT=xx.xx.xxx.xxx 59770 22OLDPWD=/home/ubuntuSSH_TTY=/dev/pts/1USER=ubuntuLS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:MAIL=/var/mail/ubuntuPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gamesPWD=/home/ubuntu/transferLANG=en_US.UTF-8SHLVL=1HOME=/home/ubuntuLOGNAME=ubuntuSSH_CONNECTION=xx.xxx.xxx.xxx 59770 10.0.0.4 22LESSOPEN=| /usr/bin/lesspipe %sXDG_RUNTIME_DIR=/run/user/1000LESSCLOSE=/usr/bin/lesspipe %s %s_=/usr/bin/packerPACKER_RUN_UUID=7127d53d-4351-77ef-fbe7-7a9b644170a7PACKER_LOG=PACKER_LOG_PATH=cccf35992f8f3cd8d1d28f0109dd953e26664531=7c28215aca87789f95b406b8dd91aa5198406750

From Spinnaker:

> PACKER_LOG=TERM=xtermSHELL=/bin/bashSPINNAKER_AWS_ENABLED=falseOLDPWD=/opt/roscoSPINNAKER_GOOGLE_ENABLED=falseSPINNAKER_STACKDRIVER_ENABLED=falseUSER=rootLS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:SUDO_USER=ubuntuSUDO_UID=1000SPINNAKER_GOOGLE_DEFAULT_REGION=us-central1USERNAME=rootPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/binMAIL=/var/mail/rootSPINNAKER_AZURE_DEFAULT_REGION=eastusPWD=/home/ubuntuLANG=en_US.UTF-8SPINNAKER_GOOGLE_DEFAULT_ZONE=us-central1-fSPINNAKER_GOOGLE_PROJECT_ID=SPINNAKER_DEFAULT_STORAGE_BUCKET=HOME=/home/ubuntuSHLVL=2SUDO_COMMAND=/opt/spinnaker/bin/start_spinnaker.shSPINNAKER_AZURE_ENABLED=trueLOGNAME=rootPYTHONPATH=/opt/spinnaker/bin/../pylibSPINNAKER_AWS_DEFAULT_REGION=us-west-2SUDO_GID=1000BASH_FUNC___get_google_metadata_value%%=() {  local GOOGLE_METADATA_URL="http://metadata.google.internal/computeMetadata/v1";
>  local path="$1";
>  local value=$(curl -L --connect-timeout 2 -s -f -H "Metadata-Flavor: Google"                      $GOOGLE_METADATA_URL/$path);
>  if [[ $? -eq 0 ]]; then
>  echo "$value";
>  else
>  echo "";
>  fi
> }BASH_FUNC___get_aws_metadata_value%%=() {  local AWS_METADATA_URL="http://xxx.xxx.xxx.xxx/latest/meta-data";
>  local path="$1";
>  local value=$(curl -L --connect-timeout 2 -s -f $AWS_METADATA_URL/$path);
>  if [[ $? -eq 0 ]]; then
>  echo "$value";
>  else
>  echo "";
>  fi
> }BASH_FUNC___determine_default_bucket%%=() {  if [[ ! -z "${SPINNAKER_GOOGLE_PROJECT_ID}" ]]; then
>  echo "spinnaker-${SPINNAKER_GOOGLE_PROJECT_ID}";
>  else
>  echo "";
>  fi
> }PACKER_RUN_UUID=f9776509-a066-6b5e-0001-df96f7e0218fPACKER_LOG_PATH=cccf35992f8f3cd8d1d28f0109dd953e26664531=7c28215aca87789f95b406b8dd91aa5198406750
>

**Comment by robumberger** [comment]
I took a quick look at /proc/<process_id>/cmdline for invoking Packer via command line vs Spinnaker and there is a difference here:

COMMAND LINE

> ubuntu@spinnaker:~$ cat /proc/7472/cmdline
> /usr/bin/packerbuild-color=false-debug-varazure_client_id=##########ClientID##################-varazure_client_secret=#########-varazure_resource_group=spinnaker-varazure_storage_account=spinnakerimages-varazure_subscription_id=########SubscriptionID##############-varazure_tenant_id=##########TenantID##################-varazure_object_id=##########ObjectID##################-varazure_location=eastus-varazure_image_publisher=MicrosoftWindowsServer-varazure_image_offer=WindowsServer-varazure_image_sku=2012-R2-Datacenter-varazure_image_name=null-null-varpackage_type=nupkg-varpackages=googlechrome javaruntime-varconfigDir=/opt/rosco/config/packer/opt/rosco/config/packer/azure-windows-2012-r2.json


SPINNAKER

> ubuntu@spinnaker:~$ cat /proc/7619/cmdline
> /usr/bin/packerbuild-color=false-debug-varazure_client_id=##########ClientID##################-varazure_client_secret=#########-varazure_resource_group=spinnaker-varazure_storage_account=spinnakerimages-varazure_subscription_id=########SubscriptionID##############-varazure_tenant_id=##########TenantID##################-varazure_object_id=##########ObjectID##################-varazure_location=eastus-varazure_image_publisher=MicrosoftWindowsServer-varazure_image_offer=WindowsServer-varazure_image_sku=2012-R2-Datacenter-varazure_image_name=null-null-varpackage_type=nupkg-varpackages="googlechrome javaruntime"-varconfigDir=/opt/rosco/config/packer/opt/rosco/config/packer/azure-windows-2012-r2.json

You'll notice that the `packages` variable has quotes in one but not the other. The really interesting part of this is when looking at the command line via `ps -ef | grep packer`, they are 100% the same. I'm not sure if this is Spinnaker directly or indirectly based on the way the shell is interrupting it, but does point more and more at how Spinnaker is launching Packer.

**Comment by DanHam** [comment]
Interesting. Looks like you're on to something there...

So, when I launch packer from a script (non-interactive shell) I still get the following from ps (note no quotes!)

```  501 47240 47239   0  4:56pm ttys004    0:00.79 packer build -only=virtualbox-iso -force -var packages=googlechrome javaruntime windows-2016.json```

**Comment by DanHam** [comment]
I think you could just quote the value with a space and not bother with the escapes e.g.

```
def keyValuePair = value instanceof String && value.contains(" ") ? "$key="$value"" : "$key=$value"
```

Note I am not at all familiar with Groovy so you might run into issues with the quotes within quotes there. Can you use single quotes? e.g. ```'$key="$value"'```

**Comment by robumberger** [comment]
Thanks for the interactive and quick feedback. I'm testing a change right now. Basically if the value starts and ends with a quote already, no need to add quotes. I'll get back to you shortly

**Comment by DanHam** [comment]
OK. Let me know how you get on. For what its worth, I think everything is good apart from the *escaping* of the quotes. You eventually want to end up with a command that looks like

```
packer build ... -var packages="googlechrome javaruntime" windows-template.json
```

In other words you still need to surround your space separated package list with quotes, but not escaped quotes...

**Comment by robumberger** [comment]
So this seems counter-intuitive. The "fix" is to remove the quotes all together. So instead of generating `packer build ... -var packages="googlechrome javaruntime" windows-template.json` I'm generating `packer build ... -var packages=googlechrome javaruntime windows-template.json`. This creates the following command line when checking via `ps -ef | grep packer`

> /usr/bin/packer build -color=false -var azure_client_id=##########ClientID################## -var azure_client_secret=######### -var azure_resource_group=spinnaker -var azure_storage_account=spinnakerimages -var azure_subscription_id=########SubscriptionID############## -var azure_tenant_id=##########TenantID################## -var azure_object_id=##########ObjectID################## -var azure_location=eastus -var azure_image_publisher=MicrosoftWindowsServer -var azure_image_offer=WindowsServer -var azure_image_sku=2012-R2-Datacenter -var azure_image_name=null-null -var package_type=nupkg -var packages=googlechrome javaruntime -var configDir=/opt/rosco/config/packer /opt/rosco/config/packer/azure-windows-2012-r2.json

When I check `/proc/<process_id>/cmdline`, I get this:

> cat /proc/16267/cmdline
> /usr/bin/packerbuild-color=false-varazure_client_id=##########ClientID##################-varazure_client_secret=########-varazure_resource_group=spinnaker-varazure_storage_account=spinnakerimages-varazure_subscription_id=########SubscriptionID##############-varazure_tenant_id=##########TenantID##################-varazure_object_id=##########ObjectID##################-varazure_location=eastus-varazure_image_publisher=MicrosoftWindowsServer-varazure_image_offer=WindowsServer-varazure_image_sku=2012-R2-Datacenter-varazure_image_name=null-null-varpackage_type=nupkg-varpackages=googlechrome javaruntime-varconfigDir=/opt/rosco/config/packer/opt/rosco/config/packer/azure-windows-2012-r2.json

which is the same as if I run it from the command line, but using `-var packages="googlechrome javaruntime"`.

Based on this, it seems to be an issue with the way Apache Commons Exec handles command line arguments. There's a [defect](https://issues.apache.org/jira/browse/EXEC-54) that's been open for a while, but not 100% it relates.

I'm going to continue testing this change in both AWS and Azure environments. I'll respond here if it "fixes" the issue.

**Comment by DanHam** [comment]
Well, on the bright side at least you got to the bottom of the issue and have everything working - even if it does seem slightly counter intuitive. Note that Packer creates its env vars by splitting on the first equals sign - everything after the equals is the value. For Powershell it then surrounds the value with double quotes. If you were setting this up directly in the json template:

```
{ "type": "powershell",
  "environment_vars": [
    "PACKAGES=googlechrome javaruntime"
  ]
  ...
}
```

You would end up with a command line of: 

```
if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'}; $env:PACKAGES="googlechrome javaruntime"; ... etc
```

So perhaps after all the quoting, etc has been done by all the various layers here, this is what you are ending up with.

From Packer's perspective I don't think there is an issue and perhaps this could be closed.

**Comment by robumberger** [comment]
Agree. Will close this issue. Thanks for the help.
