### ISSUE TITLE
Documentation to use WinRM in Ansible provisioner

### ISSUE THREAD

**Issue by Wenzel** [mitchellh/packer#4485]
Hi,
In the latest release of Packer, `0.12.1` (December 15, 2016) [Changelog](https://github.com/mitchellh/packer/blob/master/CHANGELOG.md), I noticed that Packer is now able to use `WinRM` as a communicator for `ansible`
~~~
provisioner/ansible: Allow winrm communicator. [GH-4209]
~~~

However, i don't see anything mentioned in the documentation of [ansible-remote](https://www.packer.io/docs/provisioners/ansible.html)

How should i enable this feature ?
What are the new keys to configure ?

I would be very happy to use it !

Thanks !

**Comment by rickard-von-essen** [comment]
Just scroll to the bottom of the page, under _Winrm Communicator_. (v0.12.2 is the latest version)
