### ISSUE TITLE
SSH looping through ports until it finds the good one.

### ISSUE THREAD

**Issue by rommik** [mitchellh/packer#4491]
I noticed that  "waiting for SSH to become available..." takes a really long time. On Ubuntu it takes almost 15 mins. If I run the same build through my Jenkins, on the same machine, the time increases to over 40 mins.

I see that in the logs, SSH is trying to find a correct port by checking each port each 7 seconds.
Is there a way to specify the ports without this trial-and-error?

My original post is here: https://stackoverflow.com/questions/41987800/packer-loops-through-ports-when-attempting-to-establish-ssh-connection

packer version: 0.12.2
Linux: Ubuntu  16.04.1 TLS.

I changed my json from ssh_port 22 to ssh_host-port_min and ssh_host_port_max (2222,4444) hoping that this would limit the search range. However, my last test showed that the connection was established as shown bellow. I assume the port was anything after 48282. The log doesn't say.

2017/02/01 14:46:20 packer: 2017/02/01 14:46:20 [INFO] Attempting SSH connection...
2017/02/01 14:46:20 packer: 2017/02/01 14:46:20 reconnecting to TCP connection for SSH
2017/02/01 14:46:20 packer: 2017/02/01 14:46:20 handshaking with SSH
2017/02/01 14:46:20 packer: 2017/02/01 14:46:20 handshake error: ssh: handshake failed: read tcp 127.0.0.1:48282->127.0.0.1:3781: read: connection reset by peer
2017/02/01 14:46:20 packer: 2017/02/01 14:46:20 [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:48282->127.0.0.1:3781: read: connection reset by peer
2017/02/01 14:46:27 packer: 2017/02/01 14:46:27 [INFO] Attempting SSH connection...
2017/02/01 14:46:27 packer: 2017/02/01 14:46:27 reconnecting to TCP connection for SSH
2017/02/01 14:46:27 packer: 2017/02/01 14:46:27 handshaking with SSH
2017/02/01 14:46:58 packer: 2017/02/01 14:46:58 handshake complete!
2017/02/01 14:46:58 packer: 2017/02/01 14:46:58 [INFO] no local agent socket, will not connect agent
2017/02/01 14:46:58 ui: ==> virtualbox-iso: Connected to SSH!

**Comment by mwhooker** [comment]
`127.0.0.1:48282->127.0.0.1:3781:`

the port on the left of the arrow is the port the client is using to connect. The port on the right is the port of the server. As you can see, the server port doesn't change.

What you're identifying as time taken to find the right port is actually time it takes for the server to boot and for ssh to become available.

I'm not totally certain why jenkins takes longer than running on your ubuntu machine, but I'd wager is has to do with load.

I would try mailing the mailing list to see if they can help you speed up your build.
