### ISSUE TITLE
may be crazy idea, but why not ask?

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/packer#4499]
Most of builders provide vnc/rdp. Why not bundle to packer small js vnc client and spawn additional web server for it.
So when i'm run builder with qemu, for example i have not vnc link and need to go via client to it (and client must be installed), but have http link, then it opens i can view and control vnc session?
So i don't need additional deps only browser not older then 2 years....

P.S. I'm not want novnc bundle to packer, but rfb2 library that i have some contribution to add tight png support encoding that supported by at least by qemu.

**Comment by vtolstov** [comment]
For security we can use basic auth with packer login and some generated password...

**Comment by vtolstov** [comment]
@mwhooker @cbednarski @jcrosby

**Comment by mwhooker** [comment]
sounds like a neat idea, but in general I think we want to make as few assumptions as possible about the guest OS. Trying to portably spin up a VNC server sounds like a pain.

Maybe a custom provisioner would be the way to go for this?

#2990 was I think similar to this, but for screenshots on vmware/virtualbox

We can pick this back up after 1.0. feel free to continue to flesh out ideas in this ticket

**Comment by cbednarski** [comment]
@vtolstov This is a cool idea! I'm going to defer to Matt with respect to including it, but I did not know this was a thing. Thanks for the suggestion! https://kanaka.github.io/noVNC/

**Comment by mwhooker** [comment]
@vtolstov If you wanted to put up a PR for this, actually, it might be something worth having. I'll keep it closed, though, since it's not something we're working on for 1.0
