### ISSUE TITLE
How to build vmware-iso on linux with workstation ?

### ISSUE THREAD

**Issue by rgarrigue** [mitchellh/packer#4503]
Hello

I'm trying to build template for VMWare on my Ubuntu 16.10, with VMWare Workstation installed. 
I'm missing some bin, vmrun, vmware. I guess they disappeared between VMWare Workstation <12 and my current VMWare 12. 
I found some info about this googling, tried stuff without success, but I miss a clear fuunctionnal documentation. If anyone got one, of if the official doc could include a prerequisite documentation ? Or maybe a patch for packer to use VMWare Workstation 12 out of the box

Here are my info 

    remy@computer: ~/work/bento master ⚡ $ packer -v
    0.12.1

    remy@computer: ~/work/bento master ⚡ $ packer build -only=vmware-iso centos-7.3-x86_64.json
    vmware-iso output will be in this color.

    Build 'vmware-iso' errored: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
    from each driver are shown below. Please fix at least one driver
    to continue:
    * exec: "vmware": executable file not found in $PATH
    * exec: "vmware": executable file not found in $PATH
    * exec: "vmrun": executable file not found in $PATH
    * exec: "vmrun": executable file not found in $PATH

    ==> Some builds didn't complete successfully and had errors:
    --> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
    from each driver are shown below. Please fix at least one driver
    to continue:
    * exec: "vmware": executable file not found in $PATH
    * exec: "vmware": executable file not found in $PATH
    * exec: "vmrun": executable file not found in $PATH
    * exec: "vmrun": executable file not found in $PATH

    ==> Builds finished but no artifacts were created.
    FAIL: 1

    remy@computer: ~/work/bento master ⚡ $ vmware-installer -l 2>/dev/null
    Product Name         Product Version
    ==================== ====================
    vmware-player        12.5.2.4638234
    vmware-cip-55        5.5.0.2893191

    remy@computer: ~/work/bento master ⚡ $ vmware-installer -t 2>/dev/null
    Component Name        Component Long Name                      Component Version
    ===================== ======================================== ====================
    vmware-installer      VMware Installer                         2.1.0.4298805
    vmware-player-setup   VMware Player Setup                      12.5.2.4638234
    vmware-vmx            VMware VMX                               12.5.2.4638234
    vmware-network-editor VMware Network Editor                    12.5.2.4638234
    vmware-usbarbitrator  VMware USB Arbitrator                    15.2.0.4638234
    vmware-player-app     VMware Player Application                12.5.2.4638234
    vmware-ovftool        VMware OVF Tool component for Linux      4.1.0.3634792
    vmware-player         VMware Player                            12.5.2.4638234
    vmware-vmrc-5.5       VMware VMRC                              5.5.0.2867619
    vmware-cip-55         VMware Client Integration Plug-in        5.5.0.2893191

**Comment by rickard-von-essen** [comment]
Looks like you have WMware Player not Workstation?

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rgarrigue** [comment]
I've what you get when you google & download Workstation nowadays, this :
https://my.vmware.com/web/vmware/info?slug=desktop_end_user_computing/vmware_workstation_pro/12_0


2017-02-03 17:31 GMT+01:00 Rickard von Essen <notifications@github.com>:

**Comment by TheNotary** [comment]
So, just to keep things well documented here on a resource available to google, unless I'm mistaken, you can't build with this builder without a license from VMWare.

**Comment by mwhooker** [comment]
I believe packer works with vmware workstation player on windows and linux https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/12_0

**Comment by benfairless** [comment]
@mwhooker At least on the VMware Workstation Player 12 available on Linux, it does not bundle the necessary binaries used by packer.

```
--> vmware: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* exec: "vmware": executable file not found in $PATH
* exec: "vmware": executable file not found in $PATH
* exec: "vmrun": executable file not found in $PATH
* exec: "vmrun": executable file not found in $PATH
```

```
$ vmware-installer -t 2>/dev/null
Component Name                 Component Long Name                      Component Version   
============================== ======================================== ====================
vmware-installer               VMware Installer                         2.1.0.5087745       
vmware-player-setup            VMware Player Setup                      12.5.7.5813279      
vmware-vmx                     VMware VMX                               12.5.7.5813279      
vmware-network-editor          VMware Network Editor                    12.5.7.5813279      
vmware-usbarbitrator           VMware USB Arbitrator                    15.2.0.5813279      
vmware-player-app              VMware Player Application                12.5.7.5813279      
vmware-ovftool                 VMware OVF Tool component for Linux      4.1.0.3634792       
vmware-player                  VMware Player                            12.5.7.5813279      
vmware-vix-core                VMware VIX Core Library                  1.15.7.5115892      
vmware-vix-lib-Workstation1200 VMware VIX Workstation-12.0.0 Library    1.15.7.5115892      
vmware-vix                     VMware VIX API                           1.15.7.5115892 
```
