### ISSUE TITLE
Support WinRM As A Communicator

### ISSUE THREAD

**Issue by joefitzgerald** [mitchellh/packer#451]
Currently when building a Packer template for Windows (e.g. https://github.com/joefitzgerald/packer-windows/), we need to install Cygwin to allow Packer's Provisioners to work and to allow the shutdown command to be run. Ideally, Packer could use WinRM to perform these actions, allowing us to avoid bundling Cygwin with our Windows boxes. 

See [here](https://github.com/joefitzgerald/packer-windows/issues/3) for related conversation.

@mitchellh You and I discussed using a Ruby command line utility to provide this functionality, because Go has no WinRM / WS-Management / WS-* / SOAP libraries to build upon.

**Comment by mkuzmin** [comment]
@mefellows, could you tell us about current state of this feature?
I see you are developing https://github.com/packer-community/packer-windows-plugins
Are these plugins ready to use?
Why did you choose to fork base plugins, are you going to merge these changes back?

**Comment by mefellows** [comment]
Hi @mkuzmin,

The current state of the plugins is fairly stable, and I am using them daily in both Development and Production environments. There is [one remaining issue](https://github.com/packer-community/packer-windows-plugins/issues/4) that I feel is the last thing to close out before a 1.0.x release (it sounds worse than it is and I haven't yet encountered it in my use cases).

We chose to fork for a number of reasons (breaking change was required), but for the most part it was practicality as it enabled us to develop with greater pace. We would love to get these merged in at some point, but we would really need the support of the community before we attempt to do so to ensure we keep Packer itself stable etc. Feel free to reach out via the usual [GitHub](https://github.com/packer-community/packer-windows-plugins/) channels!

**Comment by mitchellh** [comment]
Done! Now in core.
