### ISSUE TITLE
[Azure] managed disk support

### ISSUE THREAD

**Issue by davidobrien1985** [mitchellh/packer#4511]
Hi,

are you guys working with the Azure team to support managed disks by the time they go GA? Apparently this is very soon and it would obviously be awesome to have this working.

Cheers

**Comment by mwhooker** [comment]
It's not something we're planning to support. @boumenot might have some thoughts, but it's not something we're planning on implementing for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by boumenot** [comment]
Once managed disks have been added to the Azure Go SDK, I will look at adding them to the Azure builder.

**Comment by davidobrien1985** [comment]
@boumenot great, thanks. Apparently it's already "there": https://github.com/Azure/azure-sdk-for-go/releases/tag/8.0.1-beta

**Comment by davidobrien1985** [comment]
@boumenot great, thanks. Apparently it's already "there": https://github.com/Azure/azure-sdk-for-go/releases/tag/8.0.1-beta

**Comment by rajpolaris** [comment]
@boumenot  Most of my clients are already starting to use managed disks for  new deployments. So it will be great to get managed disk supported in packer.

**Comment by davidobrien1985** [comment]
@boumenot have you been able to already look at this? @devigned mentioned he might be able to look at this after he's now added this to vagrant.

**Comment by boumenot** [comment]
I have not.  If @devigned is willing to contribute support, I would gladly accept it.

**Comment by devigned** [comment]
I'll try to set some time aside this week.

**Comment by NSmeef** [comment]
I would also love to see this get baked into packer.

**Comment by tomasquith** [comment]
+1

**Comment by davidobrien1985** [comment]
@devigned I know Build happened, but already a fork or PR somewhere that one can have a look at? I'd like to show this functionality to my user group next month and might just need to start learn some Go if you really don't have time for this. Just let us know :)

**Comment by devigned** [comment]
Sorry @davidobrien1985, I'm on holiday with the family (post build). Should be back to focus on this after ChefConf (mid next week).

**Comment by rbramwell** [comment]
Managed disk support is in! https://github.com/hashicorp/packer/blob/v1.0.3/CHANGELOG.md
