### ISSUE TITLE
Create fixed-size OVA, with virtualbox-iso builder

### ISSUE THREAD

**Issue by GuillaumeSeren** [mitchellh/packer#4513]
Hey,
I need to build a fixed size vm for a customer, 
I did my VM using packer, and i see in the go source file that the option is present,
when you create a disk (option is variant), but not in the default builder setup.

I know that I can open and convert the the vmdk inside the OVA.

Would it be nice to have it as a param (variant / disk_size) of the default builder param ?

Guillaume

**Comment by mwhooker** [comment]
sorry, not sure I follow. Could you explain what you mean by default builder?

**Comment by GuillaumeSeren** [comment]
@mwhooker Yes ! 
The builder I use is virtualbox-iso, according to the doc [here](https://www.packer.io/docs/builders/virtualbox-iso.html) there is no --variant param, I took this param in the vboxmanage cli doc [here](https://www.virtualbox.org/manual/ch08.html), which show
```

  createmedium              [disk|dvd|floppy] --filename <filename>
                            [--size <megabytes>|--sizebyte <bytes>]
                            [--diffparent <uuid>|<filename>
                            [--format VDI|VMDK|VHD] (default: VDI)
                            [--variant Standard,Fixed,Split2G,Stream,ESX]
```

So I searched a bit more in the go implementation of packer, [here](https://github.com/mitchellh/packer/blob/master/builder/virtualbox/iso/step_create_disk.go)

Here we see the default api (simpler, no variant param)
```
	command = []string{
		"storageattach", vmName,
		"--storagectl", controllerName,
		"--port", "0",
		"--device", "0",
		"--type", "hdd",
		"--medium", path,
		"--nonrotational", nonrotational,
		"--discard", discard,
}
```

And the createdisk, which correspond to the createmedium function (I guess), with the default value 'Standard'
```
command := []string{
		"createhd",
		"--filename", path,
		"--size", strconv.FormatUint(uint64(config.DiskSize), 10),
		"--format", format,
                "--variant", "Standard",
```

So  my proposal is to expose this param to the default function of this packer builder, that way we can quite simply define fixed-size disk if we need.

I hope to be a bit more clear 🍺

**Comment by mwhooker** [comment]
oh, you want the `--variant` flag to be configurable? I'm not sure what the use-cases for that are, but seems reasonable. I will be happy to review any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by GuillaumeSeren** [comment]
@mwhooker Ok I understand,
this issue was there to check if you (maintainer) was not against that,
as it seems to be case I will happily try my best to patch this (small) feature.

Thanks for your feedback.
