### ISSUE TITLE
Cloudstack builder user_data kickstart?

### ISSUE THREAD

**Issue by wingZero21** [mitchellh/packer#4516]
Hi,

Can you advise if the cloudstack builder allows for sending boot commands such as a kickstart file. I am trying to create a template from a minimal iso that is in cloudstack. This works fine using the virtualbox provisioner when downloading the same iso directly and sending the kickstart boot command.

When using the cloudstack provisioner and user_data, it does not seem to pickup the file and goes directly to the UI installation screen.

Added the user data that I have added below. If this is not the place to put this, is there anyway to actually send a kickstart boot command for the cloudstack provisioner?

Cheers
Mark

Details:
```  "user_data": "<tab> text ks=http://filestore.co.uk/ks.cfg<enter><wait>",```

**Comment by rickard-von-essen** [comment]
It's currently not. I think you need to provide a ISO with a kickstart file in it.

**Comment by mwhooker** [comment]
I think this has been answered. If you're still having trouble, I would recommend bringing this to the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk). The mailing list has a lot more eyeballs on it than the github issue tracker, so I think you're more likely to find help there.

If you discover that this is a bug in packer, you should definitely open an issue. However, after a brief glance at this it's not obvious that there's a bug, so I'm going to close this.

**Comment by wingZero21** [comment]
Hi,

This is sort of answered, however after building an ISO with ks preloaded it seems to take longer than the default timeout for the kickstart to run. It then goes "Timeout waiting for SSH" and then terminates the VM.

With the cloudstack builder is there any option to specify the SSH timeout period that seems to exist with the others so we can actually see if this can complete?

**Comment by rickard-von-essen** [comment]
See [ssh_timeout](https://www.packer.io/docs/templates/communicator.html#ssh_timeout)
