### ISSUE TITLE
fail to acquire ssh session on esxi server

### ISSUE THREAD

**Issue by geoHeil** [mitchellh/packer#4517]
Packer fails to acquire access to the ssh session and seems to be stuck on waiting for ssh to become available.

I noticed in the logs that:

    /var/log/auth.log
    2017-02-08T17:33:20Z sshd[94210]: User 'root' running command 'esxcli --formatter csv network vm list\n'
    2017-02-08T17:33:25Z sshd[94210]: User 'root' running command 'esxcli --formatter csv network vm list\n'
displays a lot of the same commands.

Executing this command manually shows

    esxcli --formatter csv network vm list
    Name,Networks,NumPorts,WorldID,
    ubunu-test,"VM Network,",1,87986,
    someOther,"VM Network,",1,84833,

What could be wrong here?

http://stackoverflow.com/questions/42118827/packer-vmware-iso-local-and-on-esxi with a link to the JSON configuration of the builders: https://gist.github.com/geoHeil/5acf06cb0f3afadfa347d437c2695a7c

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
