### ISSUE TITLE
parallel running packer with "qemu: Error connecting to VNC: dial 127.0.0.1:5913 getsockopt: connection refused"

### ISSUE THREAD

**Issue by coanor** [mitchellh/packer#4520]
I'm using packer behind a web server, the backend HTTP service to create QEMU image for various OS, when there are multiple packer running at the same time, there will throw such a error, I think the VNC port 5913 has beed occupied by some other packer worker, is it possible for packer to detect whether the VNC port is available or not?

**Comment by rickard-von-essen** [comment]
@vtolstov any comments?

**Comment by vtolstov** [comment]
this is expected, i have many times this. You must use network namespaces, for example docker and build image with packer inside docker container. So in this case port does not matter.
Also i can patch packer to create some lock file in /dev/shm, but i think that this ugly way....

**Comment by coanor** [comment]
How about to running a daemon packer? and then `push` json file to that daemon, this may fix the VNC or HTTP port competition.

**Comment by vtolstov** [comment]
I don't tinks that this needed. Sometimes ago i'm work on libvirt builder. It can solve this problems and bring ability to run build on remote hosts.
But i don't remember what stopped me. If you want, i can take a look at this builder and may be fix it ro run with current packer.

**Comment by coanor** [comment]
@vtolstov 👍 : Brilliant, I think it's also possible to export VNC port settings to json, this makes it possible to manage VNC port on the caller side.
