### ISSUE TITLE
Chef Provisioner fails to copy validator 

### ISSUE THREAD

**Issue by rj-reilly** [mitchellh/packer#4521]
packer 0.12.2
Windows 2012 R2

Packer Config [url](https://gist.github.com/rj-reilly/be3dfa0f6c480d5b9f0bbf4d925cbd94)

debug output  [url](https://gist.github.com/rj-reilly/bf946071796172d4825dbbf8f0571350)

regardless of where I put the chef validator key packer returns the error 

" amazon-ebs: Error copying validation key: open c:\temp\validation.pem: invalid argument"

**Comment by mwhooker** [comment]
I think you have a problem with your config.

`validation_key_path` is supposed to be a local path to a key. The provisioner will upload it for you. You can remove the upload step

https://www.packer.io/docs/provisioners/chef-client.html#validation_key_path

Please open another issue if you still hit problems with the above changes

**Comment by rj-reilly** [comment]
that was it thank you !
