### ISSUE TITLE
Specify Version of Salt Bootstrap

### ISSUE THREAD

**Issue by thegranddesign** [mitchellh/packer#4524]
Salt's Bootstrap script _regularly_ has bugs that are introduced in later changes.  In the last year I've had it happen four separate times.

I would very much appreciate an option that allows us to specify a specific git tag to use to download directly from the git repo as opposed to being required to take the latest version.

**Comment by mwhooker** [comment]
One thing you could do, which I recommend, is set `skip_bootstrap` to true, and install salt yourself, using the shell provisioner.

However, this is not something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by thegranddesign** [comment]
Using the shell provisioned is just reinventing the wheel. If there's a bootstrap script that is know to work, it seems silly not to be able to specify it.
