### ISSUE TITLE
vmware-iso with ESX failing on network

### ISSUE THREAD

**Issue by shyam2j** [mitchellh/packer#4540]
Hi,

I am trying to create template in a ESX machine from a VMWare VM in another host. Below are versions.
- Packer version - 0.12.2
- Host platform - RHEL 6.7
- ESX 5.1

I am using below JSON and kickstart to create template. I have attached the error I am getting. When I check the "Network adapter" in the VM,
![esx](https://cloud.githubusercontent.com/assets/24409119/22823546/2276f59e-efaa-11e6-93fc-1a77fdfd9eb2.jpg)
 I see no VLAN is assigned to it. Please help me with parameter to mention the VLAN and any other required parameters if any required.
(Initially tried without passing much data to vmx_data unlike the code below, but error is same.)

JSON
====
```
{
  "variables": {
    "vm_name": "packer",
    "vm_description": "rhel7 base",
    "iso": "/packer/Virtualbox/rhel-server-7.0-x86_64-dvd.iso",
    "checksum": "85a9fedc2bf0fc825cc7817056aa00b3ea87d7e111e0cf8de77d3ba643f8646c",
    "iso_checksum_type": "sha256"
  },

  "builders": [
    {
      "type": "vmware-iso",
      "ssh_username": "packer",
      "ssh_password": "packer",
      "ssh_port": 22,
      "ssh_wait_timeout": "30m",
      "http_directory": "http",

      "vm_name": "{{ user `vm_name` }}",
      "guest_os_type": "rhel7-64",
      "iso_url": "{{ user `iso` }}",
      "iso_checksum": "{{ user `checksum` }}",
      "iso_checksum_type": "{{ user `iso_checksum_type` }}",
      "tools_upload_flavor": "linux",
      "remote_datastore": "removed",
      "remote_host": "removed",
      "remote_password": "removed",
      "remote_type": "esx5",
      "remote_username": "root",
      "headless": false,
      "vmx_data": {
      "cpuid.coresPerSocket": 1,
      "memsize": 512,
      "ethernet0.present":"true",
      "ethernet0.pciSlotNumber":"192",
      "ethernet0.virtualDev":"vmxnet3",
      "ethernet0.dvs.switchId":"",
      "ethernet0.dvs.connectionId":"0",
      "ethernet0.addressType":"vpx",
      "numvcpus": 1
      },

      "boot_wait": "10s",
      "boot_command": [
        "<esc><wait>",
        "vmlinuz initrd=initrd.img net.ifnames=0 biosdevname=0 ",
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks3.cfg<enter><wait>"
      ],

    "shutdown_command": "echo '{{ user `username` }}' | sudo -S shutdown -P now"
   }
  ]
}
```

Kickstart
=====
```
install
cdrom
lang en_US.UTF-8
keyboard us
timezone America/New_York --isUtc
network --bootproto=dhcp

user --name=packer --plaintext --password packer --groups=packer --gecos="packer"
rootpw  --iscrypted xxxxxxx
auth --enableshadow --passalgo=sha512 --kickstart
firewall --disabled
selinux --disabled

bootloader --location=mbr
services --disabled="ip6tables,iptables" --enabled=NetworkManager,sshd
text
skipx
zerombr
clearpart --all --initlabel
autopart --type=lvm
firstboot --disable
eula --agreed
reboot

%packages --instLangs=en_US.utf8 --nobase --ignoremissing --excludedocs
@Core
@Base
@Development Tools
@Console internet tools
@Legacy UNIX compatibility
@Network Infrastructure Server
@Networking Tools
@Perl Support
@Security Tools
@System administration tools
@Debugging Tools
@Compatibility libraries
%end

%post
groupadd -g 9999 packer
useradd -u 9999 -g packer -G wheel packer
echo "packer" | passwd --stdin packer
sed -E -i '/Defaults[[:space:]]+requiretty/ s/^/#/' /etc/sudoers
echo "packer        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
%end
```

Thanks in advance
Shyam

**Comment by rickard-von-essen** [comment]
You probably at least need to set something like
```json 
"vmx_data": {
  "ethernet0.networkName": "VM Network"
} 
```

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by shyam2j** [comment]
For whoever facing this network error connecting from a VM in a ESX to another ESX for template creation: 

I was able to bring network adapter online with the help of above option "ethernet0.networkName": "VM Network", but still I was not able to bring the static IP up for communication with the VM getting created. 
I was able to fix this by adding network details(IP, netmask, gateway) along with kick-start details in same line under boot_command option. 

Thanks
Shyam
