### ISSUE TITLE
no keypair, or password available for amazon-windows-ebs builder 

### ISSUE THREAD

**Issue by stephensmalls** [mitchellh/packer#4542]
- Packer version from `packer version`

PS E:\share\packer> packer version
Packer v0.12.2

- Host platform

windows 7 pro

- Debug log output from `PACKER_LOG=1 packer build template.json`.

  https://gist.github.com/stephensmalls/317baab635da53b38f55004ae8d1efa7

- The _simplest example template and scripts_ needed to reproduce the bug.

https://gist.github.com/stephensmalls/317baab635da53b38f55004ae8d1efa7

While trying to create an ami in EC2 using packer, with a pretty simple configuration, I am unable to retrieve the administrators password. there does not seem to be any keypair associated with the instance, and I cannot find documentation with instructions on how to associate a private key to a windows instance.

**Comment by cbednarski** [comment]
Thanks for the report Stephen. Unfortunately we don't maintain the `amazon-windows-ebs` builder. I think you will want to report this here: https://github.com/packer-community/packer-windows-plugins

**Comment by rickard-von-essen** [comment]
And you should probably not need that plugin anymore. `amazon-ebs` with the `winrm` communicator should probably be fine.
