### ISSUE TITLE
packer fails to start vmware player 12

### ISSUE THREAD

**Issue by j2clerck** [mitchellh/packer#4548]
Hi,

I'm trying to use packer with vmware player 12 on Centos 7 server.
After installing vmware player 12 + vix api, i though I was getting somewhere.
However, the VM doesn't start and it seems that the error is linked to:
`/usr/bin/vmrun [-T player start output-ubuntu-14.04.amd64.vmware/packer-ubuntu-14.04.amd64.vmware.vmx nogui] `

When I try to run /bin/vmrum -T player list, it works fine. If I try /bin/vmrun [-T player list].

It might that the brackets are not accepted. Sadly I'm no Go developper and can't confirm my theory.

For now I'll try to go with Workstation which doesn't seem to have the issue. (likely that vmrun is defaulting to Workstation).

With VMware Player only:
`/bin/vmrun [-T player start output-vmware-iso/packer-vmware-iso.vmx nogui]`
`Unable to connect to host.`
`Error: Service type VIX_SERVICEPROVIDER_VMWARE_WORKSTATION was specified, but not installed`

With VMware Workstation instead:
`vmrun [-T player list]`
`Error: Unrecognized command: [-T`

debug.log:
https://gist.github.com/j2clerck/609be93827a3511c757c15986095d39e

Thanks for your help,
Joseph.

**Comment by mwhooker** [comment]
Thanks for opening an issue. We need a little more info in order to help.

* Make sure you test against the latest released version. It is possible
  we already fixed the bug you're experiencing.

* Run the command with debug ouput with the environment variable
  `PACKER_LOG`. For example: `PACKER_LOG=1 packer build template.json`. Take
  the *entire* output and create a [gist](https://gist.github.com) for linking
  to in your issue. Packer should strip sensitive keys from the output,
  but take a look through just in case.

* Provide a reproducible test case. If a contributor can't reproduce an
  issue, then it dramatically lowers the chances it'll get fixed. And in
  some cases, the issue will eventually be closed.

**Comment by j2clerck** [comment]
Further info:
VM running Centos 7.3 64bits minimum install
VMware Player 12.5 installed
VIX API 1.15.6 installed

**Comment by j2clerck** [comment]
It seems I was misguided in my troubleshooting. I'll dig a bit deeper before reopening if needed.

**Comment by mwhooker** [comment]
yeah, the `[]` is just how we print the argument list. Feel free to post more or email the mailing list (https://groups.google.com/forum/#!forum/packer-tool) if you want help

**Comment by monsoft** [comment]
It should be without '[]' as looks like vmrun doesn't recognize it. I have this same issue with vmware player.
Packer is executing:
2017/11/02 17:25:47 packer.exe: 2017/11/02 17:25:47 Executing: C:\Program Files (x86)\VMware\VMware VIX\vmrun.exe [-T player start output-vmware-iso\packer-centos-7-x86_64.vmx nogui]

But this is not recognized. Same as simple listing running vms:
PS C:\Downloads\packer> vmrun.exe [-T player list]
Error: Unrecognized command: [-T
PS C:\Downloads\packer> vmrun.exe -T player list
Total running VMs: 0

**Comment by j2clerck** [comment]
Hi Monsoft,

If I remember correctly my issue was finally linked to a pop up not showing as I was using it headless. The pop up was from VMware to accept license before first use. 
I can’t recall right now how I fixed it. Maybe by installing a GUI or running the command manually to start the VM. 

Regards,
Joseph

**Comment by monsoft** [comment]
Hi Joseph,

Looks like you're right about this. There is no "nogui" option for vmware player.
There is issues with vnc now but I will look to this tomorrow.

Thanks for help :)

Irek

**Comment by mwhooker** [comment]
fyi I changed the log output so it hopefully won't cause as much confusion: 4d117bf117446845e403f0043fb30b72835cd605
