### ISSUE TITLE
OpenStack builder: Parallel provisioning sometimes assigns the same floating IP to build instances being created

### ISSUE THREAD

**Issue by themistymay** [mitchellh/packer#4551]
There are plenty of available floating IPs available to the project but packer still tried to assign the same IP to both build instances. Notice both `base-centos` and `base-ubuntu` got IP: 10.107.4.84

```
$ packer version
Packer v0.12.2
```
```
$ packer build images/base.json
base-centos output will be in this color.
base-ubuntu output will be in this color.

==> base-ubuntu: Discovering enabled extensions...
==> base-centos: Discovering enabled extensions...
==> base-centos: Loading flavor: 511ae4a4-d32a-4627-884a-565139357237
    base-centos: Verified flavor. ID: 511ae4a4-d32a-4627-884a-565139357237
==> base-centos: Creating temporary keypair: packer 589f3996-601d-864c-7c5a-a67989b61094 ...
==> base-centos: Created temporary keypair: packer 589f3996-601d-864c-7c5a-a67989b61094
==> base-centos: Successfully converted BER encoded SSH key to DER encoding.
==> base-centos: Launching server...
==> base-ubuntu: Loading flavor: 511ae4a4-d32a-4627-884a-565139357237
    base-ubuntu: Verified flavor. ID: 511ae4a4-d32a-4627-884a-565139357237
==> base-ubuntu: Creating temporary keypair: packer 589f3997-dfa3-ac49-501c-390b0728a236 ...
==> base-ubuntu: Created temporary keypair: packer 589f3997-dfa3-ac49-501c-390b0728a236
==> base-ubuntu: Successfully converted BER encoded SSH key to DER encoding.
==> base-ubuntu: Launching server...
    base-centos: Server ID: 882fa86b-336f-4880-830e-36867b954b30
==> base-centos: Waiting for server to become ready...
    base-ubuntu: Server ID: 5b00f441-951d-4e61-ae1e-77d8ee7e5181
==> base-ubuntu: Waiting for server to become ready...
==> base-centos: Searching for unassociated floating IP in pool floating_ips
    base-centos: Selected floating IP: 10.107.4.84
==> base-centos: Associating floating IP with server...
    base-centos: IP: 10.107.4.84
==> base-ubuntu: Searching for unassociated floating IP in pool floating_ips
    base-ubuntu: Selected floating IP: 10.107.4.84
==> base-ubuntu: Associating floating IP with server...
    base-ubuntu: IP: 10.107.4.84
    base-centos: Added floating IP 10.107.4.84 to instance!
==> base-centos: Waiting for SSH to become available...
    base-ubuntu: Added floating IP 10.107.4.84 to instance!
==> base-ubuntu: Waiting for SSH to become available...
==> base-ubuntu: Connected to SSH!
==> base-ubuntu: Provisioning with shell script: provisioning/shell/prep-ubuntu.sh


..... truncated 
```
Host platform: Ubuntu (executed by GitLab Runner)

This bug does NOT happen every time and therefore reproducability is not 100%.

**Comment by jrandall** [comment]
I am working on a fix for this based on the ansible os_server_module `reuse_ips` setting ( https://docs.ansible.com/ansible/os_server_module.html):
```When auto_ip is true and this option is true, the auto_ip code will attempt to re-use unassigned floating ips in the project before creating a new one. It is important to note that it is impossible to safely do this concurrently, so if your use case involves concurrent server creation, it is highly recommended to set this to false and to delete the floating ip associated with a server when the server is deleted using delete_fip.```

My fix would add the same configuration setting to packer's openstack builder, and make the default true. There may be some cases when people want to reuse existing IPs rather than allocate new ones, so I think it is important there be a setting for them.

Note that there is a partial workaround for this which is to run builds serially by setting `-debug`.

**Comment by jrandall** [comment]
I would argue there is also a second bug here which is that when the openstack builder attempts to assign the same IP to multiple instances, it does not notice that one of them has failed - it goes on to the next step and attempt to ssh to the instance, which eventually times out.
