### ISSUE TITLE
Error getting SSH config: SSH_AUTH_SOCK is not set

### ISSUE THREAD

**Issue by aaronmell** [mitchellh/packer#4556]
Getting the following error when attempting to build an AMI using the amazon-ebs builder

2017/02/14 11:40:08 packer.exe: 2017/02/14 11:40:08 [DEBUG] Error getting SSH config: SSH_AUTH_SOCK is not set

```
 "builders": [
    {
      "type": "amazon-ebs",
      "communicator": "ssh",
      "region": "us-east-1",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "subnet_id": "{{user `subnet_id`}}",
      "vpc_id": "{{user `vpc_id`}}",
      "security_group_id": "{{user `security_group_id`}}",
      "source_ami": "{{user `base_ami`}}",
      "instance_type": "{{user `instance_type`}}",      
      "ami_name": "rh7.3-{{timestamp}}",
      "iam_instance_profile": "Redacted",
      "ssh_keypair_name": "myKey",
      "ssh_agent_auth": "true",
      "ssh_private_key_file": "myKey.pem",
      "ssh_username": "ec2-user",
      "ssh_private_ip": "true",
      "encrypt_boot": "true",
      "tags": {
        "OS_Version": "Redhat 7.3 HVM",
        "Environment": "Redacted",
        "Role": "Redacted"
      }
    }
  ]
```

If I run in -debug mode I can connect via Putty after converting the PEM to a format Putty can use.

**Comment by mwhooker** [comment]
Are you meaning to do agent based authentication? I noticed from the docs

> ssh_agent_auth (boolean) - If true, the local SSH agent will be used to authenticate connections to the source instance. No temporary keypair will be created, and **the values of ssh_password and ssh_private_key_file will be ignored**. To use this option with a key pair already configured in the source AMI, leave the ssh_keypair_name blank. To associate an existing key pair in AWS with the source instance, set the ssh_keypair_name field to the name of the key pair.

And that you also have `ssh_private_key_file` set. Try removing `ssh_agent_auth` and see if that works.

**Comment by aaronmell** [comment]
That fixed the issue. Thanks
