### ISSUE TITLE
Custom builder compilation error due to vendoring

### ISSUE THREAD

**Issue by dradtke** [mitchellh/packer#4562]
I'm doing some initial work building out a Linode builder for Packer, but am running into a problem adding the SSH connection step that appears to be due to how Packer is vendored. Specifically, I'm getting the error:

```
cannot use commHost (type func("github.com/dradtke/packer-builder-linode/vendor/github.com/mitchellh/multistep".StateBag) (string, error)) as type func("github.com/dradtke/packer-builder-linode/vendor/github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep".StateBag) (string, error) in field value
```

The types that it's complaining about, in a slightly more readable format:

```
  has: func("github.com/dradtke/packer-builder-linode/vendor/github.com/mitchellh/multistep".StateBag) (string, error)
wants: func("github.com/dradtke/packer-builder-linode/vendor/github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep".StateBag) (string, error)
```

[My code](https://github.com/dradtke/packer-builder-linode) is loosely based on the Digital Ocean builder, but that may be avoiding this issue by being bundled with Packer. If you open up `linode/builder.go` and uncomment the lines importing communicator and setting up the SSH connection step, then you should be able to see the same issue. It occurs regardless of whether or not it's using the vendor folder, or recent versions of everything installed with `go get -u`.

**Comment by vtolstov** [comment]
This is vendoring problem. Fork packer and integrate own builder.

15 Фев 2017 г. 22:04 пользователь "Damien Radtke" <notifications@github.com>
написал:

**Comment by rickard-von-essen** [comment]
Duplicates #4342. Better have all the communication there.

**Comment by dradtke** [comment]
Ah, I glanced through the list but didn't see any that seemed to be the same issue. Thanks for pointing that one out.
