### ISSUE TITLE
build with go 1.8

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#4568]
first we need to upgrade our aws library. it's currently v1.4.6, needs >=1.6.3

https://aws.amazon.com/blogs/developer/aws-sdk-for-go-update-needed-for-go-1-8/

closes https://github.com/mitchellh/packer/issues/4323

**Comment by mwhooker** [comment]
see also https://github.com/golang/go/issues/19182

not sure we're effected by that. We only call `atomic.AddUint64`, and that's in a debug statement

**Comment by cbednarski** [comment]
I wouldn't worry about 19182 for packer. We don't rely on atomic functionality so it's unlikely to cause any problems. I'm sure it will be patched soon but in the mean time the work on updating AWS will probably take longer anyway.
