### ISSUE TITLE
windows floppy files been truncated for large driver files

### ISSUE THREAD

**Issue by coanor** [mitchellh/packer#4570]
I'm using packer for type qemu to create windows7/2k12/2k16 images, and I added virtio drivers for difference windows type.  I download these drivers from [here](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/).  But after the install, I find that, the network not work as expected. And I browsed the floppy folder, I find that some the files not copied to the `A:/`, so the network driver missing.

I removed the viostor driver from floppy file list(add a `-hda xxx` to `qemuargs` to walk-around the disk issue), and I find the network within windows works well, and the files been copied completely to A:/

Why packer missing copy all the driver files to `A:/`? is there any size limitation? 

Packer info:

- Packer version: `0.12.3`
- Host platform: Centos 6.8 + KVM

**Comment by mwhooker** [comment]
There's a 1.44mb file size limit for floppys. The supported ways to move large files into the OS are using the built-in http server (https://www.packer.io/docs/builders/qemu.html#http_directory) or the file provisioner: https://www.packer.io/docs/provisioners/file.html

There's been a request for a way to mount an arbitrary ISO into the guest, but that's not something we're planning on working on right now. I believe this duplicates #3328
