### ISSUE TITLE
packer --version returns an exit code of 1

### ISSUE THREAD

**Issue by keshavab** [mitchellh/packer#4580]
packer --version returns an exit code of 1 even after successful execution, where as expected would be 0.

OS/Arch: darwin amd64

```
$ packer --version
0.12.2
$ echo $?
1
$ uname -a
Darwin KEHP-M-X03J 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```
This is causing problems when used in jenkins, as it assumes failure on 1 and stops build.

**Comment by rickard-von-essen** [comment]
Duplicates #3370
