### ISSUE TITLE
Windows image on Google Compute

### ISSUE THREAD

**Issue by russellseymour** [mitchellh/packer#4581]
Is it possible to create a Windows image on Google Compute with Packer?

I have set up Packer to create a new Windows image on GCE, but it times out when trying to log into the machine using `winrm`.  Researching this appears that the first user has to be created on the instance from the `gcloud` command line tool or the GCE console.

If this is the case then I am not sure if it is possible to use Packer to create custom Windows machines.

**Comment by rickard-von-essen** [comment]
It should work.

Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
