### ISSUE TITLE
vagrant post processor wipes out the ability to login

### ISSUE THREAD

**Issue by diamantn** [mitchellh/packer#4582]
Using Packer to build a Virtualbox from ova file on mac.
Image is Ubuntu 16.04. (extracted from the official Vagrant box `cause you guys don't support a vagrant to vagrant build )
After the process completes no user can login. ("root", "ubuntu")
Without the vagrant post processor, the resulting Virtual box is fine.

```
{
  "builders": [
    {
      "type": "virtualbox-ovf",
      "source_path": "ubuntu1604.ova",
      "ssh_username": "ubuntu",
      "ssh_password": "ubuntu",
      "shutdown_command": "sudo shutdown now",
      "output_directory": "vbox",
      "vm_name": "Ubuntu1604-Vagrant",
      "headless": "false"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "scripts": [
        "config.sh"
      ]
    }
  ],
  "post-processors": [
    {
      "type": "vagrant",
      "compression_level": 6,
      "keep_input_artifact": true,
      "output": "Ubuntu1604-Vagrant.box"
    }]
}
```

- Packer version:0.12.2
- Host platform: Mac
https://gist.github.com/diamantn/5c32b00d241dec050df4337478c0d625

**Comment by mwhooker** [comment]
can you post the config.sh file? Hard to reproduce without that

**Comment by diamantn** [comment]
@mwhooker It just installs Docker and compose. I'll paste it, but it doesn't do anything that matters...

`#!/bin/bash

sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update

sudo apt install -y docker.io
curl -L "https://github.com/docker/compose/releases/download/1.11.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

sudo apt install -y mysql-client-5.6 yarn`

**Comment by rickard-von-essen** [comment]
Describe your workflow. It's that which is wrong.

**Comment by diamantn** [comment]
@rickard-von-essen
1. I use the default ubuntu 16.04 vagrant box to bring up a virtual box.
2. Export the box from virtualbox to a .ova file.
3. use packer as described above to just package that same image with the .config.sh logic.
At this point the resulting virtual box works fine.
4. using vagrant up to launch the .box, yet vagrant cannot login and no other user can either.

This is the vagrant file i use for 1. and 4. is similar:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", inline: <<-SHELL
        echo "ubuntu:ubuntu" | sudo chpasswd
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
        echo "root:ubuntu" | sudo chpasswd
  SHELL

end
```

**Comment by rickard-von-essen** [comment]
You are missing one step after 3 before 4, `vagrant box add ...`. 

Allso a common problem is that you need to clean up some network config that can't be in a Vagrant box, see
https://github.com/chef/bento/blob/master/scripts/debian/networking.sh

To troubleshoot this just write a timestamp into the box while building to ensure that you run the build you think you are running. Launch it with GUI and login via the console with `root`/`vagrant` verify that your network is working as expected.

**Comment by diamantn** [comment]
@rickard-von-essen Thank you, I'll check this out, but why do you think that the network has anything to do with this?
I'm using the console window for VB (I can also ssh)
I'm seeing the prompt that asks for user and then password, but no matter which user or password I use, I can't login.

As for the "box add", I didn't bother to mention it, (I apologize) but obviously, in the second Vagrantfile I'm using "config.vm.box_url" to specify the file.

**Comment by diamantn** [comment]
I've repeated the process, this time, I've deleted .vagrant.d and any .vagrant folder I could found.
Doing this constantly resolved the issue.

Thank you for your help. Packer is awesome.
please stop caching.
