### ISSUE TITLE
"encrypt_boot" support for the amazon-chroot builder.

### ISSUE THREAD

**Issue by josh-padnick** [mitchellh/packer#4583]
I'm using the amazon-chroot builder to create an AMI with multiple partitions. Everything is working great, but we'd like the snapshot of this AMI to be encrypted. The `encrypt_boot` property of the amazon-ebs builder seems to do exactly this, but strangely, this option isn't available for the amazon-chroot builder, so this issue is a feature request to add it there.

If there's any other "Packer native" way to create an encrypted EBS Volume using the amazon-chroot builder, I'd appreciate any insights on that as well.

**Comment by mwhooker** [comment]
Hi @josh-padnick,

I put together a small patch which adds `encrypt_boot` to the chroot builder. If you'd like to test it out, I can merge if it works. #4584

> If there's any other "Packer native" way to create an encrypted EBS Volume using the amazon-chroot builder, I'd appreciate any insights on that as well.

We just merged a new builder which might be interesting to you: https://github.com/mitchellh/packer/pull/4351

It's in master, but we haven't released it yet, so you'll need to compile source.
