### ISSUE TITLE
Packer homepage CSS not found?

### ISSUE THREAD

**Issue by varadharajan** [mitchellh/packer#4614]
Looks like the [application.css](https://www.packer.io/assets/stylesheets/application-34541528.css) for packer homepage is not found (404). This is breaking the homepage.

**Comment by mwhooker** [comment]
Hi @varadharajan, sorry you saw a 404. We deployed the docs today and its possible you saw the site while it was being deployed. Going to close since i can load it. Let me know if you're still having issues and I'll reopen. 

Cc @sethvargo so he can be aware of the issue

**Comment by varadharajan** [comment]
Hi @mwhooker, Thanks for your reply.

The homepage still points to the [old file]9https://www.packer.io/assets/stylesheets/application-34541528.css) and its a 404 from my machine as well as from one of the EC2 servers. I think you are probably viewing a cached version?

shell-> curl -i -k https://www.packer.io/assets/stylesheets/application-34541528.css
HTTP/1.1 404 OK
Cache-Control: max-age=14400
Last-Modified: Thu, 02 Mar 2017 01:16:31 GMT
ETag: "05993e48376954595bd6da013576098a"
Content-Type: text/html
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Fastly-Restarts: 1
Content-Length: 16192
Accept-Ranges: bytes
Date: Thu, 02 Mar 2017 07:18:45 GMT
Via: 1.1 varnish

**Comment by sethvargo** [comment]
Hi @varadharajan 

I'm not seeing that on my end:

```
$ curl -s https://www.packer.io/ | grep -i .css
    <link href="/assets/stylesheets/application-5b4f365a.css" rel="stylesheet" />
```

```
$ curl -svo /dev/null https://www.packer.io/assets/stylesheets/application-5b4f365a.css
< HTTP/2 200
< date: Thu, 02 Mar 2017 16:13:28 GMT
< cache-control: max-age=31536000
< last-modified: Thu, 02 Mar 2017 01:17:13 GMT
< etag: "cffd3a695cade45620a359c89f4225ee"
< content-type: text/css
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< x-frame-options: sameorigin
< accept-ranges: bytes
< via: 1.1 varnish
< age: 40193
< x-served-by: cache-iad2635-IAD
< x-cache: HIT
< x-cache-hits: 1
< x-timer: S1488471208.165166,VS0,VE3
< vary: Accept-Encoding
< content-length: 146069
```

It's possible that your browser cached an old version of the HTML. You can try clearing your cache or doing a force-reload of the page.

**Comment by varadharajan** [comment]
@sethvargo Yeah, i think so. Its working fine for me now. Thanks a lot
