### ISSUE TITLE
SSH provision skipping / Way how to bypass problem with connecting to a guest.

### ISSUE THREAD

**Issue by PetrPCZ** [mitchellh/packer#4617]
Hi,

currently working on automation of pfSense. I downloaded .iso, kinda okey went through booting via boot_command. Now I got stuck in finishing the box because I cannot connect to the machine thru default NAT setting. 

My machine: I have 4 NICs in the guest machine, 2nd, 3rd and 4th are used by pfSense, those works just fine. First one, is NAT NIC and is being used for communication with Packer. If I remove all the other NICs, connection is possible, Packer works fine, but if I setup basic configuration, connection does not work anymore. Connection starts, and handshake begins, but then it fails. No idea how to fix it. Maybe routing table does not forward traffic to the right NIC - First one, Packer's NAT. 

So, this is the problem, probably caused by incorrect setting. What pisses me off, is that there is no simple way how to bypass it. I just need close the guest, forcefully, gracefully does not matter, get a .box and rest I can do via scripting later on - I hope.

How does it look with "communicator":"none", other way how to bypass SSH connection? Also I would appreciate any other way how to connect to a guest. I can easily connect via Host-only network, SSHD is working flawlessly. Unfortunately NAT connection kinda do have problem if I add some other NICs. Ability to choose how to connect in more loose way, would help a lot. 

PS: "communicator":"none" is not working and as I read in older issue, it's not working for most of the builders - VBox for me.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
