### ISSUE TITLE
"Parallel Builds" section of Getting Started docs - DigitalOcean build fails with "ssh: handshake failed"

### ISSUE THREAD

**Issue by jason-azze** [mitchellh/packer#4629]
- Packer version from `packer version`
`Packer v0.12.3`
- Host platform
`Ubuntu 16.04.2 LTS`
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/jason-azze/3370535c9cd98b0332ea8d3775187e75

This is probably the interesting part of the debug output...
`
2017/03/06 15:09:58 ui: [1;36m==> digitalocean: Waiting for SSH to become available...[0m
2017/03/06 15:09:59 packer: 2017/03/06 15:09:59 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 52.14.185.117:22: i/o timeout
2017/03/06 15:10:13 packer: 2017/03/06 15:10:13 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 159.203.120.134:22: i/o timeout
`

To reproduce, use the template found here:
https://www.packer.io/intro/getting-started/parallel-builds.html

This was the command I used, with the naughty bits redacted:
`PACKER_LOG_PATH="packerlog.txt" PACKER_LOG=1 packer build -var 'aws_access_key=redacted' -var 'aws_secret_key=redacted' -var 'do_api_token=redacted' example.json`

**Comment by mwhooker** [comment]
I can reproduce. connecting with the debug key gives me `Permission denied (publickey).`

**Comment by mwhooker** [comment]
@jason-azze you can fix this by changing `ssh_username` to root. I think this is a documentation problem

**Comment by jason-azze** [comment]
Changing `ssh_username` to root works.
Now I have no excuse but to keep learning. :-)
Thank you!
