### ISSUE TITLE
[wishlist] Function to get the ID of a registered AMI

### ISSUE THREAD

**Issue by endemics** [mitchellh/packer#4638]
When using the `amazon-*` I'd like to be able to automatically fill the `source_ami` fields using something similar to terraform's `data.aws_ami` (https://www.terraform.io/docs/providers/aws/d/ami.html), so for instance I can automatically use the latest AMI for ubuntu or amazon linux when building an image.

Of course it is possible to do this using a var and running a command before running packer to retrieve the AMI, but an helper function (reusing terraform data aws_ami code?) would be more convenient.

**Comment by mwhooker** [comment]
Are you looking for `source_ami_filter`? https://www.packer.io/docs/builders/amazon-ebs.html#source_ami_filter

feel free to comment if you're looking for a different use-case and I'll re-open
