### ISSUE TITLE
Error removing temporary script, ssh: handshake failed

### ISSUE THREAD

**Issue by fertapric** [mitchellh/packer#4641]
### Packer version

```
Packer v0.12.3
```

### Host platform: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

### Log output and sample template

The Packer configuration this bug appeared builds an AWS AMI with a development environment based on Docker.

I don't know the source of this bug nor can reproduce it in an example template, sorry. The template works fine in some cases, but others it throws an error like:

```
==> amazon-ebs: Provisioning with shell script: provision/clone_repositories
    amazon-ebs: Cloning into '/home/ubuntu/my_project'...
    amazon-ebs: Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
    amazon-ebs: ==> another_project: Executing git clone git@github.com:jobandtalent/another_project.git...
    amazon-ebs:
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Retryable error: Error removing temporary script at /tmp/script_6152.sh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Retryable error: Error removing temporary script at /tmp/script_6152.sh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Builds finished but no artifacts were created.
```

I'm sorry for not being able to provide more information, but the build of these AMIs are automated and tend to fail due to this error.

Related issues: https://github.com/mitchellh/packer/issues/2691

**Comment by fertapric** [comment]
So, I run again the build using `PACKER_LOG=1`, here is the output https://gist.github.com/fertapric/7304c8a22fe7bf8d66242757f5d03cb7

Hope it helps!

**Comment by yaron-idan** [comment]
Packer version - 
```
Packer v0.12.3
```
Host platform:
```
macOS Sierra Version 10.12.3
```

Same issue here, ran into the error running the `packer build macos.json` command after following all the steps in this repo https://github.com/boxcutter/macos.

**Comment by fertapric** [comment]
This was not a Packer error, sorry.

At some point, we were configuring SSH providing SSH access to everyone in the team. We were doing that by updating the `~/.ssh/authorized_keys` file. The script was like:

```bash
#!/bin/bash

# Other SSH config

cat > $HOME/.ssh/authorized_keys <<TEAM_SSH_KEYS
ssh-rsa ...
TEAM_SSH_KEYS
```

However, that was removing the SSH public key that Packer uses to connect to the machine.

**Comment by opokhvalit** [comment]
I've got similar issue. I have multiple packer's .json scenarios with very small differences (for ex., source AMI, AMI name, tags, etc). I'm using customized Amazon Linux AMIs. All of them works fine except one. I can say even more: this one may works or may not and I didn't find any relations to something. Just do restart packer build, and it works. :(
Packer version is same, 0.12.3.

**Comment by ViktorSchlaffer** [comment]
legacy Oracle Linux yum server repo file needs to be updated if /usr/bin/ol_yum_configure.sh file is present.
