### ISSUE TITLE
Signature version 4 authentication failed in AWS

### ISSUE THREAD

**Issue by abdulrehman3725** [mitchellh/packer#4648]
## I receive below error when I upload bundle in AWS CLI

Signature version 4 authentication failed, trying different signature version ERROR: Error talking to S3: Server.NotImplemented(501): A header you provided implies functionality that is not implemented.

My issue is related to **create an AMI from an instance store-backed Linux instance**

**Comment by mwhooker** [comment]
dupe of #3615

**Comment by abdulrehman3725** [comment]
answer it man

**Comment by mwhooker** [comment]
I'm sorry this isn't working for you, but there's already a ticket about this which we will get to eventually. Packer is an open source project, so the tools for investigating this are available to you.
