### ISSUE TITLE
Supported Platforms

### ISSUE THREAD

**Issue by yusufyildiz86** [mitchellh/packer#4666]
As you said in the docs:
```
Note: We're always looking to officially support more target platforms. 
If you're interested in adding support for another platform, 
please help by opening an issue or pull request within GitHub 
so we can discuss how to make it happen.
````

So, Is there any platform not supported by packer that we can develop and help you ?

**Comment by mwhooker** [comment]
That's a very nice offer, however there's nothing specific I think we're lacking. It might be a good idea to message the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) asking people if there's a builder they'd like to see. 

There are a couple builders in flight, which you can see here, so there's no duplicate effort: https://github.com/mitchellh/packer/pulls?q=is%3Aopen+is%3Apr+label%3Anew-plugin-contribution

If you're looking to help out with the project, we could use some help fixing bugs, a list of which you can find here: https://github.com/mitchellh/packer/issues?q=is%3Aopen+is%3Aissue+label%3Abug
