### ISSUE TITLE
Packer can't connect with instance when are fininshing

### ISSUE THREAD

**Issue by ismFerDev** [mitchellh/packer#4667]
I have a problem with the ami builder, when the instance are stopping packer can't connect with instance.
- packer -version
0.12.3
- Amazon Linux
-  https://gist.github.com/ismFerDev/dea149700d5b467673ba06034821aaeb

**Comment by rickard-von-essen** [comment]
Your install is broken. Remove your current install directory and reinstall from [packer.io/downloads](https://www.packer.io/downloads.html). _Be sure to read the **note** about upgrading from < 0.9.0._
