### ISSUE TITLE
Feature request: support for Parallels Desktop Lite

### ISSUE THREAD

**Issue by timsutton** [mitchellh/packer#4696]
Parallels has released [Parallels Desktop Lite](https://itunes.apple.com/ca/app/parallels-desktop-lite/id1085114709) for Mac, a free version which uses macOS's Hypervisor framework as its engine. It doesn't support bridged networking, but it does still include CLI utilities for automation:

```
ls -la /Applications/Parallels\ Desktop\ Lite.app/Contents/MacOS
total 58168
drwxrwxr-x  20 root  wheel       680 17 Feb 20:21 .
drwxrwxr-x  12 root  wheel       408 19 Mar 17:57 ..
-rwxr-xr-x   1 root  wheel    522096 17 Feb 20:17 7z
-rw-r--r--   1 root  wheel   1810896 17 Feb 20:17 7z.dylib
drwxrwxr-x   3 root  wheel       102 19 Mar 17:57 Parallels Service.app
drwxrwxr-x   3 root  wheel       102 19 Mar 17:57 Parallels VM.app
-rwxr-xr-x   1 root  wheel   1288768 17 Feb 20:18 libMonitor.dylib
-rwxr-xr-x   1 root  wheel  36991568 17 Feb 20:21 prl_client_app
-rwxr-xr-x   1 root  wheel   3223936 17 Feb 20:18 prl_convert
-rwxr-xr-x   1 root  wheel   1475904 17 Feb 20:18 prl_disk_tool
-rwxr-xr-x   1 root  wheel     23248 17 Feb 20:18 prl_graphics_switcher
-rwxr-xr-x   1 root  wheel    418352 17 Feb 20:18 prl_mkiso
-rwxr-xr-x   1 root  wheel     57264 17 Feb 20:18 prl_perf_ctl
-rwxr-xr-x   1 root  wheel   5409216 17 Feb 20:18 prl_updater_ctl
-rwxr-xr-x   1 root  wheel     33072 17 Feb 20:18 prl_vmarchiver
-rwxr-xr-x   1 root  wheel   1046992 17 Feb 20:18 prlauth
-rwxr-xr-x   1 root  wheel    162176 17 Feb 20:18 prlcore2dmp
-rwxr-xr-x   1 root  wheel   1021840 17 Feb 20:19 prlctl
-rwxr-xr-x   1 root  wheel   1021856 17 Feb 20:19 prlsrvctl
-rwxr-xr-x   1 root  wheel    231616 17 Feb 20:19 unrar
```

Windows guests aren't covered for free, but *nix and Darwin guests are.

I'm not sure whether it would be as straightforward as just cloning the existing Parallels 9 driver (as the 10 and 11 drivers seem to), or whether it might be necessary to filter out any (?) features that aren't included in the Lite version. I know Lite doesn't support bridged networking configurations, but I don't know whether that's something that Packer would support for the Parallels driver anyway.

Thanks for all the work being done on this fantastic project!

**Comment by mwhooker** [comment]
I think if we got a PR for this that worked we'd probably merge it. I don't have too much time to evaluate what's needed for this right now, but probably looking to implement the Driver would be a good start.

If the lite version supports enough functionality to implement the [driver interface](https://github.com/mitchellh/packer/blob/master/builder/parallels/common/driver.go#L18), then that's where I'd look first.

I don't think we need a bridged network, but we will need to communicate with the virtual machine over ip, so that needs to work.

**Comment by rickard-von-essen** [comment]
Cool! I had forgotten about the _lite_ version was comming. 

Bridge network isn't used by default so unless you specifically set it that shouldn't be a problem. I guess we have to adapt or create a driver that works with lite, but that should be a easy task. 

@legal90 do you have any deeper insights into this?  And is it supported by the vagrant provider/docker-machine driver?

**Comment by chilcote** [comment]
Looks like Parallels Lite does not support the vagrant provider (bottom of http://kb.parallels.com/en/123796).

**Comment by rickard-von-essen** [comment]
Unfortunately this is a no go:

```
$ prlctl create fedora-25-x86_64 --distribution fedora-core --dst /Users/rickardvonessen/src/bento/packer-fedora-25-x86_64-parallels --vmtype vm --no --hdd
The command is available only in Parallels Desktop for Mac Pro or Business Edition.
```

**Comment by timsutton** [comment]
Thanks for checking, I should have done at least that much!
