### ISSUE TITLE
Packer no longer prints the tags added to AMIs

### ISSUE THREAD

**Issue by jmassara** [mitchellh/packer#4697]
In packer v0.11.0, with the `-machine-readable` flag passed to the `build` subcommand, packer would print out tags being added to the AMI. For example:

```shell
1488993771,,ui,say,==> amazon-ebs: Adding tags to AMI (ami-1a2b3c4d)...
1488993771,,ui,message,    amazon-ebs: Adding tag: "blVersion": "0.4.4dev"
1488993771,,ui,message,    amazon-ebs: Adding tag: "relatedTechnology": "linux"
1488993771,,ui,message,    amazon-ebs: Adding tag: "displayName": "Red Hat Enterprise Linux 7.2 DEV AMI v7"
1488993771,,ui,message,    amazon-ebs: Adding tag: "osVersion": "rhel7.2"
1488993771,,ui,message,    amazon-ebs: Adding tag: "status": "development"
```

In packer v0.12.3, it simply prints:

```shell
1490214972,,ui,say,==> amazon-ebs: Adding tags to AMI (ami-1a2b3d4d)...
1490214972,,ui,say,==> amazon-ebs: Tagging snapshot: snap-1a2b3d4e5f6g7h8i9
1490214972,,ui,say,==> amazon-ebs: Creating AMI tags
```

We grepped the previous version's output to provide information to downstream jobs in our CI/CD. Is there a reason why packer no longer prints this information? Can it be re-added?

It looks like it happened in this commit 800351b7ca9c966f3fe16a1135690eaffd000c22.

/cc @mwhooker

**Comment by mwhooker** [comment]
@jmassara yes, good point! Thus behavior shouldn't have been changes, sorry about that. Will make sure it's back the way it was before 1.0
