### ISSUE TITLE
Length restriction in boot_command

### ISSUE THREAD

**Issue by diekmanu** [mitchellh/packer#4700]
Hi,

is there some kind of length restriction in the boot_command array?
I tried to define some preseed variables in the json packer template, instead of getting them directly from the preseed.cfg in debian. This works as expected, except for larger strings:

`
"preseed/late_command=logger System is up!;sed -i \"s/PermitRootLogin.*/PermitRootLogin yes/g\" /target/etc/ssh/sshd_config\" <wait>",`

Will result in (from DEBCONF_DEBUG):
```
Mar 23 07:14:05 debconf: --> PROGRESS INFO finish-install/progress/preseed
Mar 23 07:14:05 debconf: <-- 10 finish-install/progress/preseed does not exist
Mar 23 07:14:05 debconf: --> SUBST finish-install/progress/fallback SCRIPT preseed
Mar 23 07:14:05 debconf: Adding [SCRIPT] -> [preseed]
Mar 23 07:14:05 debconf: <-- 0
Mar 23 07:14:05 debconf: --> PROGRESS INFO finish-install/progress/fallback
Mar 23 07:14:05 debconf: <-- 0 OK
Mar 23 07:14:05 finish-install: info: Running /usr/lib/finish-install.d/07preseed
Mar 23 07:14:05 debconf: --> GET preseed/late_command
Mar 23 07:14:05 debconf: <-- 0 logger System is up!;sed -i "s/PermitRootLogin.*/PermitRootLogin
Mar 23 07:14:05 preseed: running preseed command preseed/late_command: logger System is up!;sed -i "s/PermitRootLogin.*/PermitRootLogin
Mar 23 07:14:05 log-output: sh: syntax error: unterminated quoted string
Mar 23 07:14:05 debconf: --> SUBST preseed/command_failed COMMAND logger System is up!;sed -i "s/PermitRootLogin.*/PermitRootLogin
Mar 23 07:14:05 debconf: Adding [COMMAND] -> [logger System is up!;sed -i "s/PermitRootLogin.*/PermitRootLogin]
Mar 23 07:14:05 debconf: <-- 0
Mar 23 07:14:05 debconf: --> SUBST preseed/command_failed CODE 2
Mar 23 07:14:05 debconf: Adding [CODE] -> [2]
Mar 23 07:14:05 debconf: <-- 0
Mar 23 07:14:05 debconf: --> INPUT critical preseed/command_failed
Mar 23 07:14:05 debconf: <-- 0 question will be asked
```

- packer version 0.12.3
- win7/amd64/cygwin/vmware-builder

**Comment by mwhooker** [comment]
There's no max length, but we've definitely seen weirdness around the boot_command depending on load.

Please post the output of running packer with `PACKER_LOG=1` as well as your json file which reproduces this.

**Comment by diekmanu** [comment]
Switched to single quotes in the sed command. Seems to work now though im pretty sure that I tried that before. Weird.

**Comment by mwhooker** [comment]
glad you got it to work. Not sure exactly what happened, so hard to make a doc update or anything out of this
