### ISSUE TITLE
packer can not run  yum -y update with error Could not retrieve mirrorlist http://mirrorlist.centos.org/

### ISSUE THREAD

**Issue by KobeWangBeabloo** [mitchellh/packer#4720]
We met a problem when installing a centos 7.0 qcow2 image.
       We can run it successfully without the provisioners section, however it can't run when it executes the yum command. Seems that the internet connection of the installed image is not fine .
       Also we can access internet from our host platform os .

Host Platform OS:  openSUSE Leap 42.1
Packer version: 0.12.3
builder: QEMU 64bit 2.3.1 
OS need to be installed: centos 7.0

below is our error msg and our json template

Error msg:
2017/03/28 09:28:08 ui:     qemu: start yum update
    qemu: start yum update
2017/03/28 09:28:08 ui:     qemu: Loaded plugins: fastestmirror
    qemu: Loaded plugins: fastestmirror
2017/03/28 09:28:38 ui:     qemu: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os error was
    qemu: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os error was
2017/03/28 09:28:38 ui:     qemu: 14: curl#7 - "Failed to connect to 2607:f8f8:700:12::10: Network is unreachable"
    qemu: 14: curl#7 - "Failed to connect to 2607:f8f8:700:12::10: Network is unreachable"
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu: One of the configured repositories failed (Unknown),
    qemu: One of the configured repositories failed (Unknown),
2017/03/28 09:28:38 ui:     qemu: and yum doesn't have enough cached data to continue. At this point the only
    qemu: and yum doesn't have enough cached data to continue. At this point the only
2017/03/28 09:28:38 ui:     qemu: safe thing yum can do is fail. There are a few ways to work "fix" this:
    qemu: safe thing yum can do is fail. There are a few ways to work "fix" this:
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu: 1. Contact the upstream for the repository and get them to fix the problem.
    qemu: 1. Contact the upstream for the repository and get them to fix the problem.
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu: 2. Reconfigure the baseurl/etc. for the repository, to point to a working
    qemu: 2. Reconfigure the baseurl/etc. for the repository, to point to a working
2017/03/28 09:28:38 ui:     qemu: upstream. This is most often useful if you are using a newer
    qemu: upstream. This is most often useful if you are using a newer
2017/03/28 09:28:38 packer: 2017/03/28 09:28:38 Remote command exited with '1': chmod +x /tmp/script_7059.sh; PACKER_BUILDER_TYPE='qemu' PACKER_BUILD_NAME='qemu' PACKER_HTTP_ADDR='10.0.2.2:10086'  /tmp/script_7059.sh
2017/03/28 09:28:38 packer: 2017/03/28 09:28:38 [INFO] RPC endpoint: Communicator ended with: 1
2017/03/28 09:28:38 [INFO] 228 bytes written for 'stdout'
2017/03/28 09:28:38 [INFO] 1303 bytes written for 'stderr'
2017/03/28 09:28:38 [INFO] RPC client: Communicator ended with: 1
2017/03/28 09:28:38 [INFO] RPC endpoint: Communicator ended with: 1
2017/03/28 09:28:38 ui:     qemu: distribution release than is supported by the repository (and the
    qemu: distribution release than is supported by the repository (and the
2017/03/28 09:28:38 packer: 2017/03/28 09:28:38 [INFO] 228 bytes written for 'stdout'
2017/03/28 09:28:38 packer: 2017/03/28 09:28:38 [INFO] RPC client: Communicator ended with: 1
2017/03/28 09:28:38 packer: 2017/03/28 09:28:38 [INFO] 1303 bytes written for 'stderr'
2017/03/28 09:28:38 ui:     qemu: packages for the previous distribution release still work).
    qemu: packages for the previous distribution release still work).
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu: 3. Disable the repository, so yum won't use it by default. Yum will then
    qemu: 3. Disable the repository, so yum won't use it by default. Yum will then
2017/03/28 09:28:38 ui:     qemu: just ignore the repository until you permanently enable it again or use
    qemu: just ignore the repository until you permanently enable it again or use
2017/03/28 09:28:38 ui:     qemu: --enablerepo for temporary usage:
    qemu: --enablerepo for temporary usage:
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu: yum-config-manager --disable <repoid>
    qemu: yum-config-manager --disable <repoid>
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu: 4. Configure the failing repository to be skipped, if it is unavailable.
    qemu: 4. Configure the failing repository to be skipped, if it is unavailable.
2017/03/28 09:28:38 ui:     qemu: Note that yum will try to contact the repo. when it runs most commands,
    qemu: Note that yum will try to contact the repo. when it runs most commands,
2017/03/28 09:28:38 ui:     qemu: so will have to try and fail each time (and thus. yum will be be much
    qemu: so will have to try and fail each time (and thus. yum will be be much
2017/03/28 09:28:38 ui:     qemu: slower). If it is a very temporary problem though, this is often a nice
    qemu: slower). If it is a very temporary problem though, this is often a nice
2017/03/28 09:28:38 ui:     qemu: compromise:
    qemu: compromise:
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu: yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
    qemu: yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
2017/03/28 09:28:38 ui:     qemu:
    qemu:
2017/03/28 09:28:38 ui:     qemu: Cannot find a valid baseurl for repo: base/7/x86_64
    qemu: Cannot find a valid baseurl for repo: base/7/x86_64
2017/03/28 09:28:38 ui: ==> qemu: Deleting output directory...
==> qemu: Deleting output directory...
2017/03/28 09:28:38 ui error: Build 'qemu' errored: Script exited with non-zero exit status: 1
2017/03/28 09:28:38 Builds completed. Waiting on interrupt barrier...
2017/03/28 09:28:38 machine readable: error-count []string{"1"}
2017/03/28 09:28:38 ui error:
==> Some builds didn't complete successfully and had errors:
2017/03/28 09:28:38 machine readable: qemu,error []string{"Script exited with non-zero exit status: 1"}
2017/03/28 09:28:38 ui error: --> qemu: Script exited with non-zero exit status: 1
2017/03/28 09:28:38 ui:
==> Builds finished but no artifacts were created.
2017/03/28 09:28:38 waiting for all plugin processes to complete...
Build 'qemu' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> qemu: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
2017/03/28 09:28:38 /opt/Packer/Packer/centos/packer: plugin process exited
2017/03/28 09:28:38 /opt/Packer/Packer/centos/packer: plugin process exited

Json:
{

  "builders":
  [
    {
      "type": "qemu",
      "iso_url": "/opt/Packer/Packer/centos/CentOS-7.0-1406-x86_64-DVD.iso",
      "iso_checksum": "154ba47b7a37e52e0100310c3aeb8f9d9daf4806",
      "iso_checksum_type": "sha1",
      "output_directory": "/opt/Packer/Packer/centos/centos70_kobe_redis",
     
      "disk_size": 20000,
      "format": "qcow2",
      "headless": false,
      "accelerator": "kvm",
      "http_directory": "qemu",
      "http_port_min": 10082,
      "http_port_max": 10089,
      "ssh_host_port_min": 2222,
      "ssh_host_port_max": 2229,
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_port": 22,
      "ssh_wait_timeout": "60000s",
      "vm_name": "centos70_x86_64_redis.qcow2",
      "net_device": "virtio-net",
      "disk_interface": "virtio",
      "boot_wait": "5s",
      "shutdown_command": "echo 'vagrant'|sudo -S /sbin/halt -h -p",
      "boot_command":
      [
         "<tab>  ks=http://192.168.99.54:8080/qemu/centos70-ks.cfg<enter><wait>"
      ]
    }
  ],
  "provisioners":
    [{
      "type":"shell",
      "binary":"true",
      "inline":[
         "sleep 30",
         "echo 'start yum update' ",
         "sudo yum update -y",
         "echo 'end yum update' ",
         "sudo yum install -y redis-server"
      ]
  }]
}

Could any one can give me any hint?
Many thanks!

**Comment by rickard-von-essen** [comment]
Your VM doesn't have network connectivity.

---

Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
