### ISSUE TITLE
How could the provisioners section access the internet? From the host platform or from the installed image itself?

### ISSUE THREAD

**Issue by KobeWangBeabloo** [mitchellh/packer#4721]
As the title says， could any one can help to answer?

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
