### ISSUE TITLE
Could kickstart file(within the json template) can be accessed from local path instead of http url?

### ISSUE THREAD

**Issue by KobeWangBeabloo** [mitchellh/packer#4722]
As title says, we can see that all the kickstart file are accessed by http url。
 "boot_command":
      [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos6-ks.cfg<enter><wait>"
      ]

Could we access the ks file from a local path cause will need extra effort to deploy a http or application server like apache or tomcat？ Change the path from http url like below?
"boot_command":
      [
        "<tab> text ks=/home/tmp/ks/centos6-ks.cfg<enter><wait>"
      ]

**Comment by rickard-von-essen** [comment]
Yes in general, see the [kickstart docs](https://www.centos.org/docs/5/html/Installation_Guide-en-US/ch-kickstart2.html).

---

Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
