### ISSUE TITLE
Hi, There is a requirement in my company to use the command line to generate ova from a pxe image for deployment in an ESXi host. Is this possible using Packer?

### ISSUE THREAD

**Issue by suprajasridhar** [mitchellh/packer#4738]
**DELETE THIS TEMPLATE BEFORE SUBMITTING**

_Only use Github issues to report bugs or feature requests, see https://www.packer.io/community/_

If you are planning to open a pull-request just open the pull-request instead of making an issue first.

FOR FEATURES:

Describe the feature you want and your use case _clearly_.

FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by mwhooker** [comment]
It may be best to ask this question on the mailing list. You can see more options for getting help here https://www.packer.io/community/

This sounds like it should be possible. Have a look at this page https://www.packer.io/docs/builders/vmware-iso.html
