### ISSUE TITLE
Retryable error: use of closed network connection on RC2

### ISSUE THREAD

**Issue by mafrosis** [mitchellh/packer#4742]
I'm seeing failures due to the following under RC2:

    Retryable error: Error removing temporary script at /tmp/script_33.sh: close tcp 172.16.8.1:56315->172.16.8.138:22: use of closed network connection

Full log:
https://gist.github.com/mafrosis/dca17dded8cb6ec86c719a3c9f407b83

Host system is OSX, builder is VMWare. Packer config here:
https://github.com/mafrosis/boxcutter-debian/blob/mafrosis-uk/debian.json

**Comment by mwhooker** [comment]
Thanks for reporting this. It's fixed in master and will make a new rc.
