### ISSUE TITLE
tests: FAIL in github.com/mitchellh/packer/packer/rpc

### ISSUE THREAD

**Issue by danstender** [mitchellh/packer#4750]
Hi,
we have a randomly occurring test failure here:
```
=== RUN   TestPostProcessorRPC
panic: Fail in goroutine after TestMuxBroker has completed
goroutine 308 [running]:
panic(0x87a720, 0xc4201436a0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
testing.(*common).Fail(0xc42016c900)
        /usr/lib/go-1.7/src/testing/testing.go:412 +0x11f
testing.(*common).FailNow(0xc42016c900)
        /usr/lib/go-1.7/src/testing/testing.go:431 +0x2b
testing.(*common).Fatalf(0xc42016c900, 0x9442f3, 0x7, 0xc42019bf70, 0x1, 0x1)
        /usr/lib/go-1.7/src/testing/testing.go:496 +0x83
github.com/mitchellh/packer/packer/rpc.TestMuxBroker.func1(0xc420344a40, 0xc42016c900)
        /<<BUILDDIR>>/packer-0.10.2+dfsg/obj-x86_64-linux-gnu/src/github.com/mitchellh/packer/packer/rpc/
mux_broker_test.go:27 +0x140
created by github.com/mitchellh/packer/packer/rpc.TestMuxBroker
        /<<BUILDDIR>>/packer-0.10.2+dfsg/obj-x86_64-linux-gnu/src/github.com/mitchellh/packer/packer/rpc/
mux_broker_test.go:29 +0x281
exit status 2
FAIL    github.com/mitchellh/packer/packer/rpc  0.124s
```
What's going wrong here? The packer version for Debian 9 is 0.10.2 (newer versions will be available through backporting).

Thanks,
Dan Stender

**Comment by rickard-von-essen** [comment]
Please see if you can reproduce this with latest master.

**Comment by danstender** [comment]
... it's hardly reproducible at all since it's randomly appearing. Not packaging master, but thanks for any hints.

**Comment by rickard-von-essen** [comment]
What version of Go are you using?

**Comment by danstender** [comment]
... 1.7, a build log where this appeared is here:
https://buildd.debian.org/status/fetch.php?pkg=packer&arch=armhf&ver=0.10.2%2Bdfsg-3%2Bb1&stamp=1489747066&raw=0

I've checked, it seems the relevant files packer/rpc/mux_broker{,_test}.go appear to haven't
changed since a long time resp. not significant
(https://github.com/mitchellh/packer/commits/master/packer/rpc/mux_broker.go)

DS

**Comment by mwhudson** [comment]
The test fails about 2% of the time for me with Go 1.8.
