### ISSUE TITLE
Error When Building an AWS AMI with Packer in an AWS-CLI configured Environment

### ISSUE THREAD

**Issue by saedalav** [mitchellh/packer#4751]
Attempting to create an AWS AMI in RHEL 7 when AWS ACCESS KEY and AWS SECRET ACCESS KEY is read from environment variable leads to the following error: 

```
--> amazon-ebs: Error querying AMI: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXX\r/YYYMMDD/us-east-1/ec2/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=XXXXXXXXXXXXXXXXXXXXXXXXX" for key Authorization
```

Looks like the issue is related to the "\r" inserted after the access ID in AWS signature. 

- Packer version: 0.12.3
- Host platform: Red Hat Enterprise Linux Server Release 7.3 (Maipo)
- https://gist.github.com/saedalav/83c95ab3036e4f730553ac3c15745acd

**Comment by mwhooker** [comment]
Make sure there's no `\r` in the environment.

Can you tell me the output of `echo $AWS_ACCESS_KEY_ID | grep -q "\r"; echo $?` is?

**Comment by saedalav** [comment]
To my understanding, there is no \r in the environment. 

$? returns a non-zero (1). 

Besides env vars, I also checked into .aws/credentials and that also contains no \r

**Comment by mwhooker** [comment]
hmm, I would still investigate the data. My next debugging step might be to run `env -i AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... packer build config.json`.

I would also rename `~/.aws` if you have anything there, just to make sure the config only comes from the environment

**Comment by saedalav** [comment]
running the command with env -i worked just fine which means packer was able to read from .aws/credentials just fine. 

I then ran "env > env.txt ;  vim env.txt" and noticed the following: 
AWS_ACCESS_KEY_ID = XXXXXXXXXXX^M 
AWS_SECRET_ACCESS_KEY = XXXXXXXXXX^M

Not sure where those came from and they weren't obviously showing up with cat and env variables. 

Thanks!

**Comment by mdinos** [comment]
For anyone else who comes across this, I solved this problem by removing all files from ~/.aws/cli/cache.
