### ISSUE TITLE
amazon-chroot: empty copy_files is ignored

### ISSUE THREAD

**Issue by mercora** [mitchellh/packer#4755]
When using the amazon-chroot provisioner (Packer v0.12.3 on Ubuntu 16.10) setting copy_files to an empty list/array like suggested in the documentation does not affect the default. So instead of skipping the CopyFiles step "/etc/resolv.conf" is copied and later removed again.

I am pretty sure it is because the code cannot tell if the array is empty or nil because it will be essentially the same when [0]comparing with nil, but i only took a quick glance at the code and am not sure about the details.

[0] https://github.com/mitchellh/packer/blob/master/builder/amazon/chroot/builder.go#L101

----
Now i have to copy a dummy file in order to prevent ending up with an AMI without any working resolv.conf file. Even worse, the documentation did not make it clear that copied files will be deleted on cleanup which was quite confusing at first. In fact, when reading about copy_files i had the impression it is used to copy files to the new AMI (that is, permanently).

---
I also think a better approach could be to bind mount the hosts resolv.conf because it could change anytime in between and render the chroot without a working nameserver anyhow. However, i personally would not like that to be the default. Actually i doubt such a default makes sense at all, but that might be just my opinion.

In a related note: it could be rather useful to have the ability to not cleanup the files. Either through a switch or a separate variable.

**Comment by mercora** [comment]
I just noticed the latest commit on that file introduced the option to skip copy_files first. So it might be working on the latest RC. However, the documentation should either mention  when it is or was available or only reflect the current release.

**Comment by mwhooker** [comment]
@mercora thanks for reporting this. That definitely should not be live on the docs if it's not released. I'll investigate a bit how that happened so it doesn't happen again. I think it might have went out when we were updating our styles recently.

The 1.0 release is going out which will have that change in it
