### ISSUE TITLE
RC on windows?

### ISSUE THREAD

**Issue by wickedviking** [mitchellh/packer#4756]
I appologize, this really isn't a bug but a general question. I know that's bad form, but I can't find another way to ask. How can I use Packer 1.0.0 RC3 on windows?

**Comment by wickedviking** [comment]
and just like that, i figured it out....

https://www.packer.io/downloads.html

The link on that page should s/older/other

**Comment by mwhooker** [comment]
yeah that wording should be changed since it can reference RCs. Thanks!
