### ISSUE TITLE
Cannot provision AWS Windows images

### ISSUE THREAD

**Issue by tdhite** [mitchellh/packer#697]
I have to admit -- it might be possible, but I cannot currently see a reasonable way to configure Windows images with any provisioners.

To do anything at all, SSH has to be loaded, which is fine -- just bake OpenSSH in to an instance, add users / keys to the OpenSSH installation, and create and AMI from it.

After that, though -- Packer creates new keys (temporary) which it uses for SSH connections to the instance. Those *never* will exist in the OpenSSH install, obviously. Further, the AWS builder refuses to use ssh_password, and does not accept a ssh_keypair or anything that it should use instead of the temporary one (that would work as well).

In any event -- what am I missing? If this is true, I can fix the builder, but don't want to jump down that tunnel 'til I get my brains straight.

??

**Comment by yunlzheng** [comment]
It's same as build windows image on private openstack.
In my option the other way to handle this is add ssh_password availiable for the template.
In my case, the openstack base image already have a default ssh username and password.

**Comment by mefellows** [comment]
As per Dylans' comment above, [Packer Community](https://github.com/packer-community/packer-windows-plugins) now supports the Amazon EBS provisioner (amongst other plugins) for Windows natively without the need for SSH.
