### ISSUE TITLE
Local Shell Provisioner

### ISSUE THREAD

**Issue by defunct73** [mitchellh/packer#770]
Would it be possible to enhance the shell provisioner to optionally run locally? The use case is that when creating amazon AMIs, before the instance is turned into an AMI, I need to perform a system scan. This scan cannot be run from the instance itself, though.

Currently, packer creates the AMI, then another proesses creates an instance from the AMI, performs the scan, if succesfully the AMI gets copied out to various regions, otherwise it's deregistered.  It would be nice to completely eliminate the second step and use packer's ami_copy feature.

Thanks for consideration!

**Comment by makered** [comment]
+1

**Comment by jszwedko** [comment]
:+1:

**Comment by jszwedko** [comment]
Stumbled upon this custom provisioner: https://github.com/shaunduncan/packer-provisioner-host-command

**Comment by salizzar** [comment]
+1

**Comment by gildas** [comment]
There is a plugin already for that:
vagrant plugin install vagrant-host-shell

Been happy with it for quite some time.
