### ISSUE TITLE
SSH authentication using SSH agent

### ISSUE THREAD

**Issue by dottedmag** [mitchellh/packer#828]
Packer seems not to support SSH agent as an authentication source.

While this is not a common scenario for Packer workloads, it is useful in the following configuration:
* Public keys are stored in repository
* Encrypted private keys are stored in repository
* Build process is bootstrapped by starting long-living SSH agent and loading private keys into it.

This scheme has the property of not storing unencrypted private keys nor passwords, and access to SSH agent may be restricted as necessary as well.

**Comment by mitchellh** [comment]
Oh, this is done! I don't have an issue number, but this is on master.

**Comment by tamsky** [comment]
I'm trying to track down this feature and where it was added.
I'm guessing support would have been added via a code change in the gossh library.
Can you confirm?

**Comment by iamdefn** [comment]
I've been trying to get packer to use my ssh-agent to authenticate but no success.  I got it to work for vagrant and ssh, tho.  I wonder if the ssh-agent support added to Packer was just ssh-agent forwarding.

**Comment by timvisher** [comment]
I can't get this to work, either.

```
🐚  packer -v; sw_vers
0.10.0
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65
```

I can clone my repo locally and inside vagrant instances, etc. but the packer instance can't get to it at all.

Anything I can provide to help debug this?
