### ISSUE TITLE
Add ability to apply tags to an AMI's ELB snapshot

### ISSUE THREAD

**Issue by nickrw** [mitchellh/packer#846]
The amazon-ebs provisioner already has a feature to apply tags to the images packer produces, but it does not apply tags to the ELB snapshot which is produced alongside the AMI.

A provisioner option "snapshot_tags" or similar would be useful to help organise snapshots within an account - especially as snapshots are not deleted with their dependent AMIs.

**Comment by riccardofreixo** [comment]
+1, would be really handy in cleaning up old snapshots

**Comment by janaz** [comment]
+1 - tagged EBS volumes will make it easier to analyse the AMI related costs in tools like Cloudability

**Comment by mdub** [comment]
+1. Please merge!

**Comment by vogxn** [comment]
+1 - Been a year now, please merge this? very useful for tracking AWS costs like @janaz mentioned

**Comment by acaire** [comment]
Just ironing out a few issues with the test I wrote for this feature, encountering a race condition when deleting snapshots - Hope to have it sorted soon :)

**Comment by otakup0pe** [comment]
:+1: :sparkling_heart:

**Comment by arothian** [comment]
+1. This would help simplify our AMI cleanup scripts.

**Comment by tgolly** [comment]
+1.  This would be extremely useful.

**Comment by tusharm** [comment]
+1..waiting for it.

**Comment by VladRassokhin** [comment]
+1 for tags and for snapshot name (now it's hard to distinguish snapshots for different runs of packer)
Also tag 'For-AMI'(or something similar) with AMI id would be helpful.

**Comment by catsby** [comment]
This should be addressed in #2212
