### ISSUE TITLE
Target Playbook path should be configurable

### ISSUE THREAD

**Issue by dregin** [mitchellh/packer#853]
To allow playbooks transferred to the root of the staging directory as described on the ansible best practise page here:

http://docs.ansible.com/playbooks_best_practices.html

**Comment by tamsky** [comment]
I'd like the opposite to be possible, namely for no playbooks to be copied to the root of the staging directory.  (Admittedly against best practices, but to each their own.)

Currently, one file (the required argument for the ansible-local provisioner) `playbook_file` is copied to the root of the staging directory, and the rest to `staging_dir/playbooks`.  This breaks my world.

I need packer to copy `playbook_file` to `staging_dir/playbooks/$playbook_file` and run `ansible-playbook` with that `playbooks/$playbook_file` as its runtime argument.

**Comment by mwhooker** [comment]
Hi folks,

I'm fairly agnostic about what changes get made to the ansible provisioner. I would like for someone from the community to decide on the approach, and then submit a PR to resolve the issue.

However, this is not something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
