### ISSUE TITLE
Add network mapping options to vsphere post-processor for multiple NICs

### ISSUE THREAD

**Issue by sairez** [mitchellh/packer#857]
It is possible, via vmx_data, to add multiple NICs to an ovf during a vmware-iso build.  With ovftool, using the --net flag allows the mapping of multiple NICs to multiple networks.  However, right now the vsphere post-processor assumes only one NIC when translating options to the ovftool command line, using the --network flag.  

I think it'd be great to be able to do the following:

Set up more than one NIC in the vmx_data portion of the builder

``` json
      "vmx_data": {
        "ethernet0.present": "true",
        "ethernet0.virtualdev": "e1000",
        "ethernet0.startConnected": "true",
        "ethernet0.networkName": "primary",
        "ethernet1.present": "true",
        "ethernet1.virtualdev": "e1000",
        "ethernet1.startConnected": "true",
        "ethernet1.networkName": "secondary"
      }
```

and use vm_network_map instead of vm_network in the post-processor config

``` json
    "post-processors": [
      {
        "type": "vsphere",
        "cluster": "cluster-01",
        "datacenter": "datacenter-01",
        "datastore": "datastore-01",
        "host": "host-01",
        "resource_pool": " ",
        "username": "username",
        "password": "password",
        "vm_folder": "Templates",
        "vm_name": "sample-vm",
        "vm_network_map": ["\"primary\"=\"VM Network\"","\"secondary\"=\"Storage\""]
        "insecure": true
      }
    ]
```

which would translate to an ovftool commandline like:

```
    ovftool --noSSLVerify=true \
      --acceptAllEulas \
      --name=sample-vm \
      --datastore=datastore-01 \
      --net:"primary"="VM Network" \
      --net:"secondary"="Storage" \
      --vmFolder=Templates output-vmware-iso/sample-vm.vmx \
      vi://username:password@host-01/datacenter-01/host/cluster-01/Resources/
```

**Comment by JoelBCarter** [comment]
Is there any workaround for adding this functionality as currently I find myself in need of adding two NICs?

**Comment by mrjcleaver** [comment]
Or any workaround?

**Comment by rickard-von-essen** [comment]
Packer relies heavily on community contributions. PR's are welcome.

**Comment by mrjcleaver** [comment]
http://techdebug.com/blog/2015/09/16/packer-vmware-iso-builder-esxi-without-dhcp/ is one workaround. They ran a script afterwards. Not as nice.

**Comment by mrjcleaver** [comment]
It looks like the code that does the (presently only one network) work is at https://github.com/mitchellh/packer/blob/f65465bbb1406e864c6bec6671073f7d3e12c10e/post-processor/vsphere/post-processor.go#L161

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
