### ISSUE TITLE
Enable amazon-chroot root volume resize

### ISSUE THREAD

**Issue by njsaunders** [mitchellh/packer#865]
Looking at issue #188 it seems like the ability to resize the root volume has been added to the amazon-ebs provisioned - Would it be possible to add similar capabilities to the amazon-chroot provisioner? It would be _incredibly_ useful.

**Comment by catsby** [comment]
Hello – I just merged https://github.com/mitchellh/packer/pull/2289 , which has some general fixes for chroots as well as supporting a new config option `root_volume_size`, which should provide what you're looking for. If you can, please test it out and let me know!

**Comment by petewilcock** [comment]
Sorry to comment on an old issue. If `root_volume_size` is supported by the `amazon-ebs` builder could you document it? It's not currently in the docs for that builder.

**Comment by rickard-von-essen** [comment]
@petewilcock You can just use `ami_block_device_mappins`. E.g.

```json
            "ami_block_device_mappings": [{
                "device_name": "/dev/sda1",
                "volume_size": 20,
                "volume_type": "gp2",
                "delete_on_termination": "true"
            }],
```
