### ISSUE TITLE
InvalidPermission.Duplicate when creating temporary AWS security group

### ISSUE THREAD

**Issue by mdub** [mitchellh/packer#878]
Using Packer 0.5.1, and the amazon-ebs builder, I'm seeing errors of the form:

```
--> amazon-ebs: Error creating temporary security group: the specified rule "peer: 0.0.0.0/0, TCP, from port: 22, to port: 22, ALLOW" already exists (InvalidPermission.Duplicate)
```

It's not happening consistently, so may indicate a race-condition.

**Comment by ckelner** [comment]
I got this on 0.7.1  on amazon linux `Linux version 3.2.34-55.46.amzn1.x86_64 (mockbuild@gobi-build-31003) (gcc version 4.6.2 20111027 (Red Hat 4.6.2-2) (GCC) )`

```
1422553612,,ui,say,==> amazon-ebs: Creating temporary keypair: packer 54ca720c-7215-2052-3591-b7f155ae4299
1422553612,,ui,say,==> amazon-ebs: Creating temporary security group for this instance...
1422553612,,ui,say,==> amazon-ebs: Authorizing SSH access on the temporary security group...
1422553623,,ui,error,==> amazon-ebs: Error creating temporary security group: The permission '0.0.0.0/0-1-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)
1422553623,,ui,say,==> amazon-ebs: Deleting temporary security group...
1422553623,,ui,say,==> amazon-ebs: Deleting temporary keypair...
1422553623,,ui,error,Build 'amazon-ebs' errored: Error creating temporary security group: The permission '0.0.0.0/0-1-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)
1422553623,,error-count,1
1422553623,,ui,error,\n==> Some builds didn't complete successfully and had errors:
1422553623,amazon-ebs,error,Error creating temporary security group: The permission '0.0.0.0/0-1-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)
1422553623,,ui,error,--> amazon-ebs: Error creating temporary security group: The permission '0.0.0.0/0-1-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)
1422553623,,ui,say,\n==> Builds finished but no artifacts were created.
```

**Comment by wvega** [comment]
I'm seeing this on Packer 0.7.5 running on OS X Yosemite. I was trying to create a new AMI based on AMI I had generated with packer just a few minutes before:

```
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing SSH access on the temporary security group...
==> amazon-ebs: Error creating temporary security group: The permission '0.0.0.0/0-tcp-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error creating temporary security group: The permission '0.0.0.0/0-tcp-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error creating temporary security group: The permission '0.0.0.0/0-tcp-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)

==> Builds finished but no artifacts were created.
```

As with the other cases reported here, it doesn't happen all the time.

**Comment by volker48** [comment]
I just got this error as well in Packer v0.7.5 on OS X Yosemite.

```
amazon-ebs output will be in this color.

==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 557f31f1-5928-f518-53e5-1ea6529e9ea1
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing SSH access on the temporary security group...
==> amazon-ebs: Error creating temporary security group: The permission '0.0.0.0/0-tcp-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error creating temporary security group: The permission '0.0.0.0/0-tcp-22-22' has already been authorized on the specified group (InvalidPermission.Duplicate)
```

**Comment by WyseNynja** [comment]
I just got this error with packer 0.8.3.

I don't think this has been properly fixed :(

**Comment by adimarco** [comment]
This is definitely still happening with packer 0.8.5 on Amazon Linux

==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-56862632' does not exist in VPC 'vpc-65a13300'

**Comment by cbednarski** [comment]
@adimarco It looks to me like you have a different issue. Your error message is completely different. If you believe this is a bug, please open a new issue.

**Comment by adimarco** [comment]
@cbednarski Sorry, I meant to leave that comment in #1322.  It was closed as a duplicate of this issue, however, and I see the same error message I'm getting in 3 other posts in this issue, so I thought might be related.  I'll open a new issue.

**Comment by cbednarski** [comment]
From @phinze

> Build 'amazon-ebs' errored: Error creating temporary security group: InvalidPermission.Duplicate: The permission '0.0.0.0/0-tcp-22-22' has already been authorized on the specified group
    status code: 400, request id: []

We should probably catch and ignore this issue since I think the system is in a state where it can continue in spite of the error.

**Comment by brikis98** [comment]
Just got this with 0.8.6:

```
==> my-ami: Prevalidating AMI Name...
==> my-ami: Inspecting the source AMI...
==> my-ami: Creating temporary keypair: packer xxxx-xxxx-xxxx-xxxx-xxxxx
==> my-ami: Creating temporary security group for this instance...
==> my-ami: Authorizing access to port 22 the temporary security group...
==> my-ami: Launching a source AWS instance...
==> my-ami: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-f635fd8d' does not exist in VPC 'vpc-1111f778'
==> my-ami:   status code: 400, request id: []
==> my-ami: No AMIs to cleanup
==> my-ami: Deleting temporary security group...
==> my-ami: Deleting temporary keypair...
Build 'my-ami' errored: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-f635fd8d' does not exist in VPC 'vpc-1111f778'
  status code: 400, request id: []
```

**Comment by pporada-gl** [comment]
Packer 0.10.1 on Atlas here
```
Packer v0.10.1

amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer XXX-YYY-XXX-YYYY-XXXYYY
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-2557845e' does not exist in VPC 'vpc-6882c00c'
==> amazon-ebs: 	status code: 400, request id:
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-2557845e' does not exist in VPC 'vpc-6882c00c'
	status code: 400, request id: 

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-2557845e' does not exist in VPC 'vpc-6882c00c'
	status code: 400, request id: 
```

**Comment by gauravChaturvedi** [comment]
Getting the following 

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 573cae9f-f6e5-ba08-dc3a-d68aa1e345d3
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-3d36ea46' does not exist in VPC 'vpc-50b94137'
==> amazon-ebs: 	status code: 400, request id: []
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary security group...
^C==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-3d36ea46' does not exist in VPC 'vpc-50b94137'
	status code: 400, request id: []

**Comment by Tonesbalones** [comment]
Same issue as commented above, running packer version 0.10.1 on AWS Linux.

**Comment by cbednarski** [comment]
According to some comments in #2606 this may happen when there is an API outage. Even if this is not the root cause these issues are likely related.

**Comment by Tonesbalones** [comment]
Agreed, if I retry a minute or so later it runs with no errors. Thanks for the link to #2606!

**Comment by michaeltlombardi** [comment]
All - is this issue still ongoing? From the sounds of the conversations in May, it seems like this issue can be closed?

**Comment by mwarkentin** [comment]
@michaeltlombardi I'm still seeing the `Error launching source instance: InvalidGroup.NotFound: The security group 'sg-216d3b5b' does not exist` error every so often.

**Comment by ryanrupp** [comment]
Are you using the current master of Packer? I don't think the fix from here https://github.com/mitchellh/packer/pull/3656 has been cut into a release yet, 0.10.1 was cut before the fix and 0.10.2 was cut last week but doesn't look like it includes that fix.

**Comment by mwarkentin** [comment]
I'm using 0.10.2 now, from homebrew.

**Comment by rickard-von-essen** [comment]
@mwarkentin @ryanrupp 0.10.2 contains exactly the same code as 0.10.1 it was just rebuilt to support macOS Sierra.

**Comment by laneatomic** [comment]
This happens for us both through the homebrew version and the compiled version from the Packer site. This is definitely still an issue.

**Comment by mwhooker** [comment]
might be able to solve this with something like #3938

**Comment by mwhooker** [comment]
@laneatomic Can you confirm which error you're getting? Is it 

`InvalidGroup.NotFound` or `InvalidPermission.Duplicate`?

**Comment by mwhooker** [comment]
was able to reproduce the `InvalidGroup.NotFound` error. I created an issue to track it. #4368

I'm going to close this since I believe the `InvalidPermission.Duplicate` error has been resolved. Please feel free to re-open if anyone is still getting this error with the latest build of packer. CC @laneatomic

**Comment by laneatomic** [comment]
Unfortunately I can no longer test this error. We refactored how we use Packer in a way to avoid this entirely.

**Comment by jgillard** [comment]
Have just come across this on 0.12.2

```
==> amazon-ebs: Prevalidating AMI Name...
    amazon-ebs: Found Image ID: ami-512ffc47
==> amazon-ebs: Creating temporary keypair: packer_58b018eb-1577-525a-a81e-af7530a99da8
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Error creating temporary security group: InvalidPermission.Duplicate: The permission '0.0.0.0/0-tcp-22-22' has already been authorized on the specified group
==> amazon-ebs: 	status code: 400, request id: b95f46ab-1eef-48e3-8485-6737bef71d3f
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error creating temporary security group: InvalidPermission.Duplicate: The permission '0.0.0.0/0-tcp-22-22' has already been authorized on the specified group
	status code: 400, request id: b95f46ab-1eef-48e3-8485-6737bef71d3f
```

**Comment by cbednarski** [comment]
@jgillard Please open a new issue for this. Thanks!
