### ISSUE TITLE
Support templating in the built-in http server

### ISSUE THREAD

**Issue by jameskyle** [mitchellh/packer#908]
It would be very convenient to support templates in the built-in http server. I use templates quite extensively for provisioning. It allows me to have one file with conditional includes or target specific variables that I inject.

Templates really increase the flexibility of a provisioning system. For example, the following pattern is very common in my packer templates:

```json
      "boot_command": [
        "<esc>",
        "<wait>linux ks={{ user `host` }}/debian/preseed?proxy={{ user `proxy` }}&release=wheezy<enter>"
      ],
```

Or.

```json
    {
       "inline": [
         "mkdir -p {{ user `workdir` }}",
         "wget -qO- '{{ user `host` }}/debian/post_install?release=saucy' > {{ user `workdir` }}/post_install.sh",
         "chmod +x {{ user `workdir` }}/post_install.sh",
         "echo '{{ user `ssh_pass` }}' | sudo -S bash {{ user `workdir` }}/post_install.sh"
       ],
       "only": [
         "ubuntu-13.10-server-amd64"
       ],
       "type": "shell"
     },
```

**Comment by schmkr** [comment]
Thanks @rasa for sharing. 
I think it would already help a lot if this tip was mentioned in the documentation.

**Comment by mitchellh** [comment]
Dup of #1673. I know thats newer but it has some more detail. :)
