### ISSUE TITLE
Build fails when packer sees an "only" provisioner for an inactive builder

### ISSUE THREAD

**Issue by jjongsma** [mitchellh/packer#931]
Packer should ignore "only" provisioner restrictions that don't apply to the current builder set rather than failing the build.

We have some common provisioners for different "building blocks" that are used in multiple server images. Some of these provisioners require special steps for some conatiners (i.e. Docker needs some apt-get workarounds to avoid throwing errors from missing init.d scripts).

If I use these provisioner snippets in server builds that do NOT target Docker, the entire build fails because it's missing the "docker" builder. Packer should just ignore steps that don't apply to active builders.

**Comment by mitchellh** [comment]
This is fixed!
