### ISSUE TITLE
RackSpace with RackConnect fails to connect via SSH

### ISSUE THREAD

**Issue by carcus88** [mitchellh/packer#952]
When a server is provisioned on RackSpace with via OpenStack and that customer is using "RackConnect" (RackSpace's internal cloud to dedicated connection technology) the IP address that is returned via the OpenStack API is not the real public facing IP address and will cause packer to fail. 

From what I have gathered so far the meta data should be examined and if RackConnect is being used the real IP address should be gathered from the meta data. 

A typical meta data string on a RackConnected instance will look like this

    {"rackconnect_automation_feature_manage_software_firewall": "ENABLED", "rackconnect_automation_feature_provison_public_ip": "ENABLED", "rackconnect_automation_status": "DEPLOYED", "rackconnect_automation_feature_configure_network_stack": "ENABLED"}

If needed I can create a user under my account for development or be available for testing.

**Comment by tdooner** [comment]
Hey @carcus88, I know this is a blast from the past, but we need this too so I just took a stab at implementing this in https://github.com/mitchellh/packer/pull/1925. We'll see how it fares in the test suite and code review (it's my first Go commit).
